### ISSUE TITLE
Design user profile interface

### ISSUE THREAD

**Issue by tobscure** [flarum/core#10]
This is subject to the finalization of #1.

The user profile interface needs to be mocked up.

The title area should contain at least the avatar, username, and possibly some other stuff. The background of the title area could potentially be an average color from their avatar (like in iTunes)? Otherwise it can default to the primary/secondary color, depending on the header mode.

Other stuff that needs to be included, either in the title area or just below it:
- Short bio
- Group icons
- Last active, joined
- Basic stats (number of posts, discussions)

Then there will be a content area with a sidebar:
- **Activity:** display more of the user’s recent activity
- **Discussions:** display the user’s most recent discussions
- **Posts:** display the user’s most recent posts

**Comment by tobscure** [comment]
Will look something like this:

![user](https://cloud.githubusercontent.com/assets/128862/5772637/82ac613c-9da5-11e4-84df-728b05cf2eb2.png)

**Comment by RugWarrior** [comment]
+1

**Comment by randsonjs** [comment]
+1
