### ISSUE TITLE
Docs are outdated on extensions

### ISSUE THREAD

**Issue by Mortiferr** [flarum/core#1000]
Docs are outdated on how to create an extension. Docs say just put it in the extensions folder but doesn't exist in my installation. @dav-is confirmed on Gitter.

**Comment by franzliedke** [comment]
Thanks for the heads-up! We'll be sure to bring them up to par for the next release.

**Comment by Mortiferr** [comment]
I'd like to bump: extension documentation is still not very good or descriptive.

**Comment by issyrocks12** [comment]
Is this still not done? I'd be more than happy to assist in writing some of it.

**Comment by tobscure** [comment]
We'll be completely rewriting the extension API soon so this has to wait until (and will be a priority) after that.

**Comment by dav-is** [comment]
I think someone new on the forums was working on it. I'd check the forks of the docs on GitHub to see what he's done so far (I think they're in GitHub somewhere aren't they?).

**Comment by jordanjay29** [comment]
@Arkinn is our new doc writer who has been diligently updating all our docs. He and I will be working on extensions documentation after his current project is finished @dav-is.

**Comment by romanzpolski** [comment]
Hi Guys,
is there still no docs on how to build extension ?
I tried google and different blogs/forums but it seems none of exisiting examples are up to date.

Please let me know

Thanks

**Comment by luceos** [comment]
You might want to look at [this thread](https://discuss.flarum.org/d/1662-extension-developer-first-read) it's a collection of helpful information. In addition I'd recommend hanging out on gitter or discord chat, the best guidance you will get is from fellow extension developers.

**Comment by romanzpolski** [comment]
Thanks @luceos for your quick reply :)
Problem is my freshly downloaded version of Flarum does not contain "extensions" folder anywhere.
So it looks like I ran to the same issue as the author of this topic.

**Comment by Mortiferr** [comment]
Yep, same issue still occurs.

**Comment by romanzpolski** [comment]
did any one figure out how to go about it ?

thanks @Mortiferr

**Comment by luceos** [comment]
@romanzpolski yes you need to apply the workbench method as listed in the thread i mentioned above. I seriously recommend you read through all of these links before attempting to write an extension.

Here's the direct link: https://discuss.flarum.org/d/1608-extension-development-using-composer-repositories-path

**Comment by romanzpolski** [comment]
@luceos this workbench method doesnt work for me either, I will try again.

Thanks

**Comment by Mortiferr** [comment]
I tried following those threads and they didn't seem to work for me either, but I'm quite a beginner, so maybe it's my fault.

Regards,

Patrick Black, Jr.
Web Developer and Photographer
patrickblackjr.com

On Sep 13, 2017, 10:18 AM -0500, romanzpolski <notifications@github.com>, wrote:

@luceos<https://github.com/luceos> this workbench method doesnt work for me either, I will try again.

Thanks

**Comment by romanzpolski** [comment]
this works for me now:

 https://discuss.flarum.org/d/1608-extension-development-using-composer-repositories-path

**Comment by TurboProgramming** [comment]
Any updates about this? Shouldn't this be closed if its done?

**Comment by Mortiferr** [comment]
I haven’t tried again since then. Can someone confirm?

--

On Saturday, May 05, 2018 at 11:34 AM, Arda Çebi <notifications@github.com<mailto:notifications@github.com>> wrote:

Any updates about this? Shouldn't this be closed if its done?

**Comment by ardacebi** [comment]
@CDK2020 Umm, so shouldn't this be removed from the milestone? 🤔

**Comment by tobscure** [comment]
New extension docs for b8 are done: https://flarum.org/docs/extend/

Still incomplete, but far better than previously!
