### ISSUE TITLE
deleting a primary tag with children results in forum breaking

### ISSUE THREAD

**Issue by niv** [flarum/core#1014]
Deleting a primary tag that has child tags results in the forum breaking with a PHP error.

Version affected: latest from --stability=beta as of this ticket (0.1.0-b5 ?)

Steps to repro:
* Create primary tag
* Create child tag under primary tag
* Delete primary tag

Database now contains a invalid parent reference (in tags.parent_id), and the subsequent lookup fails in /vendor/flarum/flarum-ext-tags/src/Tag.php:147.

**Comment by kulga** [comment]
Doesn't seem to occur in the latest dev-master. Does the gif depict the correct steps?
Tested on [Devflarum](https://discuss.flarum.org/d/697-devflarum-sandbox-server) (Feel free to trial it there)


![](http://i.imgur.com/sF4bf4s.gif)

**Comment by niv** [comment]
Hey,

that's exactly what I did. I just checked the source repo for ext-tags and it appears that it was fixed in #962.

Sorry for the noise!
