### ISSUE TITLE
Logout and 404 Error

### ISSUE THREAD

**Issue by TheIsee** [flarum/core#1015]
At the time of disconnection on Flarum, the site returns a 404 error and I'm not disconnected, I'm under Nginx.

Sorry for my english

**Comment by dav-is** [comment]
I don't understand in the slightest. Maybe some screenshots or steps to reproduce?

**Comment by giga300** [comment]
Here is : http://i.imgur.com/8rgNwEC.png

**Comment by giga300** [comment]
Step 1 - I login
Step - 2 - I disconnect 
And the website return 404 error :(

**Comment by dav-is** [comment]
Is this on your local install? Are you using any sort of caching?

**Comment by giga300** [comment]
Up :(

**Comment by franzliedke** [comment]
The 404 on logout makes me think that URL rewriting is not correctly set up.

Did you follow the instructions at http://flarum.org/docs/installation/#nginx completely? And if so, did you make any additional changes to your Nginx config?

**Comment by Luceos** [comment]
@TheIsee closing this, we need to see your nginx configuration to help you out. Feel free to re-open once you have it.
