### ISSUE TITLE
All discussions page's banner close button should only work/hide banner on login. Otherwise gone forever to user.

### ISSUE THREAD

**Issue by WriterStat** [flarum/core#1016]
Hi! First off thanks for the great software and hard work!  Cheers!

If a user closes the banner on the all discussions page. It is gone forever for them.  And causes them to ask where did it go?  Constantly and what did I do? And why? They can't help themselves, it is the only banner in the software where they can, so they wonder why and they are drawn to see what happens, like moths. 

To fix, if they close the banner. The banner should only be hidden when they log in, but displayed when they aren't yet logged in, so that they can understand what it does. Allowing them to log out to see it.

Also helping the admin.

Note: 
Having it display, when not logged in gives the user an innate indicator of what it does. Without an indicator, they wonder what else did it do, when I did that?

For banner consistency, the all discussion banner close button could for the moment be removed, until a user function can re-enable it, for site consistency.  Or an option for the admin, to disable the ability for the user. Or to turn it back on for everyone.

Thanks! 

I've talked people through removing the local storage remember, but doing this is dicey. =)

Small thing for consistency, removes user question and just nice.  Plus I'd like to use the All discussions page's banner as a changing welcome message/alert for system things, since it's the first thing they see before logging in.

Again thanks for the great software!

Example below of what user's see/wonder about:

![missing_top_info_banner_1](https://cloud.githubusercontent.com/assets/12280348/17647019/34b9bcba-61a6-11e6-8955-fc1f90089d2b.png)

**Comment by jordanjay29** [comment]
Duplicate: https://github.com/flarum/core/issues/515

**Comment by WriterStat** [comment]
Hi @jordanjay29 morning. Not a duplicate of #515. 

This is something different. It's actually a discussion of removal of the close button on the hero area/banner on the All Discussions page for now. 

Or a way to manage the close button function on the All Discussions page Hero area/banner.

A quick fix for conformity, so it conforms to the rest of the software banners/hero areas.

There's no reason I can think of to allow a user to close it for now, on a normal system. And it's one easy thing you can remove, towards a solid release base. That can be added back in if really needed later.

Hope that makes sense.

Keep up the good work, cheers!

**Comment by WriterStat** [comment]
Since my user base keeps clicking on this close button and asking how do I bring it back. It's a problem. =)))
