### ISSUE TITLE
Mention thread (#)

### ISSUE THREAD

**Issue by Cu8eR** [flarum/core#1022]
Would be nice to add this feature - something like Github - when you press # you can see list of threads which can be easily mentioned in a post. Something like this also exists for MyBB as a plugin

http://i.imgur.com/WiE0XgP.gif

**Comment by Luceos** [comment]
Hello @Cu8eR,

Thanks for sharing your thoughts, these are highly appreciated. Currently we are in the process of formalizing a bit more how we are handling bug and feature reports. Feature requests at this point should be posted on our forums under the [feedback - features](https://discuss.flarum.org/t/features) tag. Bugs can be posted here on Github.

If you would be so kind to redirect your request that, that would be appreciated.
