### ISSUE TITLE
Uglify JS in flarum-gulp, commit minified files and source maps to the repo

### ISSUE THREAD

**Issue by tobscure** [flarum/core#1024]
See flarum/flarum-gulp#2

Advantages:
- No minification required on PHP end -> better performance, especially when enabling/disabling extensions
- Don't have to rely on a third-party minifier (nullifies #887)
- Full control over minification process - less likely for installation-specific errors to occur
- Source maps! Small asset filesize even in debug mode

Disadvantages:
- Lose some of the extra compression of closure compiler
  - Could potentially still use closure compiler in flarum-gulp instead of uglifyJS?
- Have to commit minified files/sourcemaps to the repo (could result in larger diffs/repo size)
  - But we already commit unminified dist files to the repo, so it's not a huge change

**Comment by sijad** [comment]
> Could potentially still use closure compiler in flarum-gulp instead of uglifyJS?

https://github.com/google/closure-compiler-js supports gulp

**Comment by tobscure** [comment]
@franzliedke do you agree with this idea?

**Comment by franzliedke** [comment]
If it wouldn't mean that we get very ugly diffs every time, I would immediately say yes... I am slightly against it for that reason right now, but let me sleep over it.

**Comment by tobscure** [comment]
GitHub's interface will hide diffs for minified/ugly/large files, I believe.

**Comment by sijad** [comment]
only developers need source maps, right? can they build them or download them from other repo somehow?

**Comment by franzliedke** [comment]
Oh, Google's Closure Compiler is now available as JS version, too: https://developers.googleblog.com/2016/08/closure-compiler-in-javascript.html?m=1

**Comment by franzliedke** [comment]
The problem with ugly diffs is not seeing them or not seeing them, it's the size of the repo that will quickly balloon, because every small change to a JS file will mean that Git will essentially store both the old and the new version completely every time.

**Comment by UrGuardian4ngel** [comment]
Those diffs can also be suppressed using [`.gitattributes`](https://www.kernel.org/pub/software/scm/git/docs/gitattributes.html), [marking them as binary files](https://www.kernel.org/pub/software/scm/git/docs/gitattributes.html#_marking_files_as_binary). E.g.:

```
# .gitattributes
js/*/dist/*.js -diff
```

But I'm not sure in which ways this will affect the size or 'ballooning' of the repository (if at all).

**Comment by franzliedke** [comment]
If we decide to commit the minified files, then yes, we should do that. Good idea, @UrGuardian4ngel. :)

**Comment by tobscure** [comment]
Thought about this a bit more today – I think we should go ahead and do it, and commit minified files to the repo, but **not commit sourcemaps**. If someone wants to use a sourcemap they can generate it themself.

**Comment by dav-is** [comment]
Minified files are automaticly excluded from diffs so that should solve the issue of messy diffs.

**Comment by tobscure** [comment]
Maybe we can set up a bot to commit minified JS so it doesn't clutter up / cause conflicts in PRs. eg. https://github.com/lhorie/mithril.js/commits/rewrite?author=Gandalf-the-Bot

**Comment by tobscure** [comment]
Btw, here's the script that powers the bot: https://github.com/lhorie/mithril.js/blob/next/.travis.yml#L25

**Comment by gwillem** [comment]
My 2cts: minified assets are build artifacts that can be derived and should not be included in the repo.
It gets messy quick ([been there](https://github.com/gwillem/magento-malware-scanner/commits/master)).

However, the current minification system is also not ideal. 

Would it be possible to build (minify) assets upon installation? That way, if one enables/disables extensions, only the relevant (already minified) fragments would have to be concatenated.

**Comment by tobscure** [comment]
@gwillem Technically the non-minified assets (transpiled from our ES6 source) are artifacts too – they can be derived if you install NodeJS and run gulp. But we obviously can't rely on our users to be able to do that. And unfortunately [Packagist downloads code straight from GitHub repos, you can't upload pre-compiled binaries](https://github.com/composer/packagist/issues/270). So considering these limitations, this is less about principles and best practices, and more about being pragmatic.

Now we really want to move to having source maps - because it doesn't make sense to include non-minified assets in the repo for the sole purpose of debug mode (and they are extremely large/slow to download), when *all* forums will end up putting them through a minifier anyway to serve up for production. If we just include and serve minified assets + source maps all the time, then debug mode gets a lot faster, and production mode retains some JS debugging capabilities. Win-win.

No JS minifier written in PHP supports generation of source maps.

That leaves us with committing minified JS and source maps to the repo. It's not a nice solution, but unless someone can solve the [Packagist issue](https://github.com/composer/packagist/issues/270), I don't see what else we can do.

**Comment by gwillem** [comment]
Consider me convinced!

**Comment by tobscure** [comment]
@gwillem Yes, but the minification will be done by flarum-gulp (which extensions must include anyway to compile their JS) so it won't cause any inconvenience.

CSS minification will still be done by the PHP LESS compiler.

**Comment by BartVB** [comment]
@tobscure Composer doesn't need to use Packagist, therefore Github isn't strictly needed.

I get that expecting users to have gulp/npm/nodejs installed is not realistic in the PHP world. But do we expect users to run Composer? Users are not great at modifying composer.json, running Composer needs more memory than your average shared hosting environment will provide to PHP, not all users have shell access.

IMHO it would make more sense to just distribute .zip/.tgz files for core and extensions and leave the Composer/Gulp part to the (extension) developers. In that scenario minified (or even transpiled) versions don't need to be put in the Git repo.

But I have no idea if there's already a plan in place for the distribution/updating of the stable release.

**Comment by tobscure** [comment]
@BartVB The problem is that by nature, installing extensions (i.e. new code which has new dependencies) requires a complete re-calculation of the whole project's dependencies. So at the moment the attitude we're taking (and we believe the only sensible one we can take right now) is that users DO need to be able to run Composer.

We discussed this at length as a staff a while ago which you may be interested in reading through, and I'd be interested to hear if you have any further thoughts: https://discuss.flarum.org/d/4369-rfc-drop-composer-simplify-project-structure

**Comment by gwillem** [comment]
That link 404’s

**Comment by datitisev** [comment]
@tobscure You linked a contributors-only discussion 😛

**Comment by tobscure** [comment]
Yeah I know, don't want to make it public just now but we are planning to write a summary to put in the FAQ. Try again now @gwillem!

**Comment by luceos** [comment]
Summary for the choice of composer: https://github.com/flarum/docs/issues/20
