### ISSUE TITLE
post.discussion() is not a function

### ISSUE THREAD

**Issue by terabin** [flarum/core#1025]
I don't know how this error appears, just a strange thing happened.

A member anwsered my post, and notification start to give error:

post.discussion() is not a function
in:

```
/**
 * Generate a URL to a post.
 *
 * @param {Post} post
 * @return {String}
 */
app.route.post = function (post) {
  return app.route.discussion(post.discussion(), post.number());
};
```

Value of two metions notification in this time is false, so, maybe is not correctly loaded?

When I refresh the page, the first time when I open notifications, works, but when I change my page(for example, for another topic), the error appears again.

When another member anwsered the same post, the error is gone.

**Comment by felagund18** [comment]
I found this error too, mine was related to notifications
![screen shot 2016-09-04 at 2 21 30 pm](https://cloud.githubusercontent.com/assets/1384327/18229211/f80acf82-72aa-11e6-919a-c83a20499833.png)
this error was related to ```subject_id```,
after notification is saved in ```notifications```, user deleted it's post. In client side forum.js, while showing notifications, did not check if related model is exists or not... this was causing the error

**Comment by terabin** [comment]
Well, I found the cause too, but for me, makes sense delete notification about a post when the post is deleted, so, I propose this:

https://github.com/flarum/flarum-ext-likes/pull/7

**Comment by Luceos** [comment]
Link to new PR https://github.com/flarum/core/pull/1027

**Comment by franzliedke** [comment]
From [Toby's comment on one of the first PRs]():

> The notification subject type checking should be done using the Blueprint for the notification type... it might be a little complex and requires some knowledge of how the (undocumented) notification system works, so might be easier to just leave for now...

**Comment by franzliedke** [comment]
The frontend issue has been fixed. Toby will create an issue for the remaining backend cleanup.
