### ISSUE TITLE
CSS/LESS cleanup

### ISSUE THREAD

**Issue by tobscure** [flarum/core#103]
Flarum's CSS/LESS is getting a bit messy. Naming inconsistencies, Bootstrap bloat, use of non-semantic class names, etc.

1. Consider adopting a naming system like [BEM](http://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/).
2. Use LESS :extend instead of non-semantic class names (like .btn-primary etc.)
3. Consider dropping all/part of Bootstrap.

**Comment by franzliedke** [comment]
Yeah, I'm all in favor of mixins instead of non-semantic class names (currently). Those are what BEM etc. lead to, aren't they?

**Comment by tobscure** [comment]
Done
