### ISSUE TITLE
Use .jsx extension instead of .js

### ISSUE THREAD

**Issue by sijad** [flarum/core#1030]
it's not really a problem now with new modern IDE's, but it feel cleaner that way.
also helps with some linters.

**Comment by franzliedke** [comment]
Any strong opinions anyone?

From my perspective it would be fine. (I don't know about any large disadvantages, but then I don't know much about JSX anyway. Quick research did not turn up any problems.)

If @tobscure gives the go-ahead, I guess a pull request would be welcomed.

**Comment by tobscure** [comment]
Counter-argument: https://github.com/facebook/react/issues/3582#issuecomment-90789417

**Comment by franzliedke** [comment]
Makes sense, too. I guess we can close this then?

**Comment by Luceos** [comment]
Closing due to strong argument.
