### ISSUE TITLE
Tag Notifications

### ISSUE THREAD

**Issue by meetdilip** [flarum/core#1031]
Currently, there is no " super sticky " option, which is quite understandable. But there can be scenarios where you need to give a sample post for users. Just like in request review, request graphics, board rules etc. I would like to suggest " Tag Notifications " which can be associated with a tag. It will be something like a pop up alert which can hold links and plain text. 

Once someone chooses a tag which has _tag notifications_ associated with it ( ie, a member choosing to post in that board ), he/she will be alerted with a popup ( dismissable ? ) which contains threads ( links ) or plain text ( instructions ) on how to behave while using that particular board ( tag ).

**Comment by franzliedke** [comment]
I think "Notifications" is a bad term here, since you're not suggesting to integrate this with the board notification system, right?

If I understand you correctly, you want something like the global welcome box on a per-tag level?

**Comment by tobscure** [comment]
Or something similar to the intended functionality of the old (outdated) [flarum-ext-instructions](https://github.com/flarum/flarum-ext-instructions)

**Comment by meetdilip** [comment]
@franzliedke  maybe, " Alerts " is a better term here. And yes, you got me right.

@tobscure , I am not sure what it is.

**Comment by franzliedke** [comment]
Can we merge this with flarum/issue-archive#387?

**Comment by meetdilip** [comment]
@franzliedke , isn't that a completely different issue ? Welcome message on register.

**Comment by franzliedke** [comment]
We never made a decision that we really want this, so I am closing this. It might one day become a reality if we decide to go with the more generic solutions discussed in the comments to flarum/issue-archive#387.
