### ISSUE TITLE
Discussion List on sidebar when in post has wrong background

### ISSUE THREAD

**Issue by datitisev** [flarum/core#1034]
Some discussions in the discussion list use the background color from below it.
Screenshots:

![captura de pantalla 2016-09-13 a las 5 53 26 pm](https://cloud.githubusercontent.com/assets/6401250/18492777/16f215ae-79db-11e6-9f1e-ba504caa5638.png)
 
![captura de pantalla 2016-09-13 a las 5 53 40 pm](https://cloud.githubusercontent.com/assets/6401250/18492778/1762b912-79db-11e6-84a4-74b08033bd6d.png)

Chrome Version: `55.0.2858.0 (Official Build) canary (64-bit)`

**Comment by franzliedke** [comment]
Has anyone encountered this on a stable build of Chrome?

**Comment by dav-is** [comment]
@franzliedke I could't replicate on Chrome 53.xx

**Comment by Luceos** [comment]
haven't seen this either.. @datitisev can you re-confirm or give some more insight on the exact discussions this happens on?

Closing until you give more details, re-open at will.

**Comment by datitisev** [comment]
I can't replicate anymore, it was probably a Webkit bug, as I am in Chrome Canary and probably got fixed a few days after I saw the error.
