### ISSUE TITLE
[Facebook Login][Twitter Login] Registration/Login issues

### ISSUE THREAD

**Issue by cristianciofu** [flarum/core#1036]
Hello,

I'm having an issue with the **Facebook Login** & **Twitter Login** extensions.

I activated it, created the FB app, filled the API/secret keys. Same goes for Twitter.

I managed to link my own account with my Facebook/Twitter account, but when I'm trying to create a new user directly with FacebookTwitter _(using different test accounts)_ the user is created in the database, but it cannot log in.

After trying to register (or login) the app displays the `noJs` page and with `debug=true` I have this error : 

![ph64kb7](https://cloud.githubusercontent.com/assets/2684268/18555064/b43ac5f4-7b66-11e6-8c5b-02cf6ac7af36.png)

I'm using : 
- **Flarum** beta.5 _(manually installed on shared hosting)_
- **Facebook Login** v0.1.0-beta.5 _(info taken from the Extensions page)_
- **Twitter Login** v0.1.0-beta.5 _(info taken from the Extensions page)_

If you need more information please don't hesitate to ask.

Thanks.

**Comment by dav-is** [comment]
Did you enter your API credentials into the extension?

**Comment by cristianciofu** [comment]
@dav-is yes I did. For both of them.

**Comment by Drilling-Billy** [comment]
Just my two cents but could be related to the fact that I got a "Invalid confirmation token" after using the confirmation link in my email. Could also not resend the activation link since I had no "rights for this action" After refreshing the Flarum page however I was in.

**Comment by cristianciofu** [comment]
I installed flarum on another server and the plugins seem to work.

I'll continue testing these days and I'll keep you post it 👍

**Comment by cristianciofu** [comment]
Apparently the issue was linked to my first server _(no ssh access / files uploaded through FTP)_. 

Now, on the new one everything works great...

So we can close this for now I guess.
