### ISSUE TITLE
Side navigation "now" does not work

### ISSUE THREAD

**Issue by luceos** [flarum/core#1037]
When you're at the top of a [discussion](https://discuss.flarum.org/d/3586-avatar4eg-share-social) and you click "now" in the side navigation to move to the latest post, it does not do anything anymore.

**Comment by franzliedke** [comment]
Hmm, do you have anything in the browser console?

For me, the same thing happens, but our custom scrollbar jumps down to the bottom, until I move on the page again.

**Comment by Cu8eR** [comment]
Do you use Google Chrome? Because since yesterday nothing works for me (same in MyBB - go to he last post, in Gmail etc).

**Comment by Luceos** [comment]
@Cu8eR yes chrome.
@franzliedke had nothing in the console, would have reported that otherwise.

Not sure what's going on here. Seems to work again now (at least on my windows 10 notebook with Chrome). Can someone verify to close?

**Comment by Cu8eR** [comment]
There was an update yesterday (beta channel, 64 bit, win 10). Now it works fine in Flarum and even in MyBB where it was broken.

**Comment by kulga** [comment]
Doesn't occur here Linux Firefox 48.0 (on discuss)

![](https://i.imgur.com/gblLGnf.gif)

**Comment by tobscure** [comment]
It was definitely occurring earlier... I'd guess it was something to do with something happening to the final post (deletion?) which was making the "Now" link try and scroll to a non-existent post - or something along those lines. If someone has some time to do some experimentation and try to reproduce that'd be super helpful :)

**Comment by luceos** [comment]
Tested this on discuss; it scrolls to the last visible post.
