### ISSUE TITLE
[extensions] check php requirements on install

### ISSUE THREAD

**Issue by luceos** [flarum/core#1039]
Related to [this PR](https://github.com/flarum/flarum.github.io/pull/36) we need Flarum to check the composer.json file for platform requirements before allowing installation.

Opened this issue in favor of the PR.

**Comment by askvortsov1** [comment]
IMO this should be fixable by my proposed solution to https://github.com/flarum/core/issues/1318#issuecomment-594272004.

**Comment by askvortsov1** [comment]
This is supported by Composer as a part of composer in https://getcomposer.org/doc/01-basic-usage.md#platform-packages.

**Comment by luceos** [comment]
You're assuming people run flarum on the same host they installed it on. To prevent broken installs we could check platform requirements when enabling. That is what this is about.

I'd like to propose to push this into an epic about the changes to the installation process (including the composer alternative).

**Comment by askvortsov1** [comment]
@luceos Last evening I started on down a fairly deep rabbit hole of trying to confirm dependency compatibility from inside flarum (which could be a possibly composer alternative). I wasn't sure how much of that we actually wanted to implement, so I decided to pause on that until I had an opportunity to discuss with y'all. I could make a brief writeup if this is something were seriously considering?

**Comment by askvortsov1** [comment]
I think https://getcomposer.org/doc/07-runtime.md#platform-check might be exactly what we need!

**Comment by luceos** [comment]
@askvortsov1 I wish I had known about that platform check sooner. We should also consider adding this to `php flarum info`.

**Comment by askvortsov1** [comment]
This is a composer 2 feature, so we couldn't really have done anything before. But anyways, this is something we could check before enabling extensions? Not 100% sure about `php flarum info` since that only shows enabled extensions (although, of course, that's under our control)

**Comment by luceos** [comment]
The file does an exit and I assume it is build dynamically whenever you run composer update commands. So including it anywhere outside of a cli command makes no particular sense, unless you wrap it in dirty exec calls. Including the file at the end of the InfoCommand if it exists would provide another layer of debugging to users and support staff.

Anyhow 👍
