### ISSUE TITLE
Use MEDIUMTEXT for post content

### ISSUE THREAD

**Issue by Magicalex** [flarum/core#1044]
Hi,

I build a Fluxbb to Flarum importer. On Fluxbb the equivalent of the column 'content' the type is mediumtext. So potentially a few posts exceed 65535 characters.

importer : https://github.com/mondediefr/fluxbb_to_flarum

**Comment by franzliedke** [comment]
Thanks for bringing this up.

I don't see an immediate use-case for texts that are longer than 64K (which is the limit of the `TEXT` type). What do other people think?

**Comment by tobscure** [comment]
@franzliedke On the other hand, is there a good reason we should stop people from writing posts longer than 64K? I am sure that someone, somewhere, would have a use-case...

**Comment by rwalkos** [comment]
I have seen may post that are really really long. Most of the time it's a review of some product or a walk-through of some build process like building a model plan or a home movie theater. But then again, lots of people just post 2 or 3 post right after and type reserved for future additions. <- That is kind of a pain if it could be avoided.

**Comment by franzliedke** [comment]
Good point. On the DB level, there does not seem to be much difference in implementation, so it should be fine.

**Comment by Luceos** [comment]
What is required:

- [ ] add a migration that [changes the column type](https://laravel.com/docs/5.3/migrations#modifying-columns)
- [ ] make sure the requirement is met: `doctrine/dbal`
