### ISSUE TITLE
Drop skeleton generator for now

### ISSUE THREAD

**Issue by Luceos** [flarum/core#1045]
Let's drop the skeleton generator for now. Switching to composer driven stack has made the command non-functional. 

See original issue #915

If @franzliedke or @sijad could take of this, that would be great! Please acknowledge.

**Comment by sijad** [comment]
I'll PR if that's ok?

**Comment by Luceos** [comment]
@sijad I was hoping you would ;)

**Comment by Luceos** [comment]
For your information this requires:

- removing the command class itself
- remove the registration in the service provider (somewhere)

**Comment by sijad** [comment]
how about https://github.com/flarum/core/tree/master/stubs/extension ?

**Comment by Luceos** [comment]
Ah yes forgot about those. Good thinking.
