### ISSUE TITLE
Hide diff for compiled js files

### ISSUE THREAD

**Issue by sijad** [flarum/core#1048]
suggested in https://github.com/flarum/core/issues/1024#issuecomment-251503338

as `js/*/dist/app.js` are auto generated files and also Babel add a lot's of ugly stuff this can help reading commits.

**Comment by Luceos** [comment]
This would require a change/add in the `.gitattributes` file:

```
js/*/dist/*.js -diff
```

See the referenced issue for more information on the discussion.

**Comment by janga1997** [comment]
@Luceos @sijad I would like to take up this issue.

**Comment by franzliedke** [comment]
@janga1997 Again, that's great to hear. :)
