### ISSUE TITLE
Reply by e-mail and e-mail category subscriptions

### ISSUE THREAD

**Issue by fdelapena** [flarum/core#105]
This feature just converts the forum into a mailing list.

Some well known forum allows this, which it is an extremely useful feature.

**Comment by rodrigoargumedo** [comment]
+1

**Comment by jsonnull** [comment]
Reply by email is probably not something that will be included out of the box. It requires either a mailserver or a 3rd party service. A mailserver is way beyond the scope of this project to provide, at best you could hope for it to be included in a docker installation image. A 3rd party service like Mandrill, which offers transactional email as a paid service, is more likely. That's plugin territory.

**Comment by franzliedke** [comment]
Indeed. It would be a very awesome plugin, though. =)

**Comment by fdelapena** [comment]
Oh, you're right. Is there a plugin specification currently?

**Comment by franzliedke** [comment]
Not yet. We're planning to have some documentation out when beta is released.

**Comment by fdelapena** [comment]
OK, thank you all! I'm looking forward for the beta.
By the way, replyPUSH service is doing some [forum extensions](https://github.com/replyPUSH?tab=repositories).

**Comment by jirutka** [comment]
Reply by e-mail is very important feature for a discussion forum IMO. It may not be difficult to implement this feature. There are two common methods:

* Poll a single mailbox with POP3. This is quite silly, but probably the simplest to setup for users (one can use even freemail mailbox) and reasonably easy to implement. For example Discourse uses this method.
* Setup a regular mail server (e.g. OpenSMTPD or Postfix) to deliver mails to your application by running some simple script (that will accept mail on stdout). This is probably the simplest to implement, but not so easy for users to setup. However, it’s a way better solution than the previous one, more scalable and flexible, good for advanced users.

**Comment by jirutka** [comment]
Sigh, if Flarum would support incoming e-mails, I would choose it instead of Discourse. :disappointed: I’m just installing Discourse and I’m really not happy with its UI and excessive complexity (for our quite simple use case).
