### ISSUE TITLE
JavaScript Styling isn't quite to Standard

### ISSUE THREAD

**Issue by dav-is** [flarum/core#1051]
Intro
======

I was wondering recently why Flarum didn't have a system like StyleCI to check JavaScript. I did some research and found [BitHound](https://www.bithound.io). I spent some time messing around with it and think I've figured out a pretty good configuration. It uses the [Airbnb Javascript Style Guide](https://github.com/airbnb/javascript) as described in the [contribution guide](https://github.com/flarum/flarum/blob/master/CONTRIBUTING.md#code-style).

The Analysis
=========

I was surprised to find the code didn't completely follow the Airbnb style guide. You can see the results of the analysis [here](https://www.bithound.io/github/dav-is/core/JS-Lint/files). I disabled all the rules that conflicted with the way Flarum functioned. There are 153 failing files currently.

**Comment by tobscure** [comment]
See https://github.com/flarum/core/issues/879
