### ISSUE TITLE
Bate6 in <head> can not normally display description

### ISSUE THREAD

**Issue by Btitle** [flarum/core#1055]
Bate6 in <head> can not normally display description

**Comment by franzliedke** [comment]
Sorry, but we need much more details than a duplicate issue title and description. Please help us help you by providing more information, most of which is described in the issue template that you saw when creating the issue. 

The most important questions your issue should answer are the following:
- What did you try to do? 
- What happened? 
- What did you expect to happen instead? 
- For extra credit: Why is that a bug with Flarum? How and where do we fix it?

Until then, I am closing this issue.
