### ISSUE TITLE
Cannot read property default of undefined

### ISSUE THREAD

**Issue by steelbrain** [flarum/core#1059]
## Bug report
- Version of Flarum: Below
- The webserver you are running: nginx, bug irerlevant
- PHP version: 5.6.x
- Hosted environment: vps
## Flarum info

This is the versions part of `composer.json`

```
    "require": {
        "flarum/core": "^0.1.0",
        "flarum/flarum-ext-akismet": "^0.1.0",
        "flarum/flarum-ext-approval": "^0.1.0",
        "flarum/flarum-ext-auth-facebook": "^0.1.0",
        "flarum/flarum-ext-auth-github": "^0.1.0",
        "flarum/flarum-ext-auth-twitter": "^0.1.0",
        "flarum/flarum-ext-bbcode": "^0.1.0",
        "flarum/flarum-ext-emoji": "^0.1.0",
        "flarum/flarum-ext-english": "^0.1.0",
        "flarum/flarum-ext-flags": "^0.1.0",
        "flarum/flarum-ext-likes": "^0.1.0",
        "flarum/flarum-ext-lock": "^0.1.0",
        "flarum/flarum-ext-markdown": "^0.1.0",
        "flarum/flarum-ext-mentions": "^0.1.0",
        "flarum/flarum-ext-pusher": "^0.1.0",
        "flarum/flarum-ext-sticky": "^0.1.0",
        "flarum/flarum-ext-subscriptions": "^0.1.0",
        "flarum/flarum-ext-suspend": "^0.1.0",
        "flarum/flarum-ext-tags": "^0.1.0"
    },
```
## The Bug

I see this bug everytime I install a third party extension. If I had to guess, it happens everytime they do NOT have a default export, it should be handled gracefully IMHO.

<img src="https://cloud.githubusercontent.com/assets/4278113/19606240/a42c137c-97de-11e6-9b07-b97712024505.png">
<img src="https://cloud.githubusercontent.com/assets/4278113/19606245/abcab66a-97de-11e6-86d1-e393130e85df.png">

**Comment by tobscure** [comment]
Many third party extensions are not be compatible with beta 6 yet. Which version of Flarum are you actually using? (The composer.json section just specifies a version constraint; to find out the specific version that's installed you can run the `php flarum info` command.)

**Comment by steelbrain** [comment]
I actually am running flarum in a docker container and the version of php installed on host doesn't have as much extensions. I installed it yesterday with the composer command suggested in installation docs so I think it's the latest one out :)

**Comment by tobscure** [comment]
Sorry, I'm talking about Flarum extensions, not PHP extensions. From the screenshot it looks like you've at least got `sijad/flarum-ext-auth-steam` installed – can you try disabling that by manually removing it from the `extensions_enabled` array in the `settings` database table?

**Comment by tobscure** [comment]
Or just run `composer remove sijad/flarum-ext-auth-steam`

**Comment by steelbrain** [comment]
Thanks @tobscure that of course solves the problem. But I was wondering if there was a problem in core not handling empty modules :)

If it's an issue of compatibility tho, from the extension's side, then it seems good. I'll close this issue and wait for beta 6 compatibility in the third party extensions

**Comment by tobscure** [comment]
Yeah, true, it should fail gracefully if the module isn't found. I'll push a fix soon!

**Comment by sijad** [comment]
why can't I reproduce this error?

**Comment by SDLyu** [comment]
I have the same issue, and I don't install any third party extensions.
<img width="963" alt="development_forum_" src="https://cloud.githubusercontent.com/assets/2996108/22853655/781c28b4-f097-11e6-98d4-72068d50f11e.png">

**Comment by Luceos** [comment]
@SDLyu can you try running `php flarum cache:clear` and see if that helps?

**Comment by luceos** [comment]
Do we want to take graceful erroring into account here @tobscure ?

**Comment by tobscure** [comment]
This will become irrelevant with #1367
