### ISSUE TITLE
PHP required version

### ISSUE THREAD

**Issue by niutech** [flarum/core#106]
The `composer.json` file shows that the minimum required version of PHP is 5.4. However, when I want to install Flarum, Composer outputs:
`zendframework/zend-diactoros 1.0.0 requires php >=5.5 -> your PHP version (5.4.7) does not satisfy that requirement.`
Also Laravel 5 requires PHP 5.5. So could you adjust the vesions of dependencies so that I could install Flarum on PHP 5.4?

**Comment by franzliedke** [comment]
Newer versions of Diactoros actually requrie 5.4 only, but yeah, we'll update to Laravel 5.1 soon anyway.

I'll take care of updating the PHP requirement as part of #75, thank you very much!
