### ISSUE TITLE
Error 500 : Issue when i try to reset my password (flarum.org)

### ISSUE THREAD

**Issue by lecteur** [flarum/core#1061]
> Issues on Github are meant for bug reporting. Please post feature requests on the [discussion forum](https://discuss.flarum.org/t/features).

---
> Try to complete the below form as far as you are able and are willing to share. Add a screenshot of the issue if you can.

## Bug report
- Version of Flarum: Flarum v0.1.0-beta.6
- Website URL where the bug is visible: https://discuss.flarum.org/
- The webserver you are running: Apache
- PHP version: 5.6
- Hosted environment: vps
- Hosting provider: N/A

## Flarum info

I try to reset my password, but i have an issue with discuss.flarum.org when i confirm the new one, i have a 500 error 
Can you check please

**Comment by Magicalex** [comment]
This may be because your password at least 8 characters.

**Comment by lecteur** [comment]
Merci Magicalex, il n'y avait pas d'indication mais c'est normal c'est qu'une beta ! Sinon magnifique ton forum je l'ai connu sur Wareziens ;)
