### ISSUE TITLE
Zend Stratigility Deprecated Message

### ISSUE THREAD

**Issue by PeterPlucinski** [flarum/core#1065]
Initial istall of flarum is showing the below deprecation message at the top of the page.

"Deprecated: The third argument to Zend\Stratigility\MiddlewarePipe() ($out) will be required starting with Stratigility version 2; please see https://docs.zendframework.com/zend-stratigility/migration/to-v2/ for more details on how to update your application to remove this message. in /vagrant/flarum/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php on line 101"

## Bug report
- Version of Flarum: 0.1.0-beta.6
- Website URL where the bug is visible: root of the site
- The webserver you are running: nginx
- PHP version: 5.6.23
- Hosted environment: vagrant
- Hosting provider: NA - vagrant

## Flarum info

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

Flarum core 0.1.0-beta.6
PHP 5.6.23-1+deprecated+dontuse+deb.sury.org~trusty+1
Loaded extensions: Core, date, ereg, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, mbstring, pcntl, session, posix, Reflection, standard, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, PDO, curl, gd, intl, json, mcrypt, mysql, mysqli, pdo_mysql, readline, xsl, mhash, Zend OPcache
EXT flarum-approval v0.1.0-beta.6
EXT flarum-bbcode v0.1.0-beta.5
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.6
EXT flarum-flags v0.1.0-beta.6
EXT flarum-likes v0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.6
EXT flarum-markdown v0.1.0-beta.5
EXT flarum-mentions v0.1.0-beta.6
EXT flarum-sticky v0.1.0-beta.6
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.6
EXT flarum-tags v0.1.0-beta.7
Base URL: http://localhost:8000
Installation path: /vagrant/flarum

## Additional comments
Some additional information you'd like to share, eg what have you tried so far.

## Log files

```
Put any relevant logs here.
```

**Comment by qius416** [comment]
Looks like zend-stratigility updated branch aliases ... 
https://github.com/zendframework/zend-stratigility/commit/6e1bd05479851fc5bc470795b67dd628af5bf555

**Comment by Luceos** [comment]
@tobscure this issue shouldn't be closed already. The fact that a deprecated warning is being shown on the front page is not a good thing. Shouldn't those be prevented by adding an error_reporting line somewhere.. @franzliedke what is your opinion?

**Comment by SteveAzz** [comment]
@Luceos As a temporary fix untill the next realse would be explicty tell which version to install from your `composer.json` such as 

```
"require": {
    "zendframework/zend-stratigility": "1.2.*",
}
```

Or 
```
$ composer require zendframework/zend-stratigility: 1.2.*
```

**Comment by Luceos** [comment]
@SteveAzz [I am aware](https://github.com/flarum/core/issues/1066). My point is about showing deprecated warnings, which should not show up at all.

**Comment by Southclaws** [comment]
I've run across this issue recently while installing and the above solution doesn't work any more with a fresh Flarum install:

```
Could not find package 1.3.0-dev at any version for your minimum-stability (beta). Check the package spelling or your minimum-stability
```

Are there any more workarounds for now?

**Comment by franzliedke** [comment]
@Southclaws This has been fixed properly in the latest dev-master version, so this workaround should no longer be necessary.

**Comment by asapabedi** [comment]
Alright now i get this after trying the work around  `[InvalidArgumentException]                                                     
  Could not find package 1.2.* at any version for your minimum-stability (stabl  
  e). Check the package spelling or your minimum-stability` Where can i get the latest dev-master version

**Comment by datitisev** [comment]
@asapabedi Set `minimum-stability` in `composer.json` to `beta`, and then execute the command again. You can find more information if you do a quick search in [Flarum Discuss](https://discuss.flarum.org)

[The composer.json Schema](https://getcomposer.org/doc/04-schema.md#minimum-stability)
