### ISSUE TITLE
Update to Stratigility 1.3

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#1069]
Updating will require some changes in our middleware stack to stay forward-compatible with the upcoming version 2.0 of Stratigility, see https://docs.zendframework.com/zend-stratigility/migration/to-v2/.

Important: MR #1066 should also be reverted as part of this.

**Comment by xtrasmal** [comment]
Any status?

**Comment by franzliedke** [comment]
See [my new pull request](https://github.com/flarum/core/pull/1100) that should fix this issue. Haven't tested it yet, though.
