### ISSUE TITLE
beta 6 can not log out.

### ISSUE THREAD

**Issue by liuminghao233** [flarum/core#1071]
> Issues on Github are meant for bug reporting. Please post feature requests on the [discussion forum](https://discuss.flarum.org/t/features).
---
> Try to complete the below form as far as you are able and are willing to share. Add a screenshot of the issue if you can.

## Bug report
- Version of Flarum: 0.1.0-beta.6
- Website URL where the bug is visible: no
- The webserver you are running: nginx
- PHP version: 7.0.13
- Hosted environment: localhost VM 12
- Hosting provider: personal

## Flarum info

```
Output of "php flarum info", run this in terminal in your Flarum directory.
.Flarum core 0.1.0-beta.6
PHP 7.0.13
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, json, exif, mcrypt, mysqlnd, PDO, pgsql, Phar, posix, recode, shmop, SimpleXML, snmp, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_dblib, pdo_mysql, pdo_pgsql, pdo_sqlite, wddx, xmlreader, zip, Zend OPcache
EXT flarum-approval v0.1.0-beta.6
EXT flarum-bbcode v0.1.0-beta.5
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.6
EXT flarum-flags v0.1.0-beta.6
EXT flarum-likes v0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.6
EXT flarum-markdown v0.1.0-beta.5
EXT flarum-mentions v0.1.0-beta.6
EXT flarum-sticky v0.1.0-beta.6
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.6
EXT flarum-tags v0.1.0-beta.7
Base URL: http://192.168.127.128
Installation path: /var/www/html


## Additional comments
just install flarum by composer and find out that the log out function not working

## Log files
![image](https://cloud.githubusercontent.com/assets/13027589/20483673/44751b46-b02e-11e6-8451-170a454e04b7.png)

#my nginx configuration
![image](https://cloud.githubusercontent.com/assets/13027589/20483690/56ffafba-b02e-11e6-869a-e168cc42baa8.png)

**Comment by liuminghao233** [comment]
post pic again:
![image](https://cloud.githubusercontent.com/assets/13027589/20483713/78f5f6e2-b02e-11e6-919e-68b37650ec93.png)
![image](https://cloud.githubusercontent.com/assets/13027589/20483716/7e296e28-b02e-11e6-9483-22e56c52866b.png)

**Comment by Luceos** [comment]
Offtopic, I think the pics weren't showing because they were in the code blocks (tripple backticks). Nice report!

Seems to be caused by a csrf token mismatch.

**Comment by liuminghao233** [comment]
@Luceos haha ,that's why i repost the pic again.

**Comment by liuminghao233** [comment]
but, this bug will not show if i use XAMPP PHP7.

**Comment by liuminghao233** [comment]
set session file's owner to nginx and the problem fixed
