### ISSUE TITLE
`app.modal.show` errors with "TypeError: Cannot set property 'retain' of undefined"

### ISSUE THREAD

**Issue by datitisev** [flarum/core#1076]
## Bug report
- **Version of Flarum**: dev-master (v0.1.0-beta.6)
- **The webserver you are running**: Apache
- **PHP version**: 7.0.8
- **Hosted environment**: Local
- ~~Hosting provider: ?~~

## Flarum info

```
Flarum core 0.1.0-beta.6 (3612ca7aca90b5d45310da1602256e247451cec3)
PHP 5.6.25
Loaded extensions: Core, date, ereg, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, hash, fileinfo, filter, ftp, gd, SPL, iconv, json, ldap, mbstring, session, standard, mysqlnd, mysqli, PDO, pdo_mysql, pdo_sqlite, Phar, posix, readline, Reflection, mysql, shmop, SimpleXML, snmp, soap, sockets, exif, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip
EXT flarum-approval dev-master
EXT flarum-bbcode dev-master
EXT datitisev-dashboard dev-master (f149b3fb445a0e75bdcf306d6ba89e3960b7b296)
EXT flarum-emoji dev-master
EXT flarum-english dev-master
EXT flarum-flags dev-master
EXT flarum-likes dev-master
EXT flarum-lock dev-master
EXT flarum-markdown dev-master
EXT flarum-mentions dev-master
EXT flarum-sticky dev-master
EXT flarum-subscriptions dev-master
EXT flarum-suspend dev-master
EXT flarum-tags dev-master
Base URL: http://localhost:8888
Installation path: /Users/david/Web Development with Node & Express/Flarum
```

## Additional comments
JavaScript Error:

![JavaScript Error with app.show.modal](http://i.imgsafe.org/cc66983e99.png)

Corresponding Erroring Code:

![Corresponding Code](http://i.imgsafe.org/cc66a1af36.png)

I am trying to create a modal for my AdminDashboard extension.
For some reason, this new one doesn't work, while my current modal still works.
My code is available at https://github.com/datitisev/flarum-ext-admindashboard/tree/newDashboard

---

_Sorry if this is the wrong place to send this, as the error starts with `app` I thought I should submit the issue here and not on Gitter_

**Comment by dav-is** [comment]
Seems to work in my code: https://github.com/dav-is/flarum-ext-securehttps/blob/master/js/admin/src/main.js#L6

**Comment by datitisev** [comment]
@tobscure It works now. Thanks.
Glad to hear new API changes will _hopefully_ make things easier 😉
