### ISSUE TITLE
Header No Longer Fixed After Search

### ISSUE THREAD

**Issue by dav-is** [flarum/core#1078]
## Bug report
- Version of Flarum: dev.master
- Website URL where the bug is visible: https://discuss.flarum.com
- Browser: Safari & Chrome iOS 10 (Probably affects all mobile browsers)

## How to Replicate
1. On index, click hamburger button, then search input box
2. Type "foobar" and press return
3. Scroll down (see the nav bar is no longer in a fixed position)

**Comment by tobscure** [comment]
Can't reproduce on Safari iOS 10.2.

**Comment by datitisev** [comment]
Can't reproduce on Safari iOS 10.2

**Comment by dav-is** [comment]
Must have been a 10.1 bug because after the upgrade to 10.2 it no longer occurs.
