### ISSUE TITLE
Upgrade FastRoute

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#108]
The latest changes [enabled optional parameters](https://github.com/nikic/FastRoute/commit/2acf2295cf6b2d21ab2a6cb45aa54de390309c1a), but changed the structure of the parsed route data.

Integrate these changes and adapt the router accordingly.

**Comment by younes0** [comment]
a simple suggestion: why not use Lumen's router? It's uses fastroute and has the Laravel syntax

**Comment by franzliedke** [comment]
Mainly because we don't want to use all of Lumen, I guess. :)

**Comment by younes0** [comment]
aha okay 
I was suggesting that since you seems to like Laravel syntax :)
Yeah I've just saw, the routing system can't be decoupled from laravel/lumen-framework :(
