### ISSUE TITLE
It doesnt send confirmation email when registering accounts

### ISSUE THREAD

**Issue by kenygamer** [flarum/core#1080]
## Bug report
- Version of Flarum: 0.1.0-beta2.0
- Website URL where the bug is visible: https://community.survivaltimep.pe.com
- Apache/2.4
- PHP version: 5.5
- Hosted environment: Shared
- Hosting provider: https://www.hostinger.es

So When you add and rechecked email Hapenned even a day ago and you dont receive confirmation email hapenned to Everyone Even me. Try register ur account at the top Website URL and you'll,see
``

**Comment by dav-is** [comment]
This is an issue with your environment. Please post on the support section of our forums instead.

**Comment by kenygamer** [comment]
@dav-is I can't . I have the same issue. I signed up at the forum and I do not receive my confirmation emaill tryed twitter and it will still request me to confirm email but idont get anything... I tryed many times with different email address

**Comment by jordanjay29** [comment]
Old version. Closing this until we can sort this out in more depth/confirm it's still an issue in beta 6. If you're having problems with discuss.flarum.org, open an issue here or find us on Gitter (@jordanjay29, you can DM me and we'll sort it out).
