### ISSUE TITLE
Changes in the js files of the Admin /admin/ cpanel directory doesnt appear deleted cookies, changed device and everything.

### ISSUE THREAD

**Issue by kenygamer** [flarum/core#1081]
Version of Flarum: 0.1.0-beta2.0
Website URL where the bug is visible: https://community.survivaltimepe.com
Apache/2.4
PHP version: 5.5
Hosted environment: Shared
Hosting provider: https://www.hostinger.es
So When I do changes in the js files of the admin directory, I want to change the text of the dashboard and after changes made they dont appear. I didnt restart hostinger free account becuase im sure i cant its shared hosting so What i can do its not cache

**Comment by dav-is** [comment]
Seriously stop posting these issues on GitHub. If you need help, post on discuss.flarum.org

**Comment by kenygamer** [comment]
Dear @dav-is,

As said in my last post, I do not have the possibility to register in the Flarum forums because I have not received the confirmation email.
After several failed attempts, and also attempting with multiple email accounts from different providers, there is no solution.

**Comment by dav-is** [comment]
Try refreshing the page after registering

**Comment by kenygamer** [comment]
@dav-is,

I have tried to perform that for several times, even rebooted my own device and changed to computer in some occasions.
There is no solution to this problem, and this is also happening to me in my Flarum.

**Comment by tobscure** [comment]
Check your spam box.

**Comment by Luceos** [comment]
@kenygamer 
> Version of Flarum: 0.1.0-beta2.0

I'm positive that support for such an outdated version cannot be provided. You can expect proper support once you've upgraded to the latest version, which is beta 6 right now.

**Comment by jordanjay29** [comment]
Old version. Closing this until we can sort this out in more depth/confirm it's still an issue in beta 6. If you're having problems with discuss.flarum.org, open an issue here or find us on Gitter (@jordanjay29, you can DM me and we'll sort it out).
