### ISSUE TITLE
[Mentions] Pointing to deleted users keep the username in mention

### ISSUE THREAD

**Issue by datitisev** [flarum/core#1082]
## Bug report
- Version of Flarum: `v0.1.0-beta.6` or maybe `dev-master` (it's Flarum Discuss)
- Website URL where the bug is visible: https://discuss.flarum.org/d/231-view-count/2
## Additional comments

The mention pointing to a message by "Kayz" is the first post. The author's account has been deleted, but the mention still shows their username, and the link of the mention goes to https://discuss.flarum.org/d//1 which then redirects to https://discuss.flarum.org

![image](https://cloud.githubusercontent.com/assets/6401250/20991804/7788cd70-bcae-11e6-8d8b-c6a6098e2fe3.png)

**Comment by dav-is** [comment]
#665 ;)

**Comment by datitisev** [comment]
Oh, sorry. I hadn't seen this already submitted. My bad.
