### ISSUE TITLE
Can't open Settings page on Android devices

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#1086]
A user [has reported](https://discuss.flarum.org/d/4387-cannot-open-settings-page-on-samsung-tablet) being unable to open the user Settings page when accessing Flarum from mobile devices running older versions of Android. This happens when accessing discuss.flarum.org as well.

Affected OS versions: Android 4.1.1, Android 4.4.2

Affected Browser: Google Chrome 55.0.2883.91

Only the Settings page seems to be affected; other functionality is working as expected.

Can anyone reproduce this?

**Comment by ryanvade** [comment]
It seems to affect Android 5.1.

**Comment by franzliedke** [comment]
We are talking about the user settings page, right? 

Works for me on discuss.flarum.org, with Chrome 55.0.2883.91, but a newer Android (v5.1.0). Can anybody else reproduce?

**Comment by Ralkage** [comment]
@franzliedke - Setting up a test environment as we speak. I'll run some tests.

**Comment by TurboProgramming** [comment]
[This issue needs the `mobile` and `UX` tags]

**Comment by ardacebi** [comment]
It works for me too using Chrome's and Firefox's latest versions on Android 7.0 Nougat.
