### ISSUE TITLE
Post scrubber resizes incorrectly when scrolling through large post

### ISSUE THREAD

**Issue by tobscure** [flarum/core#109]
Steps to reproduce:

1. Go to a discussion with a long post, like http://discuss.flarum.org/d/594-very-long-post
2. Scroll down and watch the PostStreamScrubber scrollbar.
3. Observe the scrollbar handle's height go a bit funny.

Expected behaviour:
The height of the scrollbar handle should always reflect the proportion of the post(s) that are in the viewport.

What needs to be done:

* In the PostStreamScrubber's `update` method, improve the logic that calculates `index` and `visible`.

**Comment by ahsanity** [comment]
@tobscure since I have a little idea on how the PostStreamScrubber code works, do you think I can take this? Can you clear out a little what needs to be done here? Thx!

**Comment by tobscure** [comment]
@ahsanity Thanks for offering! The calculations are a bit complicated/confusing (at least for me) and in my attempt to boil down what needs to be done, I ended up solving the issue myself :sweat_smile: I still need to clean it up a bit but will push soon.

**Comment by ahsanity** [comment]
Haha, no worries. I will try to pick up something else soon :)
