### ISSUE TITLE
[Mentions] Replying to a user's post with a post id that is not author's post uses incorrect author

### ISSUE THREAD

**Issue by datitisev** [flarum/core#1095]
## Bug report
- Version of Flarum: dev-master
- Website URL where the bug is visible: http://discuss

## Additional comments

![](https://i.gyazo.com/322d172f9dbe5f33b82ec765fcf2815b.gif)

I said `@Toby#3205` instead of `@Toby#32051`, which quoted a post that wasn't Toby's.
I fixed it now on the actual post 🙂 

The post not loading was just my slow internet choosing not to work when I made the GIF.

---

*Feel free to make the title shorter and so it makes more sense* 😜

**Comment by Luceos** [comment]
This is quite confusing. So whenever you mention a user but add a hash that refers to a post not of the mentioned user, it will redirect to nothing? Because the hash isn't on this page, correct?

Isn't really a bug, fixing this would classify as idiot-proofing I guess.

**Comment by datitisev** [comment]
> fixing this would classify as idiot-proofing I guess.

Well, you can call it that, but the user may reply to a post by another user that they didn't want to reply to, but they'd probably never notice, at it will says the author of the post replied to is wrong, but it is the author of the post that the user wanted to reply to...

> So whenever you mention a user but add a hash that refers to a post not of the mentioned user, it will redirect to nothing? Because the hash isn't on this page, correct?

No, if I say `@Toby#3205`, it will be replying to Fastidious' post with the ID 3205, and whenever you click it it will go to that post. It was blank because my internet decided to stop working at that moment.

I guess one would want that for having their own text in a reply, like I show below, but I'm thinking maybe, if the custom text corresponds to another user's username exactly, and that user is not the replied post's author, to correct that custom text in the reply to the proper author...
I am having a lot of trouble explaining this :|

![](https://i.gyazo.com/23529caef76adb0e92fd46a1a1efb4f8.gif)

_In the above example, `testuser5` is an actual user but not the author of the replied post. That's what I'm saying should be corrected, but not `test_reply_with_custom_text`, because the forum has no one with that username_

**Comment by dav-is** [comment]
I feel like this could be imcorporatd with #315

**Comment by Luceos** [comment]
@dav-is you are correct. In fact if I read that issue correctly it will solve this reported issue as well, because usernames are taken from the references and only references will be stored.

If you both agree I'd like to close this one in favor of #315.

**Comment by franzliedke** [comment]
Agreed.
