### ISSUE TITLE
CSS: Online Dot Shifts User's Badges to the Left

### ISSUE THREAD

**Issue by dav-is** [flarum/core#1097]
## Bug report
- Version of Flarum: Beta 6
- Website URL where the bug is visible: Any discussion provided a user with a group badge is online.

If user's online dot is displayed, the user's group badges are shifted to the left of the avatar.

**Comment by dav-is** [comment]
![img](https://i.imgur.com/pwvdILF.jpg)
Here's verification.

**Comment by franzliedke** [comment]
Oh, on mobile? Or do you have the same problem on desktop, too? (I believe the green dot is positioned differently there.)

I couldn't find other badged users who are online when I tried to reproduce this.

**Comment by dav-is** [comment]
It's mobile only I believe. You can test this on yourself, provided you're badged (which you are).

**Comment by Luceos** [comment]
Just checked it on my chrome mobile browser and noticed the same. Not sure it was done on purpose to reduce reserved space.

**Comment by franzliedke** [comment]
I can reproduce as well.

**Comment by muskatin** [comment]
![image](https://cloud.githubusercontent.com/assets/11082633/23092907/0acba678-f5e6-11e6-9e56-c375fb08c777.png)
Normal position?

**Comment by TurboProgramming** [comment]
[This issue needs the `mobile` and `UX` tags]
