### ISSUE TITLE
I follow the install tips ，but failed ...

### ISSUE THREAD

**Issue by JellyBool** [flarum/core#110]
![2015-06-19_16-27-48](https://cloud.githubusercontent.com/assets/6011686/8249811/a241c644-16a0-11e5-961f-a2b352eac465.png)

tried many times with vagrant,still got the error...i even installed flarum without vagrant , same issue....

any ideas?

**Comment by franzliedke** [comment]
If you want to try the public source code (it's a little bit out of date), please check out commit `76533e4096eb252974eed4d4f438c2cd012e1ea3`, that should work.
