### ISSUE TITLE
Starting A Discussion on Secondary Tag Error [Tags]

### ISSUE THREAD

**Issue by dav-is** [flarum/core#1101]
## Bug report
- Version of Flarum: beta.6

When creating a tag from `https://domain.tld/t/secondaryTag` It will throw an error saying one primary tag is required instead of opening the tag selection model like it does when you have no tag added. There is no guidance of how to fix this error and confused a client of mine to the point of him sending an email of how to fix it.

**Comment by Luceos** [comment]
When I try this in the current official forums, I actually see the primary applied automatically. 

Hope you don't mind me closing this unless you have other evidence suggesting this is still an issue in dev-master.

**Comment by dav-is** [comment]
@Luceos http://i.imgur.com/BzvRbwX.jpg

**Comment by Luceos** [comment]
Right that makes sense. I've misunderstood, but it makes sense now.

**Comment by dav-is** [comment]
This is where the code would need to be modifed: https://github.com/flarum/flarum-ext-tags/blob/master/js/forum/src/addTagComposer.js#L46

**Comment by janga1997** [comment]
@dav-is @Luceos I would like to take up this issue.

**Comment by franzliedke** [comment]
@janga1997 Please, feel free to take this on and send a pull request. :+1:

**Comment by franzliedke** [comment]
P.S.: If you encounter any difficulties, feel free to ask for help in this issue, or start a work-in-progress pull request and ask for help there.
