### ISSUE TITLE
Rename discussion modal translations

### ISSUE THREAD

**Issue by luceos** [flarum/core#1102]
We need to translate a few keys due to a recent change in the rename discussion modal PR by @datitisev ; the #1083 .

The keys affected are:

- added core.forum.discussion_controls.rename_modal.title
- added core.forum.discussion_controls.rename_modal.submit_button
- dropped core.forum.log_in.remember_me_text for core.forum.log_in.remember_me_label
- dropped core.forum.discussion_controls.rename_text

**Comment by franzliedke** [comment]
@dcsjapan @milescellar Can I ask one of you to take care of this (review the keys and add the translations), please? That would be awesome!

Sending the PR to *master* is perfectly fine for now, I'll take care of the merge conflicts when we merge *next*.

**Comment by milescellar** [comment]
Fixed with https://github.com/flarum/flarum-ext-english/pull/98?
