### ISSUE TITLE
Passwords hashing does not involve a proper salting

### ISSUE THREAD

**Issue by Slayer95** [flarum/core#1103]
## Bug report
- Version of Flarum: Master branch

As far as I can tell (I may be wrong), the passwords stored by Flarum, while hashed, are not being properly salted[[1]](https://github.com/flarum/core/blob/1031826a3d242735da26c9e5342fda2a91195db1/src/Core/User.php#L259-L262).
The best practice is to have a different salt for each user, and hash it together with the password.
The lack of this mechanism makes a compromised database vulnerable to rainbow table attacks.

**Comment by Slayer95** [comment]
Oh... bcrypt seems to store the hash together with the salt. Clever.

**Comment by Kakifrucht** [comment]
bcrypt hype!
