### ISSUE TITLE
comments_count total incorrect for users

### ISSUE THREAD

**Issue by LuffyyyffuL** [flarum/core#1104]
Hi,

Sorry for my english.

I have finding that when i remove a comment, in "users" table the value to "comments_count" line is set to n-1 and when i remove definitly the comment, the value to "comments_count" line is again seted to n-1.

So the total comments is incorrect because for one comment deleted, -2 is subtracted from the "comments_count" current total

I think that is not normal, what thinking you ?

Thank you :)

**Comment by franzliedke** [comment]
Thanks for the report. Can anyone reproduce?

**Comment by franzliedke** [comment]
Okay, I just reproduced this as well. Should have done that right away.

So, the comments_count for a user is reduced both when initially soft-deleting a post, and also when it is deleted forever.

**Comment by Luceos** [comment]
For reference: https://github.com/flarum/core/blob/master/src/Core/Listener/UserMetadataUpdater.php#L96
