### ISSUE TITLE
Protocol-relative url in config outputs incorrect url format in emails.

### ISSUE THREAD

**Issue by alrpal** [flarum/core#1107]
## Bug report
- flarum v0.1.0-beta.6
- ubuntu 16.04
- nginx 1.10.0
- PHP 7.0.13
- EC2 t2.micro
- AWS

## Example email body (note url formatting)

```
Hey flarum1!

sdf replied to your post (#1) in i think its working....

//mydomain.com/forum/d/3/4
---

flarum1 hello
```

## config.php

``` php
<?php return array (
  2   'debug' => true,
  3   'database' =>
  4   array (
  5     'driver' => 'mysql',
  6     'host' => 'localhost',
  7     'database' => 'test',
  8     'username' => 'test',
  9     'password' => '*****',
 10     'charset' => 'utf8mb4',
 11     'collation' => 'utf8mb4_unicode_ci',
 12     'prefix' => '',
 13     'strict' => false,
 14   ),
 15   'url' => '//mydomain.com/forum',
 16   'paths' =>
 17   array (
 18     'api' => 'api',
 19     'admin' => 'admin',
 20   ),
 21 );
```

## Additional comments
I don't know if you want to support protocol-relative urls. This is easily fixed by simply putting `http://` or `https://` instead of `//`, but I noticed that everything else appears to work with a protocol-relative url except for emails.

**Comment by Luceos** [comment]
Without a protocol Flarum will not know to forward a login attempt to https. I can imagine you would like to use it as such. There isn't a good reason to use http anyway if you have SSL encryption configured, because there is hardly any performance loss and it does protect your privacy for every submitted content or authentication attempt.

What do you think @franzliedke ?

**Comment by franzliedke** [comment]
I agree with @Luceos.

As it isn't perfectly obvious how we should handle this situation, I will consider this an error on your part, for not configuring an absolute URL. If you have any proposals on how to make this clearer, I will gladly take care of improving the situation.

Or even better: If anybody is interested in sending a PR that automatically adds "https:" to such a protocol-relative URL in the installer, I would be very happy. :smile: 

---

In any case, thanks for reporting this, @alrpal! :heart:
