### ISSUE TITLE
The style (font-size? bold or light?) of MarkDown Tag "#" is not clear enough.

### ISSUE THREAD

**Issue by ExerciseBook** [flarum/core#1109]
In Flarum
![1](https://cloud.githubusercontent.com/assets/6327311/22108555/a603485e-de8e-11e6-928f-002bb83e1724.png)

In Github
![2](https://cloud.githubusercontent.com/assets/6327311/22108509/76cb921c-de8e-11e6-81a3-32ee0e990e4b.png)

In my page which is full of many kinds of title levels like this

```
作业：
　├─语文：
　│　├─2015-2016学年度上学期高二期末考试卷
　│　├─[复习资料]必修五课内翻译
　│　└─实词虚词，文学常识 相关资料已上传到15班语文学习群群文件
　├─数学：
　│　├─2013-2014学年度上学期高二期末考试卷
　│　├─2016-2017学年度上学期高二数学(必修5)形成性测试卷
　│　│　├─（一）第一章 解三角形
　│　│　└─（三）第三章 不等式
　│　└─作业答案已上传到班班群群文件
　├─英语：
　│　├─单词卷
　│　├─改正听写
　│　└─练字： 
　│　　　haiku
　│　　　syllable
　│　　　minimum
　│　　　translation
　│　　　branch
　├─物理：
　│　├─物理期末复习七
　│　└─中山期末考A
　├─化学：
　│　├─期末复习综合训练题（二）
　│　│　└─两张(7面) 含答案(1面)
　│　├─非选择性专题训练六——化学实验
　│　│　└─一张(4面) 不含答案
　│　└─选择题专题训练（二）
　│　　　└─一张半 不做 保管好
　├─政治
　├─历史
　├─地理
　├─生物
　└─附录
```

The not clearful enough style of "#" tag may make the viewer puzzled.

I tried to edit the code of markdown parser but failed . ( I didnot find the parser's location .

**Comment by tobscure** [comment]
Yep agreed this needs to be fixed up.

**Comment by datitisev** [comment]
I don't think this is relevant anymore; it looks to have been fixed.

![image](https://user-images.githubusercontent.com/6401250/72671859-3c66f900-3a1f-11ea-8680-ac3744124c74.png)
