### ISSUE TITLE
Contextual binding is bad for extendability

### ISSUE THREAD

**Issue by luceos** [flarum/core#1111]
A few months ago I talked to @franzliedke about contextual binding in relation to overriding the storage adapter of avatars upload. Using contextual binding there is no way of loading the bound implementation and changing the configuration, also extending/overriding the contextual binding is not (yet) possible in Illuminate.

Now.. attempting to implement a Gambit I noticed a few issues. First, one cannot force a gambit using the `ConfigureDiscussionSearch` event, because the event is triggered _after_ the gambits have been applied. So the alternative solution is adding the gambit globally, something that might be interesting too. That solution is not possible either because the GambitManager is bound contextually..

I urge you to reconsider the use of unnecessary contextual binding for the stable version.

**Comment by Luceos** [comment]
I now see there is also a `ConfigureDiscussionGambits`

**Comment by tobscure** [comment]
What are the alternatives to contextual binding? Is it possible to do something like:

```php
$this->app->when('Flarum\Core\Command\UploadAvatarHandler')
    ->needs('League\Flysystem\FilesystemInterface')
    ->give('flarum.avatarsFilesystem');

$this->app->bind('flarum.avatarsFilesystem', function () { /* ... */ });

// extensions:
$this->app->resolving('flarum.avatarsFilesystem', function ($filesystem) { /* ... */ });
```

**Comment by Luceos** [comment]
I havent't tested that. But I would also like to suggest to refrain from dot notated bindings, because they cannot be type hinted in class constructors or methods. Creating a simple, unique Interface/Contract that extends another is very easy to do and is way more flexible.

**Comment by tobscure** [comment]
@Luceos how would that work though?

```php
interface AvatarsFilesystemInterface extends FilesystemInterface {
}

class UploadAvatarHandler {
    public function __construct(AvatarsFilesystemInterface $filesystem) {}
}

$this->app->bind(AvatarsFilesystem::class, Filesystem::class); // does not work because Filesystem does not implement AvatarsFilesystemInterface
```

Creating a unique interface/class solely for the purposes of dependency injection is wrong. There's nothing inherently/behaviourally different about the filesystem for avatars — it's a normal filesystem. Thus, the typehint should be Filesystem. The responsibility is on the DI container to provide the right Filesystem instance.

**Comment by Luceos** [comment]
Another solution is to trigger an event when the textual binding is being resolved.

**Comment by franzliedke** [comment]
As far as I can tell, this can now be configured by changing the configuration for the `flarum-avatars` "disk": https://github.com/flarum/core/blob/43c551929bfbc3b106557bcd4f6681b1fa232497/src/Foundation/InstalledSite.php#L177-L180
