### ISSUE TITLE
Cookie name cannot be configured

### ISSUE THREAD

**Issue by LuffyyyffuL** [flarum/core#1115]
Hello,

Sorry for my english.

I have a big problem : 

I have two flarum on my server : 

/var/www/flarum_1 -> https://my_domain.tld/flarum_1
/var/www/flarum_2 -> https://my_domain.tld/flarum_2

Fiew users : 

User_1 -> flarum_1 : ID_1 ; flarum_2 : ID_1 -> Connections to two Flarum OK
User_2 -> flarum_1 : ID_2 ; flarum_2 : ID_3 -> If the user logs in to the flarum_1 and then connects to the flarum_2, it is connected as user 2 instead of 3
User_3 -> flarum_1 : ID_4 ; flarum_2 : ID_2 -> If the user logs in to the flarum_1 and then connects to the flarum_2, it is connected as user 4 instead of 2
User_4 -> flarum_1 : ID_3 ; flarum_2 : ID_4 -> If the user logs in to the flarum_1 and then connects to the flarum_2, it is connected as user 3 instead of 4

Sorry, but it's hard to explain

Is there a solution ? Thank you :) 

## Bug report
- Version of Flarum: 0.1.0-beta.6
- The webserver you are running: nginx
- PHP version: 7.0 with OpCache
- Hosted environment: physical

**Comment by Luceos** [comment]
You're authenticating on the same domain. Both installations use the same cookie name and as a result will re-use the cookie set on one installation. The cookie name has been hard-coded removing any possibility of implementing scenarios you have.

Code reference [x](https://github.com/flarum/core/blob/master/src/Http/Middleware/StartSession.php#L59)

**Comment by LuffyyyffuL** [comment]
Thanks for your feedback.

If I change this way, will my problem be resolved ?

/var/www/flarum_1 -> https://sub_one.my_domain.tld/flarum
/var/www/flarum_2 -> https://sub_two.my_domain.tld/flarum

**Comment by LuffyyyffuL** [comment]
It's OK with sub domain :)

**Comment by Luceos** [comment]
Glad to hear, will keep this open in order to support configurable session names.

**Comment by clarkwinkelmann** [comment]
Looks like @tobscure added this feature in https://github.com/flarum/core/commit/87bf84ef6e1b04d1fa248f7298fb96981251319e

**Comment by tobscure** [comment]
Why yes I did! 😊
