### ISSUE TITLE
Validation errors not translated during installation

### ISSUE THREAD

**Issue by luceos** [flarum/core#1117]
## Bug report
- Version of Flarum: beta 6

When you install with a database prefix of over 10 characters the [command](https://github.com/flarum/core/blob/master/src/Install/Console/InstallCommand.php#L137) will throw a max string error, which is not clear.

Related [thread](https://discuss.flarum.org/d/4767-validation-max-string-500-error-on-install).

**Comment by luceos** [comment]
I'm sure I've seen another issue related to translations inside the installation process, but I can't find it.

**Comment by franzliedke** [comment]
@luceos Do you mean #1212?

**Comment by franzliedke** [comment]
Yep, that must be it. There's also a PR for it, I promise I'll get that in soon!
