### ISSUE TITLE
Improve order of mention auto-completes

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#1118]
When trying to respond to a user, without referring to a particular post that user has made - but when that particular user has already made more than a few posts in that topic - finding the item with just their username in the list of autocompletes is very tricky, because it comes last...

See this screenshot for what I mean:
![flarum-mention-list](https://cloud.githubusercontent.com/assets/249125/22599609/ce6e3934-ea37-11e6-91b2-b7db46f57c2e.png)

My suggestion would be to insert the just-the-name items starting at the second position of the list. Does that make sense? Any other ideas?

**Comment by Luceos** [comment]
Or in the first position. In other circumstances you simply press reply from the specific post. I personally use the reply button (on an open or closed composer window) more often than using the mention functionality to refer to a specific post.

**Comment by tobscure** [comment]
Yeah I agree, the user (without reply) should be displayed first.
