### ISSUE TITLE
Bug with approving messages : not updating values in discussions table (last_user_id, last_post_id, last_time...)

### ISSUE THREAD

**Issue by rastaferraille** [flarum/core#1119]
Hello,

When I approve a message from a user, those values are not uptated at all in discussion table : 

last_user_id
last_post_id
last_post_number
and 
last time 

they're left with their old values.
As a consequence, the discussion page is wrong (last user, last modified, discussion displaying order etc.)

Everything is fine in posts table

I'm using beta 6 version of flarum.
I recently upgraded from beta 5 via composer update command.

Everything works fine for user's posts that do not need to be approved.

> Issues on Github are meant for bug reporting. Please post feature requests on the [discussion forum](https://discuss.flarum.org/t/features).
---
> Try to complete the below form as far as you are able and are willing to share. Add a screenshot of the issue if you can.

## Bug report
- Version of Flarum: beta 6
- Website URL where the bug is visible: http://lutherie-guitare.org/flarum
- The webserver you are running: apache
- PHP version: 5.6.29-0
- Hosted environment: vps
- Hosting provider: ovh

## Flarum info

Flarum core 0.1.0-beta.6
PHP 5.6.29-0+deb8u1
Loaded extensions: Core, date, ereg, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, mbstring, pcntl, session, posix, Reflection, standard, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, PDO, curl, gd, imap, intl, json, mcrypt, mysql, mysqli, pdo_mysql, pspell, readline, ssh2, mhash, Zend OPcache
EXT flarum-approval v0.1.0-beta.6
EXT flarum-bbcode v0.1.0-beta.5
EXT vingle-configure-smtp 0.2.0
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.6
EXT flarum-auth-facebook v0.1.0-beta.6
EXT matpompili-favicon v1.0.0-beta.2
EXT flagrow-upload 0.4.6
EXT flarum-flags v0.1.0-beta.6
EXT milescellar-french v1.0.6
EXT flarum-likes v0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.6
EXT flarum-markdown v0.1.0-beta.5
EXT flarum-mentions v0.1.0-beta.6
EXT flarum-sticky v0.1.0-beta.6
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.6
EXT flarum-tags v0.1.0-beta.7
EXT flarum-auth-twitter v0.1.0-beta.6
Base URL: http://lutherie-guitare.org/flarum

**Comment by franzliedke** [comment]
Thanks for the report! 
This bug was already fixed in PR flarum/flarum-ext-approval#4 and will be released as part of the next beta version. 

If you want to enjoy the fix now, please upgrade to dev-master. :)

**Comment by rastaferraille** [comment]
Hello,

Thank you for your answer and sorry for the bug duplication ! I have'nt
seen it..
Thank you for this great forum !

2017-02-08 12:05 GMT+01:00 Franz Liedke <notifications@github.com>:
