### ISSUE TITLE
Reply composer controls obscure text

### ISSUE THREAD

**Issue by tobscure** [flarum/core#112]
![screen shot 2015-06-19 at 6 54 12 pm](https://cloud.githubusercontent.com/assets/128862/8250622/9b1ddf56-16b4-11e5-8304-5dfd914efdea.png)

**Comment by franzliedke** [comment]
Can we move the controls to a small box in the top right corner above the composer? That would be an easy fix and wouldn't require a lot of vertical padding at the top of the composer itself.

**Comment by tobscure** [comment]
I'm inclined to say that we should just show the normal header, like it shows when you navigate away from the discussion, to keep things simple. I'll make it a bit more compact too. And I think #93 will help to make it feel like there's still heaps of room.

**Comment by franzliedke** [comment]
Makes sense. I think it should read "Write your reply..." (instead of the placeholder), though, at least while looking at the topic you're replying to.

**Comment by tobscure** [comment]
@franzliedke I've kept it as the topic title for now, I think it serves as a nice reminder of the subject so people are more likely to stay on-topic. Also I think the textarea placeholder is useful to indicate where the textarea actually is, since it doesn't have borders.

**Comment by franzliedke** [comment]
How about this then?

> Reply to "Topic title"

I think this would also be better in terms of accessibility.
