### ISSUE TITLE
MS EDGE, Avatar upload, doesn't work.

### ISSUE THREAD

**Issue by 0E800** [flarum/core#1125]
When user browsing flarum site using MS Edge tries to upload avatar image, no image is uploaded. No errors appear in browser console.

**Comment by ch-lopez** [comment]
GIF representation of reproducible bug.

![image](https://user-images.githubusercontent.com/28011231/30868795-9f3e602e-a2ad-11e7-9b8c-079b0cf3f4f8.png)
