### ISSUE TITLE
MS EDGE, Login remember doesn't work

### ISSUE THREAD

**Issue by SMXRanger** [flarum/core#1127]
## Bug report
- Version of Flarum: Flarum v0.1.0-beta.6
- Website URL where the bug is visible: https://discuss.flarum.org (and any other installations)

Login remember resets every time then Microsoft Edge is closed.
Need to login every time when starting Microsoft Edge.

**Comment by Luceos** [comment]
Are you sure this is not a privacy setting in Edge? To drop any cookies/sessions on browser close?

**Comment by SMXRanger** [comment]
Yes, I am sure this is not a privacy setting. Other sites works well, and login not remembered on flarum.org and on my test installation.

**Comment by franzliedke** [comment]
Hmm, we have had a "remember me" feature [for a couple months now](https://github.com/flarum/core/pull/1075) - looks like it is time to roll out the latest dev-master on our support forum...

@SMXRanger Can you check whether this problem occurs on [Devflarum](https://discuss.flarum.org/d/697-devflarum-sandbox-server) as well? That forum runs the latest version.

**Comment by SMXRanger** [comment]
Just tested: same story. Login remember on Devflarum resets every time then Microsoft Edge is closed.

**Comment by franzliedke** [comment]
@SMXRanger Sorry, just to make sure: Did you try with and without the small checkbox beneath the password field? (It is kind of easy to miss.)

**Comment by sijad** [comment]
I tested this on my friend surface, both on Devflarum (with remember me checked) and discuss.flarum.org, it seems cookies saves as sessions. 

request headers:

```
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US, en; q=0.7, fa; q=0.3
Cache-Control: no-cache
Connection: Keep-Alive
Content-Length: 71
Content-Type: application/json; charset=utf-8
Cookie: flarum_session=35886c33e48cfeaa011a98c1ed47c2e3
Host: devflarum.xyzz.work
Referer: https://devflarum.xyzz.work/d/1-info
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393
X-CSRF-Token: aWW6kcRqBUNs6Nc8C3iTp8WiTiUBuvjSx4BLbLzh
```

response headers:

```
Connection: keep-alive
Content-Length: 65
Content-Type: application/json
Date: Tue, 14 Mar 2017 09:55:45 GMT
Server: nginx
Set-Cookie: flarum_remember=20AMA0ZBdv1TUyn8rmX4HXRHlP21v0jsqyqqiKkT; Path=/; Max-Age=1209600; Secure; HttpOnly
Set-Cookie: flarum_session=87689651954865aee392ad189726b797; Path=/; Secure; HttpOnly
Strict-Transport-Security: max-age=15768000
X-CSRF-Token: aWW6kcRqBUNs6Nc8C3iTp8WiTiUBuvjSx4BLbLzh
```

![image](https://cloud.githubusercontent.com/assets/7693001/23895430/e832f174-08ba-11e7-93fc-6894e58acea5.png)

it seems Microsoft browsers [do not support Max-Age in Set-Cookie header](https://msdn.microsoft.com/en-us/library/windows/desktop/aa384321(v=vs.85).aspx)

**Comment by sijad** [comment]
it's an old article but it seems still valid:
http://mrcoles.com/blog/cookies-max-age-vs-expires/
I guess we have to send both `Max-Age` and `Expires` with `Set-Cookie` header

**Comment by sijad** [comment]
and this one https://balanceiskey.github.io/2015/11/25/ie11-cookies.html

**Comment by franzliedke** [comment]
Thanks for unconvering that, @sijad. :)

**Comment by franzliedke** [comment]
Should be fixed now. Thanks for the help, everybody!

(That said, is it possible that we're back to the old buggy behavior of only remembering the login for two weeks after the last login, instead of two weeks after the last visit? See the discussion in #656.)

**Comment by SMXRanger** [comment]
Yes, this issue is fixed now in Edge on https://devflarum.xyzz.work/
Great!

**Comment by SMXRanger** [comment]
Just update Windows 10 on my PC to Creators Update. New version of Edge (Microsoft Edge 40.15063.0.0) remembering login correctly in old Flarum v0.1.0-beta.6.

**Comment by franzliedke** [comment]
@SMXRanger Good to know, thanks! Let's hope this is gone for good now. :)
