### ISSUE TITLE
PHP Fatal error running phpunit tests (mixed case in namespace)

### ISSUE THREAD

**Issue by Strobotti** [flarum/core#1129]
## Bug report
- Version of Flarum: 0.1.0
- PHP version: 7.0.13

As I run modern operating system with a case-sensitive file system (EXT4) I experience the following error running tests:

`PHP Fatal error:  Class 'Tests\Test\TestCase' not found in /home/juha/workspace/flarum/tests/Flarum/Api/Handler/FloodingExceptionHandlerTest.php on line 19`

Would fix this myself and make a pull-request but not sure whether you want the path to be fixed to Tests or the reference to be lower-cased. Personally I would probably want to run the tests inside the tests -root and not include it in the namespace the first place...

**Comment by Luceos** [comment]
The directory tests doesn't have to be fixed, the composer file actually refers to it properly. Something else must be going on here.

- Reference to [composer.json](https://github.com/flarum/core/blob/master/composer.json#L72).

What command do you use to run phpunit?

**Comment by Strobotti** [comment]
I just ran `phpunit` where the phpunit.xml is located.

The abstract TestCase is in namespace Tests\Test however it is located in tests/Test directory

I also propose renaming it to AbstractTestCase as suggested in PSR-naming conventions (http://www.php-fig.org/bylaws/psr-naming-conventions/)

**Comment by Luceos** [comment]
@Strobotti ,

the composer file maps `Tests\` to `tests/`, causing any class inside `tests/` to be found if they are in namespace `Tests\`, so this works..

**Comment by Strobotti** [comment]
Such a stupid mistake: I used system-wide phpunit which was older version; works flawlessly with the one under vendor-folder
