### ISSUE TITLE
Disallow bots to confirmation links

### ISSUE THREAD

**Issue by Luceos** [flarum/core#1133]
As report on the [forums](https://discuss.flarum.org/d/4971-bingbot-automatically-visiting-confirmation-links), some e-mail clients seem to read links in e-mail ( 😢 ) and pre-visit them causing confirmation links to be auto-approved.

As a solution I've suggested to add the confirmation endpoint to the robots.txt; it might be wise to add this endpoint and possibly others there as well to prevent such unwanted interaction to happen.

**Comment by Kakifrucht** [comment]
What about forums in subdirectories though? A shipped robots.txt would be ignored then.

**Comment by franzliedke** [comment]
As explained in [the forums](https://discuss.flarum.org/d/4971-bingbot-automatically-visiting-confirmation-links/6), I don't see much point in this - and also I don't see a security problem here. This will only happen if the email provider decides to visit those links, although it shouldn't - but at the same time it would give us the confirmation that the email really arrived.

So I am closing this for now, until I hear more reports (or @Kakifrucht convinces me it cannot be disabled in the way I suggested in the forums).

**Comment by Luceos** [comment]
@franzliedke remind me to use your e-mail address on all of my 5 million forums. I'd really like to know how you feel about auto approvals then. I don't think you see the full scope of this and it's only a minor thing to add a robots.txt.
