### ISSUE TITLE
Prevent duplicate content for alternative home page URL

### ISSUE THREAD

**Issue by dav-is** [flarum/core#1134]
www.google.com/search?q=site%3Adiscuss.flarum.org/all

This is an issue on a few levels. Why can users access https://discuss.flarum.org/all ? I'm told that there's an infinite number of pages too. Like `https://discuss.flarum.org/all?page={x}`.

**Comment by franzliedke** [comment]
There is no NoJS content in these search results (anymore?), as far as I can tell.

As for the `/all` page - that should only be indexed when Flarum's "Home page" setting is set to "Tags", right? When not, it should have another rel=canonical tag that points to the base URL. And vice versa: When the home page is set to "Tags", the URL `/tags` should not be indexed...

**Comment by TurboProgramming** [comment]
![46745674567](https://user-images.githbusercontent.com/17576065/42312178-5f821aa6-8048-11e8-8c56-c761e412f0dd.png)

@franzliedke

**Comment by luceos** [comment]
@TurboProgramming what is the screenshot about? I see no duplicates, nor an `/all` or `/tags` entry..

**Comment by TurboProgramming** [comment]
@luceos Just a screenshot of a Google search for all replies appearing on the results, this may be something complicated for the user.

But I don't know whether this is related to the current issue.

**Comment by franzliedke** [comment]
The screenshot by @TurboProgramming are about a different problem... see issue #1140, which I just closed. :grin:

*(Moderator note: I am hiding the post with the screenshot - and some replies - so that we can focus on topic here.)*
