### ISSUE TITLE
Zendguardframework requires attention

### ISSUE THREAD

**Issue by xBootstrap** [flarum/core#1139]
>Some arguments deprecated after the update and experiecing the following errors need to be take care of.
---
<pre> Deprecated: The third argument to Zend\Stratigility\MiddlewarePipe() ($out) will be required starting with Stratigility version 2; please see https://docs.zendframework.com/zend-stratigility/migration/to-v2/ for more details on how to update your application to remove this message. in C:\xamppp\htdocs\marketplace\vendor\zendframework\zend-stratigility\src\MiddlewarePipe.php on line 101 </pre>
Also
<pre> Deprecated: The third argument to Zend\Stratigility\MiddlewarePipe() ($out) will be required starting with Stratigility version 2; please see https://docs.zendframework.com/zend-stratigility/migration/to-v2/ for more details on how to update your application to remove this message. in C:\xamppp\htdocs\marketplace\vendor\zendframework\zend-stratigility\src\MiddlewarePipe.php on line 101 
validation.required validation.required. </pre>

**Comment by xBootstrap** [comment]
I just want to add that i was able to fix the issue by rolling back to zend-stratigility older version
<pre>composer require zendframework/zend-stratigility 1.2.1</pre>

**Comment by dav-is** [comment]
#1065
