### ISSUE TITLE
Post doesn't scroll into view when only the very top of it is visible

### ISSUE THREAD

**Issue by tobscure** [flarum/core#114]
Even if a post is mostly off the bottom of the screen, the scrolling code will think it's in view and "pulsate" it rather than scrolling down to it.

**Comment by franzliedke** [comment]
Also, can we make this effect a little more obvious? The pulsating is kinda cool, but also easy to overlook. Maybe we can also add some background color that fades in and out as the box pulsates?

**Comment by tobscure** [comment]
Good point, will come up with something

**Comment by tobscure** [comment]
Can't repro the original issue.

As for the pulsation animation, I think we can wait till we have keyboard shortcuts, which will show an orange bar on the left of the currently-active post.
