### ISSUE TITLE
Url slug

### ISSUE THREAD

**Issue by Stranikevg** [flarum/core#1142]
Slug russian
/vendor/flarum/core/src/Util/Str.php

$cyr  = array('а','б','в','г','д','е','ё','ж','з','и','й','к','л','м','н','о','п','р','с','т','у', 
            'ф','х','ц','ч','ш','щ','ъ', 'ы','ь', 'э', 'ю','я','А','Б','В','Г','Д','Е','Ж','З','И','Й','К','Л','М','Н','О','П','Р','С','Т','У',
            'Ф','Х','Ц','Ч','Ш','Щ','Ъ', 'Ы','Ь', 'Э', 'Ю','Я' );
$lat = array( 'a','b','v','g','d','e','io','zh','z','i','y','k','l','m','n','o','p','r','s','t','u',
            'f' ,'h' ,'ts' ,'ch','sh' ,'sht' ,'a', 'i', 'y', 'e' ,'yu' ,'ya','A','B','V','G','D','E','Zh',
            'Z','I','Y','K','L','M','N','O','P','R','S','T','U',
            'F' ,'H' ,'Ts' ,'Ch','Sh' ,'Sht' ,'A' ,'Y' ,'Yu' ,'Ya' );

$str = str_replace($cyr, $lat, $str);
$str = preg_replace('/[^a-z0-9]/i', '-', $str);

or

$str = transliterator_transliterate('Any-Latin; Latin-ASCII; [\u0080-\uffff] remove', $str);
 $str = strtolower($str);

or
https://github.com/ivanlemeshev/laravel5-cyrillic-slug

**Comment by tobscure** [comment]
See #194
