### ISSUE TITLE
Error 404 for missing tags

### ISSUE THREAD

**Issue by aethior** [flarum/core#1144]
The missing tags show a 200 (Ok) status code. I think these links should use a 404 (Not Found) code.

![image](https://cloud.githubusercontent.com/assets/1769227/23631979/7eac6b9a-02c0-11e7-900a-343c68abfedd.png)

**Comment by tobscure** [comment]
Merging into #906 (this goes hand-in-hand with making the content of tag pages indexable by search engines).
