### ISSUE TITLE
Clicking on profile box during editing removes all changes

### ISSUE THREAD

**Issue by kulga** [flarum/core#1145]
During editing your profile *"Write something about yourself"*, if you click on it after making changes it will revert to its prior saved state.

* Message saved at "Hello world!"
* Change default message
* Click anywhere in box
* Message reverts to "Hello world!"

## Bug report
- Version of Flarum: **dev-master** and **beta.6**
- Website URL where the bug is visible: https://devflarum.xyzz.work/
- The webserver you are running: **nginx**
- PHP version: **7.0.16**
- Hosted environment: **VPS**

![](https://i.imgur.com/IHxQuAX.gif)

**Comment by franzliedke** [comment]
Funky. Nice find. :)
