### ISSUE TITLE
New users do not get emails whenever replied to, or directly mentioned.

### ISSUE THREAD

**Issue by MarkTechComputers** [flarum/core#1152]
> Issues on Github are meant for bug reporting. Please post feature requests on the [discussion forum](https://discuss.flarum.org/t/features).
---
> Try to complete the below form as far as you are able and are willing to share. Add a screenshot of the issue if you can.

## Bug report
- Version of Flarum: 0.1.0-beta.6
- Website URL where the bug is visible: https://markwithtech.com
- The webserver you are running: Apache
- PHP version: 5.5
- Hosted environment: Shared
- Hosting provider: https://markwebhosting.com

Users can change these options just fine, but these are the default options. Any way to change them, or is this a bug?

![image](https://cloud.githubusercontent.com/assets/19245591/24731310/037814f4-1a1e-11e7-9b22-4dd4aadcc0d8.png)

**Comment by Luceos** [comment]
Thanks for sending in this report. In order to clarify the issue you have, can you answer the following please?

- What is the expected behavior?
- What behavior did you get?

**Comment by datitisev** [comment]
@MarkTechComputers I think you want to know how to enable email notifications.
Just click on the red cross and it will change to a green check mark once it enables.

**Comment by MarkTechComputers** [comment]
@Luceos
I expect the user to not have to enable those options. They should all be enabled by default.

@datitisev
It's not the issue of me personally knowing how to press buttons, it's the users who doesn't know about them who need them checked.

**Comment by tobyzerner** [comment]
Duplicate of flarum/issue-archive#329

**Comment by MarkTechComputers** [comment]
Is there any way to hard-code defaults for all new users?
