### ISSUE TITLE
Maintainer Request

### ISSUE THREAD

**Issue by Theaxiom** [flarum/core#1154]
I would like to formally request to become a maintainer of Flarum. Here are some links about me:
- https://github.com/Dynamictivity
  - My company's open-source projects
- https://www.linkedin.com/in/travisrowland

I am currently a core maintainer on the following projects:
- http://phusion.github.io/baseimage-docker/
  - https://github.com/phusion/baseimage-docker
- http://mantl.io/
  - https://github.com/mantl/mantl

I've been using PHP since the year 2000 and I have been using OOP RAD MVC frameworks such as CakePHP since 2003. I am a DevOps engineer by trade and work as a lead engineer and architect at Ericsson Inc., one of the largest communication companies in the world.

Thank you for your time and consideration, I will be pushing several updates over the coming weeks as I will be using Flarum as a core piece of a product I just released: http://taughtful.com

-- Travis

**Comment by albertalbs** [comment]
I am in. 
Happy to Accept 👍

**Comment by dav-is** [comment]
I would start by submitting some PRs and see where things go from there.

**Comment by Theaxiom** [comment]
Sounds like a plan. 😀

**Comment by franzliedke** [comment]
Hello Travis,

first of all, thank you very much for your willingness to contribute to Flarum! We are grateful for any help that we receive, and are looking forward to your contributions.

Please understand that we currently maintain a policy of **inviting community members** to become part of the core team, based on their contributions and their activity in the community.

What you can do to make this more likely:
- Take a look at some of the issues that are [planned for the short-term future](https://github.com/flarum/core/milestone/7).
- Comment on issues once you consider actively working on them.
- Send pull requests, and don't be afraid to send them in an unfinished state. 
- For everything else, please consult our [contributor guide](https://github.com/flarum/flarum/blob/master/CONTRIBUTING.md).

To discuss and influence the direction of core development, please join the corresponding [public chat room for those discussions](https://gitter.im/flarum/internals).

Looking forward to your contributions! If you need help with anything while getting started, please let us know in the forums or the chat room.
Franz & Team

**Comment by Theaxiom** [comment]
Thanks @franzliedke -- I appreciate the response and it makes complete sense. 👍

**Comment by albertalbs** [comment]
Looks like I can exit
