### ISSUE TITLE
[LOCK] Make locked threads read-only

### ISSUE THREAD

**Issue by 0E800** [flarum/core#1156]
Posts inside locked threads are still editable by post owner.

If there was a way to make the lock thread  be read-only, it would prevent editing.

Better yet, just disable/remove the edit button in the same way the reply button is unavailable.

Something I feel should be enhanced.

Flarum Reference: 
https://discuss.flarum.org/d/5451-make-locked-threads-read-only

**Comment by franzliedke** [comment]
I fixed this - edits are now not allowed when a discussion is locked. Unless the actor has the right to lock/unlock the discussion: then we fall back to the "default" behavior (i.e. so that admins can still edit things). Does that make sense?

**Comment by 0E800** [comment]
Excellent. Thank you.
