### ISSUE TITLE
Suspending - users may self-edit post / post ownership lost

### ISSUE THREAD

**Issue by kulga** [flarum/core#1157]
(GIF is 7MB, linked but not embedded)
https://i.imgur.com/gAhBgQf.gif
https://i.imgur.com/gAhBgQf.mp4

## Bug report
- Version of Flarum: dev-master
- Website URL where the bug is visible: https://devflarum.xyzz.work

## Additional comments

Suspended users may
* Self-edit or delete their own post if they are the last to post [01:35]
* Rename thread if they created it [02:29]

Note: When users are suspended, some of it is **non-reversible**. Some posts appear to be *lost* to the user when unsuspended, and acts like the post is from a foreign user [02:19 in video]

**Comment by aethior** [comment]
Yes, I can confirm it. Suspended users should not be able to edit posts.

**Comment by luceos** [comment]
Relates to #1419

**Comment by tobscure** [comment]
Not just relates, I think this is the same as #1419
