### ISSUE TITLE
Some emojis don't work

### ISSUE THREAD

**Issue by Zeokat** [flarum/core#1159]
## Bug report
- Version of Flarum: Flarum v0.1.0-beta.6
- Website URL where the bug is visible: https://discuss.flarum.org/d/5508-some-emoticos-are-broken/2
- The webserver you are running: apache and nginx (both tested)
- PHP version: 7.0
- Hosted environment: Local machine with Linux Ubuntu, local machine with Windows, VPS with Linux Ubuntu.
- Hosting provider: DigitalOcean

## Flarum info

```
zeokat@ubuntu:/var/www/html/flarum$ php flarum info
Flarum core 0.1.0-beta.6
PHP 7.0.15-0ubuntu0.16.04.4
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, Zend OPcache
EXT flarum-approval v0.1.0-beta.6
EXT flarum-bbcode v0.1.0-beta.5
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.6
EXT flarum-flags v0.1.0-beta.6
EXT flarum-likes v0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.6
EXT flarum-markdown v0.1.0-beta.5
EXT flarum-mentions v0.1.0-beta.6
EXT flarum-sticky v0.1.0-beta.6
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.6
EXT flarum-tags v0.1.0-beta.7
Base URL: http://192.168.247.128/flarum
Installation path: /var/www/html/flarum
```

## Additional comments
I tryed many different browsers (FireFox, Chrome and Opera with same result). My browsers use spanish language and i also have keyboard layout in spanish.

## Log files

```
Empty
```

**Comment by franzliedke** [comment]
@Zeokat Can you please confirm that the suggestion by @JoshyPHP in https://discuss.flarum.org/d/5508-some-emoticos-are-broken/7 works? If so, this ticket can probably be closed...

**Comment by Zeokat** [comment]
What JoshyPHP suggested was to emojis already added into old posts. But the bug on beta, is present on new emojis added into new posts.
@franzliedke emojis works good into developmet version, **only fails on beta 6**. I think that this issue can be closed.

**Comment by franzliedke** [comment]
Great, thanks for clarifying!
