### ISSUE TITLE
Entering a non-existent email breaks forgot password

### ISSUE THREAD

**Issue by tobscure** [flarum/core#116]
https://gitter.im/flarum/flarum?at=5583fabd6f7465873a35fbf4

**Comment by tobscure** [comment]
Fixed in a20e2591e6cec0875efe8ca7df5f45bb3236befe

**Comment by franzliedke** [comment]
Awww, I had wanted to fix this. ;)

**Comment by tobscure** [comment]
Haha sorry, I figured it was reasonably urgent with quite a few people coming in to reset their passwords and whatnot :P
