### ISSUE TITLE
Use short time-ago strings

### ISSUE THREAD

**Issue by tobscure** [flarum/core#117]
i.e. 5m ago instead of 5 minutes ago

We had this before the last update, I took it out because it means creating some custom logic/translations for time-ago rather than using moment.js's.

**Comment by franzliedke** [comment]
What's the rationale for this besides freeing up some space? If we don't have serious problems, i.e. not enough room, I'd be against it, as it could make people think...

**Comment by tobscure** [comment]
Mainly freeing up space and reducing clutter, especially when the discussion list is in the sidepane. But I'm not completely adamant, maybe it's not worth it

**Comment by franzliedke** [comment]
I vote :-1: then.  ;)
