### ISSUE TITLE
Emoji Suggestion Pop-Up Not Working in IE 11

### ISSUE THREAD

**Issue by Ralkage** [flarum/core#1174]
## Bug report

- Version of Flarum: 0.1.0-beta.6
- Website URL where the bug is visible: localhost
- The webserver you are running: apache, nginx or something else
- PHP version: 7.1.4
- Hosted environment: localhost
- Hosting provider: localhost

## Additional comments
I've noticed that using the bundled emoji extension on IE 11 (The latest build) on Windows 10 is a bit buggy. To clarify, when you start typing the emoji you want to use, the suggestion pop-up doesn't appear. It does work Chrome and Firefox.

**Example:**

![](https://i.gyazo.com/99680c877280208fe89a7711b79933ef.gif)

If this has been already reported, please excuse my blindness. I wasn't sure if this is where I can post issues on bundled extensions either but it was worth a try. 😂

**Comment by franzliedke** [comment]
@Ralkage Are there any errors in the JavaScript console of your browser?

Can anybody else reproduce this?

**Comment by TurboProgramming** [comment]
I'm able to reproduce this using IE 11. GIF below.

![ezgif-4-b0610fb9b2](https://user-images.githubusercontent.com/17576065/42763046-9bb46710-891a-11e8-9f93-ebf27dd4938e.gif)

**Comment by Ralkage** [comment]
@franzliedke whoops, did not see your comment until now, my apologies! I’m going to try and reproduce this again now that beta 8(.1) is out so it’ll be one less issue to add onto the hundreds that are open now :)

**Comment by Ralkage** [comment]
@franzliedke this is no longer an issue in Beta 8(.1) as I can confirm it as working again the latest build of IE11.

See screenshot below:
![image](https://user-images.githubusercontent.com/2059356/56780727-749e1b80-67ae-11e9-8995-cd0fccdd507a.png)

I am going to go to proceed with the closure of this issue as it looks to be fixed and functioning as intended.
