### ISSUE TITLE
Confusion about comment_count, discussions

### ISSUE THREAD

**Issue by MichaelBelgium** [flarum/core#1176]
I am not sure if this is a bug or a mistake or any kind. But why does "comment_count + 1" get applied every time? 

For example you have this topic:
![image](http://puu.sh/vFqpz.png)

How come `comment_count` is 3 from in the database? I agree there are 3 posts in that discussion but only 2 comments. 
![image](https://puu.sh/vFq16.png)

In the discussion list it shows 2 nonetheless:
![image](http://puu.sh/vFqAL.png)

## Bug report
- Version of Flarum: latest
- Website URL where the bug is visible: http://lmdm.exp-gaming.net
- The webserver you are running: apache
- PHP version: 5.6.30
- Hosted environment: vps
- Hosting provider: http://www.ovh.nl

## Flarum info

```
Flarum core 0.1.0-beta.6
PHP 5.6.30
Loaded extensions: Core, date, ereg, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, ssh2, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, json, exif, mcrypt, mysql, mysqli, PDO, pdo_mysql, pdo_sqlite, Phar, shmop, SimpleXML, sockets, sqlite3, tokenizer, xml, wddx, xmlreader, xmlwriter, xsl, zip, mhash
EXT flarum-bbcode v0.1.0-beta.5
EXT flarum-english v0.1.0-beta.6
EXT flarum-likes v0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.6
EXT flarum-mentions v0.1.0-beta.6
EXT flarum-sticky v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.6
EXT flarum-tags v0.1.0-beta.7
Base URL: http://lmdm.exp-gaming.net
Installation path: /var/www/html/lmdm
```

**Comment by franzliedke** [comment]
I think this works just as intended. The discussion list shows the number of replies a thread received, and the database stores the number of posts in a discussion. *All* of them are considered "comments".

If you want to debate this whole concept, please open a discussion in the community forums. :)
