### ISSUE TITLE
Migrations architecture

### ISSUE THREAD

**Issue by tobscure** [flarum/core#119]
Currently we are using standard timestamped Laravel migrations (e.g. `2015_02_24_000000_create_access_tokens_table.php`).

Running `php artisan flarum:install` runs these migrations.

Extensions also use the same migration format, and they currently need to be run manually with `php artisan migrate --path="..."`.

Obviously when we build the installer/admin UI we will have a GUI to run migrations. However, we should think about what migration architecture we want to use.

- Do we want to use the classic timestamped migration format, and create new migrations instead of modifying old ones starting from beta release? Or do we want to do something else (@franzliedke what was your plan for [FluxBB2](https://github.com/fluxbb/core/tree/master/src/Migrations/Install)? Grouping migrations by "release version"?)
- Do we want to continue to use Illuminate\Migrations?
- In addition to DB updates, is it a good idea to also use migrations for other upgrade tasks that may need to be performed (e.g. creating files/folders)?

**Comment by tobscure** [comment]
@franzliedke I know we discussed grouping migrations by release version, but on second thoughts, is there any advantage to this other than it being a bit prettier? Because it probably adds unnecessary complexity.

**Comment by tobscure** [comment]
As well, having installation migrations separate from upgrade migrations introduces some more complexity/potential for bugs. The advantage is quicker installation, but would it really be that noticeable? Applying a load of upgrade migrations to an empty database wouldn't be that slow, I wouldn't think...

**Comment by franzliedke** [comment]
Okay, I'll try building the installer to use the upgrade migrations. We'll see if that causes problems; if so, we can still switch to streamlined migrations for the installer.

Regarding grouping migrations: I think that may be helpful when developing, because we can switch code between versions, and then use the command line to switch the database / file structure to conform to that version...

**Comment by tobscure** [comment]
Fair point, makes sense.

**Comment by tobscure** [comment]
This is interesting: http://octobercms.com/docs/plugin/registration#migrations-version-history

**Comment by tobscure** [comment]
@franzliedke Not sure how much you've done so far, but if grouping migrations by release complicates things too much, don't worry about it – it's easy enough to use git tags to work out what migration to roll back to, so the use-case you mentioned doesn't *necessitate* it. Number one priority right now is just something that works :)

**Comment by franzliedke** [comment]
Okay, I'll leave it out if it gets too complex.

**Comment by tobscure** [comment]
This is done
