### ISSUE TITLE
In the Admin > Basics > Forum Description, there's a button called "core.admin.basics.show_language_selector_label"

### ISSUE THREAD

**Issue by ShenZhouHong** [flarum/core#1192]
## Bug report
- Version of Flarum: `dev-master`
- Website URL where the bug is visible: `https://devflarum.xyzz.work/admin#/basics`
- The webserver you are running: ???
- PHP version: ???
- Hosted environment: ???
- Hosting provider: ???

## Flarum info
Sorry for the sparse information. In the test flarum instance hosted at https://devflarum.xyzz.work, there seems to be a button that isn't labeled properly. In the `admins/basic` section ([link here](https://devflarum.xyzz.work/admin#/basics)) there's a button labeled with `core.admin.basics.show_language_selector_label`. Perhaps it is incorrectly localized/translated.

## Additional comments
None

## Log files
None

**Comment by Zeokat** [comment]
Maybe this happens becasue an outdated localization is activated under extensions.

**Comment by ShenZhouHong** [comment]
@Zeokat I have disabled all extensions except "English", and the problem persists. When I disable the "English" extension, it appears that all localization is removed - and everything becomes machine labels like `core.admin.basics.show_language_selector_label`. I'm pretty sure this is a problem in the English localization.

**Comment by datitisev** [comment]
That is not beta 6. That is dev-master, which is the development version. Devflarum updates every day to the latest development.

**Comment by ShenZhouHong** [comment]
Ah, okay. The same problem seems to be there for the German extension as well. Perhaps this `core.admin.basics.show_language_selector_label` label is for a new feature on which the localization hasn't catched up yet.

**Comment by datitisev** [comment]
Yeah, that's something that I overlooked 🤦‍♂️ 
It's a new feature. All in due time. Thanks, though!

**Comment by ShenZhouHong** [comment]
Alright! :) feel free to close this when the bug is fixed :D
