### ISSUE TITLE
PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at vendor/illuminate/database/Connectors/Connector.php:55

### ISSUE THREAD

**Issue by redrain-wang** [flarum/core#1196]
PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at vendor/illuminate/database/Connectors/Connector.php:55

**Comment by Luceos** [comment]
Run:

```
composer install --no-dev --prefer-dist
```

**Comment by Luceos** [comment]
Disregard my previous comment. Seems your settings are incorrect, see https://discuss.flarum.org/d/2110-on-db-connection-fail-reveal-db-related-sensitive-data

For support please use the support forums.
