### ISSUE TITLE
Build Notifications system

### ISSUE THREAD

**Issue by tobscure** [flarum/core#12]
Flarum's core will need to have a notification framework in place for extensions to make use of.

This should be loosely based on esoTalk's notifications/activity model. You can read about how that works in the [esoTalk documentation](http://esotalk.org/docs/plugins/activity). Also, the esoTalk source is well-commented — take a look at that if you are interested in this.

I’ll write more about this as it becomes more of a priority.

**Comment by tobscure** [comment]
Done!

**Comment by solhuebner** [comment]
:+1:

**Comment by franzliedke** [comment]
You're a machine!

**Comment by Holyphoenix** [comment]
:O  Wahoo!
