### ISSUE TITLE
Command-line interface

### ISSUE THREAD

**Issue by tobscure** [flarum/core#120]
- [x] Turn `php artisan` into `php flarum`
- [x] Probably ditch Illuminate's console stuff and just use Symfony's?

What commands do we need? We will aim for most things (installation, upgrade, import) to be doable via GUI, but it can't hurt to be able to manage on the CLI too. I'm a fan of [drush](http://www.drush.org/en/master/) for example.

- `php flarum install` — prompt the user for their info, run the common installation script (or should we extract this into a separate package?)
- `php flarum upgrade` — run outstanding migrations (related #119)
- `php flarum seed` — generate dummy data (or should we extract this into a separate package?)
- `php flarum generate:extension`
- `php flarum generate:locale --extension="..."`
- `php flarum generate:theme`
- `php flarum generate:migration --extension="..."`

**Comment by franzliedke** [comment]
I've taken care of renaming the script, updating Vagrant's installation files and renaming the existing commands.

**Comment by tobscure** [comment]
This is done

**Comment by axadr** [comment]
"php flarum generate:extension" generates many errors but no extension

**Comment by tobscure** [comment]
Yeah we haven't kept it updated... #743
