### ISSUE TITLE
Translation output as string as well as array

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#1200]
## Flarum info
- Version of Flarum: beta6, master

The `apply` method of the translator returns the translated text with the different parts as an array, which makes it easy to inject mithril nodes inside translation placeholder.

However this can cause issues for simple string interpolations in string context.

For example, the following translations:

```yaml
placeholder: Example: {example}
```

Injected like this:

```js
placeholder: app.translator.trans('example', {
    example: 'Hello world'
})
```

Will produce `Example: ,Hello World` as a placeholder, because the array is `join`ed as a string with the default glue `,`.

We can work around the issue by joining the array ourselves:

```js
placeholder: app.translator.trans('example', {
    example: 'Hello world'
}).join('')
```

But it's not pretty. This code is confusing. The way the current `trans` method work is confusing as well (mostly because it's undocumented https://github.com/flarum/core/blob/master/js/lib/Translator.js).

There's usually no issue because Mithril accepts a table of node and will join them together in an HTML fashion, thus not adding comas. But in `value` or `placeholder` fields, or when we try to concatenate the translation to something a coma is inserted by default because the value gets casted to string first.

There should probably two `trans` method, one returning only a string and the other one allowing object placeholders to go through untouched. In my opinion the default one should stick to string, as I believe it's what most people think it's doing anyway. And provide a second method (`transAsNodes`, `transAsArray`, ... ?) that allows objects to pass through and be used in the DOM.

**Comment by tobscure** [comment]
Thanks for the detailed report!

Our approach for `value` or `placeholder` fields thus far has been to wrap it with the `extractText` util, which is a bit more clear than `.join('')` but admittedly still not pretty.

I think a second `trans` method could be a better solution, we'll definitely consider this!

**Comment by clarkwinkelmann** [comment]
I've never seen `extractText` used in an extension, I'll definitively have a look at that :upside_down_face:

**Comment by clarkwinkelmann** [comment]
I found this issue again and I had completely forgotten it was me who opened it.

Since 2017 I'm actually used `extractText()` a lot, and I think it's a good enough solution.

I see @datitisev added new methods to the Translator on the Mithril rewrite branch. I don't know if that's really necessary.

If any change is made to the translator to allow text output it would be best made as its own PR.

I say we close this issue. There's nothing that absolutely needs to be changed.
