### ISSUE TITLE
Includes are hardcoded for current user in WebAppView

### ISSUE THREAD

**Issue by luceos** [flarum/core#1205]
It's difficult to add additional default includes to a user. The cause of this originates in the WebAppView:

```php
protected function getUserDocument(Request $request)
    {
        $actor = $request->getAttribute('actor');

        $this->userSerializer->setActor($actor);

        $resource = new Resource($actor, $this->userSerializer);

        $document = new Document($resource->with('groups'));

        return $document->toArray();
    }
```

There is no event to modify the Resource further. I think adding an event might not be the best solution, instead we should most likely revert back (according to @tobscure) to calling the API again.

Source: https://github.com/flarum/core/blob/master/src/Http/WebApp/WebAppView.php#L444

**Comment by askvortsov1** [comment]
This code no longer exists, and the replacement doesn't have this issue, as it uses ShowUserController under the surface
