### ISSUE TITLE
[ErrorException]  An on-numeric value encountered

### ISSUE THREAD

**Issue by zhoujianwei** [flarum/core#1209]
PHP version 7.15
Composer version @package_branch_alias_version@ (1.0.0-beta2)

root@san2A:/var/www/html# composer update -vvv
Reading ./composer.json
Loading config file ./composer.json
Checking CA file /etc/ssl/certs/ca-certificates.crt
Executing command (/var/www/html): git branch --no-color --no-abbrev -v
Executing command (/var/www/html): git describe --exact-match --tags
Failed to initialize global composer: Composer could not find the config file: /root/.config/composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /var/www/html/vendor/composer/installed.json
Loading plugin Studio\Composer\StudioPlugin
Loading composer repositories with package information
Downloading https://packagist.org/packages.json
Writing /root/.cache/composer/repo/https---packagist.org/packages.json into cache
Updating dependencies (including require-dev)
Reading /root/.cache/composer/repo/https---packagist.org/p-provider-2013.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/p-provider-2014.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/p-provider-2015.json from cache
Downloading http://packagist.org/p/provider-2016%24d40247ef249cc2c0f4b6497bed7afeb662845838283f3f3080954fdbf2cf26cf.json
Writing /root/.cache/composer/repo/https---packagist.org/p-provider-2016.json into cache
Reading /root/.cache/composer/repo/https---packagist.org/p-provider-2016-10.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/p-provider-2017-01.json from cache
Downloading http://packagist.org/p/provider-2017-04%24fac58a10ae2956f6cf13ae5d125669a1da587a0f98931fca1b951fe9567913d0.json
Writing /root/.cache/composer/repo/https---packagist.org/p-provider-2017-04.json into cache
Downloading http://packagist.org/p/provider-2017-07%24b1f9e822885e7cdc672ef74443c3d6b36e17196f8377ddb80f7a26277be97a8d.json
Writing /root/.cache/composer/repo/https---packagist.org/p-provider-2017-07.json into cache
Reading /root/.cache/composer/repo/https---packagist.org/p-provider-archived.json from cache
Downloading http://packagist.org/p/provider-latest%248b7beb4bc1dff245da6458b4fb9697e4295213d649c16bafa26a78d0b8b4b151.json
Writing /root/.cache/composer/repo/https---packagist.org/p-provider-latest.json into cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-tobscure$json-api.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-nikic$fast-route.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-psr$http-message.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-dflydev$fig-cookies.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-symfony$process.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-symfony$filesystem.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-psr$log.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-symfony$polyfill-mbstring.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-symfony$debug.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-symfony$console.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-franzl$studio.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-components$font-awesome.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-doctrine$lexer.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-doctrine$collections.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-doctrine$cache.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-doctrine$annotations.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-doctrine$inflector.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-doctrine$common.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-doctrine$dbal.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-zendframework$zend-diactoros.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-filp$whoops.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-franzl$whoops-middleware.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-danielstjules$stringy.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-illuminate$contracts.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-paragonie$random-compat.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-illuminate$support.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-illuminate$pipeline.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-illuminate$bus.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-symfony$translation.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-nesbot$carbon.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-illuminate$cache.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-symfony$finder.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-illuminate$filesystem.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-illuminate$config.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-illuminate$container.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-illuminate$database.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-illuminate$hashing.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-swiftmailer$swiftmailer.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-illuminate$mail.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-symfony$http-foundation.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-illuminate$validation.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-illuminate$events.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-illuminate$view.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzlehttp$psr7.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-intervention$image.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-league$flysystem.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-matthiasmullie$path-converter.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-matthiasmullie$minify.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-monolog$monolog.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-oyejorge$less.php.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-s9e$text-formatter.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-symfony$yaml.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-http-interop$http-middleware.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-zendframework$zend-escaper.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-zendframework$zend-stratigility.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-ircmaxell$security-lib.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-ircmaxell$random-lib.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzlehttp$promises.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-tijsverkoyen$akismet.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzlehttp$guzzle.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-league$oauth2-client.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flarum$core.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-symfony$polyfill-php54.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-symfony$polyfill-php55.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-ircmaxell$password-compat.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flarum$flarum-ext-flags.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flarum$flarum-ext-approval.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flarum$flarum-ext-akismet.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-league$oauth2-facebook.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flarum$flarum-ext-auth-facebook.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-league$oauth2-github.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flarum$flarum-ext-auth-github.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-league$oauth1-client.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flarum$flarum-ext-auth-twitter.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzle$guzzle.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-symfony$event-dispatcher.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flarum$flarum-ext-bbcode.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flarum$flarum-ext-emoji.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flarum$flarum-ext-english.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flarum$flarum-ext-likes.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flarum$flarum-ext-lock.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flarum$flarum-ext-markdown.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flarum$flarum-ext-mentions.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-pusher$pusher-php-server.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flarum$flarum-ext-pusher.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flarum$flarum-ext-sticky.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flarum$flarum-ext-subscriptions.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flarum$flarum-ext-suspend.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flarum$flarum-ext-tags.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-jsthon$flarum-ext-simplified-chinese.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-xengine$flarum-ext-markdown-editor.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-sijad$flarum-ext-details.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-s9e$flarum-ext-mediaembed.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-sijad$flarum-ext-spoiler-alert.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-ramsey$uuid.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flagrow$upload.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flagrow$ads.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-davis$flarum-ext-customfooter.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flarum$flarum.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flarum$approval.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-flarum$flags.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-symfony$http-kernel.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-franzliedke$studio.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-symfony$dependency-injection.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-symfony$config.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-league$flysystem-sftp.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-tightenco$collect.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzle$batch.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzle$cache.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzle$common.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzle$http.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzle$inflection.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzle$iterator.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzle$log.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzle$parser.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzle$plugin.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzle$plugin-async.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzle$plugin-backoff.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzle$plugin-cache.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzle$plugin-cookie.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzle$plugin-curlauth.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzle$plugin-history.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzle$plugin-log.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzle$plugin-mock.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzle$plugin-oauth.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzle$service.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzle$stream.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzle$plugin-md5.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-guzzle$plugin-error-response.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-sijad$flarum-spoiler.json from cache
Reading /root/.cache/composer/repo/https---packagist.org/provider-rhumsaa$uuid.json from cache
Resolving dependencies through SAT
Dependency resolution completed in 3.142 seconds
Analyzed 7844 packages to resolve dependencies
Analyzed 85461 rules to resolve dependencies
  - Updating doctrine/collections (v1.4.0 => v1.5.0)
Executing command (/var/www/html/vendor/doctrine/collections): git show-ref --head -d
Executing command (/var/www/html/vendor/doctrine/collections): git status --porcelain --untracked-files=no
    The package has modified files:
    M .gitattributes
    M .gitignore
    M .scrutinizer.yml
    M .travis.yml
    M CONTRIBUTING.md
    M LICENSE
    M README.md
    M composer.json
    M lib/Doctrine/Common/Collections/AbstractLazyCollection.php
    M lib/Doctrine/Common/Collections/ArrayCollection.php

                                   
  [ErrorException]                 
  A non-numeric value encountered  
                                   

Exception trace:
 () at /usr/share/php/Composer/Downloader/GitDownloader.php:223
 Composer\Util\ErrorHandler::handle() at /usr/share/php/Composer/Downloader/GitDownloader.php:223
 Composer\Downloader\GitDownloader->cleanChanges() at /usr/share/php/Composer/Downloader/VcsDownloader.php:116
 Composer\Downloader\VcsDownloader->update() at /usr/share/php/Composer/Downloader/DownloadManager.php:268
 Composer\Downloader\DownloadManager->update() at /usr/share/php/Composer/Installer/LibraryInstaller.php:197
 Composer\Installer\LibraryInstaller->updateCode() at /usr/share/php/Composer/Installer/LibraryInstaller.php:109
 Composer\Installer\LibraryInstaller->update() at /usr/share/php/Composer/Installer/InstallationManager.php:172
 Composer\Installer\InstallationManager->update() at /usr/share/php/Composer/Installer/InstallationManager.php:139
 Composer\Installer\InstallationManager->execute() at /usr/share/php/Composer/Installer.php:569
 Composer\Installer->doInstall() at /usr/share/php/Composer/Installer.php:228
 Composer\Installer->run() at /usr/share/php/Composer/Command/UpdateCommand.php:173
 Composer\Command\UpdateCommand->execute() at /usr/share/php/Symfony/Component/Console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /usr/share/php/Symfony/Component/Console/Application.php:841
 Symfony\Component\Console\Application->doRunCommand() at /usr/share/php/Symfony/Component/Console/Application.php:189
 Symfony\Component\Console\Application->doRun() at /usr/share/php/Composer/Console/Application.php:166
 Composer\Console\Application->doRun() at /usr/share/php/Symfony/Component/Console/Application.php:120
 Symfony\Component\Console\Application->run() at /usr/share/php/Composer/Console/Application.php:99
 Composer\Console\Application->run() at /usr/bin/composer:44

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

**Comment by datitisev** [comment]
Looks like an error with composer itself. What version are you using? Try to update as well.

**Comment by zhoujianwei** [comment]
@datitisev i have fixed by update composer now.
