### ISSUE TITLE
"falase" value set for "Forum Description"

### ISSUE THREAD

**Issue by Ralkage** [flarum/core#1210]
## Bug report
- Version of Flarum: 0.1.0-beta.7
- Website URL where the bug is visible: localhost
- The webserver you are running: apache, nginx or something else
- PHP version: 7.1.2
- Hosted environment: localhost
- Hosting provider: N/A

## Flarum info

```
Flarum core 0.1.0-beta.7
PHP 7.0.10
Loaded extensions: Core, bcmath, calendar, ctype, date, filter, hash, iconv, jso
n, mcrypt, SPL, pcre, Reflection, session, standard, mysqlnd, tokenizer, zip, zl
ib, libxml, dom, PDO, bz2, SimpleXML, xml, wddx, xmlreader, xmlwriter, openssl,
curl, fileinfo, gd, gettext, gmp, intl, imap, ldap, mbstring, exif, mysqli, Phar
, pdo_mysql, pdo_sqlite, soap, sockets, sqlite3, xmlrpc, xsl
EXT flarum-approval v0.1.0-beta.7
EXT flarum-bbcode v0.1.0-beta.5
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.7
EXT flarum-flags v0.1.0-beta.7
EXT flarum-likes v0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT flarum-mentions v0.1.0-beta.7
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8
Base URL: http://localhost/fbeta7
Installation path: C:\wamp64\www\fbeta7
```

## Additional comments
![defbyg1](https://user-images.githubusercontent.com/2059356/28534483-dce5738e-706e-11e7-8137-266672099ab8.png)

As shown above, the default value of the "Forum Description" is "false". I'm not sure if this was left intentional or not but beta 6 did not have a default value for this textarea.

## Log files

```
N/A
```

**Comment by franzliedke** [comment]
Seems to be coming from [this change](https://github.com/flarum/core/commit/60d3d6ef99e6674b7d6b2e2d33f13050cbe95d59#diff-6c89669303932293b681887d130b0458L26).
