### ISSUE TITLE
Forcing a relationship in the API result through include

### ISSUE THREAD

**Issue by luceos** [flarum/core#1217]
Related to #1205 it seems that the AbstractSerializeController does not allow any include to be added by default. For instance, I need all DiscussionSerializers to pass the recipients (private discussion) to the ListDiscussionController results. I listen to the event to ConfigureApiController, which adds a non-optional include. This works:

![image](https://user-images.githubusercontent.com/504687/28776285-49211ec2-75f6-11e7-8150-07d03192ea2a.png)

Now whenever you add the `include` param in the request, with any value, all includes are dropped. The include param is checked against optional and non-optional includes defined. But all non-optional includes are dropped. See:

![image](https://user-images.githubusercontent.com/504687/28776330-79db6388-75f6-11e7-9ed9-6be26a19fd9b.png)

This is happening on the tag specific page; with a request like:

```
http://flarum.dev/api/discussions?include=startUser%2ClastUser%2CstartPost%2Ctags&filter%5Bq%5D=%20tag%3Ageneral&
```

I'm not too sure how to solve this, but it seems better to add the relationships that are defined as non-optional to all return responses..

**Comment by tobscure** [comment]
To do so would be to directly contradict the [JSON-API spec](http://jsonapi.org/format/#fetching-includes)...

> If an endpoint supports the include parameter and a client supplies it, the server MUST NOT include unrequested resource objects in the included section of the compound document.

I think the solution is to manually add the extra include in the frontend, when the DiscussionList component makes its API request: https://github.com/flarum/flarum-ext-tags/blob/master/js/forum/src/addTagFilter.js#L44-L45

Does this work for you? Just want to confirm that it does, then we can talk about making this easier

**Comment by luceos** [comment]
That should work, I'd have to try. Never seen that frontend functionality before.

Thanks!

**Comment by luceos** [comment]
That fixed it.
