### ISSUE TITLE
Admin url is hardcoded in SessionDropdown

### ISSUE THREAD

**Issue by luceos** [flarum/core#1219]
Seems like we are allowing the admin url to be configured from `config.php` but that does not have any effect to the ux because the `/admin` path has been [hardcoded](https://github.com/flarum/core/blob/master/js/forum/src/components/SessionDropdown.js#L70).

If I'm not mistaken it would be rather easy pushing the config setting to the ux in case the user is an admin and then modify that link.

**Comment by tobscure** [comment]
Yep, just need another attribute in the forum API (GET /api/forum) if the user is an admin

**Comment by luceos** [comment]
Seems like that is already implemented:

https://github.com/flarum/core/blob/master/src/Api/Serializer/ForumSerializer.php#L88

**Comment by franzliedke** [comment]
Fixed. While doing that I noticed that there was no need to re-implement the logic for when the link should be visible. We can just base that on the presence of the `adminUrl` field. (Which is something we can do in some other places as well, I believe.)
