### ISSUE TITLE
Build installer

### ISSUE THREAD

**Issue by tobscure** [flarum/core#122]
- Should we have this as a separate package/repo, or in core?
- Build a common installation process, which:
    - Writes config (related #121)
    - Runs migrations
    - Seeds some welcome data
- Build a GUI which feeds user input into the installer
- Build a CLI (#120) which feeds user input into the installer?

Also consider how we should do importers. Should they be a part of the installation process, or a separate step after Flarum has been set up?

**Comment by franzliedke** [comment]
This is what I always thought:

* the installer itself is just a PHAR archive (apparently they can be accessed from the web, too) that takes care of the following:
  * download the actual standalone application and core
  * set up database and general config
  * create initial data (user account) or import data from another forum

So, for the above, that would mean:
- A separate package
- GUI and CLI (the latter may have to be part of the core, because the GUI should only be usable with the standalone app)

**Comment by tobscure** [comment]
OK so something like this?

**Web installation**
- User goes to flarum.org, clicks "Download", downloads "flarum_web_install.phar.php", and uploads it to their server's public directory.
- They navigate to that file in their browser. The PHAR boots up and shows a GUI prompting them to enter their config details.
- They click "Submit". The PHAR validates their data and gives them an error if something's wrong.
- If it's all good, the PHAR talks to an API hosted on flarum.org to find out the URL of the latest version of the standalone Flarum application (basically the flarum/flarum repo with flarum/core & default extensions & composer deps included, and JS pre-compiled; we'll need to write a build script for this). 
- It downloads this zip and extracts its contents into the public directory, while showing a progress bar to the user.
- Once this is done, it writes config.php, then includes Flarum's autoload.php and runs core + default extension migrations, and finally creates initial data.
- The PHAR then presents the user with a success message, and the option to import data from another forum. The PHAR contains various importers that we deem to be stable enough. The user can choose a forum software/version, enter the DB details, and the PHAR will attempt to do the import.

**Manual installation (for devs)**
- User clones flarum/flarum into their public directory. Retrieves git submodule.
- Runs composer install on system and core.
- Runs `php flarum install`. (This command is a part of flarum/flarum, not flarum/core. Because flarum/core has no knowledge of what config.php is and where it should be written, right?)
- Prompted for config data, writes config.php, runs flarum/core migrations.
- How do we run importers here?

**Laravel integration**
- `composer install flarum/laravel`, which in turn requires flarum/core
- `php artisan flarum:install`, which prompts for config data, writes config/flarum.php, runs flarum/core migrations.
- How do we run importers here?

**Comment by tobscure** [comment]
This is done
