### ISSUE TITLE
Scrubber index exceeds total number of post when dragging or clicking "now"

### ISSUE THREAD

**Issue by zinsserzh** [flarum/core#1221]
## Bug report
- Version of Flarum: whatever version https://discuss.flarum.org is now as of 08/04/2017
- Website URL where the bug is visible: https://discuss.flarum.org/d/*
- OS/Browser: Reproduced on Ubuntu-Chrome/Ubuntu-Firefox/MacOS-Chrome

## Additional comments
When clicking the `Now` button, the scrubber index will go beyond the total number of post. Doesn't matter where the scrubber was. It is not noticeable when the scrubber was not at the end because it's changing and moving at the same time, and the final value is correct. However, if the initial position is already at the bottom, you can definitely see it.

Same thing happens if the scrubber is at the bottom and users are trying to drag it down.

**Comment by zinsserzh** [comment]
I do like the design of the scrubber scrolling, so please make it perfect :D
I can spend some time next week digging into this if I get zero response O_o

**Comment by dav-is** [comment]
I believe this issue has been discussed elsewhere. You might have interest in reading this thread: https://github.com/flarum/core/issues/115

**Comment by zinsserzh** [comment]
That's such long and ancient (but active (well, sort of)) thread. I'll take a look at it/

**Comment by zinsserzh** [comment]
oops

**Comment by franzliedke** [comment]
I think given the results of the discussion in flarum/issue-archive#444, I will close this. It won't matter anymore once that is taken care of.

@tobscure Correct me if I am wrong.
