### ISSUE TITLE
Potential Namespace Conflicts

### ISSUE THREAD

**Issue by KyrneDev** [flarum/core#1223]
As I was sending a PR for beta 8 on flarum-ext-tags, I discovered a protential issue with the new namespaces. The saving, saved, deleted, etc. Events are all shared by post, user, discussion, and group, if you need to use more than one of these events in one class it requires you to alias one of them. I propose we change the events to {model}Deleted, {model}Saving, etc.

**Comment by franzliedke** [comment]
I think that's okay (and planned).

You can still do things like `import Flarum\User` and then just use `User\Deleted`, `User\Saved` etc.

**Comment by luceos** [comment]
@franzliedke you're missing one slight thing:

The full namespace of that user deleted and saved would be:

```
Flarum\User\Event
```

Your proposal would therefor not work because all these events are stored in the namespace ending `Event`. 

I still think the directory structure you propose makes sense, but I feel from an extension developer side of things @CDK2020 holds more value.

**Comment by franzliedke** [comment]
@luceos Thanks for the input, I missed that, true.

I will reopen this for more discussion about alternative solutions.
@tobscure Do you remember how you came up with these names?

I am gone for two weeks starting now, so I don't have any time for more thoughts from my side.

**Comment by tobscure** [comment]
This won't be relevant for extension developers as listening for the events will be abstracted away by the new Extenders API - see [here](https://gist.github.com/tobscure/a07da0ca4e80ac7de640d368c3d36ce0#file-bootstrap-php-L33).

That said it's probably still a good idea to make the names more explicit/standalone, as @CDK2020 has suggested.

**Comment by franzliedke** [comment]
True, I totally forgot about the extenders. Considering we will have them, I think the current names will be just fine.

**Comment by askvortsov1** [comment]
> True, I totally forgot about the extenders. Considering we will have them, I think the current names will be just fine.

Just to clarify, by current names, you mean the current names, not the ones Kyrne is proposing, right? If so I think we can safely close this as no action is necessary.

**Comment by luceos** [comment]
I think we agree on this.

**Comment by franzliedke** [comment]
Toby and I had different perspectives, as far as I can tell. I want to keep it open at least until we've finalized the remaining extenders.

**Comment by askvortsov1** [comment]
We decided in meeting that we like the current approach; conflicts can be easily handled through import aliasing.
