### ISSUE TITLE
Feature: Unread indicator in topic view

### ISSUE THREAD

**Issue by BartVB** [flarum/core#1228]
It would be really nice if there was something that showed me what post I read last in a topic that I revisit. 
For example a line between the last topic I read and the post after that.
And/or a (temporary) different background color of the first new post (like with Discourse).

Currently I find myself re-reading parts of discussions because it's not immediately clear what posts are new. Especially if there are only a few new posts because of which some old posts are in view at the top of the screen.

**Comment by franzliedke** [comment]
@tobscure Please comment: Is something like this planned?

**Comment by luceos** [comment]
Duplicates https://github.com/flarum/core/issues/1017, pushing that one closer to 0.2
