### ISSUE TITLE
Fix URL generation in various places

### ISSUE THREAD

**Issue by tobscure** [flarum/core#123]
Splitting up our front controllers is a great move, but URL generation is problematic in some cases:
- Flarum\Core\Handlers\Commands\RequestPasswordResetCommandHandler
- Flarum\Core\Handlers\Events\EmailConfirmationMailer
- Flarum\Api\Actions\Discussions\IndexAction

The first two are run through api.php, but need to generate forum routes.
The third can be run through index.php (when data is preloaded), but needs to generate an API route for the pagination links.
The Mentions extension also needs to generate forum routes when run via api.php.

@franzliedke how can we handle this?

**Comment by amdad** [comment]
I don't now if this issue embrace also utf-8 user names problem.
Like you can see in your Jérémie mentions here:
http://discuss.flarum.org/d/79/fluxbb-joins-forces-with-flarum/15

**Comment by tobscure** [comment]
@amdad That's an artefact from esoTalk import. We only allow alphanumeric usernames in Flarum for now :)

**Comment by amdad** [comment]
For now... ;)

**Comment by tobscure** [comment]
Currently Flarum's routes are defined in ApiServiceProvider, ForumServiceProvider, and AdminServiceProvider, all of which are only registered on their respective front controller. Thus, on an API request (entry via api.php), we have no knowledge of forum routes. This is problematic because sometimes API requests need to generate URLs to forum routes (e.g. when sending notification/confirmation emails)

What needs to be done:

* Work out how we can register all routes on all requests, but only route to a primary collection of them.
* Fix various instances where URLs are hardcoded (mostly in emails).

**Comment by franzliedke** [comment]
I'm planning to make all route collections available to the URL generator, but only parse those routes (for actual routing) that are needed in each section (API, forum, admin). Will do that early next week.
