### ISSUE TITLE
Non priviledged users able to (un)delete their own discussions

### ISSUE THREAD

**Issue by pflstr** [flarum/core#1230]
## Bug report
- Version of Flarum: 0.1.0-beta.7
- Website URL where the bug is visible: not public yet
- The webserver you are running: apache
- PHP version: 5.6.31

## Flarum info

Flarum core 0.1.0-beta.7
PHP 5.6.31
Loaded extensions: Core, date, ereg, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, gettext, gmp, SPL, iconv, session, intl, json, ldap, mbstring, mcrypt, standard, mysqlnd, mysqli, pcntl, mysql, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, Reflection, imap, shmop, SimpleXML, soap, sockets, exif, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache
EXT flarum-approval v0.1.0-beta.7
EXT davis-customfooter v0.1.0-beta4
EXT datitisev-dashboard v0.1.0-beta.6
EXT hyn-default-group 0.5.0
EXT flarum-emoji v0.1.0-beta.6
EXT clarkwinkelmann-emojionearea v0.1.1
EXT flagrow-byobu 0.1.0-beta.21
EXT flagrow-subscribed 0.1.0-beta.1
EXT flagrow-upload 0.5.7
EXT flagrow-user-directory 0.1.0
EXT flarum-flags v0.1.0-beta.7
EXT flarum-likes v0.1.0-beta.6
EXT sijad-links 0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT flarum-mentions v0.1.0-beta.7
EXT sijad-pages dev-master (a596fae52979b0e1ee982e27baa185c33b14f5af)
EXT reflar-user-management 0.1.4
EXT ganuonglachanh-search 0.3
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8
EXT avatar4eg-transliterator 0.4.0

## Additional comments

Although the permission to delete discussions is granted only to mods and admins, normal users are able to delete their own discussions as long as nobody else has posted in them. I assume this to be a feature, not a bug.

This however includes the ability to undelete their own discussions even in the case when a discussion has been deleted by a mod or admin. To prevent this the mod or admin needs to post something in the deleted discussion, either prior to or after the deletion.

I guess, most mods and admins are not aware of this necessity.

## Log files

Not relevant.

**Comment by Crypti-x** [comment]
Bad... Any idea how to fix it?

**Comment by luceos** [comment]
Relates to #1419 as the default gate seems to be too tolerating here.

**Comment by tobscure** [comment]
I think this can be fixed with a simple check in `DiscussionPolicy::hide`, to make sure that the `hide_user_id` is either `null` or is the actor's ID.
