### ISSUE TITLE
Basics > Home Page has no field for custom path

### ISSUE THREAD

**Issue by Ralkage** [flarum/core#1231]
## Bug report
- Version of Flarum: 0.1.0-beta.7
- Website URL where the bug is visible: localhost
- The webserver you are running: Apache
- PHP version: 7.0.10
- Hosted environment: localhost
- Hosting provider: Myself

## Flarum info

```
Flarum core 0.1.0-beta.7
PHP 7.0.10
Loaded extensions: Core, bcmath, calendar, ctype, date, filter, hash, iconv, json, mcrypt, SPL, pcre, Reflection, session, standard, mysqlnd, tokenizer, zip, zlib, libxml, dom, PDO, bz2, SimpleXML, xml, wddx, xmlreader, xmlwriter, openssl, curl, fileinfo, gd, gettext,
 gmp, intl, imap, ldap, mbstring, exif, mysqli, Phar, pdo_mysql, pdo_sqlite, soap, sockets, sqlite3, xmlrpc, xsl
EXT flarum-approval v0.1.0-beta.7
EXT flarum-bbcode v0.1.0-beta.5
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.7
EXT flarum-flags v0.1.0-beta.7
EXT flarum-likes v0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT flarum-mentions v0.1.0-beta.7
EXT reflar-gamification 1.3.0
EXT reflar-headlines dev-master
EXT reflar-reactions dev-master (5fecfce1235e5696e38832af1fd1a74e2db36ab6)
EXT xengine-signature 0.1.2
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8
Base URL: http://localhost/reflarb7
Installation path: C:\wamp64\www\reflarb7
```

## Additional comments
In the Admin Control Panel under Basics > Home Page, there is no field (lacking since 70.1.0-beta.6 from where I started from) to define a custom path. I was going to create an extension to add this feature since the description tells us we can define a path, but I figured it would be better to discuss.

![image](https://user-images.githubusercontent.com/2059356/29690879-ca4b48d4-88f6-11e7-94a7-ea210b06e8e3.png)

## Log files

```
N/A
```

**Comment by franzliedke** [comment]
This seems to be intentional. See [this commit](https://github.com/flarum/core/commit/dbd33f687c50cb232231870166d6f83d7d3014fc) that removed the feature.

**Comment by franzliedke** [comment]
I [removed the misleading help text](https://github.com/flarum/flarum-ext-english/commit/476ba8b0946005fdc3767f4dbae34fc5996664e5). Thanks for the heads-up.
