### ISSUE TITLE
Update extensions with namespace changes

### ISSUE THREAD

**Issue by tobscure** [flarum/core#1235]
As per https://discuss.flarum.org/d/6572-help-us-namespace-changes.

[Shell script](https://discuss.flarum.org/d/6573-convert-your-beta-7-compatible-extension-to-work-on-beta-8) to automate the process by @CDK2020.

- [x] tags https://github.com/flarum/flarum-ext-tags/pull/44
- [x] likes https://github.com/flarum/flarum-ext-likes/pull/12
- [x] suspend https://github.com/flarum/flarum-ext-suspend/pull/12
- [x] subscriptions https://github.com/flarum/flarum-ext-subscriptions/commit/d700fc8a327aa8f055de1e6ca305fa0afc825457
- [x] sticky https://github.com/flarum/flarum-ext-sticky/commit/01dc28f65ccdc017587f4a9947ea31dba46330a4
- [x] pusher https://github.com/flarum/flarum-ext-pusher/pull/12
- [x] mentions https://github.com/flarum/flarum-ext-mentions/commit/9fad387ad73bb6953f98c2e7ebb4001c1de7e033
- [x] markdown https://github.com/flarum/flarum-ext-markdown/commit/b8272e9b8b1565087df23d9fe2cc2d7eea9bca30
- [x] lock https://github.com/flarum/flarum-ext-lock/commit/d8f30529a83e75c9a47f348717dd6db0a8a9c2e4
- [x] flags https://github.com/flarum/flarum-ext-flags/commit/6c8f522930430d9a6496adffdcca54f677b3e298
- [x] english - *no work necessary*
- [x] bbcode https://github.com/flarum/flarum-ext-bbcode/commit/260fa86136641a829fc0c487139d230ceb9f7d13
- [x] embed https://github.com/flarum/flarum-ext-embed/pull/4
- [x] auth-twitter https://github.com/flarum/flarum-ext-auth-twitter/commit/2bdb4c7c79515d70a77b6fd06b618f48ae9bd716
- [x] auth-github https://github.com/flarum/flarum-ext-auth-github/commit/0447c2274e6ccbb0ffd3c343ba2bf7f4d1d089d3
- [x] auth-facebook https://github.com/flarum/flarum-ext-auth-facebook/commit/17ee26b8bb4b36ea8e09265daa7147db962f0c37
- [x] approval https://github.com/flarum/flarum-ext-approval/pull/8
- [x] akismet https://github.com/flarum/flarum-ext-akismet/pull/7
- [x] emoji https://github.com/flarum/flarum-ext-emoji/pull/11

**Comment by franzliedke** [comment]
I took care of the remaining ones. :)
