### ISSUE TITLE
When open notifications Front end error 

### ISSUE THREAD

**Issue by liruitian92** [flarum/core#1238]
## Bug report
Version of Flarum: 0.1.0-beta.7
The webserver you are running: apache, nginx
PHP version: 5.6

## Flarum info

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```
c:\phpDir\htdocs>php flarum info
Flarum core 0.1.0-beta.7
PHP 5.6.30
Loaded extensions: Core, bcmath, calendar, ctype, date, ereg, filter, ftp, hash, iconv, json, mcrypt, SPL, odbc, pcre, Reflection, session, standard, mysqlnd, tokenizer, zip, zlib, libxml, dom, PDO, openssl, SimpleXML, wddx, xml, xmlreader, xmlwriter, curl, fileinfo, gd, mbstring, mysql, Phar, pdo_mysql, PDO_ODBC, xmlrpc, mhash
EXT flarum-approval v0.1.0-beta.7
EXT flarum-bbcode v0.1.0-beta.5
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.7
EXT issyrocks12-filter 1.2.2
EXT flagrow-upload 0.5.7
EXT flarum-flags v0.1.0-beta.7
EXT flarum-likes v0.1.0-beta.6
EXT sijad-links 0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT s9e-mediaembed 0.3.2
EXT flarum-mentions v0.1.0-beta.7
EXT jsthon-simplified-chinese v0.1.0-beta.5
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8
EXT issyrocks12-users-list 0.2.2.1

## Additional comments
1.user A replay a dicussion
2.admin user can receive a notification
3.admin user delete forever the replay of  step1 
4.when admin user open the recevie notifications,you can see Front end error 

<img width="625" alt="_20170906101528" src="https://user-images.githubusercontent.com/31305717/30091504-7b0bcf46-92ec-11e7-84b3-4d976cc98d2e.png">

<img width="386" alt="20170906101729" src="https://user-images.githubusercontent.com/31305717/30091525-9f20b9a0-92ec-11e7-81c1-605acd24f201.png">

**Comment by luceos** [comment]
What error is logged in storage logs flarum.log?

**Comment by liruitian92** [comment]
There is no logs in  flarum.log. Following is the sql query result after running notification.
<img width="538" alt="_20170906101204" src="https://user-images.githubusercontent.com/31305717/30091400-01935d5a-92ec-11e7-8998-0977936c2a44.png">


<img width="546" alt="_20170906101200" src="https://user-images.githubusercontent.com/31305717/30091406-0ac3016e-92ec-11e7-868e-49af32db5be9.png">

**Comment by matteocontrini** [comment]
I think I'm experiencing the same issue. It seems that when you permanently delete a discussion (or a message?), the notifications related to that discussion generate a client exception.

![image](https://user-images.githubusercontent.com/2164763/30398836-155a6720-98d2-11e7-8e9c-8bfbf92985b9.png)

**Comment by matteocontrini** [comment]
Not sure but this might be the same issue as in #1025

**Comment by tobscure** [comment]
The frontend issue has been fixed. I have created an issue for the remaining backend cleanup #1380
