### ISSUE TITLE
[Approval] require approval for OP editing

### ISSUE THREAD

**Issue by liruitian92** [flarum/core#1239]
## Bug report
Version of Flarum: 0.1.0-beta.7
The webserver you are running: apache, nginx
PHP version: 5.6

## Flarum info

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

c:\phpDir\htdocs>php flarum info
Flarum core 0.1.0-beta.7
PHP 5.6.30
Loaded extensions: Core, bcmath, calendar, ctype, date, ereg, filter, ftp, hash, iconv, json, mcrypt, SPL, odbc, pcre, Reflection, session, standard, mysqlnd, tokenizer, zip, zlib, libxml, dom, PDO, openssl, SimpleXML, wddx, xml, xmlreader, xmlwriter, curl, fileinfo, gd, mbstring, mysql, Phar, pdo_mysql, PDO_ODBC, xmlrpc, mhash
EXT flarum-approval v0.1.0-beta.7
EXT flarum-bbcode v0.1.0-beta.5
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.7
EXT issyrocks12-filter 1.2.2
EXT flagrow-upload 0.5.7
EXT flarum-flags v0.1.0-beta.7
EXT flarum-likes v0.1.0-beta.6
EXT sijad-links 0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT s9e-mediaembed 0.3.2
EXT flarum-mentions v0.1.0-beta.7
EXT jsthon-simplified-chinese v0.1.0-beta.5
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8
EXT issyrocks12-users-list 0.2.2.1

## Additional comments
1.user A start a discussion ,and waiting approve,
2.admin user approved the discussion ,
3.user A edited content of discussion.
I think edited content of discussion,must be approved by admin user

**Comment by franzliedke** [comment]
@tobscure Do you agree with this feature?

**Comment by tobscure** [comment]
I don't know, I find this hard to reason about. Keen to hear from others. But at the moment I'd lean towards a "this is more trouble than it's worth" position.

**Comment by luceos** [comment]
This would probably go into "nice to have". I can imagine several use cases this could be useful to have. Let's keep this listed and label it a good first contribution?

**Comment by tobscure** [comment]
I imagine this would be a little bit tricky to implement (in "the right way"), so may not make a good first contribution

**Comment by franzliedke** [comment]
Fine with me.
