### ISSUE TITLE
What's going on with the Actor class?

### ISSUE THREAD

**Issue by tobscure** [flarum/core#124]
Flarum\Support\Actor. It's a singleton that basically just wraps a User model. I've never really been sure of its exact role.

Is it necessary? We could just as easily do `$app->instance('flarum.user', new Guest);` and then the Login middlewares can do `$app->instance('flarum.user', $user);` if they want to log a user in.

Thoughts?

**Comment by franzliedke** [comment]
That looks like a good idea to me.

What about `$app->bind('flarum.user', function() {return new Guest;})` combined with using `instance()` for the actual user, though? That way we don't need to instantiate the guest if there's none.

**Comment by tobscure** [comment]
:+1: perfect

**Comment by tobscure** [comment]
Done. Made it flarum.actor and have adopted the actor terminology application-wide.
