### ISSUE TITLE
ConfigureDiscussionSearch is not dispatched

### ISSUE THREAD

**Issue by CDK2020** [flarum/core#1243]
https://github.com/flarum/core/blob/master/src/Core/Search/Discussion/DiscussionSearcher.php#L86

This makes it impossible to add your own sort for the discussion list

**Comment by franzliedke** [comment]
Which sort order do you want to add? What's the use case?

**Comment by CDK2020** [comment]
I am trying to add a sort order for post popularity. Flarum's relevent code literally shoes that it should be dispatched.

**Comment by franzliedke** [comment]
That line should dispatch the event just fine.

Are you referring to the TODO comment above it? That's just a reminder to refactor the code so that the class uses an injected event dispatcher instead of the global `event()' helper function.

**Comment by tobscure** [comment]
Flarum's sticky extension relies on this event and works just fine. Closing this, please comment if we've misunderstood though!
