### ISSUE TITLE
Is it not possible to simulate or recreate category hierarchies using tags alone? 

### ISSUE THREAD

**Issue by aligajani** [flarum/core#1244]
I want something like this:

Photography
    - Diploma in Photography
        -- 2017-09-13
             --- Lesson 1
             --- Lesson 2
             --- ...

I see that we can apply tags on all these and organise them when the user is posting, but if you see Vanilla forums, it supports categories which are an entirely different thing because tags=labels where as categories=hierarchies. 

I think tags make sense if someone is posting with a topic label like Canon, Nikon on the Lesson 1, but posting a thread in Lesson 1 with the tag of Lesson 1 just doesn't make sense. It will mean we have to manually compose hierarchies through the tagging system.

 How do you guys approach this problem? We basically want hierarchies of information (via categories) and nesting. Is this even the right tool for the job because we wish not to hack it if other tools are offering this out of the box?

**Comment by franzliedke** [comment]
Please discuss things like this in the [forum](https://discuss.flarum.org). You will find more people watching the forums who can participate and provide input in this discussion. Once a feature has been accepted for inclusion in Flarum or a bug has been isolated, a ticket should be opened.

For now, I am closing this ticket.

**Comment by aligajani** [comment]
Thanks. I just posted it [here](https://discuss.flarum.org/d/6835-is-it-not-possible-to-simulate-category-hierarchies-using-tags-alone)
