### ISSUE TITLE
Throttling is bothersome to some permission groups

### ISSUE THREAD

**Issue by luceos** [flarum/core#1255]
Although related to #929;

I wish there was an option to enable throttling only for specific permission groups. As a moderator on discuss it sometimes block my processes to handle tasks efficiently when having to wait for the grace period.

**Comment by jordanjay29** [comment]
Admins are likewise affected.

**Comment by sijad** [comment]
also flooding should be disabled in debug mode, its annoying.

**Comment by franzliedke** [comment]
I don't think this should be related to debug mode. It should just be more configurable.

**Comment by franzliedke** [comment]
(...which is probably already possible in extension space, as far as I can tell.)

**Comment by luceos** [comment]
The throttle is now event driven, so yes an extension could override it. I think the discussion here should be whether we want to allow specific permission groups to be whitelisted based on a permission or something.
