### ISSUE TITLE
User last online text should be visible to admins

### ISSUE THREAD

**Issue by jordanjay29** [flarum/core#1256]
The ability to hide online status from other users shouldn't apply to admins, they should have a default override. There are instances where an admin would need to know if a user has been online even if they haven't posted anything. 

Ideally this would be a permission that could be handed out to mods as well. If ever there appears an Edit User permission, this would go hand in hand, IMHO. For now, just admins seems suitable, since Flarum only allows admins to edit or delete users.

**Comment by pflstr** [comment]
> If ever there appears an Edit User permission, this would go hand in hand, IMHO.

I suggest separate permissions. I would want my mods to see the last online information, but I won't like to give them the right to edit or delete users.
