### ISSUE TITLE
Blurry downscaled images (avatars, emoticons, etc) in Chrome

### ISSUE THREAD

**Issue by Zeokat** [flarum/core#1259]
## Explanation

Downscaled images looks blurry on Chrome and they looks bad. In FireFox, downscaled images are OK.
You can see that this issue is part of Chrome and was already discussed and solved with an extra CSS line at https://stackoverflow.com/questions/37906602/blurry-downscaled-images-in-chrome

## Technical details

```
Not relevant.
```

## Flarum info

```
Not relevant.
```

## Log files

```
Not relevant.
```

**Comment by franzliedke** [comment]
Thanks for the report (and a possible fix). Can you kindly share a link on discuss.flarum.org where this can be seen very well?

**Comment by Zeokat** [comment]
Hello @franzliedke , simply open https://discuss.flarum.org/ in FireFox and Chrome, then check yourself the downscaled avatar images.

![image-rendering](https://user-images.githubusercontent.com/1313154/32022652-58ad4ecc-b9d7-11e7-884f-c7e071cfca91.png)

**Comment by GTCrais** [comment]
Having this issue in a project unrelated to Flarum. This github topic popped up in google search results, so I figured I might as well respond to it - the issue is a Chrome problem. Here's a (still!) ongoing thread about it - https://bugs.chromium.org/p/chromium/issues/detail?id=562162
