### ISSUE TITLE
need explanations of one word for translations

### ISSUE THREAD

**Issue by Toinane** [flarum/core#1262]
## Explanation

I translate Flarum in french these days, and I can't understand a word used.
In flarum-tags, we have the term "slug_label: Slug"
For what purpose is used this word? For me, a slug, it's an animal, so..

Thank you for your work :)!

**Comment by tobscure** [comment]
https://en.wikipedia.org/wiki/Semantic_URL#Slug

**Comment by Magicalex** [comment]
@Toinane there is a translation of flarum already exist [here](https://github.com/milescellar/flarum-ext-french)

**Comment by Toinane** [comment]
Okey thanks all :)
