### ISSUE TITLE
[Mentions] Link in mentions uses text provided by user

### ISSUE THREAD

**Issue by datitisev** [flarum/core#1265]
## Explanation

The link in a mention uses the text provided by the user (`@USER`) for the link.
This breaks when their username is changed, as we can see in the following image.
The old username as Berlo, and the new username Berlyn

![image](https://cdn.discordapp.com/attachments/360670804914208771/372159534174699521/unknown.png)

Probably happens with posts as well.

## Technical details

- Website URL where the bug is visible: https://discuss.flarum.org/u/Berlyn/mentions

## Flarum info

N/A

## Log files

N/A

**Comment by dav-is** [comment]
This leads me to believe https://github.com/flarum/core/issues/315 was closed prematurely.

**Comment by tobscure** [comment]
Yeah this is a bug with the implementation of #315.
