### ISSUE TITLE
Allow secret question / answer to be required for sign up

### ISSUE THREAD

**Issue by edgimar** [flarum/core#1266]
In addition to (or instead of) a captcha system, it would be convenient to be able to allow people to sign up only if they are able to input a secret in response to some question prompt.  The purpose is not to detect a human vs. a robot, but rather to detect whether it is a human who belongs to a group that knows the answer to the question.

**Comment by dav-is** [comment]
What kind of question? This sort of feels like bad UX

**Comment by tobscure** [comment]
Like a password?

**Comment by ExerciseBook** [comment]
I think this kinds of question may be required when someone forgot his password.

[buy in im opinion . Using email to change the password is enough .

**Comment by edgimar** [comment]
No, that is not what I mean.  I mean that the new sign ups are not open to
the whole world, but only to those who know the answer to a shared question
which this group of people would know the answer to.  The purpose isn't for
password recovery, but for weeding out the pool of people who are allowed
to create new accounts.

**Comment by matteocontrini** [comment]
I think you can already build an extension for that. It shouldn't be difficult

**Comment by edgimar** [comment]
@matteocontrini  Ok - I assume that means that there isn't already an extension that offers this functionality?

**Comment by luceos** [comment]
@edgimar nope there is no such extension.

**Comment by franzliedke** [comment]
...which doesn't mean it isn't a good idea.

However, please understand that we cannot implement every single feature that may be a good idea, neither in core nor in our suite of official extensions.

We'd be more than happy to see this implemented in an extension. :smile:

**Comment by dav-is** [comment]
Ive seen this done in other forums and it’s almost always an arbitrary question that doesn’t really matter. Like “what is the name of the owner of the community?” This question always leads to me opening a new tab and looking up the answer. The only way of properly verifying user knowledge would probably be to activate accounts by an moderator after having a verbal interview.

**Comment by edgimar** [comment]
@dav-is  While this might be the way that some forums work, the question doesn't need to be (and probably shouldn't be) something someone can open up a web-browser and find with Google.  Maybe something like "what is the secret passphrase that was sent to you", where it was sent either by email or postal mail, or just told verbally to a person.

That said, having a "new user" state where users aren't able to do anything until approved can also be a useful feature.

**Comment by dav-is** [comment]
You can achieve that by allowing anyone to sign up, make the default group not allowed to post or anything, send them a private message (isn’t a core extension yet but there is one), and if they meet the criteria, you can transfer them into a more permissible group. This way, you don’t require your users to jump through hoops to join the community. I’d recommend open signups, with restricted permissions as it gives you permission to email them and it’s easy to convert their account once you’ve confirmed them as a member.
