### ISSUE TITLE
Add custom footer HTML in Appearance settings

### ISSUE THREAD

**Issue by tobscure** [flarum/core#1267]
Simple copy + paste of the custom header HTML code.

Has various use-cases, enough to warrant inclusion in core.

**Comment by rachellesalvadora** [comment]
I will do this one. Thanks :)

**Comment by MJBrennan** [comment]
Hi has this been done yet?

**Comment by luceos** [comment]
Not seeing a related PR yet @MJBrennan ; so I guess not.

**Comment by MJBrennan** [comment]
I will attempt this and submit a PR when I'm done.

**Comment by franzliedke** [comment]
@MJBrennan Any luck with this?

**Comment by afrastgeek** [comment]
Hello! Greeting for the first time :)

Sorry if I'm being forward, but I see this issue hasn't been resolved for a while and I thought I could give it a try.

I've created some changes on [my fork](https://github.com/afrastgeek/core/tree/feature/custom-footer-html/1267). The custom html successfully displayed, but I couldn't figure out how to display the translation.
