### ISSUE TITLE
Standard cursor and selection ability missing during compose (iOS)

### ISSUE THREAD

**Issue by gingerbeardman** [flarum/core#1268]
## Expected

On iOS it's possible to select a single word in text by simply double tapping it. 

Also, the cursor/caret can be moved anywhere with a single tap. 

## Actual

Neither of these interactions work in the text field used to compose a new topic/reply/etc. 
This makes editing text really frustrating. 

Maybe they are being overridden? 

## Technical details

- Website URL where the bug is visible: http://discuss.flarum.org
- I'm using iOS 11 + Safari

**Comment by franzliedke** [comment]
@gingerbeardman Thanks for the report! Please provide your iOS and browser version.

Can any other iOS user reproduce this, too?

**Comment by tobscure** [comment]
I can!

**Comment by gingerbeardman** [comment]
Add my environment details to OP

**Comment by tobscure** [comment]
It didn't work :( looking for another solution
