### ISSUE TITLE
Body text is outside of viewable area when tabbing to body field (iOS)

### ISSUE THREAD

**Issue by gingerbeardman** [flarum/core#1269]
## Outline

On iOS on a HTML form with good markup you can use two little arrows just above the keyboard to jump/tab between fields. 

## Expected
the caret should jump between fields and if necessary they should scroll into view. 

## Actual
Doing so on Flarum results in the body text going partially off screen. 

## Technical details

- Website URL where the bug is visible: http://discuss.flarum.org
- I'm using iOS 11 + Safari

## Screenshot
![a9ee399c-c77b-458c-aa0a-bedfbd2c1d5c](https://user-images.githubusercontent.com/49612/31994451-9efd2258-b978-11e7-9e0d-a53937658d76.png)

**Comment by tobscure** [comment]
Confirmed

**Comment by datitisev** [comment]
Similar behavior also happens when clicking the composer, as it results in the page scrolling down to the bottom. However it does not go off screen unless you somehow glitch it.

**Comment by tobscure** [comment]
This should be fixed - please try it out on discuss.flarum.org
