### ISSUE TITLE
Caret does not appear in sidebar search field (iOS)

### ISSUE THREAD

**Issue by gingerbeardman** [flarum/core#1270]
## Explanation

1. Open sidebar
2. Tap on search field
3. Observe

Additionally, tapping any item in the sidebar gives unexpected results. For example:

4. Tap notifications (actually opens Chat in Discord!)

I guess something funky has happened where the display has become decoupled from the actual tap targets? 

## Workaround

Scrolling the page whilst typing in the search field puts the cursor in the correct position. If you add or remove any  text in the search field then the cursor is misplaced once more. 

## Technical details

- Website URL where the bug is visible: http://discuss.flarum.org

## Screenshots

![eed30b38-2e72-4fef-9be7-133792e9d9a3](https://user-images.githubusercontent.com/49612/31995095-fccc3fa2-b97a-11e7-8017-c02638afd390.png)

![aee304e7-bdb3-49ad-92ea-96ae0d1136e3](https://user-images.githubusercontent.com/49612/31995096-fce4fd9e-b97a-11e7-8962-efc4e487ab10.png)

**Comment by tobscure** [comment]
Confirmed

**Comment by gingerbeardman** [comment]
Interestingly this doesn't happen on https://www.golfbuzz.com

**Comment by datitisev** [comment]
This has been fixed on iOS 11.3.

It is not a website bug, however, an iOS bug caused mostly by modals.

See https://hackernoon.com/how-to-fix-the-ios-11-input-element-in-fixed-modals-bug-aaf66c7ba3f8 for more information.
Official WebKit bug report at https://bugs.webkit.org/show_bug.cgi?id=176896.

**Comment by franzliedke** [comment]
Closing as wontfix then.
