### ISSUE TITLE
Reply via "triple dot" menu button results in obscured compose view (iOS)

### ISSUE THREAD

**Issue by gingerbeardman** [flarum/core#1271]
## Expected 
 Compose in usual way

## Actual
 Compose did not appear as expected

## Steps

1. Open multi-page  thread/topic
2. Make sure you are not at the end of the thread
3. Tap "triple dot icon"
4. Observe

## Workaround

Scrolling to top of page reveals correct compose view

## Technical details

- Website URL where the bug is visible: http://discuss.flarum.org

## Screenshots

![a4fd858e-dfaa-4dae-8e3b-252d582e735e](https://user-images.githubusercontent.com/49612/31998628-6a1c568e-b988-11e7-973c-dcc1949b436a.png)

![1121c392-2c4a-4a14-a0a9-e2639d4ff5d9](https://user-images.githubusercontent.com/49612/31998519-09c74276-b988-11e7-9a19-48012e652b3c.png)

**Comment by gingerbeardman** [comment]
I guess this is not jumping to the top of the document or positioning the compose at the current scroll position?

**Comment by luceos** [comment]
You mention this issue "resolves" itself by scrolling up, so the composer window is actually aligned at the top; aka it does exist?

**Comment by gingerbeardman** [comment]
yes it does exist at the top

**Comment by tobscure** [comment]
This should be fixed - please try it out on discuss.flarum.org
