### ISSUE TITLE
"Post discussion" button is obscured when composer made "full screen" (macOS)

### ISSUE THREAD

**Issue by gingerbeardman** [flarum/core#1274]
## Explanation

1. Start new discussion
2. click expand button to make composer go full screen
3. Observe

## Expected
"Post discussion" button should be visible

## Actual
"Post discussion" button is obscured

## Technical details

- Website URL where the bug is visible: https://discuss.flarum.org

ProductName:	Mac OS X
ProductVersion:	10.13
BuildVersion:	17A405

Retina MacBook Pro 13" running standard display size (not more space or larger text)

Doesn't happen when I am connected to an external display.

<img width="1025" alt="screen shot 2017-10-26 at 09 54 22" src="https://user-images.githubusercontent.com/49612/32065721-70fd60cc-ba75-11e7-9adc-57731dbcb3f4.png">

**Comment by datitisev** [comment]
Doesn't happen to me in my 21.5" iMac using Chrome 62.0.3202.45 (Official Build) beta (64-bit).

![image](https://user-images.githubusercontent.com/6401250/32076900-8ad263b8-ba6f-11e7-8b02-e4036fb33b60.png)

**Comment by franzliedke** [comment]
Thanks for the report.

Can anybody else verify this?

**Comment by gr8shivam** [comment]
Please correct the sample link typo. It should be https://discuss.flarum.org

**Comment by gr8shivam** [comment]
Happening on Safari 11.0.1

![screen shot 2017-11-01 at 4 59 58 pm](https://user-images.githubusercontent.com/4292333/32272926-3dab4ce2-bf26-11e7-86b4-9f617e2ac481.png)

Though it got fixed when I resized the window.

![screen shot 2017-11-01 at 5 01 35 pm](https://user-images.githubusercontent.com/4292333/32272969-78806848-bf26-11e7-9a3c-5d6bc16924a8.png)

**Comment by luceos** [comment]
Doesn't happen in Chrome. 

`Version 61.0.3163.100 (Official Build) (64-bit)`

**Comment by gr8shivam** [comment]
Well checked that out in Chrome (v62) and Firefox (v56) too. Happening in both.  

Find the attached screens:-

1) Chrome
<img width="1280" alt="screen shot 2017-11-01 at 6 17 50 pm" src="https://user-images.githubusercontent.com/4292333/32275468-58515c66-bf31-11e7-8601-2696cb166ac6.png">

2) Firefox
<img width="1280" alt="screen shot 2017-11-01 at 6 18 44 pm" src="https://user-images.githubusercontent.com/4292333/32275472-5c31ce92-bf31-11e7-826d-b6dbad0bb3bc.png">

**Comment by gr8shivam** [comment]
Just want to add that it gets fixed once we close it and reopen it again. Also happens when I open a discussion for the first time.

**Comment by anthonyrossbach** [comment]
Important note is this a new install or a install with any custom CSS/JS/Fonts?

**Comment by gr8shivam** [comment]
Verified this issue on the Flarum site (discuss.flarum.org)

**Comment by anthonyrossbach** [comment]
I saw that after ha ha @gr8shivam. I cant in any browser on my system replicate at all. Really strange bug and no way to see without dumping info when it happens to see why. I tested many browsers, displays, changing the DPI, new private windows, new browser installs and cant get it to happen even once.

**Comment by gr8shivam** [comment]
Well, I again checked this on all my browsers. The strange thing is that this time I wasn't able to reproduce the bug, maybe it's fixed?
@gingerbeardman Are you able to reproduce the bug?

**Comment by gingerbeardman** [comment]
I only get it "sometimes"

**Comment by datitisev** [comment]
Is anyone able to reproduce this bug in dev-master or in beta 7 with the latest browser versions? It may have not been a Flarum issue or already fixed in the master branch accidentally.

**Comment by tobscure** [comment]
I think it may have been fixed
