### ISSUE TITLE
Post count sidebar issues

### ISSUE THREAD

**Issue by gr8shivam** [flarum/core#1279]
## Explanation

Two issues:-
1. The post count shown is incorrect when clicked on Now though it gets corrected in a second. 
2. The post count starts increasing even though we're on the same post.

Example:- (Please wait for the gif to load)
![Flarum Bug GIF](https://user-images.githubusercontent.com/4292333/32272526-6d8153dc-bf24-11e7-8221-538a04855ca8.gif)

- As can be seen, when we click "Now", it shows 33 of 30 posts & then corrects after a second.
- Also, when we start scrolling, even though we're on the first post only, the post count increases to 3.

## Technical details

- Website URL where the bug is visible: https://discuss.flarum.org

**Comment by franzliedke** [comment]
Pretty sure this is the same as #1221, so it should probably be closed as well?

**Comment by gr8shivam** [comment]
As mentioned by @franzliedke , it's same as #1221. Closing this issue.
