### ISSUE TITLE
API client should be an interface, and pass through whole response

### ISSUE THREAD

**Issue by tobscure** [flarum/core#128]
Flarum\Forum\Actions\LoginAction calls the API and needs information about the response (status code etc.), not just the data.

Also we should consider an instance where forum is running on a separate server to API, so API requests might need to take place across the network. Thus the API client should be an interface with multiple implementations.

**Comment by franzliedke** [comment]
I'll look into this, very good points.

**Comment by dylmye** [comment]
Does this help? [http://www.slimframework.com/](Slim REST Framework for PHP)
