### ISSUE TITLE
Error installing Flarum when title contains Chinese characters.

### ISSUE THREAD

**Issue by hifall** [flarum/core#1284]
First of all, I have installed Flarum successfully with a forum title in English.

Then I try to perform a another clean installation, with the title being: "Forum 论坛", then comes on the screen an error saying installation erred.

And here is the info.

- Version of Flarum: v0.1.0-beta.7
- The webserver you are running: Apache 2.4.18
- PHP version: PHP Version 7.0.18-0ubuntu0.16.04.1
- Hosted environment: vps
- Hosting provider: http://qcloud.com

## Flarum info
Flarum core 0.1.0-beta.7
PHP 7.0.18-0ubuntu0.16.04.1
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, mailparse, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache
EXT flarum-approval v0.1.0-beta.7
EXT flarum-bbcode v0.1.0-beta.5
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.7
EXT flarum-flags v0.1.0-beta.7
EXT flarum-likes v0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT flarum-mentions v0.1.0-beta.7
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8

**Comment by tobscure** [comment]
> comes on the screen an error saying installation erred

Does the error message contain any useful information?

**Comment by franzliedke** [comment]
Can anybody reproduce this?

**Comment by franzliedke** [comment]
I am closing this issue as it seems to have grown stale. If you still encounter this problem with the latest version, please feel free to re-open it.

Please understand that outdated issues are closed regularly to keep the amount of open issues to a manageable minimum. In any case, thanks for taking an interest in this software and opening the issue in the first place!
