### ISSUE TITLE
Can I upgrade laravel framework to 5.5?

### ISSUE THREAD

**Issue by yulei745** [flarum/core#1288]
Can I upgrade laravel framework to 5.5?

**Comment by tobscure** [comment]
If you're offering to do this, thanks! We have a WIP by @luceos over here - https://github.com/flarum/core/pull/1252 - maybe see if he would like any help :)

**Comment by luceos** [comment]
Already on it, currently needs a full rewrite of our locale/language logic as Laravel implemented it's own and needs it for her translator.
