### ISSUE TITLE
Using with a blog?

### ISSUE THREAD

**Issue by rawsh** [flarum/core#1290]
What would be the best way to use this with a blog? I need a real time system that works on a static front end, preferably without an iframe. Also, is there a way to import disqus?

I guess what I have in mind would be a category called "blog" that is automatically posted to when there is a new article on the site (Ghost powered).

**Comment by franzliedke** [comment]
I am closing this ticket.

This does not mean that this feature won't ever make it into Flarum. We typically discuss these things in the [forum](https://discuss.flarum.org), though. Once a feature has been accepted for inclusion in Flarum, a ticket will be opened.

**Comment by tobscure** [comment]
FYI this topic may be of interest to you @rawsh! https://discuss.flarum.org/d/7214-the-general-blog-integration/5
