### ISSUE TITLE
Search returns empty for queries in Chinese.

### ISSUE THREAD

**Issue by hifall** [flarum/core#1291]
Hello! I tried to enter queries in Chinese in the search bar, and it returned empty. Is search supposed to work for non-English languages?

Thanks!

Info:

Version of Flarum: v0.1.0-beta.7
The webserver you are running: Apache 2.4.18
PHP version: PHP Version 7.0.18-0ubuntu0.16.04.1
Hosted environment: vps
Hosting provider: http://qcloud.com
Flarum info

Flarum core 0.1.0-beta.7
PHP 7.0.18-0ubuntu0.16.04.1
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, mailparse, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache
EXT flarum-approval v0.1.0-beta.7
EXT flarum-bbcode v0.1.0-beta.5
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.7
EXT flarum-flags v0.1.0-beta.7
EXT flarum-likes v0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT flarum-mentions v0.1.0-beta.7
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8

**Comment by tobscure** [comment]
Thanks for your report!

See https://github.com/esotalk/esoTalk/issues/38

Chinese search will be supported when we get around to adding search drivers other than MySQL FULLTEXT
