### ISSUE TITLE
Secondary tags can't be rearranged in the admin panel

### ISSUE THREAD

**Issue by pflstr** [flarum/core#1292]
## Explanation

Trying to rearrange secondary tags in the admin panel. The dashed outline representing the tag to be moved behaves as if the tag would be rearranged, but releasing the mouse button the tag jumps back to its old position. This does not happen with primary tags.

This issue can be observed with recent Firefox, Chrome and Safari browsers. It is also discussed here: https://discuss.flarum.org/d/7440-secondary-tag-sort

## Technical details

- Version of Flarum: 0.1.0-beta.7
- Website URL where the bug is visible: admin panel, not public
- The webserver you are running: apache
- PHP version: 5.6.30
- Hosted environment: local and shared hosting
- Hosting provider: localhost and https://stacklinux.com/

## Flarum info

```
Flarum core 0.1.0-beta.7
PHP 5.6.30
Loaded extensions: Core, date, ereg, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, hash, fileinfo, filter, ftp, gd, SPL, iconv, json, ldap, mbstring, session, standard, mysqlnd, mysqli, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, Reflection, mysql, shmop, SimpleXML, snmp, soap, sockets, exif, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip
EXT flarum-approval v0.1.0-beta.7
EXT davis-customfooter v0.1.0-beta4
EXT datitisev-dashboard v0.1.0-beta.6
EXT flarum-emoji v0.1.0-beta.6
EXT clarkwinkelmann-emojionearea 0.1.2
EXT flarum-english v0.1.0-beta.7
EXT flagrow-byobu 0.1.0
EXT flagrow-split dev-master
EXT flagrow-upload 0.6.0
EXT flagrow-user-directory 0.1.0
EXT flarum-flags v0.1.0-beta.7
EXT flarum-likes v0.1.0-beta.6
EXT sijad-links 0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT s9e-mediaembed 0.3.2
EXT flarum-mentions v0.1.0-beta.7
EXT sijad-pages dev-master
EXT reflar-user-management 0.1.4
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8
EXT avatar4eg-transliterator 0.4.0
Base URL: http://domain.dev
Installation path: /Users/.../domain/flarum
```

## Log files

Not relevant

**Comment by tobyzerner** [comment]
Thanks for your report.

Currently secondary tags are displayed in alphabetical order in the admin interface (works as intended).

The two secondary tags containing the most posts are displayed below the primary tags in the sidebar on the forum index.

This system will be completely rethought when we revamp the Tags extension (see flarum/issue-archive#393)
