### ISSUE TITLE
[Tags] timestamps are not in payload

### ISSUE THREAD

**Issue by luceos** [flarum/core#1295]
Looking at the Tags page you'll notice on hard refresh that all relative dates are based on "now" not any valid date related to the post or discussion;

https://discuss.flarum.org/d/7506-bug-a-couple-of-seconds-ago-everywhere-in-start-page

**Comment by Crypti-x** [comment]
Hrm. It now works after reinstall.

**Comment by Crypti-x** [comment]
I think I manipulated the wrong script... :c

**Comment by Crypti-x** [comment]
This can be closed ^^

**Comment by luceos** [comment]
I can reproduce this on discuss.flarum.org @Crypti-x this issue is not resolved.

**Comment by Crypti-x** [comment]
Oh

**Comment by Crypti-x** [comment]
But I manipulated the script, there was only the bug in my version. I edited the files.

**Comment by luceos** [comment]
Please @Crypti-x this is not a chatbox, neither is discuss.flarum.org. If you have something to add to a comment, edit the comment instead of commenting with just "Oh". Thank you.

**Comment by Crypti-x** [comment]
Sorry, but it was my fault. I think there is no bug in flarum tags extention.

**Comment by askvortsov1** [comment]
@luceos I'm unable to reproduce this. Additionally, it looks like the screenshots from the discuss site aren't working (that image site is down). Is this still an issue?

**Comment by luceos** [comment]
I guess this might have been resolved already. If not we can re-open it when needed.
