### ISSUE TITLE
Some emojis don't work

### ISSUE THREAD

**Issue by Zeokat** [flarum/core#1297]
## Explanation

Some emojis are listed but when i add them to one post, they aren't showed. You can check this on Flarum Community forums.

## Technical details

- Version of Flarum: v0.1.0-beta.7
- Website URL where the bug is visible: https://discuss.flarum.org/d/7381-some-emojis-don-t-work
- The webserver you are running: not relevant
- PHP version: not relevant
- Hosted environment: not relevant
- Hosting provider: not relevant

## Flarum info

not relevant

## Log files

not relevant

**Comment by tobscure** [comment]
Relevant: https://github.com/s9e/TextFormatter/issues/81

**Comment by datitisev** [comment]
Should be fixed with https://github.com/flarum/flarum-ext-emoji/pull/16
