### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by tobscure** [flarum/core#13]
For SEO, Flarum's Laravel app needs to respond to the same URLs as in the Ember app, serving up very basic semantically-correct HTML within `<noscript>` tags. Additionally, the Laravel app should preload the page's data into the Ember Data store to avoid the need for additional requests after the page loads.

**Comment by tobscure** [comment]
List of routes that the Ember app currently supports that need to be supported in Laravel app:
- Index: /?sort={sort}&q={search}
- Discussion: /{id}-{slug}?start={number}
- User: /u/{username}

**Comment by franzliedke** [comment]
I would totally assign this to myself, if I could ;)

**Comment by tobscure** [comment]
Sorry, I thought I had granted you access to this repo but I hadn't :S Done now!

**Comment by solhuebner** [comment]
:+1:

**Comment by romanov** [comment]
If JS renders the site, why do you need to make a pure HTML version of it?
http://searchengineland.com/tested-googlebot-crawls-javascript-heres-learned-220157

**Comment by tobscure** [comment]
Starting a fresh with this issue: #189

**Comment by tobscure** [comment]
@romanov In my experience, Googlebot's JS crawling isn't reliable, and other search engines don't crawl JS at all.
