### ISSUE TITLE
Refactor/cleanup formatting API

### ISSUE THREAD

**Issue by tobscure** [flarum/core#130]
It needs to be able to configure HTMLPurifier, and which HTML tags are allowed (related #129)

I think rather than having a formatter singleton, we should have instances created and extended on-demand (because formatting needs to work differently on posts vs. user bios vs. other things).

Also should the `ignoreTags` method (essentially a utility function) be a part of `FormatterAbstract`, or does it belong somewhere else?

**Comment by tobscure** [comment]
OK, I've cleaned up this API, but I still feel like it's a bit clunky. @franzliedke could you take a look when you get a chance?

**Comment by franzliedke** [comment]
Will do, thanks.

**Comment by tobscure** [comment]
It probably needs to be completely done over if we go ahead with http://discuss.flarum.org/d/271/text-formatting-in-flarum/11 :)

**Comment by tobscure** [comment]
This issue is no longer relevant with the implementation of s9e/TextFormatter. :)
