### ISSUE TITLE
Cannot create main categories

### ISSUE THREAD

**Issue by benhartwich** [flarum/core#1303]
## Explanation

I´ve deleted the auto installed main category Main. After removing the first and single main category I can only create sub categories.

## Technical details

- Version of Flarum: 0.1.0-beta.7.
- Website URL where the bug is visible: https://astronomie.community/
- The webserver you are running: nginx
- PHP version: 7.1.12
- Hosted environment: root server
- Hosting provider: hetzner

## Flarum info

```
Flarum core 0.1.0-beta.7
PHP 7.1.12-2+0~20171207160754.12+jessie~1.gbp5c91f3
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imap, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache
EXT flarum-approval v0.1.0-beta.7
EXT flarum-bbcode v0.1.0-beta.5
EXT cbmainz-de 0.7.1
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.7
EXT flagrow-upload 0.6.0
EXT flarum-flags v0.1.0-beta.7
EXT sijad-recaptcha 0.0.2
EXT flagrow-guardian 0.1.2
EXT flarum-likes v0.1.0-beta.6
EXT sijad-links 0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT s9e-mediaembed 0.3.2
EXT flarum-mentions v0.1.0-beta.7
EXT manelizzard-notify 0.2.1
EXT sijad-pages 0.1.0-beta.3
EXT xengine-signature 0.1.2
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8
Base URL: https://astronomie.community
Installation path: /var/kunden/flarum/httpdocs
```

## Log files

```
No logs created - no debug visible
```

**Comment by franzliedke** [comment]
Hmm, I can see that this behavior is confusing.

You can create a primary tag by creating one via the "Create Tag" button/modal and then moving the new tag to the "Primary Tags" section.

@tobscure Do we consider this a bug? An UX problem? Or will this be irrelevant with potentially upcoming changes to this extension?

**Comment by tobscure** [comment]
Should be irrelevant with https://github.com/flarum/core/issues/395 as UX will be completely redone :)

**Comment by franzliedke** [comment]
Okay, closing then.
