### ISSUE TITLE
Add search form to 404 page

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#1305]
From https://github.com/flarum/core/commit/ea2fc1ff8a7972fd809c9b45b552bda3138ed55e#commitcomment-26252028

**Comment by lex111** [comment]
@tobscure something like this? I would like to do it.

![image](https://user-images.githubusercontent.com/4408379/35482357-ff556658-0444-11e8-915c-e3df6a364aaa.png)

**Comment by franzliedke** [comment]
@lex111 I think that's a good direction. Feel free to send a PR! :smile:

**Comment by pflstr** [comment]
In the cases, where a 404 is generated because a user is not logged in, e.g. "/settings", a login modal might be a good idea.
