### ISSUE TITLE
discuss.flarum.org sends stats history with every page

### ISSUE THREAD

**Issue by gwillem** [flarum/core#1311]
## Explanation

Every page on https://discuss.flarum.org contains user/post/discussion stats since 2015. Not sure if that is the intention? And perhaps that is the reason the public forum is often so slow? I couldn't find this behaviour on other Flarum installs.

## Graphical representation

![graph](https://buq.eu/screenshots/fS70TueGgL4eMoNwQbhDNn7X.png)

**Comment by luceos** [comment]
@tobscure related to "that" new extension?

**Comment by tobscure** [comment]
That's embarrassing, thanks for the report @gwillem!
