### ISSUE TITLE
Separate code and constants

### ISSUE THREAD

**Issue by gwillem** [flarum/core#1314]
## Explanation

Currently, all bootstrap configuration (db credentials etc) is stored in `config.php` upon installation.

It would be nice to separate code and data by reading the config from a static file (e.g. json).

For multi-tenant configurations, such as run on [FreeFlarum](https://www.freeflarum.com), this is even a requirement, otherwise it is impossible to share the PHP opcache between instances. 

At FF I have replaced config.php with:
```
return json_decode(file_get_contents('../etc/flarum.json'), true);
```

## Technical details

- Version of Flarum: beta7
- Hosted environment: multi-tenant

**Comment by luceos** [comment]
Currently flarum is installed inside a public directory. Although we have plans to change that in the future, it would be - in my opinion - too much of a security risk to store the file as json, because all webservers will allow viewing such a file by a visitor. And yes we can add .htaccess rules and provide directives inside our documentation for nginx, but experience has shown that people do not heed such advice (or don't update the skeleton).

I think it has been suggested by the core team in the past, to modify the skeleton (flarum/flarum) to your needs or add extensions to provide the needed flexibility.

**Comment by gwillem** [comment]
>  it would be - in my opinion - too much of a security risk to store the file as json

Absolutely! However, I thought it was decided on Discord recently that a future release would include a `public` folder?

> to modify the skeleton (flarum/flarum) to your needs or add extensions to provide the needed flexibility.

Thanks for pointing that out to me. I considered it thoroughly, but adding multi tenancy to the software itself would imply that all forum instances have the same disk permissions - ruling out chroot per instance or different PHP users. So one hacked forum would effectively mean that all forums are hacked. 

OTOH, currently I run a hardlink setup where only flarum.json, assets/* and storage/* are unique to an instance, which so far has worked well (secure, fast, low disk usage, no mods to the code required except for config.php). What do you think?

**Comment by tobscure** [comment]
I think I prefer the flexibility of having a PHP file store configuration options by default. That way you can easily store the config however you like (in the PHP file, in another JSON file, in a database, etc) by putting some custom code in config.php. config.php is considered a file owned by the user, Flarum just generates default content for it. Flarum will never write to it after installation.

> Absolutely! However, I thought it was decided on Discord recently that a future release would include a public folder?

It will be there by default, but we will provide instructions for changing it back to no public folder for people with limitations. Therefore @luceos's point is still very relevant.

**Comment by luceos** [comment]
Just to give an example. Laravel also has a public folder and uses an `.env` file heavily. You would consider it "sane logic" to __not__ install Laravel completely inside a public directory?

Now check this google query: https://www.google.nl/search?q=intext:DB_PASSWORD+ext:env

🙏

**Comment by gwillem** [comment]
http://www.nicn.gov.ng/

:rofl:
