### ISSUE TITLE
502 Bad Gateway during installation.

### ISSUE THREAD

**Issue by max-wen** [flarum/core#1316]
## Explanation

Explain, in simple terms, but with as much detail as possible, your issue.
Be specific: What happened? What would you expect to happen? What have you tried so far?

## Technical details

- Version of Flarum: v0.1.0-beta.7
- Website URL where the bug is visible: null
- The webserver you are running: nginx
- PHP version: 5.6.32
- Hosted environment: local Mac OSX 
- Hosting provider: null

## Flarum info

```
Flarum core 0.1.0-beta.7
PHP 5.6.32
Loaded extensions: Core, date, ereg, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, hash, fileinfo, filter, ftp, gd, gettext, SPL, iconv, session, json, ldap, mbstring, standard, mysqlnd, mysqli, odbc, pcntl, mysql, PDO, pdo_mysql, PDO_ODBC, pdo_sqlite, Phar, posix, readline, Reflection, imap, shmop, SimpleXML, soap, sockets, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, intl, mhash, Zend OPcache, xdebug
EXT flarum-approval v0.1.0-beta.7
EXT flarum-bbcode v0.1.0-beta.5
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.7
EXT flarum-flags v0.1.0-beta.7
EXT flarum-likes v0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT flarum-mentions v0.1.0-beta.7
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8
Base URL: http://flarum.local
Installation path: /Users/Max/www/flarum
```

## Log files

below is a screen shot of xdebug profiler log, seems a curl request called by `s9e\TextFormatter\Utils\Http\Client` was blocked, And I tried `http://s9e-textformatter.rhcloud.com/flarum-minifier/` and the host is down : 
![e96ba32e-7fd5-4115-8b1c-8934596698c2](https://user-images.githubusercontent.com/2849142/34257612-8cfe80ac-e695-11e7-89af-2002d861c0f9.png)

**Comment by luceos** [comment]
This issue is fixed for the next beta. In the meantime I'd suggest increasing your timeout limit for nginx proxying the php-fpm request. Compilation of less only happens when necessary and always when debug is on.

**Comment by max-wen** [comment]
@luceos thanks for your reply, So how to turn debug off?

**Comment by gwillem** [comment]
@max-wen you can also disable remote minifying services. Remove lines 92-101 from [Asset/JsCompiler.php](https://github.com/flarum/core/blob/v0.1.0-beta.7/src/Asset/JsCompiler.php). It will then do minification locally.

**Comment by max-wen** [comment]
thanks  @gwillem  works for now.  expecting for the next release.

**Comment by franzliedke** [comment]
@luceos Are you saying this is already fixed, or it will be with a pending PR?

**Comment by luceos** [comment]
@franzliedke we discussed on discord the need to drop the dependency with a remote js minifier. I now notice the code hasn't yet been removed, see:

https://github.com/flarum/core/blob/master/src/Frontend/Asset/JsCompiler.php#L92-L97

@flarum/core what's the best way forward?

**Comment by gwillem** [comment]
#1307 was erroneously closed because Franz removed the `next-back` branch (hurray for cleaning up btw!).

**Comment by franzliedke** [comment]
This will also be taken care of with [the move to Webpack](https://github.com/flarum/core/pull/1367).
