### ISSUE TITLE
Don't raise a million PostWasDeleted events when deleting a discussion

### ISSUE THREAD

**Issue by tobscure** [flarum/core#1319]
Require extensions to listen for DiscussionWasDeleted instead and act appropriately.

**Comment by datitisev** [comment]
What if someone is making an extension to notify on post deletion AND discussion deletion, like webhooks?
I'd make it so there's a way to check if the main event is from deleting a discussion, and if so ignore the event / dont fire the event.

**Comment by tobscure** [comment]
Changed my mind about this, deleting a discussion doesn't happen that often so doesn't matter if the queries are a little bit inefficient - because it makes life a heck of a lot easier for extension developers.

**Comment by franzliedke** [comment]
@tobscure Isn't the problem that we query and hydrate *all* post instances for the thread?

What about an event "Posts Deleted" instead that contains an array of IDs?

(In any case, this should go via queue, once we have a queue system in place.)

**Comment by tobscure** [comment]
It's much easier to program extensions to perform whatever action in response to one event (post deleted) with all the post information available, rather than that and an additional event (posts deleted) where they may need to fetch the post information themselves anyway.

We could certainly chunk the post query though so memory doesn't become an issue.

**Comment by franzliedke** [comment]
Let's try using `cursor` for now. :)

**Comment by tobscure** [comment]
Didn't know that existed! Sounds good, will reopen this.

**Comment by tobscure** [comment]
Oops, just saw you already did it. The GitHub app on my phone doesn't show commit refs among comments :(

**Comment by franzliedke** [comment]
For the record: with the huge database changes of #1236, we're now back to Toby's original proposal, which is to not throw all the events. The database takes care of deletion now via foreign keys with cascades.
