### ISSUE TITLE
Clean up backend namespaces/structure

### ISSUE THREAD

**Issue by tobscure** [flarum/core#132]
As it is we have:
```
Admin
-- Actions
-- Middleware
Api
-- Actions
-- Client.php
-- Events
-- JsonApiRequest.php
-- JsonApiResponse.php
-- Middleware
-- Request.php
-- Serializers
Assets
-- AssetManager.php
-- CompilerInterface.php
-- JsCompiler.php
-- LessCompiler.php
-- RevisionCompiler.php
Core
-- Activity
-- Application.php
-- Commands
-- Events
-- Exceptions
-- Formatter
-- Handlers
---- Commands
---- Events
-- Models
-- Notifications
-- Repositories
-- Search
---- Discussions
---- GambitAbstract.php
---- GambitInterface.php
---- GambitManager.php
---- SearcherInterface.php
---- Users
-- Support
---- random stuff that doesn't fit anywhere else
Core.php
Extend
Forum
-- Actions
-- Events
-- Middleware
Http
Locale
Support
-- More random stuff
```

It's not bad, but there are a couple things that feel off to me:
- I'm worried that we haven't quite nailed separation of concerns, particularly with regard to what's inside the Core namespace and what's outside of it, and some dependencies (e.g. Core depending on Extend to set up notifications types, which in turn depends on API and Forum)?
- I think the stuff inside both Support namespaces needs to be cleaned up
- Should we be namespacing Core by models instead of types? (i.e. have Discussions, Posts, etc. namespaces instead of Models, Repositories, Commands etc.) I kind of like the current organisation by types actually, it just feels a bit odd that there's namespaces for Notifications, Activities, and Search but no other entities. Also in Models there are some random sidekicks (RegisteredTypesScope and MergeableInterface/Trait are related to Post)

**Comment by franzliedke** [comment]
A set of slides with some food for thought: https://speakerdeck.com/shawnmccool/a-talk-about-naming-things-talk :)

**Comment by tobscure** [comment]
Been thinking about this a lot, particularly with regard to keeping a well-defined public API for extensions to use.

The way I see it, there are four types of classes that need to be part of our extension API:
- **Extenders.** The doers. They basically map whatever it is that an extension wants to do to the actual implementation in Flarum. In this way, the implementation can change, which the API stays constant.
- **Events.** Occurrences that extensions can listen for and respond to.
- **Contracts.** Interfaces. When an extension wants to define something new (like a new gambit, or a new formatter), it creates a class that adheres to a contract.
- **Support.** Abstract classes. Gives extensions something to build on when implementing a contract, like a base gambit or formatter class.

I think we should put all of these together, either under the root Flarum namespace (Flarum\Extend, Flarum\Events, Flarum\Contracts, Flarum\Support) or under a sub-namespace, maybe something like "Public" (Flarum\Public\Extend, Flarum\Public\Events, etc.) That way it's very clear which parts of the system we need to worry about BC for.

In order to prevent the abstraction from leaking, the **Extenders** have to explicitly cover every possible action an extension could take. There can't be any references to Core or Api classes or namespaces, like there currently is. This:

```php
(new Extend\Model('Flarum\Core\Models\Discussion'))
    ->belongsToMany('tags', 'Flarum\Tags\Tag', 'discussions_tags'),

(new Extend\ApiAction('Flarum\Api\Actions\Discussions\Index'))
    ->addInclude('tags')
```

Needs to be turned into this:

```php
(new Extend\DiscussionModel())
    ->belongsToMany('tags', 'Flarum\Tags\Tag', 'discussions_tags'),

(new Extend\ApiActionDiscussionsIndex())
    ->addInclude('tags')
```

We may or may not want to namespace the extender classes. I think there is some value in seeing them all together at a single level, but there could be a lot of them.

**Events** would consist strictly (probably) of domain events. My feeling is that events shouldn't be used for other purposes; the same functionality they would enable should be better implemented by an Extender. For example, currently we have an event called Flarum\Api\Events\WillSerializeData; extensions don't need to know about this, instead they should use a method (something like "prepareData") on the appropriate ApiAction extender. The event could still be used under-the-hood, but it is an implementation detail.

**Contracts** need to include classes that an extension may implement (gambit, formatter) and also classes that it may need to work with (models, repositories, notification/activity syncer, searcher). This will enable stuff like:

```php
use Flarum\Extend;
use Flarum\Contracts\User;
use Illuminate\Database\Query\Builder;

(new Extend\DiscussionModel())
    ->scopeVisible(function (Builder $query, User $user) {
        // ...
    });

new Extend\DiscussionGambit('Flarum\Tags\TagGambit'); // implements Flarum\Contracts\Gambit
```

Of course, there is a GambitAbstract that will be useful to extensions, so this should be in the public API too, probably under a **Support** namespace.

Problems I still haven't solved:
- What about when an extension needs to use a core model class, like `Discussion::find(1)` (e.g. in an event handler)? Does some (or all) of Flarum\Core actually just need to be part of the public API? Or, technically I guess these cases should be using injected repositories, which would have contracts, so that'd be fine...
- Presumably Exceptions need to be part of the public API too?

Another thought: extension service providers should define a method called "extenders" which returns an array of Extender objects, rather than procedurally applying them using the inherited "extend" method in their "boot" function. This opens up doors for caching/compiling/optimizing the actions of the Extenders in the future, rather than running them from top to bottom on every request. In fact, this should probably be a requirement of extensions, so we should scrap the bootstrap.php concept and have some kind of base class.

**Comment by franzliedke** [comment]
Re bootstrap.php: I agree, we shouldn't need that. We can just add the extension class name (or the service provider name) to the `flarum.json` file, that can then be instantiated using the container...

**Comment by tobscure** [comment]
More thinking: our models need to part of the public API. Otherwise how does an extension do `(new Extend\Post())->belongsToMany('likes', 'Flarum\Core\Models\User')`?

**Comment by tobscure** [comment]
Unless, something like:
`Extend\Model::post()->belongsToMany('likes', Extend\Model::USER)`
`Extend\Api::post()->hasMany('likes', Extend\Api::USER)`

**Comment by tobscure** [comment]
Extender constants might be the way to go. Here's what the Likes extension looks like using that paradigm:
```php
    public function extenders()
    {
        return [
            (new Extend\Locale('en'))
                ->translations(__DIR__.'/../locale/en.yml'),

            (new Extend\ForumClient)
                ->assets([
                    __DIR__.'/../js/dist/extension.js',
                    __DIR__.'/../less/extension.less'
                ]),

            (new Extend\Model(Extend\Model::POST))
                ->belongsToMany('likes', Extend\Model::USER, 'posts_likes', 'post_id', 'user_id'),

            (new Extend\ApiSerializer(Extend\ApiSerializer::POST))
                ->hasMany('likes', Extend\ApiSerializer::USER_BASIC)
                ->attributes(function (&$attributes, Post $post, User $user) {
                    $attributes['canLike'] = $post->can($user, 'like');
                }),

            (new Extend\ApiAction(Extend\ApiAction::DISCUSSIONS_SHOW))
                ->addInclude('posts.likes'),

            (new Extend\ApiAction([
                Extend\ApiAction::POSTS_INDEX,
                Extend\ApiAction::POSTS_SHOW,
                Extend\ApiAction::POSTS_CREATE,
                Extend\ApiAction::POSTS_UPDATE
            ]))
                ->addInclude('likes'),

            new Extend\EventSubscriber('Flarum\Likes\Handlers\LikedSaver'),
            new Extend\EventSubscriber('Flarum\Likes\Handlers\PostLikedNotifier'),

            (new Extend\NotificationType('Flarum\Likes\PostLikedNotification'))
                ->subjectSerializer(Extend\ApiSerializer::POST_BASIC)
                ->enableByDefault('alert')
        ];
    }
```

**Comment by tobscure** [comment]
I don't mind this... my only question is, is this abstraction too much? Is trying to make the extension API physically separate from the internals more effort than it's worth? What are the chances we're actually going to want to change the Flarum\Core\Models namespace, for example, in between a major release? Wouldn't it be nicer for a gambit to be able to extend Flarum\Core\Search\Gambit rather than Flarum\Support\Gambit? Could we not just consider all public methods in all namespaces our public API, as expansive as that may be, and then use deprecations if we want to change things around?

**Comment by tobscure** [comment]
I'm back-and-forthing on this a lot, heh.

> What are the chances we're actually going to want to change the Flarum\Core\Models namespace, for example, in between a major release?

Not much, but we can never really know. Being locked to keeping all public methods as-is for each major version could be really restrictive. It would be better to have a well-defined extension API.

> Also consider the case where someone wants to build a new front-end for Flarum, interfacing directly with Flarum\Core.

Unless they're willing to put up with BC breaks, they can interface with Flarum's web API instead (using ApiClient).

**Comment by tobscure** [comment]
OK, after revisiting #150, I think we should put to rest the idea that our public extensions API is completely *defined* by Extenders. We should keep Extenders in place as great shortcuts/utilities for working with the API, but ultimately I think the public API needs to be inherent in the core code.

To back that up, here's a list of classes that might need to be referred to directly (i.e. extended or instantiated directly — making them a public API):

- Flarum\Api\Actions\* — various classes will need to be extended in order to create new API endpoints.
- Flarum\Api\Client — to make use of the API from within the app.
- Flarum\Api\Middleware\* — used by entry points (e.g. flarum/flarum, a WordPress plugin which sets up a Flarum instance, the Laravel integration package)
- Flarum\Api\Serializers\* — classes may need to be extended in order to create new serializers.

- Flarum\Core\Activity\ActivityAbstract
- Flarum\Core\Activity\ActivitySyncer
- Flarum\Core\Commands\* — maybe, depending on if an alternative front-end used Core or API?
- Flarum\Core\Events\* — need to be listened for.
- Flarum\Core\Exceptions\* — need to be thrown.
- Flarum\Core\Formatter\FormatterAbstract
- Flarum\Core\Formatter\FormatterManager — might need to be used by an extension to format something.
- Flarum\Core\Models\* — need to be extended to make new models. Will probably need to be used directly too (technically repositories are more correct, but sometimes that might not be possible)
- Flarum\Core\Notifications\NotificationAbstract
- Flarum\Core\Notifications\NotificationSyncer
- Flarum\Core\Repositories\* — need to be injected, might be extended/implemented?
- Flarum\Core\Search\GambitAbstract — extended to make new gambits
- Flarum\Core\Search\SearcherInterface — used by gambits
- Flarum\Core\Search\Discussions\Fulltext\DriverInterface — implement new fulltext drivers
- Flarum\Support\* — useful things that extensions might want to use

- Flarum\Forum\Actions\* — various classes will need to be extended in order to create new client endpoints.
- Flarum\Forum\Events\* — need to be listened to.
- Flarum\Forum\Middleware\* — used by entry points (e.g. flarum/flarum, a WordPress plugin which sets up a Flarum instance, the Laravel integration package)

- Flarum\Http\UrlGeneratorInterface
- Flarum\Locale\Translator

**Comment by tobscure** [comment]
Bouncing off #150 again, maybe we should implement extenders as simple utility functions, and only when they actually save work.
```php
use Flarum\Extend;

Extend\addNotificationType($class, $subjectSerializer, $enabledByDefault = []);
```

**Comment by tobscure** [comment]
Then again, I really like the current extender syntax and that whole API concept, even if it's leaky... maybe we should just roll with it.

**Comment by tobscure** [comment]
OK I think we should keep the Extenders as are.

What we can do with core is be selective about what's a public API and what's not. We can use this phpDoc tag: http://phpdoc.org/docs/latest/references/phpdoc/tags/api.html

Generally speaking, we can leave anything in core covered by an extender out of the public API.

Now, onto structural questions. Based on those slides you posted, @franzliedke, I've been playing around with the contextual namespaces (as opposed to type). This is how it looks:

![screen shot 2015-07-01 at 4 54 47 pm](https://cloud.githubusercontent.com/assets/128862/8449714/0e1feab4-2013-11e5-8637-b803ba265b3f.png)
![screen shot 2015-07-01 at 4 55 17 pm](https://cloud.githubusercontent.com/assets/128862/8449716/0e24c976-2013-11e5-9f0b-840083af9ffd.png)
![screen shot 2015-07-01 at 4 55 37 pm](https://cloud.githubusercontent.com/assets/128862/8449713/0e1b1660-2013-11e5-9436-b0a0dcd270e0.png)

I think I like it, what do you think?

**Comment by franzliedke** [comment]
I like it, except for suffixing the commands with "Command", I think.

**Comment by tobscure** [comment]
OK, this namespace refactor is done (woo!)

Still todo:
- Fix Extenders and extensions
- Get rid of repository interfaces
- Fix other bugs I’ve inevitably introduced
- Factor out model validation (see @todo in model class)
- Make the formatter API better

I also still have a couple of questions remaining:
- Should we have a Flarum\Database namespace which contains DatabaseServiceProvider and Model? I ask because the DB is used by API to store AccessTokens (I moved this out of Core, it didn't belong there).
- Should we move Flarum\Support\Action and Flarum\Support\HtmlAction into Flarum\Http?
- Should accessing config settings be made a part of the Forum class? That way rather than Core::config($key) you could do app('flarum.forum')->get($key), which might be better than a static class. Just a thought.
- Should we rename DiscussionBasicSerializer to BasicDiscussionSerializer etc.
- Should we rename plural namespaces like Flarum\Core\Exceptions to Flarum\Core\Exception? I noticed this is how high-profile APIs (like psr-7 and dictarios) do it.

**Comment by tobscure** [comment]
Had another idea about the API. What if we made it purely event-based?

```php
use Flarum\Events;

    public function boot(Dispatcher $events)
    {
        $events->listen(Events\ScopeModelVisibility::class, function (Events\ScopeModelVisibility $event) {
            if ($event->model instanceof Tag) {
                $event->query->whereNotIn('id', Tag::getNotVisibleTo($event->user));
            }
        });
    }
```

We could event implement our own dispatcher to use reflection and eliminate the need for the first parameter. The API would end up looking something like this:

```php
        $events->listen(function (Events\ScopeVisibility $event) {
            if ($event->model instanceof Tag) {
                $event->query->whereNotIn('id', Tag::getNotVisibleTo($event->user));
            }
        });

        $events->listen(function (Events\RegisterForumRoutes $event) {
            $event->collection->get('/tags', 'flarum-tags.forum.tags', 'action');
        });

        $events->listen(function (Events\RegisterForumAssets $event) {
            $event->assets->addFiles([]);
        });

        $events->listen(function (Events\BootApiAction $event) {
            if ($event->action instanceof Actions\Forum\ShowAction) {
                $event->action->addInclude('tags');
            }
        });

        $events->listen(function (Events\ModelRelationship $event) {
            if ($event->model instanceof \Flarum\Core\Users\User) {
                return $event->model->belongsToMany();
            }
        });

        $events->listen(function (Events\RegisterPostTypes $event) {
            $event->register('Flarum\Tags\DiscussionTaggedPost');
        });
```

And of course extensions would still be free to use subscribers via `$events->subscribe($class)`. We could move all Events in Flarum\Core\* into the single Flarum\Events namespace.

Pros:
- All of our APIs would be **consistent**. Instead of currently having some extenders altering classes with static variables, some altering arrays registered on the container, others registering event listeners — everything would be an event. Much easier for API design.
- Eliminate the need for classes with static variables (like Api\Actions). Instead, these properties would be instance variables, which would be modified when the action is instantiated (see BootApiAction event above).
- Like extenders, the whole range of things that you can *do* with extensions would be contained within one namespace (Flarum\Events). However, each event (thing you can do) would be its very own class which would make things even easier to understand and locate at a glance.
- We can do caching/performance optimizations. For example, for the "RegisterPostTypes" event, we could trigger that anytime the cache is cleared, and use it to construct a cache of registered post types. Then on runtime we just retrieve from the cache. Not a great example as registering post types is fast, but you get the idea.

Cons:
- Syntax is slightly less "nice" than Extenders.
- Probably a slight performance loss as well, since each event callback has to be fired even if it is not interested in a particular case. That said, we would gain some performance back because we eliminate the need to register *everything* on static classes on every boot, instead doing it on demand.

**Comment by franzliedke** [comment]
It looks to me like extension authors would have to know more of what happens in Flarum's core (aka implementation details). Hiding that is the big benefit of extenders in my eyes. Also, the many instanceof checks are somewhat annoying.

That said, it's a very basic hook/event system which is a common pattern for these types of things, so it could be fine.

Not sure I understood the part about static variables. When going the event-based way, why don't we have to change those anymore?

**Comment by tobscure** [comment]
> It looks to me like extension authors would have to know more of what happens in Flarum's core (aka implementation details). Hiding that is the big benefit of extenders in my eyes.

The Event objects can do the exact same job of the extenders: they can have public methods which hide the implementation details (see `Events\RegisterPostTypes::register` in my previous comment). They just have the added benefit of being called when they're actually needed, rather than at the very beginning of every request.

> Also, the many instanceof checks are somewhat annoying.

On the other hand, they can be a blessing too. If you want to apply the same modification to several different instances (e.g. add an included relationship to several API actions), it's much easier.

> Not sure I understood the part about static variables. When going the event-based way, why don't we have to change those anymore?

Right now each API action has numerous public static properties ($serializer, $include, $limit, $sort, etc.) which are used to sanitize the user's input for each of those variables. The Extenders would modify those static variables, on every action, at the start of every request to add new relationships etc. to API endpoints.

With Events, we can make them non-static properties which are modified only if the action is actually being called. We would trigger an event in the base SerializeAction::buildJsonApiRequest before the input is sanitized, passing through the action instance, then the event handlers do instanceof checks and modify the instance properties as necessary.

I'm pretty sure that this is the right way to go :)

**Comment by tobscure** [comment]
I'm implementing this new API (will keep it in a new branch for the time being), and I've worked out what was really bugging me about the Extenders:

They're *declarative* rather than *reactive*.

But we know that half of our API needs to be reactive anyway (hence why we have the concept event subscribers). The other half, as it stands, is a mix of declarative and reactive.

For the declarative things, like custom model relationships/permissions and API action serialization config (includes, sort, etc), rather than *reacting* and firing an event when that customization is needed (e.g. when an unknown relationship is called upon), we allow it to be *declared*  beforehand by providing static properties/methods. 

But this has two downsides:

1. Each class that implements those static declaration methods is taking on a lot of extra work. What if when registering permissions, we want to provide a way to prioritize certain callbacks over others? The Lock trait would need to add a priority argument to its `allow` method, and then sort the callbacks by priority before running them. I know of a class that does this kind of work already and is really good at it...

2. If you want to be consistent, you should really do it for *everything*. Like instead of calling a DiscussionSearchWillBePerformed event, why not have a static callback registration method on the DiscussionSearcher class? You end up with either inconsistency or insanity. Half of our Extenders just ended up registering event handlers anyway – what's the point of that extra layer?

Thus, you begin to see that you can delegate all of that *declaration* stuff to the event dispatcher. You get priorities with everything for free, and the API is nice and consistent.

Even for stuff that's still technically *declarative* (like registering post types), you can wrap it in an event to provide the same abstraction as Extenders did.

And then everything in the public API is *reactive*, which is one less concept to understand. It also has benefits in terms of how and where the event handlers are called: an extension that wants to *declare* a new client route will fail on an installation that has disabled the client; the part of an extension that *reacts* to an event that's asking for client routes to be registered will never be called on an installation that has disabled the client.

Hopefully that made a bit of sense – just wanted to write it out because it's been on my mind for a while, but I haven't been able to put my finger on it till now.
