### ISSUE TITLE
Entire post history on the profile is not viewable

### ISSUE THREAD

**Issue by duman** [flarum/core#1327]
For example on my [profile](https://discuss.flarum.org/u/duman) left hand side says that Posts 125. Meanwhile, if I scroll down and try to look at all of them one by one. It only displays me 19 of them. (Yes, I counted.) Afterwards there has to be a **"Load More"** button at the bottom but it's not there. (Tried with disabling/enabling ublock origins.)

Here's a screenshot of the missing load more when I had 91 messages: https://i.imgur.com/BAWeb1J.png
Here's a GIF of the load more disappearing after clicking it once: https://i.imgur.com/hIKxzYd.gif

Today I have 125 posts and I can't even click a button to load more. Only 19 of the past is visible. Rest is unviewable. (It's also same with mobile.)

---

**Completely unrelated rant:**

I don't know if I'm damned or something. Since reddit added me to their super secret redesign alpha project my inbox history went unviewable too. [Clicking on next to see my past is not possible](https://www.reddit.com/r/help/comments/7lo0bv/apparently_checking_my_message_history_is/). It says you don't have access for this. Cool, right?

Since I don't know that if my computer is trying to hide my history and I'm actually living in the truman show, more information might help some. So, wrote this too.

---

I'm using Google Chrome Version 63.0.3239.108 (Official Build) (64-bit) on Windows 10.
Android 7.0.0 latest version Google Chrome on mobile.

**Comment by dav-is** [comment]
https://github.com/flarum/core/issues/1006

**Comment by tobyzerner** [comment]
I don't think this is related to flarum/issue-archive#321 - I checked the database and @tkduman has indeed made 125 posts, and they should certainly all be visible to @tkduman.

I can't seem to reproduce the issue though - the Load More button consistently displayed and functions normally for me.

Do you get any JavaScript errors?

**Comment by gurjyot** [comment]
@tobscure I can reproduce this issue. On Flarum forum I have 103 posts but when I scroll down then I can't even see 1/4 of those. Even the load more button doesn't show. You can check my profile here.

https://discuss.flarum.org/u/gurjyot

**Comment by tobscure** [comment]
OK, seems I can reproduce when I'm not logged in.

**Comment by gurjyot** [comment]
Ok, but it's happening with us even if we are logged in.

**Comment by tkduman** [comment]
@tobscure I'm away from my house. Will check for JS errors when I'm back. Currently only have access to 4G and mobile.

**Comment by tkduman** [comment]
@tobscure this is my console output: https://i.imgur.com/Bun7QNr.png I've enabled verbose to make sure that everything is visible.

Here's the full log file on [pastebin](https://pastebin.com/X0TPdQML). I hope it helps. Good luck. If you need more information, please do ask. Thank you.

**Comment by franzliedke** [comment]
> Completely unrelated rant: [...]

Maybe Reddit is now using Flarum, too? :confused:

**Comment by tkduman** [comment]
@franzliedke Here's an image from the new reddit alpha redesign. [Keep it as a secret.](https://i.imgur.com/NUCuCIO.png)

Sorry for that, but I started to believe that chrome is somehow trying to murderize my JavaScript experience in a hidden way. That's why I wrote it.

**Comment by franzliedke** [comment]
Could this be the same as flarum/framework#1333?

**Comment by dsevillamartin** [comment]
Hm, yeah, I feel like flarum/framework#1333 is the issue.

**Comment by askvortsov1** [comment]
It looks like if the post stream contains any posts not visible to the actor, it will be cut off there and then, instead of just excluding non-visible posts

**Comment by askvortsov1** [comment]
Fixed in https://github.com/flarum/core/pull/2291
