### ISSUE TITLE
Password reset returns 'An error occurred while trying to load this page'

### ISSUE THREAD

**Issue by megamorf** [flarum/core#1329]
## Explanation

I registered an account on flarum.org back in April 2015 with a google alias address, e.g. `googleusername+custom-alias@googlemail.com`. Unfortunately I forgot my password and had to reset it. 

Opening the password reset link from the email (`https://discuss.flarum.org/reset/XXXXXXX`) only gave me a blank page with `An error occurred while trying to load this page`. I go by `megamorf` on flarum.org as well.

@luceos figured it's not a flarum bug but morea  configuration one.

## Technical details

- Website URL where the bug is visible: https://discuss.flarum.org/

**Comment by franzliedke** [comment]
Didn't @tobscure fix an issue with some of these pages in the last few days?

@megamorf Can you try again? It may already be fixed. Also, if possible, please try to reproduce the issue on a fresh install of Flarum.

**Comment by franzliedke** [comment]
Also, please *never* post password reset links like this publicly online. What if the link starts working again when somebody else tries to click on it? :scream:

Also, please remove it from your first post.

**Comment by tobscure** [comment]
Confirmed and fixed - some more regressions that slipped through the cracks. Thanks for the report. I've removed the link from your post :)

**Comment by megamorf** [comment]
Thanks for the quick response guys (@franzliedke, @tobscure). I figured that the link is only valid for a certain time range and since it didn't work in the first place it didn't pose much of a risk. Resetting my password worked after your changes, so thanks for that. I wish you a Happy New Year :-)
