### ISSUE TITLE
[Emoji] Change emoji picker to insert emoji character rather than shortcode

### ISSUE THREAD

**Issue by tobscure** [flarum/core#1331]
Currently in Flarum's emoji extension, we include our own map of shortcodes, which differs from TextFormatter's one - as a result, **sometimes when you pick an emoji in Flarum, TextFormatter doesn't pick it up.**

As a result, at some point [TextFormatter will be dropping its own shortcode support](https://github.com/s9e/TextFormatter/issues/81#issuecomment-354644385).

Thus, in Flarum we want to keep using our shortcode map so that users can type `:` and search for an emoji, but when they press Enter to insert it, we should insert the actual emoji character into the textarea instead of the shortcode.

**Comment by Zeokat** [comment]
Fixing this should also fix #1297 . Correct?

**Comment by JoshyPHP** [comment]
I'm subscribed to this issue. Please feel free to mention me in any discussion related to emoji.
