### ISSUE TITLE
Uncaught TypeError: post.likes(...).some is not a function

### ISSUE THREAD

**Issue by gwillem** [flarum/core#1336]
## Explanation

Posts fail to load (reproducible). 

I click on notifications, last post of a [multi-page discussion](https://discuss.flarum.org/d/7585-freeflarum-com-now-open-for-beta-access/128). Then click "original post".  

No posts load but console shows a JS error:

![screenshot](https://buq.eu/screenshots/mxPNFVu2pr5j3ixRUmN1WEuh.png)

## Technical details

- Website URL where the bug is visible: https://discuss.flarum.org
- google-chrome-stable 63.0.3239.108-1

**Comment by datitisev** [comment]
Is this still a bug? I cannot seem to reproduce it.
I went to the last post of said discussion, refreshed, and clicked "original post". No error occurred.

**Comment by TurboProgramming** [comment]
> I cannot seem to reproduce it.

Me too, I saw that we don't have any Needs Approval label, did anyone of you confirmed this?

**Comment by gwillem** [comment]
Cannot reproduce anymore. So.. I guess it has been fixed? :D
