### ISSUE TITLE
Clicking activation link multiple times results in error message

### ISSUE THREAD

**Issue by haarp** [flarum/core#1337]
Flarum 0.1.0-beta.7

When an activation email is sent and the link is clicked multiple times (usually by accident), the first request will activate the user and second request will result in the error message "Invalid confirmation token".

This confuses users as it indicates something went wrong, when everything is in fact in order.

There should be a more friendly message when an user clicks an activation link while having an already activated account. Or maybe send them to the forum main page directly.

Thanks!
Flarum is great, keep it up!

**Comment by franzliedke** [comment]
Very good suggestion, thanks for reporting!

If anybody wants to take this on (e.g. send their first PR), [this line](https://github.com/flarum/core/blob/ea353a2f2c8557e05a2f8f5c08f53e4a4776e87f/src/Forum/Controller/ConfirmEmailController.php#L66) needs to be changed. Extra points for making this translateable. :smile:

**Comment by datitisev** [comment]
How would one check if the token itself is expired or just invalid? I think we should keep the distinction.

**Comment by matale** [comment]
I see the token is deleted from the DB once a confirmation is performed so I don't think we can check that it is already confirmed unless the whole table structure is changed and the token is not deleted after confirmation. 

How about just changing the error text to something like "Invalid confirmation link or already confirmed."

**Comment by franzliedke** [comment]
Yep, changing the error text would be okay as a quick fix to me.

**Comment by haarp** [comment]
Thank you!
