### ISSUE TITLE
[Suspend] Unsuspending from timed suspension

### ISSUE THREAD

**Issue by jordanjay29** [flarum/core#1345]
To unsuspend from a timed (X days) suspension, I cannot simply switch the option to Not Suspended, but I have to lower the suspension count and Suspend for a limited time of 0 days.

**Comment by pflstr** [comment]
While we're at it: Revisiting the suspension dialog of an indefinitely suspended user shows a limited suspension for 7279 days. I guess this is equivalent to indefinitely, but shouldn't it show as indefinitely as the latter one is still an option?
