### ISSUE TITLE
the extensions folder does not load in admin page,

### ISSUE THREAD

**Issue by Witype** [flarum/core#1347]
I flow the [http://flarum.org/docs/extend/](url) Building Extensions,
like this,
![image](https://user-images.githubusercontent.com/6899329/35141454-e827f86c-fd35-11e7-920b-7aba821a4e8e.png)
![image](https://user-images.githubusercontent.com/6899329/35141458-ecc1cd6c-fd35-11e7-960a-610a22b51f91.png)

but  there is not extension in page /admin,what i miss!
![image](https://user-images.githubusercontent.com/6899329/35141485-010ab1ee-fd36-11e7-9d29-95d10cecc23e.png)
thanks

**Comment by luceos** [comment]
That documentation is outdated, please look at [this read first](https://discuss.flarum.org/d/1662-extension-developer-first-read), especially the part about the Repository Path set up.

If you have any further extension developer questions, feel free to ask them on the forums or on discord.
