### ISSUE TITLE
[Mentions] Error messages due to replies to and quotes from deleted posts

### ISSUE THREAD

**Issue by pflstr** [flarum/core#1348]
## Explanation

Quotes from and replies to deleted posts produce a confusing error message to non-priviledged users, eg. here:

https://discuss.flarum.org/d/8544-seo-robots-txt

Moving the mouse over the reference to `I-Cube`'s user name produces a red alert `The requested resource was not found.` Although this is technically correct, as the original post is deleted, it doesn't look good to the bystander who doesn't know Flarum yet. The message should be more informative like 'This post has been deleted.' and it shouldn't look like a problem with the software.

I.m.o. the message should be produced in the same place, where the replied to post would appear if it hadn't be deleted.

## Technical details

- Version of Flarum: recent
- Website URL where the bug is visible: discuss.flarum.org

**Comment by dsevillamartin** [comment]
I’m guessing this kinda interferes with what you want the normal user to know. Admin privileges sometimes return 404 to normal users, but in this case the message should be a bit more informative. There are other cases like this, though, like users that aren’t found.

**Comment by luceos** [comment]
The same way a user is marked deleted, a (soft) deleted post being mentioned, should also be marked deleted, unless you have the permission to see it anyway.

**Comment by franzliedke** [comment]
IMO, in this case our default 404 handling for API requests (that little red error box) should probably be skipped, right? Or can we somehow disable any mentions when a user is deleted?

**Comment by askvortsov1** [comment]
Duplicate of https://github.com/flarum/core/issues/911
