### ISSUE TITLE
Properly truncate post previews on user activity page

### ISSUE THREAD

**Issue by tobscure** [flarum/core#135]
Use the truncate utility so that `...` is added if necessary. Should also update the utility to only cut off at whole words.

**Comment by franzliedke** [comment]
What about Markdown? Just don't parse it?

**Comment by tobscure** [comment]
Check out js/lib/models/post.js — we use the DOM to strip out HTML tags from the formatted content.

**Comment by franzliedke** [comment]
Very cool!
