### ISSUE TITLE
[facebook ext] requires update to league 2 and league client 2

### ISSUE THREAD

**Issue by luceos** [flarum/core#1353]
Currently there seems to be an issue with the oauth facebook driver. They have deprecated the `bio` field. In order to update to the next league/oauth2-facebook package, we also need to update to at least version 2 of league/oauth2-client which is fixed in flarum/core to version 1.

My suggestion would be to add this on top of our todo for the upcoming release, not doing so marks our facebook extension incompatible.

**Comment by tobscure** [comment]
What is the actual issue? How does it manifest? Where do we use the bio field?

**Comment by vincseize** [comment]
Hello

I wanna work with you

First as simple translator

I m dev too, french


Cheers

2018-01-30 21:13 GMT+01:00 Toby Zerner <notifications@github.com>:

**Comment by luceos** [comment]
The issue is seen here:

![](https://media.discordapp.net/attachments/369174406909394944/407926069543305216/error4.JPG)

Hm seems they added backward compatibility from 2.0.1 on: https://github.com/thephpleague/oauth2-facebook/commit/789804b98ba1c710e36a1a47d52a23c58ec22951

So as long as we're stuck on < 2 we'll be seeing reports of this no longer working because it's causing an exception 🤦‍♂️

**Comment by luceos** [comment]
Just to clear this issue up. In order to fix the exception thrown, we do not need to upgrade to the next league client and server libraries. The issue seems to be fixed when loading dev-master of our facebook extension (see [here](https://discuss.flarum.org/d/3956-facebook-connect-issue/8)).

Let's focus this ticket on doing the necessary upgrade to version 2, as the fix will be in the next beta 8 anyway.

**Comment by tobscure** [comment]
We do not use `composer.lock` because any time the user installs an extension it would become irrelevant.

If people simply run `composer update` should the library not update to the latest version and fix the problem?

**Comment by luceos** [comment]
Ah right, I was assuming flarum/flarum had one, but indeed it would not make sense with different php versions.

Composer updating won't update the (nested) dependencies when there's no new release for a package. Re-installing will fix it though.

**Comment by luceos** [comment]
This is going to be handled by #1359
