### ISSUE TITLE
Shortcomings of abstract oauth 2 controller

### ISSUE THREAD

**Issue by luceos** [flarum/core#1359]
The `AbstractOAuth2Controller` is a bliss, no doubt about it. However,

- No events are triggered during the oauth procedure.
- Although the AuthToken class stores the `$identification` array (which is used within the select), one cannot store additional information to pass along to a triggered event.

What I'd like to propose is to add Events related to the OAuth2 flow. And in addition store the $suggestions as well as the source/service authorizing the authentication.

A usecase for this would be the patronage extension, automatically adding users authenticated from patreon who pledge the campaign to be assigned a specific user group.

###

Affected:

- [ ] https://github.com/flarum/core/tree/1359-oauth2-improvements
- [ ] https://github.com/flarum/flarum-ext-auth-github/tree/1359-oauth2-improvements
- [ ] https://github.com/flarum/flarum-ext-auth-facebook/tree/1359-oauth2-improvements

**Comment by luceos** [comment]
Found another issue with league/oauth2-client 1+. Seems we need to upgrade to version 2 after all. Current version we run on dev-master is league/oauth2-client 1.4.2 which includes ircmaxell/random-lib v1.2.0 which uses deprecated mcrypt functions. I'll look at upgrading to league 2+.

![image](https://user-images.githubusercontent.com/504687/37272063-c1dff588-25d5-11e8-8891-48ae27ac81a7.png)

**Comment by luceos** [comment]
Related to #1357 the avatarUrl is now successfully being sent along as suggestion:

![image](https://user-images.githubusercontent.com/504687/37276306-a15c1074-25e1-11e8-929c-b51e58e71c06.png)

**Comment by tobscure** [comment]
When I wrote that Twitter didn't support OAuth2, only OAuth1. Not sure if that's changed.

**Comment by luceos** [comment]
@tobscure I should have updated that comment, but I found out that indeed Twitter has limited oauth 2 implemented. There are no (good) oauth 2 packages for twitter either. We could;

- keep the oauth 1 implementation, if it works it works
- write our own oauth 2 implementation
- discontinue the core extension

**Comment by tobscure** [comment]
I think just keep the OAuth 1 implementation for Twitter.

**Comment by luceos** [comment]
Sure, I'll go over this PR again to see what is left to do. Thanks for getting back to this!

**Comment by tobscure** [comment]
Please review #1514 and see if it will help with the patronage use-case you've mentioned. I have a feeling we might need some additional changes in that PR.
