### ISSUE TITLE
Middle-clicking the forum header shouldn't go back to index on current tab

### ISSUE THREAD

**Issue by tobscure** [flarum/core#136]

**Comment by franzliedke** [comment]
Probably related to #140. Can't we just get the base URL there?

**Comment by franzliedke** [comment]
Ah, never mind. That would obviously work, but would require a full page reload.

**Comment by franzliedke** [comment]
You'll have to fix this one...

Also, with my changes, a simple click on the header will now take us back to the homepage with a full page reload. Not sure how to do something like old-school `event.preventDefault()` in the history util class... looking forward to your solution ;)
