### ISSUE TITLE
If I click two times Start a Discussion, the Post Discussion Jump up

### ISSUE THREAD

**Issue by skywalker512** [flarum/core#1368]
## Explanation

If I click two times Start a Discussion, the Post Discussion Jump up

![_ _20180213120713](https://user-images.githubusercontent.com/12960906/36133295-e3aa6e1a-10b7-11e8-94d6-31658b62c5d4.gif)

## Technical details

- Version of Flarum: 0.7.1
- The webserver you are running: nginx 
- PHP version: 7.2.1
- Hosted environment: vps
- Hosting provider: virmach

## Flarum info

```
N/A
```

## Log files

```
N/A
```

**Comment by Kakifrucht** [comment]
Seems to be patched already on discuss.flarum.org

**Comment by skywalker512** [comment]
Thanks for your Reply，it works will now.
