### ISSUE TITLE
Fix some responsive issues

### ISSUE THREAD

**Issue by tobscure** [flarum/core#137]
- [x] Header primary controls
- [x] Search suggestions dropdown
- [x] Composer position absolute to fix iOS 8 bug
- [x] Discussion search results
- [x] Dropdown menu scrolling
- [x] Notifications
- [x] Composer

**Comment by franzliedke** [comment]
Could we include a search icon (a magnifying glass) in the title bar? When clicked, the title bar could be replaced by a (focused) search field...

**Comment by tobscure** [comment]
There's no room, at least on less wide phones like iPhones pre-6. Anyway, the responsive stuff is deceptively tricky because the I'm trying really hard to use as little extra markup as possible (to keep complexity down) — as of right now, the only extra markup is a "back" button. But it requires making sure the UI/markup use the exact same paradigms on both mobile and desktop. (Hopefully one day I will get time to write a detailed blog post about this.) In the case of search, on desktop it is part of the header controls, and on mobile the header controls are a part of the drawer... so moving search out of the drawer would require extra markup.

**Comment by amdad** [comment]
![list](https://cloud.githubusercontent.com/assets/10062429/8344709/5156aff8-1ae5-11e5-8fac-7bcb677ddf50.png)

Notification list should also be scrollable when list is bigger then current vertical space. 
Own vertical scroll then or scroll with page at least.

**Comment by tobscure** [comment]
@amdad Thanks, fixed :)

**Comment by franzliedke** [comment]
> I'm trying really hard to use as little extra markup as possible (to keep complexity down)

Awesome - the holy grail of responsive design ;)
