### ISSUE TITLE
Update to newer TextFormatter

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#1377]
In the course of my Flarum migration service I noticed many posts coming form other platforms can't be parsed by Flarum. And by can't be parsed I mean it throws errors when passing the content to TextFormatter.

There are both critical PHP and javascript parsing issues. I tried with a newer version of TextFormatter and these seem fixed.

I expected master to run on a newer TextFormatter but it seems like it isn't. Is there any plan to update ? I can contribute to that if no plan was made.

Here's a simple example, create a new post with content `    ` (4 spaces). You won't be able to edit that post anymore :stuck_out_tongue:

**Comment by tobscure** [comment]
PR would be very welcome!

**Comment by franzliedke** [comment]
Great suggestion indeed.

Please make sure to carefully follow [the changelog](https://github.com/s9e/TextFormatter/blob/master/CHANGELOG.md) - both for core and for the bundled extensions that extend the formatter. We have skipped some (potentially breaking) minor releases before 1.0 as well...

**Comment by clarkwinkelmann** [comment]
Yes I've seen the many changes to TextFormatter, that's why I wanted to know if anything was planned :smile: 

I'm adding this to my list of things to contribute if I find some time.

**Comment by BartVB** [comment]
I think this issue makes https://github.com/flarum/core/issues/1400 obsolete?

**Comment by franzliedke** [comment]
Yes, indeed.

**Comment by sijad** [comment]
can I work on this?

**Comment by tobscure** [comment]
@sijad sure!
