### ISSUE TITLE
When replying, the timestamp of the OP appears duplicated for a few seconds

### ISSUE THREAD

**Issue by gwillem** [flarum/core#1383]
## Explanation

Example:

![](https://buq.eu/screenshots/EcoEGTQltnDhCrnF6sOdmLfu.png)

The "duplicate" timestamp disappears after a few seconds. Reproducible. 

## Technical details

- Website URL where the bug is visible: https://discuss.flarum.org
- Browser: google-chrome-stable 64.0.3282.186-1 (Ubuntu 16.04)

**Comment by luceos** [comment]
@gwillem great bug report though 👍

**Comment by gwillem** [comment]
Prior to submitting I searched for duplicates using the `frontend` tag. Could you add that to #1087 ?

**Comment by luceos** [comment]
@gwillem that makes sense. The frontend tag is pretty new.
