### ISSUE TITLE
Split permission for editing and deleting posts

### ISSUE THREAD

**Issue by tjrgg** [flarum/core#1387]
Flarum has a simple permission system. Accordingly, editing and deleting posts have been grouped into the same permission. I disagree with this choice. For our community in particular, we don't allow our moderators to edit other people's posts, only delete them and we'd like to continue this. We have an exception for announcements and updates, but those go under a separate tag, so we'd just give moderators edit permission for those tags. In any event, none of this is possible with how the permissions are currently setup, which makes this problematic.

I'm assuming I can't be the only one that would prefer to be able to control these permissions separately. I'd like to see the "Edit and delete posts" split into two separate permissions for editing posts and deleting them. This could be accomplished by replacing the current permission with two new ones, modifying the existing one and adding a new one, or keeping the existing one and adding two new permissions and requiring the existing permission along with the new ones, whatever works best.

@luceos felt that this is something that should be in the core, so hence the issue here. I was initially suggesting an extension, but I'm all for seeing this in the core for a future update (perhaps beta 8).

**Comment by tobscure** [comment]
That's a fair use-case which I hadn't thought of. Happy for this to be in core, by adding a new "deletePosts" permission alongside the existing "editPosts" one.

**Comment by luceos** [comment]
Relates to https://discuss.flarum.org/d/7195-split-permission-for-editing-and-deleting-posts

**Comment by franzliedke** [comment]
Fixed by #1466.
