### ISSUE TITLE
Discussion list refresh button?

### ISSUE THREAD

**Issue by tobscure** [flarum/core#139]
Since the dev forum has been upgraded, I have been refreshing the discussion list a lot :P

Of course, once we have Pusher integration it won't be necessary. But on installations that don't have push (speaking of which, I'll make sure the push integration has a "long-polling" implementation for people who don't want to use Pusher), a refresh button like the one on Gmail might be useful. On mobile it could be "pull down to refresh"

**Comment by franzliedke** [comment]
The difference to the browser's refresh button would be that content is loaded via AJAX, right? Interesting idea... would definitely need a keyboard shortcut, though - but that's another ticket we already have, I think.

**Comment by tobscure** [comment]
Yep. It would have the same effect as clicking "All Discussions" again when you're already viewing all discussions.
