### ISSUE TITLE
RegisteredTypesScope has no wheres [core 0.1.0-beta.7.1]

### ISSUE THREAD

**Issue by luceos** [flarum/core#1394]
RegisteredTypesScope seems to have wheres to play with. This happens in our latest beta 7.1 and not in master (the scope was refactored). @datitisev reported this on discord again. We might want to consider to patch this issue by using the following code in the scope:

```php
$this->whereIndex = count($query->wheres ?: []);
```

That fixed it for him.

forum: https://discuss.flarum.org/d/9410-oops-something-went-wrong-please-reload-the-page-and-try-again

![image](https://user-images.githubusercontent.com/504687/37714676-6e75a9dc-2d1a-11e8-9f22-a5d505f1259a.png)
see [original image](https://cdn.discordapp.com/attachments/360689644230410251/426020325076238336/screenshot.png)

**Comment by tobscure** [comment]
This issue only occurs in PHP 7.2 right?

**Comment by datitisev** [comment]
@tobscure It occurred to me in PHP 7.2 and 7.1

Luceos and I thought the issue was 7.2, but after downgrading and _completely removing_ 7.1 (homebrew) the issue was still there.

**Comment by tobscure** [comment]
But why is it not occurring on discuss.flarum.org? 🤔

**Comment by datitisev** [comment]
It had never occurred to me before... but isn’t discuss running on some commit after beta 7.1? Or not this time?
I'll try to get some more information, like installed extensions, etc...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by datitisev** [comment]
```sh
$ php flarum info
Flarum core 0.1.0-beta.7 (c6aeeeb3c1d5cf92c586c9f8ee43d2127d0fb933)
PHP 7.1.14
Loaded extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, hash, fileinfo, filter, ftp, gd, gettext, SPL, iconv, json, ldap, mbstring, session, standard, odbc, pcntl, mysqlnd, PDO, pdo_mysql, PDO_ODBC, pdo_sqlite, Phar, posix, readline, Reflection, mysqli, shmop, SimpleXML, soap, sockets, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip
EXT flarum-english v0.1.0-beta.7
EXT flarum-likes v0.1.0-beta.6
EXT flarum-markdown v0.1.0-beta.5
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-tags v0.1.0-beta.8
Base URL: https://flarum.dev
Installation path: /Users/david/Sites/flarum
```

It also didn't work with all extensions disabled.

**Comment by luceos** [comment]
@tobscure although confusing the issue title might be, this relates to Flarum 0.1.0-beta.7.1 hence the title. The issue is related to a clean Flarum install and will most likely be caused when no wheres are added by the scope; so the fewer extensions the higher the chance of this happening.

**Comment by franzliedke** [comment]
@luceos @datitisev Is this still relevant?

**Comment by datitisev** [comment]
@franzliedke Doubt it. The code for `RegisteredTypesScope` was completely changed in beta 8.
