### ISSUE TITLE
Make the Switch/Checkbox components compatible with raw settings values

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#1395]
When using the Switch or Checkbox in a settings modal, saving works fine (sending `true` or `false` to the API)

However when showing the value on page load, the raw settings use values `'0'` or `'1'`, which both evaluate to `true`.

The solution is either to cast the setting at the API level, which you don't usually do in the admin because you pull raw values from the full list of settings, or do it in the front-end with a solution like `state: [true, '1'].indexOf(this.setting('mysetting'))`. Both solutions are very verbose and don't make the code more readable.

Of course storing type information along with settings would solve this issue #1312

But in the meantime maybe the component should be made to accept `'0'` as an "off" value ?

Might be related to #1367 

This follows a discussion on the Flarum Discord.

**Comment by tobyzerner** [comment]
> But in the meantime maybe the component should be made to accept '0' as an "off" value ?

Happy for this as a temporary solution before flarum/issue-archive#299

**Comment by franzliedke** [comment]
@clarkwinkelmann Is this still relevant?

**Comment by clarkwinkelmann** [comment]
I think it is. Feeding the raw boolean value back to the checkbox still has the same behavior as described above.
