### ISSUE TITLE
Whats the problem here ?

### ISSUE THREAD

**Issue by xpt1x** [flarum/core#1399]
Just installed Flarum on localhost with XAMPP and composer on Windows ..
Getting this Screen after Installation and providing all Mysql credentials Successfully 
![capture](https://user-images.githubusercontent.com/33655587/38266572-a9d98a1c-3796-11e8-941f-82aceca0dd53.JPG)
Why it cant take Phrases ?

**Comment by franzliedke** [comment]
Please don't use our issue tracker for support requests. Questions like this one belong to our community forums. Please provide as many details as possible, to make it easier for community members to help you.
