### ISSUE TITLE
Home button does not direct home

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#140]
On some pages (e.g. search results, category-specific index), the home button in the title bar does not take us back to the homepage. Instead, it simply takes us to the current URL with a ' #' appended (which is the `href` attribute). This makes me think the `route` method doesn't always do its job (or our history helper is failing).

**Comment by franzliedke** [comment]
I fixed this in 8a496970e9ad941ec7fbe1ccfb06c8e1dab1300d.

**Comment by tobscure** [comment]
Quick explanation: every time the IndexPage component is reloaded, it calls `app.history.push('index')`. So if you do a search, then the bottom layer of the history stack will be overwritten with the current URL (including query param). To fix, I made the `home` method route directly to `/`.
