### ISSUE TITLE
Markdown List Bug

### ISSUE THREAD

**Issue by Ralkage** [flarum/core#1400]
## Explanation

Currently, in any installation of Flarum and even discuss.flarum.org, the Markdown extension seems to have a hard time processing/parsing list items after a non-listed item is placed above it.

## Technical details

- Version of Flarum: Beta 7.1 and Master
- Website URL where the bug is visible: https://discuss.flarum.org/d/10869-picture-association-game

## Screenshots

Before:
![](https://i.imgur.com/NKI5BOs.png)

After:
![](https://i.imgur.com/2lLCoT9.png)

**Comment by Ralkage** [comment]
Seems as if this was brought up, considered, and fixed in s9e's TextFormatter repo: https://github.com/s9e/TextFormatter/issues/74

https://github.com/s9e/TextFormatter/commit/e6f58045de39739c0528fbe19bc9cc7299a3aff2

Should updating to the newest version or version that fixes this issue in the next release or after beta 8?

**Comment by franzliedke** [comment]
Indeed, updating TextFormatter should fix this.

I will keep this issue open as a reminder for us to update before the next beta release. We are lagging behind a bit.

**Comment by franzliedke** [comment]
Closing, as we already have #1377. Whoops.
