### ISSUE TITLE
[ReCaptcha] Add option for ReCaptcha to required to post

### ISSUE THREAD

**Issue by CDK2020** [flarum/core#1413]
I have discussed this with a few people and they all generally agree that we should have an option to make recaptcha required to post. I am willing to PR it if you think this would be something you would want.

**Comment by luceos** [comment]
There might be several different situations:

- [ ] register
- [ ] log in
- [ ] create discussion
- [ ] create post
- [ ] access admin

Not all of these would required at first, but it would make a great start implementing at least a few 👍

**Comment by CDK2020** [comment]
What do you mean access admin? I feel like admin users generally wouldn't be spamming that endpoint. While we are at it, we should implement invisible recaptcha, (it's a simple 1 line of code change)

**Comment by sijad** [comment]
@CDK2020 it's not that simple sijad/flarum-ext-recaptcha@0244c85d610dca15445928513dc234e6ac10156d, it does work but I'm not sure if it's possible to change position of "protected by reCAPTCHA" banner:

![image](https://user-images.githubusercontent.com/7693001/39404806-7f016f12-4baf-11e8-9d70-3aa6a1d2fc08.png)

**Comment by CDK2020** [comment]
@sijad You can control the css by adding the `badge: 'inline'` parameter to the render function

**Comment by Eldenroot** [comment]
Isnt it better to add this feature as a standalone official plugin?

**Comment by franzliedke** [comment]
There's https://github.com/FriendsOfFlarum/recaptcha now, which is maintained well enough. Let's leave this to the community. :smiley:
