### ISSUE TITLE
GitHub services deprecation

### ISSUE THREAD

**Issue by luceos** [flarum/core#1423]
GitHub [announced](https://developer.github.com/changes/2018-04-25-github-services-deprecation/) the services deprecation. The effect is that more tools have become Apps inside their marketplace, including Travis. Travis moved to travis-ci.com for open source project and offers free plans for these still through the marketplace.

As a [new "checks" tab](https://github.com/flarum/core/pull/1344/checks) has surfaced on PRs adding some features, we should try to move to this new way of integrating with Travis whenever we have the chance.

# Deprecation timeline:

- May 31, 2018: Submit your intentions for migrating or replacing your GitHub Service.
- October 1, 2018: GitHub discontinues allowing users to install services. GitHub Services will be removed from the GitHub.com UI.
- January 31, 2019: GitHub stops delivering installed services' events on GitHub.com.

**Comment by franzliedke** [comment]
We have three services configured on flarum/core:

- Travis - can be migrated right away by somebody with the correct permissions
- Packagist - depending on https://github.com/composer/packagist/issues/907
- IRC - still needed? I vote for deletion

**Comment by tobscure** [comment]
OK I've installed Travis.ci GitHub app, I think that's all we need to do for that??

**Comment by franzliedke** [comment]
I have deleted the Travis and IRC services. Only Packagist remaining...

**Comment by franzliedke** [comment]
Uh oh. I think deleting Travis was a bad idea, sorry about that. Reverted.

**Comment by franzliedke** [comment]
Packagist is done as well. Can we close this then?

**Comment by luceos** [comment]
Did someone re-log in onto packagist and confirm there are no issues on the flarum related packages?

**Comment by tobscure** [comment]
Just did it, can confirm all is well.
