### ISSUE TITLE
Watch our dependencies for security issues

### ISSUE THREAD

**Issue by luceos** [flarum/core#1425]
See https://github.com/marketplace/gemnasium

This way we will be notified in time about risks to Flarum.

**Comment by Eldenroot** [comment]
+1, it could be really useful!

**Comment by franzliedke** [comment]
Gemnasium is gone, see https://docs.gitlab.com/ee/user/project/import/gemnasium.html.
(The marketplace link also does not work anymore.)

https://github.com/marketplace/dependabot/ looks like it's an alternative.

**Comment by luceos** [comment]
Crap, let's blame GitLab.

The idea behind the proposal still stands so whatever alternative we can pick up (and is free for foss) would be fine imo.

**Comment by franzliedke** [comment]
We now get automatic notifications directly from GitHub (both for JS and PHP dependencies), as GitHub bought and integrated Dependabot in the meantime.
