### ISSUE TITLE
Mobile slide gesture breaks on Delete

### ISSUE THREAD

**Issue by jordanjay29** [flarum/core#1427]
On the mobile view of Flarum, swiping left on a discussion will open the discussion options menu. Choosing delete, and then performing the swipe left option again will hide the discussion from view (the display block remains, though empty) and fail to bring up the discussion options again. 

I haven't experienced this with any option other than delete.

**Comment by tobscure** [comment]
Confirmed

**Comment by TurboProgramming** [comment]
This issue needs the mobile label (and maybe UX).

**Comment by luceos** [comment]
Confirmed on beta 8 (current discuss version).
