### ISSUE TITLE
The fontawesome icon always shows to the side

### ISSUE THREAD

**Issue by skywalker512** [flarum/core#1428]
## Explanation
For example, this icon is not obvious static, it will turn up and down
 ![图片介绍](https://i.imgur.com/Lf1ljCP.gif)

## Technical details

- Version of Flarum: x.y.z
- Website URL where the bug is visible: http://example.com
- The webserver you are running: apache, nginx or something else
- PHP version: x.y.z
- Hosted environment: shared or vps
- Hosting provider: http://some-amazing-provider.com

## Flarum info

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

## Log files

```
Put any relevant logs here.
```

**Comment by luceos** [comment]
Feel free to re-open when you clarified:

> this icon is not obvious static, it will turn up and down

From your title it seems you want to modify the position of the icon, this should be possible using custom styling.

**Comment by skywalker512** [comment]
@luceos i want to say every icons are on the wrong place

**Comment by luceos** [comment]
And where do you believe should they be positioned?
