### ISSUE TITLE
Better Laravel Auth integration

### ISSUE THREAD

**Issue by REPTILEHAUS** [flarum/core#1434]
Im wondering if it is possible to have a more seamless secure way of integration with existing laravel websites

**Comment by franzliedke** [comment]
Hi,

yes, it is possible to improve the situation in this regard.
Unless there is a concrete step you'd like to see taken (and even then it's probably better to discuss it first), I would like to ask you to move this discussion to our community forums, until a decision is made to  implement this (or part of this) in a future release.
