### ISSUE TITLE
How to install？

### ISSUE THREAD

**Issue by rmujianxin** [flarum/core#1437]
i dont know install.

**Comment by franzliedke** [comment]
Hello and thank you for your interest in Flarum! :smile: 

Unfortunately, this is not the right place for getting support. We only discuss bug reports and features to-be-implemented here on GitHub. Please take your discussion to [our forums](https://discuss.flarum.org). More people can help out there,

When you do so, please make sure to describe in much detail as possible:
- what problem you are having,
- what steps you took so far,
- what went wrong,
- what happened and what you would have expected instead.

Please help us help you!
