### ISSUE TITLE
Composer post install/update/uninstall scripts

### ISSUE THREAD

**Issue by tobscure** [flarum/core#1442]
Was just reading https://discuss.flarum.org/d/12529-can-i-remove-an-extention-on-flarum

Obviously needing to run `rm -f assets/rev-manifest.json` is a bug, will be fixed as part of #1309 

But should we automatically run `php flarum cache:clear` whenever you run a composer install/update/remove command by adding it as a script in composer.json?

**Comment by datitisev** [comment]
I think this would most likely be fixed when [#881 (comment)](https://github.com/flarum/core/issues/881#issuecomment-348722857) (from [Franz's comment in #837](https://github.com/flarum/core/issues/837#issuecomment-351525892)) is fixed, and/or maybe #837.
All these issues are most likely connected, and while #837 is about the CLI command, it may fix this while the command is being improved with the changes it brings.

Did this make any sense...? 🤔

**Comment by luceos** [comment]
I'm in doubt. Without using the composer flag `--without-scripts` there would be no way to circumvent clearing the cache. In some situations it might be better to have full control over when to do that, eg after running migrations.

**Comment by CDK2020** [comment]
The problem I see with running the cache clear script when you require an extension is that the LESS from the extension isn't actually added to the forum's and admin's LESS until it's enabled. Clearing the cache on require wouldn't do anything.

**Comment by tobscure** [comment]
@CDK2020 this is true. We should have a `php flarum` command for enabling/disabling extensions - we can clear the cache as part of those.
