### ISSUE TITLE
[b8] CommentPost article has undefined class

### ISSUE THREAD

**Issue by luceos** [flarum/core#1454]
![image](https://user-images.githubusercontent.com/504687/41281039-bca649d4-6e30-11e8-9fbb-7a28101708ff.png)

https://discuss.flarum.org/d/12942-shared-hosting/11

**Comment by tobscure** [comment]
There are probably a bunch of these in other components around the place too.

**Comment by luceos** [comment]
It really doesn't make much sense because both the CommentPost and Post components have fallbacks to `''`: `className || ''`

https://github.com/flarum/core/blob/master/js/forum/src/components/Post.js#L42

**Comment by sijad** [comment]
@luceos i guess problem was here:

https://github.com/flarum/core/blob/211e7681ccd53a8fe408946c380b663f0dfb3301/js/forum/src/components/CommentPost.js#L83

**Comment by luceos** [comment]
@sijad correct; might need a PR. Someone up for it?
