### ISSUE TITLE
Display error in thread view, posts are missing

### ISSUE THREAD

**Issue by pflstr** [flarum/core#1455]
The current implementation of Flarum at discuss.flarum.org shows an error in the view of the content of discussions, best to be seen here:

https://discuss.flarum.org/d/3056-facebook-open-graph-tags-missing-any-extension/1
https://discuss.flarum.org/d/3056-facebook-open-graph-tags-missing-any-extension/4
https://discuss.flarum.org/d/3056-facebook-open-graph-tags-missing-any-extension/8

The first two links are fine, the third link shows only the last post, the rest of the discussion is missing.

**Comment by tobscure** [comment]
This has been fixed on discuss.flarum.org and I will push the fix to the repo tomorrow.
