### ISSUE TITLE
Search highlighting is prone to regular expression injection

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#1458]
Whatever you enter in the search field is being put unescaped into a regular expression to locally highlight matches. For example:

https://discuss.flarum.org/?q=test%20%5Bblah%5D%2B%20test

You can also easily crash the search by typing an invalid pattern:

https://discuss.flarum.org/?q=test%20%2B%20test

**Comment by DanielTheGeek** [comment]
It's very inappropriate to post security bugs on the issue tracker page. You should have mailed the development team instead.

**Comment by DanielTheGeek** [comment]
Oh, okay... thanks for pointing that out.

**Comment by sijad** [comment]
lodash has a [escapeRegExp](https://lodash.com/docs#escapeRegExp) method, we can use that or something like (suggested at https://stackoverflow.com/a/6969486):

```
function escapeRegExp(str) {
  return str.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");
}
```

which one do you think is better?

**Comment by tobscure** [comment]
@sijad lodash sounds good, just make sure Webpack tree shakes properly :)

**Comment by datitisev** [comment]
I cannot reproduce this in the latest dev-master.

![image](https://user-images.githubusercontent.com/6401250/44004257-d2ce3122-9e2d-11e8-9d2c-ab7d900f8c1f.png)

**Comment by tobscure** [comment]
@datitisev it's not enough to just visit a search URL; you need to actually type a phrase into the search box for it to be parsed as a regular expression.

**Comment by datitisev** [comment]
@tobscure Ah, the issue was that no discussions or posts matched the query. Now I can reproduce it.
Related to https://github.com/flarum/core/pull/1539, may want to escape regex in #1539 instead of the current solution.
