### ISSUE TITLE
"You may have missed this post"

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#146]
Maybe not an urgent issue, but a very valuable one in terms of usability:
Sometimes, we write up long replies to topics while somebody else is doing the same. It is very easy to miss the previous post in those cases (at least in FluxBB).

General plan of attack:
- When opening a composer, remember the time
- When posting succeeds and the posts are reloaded, we check the date of the last previous post and compare it to the time we remembered.
- If there seems to be a new post, we show an alert (with a link?) saying something along the lines of "There was another post in the meantime. [Don't miss it.]"

**Comment by tobscure** [comment]
Will this be necessary once we have push integration? The other person's post will show up as you're typing, so you won't miss it :)

**Comment by NexPB** [comment]
@tobscure Well keeping in mind not every default install will have pusher integration it wouldn't be bad having this.

**Comment by tobscure** [comment]
@NexPB That's true.

Currently when you submit a reply, it is returned from the API and appended to the discussion directly. Due to the nature of REST API endpoints, no other posts are returned with it. We'll need to do an extra request after submitting but before displaying the post, to fetch any other new posts that may have been made.

**Comment by tobscure** [comment]
This is half done, in terms of loading all new posts after submitting a reply. If you post a reply and there are new posts, they will appear at the top of the viewport and push your new reply down, so you won't possibly miss them, which makes the alert idea redundant. So, I'm going to close this, we can always reopen later if we want to revisit the behaviour.
