### ISSUE TITLE
Not all unfound url returns 404

### ISSUE THREAD

**Issue by selfboot** [flarum/core#1461]
When i access discuss page that not available, it returns 404 as expect:

![image](https://user-images.githubusercontent.com/2769831/41477508-1716dea6-70f7-11e8-8bef-e2ac0747971c.png)

But when i access user page that are not available, it looks like this. 

![image](https://user-images.githubusercontent.com/2769831/41477496-112a900a-70f7-11e8-8e67-c56eab53a4ed.png)

Should not it be 404 ?

**Comment by tobscure** [comment]
Yes. Related: https://github.com/flarum/core/issues/358

**Comment by franzliedke** [comment]
Closing this as duplicate of #1846, which already has an open PR (#1901).
