### ISSUE TITLE
Mentions should be stored as IDs

### ISSUE THREAD

**Issue by tobscure** [flarum/core#147]
Storing them as usernames means that they will no longer work if a user changes their username.

This would also allow for better extensibility with something like a "Display Names" extension, allowing users to change their display name without changing their username.

**Comment by amdad** [comment]
In DB id's, but in editor (when add/edit) we should see usernames. It's better to recognize to who we address message, than just ID number. So It should convert it (username<>id) on fly when SAVE or GET content between DB & editor.

**Comment by tobscure** [comment]
Alright, mentions are now stored with IDs. Currently we still display the original username entered by the post author, but using the latest should be pretty easy with the stored data. Low priority though. Going to close this and will open a new issue in the extension's repo once beta is out.
