### ISSUE TITLE
Rename Tags to Categories

### ISSUE THREAD

**Issue by TurboProgramming** [flarum/core#1472]
Hi,

Can you rename tags to categories as the name categories is better for few sections on the forum?

After you rename tags to categories, we might have an extension or a feature integrated to core for tags, allowing us 2 ways of organizing forum posts.
What do you think?

Thanks.

![screenshot_2018-06-30 flarum community](https://user-images.githubusercontent.com/17576065/42127690-d6049394-7ca5-11e8-9ce1-9f671ac03200.png)

**Comment by datitisev** [comment]
@TurboProgramming You can change the text of localizations yourself with [`flagrow/linguist`](https://discuss.flarum.org/d/7026-flagrow-linguist-customize-translations-with-ease).

**Comment by TurboProgramming** [comment]
@datitisev Thank you for your suggestion but I'm aware of that already.

I suggested this change to Flarum's core as that name is meaningful for every user, not just for me.

What do you think?

**Comment by dsevillamartin** [comment]
If I remember correctly, I think there was already a discussion about tags vs categories somewhere...

Yep! This is a duplicate of flarum/issue-archive#393. While flarum/issue-archive#393 doesn't exactly mention this, it discusses the confusing terminology the core tags extension has.

**Comment by TurboProgramming** [comment]
Sorry for the duplicate, but this issue is great for reminding the developers of this request as that issue is way to old and still open, I requested this for an immediate change for beta 8.

**Comment by franzliedke** [comment]
Not goint to happen in beta 8. Feel free to add to the discussion in flarum/issue-archive#393.
