### ISSUE TITLE
Rich editor extension to be implemented to core

### ISSUE THREAD

**Issue by TurboProgramming** [flarum/core#1474]
We have plenty of rich editor extensions at the community, allow us to format our text by clicking buttons at the top of the editor instead of knowing a formatting language.

Can we see one that is stable, integrated to the core?

**Comment by franzliedke** [comment]
Our issue tracker is not a wishlist. Suggestions are welcome to be proposed and fleshed out [in our forums](https://discuss.flarum.org/).

Feature requests need to be [reasonably detailed](https://github.com/flarum/core/issues/new?template=feature-request.md) or have been confirmed by one of the core team members.
