### ISSUE TITLE
[Tags] last discussion still showed after moving discussion

### ISSUE THREAD

**Issue by manurohr** [flarum/core#1476]
## Bug Report

**Current Behavior**
If you move a most recent discussion to another topic, the last discussion is still showed in old category also in new category, it's kind of duplicated. If I click on the the last discussion in old category, I am redirected to correct category.
 
**Steps to Reproduce**
1. Create a discussion in a category. 
2. Move discussion to other category.
3. You will see on tagspage `Last Discussion..` in both categories. 

**Expected Behavior**
The last discussion should be shown only once and displayed in the new category.

**Screenshots**
<img width="718" alt="lastdiscussion" src="https://user-images.githubusercontent.com/38522534/42151792-beb5061e-7de6-11e8-8f06-55f21c96bb4b.png">

**Environment**
Flarum 0.1.0-beta.7PHP 7.0.27-0+deb9u1

**Comment by franzliedke** [comment]
Nice catch! It looks like [this method](https://github.com/flarum/flarum-ext-tags/blob/03613432cb5e944c6387f1a652942dbbe5713370/src/Listener/UpdateTagMetadata.php#L52) should also take care of updating the old tags' metadata.
