### ISSUE TITLE
switcher for show language dropdown not correctly displayed

### ISSUE THREAD

**Issue by manurohr** [flarum/core#1478]
## Bug Report

**Current Behavior**
In the admin page, I can choose if I want to show langauge dropdown on frontend or not. I decide not to display the dropdown for the list of languages. After I save the setting, the switcher is set back turned on. However on the frontend it has taken the effect, I do not see any dropdown even the switcher is turned on in the admin page.

**Steps to Reproduce**
1. Go to admin page where basic settings are.
2. Turn switcher on for showing dropdown of languages.
3. Save the setting.
4. Refresh and check switcher again.

**Expected Behavior**
The switcher shall be turned off after having saved the setting and refreshed the page.

**Environment**
Flarum 0.1.0-beta.7PHP 7.0.27-0+deb9u1

**Comment by datitisev** [comment]
Ok, let me see if I understood this:

> The language switcher does not appear on the admin pages when enabled

I think this is an intended design, as the admin page has no user controls (when you click your avatar + username) apart from “Logout”.

**Comment by manurohr** [comment]
No, I mean this setting is still turned on even I do not see any language selector on header. Because if I do something else such as writing forum description and save it, the turned on language selector setting would be saved as well. See attached pictures.

<img width="301" alt="user_controls_header" src="https://user-images.githubusercontent.com/38522534/42163221-6107a822-7e0a-11e8-9501-4676a2254445.png">
<img width="357" alt="user_selector" src="https://user-images.githubusercontent.com/38522534/42163222-612d82b8-7e0a-11e8-94f8-cbdda03e496a.png">

**Comment by datitisev** [comment]
Oh, I see what you mean now.
It works for me just fine. Have you tried clearing the Flarum cache & hard refreshing?

**Comment by franzliedke** [comment]
Can anybody reproduce this with the latest dev-master?

**Comment by manurohr** [comment]
@datitisev I think you commented in the wrong ticket. Are you refering to this issue #1477 ?
If yes, please change your startpage to tagspage, then check it again.

**Comment by datitisev** [comment]
@manurohr Oh shoot, you are right lol. I’ll test #1477 again, post it there and then put my comment in a spoiler so it doesn’t occupy space.

This is what happens when you have too many issues open lol.

**Comment by 1iuhongyu** [comment]
I can reproduce this problem, the chain problem is the display problem of the front-end language tab. [Language tab issue #1729](https://github.com/flarum/core/issues/1729)

**Comment by waql** [comment]
You can modify the default word of "$locales->addLocale($this->getDefaultLocale(), 'Default');" in the boot method in /vendor/flarum/core/src/Locale/LocaleServiceProvider.php

**Comment by NicklasMF** [comment]
This seems to regard the following snippet in BasicsPage.js on line 36:
`if (typeof this.values.show_language_selector() !== "number") this.values.show_language_selector(1);`

But the Switch component seems to want a boolean.

**Comment by clarkwinkelmann** [comment]
I just experience this as well.

The most inconvenient is that it's not only a UI glitch. If you save the settings without changing it, it will be saved as ON.

For example if you change the forum description and save without noticing the switcher went back to ON, now it will be saved as ON and you will have to disable it again.

**Comment by datitisev** [comment]
We might want to connect this issue to another one that talks about setting values formats, i think we have one for it because of Boolean values stored.

**Comment by clarkwinkelmann** [comment]
That wouldbe #1395
