### ISSUE TITLE
U2F Key Support

### ISSUE THREAD

**Issue by tankerkiller125** [flarum/core#1479]
Currently there is no two factor authentication for Flarum that I can find. I think k it would be extremely beneficial to support both the traditional two factor through an app on the phone (Authy, Google Authenticator, etc.) And the newer more secure U2F keys that some people have.

**Comment by franzliedke** [comment]
I suppose this would be covered by using the new [WebAuthn spec](https://en.wikipedia.org/wiki/WebAuthn)?

Thanks for contributing your ideas! However, this is not the right place for out-of-the-blue feature proposals. Please discuss this on our forums first. :wink: 

Quoting the beginning of our feature request issue template:

> Note: The issue tracker is only for serious requests which have had some thought and planning put into them. If you just have an idea you would like to discuss, please post in the Flarum Community: https://discuss.flarum.org/t/feedback
