### ISSUE TITLE
Update feature request template 

### ISSUE THREAD

**Issue by luceos** [flarum/core#1480]
Just read Franz reply explaining the feature request template. It starts with something like, use only for serious requests that have been planned. I would like to suggest an edit where serious is replaced by the thought and planned part to give that more weight over being serious, to a user all their issues are serious 🤷‍♂️

Cc @tobscure, @jordanjay29

**Comment by franzliedke** [comment]
Sure, go ahead.

**Comment by franzliedke** [comment]
Closing in favor of the PR
