### ISSUE TITLE
Notification number pop-up icon edges appear fuzzy

### ISSUE THREAD

**Issue by TurboProgramming** [flarum/core#1481]
## Bug Report

**Current Behavior**
The notification number pop-up icon looks fuzzy compared to other icons.
This problem existed with other icons before too (#569)

**Steps to Reproduce**
1. Post something
2. Wait for a reply
3. See notification count badge

**Expected Behavior**
The icon corners shouldn't be fuzzy.

**Screenshots**
![screenshot_2018-07-03 1 flarum community](https://user-images.githubusercontent.com/17576065/42231698-e89859f4-7ef4-11e8-805d-397a5f460b55.png)

![2345234523453245](https://user-images.githubusercontent.com/17576065/42231959-b3b4fff2-7ef5-11e8-840f-d5149a41e9de.png)

**Environment**
Flarum Community
https://discuss.flarum.org

**Possible Solution**
https://github.com/flarum/core/commit/dc757fae5f4a43630447b4c6efc5fe4fbec02a53

This was used for the previous icon bug.

**Comment by TurboProgramming** [comment]
Should we remove this line in order to see this fixed?

https://github.com/flarum/core/blob/master/less/forum/NotificationsDropdown.less#L41

**Comment by datitisev** [comment]
CSS border should have nothing to do with any blurriness...though I'm not sure why there'd be any to begin with.
What browser are you using?

**Comment by TurboProgramming** [comment]
@datitisev I'm on Firefox.

---
I suggested that solution to change the style of the bubble if I'm right with the code, as you applied that fix to other badges like group badges that appear at the top right on user profiles, locked icons etc.

**Comment by franzliedke** [comment]
@datitisev That fix would work, see #569 and https://github.com/flarum/core/commit/dc757fae5f4a43630447b4c6efc5fe4fbec02a53.

However, in this case removing the border would have a rather ugly effect:
![Notification icon without border](https://user-images.githubusercontent.com/249125/42313626-7d430398-8043-11e8-9c46-627c3659997c.png)

I see two possible solutions:
- try to replicate the effect using a shadow instead of a border
- remove the border, and give the bubble a slightly darker color than the icon

@tobscure is the designer, it's his choice. :grin:

**Comment by TurboProgramming** [comment]
> try to replicate the effect using a shadow instead of a border
This seems to be the best fix, but if possible can you send a preview of this too? I would like to see it, then we can discuss it.

> remove the border, and give the bubble a slightly darker color than the icon
For this too, send a preview so we can discuss about them, but the other fix seems to be the best. This could look something like you sent.

**Comment by datitisev** [comment]
I've been reading some articles about design, and in a [Medium article by RefactoringUI.com](https://medium.com/refactoring-ui/7-practical-tips-for-cheating-at-design-40c736799886#b2c1) it mentions that 

> Box shadows do a great job of outlining an element like a border would, but can be more subtle and accomplish the same goal without being as distracting.

It may also solve this blurriness effect users are getting for some reason.

**Comment by TurboProgramming** [comment]
Thank you for the Medium article, it really does make a difference using shadows instead of borders.

But as I said earlier, we need a preview for us to decide, the example they gave is for a card, for example, Material Design includes a card that needs to have 2dp of shadow around it, but it's for a card, we need to see how it will look in a badge.

**Comment by TurboProgramming** [comment]
![screenshot_2018-07-05 flarum community 4](https://user-images.githubusercontent.com/17576065/42334888-3c897366-8087-11e8-8acb-b9a8774187c3.png) ![screenshot_2018-07-05 flarum community 5](https://user-images.githubusercontent.com/17576065/42334892-3e83df8a-8087-11e8-8e72-b2a696f2d84c.png) ![screenshot_2018-07-05 flarum community 6](https://user-images.githubusercontent.com/17576065/42334894-401cba9c-8087-11e8-91ba-51aae88c1a0b.png)

Let's apply the same fix for these, these icons' style should look great on the notification bell.

**Comment by TurboProgramming** [comment]
By the way, just to discuss, will it be good to change the notification bell badge's bg color to red? To get the user's attention instead of the blue color?

**Comment by TurboProgramming** [comment]
> I'll find the old commit, apply the fix and send a PR.

...and, in case I don't find it (and probably I won't), can any of you guys find me the old commit?

**Comment by TurboProgramming** [comment]
Possible commits that add shadow around the badges:
- https://github.com/flarum/core/commit/53b32eda124892b5390cb32410225f9280d209c9
- https://github.com/flarum/core/commit/3d429d9af3c86be3756ff321e5250af81d25c2d3
- https://github.com/flarum/core/commit/858feb5ac05f9a4dbee71b5fb094e0d8c46c1314

Are these the ones I'm looking for?

**Comment by franzliedke** [comment]
Yep, [here is the current version](https://github.com/flarum/core/blob/00bc8fc0bc63643ec850f5d5eec78701225b7f7b/less/common/Badge.less#L8).

**Comment by TurboProgramming** [comment]
Which old commit should I use to change the current version?

**Comment by TurboProgramming** [comment]
@franzliedke Please see #1500, check if anything is wrong on this.
