### ISSUE TITLE
Default avatar for "J" is not centered

### ISSUE THREAD

**Issue by TurboProgramming** [flarum/core#1482]
## Bug Report

**Current Behavior**
The J letter seem to be a little bit at the bottom-left.

**Steps to Reproduce**
1. Find someone with no profile picture and with a name starting with J
2. See error

**Expected Behavior**
The letter should be at the very middle.

**Screenshots**
![screenshot_2018-07-03 flarum community 3](https://user-images.githubusercontent.com/17576065/42232383-e6e724c6-7ef6-11e8-9e4d-c0bca05a48b7.png) ![screenshot_2018-07-03 flarum community 4](https://user-images.githubusercontent.com/17576065/42232398-ef5db9d0-7ef6-11e8-8db8-376f1992c0e1.png)

![screenshot_2018-07-03 joaquimcavalcanti - flarum community](https://user-images.githubusercontent.com/17576065/42232446-1a0c525e-7ef7-11e8-93f6-dd5c34288238.png) ![screenshot_2018-07-03 jmex - flarum community](https://user-images.githubusercontent.com/17576065/42232448-1b378d9c-7ef7-11e8-9bbd-c2e2155ecf0d.png) ![screenshot_2018-07-03 jbreuer95 - flarum community](https://user-images.githubusercontent.com/17576065/42232451-1c9683aa-7ef7-11e8-8ff9-fc70aeb55454.png)

**Environment**
Flarum Community
https://discuss.flarum.org

**Possible Solution**
Change font style/type

**Comment by franzliedke** [comment]
@tobscure Do we want to do something about this? Not sure other fonts would help here (and work across different browsers / operating systems)...

**Comment by luceos** [comment]
Didn't Toby talk about using flex? Flex would be very helpful with alignment and might fix that issue with the icons in #1484 too.

**Comment by tobscure** [comment]
This may be solved for the "J" case when we stop using Open Sans as the default font in an upcoming beta. Beyond that I don't think we can/should correct for [glyph design characteristics](https://en.wikipedia.org/wiki/Baseline_(typography))
