### ISSUE TITLE
Categories (tags) collapsed for no reason while there is a lot of space

### ISSUE THREAD

**Issue by ardacebi** [flarum/core#1485]
## Bug Report

**Current Behavior**
Most of the time after 3 tags are used on a post, the tag area collapses with a white filter to the right side, even there is space for them to stay there.

**Steps to Reproduce**
1. Go to the homepage
2. Find a post with 3 tags and a short title
3. See error

**Expected Behavior**
The tags should only collapse if the title is long.

**Screenshots**
![screenshot_2018-07-03 flarum community 5](https://user-images.githubusercontent.com/17576065/42241711-2bdf9e2e-7f14-11e8-903e-41b287c8bafd.png)

![screenshot_2018-07-03 flarum community 6](https://user-images.githubusercontent.com/17576065/42241714-2d03661e-7f14-11e8-80e5-8fc5c260d008.png)

**Environment**
Flarum Community
https://discuss.flarum.org

**Possible Solution**
Disable collapsing if the title is short.

...and collapse only if the title is long.

**Comment by datitisev** [comment]
This could probably be easily fixed with a flex layout. `flex-grow` for the title, and `flex-shrink` for the tags & comments number.

**Comment by TurboProgramming** [comment]
Can you tell me where can I find the lines to change so I can open a PR?

**Comment by franzliedke** [comment]
I doubt that this is easily "fixable" with just CSS. The info area on the right has a fixed width. As far as I can tell from [the commit that introduced this](https://github.com/flarum/flarum-ext-tags/commit/61b4599031b89308e2199385ee3687fd0d1905a3), I think this was intentional.

If you want to play around, the relevant CSS is currently in this file:
https://github.com/flarum/flarum-ext-tags/blob/03613432cb5e944c6387f1a652942dbbe5713370/less/forum.less

**Comment by TurboProgramming** [comment]
So what's our final decision? What should we do?

I prefer only collapsing the tags as it's like this only if the title is long and if the title is short, expand the tag view.

**Comment by luceos** [comment]
I fully agree with @datitisev that this might be a great use case for flex. Toby mentioned it before and I'd say this should be part of such an implementation.

**Comment by tobscure** [comment]
Discussion list is set for an updated look probably in beta 9 (related to https://discuss.flarum.org/d/2716-discussion-list-revamp). The plan is that only the primary tag ± the sub-tag will be shown, while secondary tags will be visible on hover.

**Comment by franzliedke** [comment]
Closing in favor of possible future discussion list revamps.
