### ISSUE TITLE
[Tags] "Start a discussion" button width too small on tags page

### ISSUE THREAD

**Issue by TurboProgramming** [flarum/core#1487]
## Bug Report

**Current Behavior**
The "Start a discussion" button collapses for no reason after switching to tags view and opposite.

**Steps to Reproduce**
1. Go to homepage
2. Click on tags
3. See error

**Expected Behavior**
"Start a discussion" button should always have the same width.

**Screenshots**
![5785678](https://user-images.githubusercontent.com/17576065/42242302-13bcdaee-7f16-11e8-89e2-e9e3328641dc.png)

![354634563645](https://user-images.githubusercontent.com/17576065/42242305-14d877b2-7f16-11e8-95b7-572a71071a39.png)

**Environment**
Flarum Community
https://discuss.flarum.org

**Possible Solution**
Disable collapsing and have the same width as the all discussions page on the tags page.

**Comment by tobscure** [comment]
This is a byproduct of https://github.com/flarum/core/issues/1486.

**Comment by TurboProgramming** [comment]
@tobscure It's not, see screenshots (Beta 7) below. This needs to be reopened.

![screenshot_2018-07-15 appybuilder community 3](https://user-images.githubusercontent.com/17576065/42735130-9f94041c-8857-11e8-9537-5fab1c8e3c1c.png)

![screenshot_2018-07-15 appybuilder community 4](https://user-images.githubusercontent.com/17576065/42735131-a1b8f0c2-8857-11e8-9114-f637df3ba2f2.png)

You can see that the button has the same issue even if the alignment issue (#1486) doesn't exist.

**Comment by TurboProgramming** [comment]
@tobscure Do you know which file can I find the code below?

```
 .TagsPage-nav .item-newDiscussion .Button {
  width:auto
 }
```

I searched a lot and was not able to find anything for TagsPage.

**Comment by TurboProgramming** [comment]
> Do you know which file can I find the code below?

I have the fix and I'm going to open a PR for this, that's why I'm asking.

**Comment by TurboProgramming** [comment]
I found that line of code I sent you via the inspector and it is for the new discussion button on the tags page.

When I try searching that code on the core package, I find one thing: IndexPage.less. That style file is for the new discussion button on the discussion list, not the tags page. It has the exact same code, but TagsPage is replaced with IndexPage.

I don't know how does this exist on the discussion forum, but not in the core code. Just let me know if you find anything about this. I'll apply the fix and open a PR immediately.

**Comment by franzliedke** [comment]
The code for the tags extension can be found in [this repository](https://github.com/flarum/flarum-ext-tags).

**Comment by TurboProgramming** [comment]
I keep forgetting that it's an extension thank you 👍

**Comment by TurboProgramming** [comment]
This is a core extension issue, closing this. 

Please see https://github.com/flarum/flarum-ext-tags/pull/54 for future discussions and updates.

**Comment by datitisev** [comment]
@TurboProgramming Core extension issues are also posted here, but the PRs are made to the corresponding repositories.
Reopen this issue and add `[Tags]` to the beginning of this issue's title.
