### ISSUE TITLE
Set character limit to tag descriptions

### ISSUE THREAD

**Issue by TurboProgramming** [flarum/core#1488]
## Bug Report

**Current Behavior**
The long description (eg. Extensions' description) hides the sub-tags of the parent tags with a scrollbar.

**Steps to Reproduce**
1. Go to homepage
2. Click on tags
3. See error

**Expected Behavior**
Tag descriptions' need a character limit or if they already exist, they need require fewer characters for them to not hide sub-tags **by adding a scrollbar for such small area.**

**Screenshots**

![screenshot_2018-07-03 flarum community 7](https://user-images.githubusercontent.com/17576065/42242459-9a3e6754-7f16-11e8-95ee-602e7f209c6f.png)

![screenshot_2018-07-03 flarum community 8](https://user-images.githubusercontent.com/17576065/42242462-9b4f5d10-7f16-11e8-92bc-3b02b1e923b8.png)

**Environment**
Flarum Community
https://discuss.flarum.org

**Possible Solution**
Set a character limit to tag descriptions or if they exist, they need a fewer character requirement.

**Comment by franzliedke** [comment]
Thta page is responsive, though. What would a limit be that works in every case?

IMO, the only thing we can do is try to make the description scroll if it overflows, and always show the subtags at the bottom of the box.

I seem to remember that @tobscure had some plans for a redesign of this page, so this might even be obsolete. Can't find it, though.

**Comment by TurboProgramming** [comment]
Making the description scrollable and the sub-tags not is a great solution.

But still, even if the description will have a scrollbar, we will have another issue, why have a scrollbar for some pixels? 

I'm not sure a limit would fix this, but it looks like there are 2 valid fixes for now. The first is a redesign and separating the sub-tags from the scrollbar, the second is the limit.

**Comment by tobscure** [comment]
Yep this page is planned for a redesign before stable, which will fix the issue.

**Comment by pflstr** [comment]
As the descriptions are given by the site owner and the site owner has the power to increase the height of the whole tag box via CSS, I don't see a benefit in introducing a restriction here.

**Comment by datitisev** [comment]
@pflstr I think the issue here is that normal users that use Flarum won't have any idea how to do it.
With "normal" being non-developers. Like if the admin used an installation service or FreeFlarum.

**Comment by tobscure** [comment]
I have reduced the tag description font size in flarum/flarum-ext-tags@2619c7f which mitigates this issue.

A redesign for the tags page is planned in which the space for the description will be flexible. I think it is up to the user to make their descriptions a reasonable length, but there is no sense in us enforcing a maximum number of characters (especially since HTML code is allowed in tag descriptions).
