### ISSUE TITLE
Improve web notifications icon

### ISSUE THREAD

**Issue by TurboProgramming** [flarum/core#1490]
## Bug Report

**Current Behavior**
The icon above the web notifications tab inside settings is a notification bell and the email notifications icon is an email icon.

**Steps to Reproduce**
1. Go to settings
2. See error

**Expected Behavior**
The icon above the web **notifications tab should be changed with an icon that represents the web**. Not with a notification bell. Notification bell _means notifications and email is also a notification._

**Screenshots**
![screenshot_2018-07-03 settings - flarum community](https://user-images.githubusercontent.com/17576065/42244402-96c3a1e6-7f1d-11e8-8e86-a79c3b25f4fb.png)

**Environment**
Flarum Community
https://discuss.flarum.org

**Possible Solution**
Replace notification bell with the following alternative Font Awesome icons:

- https://fontawesome.com/icons/desktop?style=solid (fas fa-desktop)
- https://fontawesome.com/icons/browser?style=regular (far fa-browser)

**Comment by franzliedke** [comment]
What about the [globe icon](https://fontawesome.com/icons/globe?style=solid)?

**Comment by TurboProgramming** [comment]
> What about the globe icon?

Definitely the best option. Let me create a PR.

**Comment by TurboProgramming** [comment]
Please see #1490 as it works pretty well (screenshot included)

**Comment by rob006** [comment]
These are [web/browser notifications](https://developer.mozilla.org/en-US/docs/Web/API/notification) or notifications displayed on web ([here](https://user-images.githubusercontent.com/5972388/42369027-01881308-8109-11e8-95b8-d8d0a36798cf.png))

**Comment by TurboProgramming** [comment]
@rob006 The second link you gave me, the image of the notification bell needs to stay, that's a notification sign, the reason I opened this PR is web is not relevant with bell, while email is assigned with the email icon.

**Comment by rob006** [comment]
If bell icon is used as a icon of web notifications in menu, then why you want to use different icon for the same thing in settings? For me current design is quite intuitive. After change from #1501 I'm not sure what "web" notifications actually are (I would expect browser push notifications).

**Comment by rob006** [comment]
You're overthinking this. Using one icon for the same thing is consistent and intuitive. "web" and globe icon are too ambiguous. 

Besides you have "web" and "email" labels for some reason. You don't need to duplicate the same meaning by icons.

**Comment by tobscure** [comment]
I'm in agreement with @rob006, I think it's most intuitive for the icon to be consistent with the one in the header. Thanks for the effort that went into this report though.
