### ISSUE TITLE
Loading state of Switch is hard to see

### ISSUE THREAD

**Issue by ardacebi** [flarum/core#1491]
## Bug Report

**Current Behavior**
After changing a setting using a switch at settings, the loader that warns the user the setting is applying appears over the switch instead of appearing next to it, creating a bad looking UI.

**Steps to Reproduce**
1. Go to settings
2. Click on change one of the options with a switch
3. See error

**Expected Behavior**
The loader should appear next to the switch instead of over it.

**Screenshots**

![4765475475](https://user-images.githubusercontent.com/17576065/42244743-d99ba436-7f1e-11e8-97f3-153bcc8264e1.png)

![3546635463](https://user-images.githubusercontent.com/17576065/42244744-da899ce0-7f1e-11e8-9003-ca3f1f7d80bd.png)

Please don't mind the screenshots, I was able to take these even hard because of **the speed of Flarum** 😉 (the loader was going away immediately)

**Environment**
Flarum Community
https://discuss.flarum.org

**Possible Solution**
Move loader next to the switch.

**Comment by franzliedke** [comment]
Oh wow, I never even noticed that loading indicator.

> I was able to take these even hard because of the speed of Flarum :wink:

That must be the reason. :grinning: 

Again, this might be intentional, so let's wait for input from @tobscure.

Since I would like to avoid page content jumping around (which might happen with the indicator appearing next to the toggle button), what about adding a semi-transparent overlay to the button while it is saving the state, with the indicator on top? That way, it would be more visible...

**Comment by TurboProgramming** [comment]
@tobscure Do you have anything about this? We've been waiting you for this 🤔

**Comment by luceos** [comment]
@TurboProgramming please, I urge you to stop bumping (your own) issues!

I think I speak on behalf of all contributors that every comment is read and seeing these bumps pop up just make me want to press "mark all read", which would be detrimental with all the issues I should know about or where I was mentioned.

This is such a minor issue compared to rewriting the full database schema or pushing forwards with releasing beta 8. Toby was already mentioned and seeing his emoji response he already read it. So .. don't bump please 🙏
