### ISSUE TITLE
[Mobile Issue] While scrolling, after a point, the gray background stops coming and text got into themselves creating a bad look

### ISSUE THREAD

**Issue by TurboProgramming** [flarum/core#1493]
## Bug Report

**Current Behavior**
After a point, while scrolling, the gray background stops coming with the topic and the topic title, description etc. got mixed with All Discussions, tags etc. button texts.

**Steps to Reproduce**
1. Go to homepage
2. Scroll a topic to the left
3. See error

**Expected Behavior**
The gray background should not stop coming and should come with the article itself, to prevent it to mix with the background text.

**Screenshots**

![img_1960](https://user-images.githubusercontent.com/17576065/42256997-0f4ad2c6-7f5d-11e8-92fb-790ed6fe6748.PNG)

![img_1961](https://user-images.githubusercontent.com/17576065/42256998-11fe5574-7f5d-11e8-977b-77f27358f5b5.PNG)

**Environment**
Flarum Community
https://discuss.flarum.org

**Note: Keep in mind that this is a mobile-only issue.**

**Comment by dsevillamartin** [comment]
Related to flarum/issue-archive#334

**Comment by TurboProgramming** [comment]
@datitisev So should I close this or remain it opened to remind the developers of the issue?

**Comment by franzliedke** [comment]
Are we talking about scrolling or swiping?

**Comment by franzliedke** [comment]
Yeah, duplicate of flarum/issue-archive#334.
