### ISSUE TITLE
The "Remember me" button checkbox sometimes don't show on Google Chrome and Safari

### ISSUE THREAD

**Issue by TurboProgramming** [flarum/core#1497]
## Bug Report

**Current Behavior**
Sometimes (I wasn't able to reproduce the bug every time) when I launch the login form, the remember me button checkbox didn't appear, but worked when I clicked on it.

**Steps to Reproduce**
1. Go to homepage
2. Click on login
3. See error

**Expected Behavior**
The remember me checkbox should appear always.

**Screenshots**

![34523452345](https://user-images.githubusercontent.com/17576065/42304569-83d2fc22-802f-11e8-9823-3c453a865cb1.png)

**Environment**
Flarum Community
https://discuss.flarum.org

**Comment by TurboProgramming** [comment]
I'm waiting for someone's confirmation on this.

**Comment by franzliedke** [comment]
How often does this happen?

Can you try to reproduce it and check the browser's console for an error message when the problem appears?

**Comment by TurboProgramming** [comment]
It started happening every time now, I refreshed 3 times in a row and the same result.

**There are 2 errors Google Chrome is outputting:**
1. Error in event handler for (unknown): TypeError: Cannot read property 'trace' of undefined at browser.runtime.sendMessage.response (chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/include.preload.js:750:20)
2. Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by franzliedke** [comment]
Please disable all browser extensions (or use incognito mode) and try again. Maybe a conflict with a password manager or something similar?

**Comment by TurboProgramming** [comment]
@franzliedke I did that before reading your response: no luck, the same.

Though I have something: in incognito mode, seems like we don't have any console messages, meaning that those aren't related to what we're working here.

**Comment by franzliedke** [comment]
Is the checkbox DOM element there and just not visible (via CSS etc.)? Or is the element missing?

**Comment by TurboProgramming** [comment]
Let me check.

**Comment by TurboProgramming** [comment]
![4657567467](https://user-images.githubusercontent.com/17576065/42316946-c0b5e338-8053-11e8-8baf-b9de3b5dcbc6.png)

**Comment by franzliedke** [comment]
Can you figure out which CSS rule makes the `<input>` disappear?

**Comment by TurboProgramming** [comment]
When I select `<input>` the following styles appear, so the one and only luck of ours is probably below here somewhere:

```
element.style {
}
.checkbox input[type=checkbox], .checkbox input[type=radio] {
    margin-left: -20px;
    margin-top: 2px;
    float: left;
}
input[type="checkbox"], input[type="radio"] {
    box-sizing: border-box;
    padding: 0;
}
input, button, select, textarea {
    font-family: inherit;
    font-size: inherit;
    line-height: inherit;
}
input {
    line-height: normal;
}
button, input, optgroup, select, textarea {
    color: inherit;
    font: inherit;
    margin: 0;
}
*, *:before, *:after {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
user agent stylesheet
input[type="checkbox" i] {
    -webkit-appearance: checkbox;
    box-sizing: border-box;
}
user agent stylesheet
input[type="radio" i], input[type="checkbox" i] {
    background-color: initial;
    cursor: default;
    margin: 3px 0.5ex;
    padding: initial;
    border: initial;
}
user agent stylesheet
input {
    -webkit-appearance: textfield;
    background-color: white;
    -webkit-rtl-ordering: logical;
    cursor: text;
    padding: 1px;
    border-width: 2px;
    border-style: inset;
    border-color: initial;
    border-image: initial;
}
user agent stylesheet
input, textarea, select, button {
    text-rendering: auto;
    color: initial;
    letter-spacing: normal;
    word-spacing: normal;
    text-transform: none;
    text-indent: 0px;
    text-shadow: none;
    display: inline-block;
    text-align: start;
    margin: 0em;
    font: 400 11px system-ui;
}
user agent stylesheet
input, textarea, select, button, meter, progress {
    -webkit-writing-mode: horizontal-tb !important;
}
.Form--centered .checkbox {
    text-align: left;
}
.checkbox {
    display: block;
    padding-left: 20px;
    margin-bottom: 5px;
    cursor: pointer;
}
user agent stylesheet
label {
    cursor: default;
}
.Form--centered {
    text-align: center;
}
.Modal-body {
    background-color: #e7edf3;
    padding: 25px 30px;
    color: #667d99;
}
body {
    background: #fff;
    color: #111;
    font-family: "Open Sans",Helvetica,Arial,sans-serif;
    font-size: 13px;
    line-height: 1.5;
    overflow-y: scroll;
}
html {
    font-family: sans-serif;
    -ms-text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%;
}
*, *:before, *:after {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
*, *:before, *:after {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
```

**Comment by datitisev** [comment]
@TurboProgramming What version of Chrome are you using? Also, make sure you don't have any extensions enabled in Incognito mode, as you can enable extensions in Incognito through the settings.

**Comment by TurboProgramming** [comment]
> What version of Chrome are you using?

67.0.3396.99

> Also, make sure you don't have any extensions enabled in Incognito mode, as you can enable extensions in Incognito through the settings.

I'm always aware of those things don't worry, there isn't any enabled.

**Comment by datitisev** [comment]
I added those styles you posted above to the inspector stylesheet, making sure they were being loaded by setting `display: none;` to the body (which hid the body, effectively proving that the styles were being loaded). 
However, I can still see the checkbox...

Can you check in the `input`'s computed styles if `-webkit-appearance` is set to `none`? https://stackoverflow.com/questions/16632955/checkboxes-not-displaying-chrome-work-in-other-browsers#23705615 may still be applicable, even though it's from 2013.
If I set `-webkit-appearance` to `none`, then the checkbox disappears.

![image](https://user-images.githubusercontent.com/6401250/42381023-cef4f39e-80fd-11e8-82ee-40dec460eedc.png)


This style, however, is automatically added to inputs of type checkbox through the user agent stylesheet. At least, it's supposed to...

**Comment by TurboProgramming** [comment]
Checkbox has -webkit-appearance set to "checkbox"

**Comment by datitisev** [comment]
@TurboProgramming Does it appear if you click the "Remember Me" label?

**Comment by TurboProgramming** [comment]
No, it stays the exact same.

**Comment by datitisev** [comment]
What happens if you create a checkbox somewhere else in the body without any classes? Just a plain` <input type="checkbox" />`. Does it show?
Make sure to add it as a direct child of `body` so no classes from other elements get applied.

**Comment by TurboProgramming** [comment]
I inserted a blank checkbox to body the same area on Chrome and Firefox. Here are the results.

Chrome:

![45674534567](https://user-images.githubusercontent.com/17576065/42387784-23d71d26-814c-11e8-8763-403d46e22c5e.png)

Firefox:

![screenshot_2018-07-06 flarum community](https://user-images.githubusercontent.com/17576065/42387786-24f01276-814c-11e8-8a12-010186c2887b.png)

**Comment by tobscure** [comment]
Does this happen on Flarum installations other than discuss.flarum.org, or websites other than Flarum?

**Comment by TurboProgramming** [comment]
It does happen on http://104.251.211.123/ too. You can see it yourself. Running Beta 7.

**Comment by datitisev** [comment]
No, I can't see it myself...

![image](https://user-images.githubusercontent.com/6401250/42734643-8cc8f456-8815-11e8-9f45-9411601ea9de.png)

**Comment by TurboProgramming** [comment]
Browser?

**Comment by datitisev** [comment]
@TurboProgramming Chrome Version 68.0.3440.59 (Official Build) beta (64-bit)

**Comment by TurboProgramming** [comment]
![354634563456](https://user-images.githubusercontent.com/17576065/42734830-06ab3710-8853-11e8-90e4-cadeb00d8fdf.png)

I'm on **macOS** testing on **Chrome Version 67.0.3396.99** (Official Build) (64-bit).

**Comment by TurboProgramming** [comment]
Are you on Windows?

**Comment by tobscure** [comment]
@TurboProgramming does it happen on websites other than Flarum?

**Comment by TurboProgramming** [comment]
@tobscure Yes, I tried the signup page at community.makeroid.io (Discourse Community) and it was the same, checkbox invisible.

So, this means that this is a non-Flarum issue?

**Comment by tobscure** [comment]
Yep, this is a you issue ;)
