### ISSUE TITLE
"@" and "*" crashing forum if searched

### ISSUE THREAD

**Issue by ardacebi** [flarum/core#1498]
## Bug Report

**Current Behavior**
I know, this is not something that prevents usability, but it crashes the forum: if I search for @ or * using the search bar, the forum will crash until the ?q=%40 or ?q=* gets deleted from the URL bar.

**Steps to Reproduce**
1. Go to homepage
2. Search for @ or *
3. See error

**Expected Behavior**
The forum should really search for articles including those characters.

**Screenshots**

After searching for "@":

![screenshot_2018-07-05 flarum community 1](https://user-images.githubusercontent.com/17576065/42304970-8154fffc-8031-11e8-8331-e0ec20717ace.png)

After searching for "*":

![screenshot_2018-07-05 flarum community 2](https://user-images.githubusercontent.com/17576065/42304973-8939694c-8031-11e8-8c74-f27d13a3cb61.png)

After refreshing the website without deleting the search query from URL:

![screenshot_2018-07-05 flarum community 3](https://user-images.githubusercontent.com/17576065/42304990-970022aa-8031-11e8-9cab-752158102b5d.png)

**Environment**
Flarum Community
https://discuss.flarum.org

**Additional Context**
I only found these for now, but we may have other characters doing the same (or worse).

**Comment by TurboProgramming** [comment]
The issue is probably the "*" as "@" already gets replaced by it:
https://github.com/flarum/core/blob/master/src/Discussion/Search/Gambit/FulltextGambit.php#L34

**Comment by franzliedke** [comment]
As far as I can tell, the problem is the "*" character, which is a wildcard in MySQL's fulltext search. And that wildcard [needs to have a "real" prefix](https://stackoverflow.com/a/20680736/192741).

So we should ensure that searches do not start with the "*" character. How should Flarum behave in that case, though?

**Comment by TurboProgramming** [comment]
I came up with something, before submitting the search, we can warn the user that the "*" character is removed from the search and after the user dismisses the pop-up, submit the search without the "*" character.

The only solution that can be applied looks like this. What do you think @franzliedke? Any other ideas?

**Comment by franzliedke** [comment]
Just returning an empty result set would be a possible solution as well.

**Comment by TurboProgramming** [comment]
Yes, pretty sure no one will use @ or * in their posts, so when the user submits a search, the core should detect the character and automatically return an empty result.

The pop-up idea is not that great as this, it might take useless time.

**Comment by TurboProgramming** [comment]
The warning message seems to be a great fix. We can have a simple text saying the user that this is a technical problem and some kind of drop-down that explains with a text to advanced users. 

So regular users won't be confused with technical details and advanced users would understand why we return no results.

**Comment by datitisev** [comment]
Talking about ignoring those characters, Github does something similar where it ignores some characters when you search, which can turn out to be quite annoying when looking for specific code, however I don't think it would affect many users here.

![image](https://user-images.githubusercontent.com/6401250/42326213-82ab4294-8036-11e8-9093-85e68da25a40.png)

**Comment by TurboProgramming** [comment]
Even if you search something like backupGlobals="false", the words you need to find that piece of code are enough so it finds it. This will be the same for Flarum users, if a user searches for `Bugs, suggestions, and feedback`, Flarum will get only `Bugs suggestions and feedback`, and list everything related to it. 

> I don't think it would affect many users here.

1 comma wouldn't change the results if a forum is based on all commas. So it won't.

**Comment by luceos** [comment]
linking to #189

**Comment by luceos** [comment]
linking to flarum/issue-archive#286

**Comment by franzliedke** [comment]
I'd consider it going the extra mile in terms of user-friendliness, to avoid confusion (and bug reports ^^). But yeah, probably not important enough at this point.

**Comment by tobscure** [comment]
Not even google goes that extra mile: https://www.google.com/search?q=*
I don't think any user will expect to have meaningful search results when they search for just `*`.

**Comment by franzliedke** [comment]
So all that needs to be done here is the following, right?

- Remove leading `*` characters from the search term.
- Return an empty result set when the search term is an empty string.

**Comment by TurboProgramming** [comment]
@franzliedke I actually have a better solution: for Flarum to give users accurate and better search results, let's do what Discourse is doing:

![screenshot_2018-08-05 makeroid community](https://user-images.githubusercontent.com/17576065/43687770-ffd17b24-98e3-11e8-867c-982aafc6a610.png)

**Comment by franzliedke** [comment]
I just came across an error caused by this bug on discuss.flarum.org, so I went ahead and fixed this for all the special search characters out there.

Reference:
- https://dev.mysql.com/doc/refman/5.7/en/fulltext-boolean.html
- https://stackoverflow.com/questions/26507087/escape-string-for-use-in-mysql-fulltext-search
