### ISSUE TITLE
Profile: Group badges are overlapping

### ISSUE THREAD

**Issue by ardacebi** [flarum/core#1499]
## Bug Report

**Current Behavior**
If a user is inside in multiple groups, group badges don't have spaces between them.

**Steps to Reproduce**
1. Go to homepage
2. Go to a user who is in 2 groups
3. See error

**Expected Behavior**
The badges should have a small space between them.

**Screenshots**

![screenshot_2018-07-05 hossein - appybuilder community](https://user-images.githubusercontent.com/17576065/42338212-c4801c16-8091-11e8-8ded-18a24f26d7d3.png)

**Environment**
- Flarum version: 0.1.0-beta.7

**Possible Solution**
Create spaces between badges.

**Comment by franzliedke** [comment]
Again, might be intentional. Let @tobscure decide.

**Comment by luceos** [comment]
Asked Toby about it. 

"a bit of spacing probably wouldn't hurt there"

**Comment by tobscure** [comment]
Just a pixel or two I reckon.

**Comment by TurboProgramming** [comment]
I'll try my best to open a PR on this.

**Comment by Nayan-Das** [comment]
Can I work on this.

**Comment by ardacebi** [comment]
@Nayan-Das We already have a valid fix waiting to be merged at #1506.
