### ISSUE TITLE
JavaScript module structure and APIs

### ISSUE THREAD

**Issue by tobscure** [flarum/core#150]
**1. Currently we don't have any modules which used named exports — they're all individual and have to been imported as such, and it can get very verbose, e.g.:**
```javascript
import { extend, override } from 'flarum/extension-utils';
import app from 'flarum/app';
import Model from 'flarum/model';
import Component from 'flarum/component';
import Discussion from 'flarum/models/discussion';
import Badge from 'flarum/components/badge';
import ActionButton from 'flarum/components/action-button';
import SettingsPage from 'flarum/components/settings-page';
import DiscussionPage from 'flarum/components/discussion-page';
import icon from 'flarum/helpers/icon';
```
Does this structure need refinement? I think app components are probably OK being independent, but would it be better to make the rest something like this?
```javascript
import app from 'flarum/app';
import { Model, Component } from 'flarum';
import { extend, override } from 'flarum/extension-utils';
import { Badge, ActionButton } from 'flarum/components/ui';
import { icon } from 'flarum/helpers';
import Discussion from 'flarum/models/discussion';
import SettingsPage from 'flarum/components/settings-page';
import DiscussionPage from 'flarum/components/discussion-page';
```
Look into what other frameworks, like Ember and React, are doing.

**2. Do we need a public API layer for the front-end, like we have with Flarum\Extend on the backend? Something like:**

```javascript
import app from 'flarum/app';
import Extend from 'flarum/extend';

app.extend([
  // either this
  (new Extend.Model('flarum/models/discussion'))
    .attribute('subscription'),

  // or this
  new Extend.DiscussionAttribute('subscription'),

  new Extend.DiscussionBadges(function(items) {
    if (discussion.subscription()) {
      items.add('subscription', Badge.component({...}));
    } 
  }),

  new Extend.DiscussionControls(function(sections) {
    sections.user.add('subscription', ...);
  }),

  new Extend.DiscussionSidebar(function(items) {
    items.add('subscription', ...);
  }),

  new Extend.NotificationType(
    'newPosts',
    NewPostsNotification,
    "Someone posts in a discussion I'm following"
  ),

  // Pretty specific ones like this
  new Extend.BeforeDiscussionComposer(function(deferred) {
    // do something before the discussion composer opens (e.g. select tags modal)
  })
]);
```

This will result in a lot of Extend objects though, because there are a lot of extension points in the front end. Still, it's probably a good idea so that our public APIs are all in one place, easy to keep track of, and make sure we don't break them?

**Comment by franzliedke** [comment]
Can't say much about the first part, but I agree that we should have a public API like the second (it seems to work very well on the backend, so that should be a good way forward). This also keeps the surface area smaller, so that we can be more free in changing lots of things behind the scenes, because only those extenders are the public contract.

**Comment by tobscure** [comment]
I've been playing around with this (public JS API), and my feeling is that it seems kinda futile.

Using the Extender concept to apply extensions to various components is all well and good, but things break down when extensions build their own components which need to interact with the rest of the app. Take this snippet from the "edit tags" modal, for example:

```javascript
if (app.current instanceof DiscussionPage) {
    app.current.stream.sync();
}
```

It's checking whether the app's current route is a discussion page, and if so, it's telling the discussion page's post stream to update with any new posts. For this snippet to be "possible", the DiscussionPage component needs to be part of the public API. If one component is part of the public API, all components should be part of the public API. If all components are part of the public API, then what are we doing with Extenders?

Of course, we could rewrite that snippet as an explicit API, perhaps as a static method on an extender, something like `Extend.DiscussionPage.sync()`. But that's a very specific API for a very specific case. What about closing the Modal component, which would normally be done with `app.modal.close()`? Should that be done with `Extend.Modal.close()`? Seems kinda pointless to me.

**Comment by tobscure** [comment]
I that case, I think it's better to implement these "extenders" as simple utility functions that work with the API. And only when they're actually useful and save typing. e.g.
```javascript
  // Instead of:
  app.notificationComponentRegistry['postLiked'] = PostLikedNotification;
  extend(SettingsPage.prototype, 'notificationTypes', function(items) {
    items.add('postLiked', {
      name: 'postLiked',
      label: [icon('thumbs-o-up'), ' Someone likes my post']
    });
  });

  // ... use:
  import { addNotificationType } from 'flarum/extension-utils';
  addNotificationType('postLiked', PostLikedNotification, [icon('thumbs-o-up'), ' Someone likes my post']);

  // but don't use a util for simple things like this:
  Post.prototype.canLike = Model.prop('canLike');
```

**Comment by franzliedke** [comment]
:+1:
