### ISSUE TITLE
Start a Discussion Tag Popup closes in IE 11

### ISSUE THREAD

**Issue by D-mata** [flarum/core#1504]
When creating a new discussion using "Start a Discussion", the modal that appears if a tag is not chosen closes immediately after it appears and leaves the default overlay.

**Steps to Reproduce**
1. Go to 'Start a Discussion'
2. Fill out Title and Post text
3. Then click "Post Discussion"
4. See the popup appear then fade away

**Comment by franzliedke** [comment]
Can anybody reproduce this?

@D-mata Do you see any error messages in the browser's console?

**Comment by TurboProgramming** [comment]
I tested on IE 9, and it works fine. Not sure about IE 11.

![ezgif-4-a352cfbd77](https://user-images.githubusercontent.com/17576065/42734980-511e3246-8855-11e8-8b85-87e29cad711d.gif)

**Environment**
http://104.251.211.123 (Beta 7)

**Comment by TurboProgramming** [comment]
I just tested this on IE 11 too. I can't reproduce this and with IE 11, I'm able to create, delete and edit a post fine.

**Comment by D-mata** [comment]
![flarum-ie11-issue](https://user-images.githubusercontent.com/11344451/43019502-129d186e-8c12-11e8-86b2-30fac11129a9.gif)

There are no errors in the console window, and none in network calls.

**Comment by TurboProgramming** [comment]
https://www.browserling.com/browse/win/7/ie/11/http%3A%2F%2Fdiscuss.flarum.org

I tried here and I see the same output @D-mata is getting. Try it yourself.

**Comment by TurboProgramming** [comment]
> I tried here and I see the exact same output @D-mata is getting. Try it yourself. (Confirming)

Just to make things right, I confirmed this and experiencing the same @D-mata sent on his GIF. Can we remove the needs confirmation label?

**Comment by D-mata** [comment]
So it appears to be this line that doesnt work in IE11:
```
 .one('bsTransitionEnd', function ()
           that.$element.trigger('focus').trigger(e)
```
Removing the command doesn't seem to affect anything. I may try to submit the code change later today.

**Comment by tankerkiller125** [comment]
It appears that as of beta11.1 discuss no longer functions at all in IE11, what is interesting is that my forum that has polyfill.io enabled (added myself) everything works completely as expected including the modules.

**Comment by therealsujitk** [comment]
##Temporary Solution

I faced the same issue on Discuss and on my own forum. No idea why this is happening. I cleared the cache and browser data on my browser (not sure if clearing cache alone is sufficient) and it seems to have fixed the issue for now...

**Comment by franzliedke** [comment]
@tankerkiller125 What about https://nightly.flarum.site/ and https://beta.flarum.site/? Maybe the problem is one of the many extensions enabled on Discuss...

**Comment by tankerkiller125** [comment]
@franzliedke On nightly and beta the tags disappearing still happen, but the overall the site loads. Proxying in Polyfill.io resolves the tags dialog disappearing but I'm not sure why that is since we don't get any console errors. What's interesting is that the dialog is still technically speaking open and you can technically add tags if have an idea of where tags are located and press the enter button, it seems like a potential shadow DOM issue.

**Comment by datitisev** [comment]
This doesn't just occur on IE, it sometimes happens on Chrome and Firefox, among others, with the same behavior @tankerkilker125 describes.

**Comment by matteocontrini** [comment]
Isn't this the same issue as #1813?
