### ISSUE TITLE
Displays a blank page

### ISSUE THREAD

**Issue by liuxingjun** [flarum/core#1510]
## Bug Report

**Current Behavior**

***case one***
visit -> [https://forum.ykxmall.cn/](https://forum.ykxmall.cn/)
result -> Displays a blank page

***case two***
visit -> [https://forum.ykxmall.cn/index.php](https://forum.ykxmall.cn/index.php)

result->The resource file path contains index.php
             Console display  `System is not defined`

**Expected Behavior**
case one : The page content should be displayed
case two : When the resource address is generated，When generating a resource address, there should be no index.php。

**Environment**
- Flarum version: Flarum core 0.1.0-beta.7
- Website URL: https://forum.ykxmall.cn/
- Webserver: nginx
- Hosting environment:  vps 
- PHP version: PHP 7.1.16-1
- Browser: chrome 67

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```
```Shell
Flarum core 0.1.0-beta.7
PHP 7.1.16-1+ubuntu16.04.1+deb.sury.org+1
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, intl, json, exif, mcrypt, msgpack, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, memcached, Zend OPcache
EXT flarum-approval v0.1.0-beta.7
EXT flarum-bbcode v0.1.0-beta.5
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.7
EXT flarum-flags v0.1.0-beta.7
EXT flarum-likes v0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT flarum-mentions v0.1.0-beta.7
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8
Base URL: https://forum.ykxmall.cn/index.php
Installation path: /var/www
```

**Comment by luceos** [comment]
Update your `config.php` inside your flarum installation directory and remove `index.php` in the `url` setting.

**Comment by liuxingjun** [comment]
Many thanks
