### ISSUE TITLE
unicode username 

### ISSUE THREAD

**Issue by hassandraga** [flarum/core#1517]
**using Unicode username.**

I know its low priority feature, but its a good feature for non-English users around the world in the future stable release.

**Comment by TurboProgramming** [comment]
This is already being discussed at #557.

**Comment by luceos** [comment]
@hassandraga thank you for suggesting this feature. Although you make an excellent point, it would be better - as @TurboProgramming points out - to search the issue tracker and [discussions board](https://discuss.flarum.org) before posting.
