### ISSUE TITLE
POS1 doesn't load previous posts in a discussion

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#152]
When I visit a discussion with a lot of posts, I get to see the last post (because I've read all of it).

When jumping to the top of the discussion using the keyboard, I only jump up to the first post that's loaded. That's fine, of course, but it doesn't trigger any loading like when I scroll...

**Comment by tobscure** [comment]
This may be fixed. Will need confirmation when we push to the dev forum again.

**Comment by franzliedke** [comment]
Have you pushed this? :)

**Comment by tobscure** [comment]
Nope

**Comment by franzliedke** [comment]
Awesome, it works!
