### ISSUE TITLE
DiscussionList order not auto updated after replying (posting)

### ISSUE THREAD

**Issue by ardacebi** [flarum/core#1531]
## Bug Report

**Current Behavior**
The topic that a user replies to don't bump up to the top but after refresh, it does.

**Steps to Reproduce**
1. Go to a topic
2. Reply
3. Go to homepage

**Expected Behavior**
The topic that the user replied to should bump up to the top.

**Screenshots**

Before refresh (attention to the Clean & Modern theme topic):

![screenshot_2018-08-10 flarum community](https://user-images.githubusercontent.com/17576065/43970430-46f802b6-9cd6-11e8-96ba-a4f3a4f2bd02.png)

After refresh:

![screenshot_2018-08-10 flarum community 1](https://user-images.githubusercontent.com/17576065/43970432-486033ee-9cd6-11e8-869d-b8f2dc8a61c2.png)

**Environment**
Flarum Community
https://discuss.flarum.org

**Comment by tobscure** [comment]
I would say this is a feature, not a bug. When you return from a discussion to the discussion list, everything should be in the same order as you left it, otherwise it would be confusing. Only by refreshing are you explicitly asking for the most up-to-date order of discussions.

**Comment by ardacebi** [comment]
Reasonable enough. 👍
