### ISSUE TITLE
Do we really need to namespace extension "names" by vendor?

### ISSUE THREAD

**Issue by tobscure** [flarum/core#154]
As in "flarum-likes", "flarum-markdown", etc.

I just noticed that Atom (which has a lot of packages) doesn't bother: https://atom.io/packages

Drupal modules are the same.

Would be simpler without the namespace. I thought it would be good to reduce conflicts, but maybe that wouldn't actually be an issue.

**Comment by jmichaelward** [comment]
I'm not familiar with the Atom package library, but is there a difference between 'official' Atom packages versus 'unofficial' ones (e.g., packages developed by the core team versus packages developed by the community)? If so, it way be a way to differentiate a package from the team that developed Flarum versus one from someone in the community (if such a differentiation is deemed necessary).

I'm sure you're plenty familiar with the Grunt packages that are out there, many of which are prefixed with grunt-. I'm guessing the same thing is at play here.

Whether or not these are good reasons, I don't know, but they are probably reasons to someone, somewhere. In my view, if namespaces exist to help prevent possible code collisions, they are rarely bad. If that's not the issue in this case, then it should certainly be up for debate.

My unsolicited $.02. :)

**Comment by franzliedke** [comment]
After talking to Toby, I vote to not have any vendor namespacing. We can still encourage a bit of namespacing by prefixing the official extensions' IDs with something like "flarum-" or "ext-".

**Comment by tobscure** [comment]
Yep, agreed. I don't even think a namespace is necessary for the official extensions; this differentiation can occur in the extension's metadata and thus how/where it is displayed in the marketplace.

I will close this once I remove the namespaces from current extensions, and from the extension generator.
