### ISSUE TITLE
[Mobile] Sliding discussion item while dark mode is enabled causes b-color issue

### ISSUE THREAD

**Issue by ardacebi** [flarum/core#1548]
## Bug Report

**Current Behavior**
Sliding a discussion item on the discussion list **while dark mode is enabled** causes the background color of the list to become white because of manual color setting (line 44):

https://github.com/flarum/core/blob/c16ddf24f2159c36e9026cb89457ec929a081fcc/less/forum/Slidable.less#L42-L48

**Steps to Reproduce**
1. Enable Dark Mode
2. Launch Flarum home screen on mobile
3. Start sliding a discussion to reveal more button

**Expected Behavior**
Background color should stay something dark to match up with dark mode.

**Screenshots**

![](https://cdn.discordapp.com/attachments/360689688815730701/479259166008147968/Registrazione_schermo_2018-08-15_alle_15.02.55.gif)

**Environment**
- Flarum version: 0.1.0-beta.7
- Website URL: localhost
- Webserver: apache
- Hosting environment: local
- PHP version: 7.2.1
- Browser: firefox quantum

**Comment by matteocontrini** [comment]
Hello, this is still an issue.

Would it be a solution to use the `@control-bg` variable instead of the hardcoded white, as the Night Mode extension was doing?

https://github.com/FriendsOfFlarum/nightmode/blob/b972c5ffcd6875be3d98fdbb87a1856dfcd36334/resources/less/forum/extension.less#L490-L500

**Comment by askvortsov1** [comment]
That definitely seems like a sensible solution! A PR would be welcome
