### ISSUE TITLE
Secondary tags order not respected in frontend

### ISSUE THREAD

**Issue by breathingboard** [flarum/core#1549]
You can create secondary tags a, b, c, and they will be in that order in the backend since secondary tags are listed alphabetically, but in the front end, they will not be in that order. 

It would be best to make it so that you can reorder secondary tags. If that happened then this issue would be resolved in a way because you could manually reorder them.

**Comment by tobscure** [comment]
The current implementation is a design decision: the three most popular secondary tags are displayed in the sidebar below the primary tags. Secondary tags do not have "order".

**Comment by breathingboard** [comment]
That makes sense. Thanks!
