### ISSUE TITLE
Extensions: Drop support for bootstrap.php

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#1557]
Kill the fallback introduced in #1556.

**Comment by franzliedke** [comment]
@flarum/core Should we revert this as it's a rather nitpicky BC break that could annoy extension developers unnecessarily? I would push it back to the stable 0.1 release.

**Comment by datitisev** [comment]
I agree with that. While we might (and often do) need to make breaking changes, this one is unnecessary at this point.

**Comment by franzliedke** [comment]
Okay, reverted. Will move this back to 0.1-stable.
