### ISSUE TITLE
UNREAD counter is not fully visible

### ISSUE THREAD

**Issue by Eldenroot** [flarum/core#1569]
![image](https://user-images.githubusercontent.com/778890/45639425-446ffb00-bab0-11e8-9455-b1c44c06532a.png)

Flarum discuss board flarum.org

Unread indicator is not fully visible :(

**Comment by luceos** [comment]
Should we keep it as is (relative size compared to the rest) or give it a min height?

**Comment by tobscure** [comment]
Pagination is planned for a [redesign](https://github.com/flarum/core/issues/115#issuecomment-294070243) anyway so not particularly important

**Comment by Eldenroot** [comment]
Still valid...
