### ISSUE TITLE
IE11 upload doesnt work

### ISSUE THREAD

**Issue by D-mata** [flarum/core#1572]
Uploading does not work in IE11. See below.

![flarum-ie11-issue](https://user-images.githubusercontent.com/11344451/45767519-3aa0e180-bbef-11e8-93e6-0beda15aa2b9.gif)

**Comment by datitisev** [comment]
Most likely related to #1125.

**Comment by franzliedke** [comment]
Closing as duplicate(-ish) of #1125 and #1242. Thanks for the report.
