### ISSUE TITLE
Disabled user can't get itself from API, causing 500 error on any page

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#1573]
(as initially reported on Discord)

## Bug Report

**Current Behavior**
Now that an internal API call is used to get the user attributes for the session, it requires the user to be able to see itself. However the disabled user is considered as a guest and can't see itself.

**Steps to Reproduce**
1. Create new account
2. See `No query results for model [Flarum\User\User]` error

**Or**
1. Set `is_email_confirmed` to 0 in the database for any user
2. Login with that user 
3. See `No query results for model [Flarum\User\User]` error

**Expected Behavior**
This internal API call should never fail

**Screenshots**

**Environment**
- Flarum version: dev-master

**Possible Solution**

It's probably not a regression, the only cause I can find in the (good) change of using an internal API request for the user resource instead of calling the serializer directly like previously.

I don't really understand how the visibility scope works but it's probably something there that should be changed so any user can always see itself.

**Comment by tobscure** [comment]
I can't reproduce this on dev-master :thinking:

**Comment by tobscure** [comment]
@clarkwinkelmann can you please try to reproduce this on latest dev-master?

**Comment by clarkwinkelmann** [comment]
Doing that tomorrow!

>
If it works on a fresh dev-master I'm curious what I managed to do on my
dev install to get this...

**Comment by clarkwinkelmann** [comment]
Okay I removed lock file, installed again and now everything's fine.

Reverting to the previous commit of master I was using didn't cause the issue again so it must be linked to an outdated dependency in my previous lockfile.

I suppose this can be closed. I still have a lockfile that can replicate it, but it's using a previous version of dev-master and previous versions of core extensions as well so I don't think it deserves more digging.

**Comment by franzliedke** [comment]
Thanks for digging!
