### ISSUE TITLE
ConfigureMiddleware Event is deprecated with seemingly no replacement

### ISSUE THREAD

**Issue by CDK2020** [flarum/core#1579]
## Bug Report

[ConfigureMoiddleware](https://github.com/flarum/core/blob/master/src/Event/ConfigureMiddleware.php) event is deprecated and there seems to be no way to add a middleware after it is removed. Perhaps it could be turned into an extender?

**Comment by tobscure** [comment]
A Middleware Extender is planned and the internal implementation will be different (see https://github.com/flarum/core/pull/1462). @franzliedke will be making issues for further Extender implementations soon.

**Comment by franzliedke** [comment]
Indeed. Closing this as duplicate. :wink: 

Thanks for thinking along!
