### ISSUE TITLE
Something went wrong while trying to load the full version of this site.

### ISSUE THREAD

**Issue by jerauf** [flarum/core#1583]
Just installed this and I'm getting an error "Something went wrong while trying to load the full version of this site."

The page has the site name at the top, the error text, "All Discussions" and "Next Page", all in Times without any formatting.

This shows when on x.com/install/all?page=3 (right after installation).

When I inspect the page, I get these errors:

x.com/install/assets/forum-aeb8c780.css net::ERR_ABORTED 404 (Not Found)
x.com/install/assets/forum-en-df77f08d.js net::ERR_ABORTED 404 (Not Found)
x.com/install/assets/forum-463e7003.js net::ERR_ABORTED 404 (Not Found)
x.com/install/assets/forum-en-df77f08d.js net::ERR_ABORTED 404 (Not Found)
all?page=3:86 Uncaught ReferenceError: System is not defined
    at all?page=3:86
﻿
When you hit the index page, it is blank.

I'm seeing no change, whether debug is on or off. I also cleared the cache, as I found on the "Common Issues" page of Flarum's install guide.

**Comment by franzliedke** [comment]
This is not the right place for getting support. We only discuss bug reports and features to-be-implemented here on GitHub. Please take your discussion to [our forums](https://discuss.flarum.org). More people can help out there,

When you do so, please make sure to describe in much detail as possible:
- what problem you are having,
- what steps you took so far,
- what went wrong,
- what happened and what you would have expected instead.

Please help us help you!

---

That said, when opening an issue on GitHub, please respect and use our [issue templates](https://github.com/flarum/core/issues/new?template=bug-report.md) and provide the requested info, such as the output of `php flarum info`. This is a matter of respecting the developers' time and efforts.
