### ISSUE TITLE
Do you plan to provide an updating doc soon ?

### ISSUE THREAD

**Issue by clrh** [flarum/core#1585]
**Current Behavior**

The page https://flarum.org/docs/translate/updating/ is empty :)

**Comment by clrh** [comment]
If no, what would be the path to do it ?

**Comment by ardacebi** [comment]
Related #1000

**Comment by datitisev** [comment]
We are updating docs in https://github.com/flarum/docs for beta 8.

The docs will be ready and better than ever for both users & extension developers when beta 8 drops or sometime later.

**Comment by franzliedke** [comment]
Let's keep this issue tracker for bug reports and planned features. The question was answered well. :)
