### ISSUE TITLE
Upgrade twitter bootstrap (js) to version 4

### ISSUE THREAD

**Issue by luceos** [flarum/core#1589]
Even though we're only using the JS side of twbs, we need to upgrade it to at least version 4.

**Comment by franzliedke** [comment]
I've upgraded to the latest 3.x version of Bootstrap to fix a vulnerability in its JS code.

**Comment by luceos** [comment]
Ref https://github.com/flarum/core/commit/d959d085612ee501345f7b7afd9feb6e29329669

**Comment by askvortsov1** [comment]
We're now planning to drop bootstrap js (and jquery) completely, so this is no longer planned.
