### ISSUE TITLE
Question: How is a deleted users message displayer?

### ISSUE THREAD

**Issue by lightonflux** [flarum/core#159]
Hello, just found flarum because i checked on fluxbb 2.0 status.

My question is how flarum displays/handles message by deleted users.

Examples: 

 * [deleted]  – like reddit
 * just disable login for the account and leave everything as is
 * disable account login and don't show links for the users just the name, so people can't easily track ones post history 

And if only user id are in the DB would it be possible to reclaim the name? IMHO the account name should land on a black list so people can't imposter old members of the forum.

**Comment by tobscure** [comment]
[deleted], like reddit.

> IMHO the account name should land on a black list so people can't imposter old members of the forum. 

This could easily be implemented as an extension.
