### ISSUE TITLE
Configurable paths

### ISSUE THREAD

**Issue by luceos** [flarum/core#1591]
In the config we find the ability to override paths for api and admin.

In the ApiServiceProvider we see the registration of these paths as follows:

```php
        $this->app->extend(UrlGenerator::class, function (UrlGenerator $url) {
            return $url->addCollection('api', $this->app->make('flarum.api.routes'), 'api');
        });
```

This makes me believe we're not taking the configurable route prefixes into account and we either drop that ability or implement it.

**Comment by luceos** [comment]
Seems like Foundation\Application uses it for creating an url..

```php
    public function url($path = null)
    {
        $config = $this->make('flarum.config');
        $url = array_get($config, 'url', array_get($_SERVER, 'REQUEST_URI'));

        if (is_array($url)) {
            if (isset($url[$path])) {
                return $url[$path];
            }

            $url = $url['base'];
        }

        if ($path) {
            $url .= '/'.array_get($config, "paths.$path", $path);
        }

        return $url;
    }
```

**Comment by franzliedke** [comment]
What exactly is the question here?

Take a look at these lines: https://github.com/flarum/core/blob/8474dfd6e2cc8298176f0e088f0786ef099d0b73/src/Foundation/InstalledApp.php#L60-L64

That's where they are *really* used.

**Comment by luceos** [comment]
I'm mystified, I couldn't trace it back there.
