### ISSUE TITLE
Mobile: Install to homescreen

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#160]
A nifty Android feature - https://developer.chrome.com/multidevice/android/installtohomescreen explains how to do it.

Not urgent, but I'd like to see this integrated in the final version.

**Comment by rodrigoargumedo** [comment]
gets my :+1: from me.

**Comment by Ralkage** [comment]
They made this even easier now :)

https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/

**Comment by TurboProgramming** [comment]
[This issue needs the `mobile` tag]

**Comment by askvortsov1** [comment]
https://github.com/askvortsov1/flarum-pwa :D

**Comment by askvortsov1** [comment]
Since this has been demonstrated to be doable in the extension space, and it doesn't seem to provide extension points for other extensions, and isn't really an "essential core feature" of forum software, I'm going to close this. If anyone has objections please feel free to comment.
