### ISSUE TITLE
PHP Extender: Rendering

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#1602]
We need another extender that allows setting variables when rendering a HTML frontend (e.g. the forum). This will replace code like this in the statistics extension:

~~~php
public function addStatisticsData(Rendering $event)
{
    if ($event->isAdmin()) {
        $event->view->setVariable('statistics', array_merge(
            $this->getStatistics(),
            ['timezoneOffset' => $this->getUserTimezone()->getOffset(new DateTime)]
        ));
    }
}
~~~

Follow-up to #851.

**Comment by tobscure** [comment]
Since any work done on the HtmlDocument is related to a frontend, I'm thinking we can just add a new method to the `Frontend` extender:

```php
(new Extend\Frontend('admin'))
    ->js(__DIR__.'/js/dist/admin.js')
    ->css(__DIR__.'/less/admin.less')
    ->document(function (HtmlDocument $document) {
        $document->payload['statistics'] = 'blah';
    })
```

Sound good?

**Comment by franzliedke** [comment]
Yep, sounds good. I made this work, PR incoming...

Just note that for flarum/statistics, due to the size of the listener, I allowed registering callbacks by name (needs to pass the name of an invokable class, which is then built by the container):

~~~php
(new Extend\Frontend('admin'))
    ->js(__DIR__.'/js/dist/admin.js')
    ->css(__DIR__.'/less/admin.less')
    ->document(Listener\AddStatisticsData::class)
~~~
