### ISSUE TITLE
b8 installer issue with subdirectories

### ISSUE THREAD

**Issue by luceos** [flarum/core#1604]
I currently have an issue with installation via web in a subdirectory. The app throws an RouteNotFoundException. For some reason it's unable to understand the current host and add the prefix it used to do.

I've tested this with url: http://flagrow.test/community

**Comment by franzliedke** [comment]
When is the error thrown? After installation, which is completely successful?

**Comment by luceos** [comment]
No this happens immediately after composer installation. The error is thrown in the Installer (wizard). As the installer command runs in console, there's no issue there. But installation in a subdirectory is broken right now.

**Comment by franzliedke** [comment]
Please confirm this works now. Not sure how this could work before, to be honest.
