### ISSUE TITLE
b8 issue with admin frontend in subdirectory

### ISSUE THREAD

**Issue by luceos** [flarum/core#1606]
## Bug Report

**Current Behavior**

There's strange behavior when installing in a subdirectory. Somehow the JS frontend is redirecting to an url postfixed with the subdirectory, eg: `http://flagrow.test/community/admin#/community/`, clicking any nav tab fails without error, changing the path to `http://flagrow.test/community/admin#/community/permissions` does open the permission tab.

**Steps to Reproduce**
1. Install flarum in a subdirectory
2. Log in and open the admin
3. Try clicking a tab.

**Expected Behavior**
No postfix in the path.

**Environment**
- Flarum version: beta 8

**Possible Solution**

I tried looking into it, but haven't found any indication of a cause yet.

**Comment by CDK2020** [comment]
Looks like something similar happens even without sub directory use. The back button completely doesn't work in the admin page.

**Comment by franzliedke** [comment]
@Shahiem Thanks for looking into it. Let's wait what @tobscure makes out of this. ;)
