### ISSUE TITLE
pusher-ext doesn't send out notifications to pusher.com

### ISSUE THREAD

**Issue by smellymoo** [flarum/core#1609]
## Bug Report

no matter how you configure the clusters, the pusher extension just doesn't send out any notifications when a message is posted.

If I use debug from the pusher.com console to send out a notification it displays the yellow bar as expected in flarum though. Also it's logging clients connected. So everything works except no notifications are being sent (to pusher.com) when there is a new message.

**Environment**
- Flarum version:  0.1.0-beta.7
- Webserver: Apache 2.4
- PHP version: 7.1
- Browser: firefox quantum 62.0.3 (64-bit) on linux

**Comment by smellymoo** [comment]
I do about 1 bug report a year, as I normally debug it myself. So time respected and post updated.

**Comment by franzliedke** [comment]
Thanks a lot!

**Comment by franzliedke** [comment]
Now we need a confirmation on the latest dev-master, though. If it cannot be confirmed (e.g. on discuss.flarum.org), then we can consider this fixed in the upcoming beta-8 release.

**Comment by luceos** [comment]
So the problem here is that pusher-php isn't connecting to the pusher server to send messages. Most likely these will cause exceptions logged in `storage/logs/flarum.log`, @smellymoo can you check that file for any errors related to pusher?

Discuss is currently working fine, and I don't remember this being an issue in beta 7+. @smellymoo can you post your pusher settings, without the key/secret?

**Comment by smellymoo** [comment]
pusher.com shows connections as expected (with subscribes to the right channels), just it isn't sending anything when a new post is sent.

nothing relevant looking, last weeks have only these (repeated):
production.DEBUG: Flarum\Http\Exception\RouteNotFoundException in /home/public/flarum/vendor/flarum/core/src/Forum/Controller/DiscussionController.php:109

production.DEBUG: Flarum\Core\Exception\PermissionDeniedException in /home/public/flarum/vendor/flarum/core/src/Core/Access/AssertPermissionTrait.php:26

I tried cluster: "", "mt1", "eu".

**Comment by saleksin** [comment]
Is your forum public, or private? Because it does not send notifications, if guest user cannot see the message. It is probably by design for now.

**Comment by smellymoo** [comment]
Is your forum public, or private?

ah, that is probably the reason then, it is private.
