### ISSUE TITLE
Remove all beta references in installer / config / code

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#1611]
Just a reminder ticket for the first stable release...

Some parts of the source code still mention Flarum being in beta and not being production-ready. Those things should either be removed or re-worded.

- [ ] Docs
- [ ] flarum/core
- [ ] flarum/flarum
- [ ] Website

**Comment by askvortsov1** [comment]
CLosing in favor of https://github.com/flarum/core/issues/2700
