### ISSUE TITLE
Header can overflow on small screens

### ISSUE THREAD

**Issue by tobscure** [flarum/core#162]
![screen shot 2015-07-01 at 5 15 10 pm](https://cloud.githubusercontent.com/assets/128862/8449917/d33890fc-2014-11e5-9ed8-7c0f70a63697.png)

**Comment by franzliedke** [comment]
Does that mean we only need to adapt the media queries a bit?

**Comment by tobscure** [comment]
For tablet width, we don't want the search field to expand when focused.

We should also have some measure in place to prevent the header content from wrapping if it does still end up being too wide (e.g. due to the additions of an extension).
