### ISSUE TITLE
b8 CorePayload can't access ShowUserController

### ISSUE THREAD

**Issue by luceos** [flarum/core#1626]
## Bug Report

**Current Behavior**

In the current dev-master when the show user permission is at its default to members. You will get a weird error because:

- getDataFromApiDocument assumes a data key exists in the payload, with a 404 this is not true.
- getUserApiDocument will hit the ShowUserController internally, which faults to a 404.

**Steps to Reproduce**

1. do a clean install
2. sign up

**Screenshots**

![](https://cdn.discordapp.com/attachments/360683284117585920/509471282124029964/unknown.png)

**Environment**
- Flarum version: dev-master

**Possible Solution**

- use array_get on getDataFromApiDocument
- allow internal client to bypass permission

**Related**

- https://canary.discordapp.com/channels/360670804914208769/360689688815730701/504441480753053697
- https://discordapp.com/channels/360670804914208769/360683284117585920/509470940502032394

**Comment by luceos** [comment]
It seems [this issue with byobu](https://discuss.flarum.org/d/4762-flagrow-by-bu-well-integrated-advanced-private-discussions/311) is related. There's no way to identify the root cause without having access to the Flarum installation because `getDataFromApiDocument` demands a `data` key in the array.

Please note Byobu has no Forum controllers/routes of its own.

**Comment by franzliedke** [comment]
@luceos Just so I understand you correctly: the issue is that error responses from the API layer trip up the `CorePayload` class and its `getDataFromApiDocument`, making it hard to identify the exact error from the API response?

**Comment by luceos** [comment]
@franzliedke yes exactly. Internally using the Client is okay, but not handling any error it throws makes it terrible to trace, especially when this happens on systems you have no access to.
