### ISSUE TITLE
A serious leak

### ISSUE THREAD

**Issue by aiyijing** [flarum/core#1628]
-- modded for security --

**Comment by luceos** [comment]
Thanks, I've confirmed the issue and found the cause of this. I am going to move this off of the public tracker so that no one can abuse this.

**Comment by franzliedke** [comment]
Thanks indeed. Good thing beta.8 is right around the corner. ;)

**Comment by aiyijing** [comment]
Because this problem was discovered in the process of developing plug-ins recently. Nor did I find the right way to solve it because he was the core document

**Comment by luceos** [comment]
Although we're very glad about the issue, next time please use the directions mentioned in our contributor details: https://github.com/flarum/flarum/blob/master/CONTRIBUTING.md#security-vulnerabilities

**Comment by Zeokat** [comment]
Can you provide a fix that we can apply temporarily to solve this? I don't want to wait until beta 8 that who knows when it will be released.

Meanwhile the emails of registered users are being exposed.

**Comment by aiyijing** [comment]
I'm very sorry, but I just want you to update the core files. I didn't expect such an irretrievable problem. I modified the UpdateUserController.php file.
`
if(!$actor->isAdmin())
{
                $id=$actor->id;       
}
`

**Comment by luceos** [comment]
I'm closing this, because discussing this openly only opens up further potential of forums being hacked.
