### ISSUE TITLE
Routes extender cannot use Content, only handler

### ISSUE THREAD

**Issue by luceos** [flarum/core#1637]
A refactor to allow `$route->toForum()` to pass through to the frontend can only be used inside core. If you are interested in doing additional permission checks (which was previously possibly by doing the below) you can no longer do that:

```php
<?php

namespace Flagrow\Aqueduct\Http\Controllers;

use Flarum\Forum\Controller\FrontendController;
use Flarum\User\User;
use Flarum\Http\Exception\RouteNotFoundException;
use Psr\Http\Message\ServerRequestInterface as Request;

class BoardController extends FrontendController
{
    protected function getView(Request $request)
    {
        /** @var User $actor */
        $actor = $request->getAttribute('actor');

        if ($actor->cannot('discussion.flagrow.aqueduct.board-access')) {
            throw new RouteNotFoundException();
        }

        return parent::getView($request);
    }
}
```

The new behavior allows for Content to be shown:

```php
    $map->get(
        '/all',
        'index',
        $route->toForum(Content\Index::class)
    );
```

But this requires `$route` (RouteHandlerFactory) to be available inside the Routes extend as well. Can we move that in so that you can use either a Handler or Content?

Content allows for pre-seeding values or doing permission assertions.

**Comment by tobscure** [comment]
Use the Frontend extender's route method to set up a route with content?

**Comment by franzliedke** [comment]
That is correct.

**Comment by luceos** [comment]
Cool thanks, totally missed that one 😬
