### ISSUE TITLE
Emoji picker doesn't place cursor at the right place

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#1638]
## Bug Report

**Current Behavior**
After you insert an emoji with the new beta 8 picker, the cursor always ends up at index 2 (maybe sometimes 1 or 3, depending on emoji length) of the textarea once the emoji is inserted.

**Steps to Reproduce**
1. Open the discussion/post composer
2. Type some text so the textarea isn't empty
3. Type `:` or the emoji icon to bring up the emoji picker
4. Select an emoji via enter or by clicking
5. The cursor is placed at the beginning of the texteara

**Expected Behavior**
The cursor should be placed after the newly inserted emoji

**Environment**
- Flarum version: dev-master
- Browser: Firefox, Chrome, probably all

**Possible Solution**

It looks like once `composer.editor.setValue` is called in https://github.com/flarum/emoji/blob/43ba700e8ac6db7006adb57931c97b7d07550d5e/js/src/forum/addComposerAutocomplete.js#L30 this triggers the `input` event, which resets `emojiStart` to zero. So when https://github.com/flarum/emoji/blob/43ba700e8ac6db7006adb57931c97b7d07550d5e/js/src/forum/addComposerAutocomplete.js#L32 runs, `emojiStart` no longer has the correct value and the custor is placed at `0 - 1 + insert.length` everytime.

I suppose we either need to compute `index` before calling `composer.editor.setValue` or create another variable that will hold `emojiStart` value until the method finishes its work.

I tried it locally and these options fix the issue. I'm just unsure which is best. I can prepare a PR if needed.

**Additional Context**
Happens on Discuss so very noticeable.

The issue was introduced in https://github.com/flarum/emoji/commit/8a8d4b920c13b655f7b707a8c3895f1f98f31763 by adding an `input` event listener.

**Comment by tobscure** [comment]
Thanks for the thorough report. A PR for option no. 1 (compute `index` before calling `setValue`) would be great :)

**Comment by clarkwinkelmann** [comment]
@tobscure I suppose a comment will prove valuable to describe why this operation is done beforehand ? I'm never too sure about how detailed I should be with comments.

Does something like this looks clear enough ?

```js
// When calling setValue(), emojiStart will be set back to 0 so we need to compute this beforehand
const index = emojiStart - 1 + insert.length;
```

**Comment by tobscure** [comment]
Looks good to me!
