### ISSUE TITLE
Links do not work when a Chrome AdBlock Plugin is enabled

### ISSUE THREAD

**Issue by haobinliang** [flarum/core#164]
I am using Advertising Terminator (https://chrome.google.com/webstore/detail/%E5%B9%BF%E5%91%8A%E7%BB%88%E7%BB%93%E8%80%85/fpdnjdlbdmifoocedhkighhlbchbiikl), which is a fairly popular adblock extension in China. Chrome does not load content of target link, however, the title of the tab in Chrome does change properly.

![screen shot 2015-07-01 at 23 26 11](https://cloud.githubusercontent.com/assets/7793969/8466267/a5f54584-2048-11e5-95eb-c486474d0099.png)
(When I clicked the thread "From Beta to Final Version" on the index page)

**Comment by tobscure** [comment]
Any JavaScript errors in the console? (View > Developer > JavaScript Console)

**Comment by Seevil** [comment]
It's no a bug, is Chrome plug-in error, and in China popular is Adblock Plus.
这不是什么 bug，是Chrome插件的错误，而且在中国流行的是Adblock Plus。

**Comment by haobinliang** [comment]
@tobscure Below is the console output which I am not sure if helps.

```
Uncaught TypeError: Cannot call a class as a function
	t.classCallCheck @ forum-3lERXKevTPzqGBoN.js:1
	t @ forum-3lERXKevTPzqGBoN.js:12
	(anonymous function) @ VM1117:6
	o @ forum-3lERXKevTPzqGBoN.js:1
	o @ forum-3lERXKevTPzqGBoN.js:1
	o @ forum-3lERXKevTPzqGBoN.js:1
	o @ forum-3lERXKevTPzqGBoN.js:1
	o @ forum-3lERXKevTPzqGBoN.js:1
	o @ forum-3lERXKevTPzqGBoN.js:1
	o @ forum-3lERXKevTPzqGBoN.js:1
	o @ forum-3lERXKevTPzqGBoN.js:1
	o @ forum-3lERXKevTPzqGBoN.js:1
	o @ forum-3lERXKevTPzqGBoN.js:1
	o @ forum-3lERXKevTPzqGBoN.js:1
	i.render @ forum-3lERXKevTPzqGBoN.js:1
	m @ forum-3lERXKevTPzqGBoN.js:1
	i.redraw @ forum-3lERXKevTPzqGBoN.js:1
	i.endComputation @ forum-3lERXKevTPzqGBoN.js:1
	oe @ forum-3lERXKevTPzqGBoN.js:1
	i.mount.i.module @ forum-3lERXKevTPzqGBoN.js:1
	(anonymous function) @ forum-3lERXKevTPzqGBoN.js:1
	v @ forum-3lERXKevTPzqGBoN.js:1
	i.route.ue @ forum-3lERXKevTPzqGBoN.js:1
	i.route @ forum-3lERXKevTPzqGBoN.js:1
	g @ forum-3lERXKevTPzqGBoN.js:1
```

@Seevil Do not mistake "fairly" as "the most".

**Comment by Seevil** [comment]
好吧，你赢了。

**Comment by tobscure** [comment]
Still happening?

**Comment by Seevil** [comment]
@tobscure 
I do not know, I think it was his own browser issue.
不知道，我认为是他自己浏览器的问题。
----------------------------------------------------------
@haobinliang 
而且作为一个中国人对中国人竟然不说中国话，表示费解。nizaizhuangbi？

**Comment by tobscure** [comment]
Closing this then, comment if there's any new info.
