### ISSUE TITLE
Upgrade to Laravel 5.7

### ISSUE THREAD

**Issue by tobscure** [flarum/core#1640]
We're currently on Laravel 5.5, which is an [LTS release](https://laravel.com/docs/5.7/releases#support-policy). But I think we should still try to keep on the latest? It shouldn't be a huge amount of work to upgrade by the looks of it.

https://laravel.com/docs/5.6/upgrade
https://laravel.com/docs/5.7/upgrade

**Comment by franzliedke** [comment]
Fine with me. We can try to catch up during the next beta releases, and then try to upgrade regularly.

**Comment by luceos** [comment]
I personally think it best to push out an upgrade as soon as a new Laravel version is released. Taylor isn't really going to release a huge backward breaking version soon anyway, the framework stabilised and is mature so it all should be pretty manageable to do.

**Comment by franzliedke** [comment]
@luceos We still need to revert #1656.

**Comment by luceos** [comment]
#1656 reverted, in all core extensions as well.

**Comment by franzliedke** [comment]
Apparently, [mentions](https://github.com/flarum/mentions/commit/3ef5ac0cce350aff9db93c28c8ba3432dab86bcd) and [likes](https://github.com/flarum/likes/commit/c2281d14f6e9268c6eb306781ffb43d74095cc9e) were forgotten.

Did that now. :wink:

**Comment by luceos** [comment]
🤔 odd, maybe forgot to commit them, thanks 👍
