### ISSUE TITLE
New command to publish assets

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#1644]
From https://github.com/flarum/core/commit/b26eb8e609006f7199ffe07e6a36e5503165dc43:

Extract publishing assets from the `migrate` command into a new command. Possible names:

* `publish`
* `vendor:publish` (this is what Laravel uses right?)
* `asset(s):publish`
* ...

Also will need to consolidate the publishing logic with the installer while we're at it.

**Comment by luceos** [comment]
I am in favor of `asset:publish`. 

- Can we allow other extensions to hook into this command to be able to publish their extensions as well. 
- I've also felt that the way vendor:publish works with the `--provider` or `--tag` flag was pretty overcomplicated, although it suits the frameworks needs. Maybe we can make this interactive once it grows too much by allowing the user to toggle what extension is allowed to publish?

**Comment by lubobill1990** [comment]
+1
