### ISSUE TITLE
Forums Rendered Unusable After Enabling Extension

### ISSUE THREAD

**Issue by popatop15** [flarum/core#1645]
## Bug Report

**Current Behavior**
With a fresh install of _0.1.0-beta.7.2_ I go to enable one of the pre-installed extensions (any of them) and the software stops responding to my currently logged in session. If I try to visit the forums after enabling an extension I see a red alert bar at the top of the screen under the header which reads "Something went wrong while trying to load the full version of this site." To resolve this issue I have to manually clear my browser's cache. 

**Steps to Reproduce**
1. Install and setup Flarum 0.1.0-beta.7.2 + Nginx
2. Try to enable an extension 

**Expected Behavior**
I expected the extension to enable and prompt  me with a settings modal

**Screenshots**
I can supply a screenshot if needed, I would have to reproduce the issue again.

**Environment**
- Flarum version: 0.1.0-beta.7.2
- Webserver: Nginx
- Hosting environment: VPS via Digital Ocean running CentOS 7
- PHP version: 7.2.11
- Browser: Chrome Version 70.0.3538.102 (Official Build) (64-bit)

```
Flarum core 0.1.0-beta.7.2
PHP 7.2.11
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, exif, mysqlnd, PDO, Phar, SimpleXML, sockets, sqlite3, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, zip
EXT flarum-approval v0.1.0-beta.7
EXT flarum-bbcode v0.1.0-beta.5
EXT flarum-emoji v0.1.0-beta.6
EXT flarum-english v0.1.0-beta.7
EXT flarum-flags v0.1.0-beta.7
EXT flarum-likes v0.1.0-beta.6
EXT flarum-lock v0.1.0-beta.7
EXT flarum-markdown v0.1.0-beta.5
EXT flarum-mentions v0.1.0-beta.7
EXT flarum-sticky v0.1.0-beta.7
EXT flarum-subscriptions v0.1.0-beta.6
EXT flarum-suspend v0.1.0-beta.7
EXT flarum-tags v0.1.0-beta.8
```
_**Note:**_ I disabled all non-default extensions

**Possible Solution**
Clear your browser cache

**Additional Context**
N/A

**Comment by luceos** [comment]
This was fixed in the upcoming version. You can install reflar uncache for the time being. Clear cache.

Please check the forums as suggested in the issue template, because it's been widely discussed over there.

**Comment by popatop15** [comment]
Will do. My bad I did see it discussed on the forums, but all I could find was vague explanations, and I couldn't find any official issue on github.

**Comment by luceos** [comment]
Flushing your cache is by running `php flarum cache:clear` and `rm -f assets/*.js*` then hard refresh your browser. reflar/uncache takes care of most of this.
