### ISSUE TITLE
Missed forum notifications

### ISSUE THREAD

**Issue by PeopleInside** [flarum/core#1646]
**Current Behavior**
A clear and concise description of the behavior.

As user i want can choose if receive notification for all replies in a topic or just when i am mentioned.
Actually i see in Flarum the option i want: to be notified of all replies on the topic where i am but this seems is not working as expected. If the reply has not the mention i never receive notification.

**Steps to Reproduce**
1. Partecipate in a topic.
2. Click on the Following button
3. Following option is selected ( Be notified of all replies )
4. See error: no email and notification arrive if you are not mentioned.

Please see this: https://discuss.flarum.org/d/17605-be-notified-when-an-update-is-avaiable/4
Also here: https://discuss.flarum.org/d/17608-issues-with-composer-on-centos/11

My experience is that i miss replies because are not notified.

**Expected Behavior**
1. I should decide if by default following for all replies or just when mentioned. This maybe in the profile preference
2. If i see i am following all replies i should be notified on all replies not only when mentioned as happen now

**Screenshots**
https://discuss.flarum.org/d/17605-be-notified-when-an-update-is-avaiable/4

**Environment**
- Flarum version: Flarum Community it's your version and your forum. The bug is in the Flarum support community

- Website URL: https://discuss.flarum.org/

Output of "php flarum info", run this in terminal in your Flarum directory.

I cannot do as server is yours :D

**Possible Solution**

**Additional Context**
In a support community you should never miss replies. In my experience with the Flarum forum i found many replies to my topics that i miss to read because of no notifications.

**Comment by PeopleInside** [comment]
I understood now all replies means when someone click on reply on your message.
Should be another option to decide to be notified of all message posted in a topic. This will be not inserted in the core? There is an extension who will do that?

**Comment by tobscure** [comment]
Actually, here "all replies" refers to all new posts in the discussion, even if they're not in direct reply to yours. Note that you will only receive **one** notification for the first new post that you haven't seen, and you won't receive any further notifications until you are once again up-to-date and have read all the posts in the discussion.

If you're not receiving this initial notification, though, that's a bug. I've followed a few discussions on discuss.flarum.org to see if I can reproduce the issue.

**Comment by tobscure** [comment]
Confirmed and fixed. Thanks for the report @PeopleInside.

**Comment by PeopleInside** [comment]
@tobscure i made some errors maybe but i am happy to see i can help little bit. Happy to be right this time, thank you!

**Comment by PeopleInside** [comment]
Hi, this is not fully fixed.

- I visited [this topic on Flarum community](https://discuss.flarum.org/d/17708-is-there-a-rich-text-editor-that-supports-videos-and-pictures)
- Without posting i subscrive to the topic (Following)
- I see [someone has posted a reply (post) ](https://discuss.flarum.org/d/17708-is-there-a-rich-text-editor-that-supports-videos-and-pictures/4)and i never been notified by email and by notification
