### ISSUE TITLE
[Beta 8] Links missing attributes like target, rel

### ISSUE THREAD

**Issue by jordanjay29** [flarum/core#1650]
This appears to be a regression bug (#247 or surprise implementation of #626 ;) ) from Beta 7.x. 

Demonstrated at discuss.flarum.org ([for example](https://discuss.flarum.org/d/17648-in-the-beta-8-links-in-post-will-open-differently/5)):

```
<a href="https://github.com/flarum/core/blob/c34fcecf0380d130d1aeb0a5dc6155f07f885d87/src/Formatter/Formatter.php#L140">https://github.com/flarum/core/blob/c34fcecf0380d130d1aeb0a5dc6155f07f885d87/src/Formatter/Formatter.php#L140</a>
```

**Comment by clarkwinkelmann** [comment]
Wait... this means it's reverting this commit I made a while ago https://github.com/flarum/core/commit/4c55d278b612ac543f3eaa32e702b71a2c7eeb7e flarum/framework#1432 and therefore will prevent configuring those link attributes via extensions.

Not sure if my commit was the cause of the issue (looks like it was then ?), but I don't think that simply reverting is wise here as we loose the extensibility option :grimacing:

**Comment by clarkwinkelmann** [comment]
@tobscure of course you're right. I'll check out how to re-implement this correctly.
