### ISSUE TITLE
Google Recaptcha V3

### ISSUE THREAD

**Issue by Kio-td** [flarum/core#1654]
## Feature Request

**Describe the solution you'd like**
Google Recaptcha has been a staples for websites for many, many years. Corporations from big to small use it. You're going to find it no matter where you look. With a big bang, Google released Google Recaptcha V.3, a.. sneaky little scoring system ther shows from a score on 0 to 10, how likely a user is to be a bot. This could help flarum admins hide scrapers, prevent credential-stuffing requests with captchas, and send posts to automatic "Needs-to-be-approved" mode.

I believe that GRV3 will be a hit on this forum software, I'm not going to lie. And if you doubt me, consider it like this.
Flarum, is like toast. Sure, it's good, it's.. decent.
Adding generic captcha software, jelly, will make it better, but.. eh, it's not the best.
Adding GRV3, the fresh squeezed expensive brand will make you smile. Users will not be pesked around by random GC popups, nor will be throwing fits, because GOOGLE OUR OVERLORDS sees them as a human being.

Of course, this may set you back some time, but, I think that it'll be worth it.

**Describe alternatives you've considered**
GRV2 is okay.. but I want something more perkier!
Nobody should be paid to show ads for a captcha. No can do, Solve Media.
Looking at ther extensions, there's only one, and it's for version two. I think we need to update, and have this stuff fixed into the code so we can protect our users!

**Comment by luceos** [comment]
This would make perfect sense as an extension. One already exists for the older version, see: https://github.com/sijad/flarum-ext-recaptcha

Next time please follow the directions given in the issue template:

```
IMPORTANT: Feature requests on this GitHub issue tracker are only accepted in case they have been approved by a core developer or contain extensive argumentation and directions for implementation. For all other feature requests, ideas and feedback please post in the Flarum Community: https://discuss.flarum.org/t/feedback.
```

**Comment by luceos** [comment]
> The only thing though, Daniel, I'd see this being a core feature as it'd be
useful for basically everyone.

Flarum core is meant to be slim, there are also core extensions. Core extensions are maintained by the core team. The issue with core extensions is that the more we have, the larger the workload becomes in maintaining them. It's better for our ecosystem to offer the best extensibility possible and offload the workload of maintaining decent, quality extensions to others. 

Don't worry, a recaptcha extension based on version 3 will most likely pop up sooner than later 👍
