### ISSUE TITLE
"Send test email" button

### ISSUE THREAD

**Issue by luceos** [flarum/core#1655]
There is a way to reset your (admin) password without doing a full new reinstall.

Use the forgot password feature. In case the mail driver isn't fully working edit the `settings.mail_driver` value to `log`. Then run the password forgotten action again and check `storage/logs/flarum.log` it will hold the full email contents.

**Comment by franzliedke** [comment]
Another good follow-up to #1169.

**Comment by askvortsov1** [comment]
The above 2 PRs should address both the test mail functionality and the console password reset functionality as requested in the discussion above.
