### ISSUE TITLE
continuously redirect to nojs version and show error

### ISSUE THREAD

**Issue by lubobill1990** [flarum/core#1657]
## Bug Report

**Current Behavior**
Once the browser show nojs version, can't recover

**Steps to Reproduce**

I'm not sure how to reproduce, but once nojs version is shown, whatever I do, I can't recover from it.

**Expected Behavior**

When forum js detector makes a mistake to show nojs version page, I can somehow recover to standard version.

**Screenshots**
![image](https://user-images.githubusercontent.com/641540/49072678-b3658f00-f26b-11e8-887b-272e4e1988ee.png)

**Environment**
- Flarum version: beta-0.1.0-7.2
- Website URL: http://flarum.dev.zhishiq.com:8000/
- Webserver: [e.g. apache, nginx] nginx
- Hosting environment: [e.g. shared, vps]
- PHP version: 7.2.11
- Browser: [e.g. chrome 67, safari 11] chrome

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

**Possible Solution**

Add a button to recover from nojs version.

**Additional Context**

**Comment by luceos** [comment]
Clear flarum cache:

```bash
php flarum cache:clear
```

Then clear your browser cache.

Alternatively install reflar/uncache OR wait for beta 8.

**Comment by tobscure** [comment]
Closing because this is likely fixed in beta 8.

**Comment by lubobill1990** [comment]
Thanks
