### ISSUE TITLE
[Emoji] Twemojify emoji in discussion titles

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#1660]

**Comment by tankerkiller125** [comment]
I think this might still be relevant. I just tested this in nightly and we are still unable to parse emoji in titles.

**Comment by askvortsov1** [comment]
Isnt this just running the titles through text formatter?

**Comment by datitisev** [comment]
Probably not TextFormatter, and just twemoji... I don't think we want any other formatting in the title.

**Comment by tankerkiller125** [comment]
We could turn on the TextFormatter Emoji handler only for titles pretty easily I think. I'd have to review the actual code first before being certain.
