### ISSUE TITLE
[Tags] "Invalid date" displayed randomly on posts on tags page

### ISSUE THREAD

**Issue by poVoq** [flarum/core#1662]
## Bug Report

**Current Behavior**
Just installed a fresh version of Beta8 on my shared host and when posting new topics they don't show up in the All discussions page. Only if I go to the exact sub-tag they are visible.
If I switch to the tags view the posts get added to the bottom row of the tag, but randomly a "INVALID DATE" is shown instead of the actual time it was posted.

This is on a Netcup.de shared host and Flarum Beta7 is running great on it.

The page in question is running php 7.2.12.

**Comment by franzliedke** [comment]
Please post the output of `php flarum info`, as we ask for in the bug report template.

**Comment by poVoq** [comment]
Seems to work with php 7.1.24

**Comment by tobscure** [comment]
> Just installed a fresh version of Beta8 on my shared host and when posting new topics they don't show up in the All discussions page. Only if I go to the exact sub-tag they are visible.

Is the "Hide from All Discussions" checkbox ticked for your tags?

The INVALID DATE issue is occurring on discuss.flarum.org too for some tags, so we can verify that one.

**Comment by poVoq** [comment]
No, but it happens both on primary tags and sub tags of primary tags.

I also noticed that the default "Gerneral" group was acting strangely (reverting color and location randomly but temporarily) but it seems that after completely removing and recreating it that issue was removed.

**Comment by poVoq** [comment]
No special permissions. This is literally a fresh installation with no special setup. I just installed and created some primary tags.

**Comment by tobscure** [comment]
Mystery. Can anyone else test/confirm this?

**Comment by poVoq** [comment]
The strange thing is that Flarum Beta7 is right now running on the same web-pack with the exact same setup just fine, but Beta8 is un-usable because the posts dont't show up in the all discussions tab most of the time.

Maybe this is a database issue? This is on MySQL 5.7.24 on a separate server (not localhost).

**Comment by PeopleInside** [comment]
I have this issue too in Beta 8 https://discuss.flarum.org/d/17842-i-get-this-invalid-date-error-both-in-my-localhost-and-in-discuss-flarum-org/2

https://community.peopleinside.it/tags
![00](https://user-images.githubusercontent.com/5006150/49338285-9c35f100-f61f-11e8-9546-91b01a23d040.png)

**Comment by poVoq** [comment]
The difference seems to be that while this also shows up on discuss.flarum.org (both in Firefox and Chome) the posts in the "all discussions" view still seem to be unaffected? On my forum the all discussions view stays empty most of the time because of this bug.

**Comment by luceos** [comment]
Look at the discussions. These seem to be spam items, **maybe** they are visible while being held for moderation (approval extension?) or they have been deleted and as such don't have the attribute date?

**Comment by PeopleInside** [comment]
@luceos good idea but not sure.
If i click on the items with near the invalid date the post is opened than i press back button in the browser and invalid date disappears.

![00 - copia](https://user-images.githubusercontent.com/5006150/49436107-8871c280-f7b8-11e8-9d7b-e2d92ed49ae4.png)
![01 - copia](https://user-images.githubusercontent.com/5006150/49436108-890a5900-f7b8-11e8-9f78-5cad131d8697.png)

**Comment by luceos** [comment]
@PeopleInside scores!

Just confirmed the same thing, pretty easy to reproduce, try hard refreshing your /tags page. Seems like it's not using/requesting enough attributes?

**Comment by PeopleInside** [comment]
If i refresh the page in the screenshot i continue to see invalid date also if i refresh Firefox 10 times.
It change for me only if i click on the post near the invalid time than press back button to return to the tag screen. Just the post clicked has now the correct time.

I do not understand on programming side where the issue is but this is what i can see. :P Tested with Firefox and Chrome, latest version.

**Comment by poVoq** [comment]
Yeah, that is one of the ways I meant with more or less randomly. Similarly you can refresh the "all discussions" page and sometimes the posts will show up. If they show up you can click on "tags" and there is no invalid date, but after a page refresh it comes back.

**Comment by PeopleInside** [comment]
Issue resolved, thanks to @tobscure for fixong this and @poVoq for the report :) 👍
