### ISSUE TITLE
Missed forum notification 2

### ISSUE THREAD

**Issue by PeopleInside** [flarum/core#1667]
https://github.com/flarum/core/issues/1646
Hi, I tested on my Flarum Beta 8 but also on the Flarum community, seems if you join in a thread for the first time (maybe) and write without mention or quote anyone no notification about your post are sent by email. Seems again notification are missed, the forum doesn't alert about new post where you result subscribed to all comment because you posted something before.

Flarum core 0.1.0-beta.8
PHP version: 7.1.24
Loaded extensions: Core, date, libxml, pcre, dom, fileinfo, filter, hash, json, SPL, bz2, posix, Reflection, session, SimpleXML, standard, xml, xmlreader, xmlwriter, bcmath, openssl, calendar, ctype, curl, dba, mbstring, ftp, gd, gettext, gmp, iconv, imap, intl, ldap, exif, mcrypt, zlib, pcntl, PDO, pdo_sqlite, shmop, soap, sockets, sqlite3, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlrpc, xsl, zip, Phar, mysqlnd, mysqli, pdo_mysql, ionCube Loader, Zend OPcache
+----------------------+-----------------+--------+
| Flarum Extensions    |                 |        |
+----------------------+-----------------+--------+
| ID                   | Version         | Commit |
+----------------------+-----------------+--------+
| flarum-approval      | v0.1.0-beta.8   |        |
| flarum-bbcode        | v0.1.0-beta.8   |        |
| flarum-emoji         | v0.1.0-beta.8   |        |
| flarum-flags         | v0.1.0-beta.8   |        |
| flarum-likes         | v0.1.0-beta.8   |        |
| flarum-lock          | v0.1.0-beta.8   |        |
| flarum-markdown      | v0.1.0-beta.8   |        |
| flarum-mentions      | v0.1.0-beta.8   |        |
| flarum-sticky        | v0.1.0-beta.8   |        |
| flarum-subscriptions | v0.1.0-beta.8   |        |
| flarum-suspend       | v0.1.0-beta.8   |        |
| flarum-tags          | v0.1.0-beta.8.1 |        |
| flarum-auth-github   | v0.1.0-beta.8   |        |
| flarum-auth-facebook | v0.1.0-beta.8   |        |
| flarum-auth-twitter  | v0.1.0-beta.8   |        |
| flarum-lang-english  | v0.1.0-beta.8   |        |
| flagrow-upload       | 0.7.0           |        |
| flarum-statistics    | v0.1.0-beta.8   |        |
| flarum-pusher        | v0.1.0-beta.8   |        |
| nearata-lang-italian | v0.1.0-beta.8.1 |        |
| fof-user-bio         | 0.1.1           |        |
+----------------------+-----------------+--------+

Debug mode off

**Comment by PeopleInside** [comment]
Notifications seems work when:
- someone is mentioned maybe also quoted
- you subscrive to a discussion ( but not sure notification works well here)

Is not working when exist Topic A with a post of User A that are subscribed to receive all post notifications and User B made a post without mention User A like a generic reply that say simply Hello.

Notification is working if the reply is pressed from the post (mention) not work if used the "reply on the footer" that is not generating a mention.

I hope this info can help.

**Comment by tobscure** [comment]
I cannot reproduce this. The steps I took were:

- Log into User A, go to settings and tick "Email" for "Someone posts in a discussion I'm following"
- Create a discussion, then follow it
- Log into User B, post in that discussion "hello" (no mentions or anything)

User A received an email notification for User B's new post.

**Comment by PeopleInside** [comment]
Hi @tobscure , [i am testing more](https://discuss.flarum.org/d/17808-test).
The issue seems to be when simply reply in the footer is used but now i am unable to reproduce on the Test Posting... i tested on my Beta 8 and i am sure some notification are missed just i need understand when... I will update here as soon i found the right sequence.

Please do not close this issue you can ask me to close if you want close for now. If i will find again the issue so i can reopen it.

**Comment by PeopleInside** [comment]
Let's see if this has sense:

Step 1. [Created a test topic with user account peopleinside](https://discuss.flarum.org/d/17808-test)

Step 2. [Replied without any quote](https://discuss.flarum.org/d/17808-test/2) with user account MaBo no mentions, no quote. **peopleinside received the email** so seems no issue

Step 3. [peopleinsde made a reply](https://discuss.flarum.org/d/17808-test/3) with reply in the footer without use quote or mention, **MaBo never received a notification mail** or a notification in the forum.

Step 4. [Mabo posted a reply](https://discuss.flarum.org/d/17808-test/4) , peopleinside get notified

Step 5. [peopleinsde posted a reply](https://discuss.flarum.org/d/17808-test/5), Mabo never received a notification email

Let's check without press Subscribe if MaBo was subscribed.
MaBo is not subscribed... that's why... the setting that doesn't subscribe by default confused me... i hate this settings disabled by default no sense for me... let's check if in my Flarum install i have the same issue, let's see my user test..

Nothing in my Flarum Beta 8 where i found the issue each user has the option to auto subscribe where made a post. I will close this issue for now. ( I know if you believe they should stay open you can reopen).

I have to made other test on the flarum community test section by enable subscription from the test profile MaBo and try again the scenario in a new topic.

Unable to reproduce at the moment. :S

**Comment by luceos** [comment]
@PeopleInside just wanted to tell you that you're doing a great job. You take the time to test, to reproduce and to write it down. Thank you! I'm very glad you joined the community.
