### ISSUE TITLE
Splitting a discussion not permitted even though priviledge has been granted

### ISSUE THREAD

**Issue by pflstr** [flarum/core#1672]
## Bug Report

**Current Behavior**
Trying to split a discussion results in a red `You do not have permission to do that` warning.

**Steps to Reproduce**
1. Login with an account that is priviledges to split discussions.
2. Perform the usual steps:
2.a. Select the context menu of the first post to be split.
2.b. Select `Split from here`.
2.c. Select `Split to here` at the last post meant to be split.
2.d. Choose an appropriated title
2.e. Click `Split`.
3. See the red `You do not have permission to do that.` warning.

**Environment**
- Flarum version: Beta 8
- Website URL: https://discuss.flarum.org
- Browser: Firefox 62.0.3 on MacOS

**Comment by tobscure** [comment]
Split is a [third-party extension](https://github.com/flagrow/split). Please report issues over there :)

**Comment by matteocontrini** [comment]
For the record, there's already an issue for that there 😊 

https://github.com/flagrow/split/issues/14
