### ISSUE TITLE
Any idea about this video demostration cache issue?

### ISSUE THREAD

**Issue by PeopleInside** [flarum/core#1673]
Please see the following post where is part of a discussion that take more users... i made a video of the issue, tested on Flarum community but unable to reproduce on Flarum community.

https://discuss.flarum.org/d/17793-a-force-refresh-fixes-everything-temporarily/28

Any idea if this is a bug or an issue of the current Beta 8?
I see i am not the only one to have this situation.

**Comment by tobscure** [comment]
I'm going to close this and we can continue the investigation in the discussion you linked, because I suspect it's an issue with your web server configuration and not with Flarum.
