### ISSUE TITLE
Add new "Show" event for Users (and discussions)

### ISSUE THREAD

**Issue by MichaelBelgium** [flarum/core#1676]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Yes, technically. I've got issues in my profile views extension where it struggles to detect when a profile has been viewed. Also issues when a Guest visits a profile.

### For User:
As alternative I'm listening to the event  `WillSerializeData` and checking if the controller is `ShowUserController` but this only gets called

* on directly navigating to the user profile url 
    * Example: opening new tab and navigating to https://discuss.flarum.org/u/MichaelBelgium
* pressing F5 on a user profile 
    * Example: go to a discussion and click on someone's name to go to their profile - **it doesnt get called**, the user profile "is not being displayed" => only refreshing the page does (same principle like above then)

**THE SECOND EXAMPLE CREATES A BUG ABOUT PERMISSIONS!!!** (I can make a different issue for this if you like) => https://discuss.flarum.org/d/17835-the-requested-resource-was-not-found-on-refresh

> The thing is that you still can watch profiles when the permission "view user list" is set to members only, if a guest goes to a discussion and click on one's username u can see the profile.

> Expected a "Permission denied" error and not a "The requested resource was not found" error

### For a discussion
Using the same method as for a user, listening to `WillSerializeData` and checking if the controller is `ShowDiscussionController`. Although this does work every time it would be a nice addition next to it.

**Describe the solution you'd like**
- Improve or make a new event to fire when a user profile gets displayed

**Describe alternatives you've considered**
See above

**Comment by tobscure** [comment]
This is because if the user data has already been loaded (eg. in association with a discussion or post), there's no need to hit the API again when you go to a user page.

There's no good reason to add an extra API call in core (because it wouldn't do anything), so your best bet is to make your own call when the `UserPage` component is initialised. You could just hit the `/api/users/{id}` endpoint again, or you could expose your own endpoint like `POST /api/users/{id}/views`.

The permission error is valid though, if you could make a new issue that would be much appreciated!

**Comment by MichaelBelgium** [comment]
Thanks for the idea @tobscure , I just add a relationship to the front end and do this instead:

```JAVASCRIPT
extend(UserPage.prototype, 'view', function(view) {
    if(this.user !== null && typeof app.session.user !== 'undefined' && this.user.id() !== app.session.user.id())
    {
        this.user.save({
            relationships: {
                profileViews: [
                    app.session.user
                ]
            }
        });
    }
    
    return view;
});
```

So far I think this is more accurate, at least I assume so. Tried to extend the "init" function but that was like a bad idea haha. I think extending "view" is the best choice here

Thank you!

**Comment by MichaelBelgium** [comment]
Well, the user prop was always null. And isnt it also the case extending overwrites the whole method or some kind?

The IP thing exists to prevent spam, if u keep pressing F5 it would add a view over and over otherwise. I still didnt think about another way.

**Comment by tobscure** [comment]
Ah, gotcha. Extend the `show` method instead. Using the `extend` utility doesn't overwrite the method, it just adds your code onto the end.

**Comment by MichaelBelgium** [comment]
Alright, yes the `show` method is best choice here. Now to add the api route, I assume only a backend route is needed here?

```
(new Routes('api'))
        ->post('/profileview/{id}', 'profileview.add', CreateUserProfileViewController::class),
```

Then just doing an ajax request to that route and tada

**Comment by tobscure** [comment]
```js
extend(UserPage.prototype, 'show', function() {
    if(typeof app.session.user !== 'undefined' && app.session.user.id() !== this.user.id())
    {
        app.request(app.forum.attribute('apiUrl') + '/profileview/' + this.user.id()).then(function(data) {
            console.log(data);
        });
    }
});
```
