### ISSUE TITLE
Meta description, SEO

### ISSUE THREAD

**Issue by PeopleInside** [flarum/core#1677]
## Bug Report

**Current Behavior**

Seems there are issue with Meta Tag. On Firefox if i visit the website and see the page information the description is empty, seems also there are some issues with language meta tag and maybe need SEO improvements.

Please see:
- [SEO and Open Graph Tags Issues (Beta 8)](https://discuss.flarum.org/d/17870-seo-and-open-graph-tags-issues-beta-8)
- [Meta description is empty](https://discuss.flarum.org/d/17817-meta-description-is-empty)

**Environment**
- Flarum version: Beta 8

**Comment by PeopleInside** [comment]
Hi @tobscure , thanks for the fix, did you consider also [this message](https://discuss.flarum.org/d/17817-meta-description-is-empty/8)?

**Comment by matteocontrini** [comment]
A bit better, but...

![image](https://user-images.githubusercontent.com/2164763/49443238-3470d900-f7cc-11e8-9cf9-cf1e5c442afc.png)

And why are the language codes missing in this case?
