### ISSUE TITLE
[Markdown] Toolbar missing image button

### ISSUE THREAD

**Issue by jordanjay29** [flarum/core#1679]
On Beta 8's new toolbar for Markdown, there is no image button to insert `![alt text](https://www.link.to/image.jpg)` code.

**Comment by franzliedke** [comment]
It looks like this is not yet supported by [GitHub's library](https://github.com/github/markdown-toolbar-element).

**Comment by tobscure** [comment]
Ultimately we're probably going to have to fork GitHub's library into our codebase to provide a text editor API that other extensions can use, which will also allow us to add additional buttons like an image one.

**Comment by Ralkage** [comment]
@tobscure would that include the ability to add custom BBCode toolbar buttons and functionality? 😉
