### ISSUE TITLE
Password strength meter

### ISSUE THREAD

**Issue by tobscure** [flarum/core#168]
http://discuss.flarum.org/d/238/password-strength-checker/1

**Comment by franzliedke** [comment]
A very useful article on designing forms that guide people in creating strong passwords:
http://www.nngroup.com/articles/passwords-memory/?utm_source=Alertbox&utm_campaign=2941b017d6-Mobile_Fields_Memorable_Passwords_06_15_2015

**Comment by override-chaos** [comment]
This is a nice JS lib for a password strength meter.

https://github.com/dropbox/zxcvbn

**Comment by jsonnull** [comment]
http://blog.codinghorror.com/your-password-is-too-damn-short/

This is a must-read. There's a variety of ways to gauge password strength. You can also glimpse the effectiveness of quite a few solutions in the image comparison he provides (though this may be a bit dated now).

**Comment by detis** [comment]
@override-chaos +1

**Comment by tobscure** [comment]
Merged into #193
