### ISSUE TITLE
All discussions stays empty until a refresh of the page, when tags view is the default

### ISSUE THREAD

**Issue by poVoq** [flarum/core#1684]
## Bug Report
First reported here and likely related: https://github.com/flarum/core/issues/1662#issuecomment-444290685
**Current Behavior**
The "all discussions" view says "It looks like there are no discussions here." if you select "tags" view as the default in the admin menu.

**Steps to Reproduce**
1. Go to 'https://community.freegamedev.net (a fresh Flarum beta8 installation on a shared host updated to Beta8.1 a few minutes ago)'
2. Click on 'All discussions'
3. See 'It looks like there are no discussions here.' despite there being several test posts
4. Reload page in browser to see posts.
5. When switching back to "all discussions" view in the admin menu this doesn't seem to happen.

**Environment**
- Flarum version: beta8.1
- Website URL: https://community.freegamedev.net
- Webserver: Apache behind nginx reverseproxy
- Hosting environment: shared
- PHP version: 7.2.1.0
- Browser: Firefox

```
Flarum core 0.1.0-beta.8.1
PHP version: 7.2.10
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, session, json, mbstring, standard, Phar, posix, Reflection, imap, shmop, SimpleXML, soap, sockets, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, mysqlnd, imagick, curl, gd, mysqli, PDO, pdo_mysql, xsl, sqlite3, intl, ionCube Loader
+----------------------+-----------------+--------+
| Flarum Extensions    |                 |        |
+----------------------+-----------------+--------+
| ID                   | Version         | Commit |
+----------------------+-----------------+--------+
| flarum-bbcode        | v0.1.0-beta.8   |        |
| flarum-emoji         | v0.1.0-beta.8   |        |
| flarum-lang-english  | v0.1.0-beta.8   |        |
| flarum-flags         | v0.1.0-beta.8.1 |        |
| flarum-likes         | v0.1.0-beta.8.1 |        |
| flarum-lock          | v0.1.0-beta.8   |        |
| flarum-markdown      | v0.1.0-beta.8   |        |
| flarum-mentions      | v0.1.0-beta.8.1 |        |
| flarum-statistics    | v0.1.0-beta.8   |        |
| flarum-sticky        | v0.1.0-beta.8   |        |
| flarum-subscriptions | v0.1.0-beta.8   |        |
| flarum-suspend       | v0.1.0-beta.8   |        |
| flarum-tags          | v0.1.0-beta.8.2 |        |
| flarum-approval      | v0.1.0-beta.8   |        |
| flagrow-split        | 0.3.1           |        |
+----------------------+-----------------+--------+
Base URL: https://community.freegamedev.net
Installation path: /fgd_flarum/flarum
Debug mode: off

```

**Comment by datitisev** [comment]
I can't reproduce. Using Chrome Version 71.0.3578.80 (Official Build) beta (64-bit).

![screen recording 2018-12-06 at 3 39 18 pm](https://user-images.githubusercontent.com/6401250/49610679-48077580-f96d-11e8-8b4d-599982f2d06f.gif)

**Comment by luceos** [comment]
Same, cannot confirm. Please make sure you fully clear your browser cache.

If this issue can be reproduced, please re-open.
