### ISSUE TITLE
Editor: some link can have issue

### ISSUE THREAD

**Issue by PeopleInside** [flarum/core#1690]
Beta 8.1

![0000](https://user-images.githubusercontent.com/5006150/49686439-ea059a00-faf4-11e8-9ca1-ec174ffe8f37.png)

the screen is from the Flarum community, seems link to a specific comment as have special character in the middle are not converted to full correct link.

For solve user have to edit the posted message once sent and select the link, press the hyperlink button than insert link again. Can be this improved to convert link automatically also with specials character in links?

**Comment by franzliedke** [comment]
I believe this is an issue with an extension. Please create an issue [on its repository](https://github.com/sijad/flarum-ext-github-autolink) or post in the [relevant discussion on discuss](https://discuss.flarum.org/d/2634-github-autolink).

**Comment by PeopleInside** [comment]
Confirmed, thanks @franzliedke i will do.
I don't use this extension so i cannot see the issue that is present only on Discuss Flarum.

I reported on the extension page 👍

**Comment by tobscure** [comment]
ref https://github.com/sijad/flarum-ext-github-autolink/issues/5
