### ISSUE TITLE
RegistrationToken returning null from $token->id, should be $token->token

### ISSUE THREAD

**Issue by ripperdoc** [flarum/core#1691]
## Bug Report

**Current Behavior**
When I use a Login Provider, e.g. Github (or custom), it should return a RegistrationToken to the SignUpModal, to complete the registration. However, currently this token is incorrectly returned from Flarum\Forum\Auth\ResponseFactory, making the SignUpModal display a normal sign up (including a password field).

**Steps to Reproduce**
1. Install e.g. Github Sign in extension
2. Click on Log In with a user that is not know since before
3. When the authentication completes, you are redirected to SignUpModal. However the props.token is null, so the correct state is not shown for this form. The user can sign-up but has to put in a dummy password. The missing token generates an error on submission of the SignUp form.

**Expected Behavior**
A token should be returned to the SignUpModal so that it hides the password field and can submit it along with the other data, to complete the registration flow with a Login Provider.

**Screenshots**

**Environment**
- Flarum version: v0.1.0-beta.8.1
- Website URL: Not live
- Webserver: Nginx
- Hosting environment: Docker
- PHP version: 7.1
- Browser: Chrome

```
(Not able to run "php flarum info" easily due to my Docker setup, but the issue should be observable directly in the code)
```

**Possible Solution**
In the Flarum\Forum\Auth\ResponseFactory, line 59, change `'token' => $token->id,` to `'token' => $token->token,`. There is no `id` attribute on RegistrationToken.

**Comment by franzliedke** [comment]
Thanks for the report! Fixed. :)
