### ISSUE TITLE
store.find with an array of ids misbehaves

### ISSUE THREAD

**Issue by luceos** [flarum/core#1694]
When using the store `find` method with an array of ids the returned response holds more than the id's requested.

Reproduce:

- open developer console on discuss
- enter: `app.store.find('discussions', [1,2]).then(response => console.log(response));`
- expected discussions with id 1 and 2 to pop up
- got 20 results back

![screen shot 2018-12-11 at 13 05 17](https://user-images.githubusercontent.com/504687/49799521-76a69700-fd45-11e8-86de-f676c1a007b0.png)

The returned response becomes more random when using `[1, 2000]` for instance.

**Comment by franzliedke** [comment]
Is this feature being used anywhere in core?

**Comment by franzliedke** [comment]
There is no `id` filter implemented in [the `ListDiscussionsController`](https://github.com/flarum/core/blob/0ceb8d64df33c1131fcb8e5fcd5815fea352f7d8/src/Api/Controller/ListDiscussionsController.php), so this is simply not implemented. Feel free to open a feature request. :wink:
