### ISSUE TITLE
Post events increasing post count

### ISSUE THREAD

**Issue by jordanjay29** [flarum/core#1695]
## Bug Report

**Current Behavior**
Post count increases by one for Post Events, counted after post is made following the post event. See [this thread on discuss](https://discuss.flarum.org/d/17979-post-counts-now-include-actions-like-closing-discussion/) for more information and demonstration links.

**Steps to Reproduce**
1. Check profile for post count
2. Perform an action on a discussion that generates a Post Event
3. Check profile, post count should reflect previous count
4. Make a new reply
5. Check profile, post count should reflect previous count + 2

**Expected Behavior**
In step 5, post count should only reflect previous count + 1, post events should not count

**Screenshots**

**Environment**
- Flarum version: Beta 8.1

**Comment by datitisev** [comment]
The issue seems to be that `comments_count` includes all types of posts, not only comments.
Thus actions like renaming a discussion are included in the count.

https://github.com/flarum/core/blob/master/src/User/User.php#L756

**Comment by MichaelBelgium** [comment]
Honestly why is there `comment_count` and `discussion_count` while you can get the count from the relationships 🤔

**Comment by franzliedke** [comment]
Performance and DB load, right. Sometimes a little bit of extra work when inserting pays off greatly when reading.

You just have to be extra careful to sync correctly when inserting, as this issue shows. :wink:

**Comment by luceos** [comment]
This is probably one of the hardest things to implement correctly. Because we'll never be sure which Post type (CommentPost - default, EventPost - relabelling & locking for instance, PollPost or anything else) is valid to be included in this count without actually going over each entry in the relationship and checking the Type class implementation.

**Comment by tobscure** [comment]
This should be an easy fix. Just change

```php
$this->comment_count = $this->posts()->count();
```

to

```php
$this->comment_count = $this->posts()->where('type', 'comment')->count();
```

**Comment by franzliedke** [comment]
What about `is_private`?

**Comment by tobscure** [comment]
True, didn't think about that.

**Comment by luceos** [comment]
What if we had a UserMeta collection/class that would be extensible. In addition the default values, like `comment_count` and `discussion_count` are retrieved while dispatching an event. That logic could re-use the same logic used with the Policies perhaps..

I'm not too fond of more complexity, but it might be interesting to be able to create such statistical meta information on models.
