### ISSUE TITLE
Topic list does not close on iPad

### ISSUE THREAD

**Issue by pixi** [flarum/core#170]
Hi,
the topic list visible when clicking on a topic goes not close/go away automatically when entering a topic detail. The left arrow on top is "misindicating" to close the whole (it goes back tot he list).

![image](https://cloud.githubusercontent.com/assets/7418913/8567975/1af6ee34-256a-11e5-9be9-31c5378d97e0.jpeg)
![image-1](https://cloud.githubusercontent.com/assets/7418913/8567976/1afa2ee6-256a-11e5-801c-e6aae7767f82.jpeg)

**Comment by tobscure** [comment]
The discussion list pane shouldn't display at all on iPad. It doesn't on mine. Unless there's something specific you're doing to bring it up?

**Comment by pixi** [comment]
Nope, I was just clicking on the topic title.



Am 09.07.2015 um 08:59 schrieb Toby Zerner:

**Comment by tobscure** [comment]
I suspect it's due to the old version of iOS you're using then. We don't really have the developer resources to be supporting old browsers right now, sorry.
