### ISSUE TITLE
Mentions - Partially hidden on iOS

### ISSUE THREAD

**Issue by zerosonesfun** [flarum/core#1705]
Beta 8.1 on iPhone, Chrome browser, mentions partially hidden. 

<img src="https://i.ibb.co/mJ7cPV6/0406810-D-15-E9-4-D4-D-B361-3-A0-B5-A3-A2621.jpg" alt="0406810-D-15-E9-4-D4-D-B361-3-A0-B5-A3-A2621" border="0">

**Comment by franzliedke** [comment]
Can anybody explain what part of the screenshot is wrong? And is this still a problem?

**Comment by tankerkiller125** [comment]
Looks like an issue where the beginning on the "drop-down" is missing. This remains an issue on Android as well.

**Comment by franzliedke** [comment]
Oh, right. Didn't realize it was a full-width screenshot. :laughing:

**Comment by askvortsov1** [comment]
Fixed in https://github.com/flarum/mentions/pull/46
