### ISSUE TITLE
Sizing issue with reply hover card

### ISSUE THREAD

**Issue by gurjyot** [flarum/core#1707]
## Bug Report

**Current Behavior**
The reply hover card is not of correct length. I think it shoud be much wider on desktop and not like a vertical card. For the reference, you can also see the issue in the image. To reproduce it, I have provided the steps below.
![flarumissue](https://user-images.githubusercontent.com/6462850/50058641-327e2100-01a1-11e9-8b38-4e187940983e.png)

The hover window is not of the correct size. You can check the [thread here](https://discuss.flarum.org/d/17745-flarum-0-1-0-beta-8-released/137). Clarkwinkelmann replied to Ralkage post in another dicussion and when I hover my mouse over the name then this is how the hover card appears.

**Steps to Reproduce**
1. Go to '[this discussion](https://discuss.flarum.org/d/17745-flarum-0-1-0-beta-8-released/137)'
2. Hover on 'clarkwinkelmann name under Ralkage's reply'
3. You'll see the issue there.

**Environment**
- Website URL: https://discuss.flarum.org
- Browser: Chrome version 71, edge (latest version)
- Operating System: Windows 10 (latest version)

**Comment by franzliedke** [comment]
> I think the iamge says it all.

To be honest, no. Also, images can disappear. I *assume* you want the card to be wider. What is the "correct" size?

We are thankful for every bug report, but please, never assume anything in bug reports. Provide as much details as possible - optimally in text form - so that it is easy to jump into the topic and understand context even months later.

**Comment by gurjyot** [comment]
@franzliedke Yes, you are right. Actually, I was in the impression that the bug is small style bug so it won't be long before it's fixed. But I also agree that we should provide as much detail as possible. So I have made some changed in the original post. :)

**Comment by franzliedke** [comment]
@gurjyot Thanks for your understanding. :wink: 

I agree this is a bug and would like to see this fixed, too. I, personally, have some bugs in actual functionality to take care of, so why this is easy to fix, it's not that important in comparison. Good chance for sending a PR, if anyone is interested. :smile:

**Comment by SychO9** [comment]
Can this be re-opened please ?

**For reference:**
There was an attempted fix here: https://github.com/flarum/mentions/pull/38
But that introduced a slight bug which was fixed here: https://github.com/flarum/core/commit/79f90126948a19fe88e405a482f7ce00fffc4b0a
But that reintroduced this bug (:face_with_head_bandage:)

**Comment by askvortsov1** [comment]
That's unfortunate, I thought that commit hadn't reintroduced the bug. Oh well...

**Comment by SychO9** [comment]
> That's unfortunate, I thought that commit hadn't reintroduced the bug. Oh well...

Indeed, not as simple as I expected, this one'll require more thought into it :thinking:

**Comment by askvortsov1** [comment]
Hmm, when testing on nightly, I'm not seeing this issue: https://nightly.flarum.site/d/1-testing/5

**Comment by SychO9** [comment]
you're probably looking at the mention of the post, the issue only happens on the reply preview

**Comment by askvortsov1** [comment]
https://i.imgur.com/pUdpTtY.png I might be missing something, but the reply preview looks fine on Discuss?

**Comment by SychO9** [comment]
Discuss uses the `fof/best-answer` extension which is currently misaligning the footer elements (likes on right side and replies on left side) probably by making the left side full width which makes the replies dropdown also full width. Hence why I decided to move out the replies dropdown from the footer, so that it no longer has to be restricted by its width, which allows us to keep the footer elements properly aligned.

**Comment by askvortsov1** [comment]
Ah... 🤦‍♂️ I guess that's my weekly reminder to test this stuff on nightly and not on discuss

**Comment by davwheat** [comment]
Should this be reopened?
