### ISSUE TITLE
Resolving of api routes makes route 404

### ISSUE THREAD

**Issue by luceos** [flarum/core#1708]
## Bug Report

**Current Behavior**

When registering an api route on the root extend.php like this:

```php
    (new Extend\Routes('api'))
        ->post('/auth/flagrow', 'auth.flagrow.callback', Controllers\Auth\FlagrowCallbackController::class),
```

The route is not found. The cause seems to lie in the fact that the routes is bound as singleton in the boot of the provider and being resolved and pushed to the router in the boot. The extenders are however run after the providers are booted, so hooking into them resolving will be too late.

I changed the following in `InstalledSite` and that resolved the issue I had locally:

```php
        $laravel->boot();

        foreach ($this->extenders as $extension) {
            $extension->extend($laravel);
        }
```

to

```php

        foreach ($this->extenders as $extension) {
            $extension->extend($laravel);
        }

        $laravel->boot();
```

**Comment by franzliedke** [comment]
Yep, that fix is correct. (Although we can discuss whether the local extenders should run first, or the ones from enabled extensions. In the latter case - which I prefer - this would have to change slightly.)
