### ISSUE TITLE
Title field is too narrow when adding a topic.

### ISSUE THREAD

**Issue by pixi** [flarum/core#171]
When adding a topic the title field is too narrow (although it widens when typing partly).
See the green selected text!

![addtopic](https://cloud.githubusercontent.com/assets/7418913/8582563/e557e25c-25c7-11e5-8d56-5ee090bb20b1.png)

**Comment by tobscure** [comment]
Which browser?

**Comment by pixi** [comment]
FF 28, OS X 10.6.8 and 10.9.5

Am 09.07.2015 um 08:56 schrieb Toby Zerner:

**Comment by tobscure** [comment]
You should upgrade Firefox. Firefox 28 is over a year old.

Anyway, duplicate of #161
