### ISSUE TITLE
Mail drivers should be a dropdown

### ISSUE THREAD

**Issue by CDK2020** [flarum/core#1712]
## Feature Request

**Is your feature request related to a problem? Please describe.**
If an incorrect driver is used, Flarum will fail to load. Potentially related to #1578 

**Describe the solution you'd like**
Add a dropdown (via item list for extensibility) that has the valid drivers listed on the email setup page.

**Comment by luceos** [comment]
This duplicates https://github.com/flarum/core/issues/1169, discussion should take place there.
