### ISSUE TITLE
GitHub login, pop up is in the wrong size, no scroll bars

### ISSUE THREAD

**Issue by PeopleInside** [flarum/core#1716]
This issue will be simple:

The GitHub plugin show a pop up that is cutted and has no scrolls bars.
Facebook and twitter pop up are correct, github not. Can be this correct?

![00](https://user-images.githubusercontent.com/5006150/50288566-9a18c280-0466-11e9-9608-aaf4fae5d476.png)

**Comment by datitisev** [comment]
I can't reproduce with Chrome Version 72.0.3626.28 (Official Build) beta (64-bit)

![image](https://user-images.githubusercontent.com/6401250/50310367-c84ed000-046f-11e9-902d-b307a7481fb1.png)


However, I **CAN** reproduce with Firefox Developer Edition 64.0b13 and 65.0b5 (64-bit)

![image](https://user-images.githubusercontent.com/6401250/50310421-eb797f80-046f-11e9-924b-09650c7b3508.png)

**Comment by PeopleInside** [comment]
True, i do not use Chrome much. On Chrome the issue is not present but is present on the stable version of Firefox. You also tested on developers version :D great.

**Comment by Ralkage** [comment]
I can also reproduce this on both FireFox Dev Edition and the standard edition as well (64bit).

IE11 as well, if not worse 😂 (Who uses IE anymore anyways? ;))

**Comment by PeopleInside** [comment]
Thanks, how can i apply and try this patch?

**Comment by franzliedke** [comment]
@PeopleInside You could use [our demo](https://nightly.flarum.site), once it has updated (although that will require enabling and configuring Facebook login with an app ID and secret.

Other than that, wait for discuss to be updated or try a local install. :smile:

**Comment by PeopleInside** [comment]
Umh i changed the scroll bar from no to yes on my install but still see the issue when i press to login with Github https://community.peopleinside.it/ why? I cleared flarum cache.

**Comment by datitisev** [comment]
@PeopleInside You'd need to build the JS dist file as well so the JavaScript is recompiled.

**Comment by PeopleInside** [comment]
Done thanks. Works
