### ISSUE TITLE
SecurityError on FF v39, Mac OSX Yosemite

### ISSUE THREAD

**Issue by phanimahesh** [flarum/core#172]
The forum does not load at all, when testing discuss.flarum.org. The console shows:

    SecurityError: The operation is insecure.                forum-3lERXKevTPzqGBoN.js:12:0

I've tried taking browserstack screenshots and it's working on FF v37, that's the latest they got for free screenshot service.

**Comment by tobscure** [comment]
Weird, can't reproduce on my end (FFv39, Mac OS X El Capitan). I don't think it's likely for it to be a Yosemite issue. Do you have any special security settings etc. on your Firefox installation?

**Comment by phanimahesh** [comment]
Mine is a slightly unusual setup. I have a bunch of extensions active and they may be interfering with something. I'll try to debug by enabling extensions selectively. However it seems unlikely that these extensions trigger a `SecurityError`. Will also check my FF prefs. This is going to take a some time.

**Comment by poush** [comment]
I am on FF V38 OSX 10.10.4 -- Nothing Such SecurityError

**Comment by poush** [comment]
Checked with FF V39 also. No SecurityError here with default configuration on OS X 10.10.4

**Comment by phanimahesh** [comment]
I have traced it finally. `localStorage.setItem` is the culprit, it is throwing a securityerror no matter how it is called. The offending line has a call to this. The issue also occurs on some other pages, and all of them have this in common. Now to debug why this happens.. Gimme one more day and I'll get to the bottom of this.

**Comment by tobscure** [comment]
Closing this because it seems to be a browser problem, but feel free to comment if you have more info

**Comment by phanimahesh** [comment]
It is a local issue, can't reproduce with a fresh profile, so okay to close.
