### ISSUE TITLE
[Facebook] Login popup window should be 580px wide instead of 600px

### ISSUE THREAD

**Issue by matteocontrini** [flarum/core#1727]
## Bug Report

**Current Behavior**
The login window shows a warning to Facebook app developers about the use of the popup mode.

**Steps to Reproduce**
1. Go to a forum with the flarum/auth-facebook extension enabled
2. Try to login/signup with a Facebook account that is a developer for the Facebook application
4. See the warning at the bottom

**Screenshots**
![immagine](https://user-images.githubusercontent.com/2164763/51027367-fae07a00-1590-11e9-8753-3369bb3d85e5.png)

**Possible Solution**
According to [this](https://stackoverflow.com/questions/16542490/facebook-auth-dialog-developer-warning-concerning-the-use-of-display-type-po) StackOverflow question, the issue is related to the popup window size. Although I can't find the reference in the Facebook docs, they say that the popup window should be no more than 580x400 pixels.

Currently, the `LoginButton` component creates a window of 600x400 pixels.

https://github.com/flarum/core/blob/167059027e5a066d618599c90164ef1b5a509148/js/src/forum/components/LogInButton.js#L15-L26

I think that changing the window size to 580x400 would fix this problem, and it should not have any other unintended consequence with other providers.

**Comment by franzliedke** [comment]
@matteocontrini Do you still have this problem? I cannot reproduce it on https://discuss.flarum.org.

**Comment by datitisev** [comment]
I cannot reproduce this on Discuss either.

**Comment by matteocontrini** [comment]
Yes, still seeing this. Firefox 69 on Windows 10.

![immagine](https://user-images.githubusercontent.com/2164763/66003212-c2c5f200-e4a5-11e9-88c9-8e5c75d2c6be.png)

**Comment by franzliedke** [comment]
Thanks for the quick feedback! Merging then...
