### ISSUE TITLE
Confirmed opt-in for mails + anti spam listing registration

### ISSUE THREAD

**Issue by luceos** [flarum/core#1728]
## Feature Request

Although we are doing a confirmed opt-in for emails, once a user signed up there's no way for the user to opt out from the email. The mails sent by Flarum have to offer the ability to unsubscribe. Not doing so ensures that ISP's and spamlists will mark the mails as potential spam, resulting in a potential ban.

**Describe the solution you'd like**

All mails sent by Flarum should have a link allowing the user to unsubscribe from emails. This link can direct to the user settings page.

This features should be part of core because a) core (extensions) is sending most (if not all) of the current mails and b) because it has to set a standard.

**Comment by tobyzerner** [comment]
Duplicate of flarum/issue-archive#447

**Comment by luceos** [comment]
Wow ancient 😂
