### ISSUE TITLE
Language tab issue

### ISSUE THREAD

**Issue by 1iuhongyu** [flarum/core#1729]
After installing the Simplified Chinese language pack, the Select Language menu is opened by default. Even if it is closed in the background, it will be opened in the background next time. Front-end and background tab Simplified Chinese options display "default" (Google Translate)

![](https://i.loli.net/2019/01/17/5c3fc6c25f680.jpg)
![](https://i.loli.net/2019/01/17/5c3fc6e181238.jpg)

**Comment by 1Cosmo** [comment]
Video presentation
https://dev.tencent.com/s/75107769-ddff-437b-b64b-e8678abc90fa

**Comment by glowingblue** [comment]
I think, this issue reported the same. #1478

**Comment by LetUsPro** [comment]
Hi,在你的Flarum项目里 /vendor/flarum/core/src/Locale/LocaleServiceProvider.php  这个php文件里的第31行代码，  你注释掉就会正常显示，不会出现Default了 @1iuhongyu

**Comment by LetUsPro** [comment]
Hello, You can find problem in /path to your flarum project/vendor/flarum/core/src/Locale/LocaleServiceProvider.php  line 31, comment it out and it's OK. @glowingblue

**Comment by franzliedke** [comment]
Merging this into #1478.
