### ISSUE TITLE
JavaScript failed on empty User.data().links

### ISSUE THREAD

**Issue by ppoffice** [flarum/core#173]
I found [this thread](http://discuss.flarum.org/d/191/chinese-words-test/14) cannot show replies correctly, so I checked the console to find out what happened:

![image](https://cloud.githubusercontent.com/assets/8849362/8741219/19473d94-2c88-11e5-956f-042d123c2079.png)

As I looked a little bit into the call stack, I find forEach() failed on this.groups() and it seems that this.groups() returned either a null or an undefined value so the forEach() method was not functioning normally.

```js
d.prototype.badges=function(){var e=new u["default"];return this.groups().forEach(function(t)
```

So I went into the source code and found this "this.groups().forEach" in https://github.com/flarum/core/blob/27419237141e7a5f59eb94d13ba408abd753d90a/js/lib/models/user.js#L52.
```js
User.prototype.badges = function() {
  var items = new ItemList();

  this.groups().forEach(group => {
    if (group.id() != 3) {
      items.add('group'+group.id(),
        Badge.component({
          label: group.nameSingular(),
          icon: group.icon(),
          style: {backgroundColor: group.color()}
        })
      );
    }
  });

  return items;
}
```
It's clear that the "d" above refers to the User class. So I opened the console again:

![2](https://cloud.githubusercontent.com/assets/8849362/8741429/36a6aa52-2c8b-11e5-8798-c23e0332cd93.JPG)

All of the stored users has a groups() array returned except for user #975, so I skimmed the source code again and found https://github.com/flarum/core/blob/27419237141e7a5f59eb94d13ba408abd753d90a/js/lib/models/user.js#L19
```js
User.prototype.groups = Model.many('groups');
```
and https://github.com/flarum/core/blob/27419237141e7a5f59eb94d13ba408abd753d90a/js/lib/model.js#L96
```js
static many(name) {
    return function() {
      var link = this.data().links[name];
      return link && link.linkage.map(function(link) {
        return app.store.getById(link.type, link.id)
      })
    }
  }
```
The user groups come from User.data().links(), but from what I found in the thread page, user #975 do not have data().links:

![3](https://cloud.githubusercontent.com/assets/8849362/8741424/28fedbea-2c8b-11e5-8a26-c74ffe29742b.JPG)

I stopped here, and I think the easiest way to solve this issue is to add a condition to the `many(name)` function to test whether this.data().links exists. I hope this will help you solve the problem :)

**Comment by tobscure** [comment]
@ppoffice Thanks for the detailed investigation – 'twas helpful indeed :)
