### ISSUE TITLE
Interchangable Icons

### ISSUE THREAD

**Issue by tankerkiller125** [flarum/core#1737]
## Feature Request

Currently, the Icons used in flarum is Font Awesome 5 which based on searching through code appears to be hard-coded, now as I understand it beta 8 made using custom icons in groups much better but I still do not see a way that would allow the replacement of core icons. (navigation, editor, etc.)

This features should be part of flarum because it allows some customizability and prevents every flarum install from looking the same as another one. It would also allow extension developers to introduce new ways of implementing icons.

A solution to this problem would be to move the icon packs to an extension as @luceos had previously noted back [here](https://github.com/flarum/core/issues/1326#issuecomment-355958640) 

The alternative I considered in [this post](https://discuss.flarum.org/d/18640-use-iconify-for-icons/2) (Iconify) seems to have been a good idea but as luceos pointed out in a comment it would increase the offsite dependency which is not ideal, it seems that making icons an extension is an excellent alternative.

**Comment by tobscure** [comment]
Theoretically replacement of core icons is possible via custom CSS, something like:

```css
.far.fa-comments {
  font-family: MyCustomIconFont;
  content: "\uXXXX";
}
```

Happy to consider any ideas for how de-coupling icons from FontAwesome could work, but I have none myself atm

**Comment by luceos** [comment]
I have heard this same request from clients as well. Especially when they have very strict design systems in place. My solution would be to 

a) extract icons to their own extension
b) use locale strings or other type of replacement references (we could even inject into TextFormatter perhaps) for the icon

Obstruction might be the difference between the sets and how they should be rendered. Span vs svg vs font etc.

Also FA could potentially work with treeshaking too.

**Comment by tobscure** [comment]
I think this will quickly get unnecessarily complicated. Best solution in my eyes is to stick with FontAwesome as the core syntax/icon naming, and then allow extensions to override CSS as per my previous comment, or add their own JS to inject SVGs etc etc. That way we keep core uncomplicated, and extensions just need to "bridge" their own custom icons with FontAwesome syntax, in whatever way they deem appropriate.

**Comment by franzliedke** [comment]
[Using SVG](https://svgontheweb.com/) (possibly directly via inlining) could help - we'd need to create a map of all icons and make that overridable for extensions.

Sounds like quite a lot of work, though.

**Comment by tankerkiller125** [comment]
I'm going to close this ticket, an extension has been created that takes care of this issue.

**Comment by luceos** [comment]
@tankerkiller125 can you please mention that extension? Discuss or packagist link would be best.

**Comment by tankerkiller125** [comment]
https://discuss.flarum.org/d/21401-icons-by-fajuu is the extension that currently does this.
