### ISSUE TITLE
Searching title within discussions from search bar

### ISSUE THREAD

**Issue by bdumaspilhou** [flarum/core#1738]
## Bug Report

**Current Behavior**
I have 2 discussions and when I'm searching them with a word from searchbar, no result.

**Expected Behavior**
I don't understand as last version of Flarum added this point [Improve search performance and design (#1339, 7e95b80)]

**Screenshots**
Discussions List
![image](https://user-images.githubusercontent.com/4144908/51912455-b0eef500-23d4-11e9-9c53-66d1cdd66480.png)

After search
![image](https://user-images.githubusercontent.com/4144908/51912491-cfed8700-23d4-11e9-8625-f730ee701209.png)

**Environment**
- Flarum version: 0.1.0-beta.8.1
- Webserver: Apache 2.37
- Hosting environment: vps
- PHP version: 7.3.1-1
- MySQL 5.7.19

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```
![image](https://user-images.githubusercontent.com/4144908/51912740-48ecde80-23d5-11e9-81ad-b85ffcb73060.png)

Many Thanks

**Comment by bdumaspilhou** [comment]
Hi All,
I found the problem and I correct it on my local sources.
The problem was in core/src/Discussion/search/Gambit/FulltextGambit.php on line 55. Replace ->join by ->leftJoin to correct this.

**Comment by luceos** [comment]
@bdumaspilhou could you perhaps send in a PR to mitigate this and we can review?

Editing files in your vendor folder will block upgrades.
