### ISSUE TITLE
Move GetDisplayName to User namespace

### ISSUE THREAD

**Issue by luceos** [flarum/core#1742]
The GetDisplayName event is stored under the src/Event, this is incorrect. The event is purely in use for the Flarum/User namespace and as such should be moved to Flarum/User/Event.

All related code has to change and a changelog item should be created.

**Comment by franzliedke** [comment]
Not really necesary, IMO. All events under `Flarum\Event` should basically be considered deprecated - their use cases are all meant to be covered by [extenders](https://github.com/flarum/core/issues/851).

**Comment by tobscure** [comment]
But I suppose assuming we do add an extender for this, the internal GetDisplayName event should still be moved to the User namespace

**Comment by luceos** [comment]
This issue is indeed about the location of the event. As it is related to the user it should be moved under that namespace, not the global Flarum one where eventually no events should remain.
