### ISSUE TITLE
Possibile issue with posts and profile (public / private )

### ISSUE THREAD

**Issue by PeopleInside** [flarum/core#1746]
## Bug Report

**Current Behavior**

User admin peopleinside is an administrator.
It has public posts and private posts, private posts are associated to a tag restricted to only admin.

If you visit the peopleinside profile as visitor: https://community.peopleinside.it/u/peopleinside
you can see Messaggi (Post): 139 but the list is empty to the visitor.

peopleinside profile should have public posts listed and the number 139 is not correct to the visitor side, should count only posts allowed (public) instead of show a empty list.

![00](https://user-images.githubusercontent.com/5006150/52598248-73b74800-2e55-11e9-9530-25e1330631a5.png)

An example of public post made by peopleinside and visible to visitor is here: https://community.peopleinside.it/d/19-vulnerabilit-phishing-in-firefox-chrome-opera-unicode-domains-2017/2

If i am logged as admin i can see the 139 post listed also, all correct but not into the visitor side...

**Steps to Reproduce**

Create some private posts. How? Associate then to a private tag accessible only to admin.
Make profile admin to be visible by everyone, visit it.

I don't know in a new install (not tested) but on my existent install public posts are not showed in my user profile, posts list.

**Expected Behavior**
See listed public posts in the profile

**Environment**
* Flarum version: 0.1.0-beta.8.1PHP 7.3.1
* Website URL: https://community.peopleinside.it
* Webserver: [e.g. apache, nginx] Apache
* Hosting environment: [e.g. shared, vps] VPS
* PHP version: 7.3.1
* Browser: Firefox last one

```
Output of "php flarum info", run this in terminal in your Flarum directory.


`Loaded extensions: Core, date, libxml, pcre, dom, fileinfo, filter, hash, json, SPL, bz2, posix, Reflection, session, SimpleXML, standard, xml, xmlreader, xmlwriter, bcmath, openssl, calendar, ctype, curl, dba, mbstring, ftp, gd, gettext, gmp, iconv, imap, intl, ldap, exif, zlib, pcntl, PDO, pdo_sqlite, shmop, soap, sockets, sqlite3, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlrpc, xsl, zip, Phar, mysqlnd, mysqli, pdo_mysql, ionCube Loader, Zend OPcache
+------------------------------+-----------------+--------+
| Flarum Extensions | | |
+------------------------------+-----------------+--------+
| ID | Version | Commit |
+------------------------------+-----------------+--------+
| flarum-approval | v0.1.0-beta.8 | |
| flarum-bbcode | v0.1.0-beta.8 | |
| flarum-emoji | v0.1.0-beta.8 | |
| flarum-flags | v0.1.0-beta.8.1 | |
| flarum-likes | v0.1.0-beta.8.1 | |
| flarum-lock | v0.1.0-beta.8 | |
| flarum-mentions | v0.1.0-beta.8.1 | |
| flarum-sticky | v0.1.0-beta.8 | |
| flarum-subscriptions | v0.1.0-beta.8 | |
| flarum-suspend | v0.1.0-beta.8 | |
| flarum-tags | v0.1.0-beta.8.2 | |
| flarum-lang-english | v0.1.0-beta.8 | |
| flarum-statistics | v0.1.0-beta.8 | |
| flarum-akismet | v0.1.0-beta.8 | |
| nearata-lang-italian | v0.1.0-beta.8.2 | |
| flarum-auth-facebook | v0.1.0-beta.8 | |
| flagrow-terms | 0.3.1 | |
| fof-links | 0.1.1 | |
| flarum-auth-github | v0.1.0-beta.8 | |
| fof-user-bio | 0.1.1 | |
| flarum-pusher | v0.1.0-beta.8.1 | |
| reflar-twofactor | 0.1.0-beta.4.2 | |
| flarum-auth-twitter | v0.1.0-beta.8 | |
| flagrow-upload | 0.7.0 | |
| flarum-markdown | v0.1.0-beta.8 | |
| fof-default-user-preferences | 0.1.0 | |
+------------------------------+-----------------+--------+
Base URL: https://community.peopleinside.it
Debug mode: off`


**Possible Solution**
<!--- Only if you have suggestions or a fix for the bug -->

**Additional Context**
Add any other context about the problem here.

**Comment by PeopleInside** [comment]
Discussion showed in my profile is 69 but for the user is not listed 69 topics. Is this number correct?
Maybe so the post issue can be not the number 139 but the fact there are no public post listed ?!

Should post and discussion number be relative to what the visitor see or should include all posts also not visible posts for the user?

**Comment by franzliedke** [comment]
Closing this as duplicate of flarum/issue-archive#321 and flarum/framework#1722.
