### ISSUE TITLE
Error mesage when click profile (avatar icon) in homepage

### ISSUE THREAD

**Issue by gumpon** [flarum/core#1747]
First time open flarum beta 8.1 and click avatar icon have error message.

**Steps to Reproduce**
1. Go to https://webboard.badawards.com/
2. click avatar
3. Error message "The requested resource was not found."

**Screenshots**
https://www.danbkk.com/flarum/404.gif

**Environment**
- Flarum version: 0.1.0-beta.8.1
- Website URL: https://webboard.badawards.com/
- Webserver:  apache
- Hosting environment: vps
- PHP version: 7.2.10-0ubuntu0.18.04.1
- Browser: Version 71.0.3578.98 (Official Build) (64-bit)

**Output of "php flarum info"**

+------------------------+-----------------+--------+
| Flarum Extensions      |                 |        |
+------------------------+-----------------+--------+
| ID                     | Version         | Commit |
+------------------------+-----------------+--------+
| flarum-approval        | v0.1.0-beta.8   |        |
| flarum-bbcode          | v0.1.0-beta.8   |        |
| flarum-emoji           | v0.1.0-beta.8   |        |
| flarum-lang-english    | v0.1.0-beta.8   |        |
| flarum-flags           | v0.1.0-beta.8.1 |        |
| flarum-likes           | v0.1.0-beta.8.1 |        |
| flarum-lock            | v0.1.0-beta.8   |        |
| flarum-markdown        | v0.1.0-beta.8   |        |
| flarum-mentions        | v0.1.0-beta.8.1 |        |
| flarum-statistics      | v0.1.0-beta.8   |        |
| flarum-sticky          | v0.1.0-beta.8   |        |
| flarum-subscriptions   | v0.1.0-beta.8   |        |
| flarum-suspend         | v0.1.0-beta.8   |        |
| flarum-tags            | v0.1.0-beta.8.2 |        |
| zeokat-seoslugs        | v0.1.6          |        |
| s9e-mediaembed         | 1.0.0           |        |
| fof-links              | 0.1.1           |        |
| fof-profile-image-crop | 0.1.1           |        |
| fof-socialprofile      | 0.1.0           |        |
+------------------------+-----------------+--------+

**Comment by datitisev** [comment]
@gumpon Please use our issue template when reporting issues. We have a template so sufficient information is provided for us to solve the issue. You can find the template [here](https://raw.githubusercontent.com/flarum/core/master/.github/ISSUE_TEMPLATE/bug-report.md).

**Comment by luceos** [comment]
Try disabling image crop and social profile and see whether that helps.

Other than that the "resource not found" most often is caused by incorrect url rewriting.

**Comment by gumpon** [comment]
disable social profile extension. It's OK.

**Comment by gumpon** [comment]
I try disable but it's not ok.

**Comment by PeopleInside** [comment]
This is happening because access to profile is not set to public. If you change access profile to public in the backend the issue is resolved.

**Comment by datitisev** [comment]
@PeopleInside 🤦‍♂️ That is most likely true. If so, @gumpon are you admin in the forum? Can you try setting the "View user list" permission to Guest/Everyone, and see if that fixes the issue?

**Comment by PeopleInside** [comment]
Will fix because I had the same issue. Maybe profile view permission should be changed to public by default or you should have a different error page.

**Comment by MichaelBelgium** [comment]
Kinda related to #1680

**Comment by franzliedke** [comment]
So is there a new bug here or not? To me, it sounds like it was a misconfiguration?

**Comment by datitisev** [comment]
@franzliedke I think it's both misconfiguration and the fact that the "view user list" permission blocks users from viewing user profiles when they do not have it, which has been discussed before.

**Comment by franzliedke** [comment]
So then #1680 should be enough.
