### ISSUE TITLE
Remove overflow-x: hidden on .App to make scroll anchoring work in Firefox

### ISSUE THREAD

**Issue by matteocontrini** [flarum/core#1748]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Firefox will be introducing an implementation of scroll anchoring in Firefox 66. This is a feature that's been available in Chrome for a while now, that allows to avoid content jumping when images or content in general are loaded above the viewport.

It turns out that the fact that in Flarum the `overflow-x: hidden` rule is applied on the `.App` container makes it hard for scroll anchoring to work. Google Chrome has a workaround for that, Firefox not yet, so the implementation of scroll anchoring actually does nothing on Flarum.

The discussion about this is in the Firefox bug reports platform. Specifically: the bug about Flarum ([1525586](https://bugzilla.mozilla.org/show_bug.cgi?id=1525586)), and the one about overflow hidden ([1520581](https://bugzilla.mozilla.org//show_bug.cgi?id=1520581)).

**Describe the solution you'd like**

Considering that:
- the final fix from Firefox could take a while, while scroll anchoring will be out in a month
- we don't know if this behaviour reduces the "quality" of scroll anchoring in Google Chrome as well
- Firefox is the second most used browser

And if it is confirmed that the `overflow-x` could be removed without unintended consequences, my proposal would be to remove that rule from the `.App` container.

I can confirm that disabling the overflow makes scroll anchoring work, as shown by the anchor highlighted in Firefox 66 Beta by enabling a flag. I also see no horizontal scrollbars in my limited testing.

With overflow-x:

![immagine](https://user-images.githubusercontent.com/2164763/52626606-d2abaa00-2eb3-11e9-83a9-bd2b6d9624b6.png)

Without overflow-x:

![immagine](https://user-images.githubusercontent.com/2164763/52626593-caec0580-2eb3-11e9-929c-b8e41fb05482.png)

Thank you.

**Comment by franzliedke** [comment]
Thanks for the detailed research!

We'll need input from @tobscure on why this rule is there in the first place. :)

**Comment by tobscure** [comment]
I can't remember why it's there :( It may be something to do with modals and scrolling.

If someone could remove it on their local installation and do some reasonably extensive multi-browser testing on any side effects, that would be greatly appreciated.

**Comment by matteocontrini** [comment]
I've just applied

```
.App { overflow-x: visible; }
```

on my [production forum](https://forum.fibra.click). Let's see if I notice something or someone complains. Nothing evident for now.

**Comment by tobscure** [comment]
@matteocontrini Thanks. On mobile your forum now scroll horizontally a tiny bit when viewing a discussion. That'd be why we have the `overflow-x: hidden` rule. We should try and fix the problem in another way though.

**Comment by matteocontrini** [comment]
@tobscure I'm unable to reproduce that... Chrome on Android 9

**Comment by luceos** [comment]
Seeing the same white space when using mobile view on Chrome/osx

![image](https://user-images.githubusercontent.com/504687/55036484-0c2b1580-501b-11e9-9b14-3d7ca8ffbc8d.png)

**Comment by matteocontrini** [comment]
I'm not seeing that on Chrome/Windows 🤔

![immagine](https://user-images.githubusercontent.com/2164763/55069775-197cea00-5085-11e9-8187-0081cf78b5b2.png)

**Comment by matteocontrini** [comment]
Ok I'm seeing it now, not sure why I wasn't 🤔

**Comment by matteocontrini** [comment]
The Firefox scroll anchoring bug will be [fixed](https://bugzilla.mozilla.org/show_bug.cgi?id=1520581) in Firefox 77, out on 2 June 2020.
