### ISSUE TITLE
MiddlewarePipe.php Issue

### ISSUE THREAD

**Issue by erguner** [flarum/core#175]
This issue from after the installation ...

( ! ) Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Middleware must be callable' in /vagrant/system/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php on line 112
( ! ) InvalidArgumentException: Middleware must be callable in /vagrant/system/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php on line 112
Call Stack
#	Time	Memory	Function	Location
1	0.0001	126764	{main}( )	.../index.php:0
2	0.2222	1942096	Zend\Stratigility\MiddlewarePipe->pipe( )	.../index.php:14
Variables in local scope (#2)
$middleware =
null
$path =
object(Flarum\Forum\Middleware\LoginWithCookie)[265]
  protected 'actor' => 
    object(Flarum\Support\Actor)[267]
      protected 'user' => null

**Comment by franzliedke** [comment]
Duplicate. Please check out #110.
