### ISSUE TITLE
delete user lacks ui feedback

### ISSUE THREAD

**Issue by acodispo** [flarum/core#1750]
## Bug Report

**Current Behavior**
When deleting a user, no feedback is shown to indicate whether the delete was successful or not.

**Steps to Reproduce**
1. Go to user profile page
2. Use controls dropdown to click delete
3. confirm delete
4. Bug: there is no confirmation that the delete has happened, and the user profile remains displayed. If you refresh, you see a message indicating that the resource is not available.

**Expected Behavior**

Once the delete is confirmed, a message should be displayed indicating the user has been deleted.

The user profile should probably cease to show at that point as well, since continuing to show it indicates that it still exists (when presumably it has been deleted).

**Environment**
- Flarum version: 0.1.0-beta.8.1
- Website URL: https://bb.acodispo.net
- Webserver: apache
- Hosting environment: shared
- PHP version: 7.2.11
- Browser: firefox 65.0.1

```
$ php flarum info
Flarum core 0.1.0-beta.8.1
PHP version: 7.2.11
Loaded extensions: Core, date, libxml, pcre, sqlite3, filter, hash, mbstring, SPL, PDO, Reflection, sodium, pdo_sqlite, session, standard, bcmath, bz2, calendar, ctype, curl, dom, exif, fileinfo, ftp, gd, gettext, iconv, imap, json, mysqlnd, openssl, pcntl, pdo_mysql, zlib, posix, pspell, mysqli, SimpleXML, soap, sockets, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, Phar, imagick, Zend OPcache
+----------------------+-----------------+--------+
| Flarum Extensions    |                 |        |
+----------------------+-----------------+--------+
| ID                   | Version         | Commit |
+----------------------+-----------------+--------+
| flarum-approval      | v0.1.0-beta.8   |        |
| flarum-bbcode        | v0.1.0-beta.8   |        |
| flarum-emoji         | v0.1.0-beta.8   |        |
| flarum-lang-english  | v0.1.0-beta.8   |        |
| flarum-flags         | v0.1.0-beta.8.1 |        |
| flarum-likes         | v0.1.0-beta.8.1 |        |
| flarum-lock          | v0.1.0-beta.8   |        |
| flarum-markdown      | v0.1.0-beta.8   |        |
| flarum-mentions      | v0.1.0-beta.8.1 |        |
| flarum-statistics    | v0.1.0-beta.8   |        |
| flarum-sticky        | v0.1.0-beta.8   |        |
| flarum-subscriptions | v0.1.0-beta.8   |        |
| flarum-suspend       | v0.1.0-beta.8   |        |
| flarum-tags          | v0.1.0-beta.8.2 |        |
+----------------------+-----------------+--------+
Base URL: https://bb.acodispo.net
Installation path: /home/andcod/flarum
Debug mode: off
```

**Possible Solution**

**Additional Context**

I'm not sure if this should be categorized as a bug or a UI feature request.

**Comment by franzliedke** [comment]
Thanks for the report - yes, that sounds wrong indeed.

If anybody wants to take this on:
- Redirect to the forum homepage **on successful deletion**
- Show a message (banner? flash?) that the deletion was successful.
- Error handling if deletion fails
