### ISSUE TITLE
Unread View

### ISSUE THREAD

**Issue by Justinzobel** [flarum/core#1755]
## Feature Request

**Describe the solution you'd like**
A new view in the dropdown box
![image](https://user-images.githubusercontent.com/1370117/53768963-56dcd480-3f2a-11e9-9b33-fb2141cce936.png)

Ideally, a new item in this dropdown that shows ONLY unread posts. I monitor a forum for new posts in all threads, this would make my job easier to view just unread and action accordingly.

This would likely be more useful to forum admins/mods but maybe useable by users who are interested in responding to posts and assisting.

**Comment by tobscure** [comment]
The dropdown you're referring to is for *sorting* results. You're after a *filter* to display only unread results.

You can actually achieve this now by searching for `is:unread`. (Seems to be broken in beta 8, have just pushed a [fix](https://github.com/flarum/core/commit/e17bb0b4331f2c92459292195c6b7db8cde1f9f3))

The question is should we add this as a filter on the index sidebar (below All Discussions / Following).

**Comment by Justinzobel** [comment]
Excellent work. I'll wait for the fix to land and just use the search feature. 

I think this will suffice for my use, however, if more users request it, it may be worth implementing as a filter on the sidebar.

I'm going to close this as you have provided a process for me achieving what I want. I'll wait for the fix to land in the next release and talk to my admin about getting it updated.

**Comment by therealmaxmoon** [comment]
It would be a really useful feature to have it in the drop down menu. Most modern forums have this feature and I really miss it.

It's cool to use `is:unread` but I want to provide this feature to all my users. 

Would it be possible to implement this to have it in the drop down menu?
