### ISSUE TITLE
The link to get help in the installation is a 404

### ISSUE THREAD

**Issue by arteteco** [flarum/core#1758]
## Bug Report

That's a very easy bug, but you know, may give the impression of a pretty much unpolished software. Flarum can do better than that.

**Current Behavior**
In the error page during the installation the "help" link brings to a 404

**Steps to Reproduce**
1. Install flarum with composer (with wrong permissions on the folder, for example) and go with the browser to the 
2. You'll see a page saying 

> Hold Up!
> These errors must be resolved before you can continue the installation. If you're having trouble, get help on the [Flarum website](http://flarum.org/docs/installation).
3. click on the Flarum website and...
4. See error 404

**Expected Behavior**
Should have been directed to the existing docs

**Environment**
- Flarum version: x.y.z
- Website URL: http://example.com
- Webserver: nginx
- Hosting environment: self-hosted
- PHP version: 7.3
- Browser: chrome

Output of "php flarum info", run this in terminal in your Flarum directory.
```
Command "info" is not defined.
```

**Possible Solution**
just replace `http://flarum.org/docs/installation` with `https://flarum.org/docs/install.html`

**Comment by matteocontrini** [comment]
Already fixed for the next beta: https://github.com/flarum/core/pull/1699
