### ISSUE TITLE
Flarum may cause Browsing History massed up

### ISSUE THREAD

**Issue by LimiQS** [flarum/core#176]
As we all know, when scrolling in a post in Flarum, the last section in the URL will change. (for example, in "http://discuss.flarum.org/d/187/word-association-game/123" the changing part is "123")
In chrome 43 and some other browsers, the NOT constant URL will cause browsing history messed up, because browser will record every URL change. So hundreds of browsing history may generated while a visitor viewing JUST ONE post.
Here is the screenshot:
![historyyyyyyyy](https://cloud.githubusercontent.com/assets/9378097/8845127/954a28f0-314e-11e5-9735-e55e9a93378d.png)

Please forgive my poor English.

**Comment by tobscure** [comment]
I don't think this can be fixed. http://stackoverflow.com/questions/26793130/history-replacestate-still-adds-entries-to-the-browsing-history
