### ISSUE TITLE
If the mail server is down or not accessible at that moment, the register process will be damaged

### ISSUE THREAD

**Issue by lubobill1990** [flarum/core#1769]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Steps to Reproduce**
1. go to the register page
2. if mail server is down at that moment
3. user can't register because the AccountActivationMailer doesn't catch exception when sending mail.

**Expected Behavior**
A 

**Screenshots**
![image](https://user-images.githubusercontent.com/641540/55384330-0a061100-555d-11e9-8b32-098c2877aa97.png)

**Environment**
- Flarum version: latest
- Website URL: http://example.com
- Webserver: [e.g. apache, nginx]
- Hosting environment: [e.g. shared, vps]
- PHP version: 7.3
- Browser: [e.g. chrome 67, safari 11]

**Comment by luceos** [comment]
What behaviour do you expect? The mail to be delayed or registration to succeed nevertheless and auto activating the user?

**Comment by lubobill1990** [comment]
@luceos I except to catch the exception and log the exception to notify the administrator.
I think the activation mail sending failure is not so significant to prevent the register process.
Especially in my scenario, I'm developing mobile app with flarum as the backend, email is not sufficient to register an user.

I'm looking forward to have official queue or scheduled tasks in core. Currently, I'm using a queue extension https://github.com/ZhiShiQ/FlarumQueue developed by myself based on  illuminate/queue.

**Comment by tobscure** [comment]
> @franzliedke are we going to introduce queues or scheduled tasks in core?

yes

**Comment by askvortsov1** [comment]
Considering all the mail verification and testing features, and that https://github.com/flarum/core/issues/978 should essentially fix this, should we close this in favor of #978?

**Comment by lubobill1990** [comment]
Yes, thanks
