### ISSUE TITLE
Infinite loading for the notifications

### ISSUE THREAD

**Issue by SolidOrphan** [flarum/core#177]
I have a notification but when I click on it, the infinite loading gif shows but nothing happens. Sometimes it works sometimes it doesn't. I have no messages of errors.

**Comment by tobscure** [comment]
Errors in the JavaScript console?

**Comment by SolidOrphan** [comment]
I found this in the console of Google Chrome :

Uncaught TypeError: Cannot read forum-3lERXKevTPzqGBoN.js:1 property 'discussion' of undefined.

**Comment by tobscure** [comment]
Still happening?

**Comment by SolidOrphan** [comment]
It's fixed !

**Comment by tobscure** [comment]
:tada:
