### ISSUE TITLE
Newly Install Flarum + Let's Encrypt SSL Website Broken

### ISSUE THREAD

**Issue by janskey** [flarum/core#1771]
I setup Let's Encrypt and enable to redirect HTTP traffic to HTTPS. After Nginx reloads, the website becomes broken. If I click the "Load Unsafe Script", the page becomes "Not Secure". Any idea on this?

Details:
* Ubuntu 18.04.2 LTS
* nginx version: nginx/1.14.0
* Let's Encrypt SSL

![with-ssl](https://user-images.githubusercontent.com/11430512/56089432-2bec8580-5ec5-11e9-83ef-cf31fd1980eb.jpg)

![script-ssl](https://user-images.githubusercontent.com/11430512/56089431-2b53ef00-5ec5-11e9-8499-762b5d0cae2d.jpg)

**Comment by matteocontrini** [comment]
Make sure you changed the website URL in config.php and cleared the Flarum cache.

**Comment by janskey** [comment]
@matteocontrini thanks it solved the issue. by the way how to clear the cache?

**Comment by datitisev** [comment]
You can clear the cache by running `php flarum cache:clear` or clicking the "Clear Cache" button found in the "Tools" dropdown in the Admin Dashboard page.
