### ISSUE TITLE
Translation fallbacks are not loaded in the front-end

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#1774]
I investigated the issues a few people had with translations and found that the fallback translations simply aren't loaded in the front-end. Most recent discussion about this on Discuss https://discuss.flarum.org/d/19684-missing-translations-flarum-shows-translation-id

Situation is as follow: an extension isn't translated in a given language. The visitor switches the language of the forum to that language.

Expected: get texts in english.

Actual: no translations available, we end up with the keys being displayed.

We can point the lack of implementation to https://github.com/flarum/core/blob/9115b9e28f9c5d1b53708090f183d71e095678ce/src/Frontend/AddTranslations.php#L57 where we essentially only give the front-end strings in the active language. Meaning the fallback strings are never retrieved.

I did some tests to see what is needed to implement it. It seems as "simple" (see issue below) as taking the example from the Symfony documentation https://symfony.com/doc/current/components/translation/usage.html#retrieving-the-message-catalogue

```php
$catalogue = $this->locales->getTranslator()->getCatalogue($locale);
$translations = $catalogue->all('messages');
while ($fallbackCatalogue = $catalogue->getFallbackCatalogue()) {
    $translations = array_replace($fallbackCatalogue->all('messages'), $translations);
}
```

Trying to run this code, I kept getting "Maximum execution time exceeded" PHP errors. So I suppose maybe the current implementation was made that way because of performance concerns.

Still, it's very problematic. We need those fallback translations in the front-end.

If I find an efficient way of merging those arrays I'll make a PR but in the meantime I wanted to officially report it so we can refer to this issue.

**Comment by jordanjay29** [comment]
Perhaps this could be resolved by including a 'fallback language' field in config.php and having it auto-generate as 'en'. So Flarum could rightfully assume but allow it to be changed.

**Comment by franzliedke** [comment]
> Trying to run this code, I kept getting "Maximum execution time exceeded" PHP errors. So I suppose maybe the current implementation was made that way because of performance concerns.

I'd appreciate if you could look into this a bit further. I assume it should not be a problem in production, because that code would only be run when compiling the JS assets (e.g. when enabling/disabling extensions).

Regarding fallback language:
- It's true that due to our language pack architecture, we don't really have a default fallback language.
- Falling back to the system-configured default makes sense.
- If that's easy to implement, we can also hardcode the English language pack as a last resort, *if it is installed*.

**Comment by clarkwinkelmann** [comment]
Could we split this into two different issues? The discussions about which
language should be the default are a completely different matter than the
broken fallback in the front-end. They can both be worked on separately.

Le dim. 7 juil. 2019 à 15:14, Franz Liedke <notifications@github.com> a
écrit :

**Comment by franzliedke** [comment]
Hmm, the [fallback is indeed already configured](https://github.com/flarum/core/blob/f31f02d4cc0739c4c778a77f786d769634c32e10/src/Locale/LocaleServiceProvider.php#L62) and the [fallback logic is implemented](https://github.com/flarum/core/blob/master/src/Locale/Translator.php#L41-L43), so there is indeed only a bug in getting this to be triggered for the frontend assets.

**Comment by clarkwinkelmann** [comment]
@franzliedke the problem is specifically with the frontend. You can see the line I linked in the issue description in the file `core/src/Frontend/AddTranslations.php`. It's only fetching the catalog for the current locale, bypassing any fallback that might have been defined.

**Comment by jbrgr** [comment]
@clarkwinkelmann The example from the symfony documentation is actually the solution to this problem. There is just a small logical error in your code snipped causing an infinite while loop. :wink:

This way it should work fine (at least it did in my test):
```
$catalogue = $this->locales->getTranslator()->getCatalogue($locale);
$translations = $catalogue->all('messages');
while ($catalogue = $catalogue->getFallbackCatalogue()) {
    $translations = array_replace($catalogue->all('messages'), $translations);
}
```

**Comment by clarkwinkelmann** [comment]
Nice spot! Thanks!

I'll review your PR right away.

**Comment by clarkwinkelmann** [comment]
I separated the discussion about setting the fallback locale so that we can close this one and not forget.

**Comment by jbrgr** [comment]
Thanks for taking care of that so quickly!

**Comment by bobmulder** [comment]
Can anybody give me any direction what happens? My fallback language isn't loaded either...

**Comment by clarkwinkelmann** [comment]
@bobmulder the fix has been merged into the master branch and will be released with beta 12.

**Comment by bobmulder** [comment]
Thank you for the quick response! Any release date of beta 12?

**Comment by clarkwinkelmann** [comment]
@bobmulder see https://discuss.flarum.org/d/22183-dev-diary-beta-12
