### ISSUE TITLE
Add ActivityPub protocol support

### ISSUE THREAD

**Issue by marek-lach** [flarum/core#1778]
## Feature Request

**Is your feature request related to a problem? Please describe.**
ActivityPub would allow greater engagement in discussions on the forum by users coming from decentralised social networks like Mastodon, Misskey, Pleroma, Pixelfed, Plume, Prismo, Friendica, Hunzilla and others.

**Describe the solution you'd like**
An attempt at this has already been started (if stalled?) here: **https://github.com/squeevee/flarum-ext-feddle**. This means that it is very possible to implement ActivityPub in Flarum.
It may serve as an inspiration...

The official ActivityPub specification from W3C can be found here: **https://www.w3.org/TR/activitypub**

**Justify why this feature belongs in Flarum's core, rather than in a third-party extension**
Federation is implemented most reliably when ActivityPub classes are mapped onto the core of the project. That way, any new Flarum user automatically also becomes an activitypub actor, and any new Flarum post is always recognised as an activitypub note too.

As core developers, you know Flarum's internal codebase best. Federation would spike a revival of interest both in Flarum particularly, and forum software in general. The Fediverse has a lively community around it, that is always interested in using and supporting new projects.

**Describe alternatives you've considered**
None?

**Comment by tobscure** [comment]
I think this is extension territory, because not all forums may wish to integrate this technology.

**Comment by luceos** [comment]
Agreed, most definitely. We'll gladly add flexibility to make a third party extension possible, when running into limitations.

**Comment by maltfield** [comment]
What's the status on this?
