### ISSUE TITLE
Little blue square appears

### ISSUE THREAD

**Issue by SolidOrphan** [flarum/core#178]
I don't know if I should report this but in anycase I prefer to be safe. When I move my cursor on the title of one of the topics, a blue square appears : 
![capture](https://cloud.githubusercontent.com/assets/7015069/8882060/99907922-3244-11e5-8a2c-bbd0fa12f055.JPG)

Sometimes everything is fine, sometimes the thing comes back.

**Comment by franzliedke** [comment]
Hmm, is anybody else able to reproduce this?

Also, which operating system and browser (with version) are you using?

**Comment by SolidOrphan** [comment]
Google Chrome Version 44.0.2403.107 m with Windows 8.1

**Comment by tobscure** [comment]
I'm guessing the device you're using is touch-enabled, or Chrome thinks it's touch-enabled, so it's activating the slide controls which aren't meant to be activated on non-mobile devices. But yeah it's a valid bug.

**Comment by SolidOrphan** [comment]
It is ! I didn't think of that. It's a laptop Asus ux303 with a touchscreen.
