### ISSUE TITLE
New PHP Extender: Registering custom exception handler

### ISSUE THREAD

**Issue by matteocontrini** [flarum/core#1781]
Currently, extensions cannot register a custom `ErrorHandler`. For example, an extension cannot throw a custom exception in a controller and also rely on a custom handler to generate an appropriate JSON response.

With the following sample, if `MyException` is thrown in a controller the registered error handler is not called.

```php
# extend.php
return [
    function (ErrorHandler $handler)
    {
        $handler->registerHandler(new MyErrorHandler);
    },
];
```

```php
class MyErrorHandler implements ExceptionHandlerInterface
{
    public function manages(Exception $e)
    {
        return $e instanceof MyException;
    }

    public function handle(Exception $e)
    {
        $status = $e->getCode();
        $error = [
            'status' => (string) $status,
            'message' => $e->getMessage()
        ];

        return new ResponseBag($status, [$error]);
    }
}
```

The problem is that the ErrorHandler is configured with a FallbackHandler that catches all the exceptions (line 82), so if you register a new one it will be appended after the fallback one.

https://github.com/flarum/core/blob/bbe62f400fd849f1f86ce7a4931c59fab4aec6fc/src/Api/ApiServiceProvider.php#L68-L85

I'll leave the discussion and proposals for an improvement to actual PHP/Flarum developers 😄 

Thanks.

**Comment by tobscure** [comment]
Thanks for the detailed report! We basically just need to restructure the binding and then add an Extender for this, similar to how the Frontend extender works.

**Comment by luceos** [comment]
The first example that came into mind is fof/sentry. Which adds it own handler as well. It does by adding the handler into the middleware stack. Check:

https://github.com/FriendsOfFlarum/sentry/blob/master/extend.php#L24-L30

**Comment by franzliedke** [comment]
Linking this to #1641, which also has to do with exception handling, so the two should probably be handled together.

**Comment by franzliedke** [comment]
#1843 made this very easy, now we just need the extenders. :smile:
