### ISSUE TITLE
Extension Management Without Admin Permissions

### ISSUE THREAD

**Issue by Fidgetcetera** [flarum/core#1785]
## Feature Request

As far as I understand it, the usual place extension options get put is inside the admin page. This means that the only people who can change extension options are admins. I'm currently getting started on a themeing overhaul extension, and realizing it would be great for that kind of forum customization to be optionally available to non-admins - forum moderators who can notice an accessibility issue in the current UI and fix it, but maybe don't need to go edit the email data or forum title.

I could see a separate page, like the Admin page, for managing extension options, with separate permissions to possibly access that page at all, and then individual extension permissions.

This would probably be useful for a lot of extensions and a lot of forums. You don't want to make someone an admin just to let them edit translations in Flagrow Linguist because a moderator spotted a typo.

I could see this still being in the admin page, and the admin page given its own permission, and tabs on the admin page individually having sets. I think extension options getting their own section might be less confusing, but I could see it working either way.

**Comment by tobscure** [comment]
I think this would just add too much complexity for a not very convincing use-case, at least at this stage. It's not that hard for a mod to send a message to an admin to point out a typo. Or if the admin trusts someone enough to let them completely alter the forum appearance, then just make them an admin and tell them not to fiddle around with other things.

**Comment by luceos** [comment]
I have had a hard time on this question. From one side I fully understand the need to allow non administrators access to non-vital and extension configuration, on the other hand I also prefer to keep our ACL simple.

**Comment by franzliedke** [comment]
Yeah, can we agree to put this off until more people come along with similar use-cases?

**Comment by franzliedke** [comment]
That said, you should already be able to add a unique settings modal / page / widget in the frontend for your extension, and create / check custom permissions. Or am I missing something?

I am closing this for now, our backlog is already large enough.

**Comment by Ralkage** [comment]
@franzliedke I believe a better example would be how other forums handle Admin CP access such as Vbulletin. With Vbulletin, you can grant Admin access to a user through user groups but you can also grant them access to specific tabs in the Admin CP (not giving them the entire cake, just a piece). Thought, that would be interesting to see a settings modal being used in the way you described. The Admin settings modal can still be there but a permission-based settings modal for the frontend would be neat as well for more control.

**Comment by franzliedke** [comment]
> The Admin settings modal can still be there but a permission-based settings modal for the frontend would be neat as well for more control.

Please note I wasn't suggesting that Flarum's core should offer a base component for such a public modal like we do for the admin side with the `SettingsModal`. Unless, that is, at some point this pattern becomes widely used in extensions. Until then, it is easily possible to implement such a UI in a use-case-driven way by each extension that may need something like this.
