### ISSUE TITLE
Console not making use of error handling

### ISSUE THREAD

**Issue by luceos** [flarum/core#1789]
I've encountered a slight problem with the inability to handle errors in console. Both the API and Frontends (admin/forum) are using the middleware pipe which can be used by extensions to hook into. For this use case I was testing the functionality of [fof/sentry](https://github.com/FriendsOfFlarum/sentry) for Bokt, an extension we aim to be using on discuss soon as well.

The console side of Flarum is very slim, it uses the Symfony Console Application and, aside from registering commands, that's pretty much it. What we need to do is implement the same error handler stack of the middleware pipe. I haven't looked into possible solutions yet and would to hear your opinion @franzliedke as you refactored that part of Flarum recently.

The problem with not having an error handler is that any exception thrown in the application will kill the process. If you don't output the console output to a log you'll never be able to identify an issue at all. Being able to log these errors to a third party service like Sentry helps in taking action as soon as possible, especially when actively using the queue.

**Comment by luceos** [comment]
I've looked into this and symfony console offers a way to work with erroring. In order to do so we need to add an EventDispatcher to the Application. Some information:

- https://symfony.com/doc/current/components/console/events.html
- https://symfony.com/blog/new-in-symfony-3-3-better-handling-of-command-exceptions

**Comment by franzliedke** [comment]
Sounds like a good idea, and the changes should be mostly in `Flarum\Console\Server`. Thanks for doing the research, @luceos.

Open for contributions here!

**Comment by luceos** [comment]
This was fixed in the merged PR's. It now uses the general error handling stack.
