### ISSUE TITLE
font-awesome version 5.9.5 fa-*.less

### ISSUE THREAD

**Issue by Tall75** [flarum/core#1790]
## Bug Report

**Current Behavior**
composer updates which update font-awsome to version 5.9.5 missing fa-icons

Font Awesome 5.9.0 LESS naming change https://fontawesome.com/how-to-use/on-the-web/using-with/less
Font Awesome 5.0.13 https://fontawesome.com/v5.0.13/how-to-use/on-the-web/using-with/less

**Steps to Reproduce**

- Go to Bazaar in admin console
- Install  FoF Profile Image Crop 0.1.1

On command line

- ls -ltr vendor/components/font-awesome/less from flarum root folder, see that fa-files are missing
- php flarum cache:clear

**Expected Behavior**
Forum is not working anymore

In ./storage/logfile:
production.ERROR: Less_Exception_Parser: File fa-brands.less not found. in variables.less in /flarum/vendor/oyejorge/less.php/lib/Less/Parser.php:2793

**Screenshots**

**Environment**
- Flarum version: Flarum core 0.1.0-beta.8.1

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

**Possible Solution**

Check this discussion and the given workaround by Intern

https://discuss.flarum.org/d/20282-less-exception-parser-file-fa-brands-less-not-found-in-variables-less/11

**Additional Context**

**Comment by luceos** [comment]
#1791 fixes this
