### ISSUE TITLE
Consider upgrading PHPUnit version notice

### ISSUE THREAD

**Issue by peter279k** [flarum/core#1795]
## Feature Request

- According to this [issue](https://github.com/sebastianbergmann/phpunit/issues/3332), the `@expectedException` annotation will be deprecated in future PHPUnit versions.
- According official PHPUnit [site](https://phpunit.de/getting-started/phpunit-6.html), the PHPUnit `6` version supports `php-7.0`, and it's not supported currently.
Using `PHPUnit 7` or `PHPUnit 8` instead.

## Suggested solution
- Upgrading the PHPUnit version to `7` or `8` if possible.
And it seems that this project still supports `php-7.1`, I think it's proper to use `PHPUnit 7`.
- The `@expectedException` will be deprecated. Using the `expectException` method instead.

Once this issue is accepted, I would be happy to do this and create related PR :).

**Comment by luceos** [comment]
Yeah this makes a lot of sense. Especially because we already went to php 7.1. Feel free to send in a pr for this.

Thank you for pointing this out 👍

**Comment by franzliedke** [comment]
I've taken care of the deprecated annotation. We're already running PHPUnit 7.
