### ISSUE TITLE
Subject is not edited

### ISSUE THREAD

**Issue by halilhanbadem** [flarum/core#1798]
When editing, if the subject "if" condition, "you do not have the authority," he received a warning.

Website: https://yazilimtoplulugu.com
Browser: Chrome 75
Flarum: 0.1.0-beta.8.1

SS: 

![image](https://user-images.githubusercontent.com/17130294/59963070-79edbd00-94f6-11e9-889d-4f0ac6f2e48b.png)

come to the site you can try,
yours sincerely,
good work!

**Comment by Ralkage** [comment]
I am not able to reproduce this locally or on Flarum Discuss.

To better assist you, can you please provide the following information?

1). The output of the `php flarum info` command ran from the root of your Flarum installation.

and

2). The full contents of the post you made that you tried to edit and was given that error.

**Comment by halilhanbadem** [comment]
I am hosting on a hosting and do not support SSH. I can't execute any commands.

The content of the article is as follows:

if (a == 1) {
 messagebox.show ("this is a");
} else if (b == 1) {
 messagebox.show ("this is b");
}

if there is a "if" condition, it gives an error. When I delete the lines I wrote above (that is, the "if" condition) it does not give an error and confirms the editing.

**Comment by franzliedke** [comment]
@halilhanbadem Can you try to reproduce this on https://beta.flarum.site, please? If you do not encounter the error there, please try disabling extensions on your own install one-by-one to find whether one of them is the problem.

**Comment by halilhanbadem** [comment]
There was no problem when I tried here. It's probably a case of my hosting. Thank you.
