### ISSUE TITLE
Posts content is not a mediumText (ref #1155)

### ISSUE THREAD

**Issue by luceos** [flarum/core#1801]
Even though we merged a PR #1155 in 2017, this migration is not working. The issue seems to relate to something in dbal where changing from text to medium or longtext has no effect.

We need to increase the size of our content.

Ref: https://github.com/doctrine/dbal/issues/2566

**Comment by franzliedke** [comment]
@luceos This only fixed the problem for new installs, but not for existing databases, which would have already run this migration.

Never change migrations that have been released already.

I would wager that discuss probably still has a `text` column here. :confused:

**Comment by franzliedke** [comment]
Hmm, discuss has mediumtext. Something is wrong here.

**Comment by askvortsov1** [comment]
Let's create a new migration that uses the `comment` hack? Linked GH issue doesn't seem to show progress, but if that gets the job done...
