### ISSUE TITLE
Composer does not change when post changed

### ISSUE THREAD

**Issue by luceos** [flarum/core#1807]
## Bug Report

**Current Behavior**

**Steps to Reproduce**
1. Open the composer by clicking edit on a post (don't save)
2. close the composer
3. someone else (or another session) edits the post
4. refresh the page
5. click to edit the post again
6. composer holds the old content, not the new

**Expected Behavior**
Composer should hold the new content.

**Screenshots**

**Environment**
- Flarum version: 0.1.0-beta.9
- Browser: Firefox

**Comment by askvortsov1** [comment]
I am unable to replicate this on discuss.
