### ISSUE TITLE
Error when replying to a post wile the e-mail configuration is wrong

### ISSUE THREAD

**Issue by iPurpl3x** [flarum/core#1808]
## Bug Report

**Current Behavior**
We have a running instance of Flarum where we configured an e-mail address with it's SMTP server and password. Our client changed the password of this e-mail account and suddenly there was an error showing up most of the time when someone tried to reply to a discussion. The error didn't tell anything in particular as the server just responded with status code 500 and "internal server error" as message.
When we figured out that this was related to the change of password, we updated the password in the administration interface and all was working fine again. 
Now the thing is that when this error happens, first the Composer component is loading for a wile (the time it takes for the SMTP request to timeout) and then the GUI would behave as if the reply was not taken in account. When you reload the page, you can see that the reply was actually posted and saved to the DB. 

**Expected Behavior**
For the end user, who is posting a reply, this error does not matter and his reply should be posted to the thread like normal. 
I have no idea how the problem could be reported to admins, but it definitely should be reported as all outgoing e-mails are not working.

**Environment**
- Flarum version: 0.1.0-beta.8.1
- Website URL: https://community.quickline.ch
- Webserver: nginx
- Hosting environment: vps
- PHP version: 7.2.13
- Browser: chrome 75

```
/opt/flarum # php flarum info
Flarum core 0.1.0-beta.8.1
PHP version: 7.2.13
Loaded extensions: Core, date, libxml, pcre, zlib, filter, hash, readline, Reflection, SPL, session, ctype, curl, dom, fileinfo, gd, json, mbstring, openssl, PDO, standard, tokenizer, xmlwriter, zip, mysqlnd, Phar, pdo_mysql, Zend OPcache
+---------------------------------+-------------------------+------------------------------------------+
| Flarum Extensions | | |
+---------------------------------+-------------------------+------------------------------------------+
| ID | Version | Commit |
+---------------------------------+-------------------------+------------------------------------------+
| flarum-tags | v0.1.0-beta.8.2 | |
| flarum-akismet | v0.1.0-beta.8 | |
| flarum-approval | v0.1.0-beta.8 | |
| wiwatsrt-best-answer | v0.1.0-beta.12 | |
| flarum-bbcode | v0.1.0-beta.8 | |
| flagrow-byobu | 0.2.2 | |
| datitisev-dashboard | v0.1.0-beta.8 | |
| cbmainz-de | 0.8.1 | |
| michaelbelgium-discussion-views | dev-master | 756d11681579849ca398f722ef9c4fa67186bcc1 |
| flarum-emoji | v0.1.0-beta.8 | |
| flagrow-analytics | 0.7.0 | |
| flarum-lang-english | v0.1.0-beta.8 | |
| flagrow-html-errors | 0.2.0 | |
| flagrow-impersonate | 0.2.0 | |
| flagrow-linguist | 0.3.1 | |
| flagrow-sitemap | dev-master | de156748aa0d4371fdbaccd6b9160fe293e518f2 |
| flagrow-terms | 0.3.1 | |
| flarum-flags | v0.1.0-beta.8.1 | |
| fof-default-user-preferences | dev-master | 889f349e9e7be6099df6fa8e2604496307ffd9fd |
| fof-links | 0.1.1 | |
| fof-masquerade | dev-master | fbdd21bf6190e8ca988e64a1da1684f6a8fea15b |
| fof-pages | 0.2.3 | |
| flarum-likes | v0.1.0-beta.8.1 | |
| flarum-lock | v0.1.0-beta.8 | |
| kilowhat-mailing | 0.1.0-beta.1 | |
| flarum-markdown | v0.1.0-beta.8 | |
| s9e-mediaembed | 1.0.0 | |
| flarum-mentions | v0.1.0-beta.8.1 | |
| glowingblue-modmsg | dev-develop | 28cf4e724d809c6c78b77cdbad6f37efc7aa5596 |
| flarum-pusher | v0.1.0-beta.8.1 | |
| glowingblue-quickline | dev-develop | 00ee6a1038f107368eef6399c10705bf4f9d1364 |
| reflar-level-ranks | dev-develop | 5abaea7116e922f8a0857ae4f629811879d61d4b |
| reflar-polls | 1.3.4 | |
| reflar-reactions | dev-faq-feedback | b5f124afc3454980d1039e213bab680de84d9d5f |
| flagrow-split | dev-german-translations | b6a9e1b08f5e5512cd18fb66975d30774fc38f61 |
| flarum-statistics | v0.1.0-beta.8 | |
| flarum-sticky | v0.1.0-beta.8 | |
| flarum-subscriptions | v0.1.0-beta.8 | |
| flarum-suspend | v0.1.0-beta.8 | |
| flagrow-upload | 0.7.1 | |
| flagrow-user-directory | dev-master | 63964b5509eb0f3b5e9cb31c10c0a74f7d551311 |
+---------------------------------+-------------------------+------------------------------------------+
Base URL: http://localhost:8888
Installation path: /opt/flarum
Debug mode: ON
```

**Comment by franzliedke** [comment]
This is very much related to several other tickets, the combination of which should make this obsolete:
- #1655 "Send test email" button
- #1763 Warning for unconfigured (and erroring?) mail drivers
- #978 Queues for emails (PR #1773)

**Comment by askvortsov1** [comment]
The same applies to #1769.

**Comment by franzliedke** [comment]
Yes. One of these is a notification mail, which was going to be fixed by Daniel's generic "Notifications into the queue" approach. For #1769, we need to explicitly queue the mail.

#978 is also rather generic, so I'm glad we have a concrete issue for registration. :grin:

**Comment by askvortsov1** [comment]
Seems to me that now that we have queuing for notifications, as well as a test email config button in #2004,  this can be closed.
