### ISSUE TITLE
Searching users doesn't seem to work properly

### ISSUE THREAD

**Issue by iPurpl3x** [flarum/core#1809]
## Bug Report

**Current Behavior**
I noticed that when I type a username into the search-box it only gives results for users that where already "loaded by the frontend". 
This is happening also when I disable all extensions (including the default extensions).

**Steps to Reproduce**
1. Login as an admin
1. Open my forum on the home page (myforum.com/all)
2. Type a known username (TheUser) into the search box
3. Get no results at all
4. Go to the user's Profil page manually (by typing into the address bar : myforum.com/u/TheUser)
5. Go back to the home page by clicking on the forums logo (the page does not reload, just the frontend route changed and displayed different content)
6. Type the same username (TheUser) into the search box
7. Get a normal result showing TheUser
8. Reload the page (Cmd+R)
9. Type the same username (TheUser) into the search box
10. Get no results at all

**Expected Behavior**
See results for any user of the community when typing in the search-box.

**Environment**
- Flarum version: 0.1.0-beta.8.1
- Website URL: https://community.quickline.ch
- Webserver: nginx
- Hosting environment: vps
- PHP version: 7.2.13
- Browser: chrome 75

```
/opt/flarum # php flarum info
Flarum core 0.1.0-beta.8.1
PHP version: 7.2.13
Loaded extensions: Core, date, libxml, pcre, zlib, filter, hash, readline, Reflection, SPL, session, ctype, curl, dom, fileinfo, gd, json, mbstring, openssl, PDO, standard, tokenizer, xmlwriter, zip, mysqlnd, Phar, pdo_mysql, Zend OPcache
+---------------------------------+-------------------------+------------------------------------------+
| Flarum Extensions | | |
+---------------------------------+-------------------------+------------------------------------------+
| ID | Version | Commit |
+---------------------------------+-------------------------+------------------------------------------+
| flarum-tags | v0.1.0-beta.8.2 | |
| flarum-akismet | v0.1.0-beta.8 | |
| flarum-approval | v0.1.0-beta.8 | |
| wiwatsrt-best-answer | v0.1.0-beta.12 | |
| flarum-bbcode | v0.1.0-beta.8 | |
| flagrow-byobu | 0.2.2 | |
| datitisev-dashboard | v0.1.0-beta.8 | |
| cbmainz-de | 0.8.1 | |
| michaelbelgium-discussion-views | dev-master | 756d11681579849ca398f722ef9c4fa67186bcc1 |
| flarum-emoji | v0.1.0-beta.8 | |
| flagrow-analytics | 0.7.0 | |
| flarum-lang-english | v0.1.0-beta.8 | |
| flagrow-html-errors | 0.2.0 | |
| flagrow-impersonate | 0.2.0 | |
| flagrow-linguist | 0.3.1 | |
| flagrow-sitemap | dev-master | de156748aa0d4371fdbaccd6b9160fe293e518f2 |
| flagrow-terms | 0.3.1 | |
| flarum-flags | v0.1.0-beta.8.1 | |
| fof-default-user-preferences | dev-master | 889f349e9e7be6099df6fa8e2604496307ffd9fd |
| fof-links | 0.1.1 | |
| fof-masquerade | dev-master | fbdd21bf6190e8ca988e64a1da1684f6a8fea15b |
| fof-pages | 0.2.3 | |
| flarum-likes | v0.1.0-beta.8.1 | |
| flarum-lock | v0.1.0-beta.8 | |
| kilowhat-mailing | 0.1.0-beta.1 | |
| flarum-markdown | v0.1.0-beta.8 | |
| s9e-mediaembed | 1.0.0 | |
| flarum-mentions | v0.1.0-beta.8.1 | |
| glowingblue-modmsg | dev-develop | 28cf4e724d809c6c78b77cdbad6f37efc7aa5596 |
| flarum-pusher | v0.1.0-beta.8.1 | |
| glowingblue-quickline | dev-develop | 00ee6a1038f107368eef6399c10705bf4f9d1364 |
| reflar-level-ranks | dev-develop | 5abaea7116e922f8a0857ae4f629811879d61d4b |
| reflar-polls | 1.3.4 | |
| reflar-reactions | dev-faq-feedback | b5f124afc3454980d1039e213bab680de84d9d5f |
| flagrow-split | dev-german-translations | b6a9e1b08f5e5512cd18fb66975d30774fc38f61 |
| flarum-statistics | v0.1.0-beta.8 | |
| flarum-sticky | v0.1.0-beta.8 | |
| flarum-subscriptions | v0.1.0-beta.8 | |
| flarum-suspend | v0.1.0-beta.8 | |
| flagrow-upload | 0.7.1 | |
| flagrow-user-directory | dev-master | 63964b5509eb0f3b5e9cb31c10c0a74f7d551311 |
+---------------------------------+-------------------------+------------------------------------------+
Base URL: http://localhost:8888
Installation path: /opt/flarum
Debug mode: ON
```

**Comment by Ralkage** [comment]
I cannot reproduce this, what do you have the "View user list" set to in the Permissions area of your Admin CP? Try clearing your Flarum cache when you try disabling all 3rd party extensions again to see if that helps.

You also seem to have some custom/locally developed extensions too so we can't be sure what you modified or added.

**Comment by iPurpl3x** [comment]
Ok thank you for giving me this idea. I found the culprit : **fof-masquerade** !

**Comment by iPurpl3x** [comment]
For reference, here is the open issue on the extensions repo : https://github.com/FriendsOfFlarum/masquerade/issues/36
