### ISSUE TITLE
Add valid log entries to info command

### ISSUE THREAD

**Issue by luceos** [flarum/core#1812]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Whenever Flarum breaks, mostly due to extensions, we'd like to know more than just the installed extensions. We often also want to be able to get the latest Exception trace.

**Describe the solution you'd like**

Let's extend the info command with a flag `--with-log` so it reads and shows the latest trace, but only a limited number of lines. This could be copied over when filing issues.

**Justify why this feature belongs in Flarum's core, rather than in a third-party extension**

This applies to any error and compared to asking for the info output, asking for the last log entries is asked for more often.

**Describe alternatives you've considered**

Perhaps we can offer a separate command that reads the log and provides more than just a few lines..

**Comment by datitisev** [comment]
We could possibly provide a command similar to `tail` in Unix systems, which also lets users watch the log file.

Color coding might be useful as well, if possible.
