### ISSUE TITLE
Flarum is get too slow with more than 10M posts

### ISSUE THREAD

**Issue by mtawil** [flarum/core#1815]
## Bug Report

**Current Behavior**
We have a vBulletin forum with more than 80M posts, and I developed a custom migration script to Flarum forum, and everything is perfect.

Suddenly, when the script reaches to more than 10M posts, the home page and admin page of Flarum forum get too slow to open, it takes 5-10 seconds to finish the TTFP.

I don't know what the issue is, and I don't know what is the SQL query causes that slowness. But now I am being worried about completing the migration, how long will Flarum homepage will take to finish the request with 80M posts?

The link is private, and it's restricted to our office IP.

```
Flarum core 0.1.0-beta.9
PHP version: 7.3.6-1+ubuntu18.04.1+deb.sury.org+1
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, sodium, session, standard, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, imap, intl, json, exif, msgpack, mysqli, newrelic, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, memcached, Zend OPcache
+---------------------------------+-----------------+--------+
| Flarum Extensions               |                 |        |
+---------------------------------+-----------------+--------+
| ID                              | Version         | Commit |
+---------------------------------+-----------------+--------+
| flarum-approval                 | v0.1.0-beta.8   |        |
| flarum-bbcode                   | v0.1.0-beta.8   |        |
| flarum-emoji                    | v0.1.0-beta.8   |        |
| flarum-lang-english             | v0.1.0-beta.9   |        |
| flarum-flags                    | v0.1.0-beta.9   |        |
| flarum-likes                    | v0.1.0-beta.9   |        |
| flarum-lock                     | v0.1.0-beta.9   |        |
| flarum-markdown                 | v0.1.0-beta.9   |        |
| flarum-mentions                 | v0.1.0-beta.9   |        |
| flarum-statistics               | v0.1.0-beta.9   |        |
| flarum-sticky                   | v0.1.0-beta.9   |        |
| flarum-subscriptions            | v0.1.0-beta.9   |        |
| flarum-suspend                  | v0.1.0-beta.9   |        |
| flarum-tags                     | v0.1.0-beta.9   |        |
| michaelbelgium-discussion-views | v0.1.0-beta.8.2 |        |
| migratetoflarum-old-passwords   | 0.4.0           |        |
| flagrow-upload                  | 0.7.1           |        |
| flagrow-analytics               | 0.8.0           |        |
| flagrow-ads                     | 0.2.0-beta.1    |        |
| clarkwinkelmann-emojionearea    | 0.2.0           |        |
| fof-reactions                   | 0.1.0           |        |
| v17development-seo              | 1.0.1           |        |
| clarkwinkelmann-circle-groups   | 0.2.1           |        |
+---------------------------------+-----------------+--------+
```

**Possible Solution**
Using caches, maybe?

**Comment by mtawil** [comment]
I recently get `504 Gateway Time-out` when sometimes trying to open the admin panel page 🙂

**Comment by franzliedke** [comment]
Hi @mtawil, thanks for reaching out! We obviously want Flarum to scale in the best way possible. In this case, I am not sure what we can do right now.

To continue solving these problems, you should first try to narrow down the exact origin of this error. What you could do:
- disable all non-official extensions to make sure they are not the problem
- use a debugger / profiler to find which part of Flarum / an extension is slow
- check your database's slow query logs
- check other error logs (PHP / server etc.)

We cannot do this for you, as it's obviously a problem on your forum. We will be glad to help you if you need help with any of these steps - but let's take this to the [forums](https://discuss.flarum.org).

Until we have more information, I will close this issue. We are trying to keep only actionable issues open on GitHub. Thanks for your understanding. :)

**Comment by mtawil** [comment]
Hello @franzliedke,

Let's start debugging the slowness SQL query that executed at `/admin` and takes `34,100ms`:
```sql
select count(*) AS aggregate FROM `forum_posts` WHERE `type` = ? AND `type` IN (?, ?, ?, ?, ?) 
```

### Stack trace:
```
/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php (117)
/vendor/illuminate/database/Connection.php (330)
/vendor/illuminate/database/Connection.php (657)
/vendor/illuminate/database/Connection.php (624)
/vendor/illuminate/database/Connection.php (333)
/vendor/illuminate/database/Query/Builder.php (2095)
/vendor/illuminate/database/Query/Builder.php (2083)
/vendor/illuminate/database/Query/Builder.php (2569)
/vendor/illuminate/database/Query/Builder.php (2084)
/vendor/illuminate/database/Query/Builder.php (2496)
/vendor/illuminate/database/Query/Builder.php (2424)
/vendor/illuminate/database/Eloquent/Builder.php (1338)
/vendor/flarum/statistics/src/Listener/AddStatisticsData.php (57) in Flarum\Statistics\Listener\AddStatisticsData::Flarum\Statistics\Listener\{closure} called at ? (?)
/vendor/flarum/statistics/src/Listener/AddStatisticsData.php (55)
/vendor/flarum/statistics/src/Listener/AddStatisticsData.php (42)
/vendor/flarum/core/src/Frontend/Frontend.php (65)
/vendor/flarum/core/src/Frontend/Frontend.php (57)
/vendor/flarum/core/src/Frontend/Controller.php (34)
/vendor/flarum/core/src/Http/RouteHandlerFactory.php (40)
```

### Table hints:
- This table was retrieved with a full table scan, which is often quite bad for performance unless you only retrieve a few rows.
- The table was retrieved with this index:
- No index was used in this part of the query.
- You can speed up this query by querying only fields that are within the index. Or you can create an index that includes every field in your query, including the primary key.
- Approximately 24590264 rows of this table were scanned.

### Query Analysis:
| Id | 1 |
|---------------|-------------|
| Select type | SIMPLE |
| Table | forum_posts |
| Partitions |  |
| Type | ALL |
| Possible keys |  |
| Key |  |
| Key len |  |
| Ref |  |
| Rows | 24590264 |
| Filtered | 5.0 |
| Extra | Using where |

---

Obviously, this query is not coming from any extension; it comes from Flarum itself.

**Comment by franzliedke** [comment]
That would be our [statistics extension](https://github.com/flarum/statistics).

Can you also find out the origin behind the forum's index slowness?

**Comment by luceos** [comment]
The statistics extension is not recommended on large installations, we need to do some work on that extension to be valuable in the long run. Feel free to disable it for now.
