### ISSUE TITLE
[Tags] Improve UI for drag-and-drop placeholder

### ISSUE THREAD

**Issue by jordanjay29** [flarum/core#1816]
The UI for the tag ordering via drag-and-drop is still fairly clunky despite its attempt at elegance. 

To change order, without nesting, tags must be dragged significantly above/below an existing tag's center line. There are no visual indicators as to how far to drag to achieve this in order to be between the target tags and not others. 

To change nesting, tags must be dragged to the right of the primary tag's color/icon badge. There are no visual indicators of how far to drag to achieve this, or how far to drag back to restore a tag to an unnested state. There is also a timed delay on switching from dragging to a nested positioning and primary positioning. 

The UI may need improvements with regards to spacing and visual indicators to allow more precise targeting during the drag-and-drop operations.

**Comment by askvortsov1** [comment]
Fixed in https://github.com/flarum/tags/pull/82
