### ISSUE TITLE
Issue with HTTPS

### ISSUE THREAD

**Issue by haizbp** [flarum/core#1825]
Hi,

I tried to run Flarum with HTTPS but it seems not working as expected.
I am not sure whether this is a bug or not.
Please check my screenshot below

![image](https://user-images.githubusercontent.com/32725831/61427784-9b9d6100-a949-11e9-83e8-2e15e2d691e6.png)

![image](https://user-images.githubusercontent.com/32725831/61427804-ab1caa00-a949-11e9-8ebf-0ad4c59c4c84.png)

**Comment by matteocontrini** [comment]
Make sure you change the endpoint in the configuration file.

**Comment by matteocontrini** [comment]
Solved here, for the record: https://discuss.flarum.org/d/20775-issue-with-https

**Comment by clarkwinkelmann** [comment]
@haizbp were you able to solve this ? As pointed out by matteo this looks like a wrong url in `config.php`, not an issue with Flarum itself.

I'm closing this issue, consider opening a discussion on the forum if you still have issues with your Flarum configuration, or let me know if you think I should reopen this issue.
