### ISSUE TITLE
First run Flarum

### ISSUE THREAD

**Issue by CarlosVitorino** [flarum/core#1826]
Opening the browser with nginx pointing to public folder I got directly the error:
Error booting Flarum: syntax error, unexpected '='

Any tip about it?

System: 
Ubuntu 18.04
PHP 7.2
MariaDB 10.0.38
Nginx 1.10.3

The error stacktrace:

` #0 /srv/flarum/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/srv/flarum/ven...') #1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Illuminate\\Supp...') #2 /srv/flarum/vendor/flarum/core/src/Foundation/Application.php(415): spl_autoload_call('Illuminate\\Supp...') #3 /srv/flarum/vendor/flarum/core/src/Foundation/Application.php(373): Flarum\Foundation\Application->getProvider(Object(Illuminate\Events\EventServiceProvider)) #4 /srv/flarum/vendor/flarum/core/src/Foundation/Application.php(196): Flarum\Foundation\Application->register(Object(Illuminate\Events\EventServiceProvider)) #5 /srv/flarum/vendor/flarum/core/src/Foundation/Application.php(110): Flarum\Foundation\Application->registerBaseServiceProviders() #6 /srv/flarum/vendor/flarum/core/src/Foundation/UninstalledSite.php(58): Flarum\Foundation\Application->__construct('/srv/flarum/pub...', '/srv/flarum/pub...') #7 /srv/flarum/vendor/flarum/core/src/Foundation/UninstalledSite.php(52): Flarum\Foundation\UninstalledSite->bootLaravel() #8 /srv/flarum/vendor/flarum/core/src/Http/Server.php(57): Flarum\Foundation\UninstalledSite->bootApp() #9 /srv/flarum/vendor/flarum/core/src/Http/Server.php(34): Flarum\Http\Server->safelyBootApp() #10 /srv/flarum/public/index.php(22): Flarum\Http\Server->listen() #11 {main}`

**Comment by CarlosVitorino** [comment]
The error stacktrace:

 #0 /srv/flarum/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/srv/flarum/ven...') #1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Illuminate\\Supp...') #2 /srv/flarum/vendor/flarum/core/src/Foundation/Application.php(415): spl_autoload_call('Illuminate\\Supp...') #3 /srv/flarum/vendor/flarum/core/src/Foundation/Application.php(373): Flarum\Foundation\Application->getProvider(Object(Illuminate\Events\EventServiceProvider)) #4 /srv/flarum/vendor/flarum/core/src/Foundation/Application.php(196): Flarum\Foundation\Application->register(Object(Illuminate\Events\EventServiceProvider)) #5 /srv/flarum/vendor/flarum/core/src/Foundation/Application.php(110): Flarum\Foundation\Application->registerBaseServiceProviders() #6 /srv/flarum/vendor/flarum/core/src/Foundation/UninstalledSite.php(58): Flarum\Foundation\Application->__construct('/srv/flarum/pub...', '/srv/flarum/pub...') #7 /srv/flarum/vendor/flarum/core/src/Foundation/UninstalledSite.php(52): Flarum\Foundation\UninstalledSite->bootLaravel() #8 /srv/flarum/vendor/flarum/core/src/Http/Server.php(57): Flarum\Foundation\UninstalledSite->bootApp() #9 /srv/flarum/vendor/flarum/core/src/Http/Server.php(34): Flarum\Http\Server->safelyBootApp() #10 /srv/flarum/public/index.php(22): Flarum\Http\Server->listen() #11 {main}

**Comment by franzliedke** [comment]
Hello and thank you for your interest in Flarum! :smile: 

Unfortunately, this is not the right place for getting support. We only discuss bug reports and features to-be-implemented here on GitHub. Please take your discussion to [our forums](https://discuss.flarum.org). More people can help out there,

When you do so, please make sure to describe in much detail as possible:
- what problem you are having,
- what steps you took so far,
- what went wrong,
- what happened and what you would have expected instead.

Please help us help you!
