### ISSUE TITLE
Error message window appears with Chrome data compression proxy

### ISSUE THREAD

**Issue by alexbagirov** [flarum/core#183]
After the last update I can't use Flarum on my forum correctly. It creates about threee windows with the same error "Oops! Something went wrong". I also can't close them because they appear again. 
Also it is not possible to mark thread as read by swiping it :(

**Comment by alexbagirov** [comment]
Also it doesn't read the thread so if I open and read the topic then it will throw me these errors and won't mark as read.

**Comment by tobscure** [comment]
Marking as read by swiping is fixed. Closing this until we can work out what's going on with the error messages. Basically I need more info, like info from the JS console if you can work out how to get it. But until then, I have no way of reproducing the issue.

**Comment by SolidOrphan** [comment]
I was browsing with my phone (Chrome on Galaxy S5) and I had this message : 
(I don't know if there is a console on mobile so I can't find an error message)
![screenshot_2015-07-29-02-02-57](https://cloud.githubusercontent.com/assets/7015069/8947047/858ed6b2-3596-11e5-85af-da2d51b30771.png)

**Comment by tobscure** [comment]
Could you please follow the instructions [here](https://developer.chrome.com/devtools/docs/remote-debugging) to inspect any errors in the console? Nothing I can do unless I know what's going wrong :/

**Comment by SolidOrphan** [comment]
I found that tuto yesterday while searching to find the console on Android it but my computer doesn't recognize the phone (I installed the drivers and enabled the USB debugging). I'll try an another method or another phone.

**Comment by alexbagirov** [comment]
@tobscure, I have the same as @SolidOrphan. Will try to use your article and inspect those errors.

**Comment by SolidOrphan** [comment]
Chrome won't recognize my phone argh...

**Comment by alexbagirov** [comment]
@SolidOrphan, me too. Have you installed USB driver?

**Comment by SolidOrphan** [comment]
I did, I have a Galaxy S5. I even installed Kies 3 (the USB driver is inside too). I enabled the USB debugging option but nothing on Chrome;

**Comment by alexbagirov** [comment]
@SolidOrphan, have just successfully connected. Don't know what I did...

**Comment by alexbagirov** [comment]
@tobscure, first of all it gives me a 404 for favicon file...
Looking for the error.
![default](https://cloud.githubusercontent.com/assets/6885864/8964352/8f44ec3e-363e-11e5-827f-cc90331d1032.jpg)

**Comment by alexbagirov** [comment]
@tobscure 
Yeah, got it. That what it says...
![default](https://cloud.githubusercontent.com/assets/6885864/8964422/ebb74426-363e-11e5-8f8e-ef8c4289086f.jpg)

Also I doesn't do anything right now and it continue throwing errors.
![1](https://cloud.githubusercontent.com/assets/6885864/8964462/2979d094-363f-11e5-9ce6-882581ff9952.jpg)

**Comment by tobscure** [comment]
@alexfox thanks. could you please go into the Network tab and screenshot the contents of the "Headers" and "Response" tabs for one of those 502 requests?

**Comment by alexbagirov** [comment]
@tobscure sure. The headers are

![headers](https://cloud.githubusercontent.com/assets/6885864/8977877/786e004a-36b6-11e5-8993-868661d1c5cf.jpg)

Also that is the response preview (HTML Page)

![preview](https://cloud.githubusercontent.com/assets/6885864/8977884/86f5436c-36b6-11e5-8f9e-2904e9b8d899.jpg)

"Response" tab gives me an HTML code of the page from preview. My browser uses Chrome Data Compression. Seems that it brakes something.

**Comment by franzliedke** [comment]
Judging by [the extension page](https://chrome.google.com/webstore/detail/data-compression-proxy/ajfiodhbiellfpcjjedhmmmpeeaebmep), you should be able to put Flarum on the bypass list as a temporary fix.

That said, it would still be interesting to know why this causes it to fail.

**Comment by alexbagirov** [comment]
@franzliedke, it is a Chrome app for PC, isn't it? I have problems only on mobile Chrome and can disable Data Compression there.

**Comment by SolidOrphan** [comment]
I have data compress on my phone too !

**Comment by alexbagirov** [comment]
After the last push "mark all as read" button doesn't work at all too. So it is not possible to read topics at all...

**Comment by tobscure** [comment]
Steps to reproduce:

1. Enable the Chrome Data Compression Proxy extension in Google Chrome (https://chrome.google.com/webstore/detail/data-compression-proxy/ajfiodhbiellfpcjjedhmmmpeeaebmep)
2. Attempt to mark a discussion as read, edit a post, or perform another action that *updates* something.
3. After a while, an error message saying that something went wrong will be displayed. Upon inspection via the Chrome Inspector's Network tab, we can see that Chrome Data Compression Proxy has an error with these requests.

Technical info:
It appears that Chrome Data Compression Proxy is not able to handle Flarum's PATCH ajax requests for some reason.

What needs to be done:

* Investigate why this is happening.
* Come up with a fix or workaround.

**Comment by tobscure** [comment]
@alexbagirov don't create a new topic on the forum when there is already a well-documented issue for this

**Comment by tobscure** [comment]
Should be fixed with #502
