### ISSUE TITLE
Browser state on mobile for index not persisting

### ISSUE THREAD

**Issue by luceos** [flarum/core#1831]
## Bug Report

**Current Behavior**
When browsing discuss the mobile browser does not remember the state after visiting discussions. So when you re-open the browser the state is as if you didn't visit any discussions. You can manually reset the state by refreshing the page, which is annoying and defeats the idea of a SPA.

**Steps to Reproduce**
1. Open discuss on mobile
2. Click on any discussion
3. See the state of the index change
4. Close browser
5. Re-open browser
6. State is reset as if you never opened that discussion
7. Refresh page reads the new state

**Expected Behavior**
Whenever you re-open the browser that the index state is identical to after having visited the last time.

**Environment**
- Flarum version: nightly
- Website URL: https://discuss.flarum.org

**Comment by matteocontrini** [comment]
I've had this happen similarly on desktop now. I opened my forum, viewed some unread discussions, closed the tab and then reopened it (ctrl+shift+t). The discussions that I previously read were marked as unread.
