### ISSUE TITLE
Screen Reader semi-unlabeled button to show notifications when logged in 

### ISSUE THREAD

**Issue by smoke-j** [flarum/core#1836]
There is a button when logged in to show your notifications. This button has an irregular behavior when navigating with a screen reader. It seems to bee labled, but only partially. When navigating from the top of the page it reads as "button  collapsed". However if I go to the button after it which reads as "S Smokebutton" then go back to the unlabled button it reads normally as "button  collapsed  Notifications".
I have only ever seen this once before on FluxBB with the quick reply to a topic buttons.

I have no idea what causes this, but it would probably be something fairly simple since I have only ever seen it once before.
I tested this in both NVDA and Jaws.
Everything works perfect with Jaws, but with NVDA the above issues happen both in chrome and firefox.

**Comment by SychO9** [comment]
@davwheat this is probably not valid anymore since we added explicit aria labels to those buttons ?

**Comment by davwheat** [comment]
Yep, these are labelled now.

![image](https://user-images.githubusercontent.com/7406822/142634911-74f38d89-f538-4752-b500-edbf2e62ef66.png)
