### ISSUE TITLE
Only translations for enabled extensions should be loaded from language pack

### ISSUE THREAD

**Issue by rob006** [flarum/core#1837]
According to [this discussion](https://discuss.flarum.org/d/19971-extensions-translation-in-their-own-repository-or-in-language-pack), translations of extensions should be in language packs instead of extensions itself. I worked recently to make this approach more convenient for translators, but there is still a performance issue with it. 

Right now Flarum loads all translations from language packs, so if I install a language pack with translations for 1000 extension, Flarum will load all 1k translation files even if I don't need 970 of them. I'm not sure how heavy this is from PHP side, but translations are also included in the generated JS file, so this may result in a huge JS file (full of unnecessary translations) which will slow down page load.

I suggest loading only translation files with names that match the ID of one of the installed extensions (+core files). This change may break some language packs which does not follow this convention, so this probably should be addressed in beta 10.

**Comment by datitisev** [comment]
@rob006 That's funny, I actually suggested this privately about a week ago and forgot about it.

I don't think the issue would be with convention (tbh I don't think it's official either, so we wouldn't want to push that, but perhaps we do as we'd be introducing breaking changes after all). What could be done is add a method to the `Frontend` extender which specifies the locale prefix if necessary. Probably not the best idea, not sure how the PHP obtains translations that aren't passed to frontend / backend. That can be discussed.

Translations aren't very heavy on the backend afaik as they are only compiled when the cache is cleared or an extension is enabled/disabled, so that wouldn't be an issue. However, a big locale JS size could still be.

**Comment by rob006** [comment]
> Translations aren't very heavy on the backend afaik as they are only compiled when the cache is cleared or an extension is enabled/disabled, so that wouldn't be an issue.

It could be an issue if generating cache will be so slow that it will never complete on slow hosting with low timeout limit.

**Comment by datitisev** [comment]
@rob006 I highly doubt that would ever be an issue, most likely other elements that generate cached assets would timeout before it. Still this would be a good idea.

**Comment by clarkwinkelmann** [comment]
We currently don't enforce any naming convention for translations, so we can't just use the prefix to choose which translations to keep. Maybe we should standardise that so we can use it to easily discard any translation not using a prefix that's in the `enabled_extensions` settings.

If we cross-reference the translation keys registered in the default language with the one from a language pack, we might hit similar memory issues as with #1774 

Also relevant: translations can reference another translation key. If that key is not part of any enabled extension, what should happen ?

**Comment by rob006** [comment]
@clarkwinkelmann I'm not proposing filtering by key prefix, but by file name. So if in language pack you have file `flarum-pusher.yml`, it will be loaded only if `flarum-pusher` extension is enabled. We don't care what keys are used inside of this file.

This approach should be easier to implement, easier to maintain for language packs maintainers, and more efficient overall (no need to process unused file at all). It may be also more flexible - technically you could create 2-3 extensions which will only provide translation strings (each extension would have different message for the same key) - user could choose which labels he wants by simple enabling correct extension.

**Comment by clarkwinkelmann** [comment]
@rob006 sorry I must have missed that part in your comment above. That would be a great solution!

**Comment by franzliedke** [comment]
Personally, I'd rather pursue a centralized / official version of the [Weblate initiative](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate) (at some point after stable). If that became reality, we could automatically fetch only the translations for the currently installed set of languages / extensions from that central server.

But let's leave this up for discussion.

**Comment by rob006** [comment]
@franzliedke That would be the best solution, but we still need some intermediate solution to test the centralized translations repository idea and migrate every existing language pack to the new repo. This means that we need a solution like https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate working for some time, and this issue is a serious blocker to keep it reliable. 

Performance is one concern, but current logic (load every file from language pack) is also problematic from a language pack maintainer perspective. Right now my Weblate initiative automates many things, including fetching new translation strings and generating language packs from them. There is no validation of the content of `yml` files - every extension can use any key for translation strings. This means that two extensions can use the same key and conflicts with each other. Automation script will fetch both translations and put them in 2 separate files in the language pack. 

At current state always both files will be loaded from language pack and translations from one extension will be overwritten. This is a pathological situation - language pack maintainer needs to fix it manually and remove one extension from language pack. This means additional responsibilities for language pack maintainers - they need to monitor translation sources, search for conflicts and then resolves them by deciding which extension should be kept (which should not really be their concern).

If only translation files from enabled extensions will be loaded, this is no longer language pack maintainer concern - this is extensions conflict which could be handled by the user, like any other extension conflict - just disable one of conflicting extensions.

**Comment by rob006** [comment]
To put some numbers related to this issue:

1. I detected about 110 extensions which support translations and are compatible with Flarum beta 8 or higher.
2. [Polish language pack](https://github.com/rob006-software/flarum-lang-polish) contains translations for these 110 extensions (right now it contains mostly English fallback messages). As a result size of `admin-pl-xxx.js` is about 96kB, and `forum-pl-xxx.js` is about 66kB.
3. I found 2 popular forks, which have not changed keys for translations strings, so they're conflicting with upstream extensions. Many extensions do not use extension ID to prefix their translations (I would say that about 30-50% of community extensions contains keys without such prefix), and it is quite likely that there will be some conflicts in the future.

**Comment by tankerkiller125** [comment]
Personally I like the idea of centralizing where the translation work happens for the core at least, I feel uncomfortable with handling translations of extensions as part of the centralization though. Maybe this is just me misunderstanding how that would work though.

Something I do want to note though is that I am a fan of forcing a standard translation prefix (eg. fof-upload), this prefix is already forced in the JS and I see no reason that we should shy away from forcing it in the language resources. By standardizing/forcing the syntax it would have several benefits I think. Most notably we could easily filter translations so that only relevant ones are served and number two the possibility of an extension conflicting with another one in translations becomes almost impossible as composer packages can't have the same name.

The easiest way I see of forcing the standardization is to make a very public announcement that all extensions will need to use the new standardized prefix syntax in order to be compatible in the next release, update the documentation to reflect this change immediately before the release. And then merge the PR that implements the filtering. This provides one release cycle of fixing/preparing before it breaks (as we are doing for the Zend -> Laminas update)

**Comment by rob006** [comment]
> Something I do want to note though is that I am a fan of forcing a standard translation prefix (eg. fof-upload), this prefix is already forced in the JS and I see no reason that we should shy away from forcing it in the language resources. By standardizing/forcing the syntax it would have several benefits I think. Most notably we could easily filter translations so that only relevant ones are served and number two the possibility of an extension conflicting with another one in translations becomes almost impossible as composer packages can't have the same name.

There are number of drawback of this approach:
1. This is big BC break, that will take a lot of efforts to deal with. All incompatible extensions (and there is a lot of them) will have to update their translations and then all language packs will need to adjust to these changes. Filtering only by package name will require only renaming files in language packs (in many cases it will not be even needed if language pack already follows naming convention), which is simple and BC change.
2. Filtering translations only by prefix will not solve this problem from language pack maintainers perspective - some extensions may still "poison" other extensions by defining translations with prefix from other extension (this problem already exists in some forks, see https://github.com/flarum/core/issues/1837#issuecomment-522220331).
3. This just seems to be more complicated to implement, less efficient and creates another artificial rule developers needs to learn.

**Comment by tankerkiller125** [comment]
Wouldn't extensions still be able to poison one another even with a file name change though? And the problem I see with changing the file name is we either need that file to go into a new directory (so `resources/locale/en/your-extension.yml` or we have to assume a default language that all extensions are written in. For a language pack we could fore sure load it by file name only as the language pack defines the language, but for regular extensions we should still be able to define multiple languages.

**Comment by rob006** [comment]
This problem is not related to regular extensions. Users already have tools to deal with conflicting extensions - they can disable and/or uninstall them, like in any other case when two extensions are conflicting each other.

This problem is related to language packs, which can have over a 100 translation files of different extensions. Right now users have no control which translation files will be loaded - they can either disable language pack completely or load all files. Filtering by file name will give them similar tools like in case of regular extensions - if translation of `your-extension` is conflicting with other extension, user can disable it (and report this as bug to extension maintainer).

**Comment by clarkwinkelmann** [comment]
Following @rob006 suggestion above https://github.com/flarum/core/issues/1837#issuecomment-519585682 I think that's one of the easiest solutions and it might not even break anything as most language packs already retained each extension in their own file.

To add to @tankerkiller125 I don't know if forcing a translation prefix makes sense. I don't think any part of the code currently requires a given prefix (except Linguist, it's the only code that expects the prefixes). The solution above doesn't require us to force anything upon extension devs, we just force language pack maintainers to name the files based on the extension they come from.

I do think we should issue a recommendation for naming translations though. Even if we don't change anything right now, I think our documentation should recommend using the extension ID (vendor-package) for both translation prefix, and file name in language packs. That way when we eventually implement one of the solutions discussed here, less extensions will break.

Given most extensions already follow that unofficial convention, I don't think we would have any issue implementing the change in a not-backwards-compatible way. Only a few extensions would need to fix their keys, probably far less than the other breaking changes we made in the last few betas.

**Comment by rob006** [comment]
There are tens of extensions which does not use extension ID as translation prefix. Just to mention some popular examples:

https://github.com/extiverse/bazaar/blob/master/resources/locale/en.yml
https://github.com/MichaelBelgium/flarum-discussion-views/blob/master/locale/en.yml
https://github.com/wiwatsrt/flarum-ext-best-answer/blob/master/locale/en.yml

The are also forks which does not change translations keys (it is not needed anyway, since you will not install both versions from upstream and fork). And to be honest the way how extension ID is generated i neither intuitive nor reliable (you will still get collisions in some cases).

**Comment by askvortsov1** [comment]
> Personally, I'd rather pursue a centralized / official version of the [Weblate initiative](https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate) (at some point after stable). If that became reality, we could automatically fetch only the translations for the currently installed set of languages / extensions from that central server.
> 
> But let's leave this up for discussion.

I'm not sure how I feel about forcing a centralized service onto users. Right now, a flarum installation can be completely standalone, without needing to connect to any central servers. Some extensions (e.g. Extiverse Bazaar) use this, yes, but that's why they're 3rd party extensions imo. 

We already require developers to use the extension ID in frontend JS, I don't see why we couldn't require language pack maintainers to use it in file names. I think that https://github.com/flarum/core/issues/1837#issuecomment-519585682 is the best approach for core. Centralized translation services are great too, don't get me wrong, but IMO that's more extension territory.

**Comment by datitisev** [comment]
Have we given any thought to having an extended (even an argument for locale extender) to pass the root key (eg in hello.there, root key is hello)? That way the extension passed the root keys to be loaded, and we don't have weird issues like this.

 I guess that'd still be a breaking change though and would require extensions to update rather than language packs. Hm.

**Comment by askvortsov1** [comment]
To be honest, either approach will yield a breaking change (the benefits of being in beta I guess). We could use the extension ID by default if the root key isn't provided to the extender (as most extensions use that anyway) for compatability purposes to give our developers enough time to update their extensions. 

I like your strategy in that it allows flexibility with root keys not necessarily being the extension ID, but I wonder if that might be a down side. Imo, requiring extensions to stick to the ID format is beneficial and gives some rigidity to the framework. If we require it for frontend, I think we should require it for backend too.

**Comment by rob006** [comment]
@datitisev What if two separate extensions define the same root key?

**Comment by askvortsov1** [comment]
Good point, I feel like this is yet another argument for sticking to the extension ID requirement. Checking file names as discussed above might be better than checking the actual root key.

**Comment by clarkwinkelmann** [comment]
I believe forcing the file name in a language pack to match the extension ID doesn't have any downside, and might not even require any change by most language pack maintainers.

Even if an extension is using a non-stand key, you can still name the file according to the extension ID, but include keys that use the actual extension prefix. What we need here is standardize the file names, we don't have to enforce the keys themselves (I think we should strongly recommend using the extension ID there as well, but no need to force it now).

This would really only be a change to the language pack extender, and only language packs might have a small update to do for the few packages.

If I take @rob006 examples from above about extensions with unusual keys, and if I take the French language pack for example:

https://github.com/rooaaar/lang-french-extended/blob/master/locale/extiverse-bazaar.yml
https://github.com/rooaaar/lang-french-extended/blob/master/locale/michaelbelgium-discussion-views.yml
https://github.com/rooaaar/lang-french-extended/blob/master/locale/wiwatsrt-flarum-best-answer.yml

We can see it already follows the rules we would require. The files are already named according to the correct extension ID, and would not require any change to work with the update proposed to the language pack extender.

I believe all we need now is a PR.

**Comment by askvortsov1** [comment]
Correct me if I'm wrong, but this looks like what Daniel's closed PR did. If so, we can just reopen that. If not, I can drop a PR.

**Comment by clarkwinkelmann** [comment]
I just commented on the PR. I don't remember why it was closed. Not sure if this was discussed with the whole team or not. I like the existing PR.

**Comment by rob006** [comment]
New PR: https://github.com/flarum/core/pull/2020
