### ISSUE TITLE
Live preview hidden behind post reply box

### ISSUE THREAD

**Issue by henrywright** [flarum/core#184]
As you can see from the screenshot, the live preview isn't visible after clicking on "reply". I have to scroll down past Allineer's post to see it. This could be happening because I'm using a Chromebook (my vertical screen size isn't very big).

![flarum](https://cloud.githubusercontent.com/assets/1963288/8904959/c1ea3de0-345b-11e5-8d6f-94a706c3d1dc.png)

**Comment by tobscure** [comment]
It's intentional, but I guess it's not the most obvious behaviour, I'll think about changing it.

**Comment by henrywright** [comment]
I did wonder where the preview was at first. I doubt I'd have found it if I wasn't specifically looking for it.

**Comment by DCSJAPAN** [comment]
For what it's worth @tobscure ... I spent a while wondering where I could find that new "preview" feature so I could check it out. (I finally found it by accident, when stroking my Magic Mouse made it pop up.)

On the other hand, I get why you wanted it hidden by default. Having it visible *above* the reply box by default could be a bit confusing to some users (at least until they figure out what's going on).

Perhaps you could leave the preview hidden as you intended, but add a "Preview" button next to the "Post Reply" button in the lower part of the reply box. When the user clicks that button, it causes the discussion to scroll up, revealing the preview from behind the reply box. (Eventually the user will figure out that he can do the same thing by scrolling, so the button is more a teaching aid than anything.)

**Comment by tobscure** [comment]
> Perhaps you could leave the preview hidden as you intended, but add a "Preview" button next to the "Post Reply" button in the lower part of the reply box. When the user clicks that button, it causes the discussion to scroll up, revealing the preview from behind the reply box.

I think this is a good solution.

**Comment by tobscure** [comment]
Added a preview button which scrolls to the preview.

**Comment by DCSJAPAN** [comment]
Love the design you chose for the preview button! It's perfect.
