### ISSUE TITLE
Allow calling formatContent() on a CommentPost without passing a request

### ISSUE THREAD

**Issue by matteocontrini** [flarum/core#1840]
When the `Formatter` was made dependent on the current HTTP request in 0ab9facc4bd59a260575e6fc650793c663e5866a, the `$request` parameter on the `render` method on the formatter was made optional, but [it wasn't](https://github.com/flarum/core/commit/0ab9facc4bd59a260575e6fc650793c663e5866a#diff-3b6ca93f8d90cf7a0b08c9cdc12eba0eR172) on the `formatContent($request)` method in the `CommentPost` class.

As discussed [here](https://discuss.flarum.org/d/20986-contenthtml-attribute-on-post), there might be the need to generate the HTML content in contexts where the request is not available.

The proposal is to change, in the `CommentPost` class, this signature from:

```php
public function formatContent(ServerRequestInterface $request)
```

to:

```php
public function formatContent(ServerRequestInterface $request = null)
```

**Comment by clarkwinkelmann** [comment]
Cross-linking the PR: #1721

Not sure if it's worth an additional issue, but IMO it would be more logical to pass the actor as parameter, assuming guest in contexts where no actor was given. That way the same method can also be useful in the context of sending emails for example, where there is no request, but definitely is an actor.

**Comment by franzliedke** [comment]
Definitely :+1: for the proposal - please feel free to send a PR!

@clarkwinkelmann That was also [my reaction](https://github.com/flarum/core/pull/1721#issuecomment-451325004), but Toby's response isn't completely without merit. Can you share example code where you are using the formatter in a non-request context, please?

**Comment by franzliedke** [comment]
We could also consider passing in something like a `FormattingContext` or `FormattingOptions` that would be determined / retrieved by the calling site based on context.

**Comment by clarkwinkelmann** [comment]
I have no example of my own but it could maybe be used here for example https://github.com/flarum/subscriptions/blob/v0.1.0-beta.9/views/emails/newPost.blade.php#L10

**Comment by matteocontrini** [comment]
Is it still possible to have the PR merged for beta10, as a temporary solution? Thanks
