### ISSUE TITLE
Profile photo - unable to upload

### ISSUE THREAD

**Issue by Notanotherdotcom** [flarum/core#185]
Hi there

When I go to upload a profile photo I get the message "Oops! something went wrong on the server" and it suggests reloading the page.

I tried it with quite a large image initially and then with a much smaller (15kb, square photo 200x200 pixels) and same error message both times.

It was a photo of me, same as on Github here, so hope it's not programmed to find my face offensive ;)

**Comment by franzliedke** [comment]
May be a permission problem on the server, we'll check. :)

Can you share your setup (operating system and browser, with version) please?

**Comment by alexbagirov** [comment]
@franzliedke, see [this](http://discuss.flarum.org/d/395/oops-something-went-wrong/18). Seems to be the same.

**Comment by Notanotherdotcom** [comment]
It was Windows 8.1 with latest Chrome (39). Same issue on two PCs. Also tried Firefox (an older version - can't remember which but not at that machine right now) and same issue if that helps?

**Comment by tobscure** [comment]
Fixed. Just didn't have imagick installed on the new server.
