### ISSUE TITLE
Slow SQL query, possible missing indexes

### ISSUE THREAD

**Issue by waltdestler** [flarum/core#1856]
I've been having an issue where Flarum (beta 7.1) has suddenly become unusually slow, often taking several seconds to respond, despite no changes/upgrades to either Flarum or my server, or any noticeable increase in user activity.

I turned on MySQL slow logging, which revealed this:

```
# Time: 2019-08-21T19:40:23.960144Z
# User@Host: root[root] @ localhost []  Id: 15001
# Query_time: 3.637616  Lock_time: 0.000097 Rows_sent: 4  Rows_examined: 465379
SET timestamp=1566416423;
select * from `notifications` where `notifications`.`user_id` = '10' and `notifications`.`user_id` is not null and `type` in ('discussionRenamed', 'discussionLocked', 'postMentioned', 'userMentioned', 'newPost') and `is_read` = '0' and `is_deleted` = '0';
```

Running EXPLAIN for this query shows:

```
mysql> explain select * from `notifications` where `notifications`.`user_id` = '10' and `notifications`.`user_id` is not null and `type` in ('discussionRenamed', 'discussionLocked', 'postMentioned', 'userMentioned', 'newPost') and `is_read` = '0' and `is_deleted` = '0';
+----+-------------+---------------+------------+------+---------------+------+---------+------+--------+----------+-------------+
| id | select_type | table         | partitions | type | possible_keys | key  | key_len | ref  | rows   | filtered | Extra       |
+----+-------------+---------------+------------+------+---------------+------+---------+------+--------+----------+-------------+
|  1 | SIMPLE      | notifications | NULL       | ALL  | NULL          | NULL | NULL    | NULL | 464433 |     0.04 | Using where |
+----+-------------+---------------+------------+------+---------------+------+---------+------+--------+----------+-------------+
1 row in set, 1 warning (0.00 sec)
```

My notifications table does not have any indexes except for `id`.

This issue was originally [discussed on Discord](https://discordapp.com/channels/360670804914208769/369174406909394944/613820761395822627), and I was requested to post an issue here.

**Comment by tankerkiller125** [comment]
It would appear that beta 7.1 did not have user_id indexes, as of the latest code these indexes have been added. https://github.com/flarum/core/blob/master/migrations/2018_09_15_043337_add_notifications_indices.php

You could as a work around for your forum run the following MySQL command (after selecting your database) in order to manually add the Index:
```mysql
CREATE INDEX notifications_user_id_index ON notifications(user_id);
```

This would add an index for the user_id field in the notifications table. The only issue I can see with doing this however is upgrading Flarum later might not work as already have an index in place could break the future migrations.

**Comment by franzliedke** [comment]
Please update to the latest beta. We do not support outdated beta versions (they are also known security problems in that version, by the way), and as @tankerkiller125 reports this is probably fixed in the latest version.
