### ISSUE TITLE
Deleting a tag can cause error in DiscussionTaggedPost.content()

### ISSUE THREAD

**Issue by squeevee** [flarum/core#1864]
## Bug Report

**Current Behavior**
If a discussion contains a DiscussionTaggedPost that says that a tag was removed from the discussion, and the tag has since been deleted, then in `DiscussionTaggedPost.initProps()` `props.tagsRemoved` will be set to an array containing `undefined`, which will then cause a TypeError in `content()`

This is most easily visible in that it causes the scrubber not to work.
EDIT: this also causes the replies composer to fail.

**Steps to Reproduce**
1. Create a discussion and a tag.
2. Add the tag to the discussion.
3. Add a comment to the discussion.
4. Remove the tag from the discussion.
5. Delete the tag in /admin
6. Refresh the discussion page.

(The comment is so that the "tag removed" DiscussionTaggedPost is separate from the "tag added" DiscussionTaggedPost. It would probably also work to create the discussion with the tag from the beginning, then remove it after; or to add multiple tags and then only remove one.)

**Expected Behavior**
I'd expect DiscussionTaggedPost not to mention any tag that has been deleted, and for it not to be displayed if no existing tags are mentioned.

**Environment**
- Flarum version: 0.1.0-beta.9
- Website URL: localhost
- Webserver: apache2, 
- Hosting environment: localhost
- PHP version: 7.2
- Browser: Chromium Version 76.0.3809.100, Firefox 68.0.2

```
Flarum core 0.1.0-beta.9
PHP version: 7.2.21-1+ubuntu18.04.1+deb.sury.org+1
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, sodium, session, standard, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gettext, iconv, imagick, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, Zend OPcache, xdebug
+----------------------+---------------+--------+
| Flarum Extensions    |               |        |
+----------------------+---------------+--------+
| ID                   | Version       | Commit |
+----------------------+---------------+--------+
| flarum-approval      | v0.1.0-beta.8 |        |
| flarum-bbcode        | v0.1.0-beta.8 |        |
| flarum-emoji         | v0.1.0-beta.8 |        |
| flarum-lang-english  | v0.1.0-beta.9 |        |
| flarum-flags         | v0.1.0-beta.9 |        |
| flarum-likes         | v0.1.0-beta.9 |        |
| flarum-lock          | v0.1.0-beta.9 |        |
| flarum-markdown      | v0.1.0-beta.9 |        |
| flarum-mentions      | v0.1.0-beta.9 |        |
| flarum-statistics    | v0.1.0-beta.9 |        |
| flarum-sticky        | v0.1.0-beta.9 |        |
| flarum-subscriptions | v0.1.0-beta.9 |        |
| flarum-suspend       | v0.1.0-beta.9 |        |
| flarum-tags          | v0.1.0-beta.9 |        |
+----------------------+---------------+--------+
Base URL: https://dev.<private>.localhost/forum
Installation path: /var/www/<private>/dev/forum
Debug mode: ON
Don't forget to turn off debug mode! It should never be turned on in a production system.
```

**Possible Solution**

**Additional Context**
Also seen on https://www.seekadventure.net/d/103-pictures-now-can-be-enlarged, but I am not the admin of that site.

**Comment by datitisev** [comment]
This occurs on discuss as well, [can be seen here](https://discuss.flarum.org/d/178) (unless we fix it / remove the tag label post).
