### ISSUE TITLE
[Subscriptions] Queue "new post" email

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#1869]
**Relates to #978.**

A nice first use-case for playing around with our new queueing support (#1773).

1. Send `new_post` email via queue (which uses the `sync` driver by default, so this should not change behavior).
2. Document the setup for real queue workers using e.g. Redis, and try it out on discuss.

Once this is implemented, we can start showcasing this to extension developers, and tackle other tasks in the system that could benefit from being offloaded to the queue.

**Comment by STotev** [comment]
I've read both the #978 issue and PR conversation as well as the code(multiple times) and still wondering what's the idea of this? Why just not using the original laravel queuing system?

Would've been easier to just have a configuration of what queue type to be used. If the shared hosting doesn't support background workers, the config can remain `sync`.

Am I missing something that I can't explain myself or... ?

**Comment by luceos** [comment]
We are actually using the Laravel Queue, but without any configs (per se). What Flarum relies on more heavily is the ability to replace bindings in the service container. There are several reasons for this:

- we rather allow admins to configure things in the admin area, not in configuration files
- we hope to limit the file size of a full Flarum install by not loading all direct dependencies (drivers)

I used to be skeptic too, mind you, but I think doing it like this makes sense for a product like Flarum.

**Comment by STotev** [comment]
I guess I am missing some internal knowledge about Laravel and components and makes me confused of what is going on.
To be honest. I've never worked on a project that strips off a huge part of Laravel.

I need to dig a bit longer to get better understanding of the internals but I will still be happy to try and work on this so I can get deeper understanding of Flarum as well.

Anyone else could work on this as well. I am taking this mostly for learning purposes.

@luceos is your Redis approach going to be implemented in Flarum?

**Comment by franzliedke** [comment]
AFAIK, bokt/flarum-redis is the current playground for what will probably move into core.

As @luceos already explained, there is not much gain in offering all the adapters and functionalities that Laravel brings to the table in Flarum. We mostly use Laravel (its components, really) as a library, not so much as a framework. Laravel wants to offer a lot to many different types of applications; we have very specific requirements and goals, thus we don't need it all.

My current vision is for Flarum to support a fallback and a "real" driver for queueing. The latter will probably be based on Laravel's Redis queue.

**Comment by gwillem** [comment]
For context: people entering incorrect mail settings is the number 1 cause of people bricking their Free Flarum forum (2-3 cases per week). I'm not sure how you will implement the async mail system, but I hope it has some way to report errors back to the user.

**Comment by datitisev** [comment]
@gwillem I think that's #1763.
