### ISSUE TITLE
Header redrawn incorrectly in some cases

### ISSUE THREAD

**Issue by DCSJAPAN** [flarum/core#187]
This is something new since the recent update. Now and then Safari seems to think the page should be redrawn in a slightly scrolled up position. This causes the header to be only partially redrawn, and it gets stuck that way even after the page is scrolled down.

Here's an example:

![screen shot 2015-07-28 at 4 45 17](https://cloud.githubusercontent.com/assets/13129997/8916113/48b0e526-34e4-11e5-9580-f7f6ec9d5574.png)

This wouldn't be such a problem if it was just the logo ... but it also makes it impossible to use any of the links in the header, including the notification and account control panel buttons.

Fortunately the fix is easy ... just scroll up and down again, and it gets redrawn properly. So this is really an aesthetic issue more than anything.

I wouldn't be surprised if this is a glitch specific to my browser (Safari 7.1.7 running on Mavericks), in which case it will be even less necessary to look into it.

**Comment by tobscure** [comment]
This is indeed a Safari bug, still present in the latest versions. I'll look into a way to fix it.
