### ISSUE TITLE
API returning different data types based on subscription state

### ISSUE THREAD

**Issue by KennethWussmann** [flarum/core#1871]
## Feature Request

**Is your feature request related to a problem? Please describe.**
The REST API responds with the field `subscription` of type `discussions` with different data types.
- When you are unsubscribed to that discussion It's returning a boolean `false` 
- When you are subscribed it's a string with the content `follow`
- When you ignore the discussion it's a string with the content `ignore`

That makes it hard to have a consistent way of interacting with the REST API.

**Describe the solution you'd like**
I'd rather have one data type, so you a can expect what you get back from the API and don't have to map values manually to the correct data types.
Some ideas to streamline that:
- Return `null` when unsubscribed
- Return a string containing `unsubscribed`
- Use integers (0, 1, 2) - not my personal favorite because it encodes the real meaning behind the value

Of course, all of them are breaking changes.

**Justify why this feature belongs in Flarum's core, rather than in a third-party extension**
The REST API already is a core Flarum feature. I think this change would make sense to all third-party users of the REST API.

**Describe alternatives you've considered**
Mapping it manually from booleans or strings to a common type in my project and vice-versa. 
Thats not quite handy and every API consumer will have to do it.

Thank you!

**Comment by clarkwinkelmann** [comment]
Still a good first issue

**Comment by askvortsov1** [comment]
Let's keep this

**Comment by askvortsov1** [comment]
Pr to fix this looks good, just needs a second approval and merge conflict resolution.
