### ISSUE TITLE
Short Password Locks up registration (Beta 10, Nightly Forum)

### ISSUE THREAD

**Issue by tankerkiller125** [flarum/core#1886]
## Bug Report

**Current Behavior**
If the password entered is not eight characters during sign up the error will appear and will not be able to edit the form data.

**Steps to Reproduce**
1. Go to https://nightly.flarum.site
2. Click on "Register"
3. Enter in all information above correctly except for the password (make it less than 8 characters)

**Expected Behavior**
Should still see error but the form should not lock up

**Screenshots**
![image](https://user-images.githubusercontent.com/3457368/64930285-6ef8af00-d7fd-11e9-8921-6285e224bcb4.png)

**Environment**
- Flarum version: dev-master
- Website URL: https://nightly.flarum.site
- Browser: Chrome 76.0.3809.132

**Comment by Ralkage** [comment]
@tankerkiller125 we are aware of this issue but it only pertains to Flarum/nightly as of right now as I have already brought this up with the team during my initial QA testing. Are you having the same issue on your own install either locally or hosted after updating?

**Comment by tankerkiller125** [comment]
I had the same issue in my local dev-master I have not gotten around to testing the actual tagged release yet. I think I jumped the gun adding beta 10 to the title thinking beta 10 was pretty much dev-master at that point.

**Comment by datitisev** [comment]
@tankerkiller125 Have you been able to reproduce it locally again?

**Comment by tankerkiller125** [comment]
@datitisev I am no longer able to replicate this issue locally. However after some further research and a discussion on Flarum I've discovered that the most likely culprit is the Sentry extension (which I had enabled during a test).  I think we might be able to close this issue.

**Comment by datitisev** [comment]
@tankerkiller125 Yeah, the Sentry ext is known to cause some issues with redrawing when you have JS reporting enabled, I'll have to fix that.

I'll close this for now.
