### ISSUE TITLE
Language variables

### ISSUE THREAD

**Issue by Gerryfw** [flarum/core#1889]
Is it planned that you can edit variables for other languages? The reason is that some plugins have not been translated for all languages. In the forum then, for example, only plugin.flarum.list.

**Comment by datitisev** [comment]
Do you mean something like flagrow/linguist, but in core ? Most likely not, as that doesn't seem like it would fit in the simple core of the forum. Don't quote me on that, though.

You can add your own translations already by adding custom locale files to your installation and registering them through the Flarum root `extend.php`.

**Comment by franzliedke** [comment]
Closing this.

We have Linguist, and there is an initiative for a community-wide translation tool for extensions, where everybody could contribute translations for extensions.
