### ISSUE TITLE
Error alert in modal remains after request succeeds

### ISSUE THREAD

**Issue by datitisev** [flarum/core#1892]
## Bug Report

**Current Behavior**
Errors handled with the modal handing that shows an Alert of type error remain after the request succeeds. I don't think there's a method to reset that, probably simply setting `this.alert = null` would be fine.

**Steps to Reproduce**
1. Open change email modal
2. Change email
3. Input wrong password
4. Input correct password

**Expected Behavior**
Error message disappears.

**Screenshots**
![image](https://user-images.githubusercontent.com/6401250/65468980-ccab7d80-de33-11e9-8335-fbb15a8cc1cb.png)
![image](https://user-images.githubusercontent.com/6401250/65468993-d339f500-de33-11e9-8068-ae7c845f0241.png)

**Possible Solution**
Simply set `this.alert = null;` or add a method that does this - easier for extension developers to know it exists and use it.

**Comment by azibom** [comment]
Hi
I fixed it [link](https://github.com/flarum/core/pull/2467)
