### ISSUE TITLE
Back button top: not working as expected

### ISSUE THREAD

**Issue by PeopleInside** [flarum/core#1895]
## Bug Report

**Current Behavior**

The back button should do his job to load the previous page as the browser button but is not working like this. See the steps to reproduce the issue.

**Steps to Reproduce**
1. Go to 'https://discuss.flarum.org/'
2. Click on 'Support'
3. Click on sub category tag 'Upgrading'
4. Open a discussion
5. Move the mouse on top left where you can sticky the menù or press the back button
6. Mouse on the back button, the browser on footer show the Upgrading link so seems as my logic is, when you press back you go back to the Upgrading tag.
7. If you click you will be forwarded to https://discuss.flarum.org/ and you have again to search and open the relative tag and tub tag for be again where you was.

**Expected Behavior**
When you press the back you should go on back not on the main page of the community.

**Screenshots**

NOTE FOR THE SCREENSHOT:

The URL showed on footer by the browser is correct but is not be respected... I mean when you click on back button top you should go back to Upgrading tag, in this case and you are not.

![Immagine](https://user-images.githubusercontent.com/5006150/65814512-1228cb80-e1e3-11e9-8b0f-2f0cfaea31b3.png)

**Environment**
- Flarum version: latest
- Website URL:https://discuss.flarum.org/

**Possible Solution**

**Additional Context**

**Comment by PeopleInside** [comment]
Seems resolved in Beta 11

**Comment by datitisev** [comment]
Ah yes, there was a PR that fixed this but didn't reference the issue. #1942 if I remember correctly.
