### ISSUE TITLE
Can't create user token via API without CSRF

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#1905]
## Bug Report

**Current Behavior**
POSTing to `/api/token` with user credentials in order to create a user token is not possible without CSRF or an Api Key.

**Steps to Reproduce**
1. Perform the request with correct (or invalid) credentials. For example via `curl -d "anything=anything" -X POST https://beta.flarum.site/api/token`
2. `{"errors":[{"status":"400","code":"csrf_token_mismatch"}]}`

**Expected Behavior**
This API endpoint can be useful for mobile apps or other client-side tools that want to authenticate the user and get a token to then access CSRF-protected API endpoints. To enable that, this first endpoint would need to not require the CSRF token.

**Environment**
- Flarum version: beta9, beta10

**Possible Solution**
We should whitelist this route. And maybe have a way to let extensions whitelist other routes as we have seen it's difficult (https://discuss.flarum.org/d/21421-handling-requests-without-csrf-tokens)

If the issue described at that link can not be made easier together with this, maybe it's worth its own issue.

**Additional Context**
first discussed here https://discuss.flarum.org/d/20867-csrf-token-mismatch-on-beta-9-upgrade/6 but I didn't open an issue at the time.

brought up again here https://discuss.flarum.org/d/21581-admin-page-to-generate-api-key

**Comment by franzliedke** [comment]
Haha, it's funny to see how I circumvented this in the tests:
https://github.com/flarum/core/blob/aba291c542b1095fe958650a117602048dd673d1/tests/integration/api/authentication/WithTokenTest.php#L45

That should have been a red flag, I guess. :sweat:

**Comment by franzliedke** [comment]
Closed by #2095.
