### ISSUE TITLE
Security: Admin logs

### ISSUE THREAD

**Issue by PeopleInside** [flarum/core#1911]
## Feature Request

**Is your feature request related to a problem? Please describe.**

In a celebrity forum i discover a security vulnerability not about the software but about a wrong admin configuration but the software used was PHPBB that has a deep admin logs.

The vulnerability discover was the admin was created with an not existant email address and the domain was a public email provider so just registering that address allow the email owner to request password reset and log in into the forum than be able to change users permission, delete post etc.

Vulnerability discovered on thta forum has been fixed so it's no more present.

In PHPBB all is logged also you cannot fully delete log also if you are the admin. This is a good think for security because you have a log of what is happenng.

I think in the future this can be userful also in a serious, great community.
Logs maybe of user admin login, admin actions, etc.

**Describe the solution you'd like**

I think logs in phpbb is something useful for security that helps to understand what is happening in the community also admin side where you can have different moderators and admin.

**Justify why this feature belongs in Flarum's core, rather than in a third-party extension**

An extension can be maybe deactived from the hackers or by other admin.

**Describe alternatives you've considered**

Is just an idea. See you if this can be usefull.

**Comment by franzliedke** [comment]
Thanks for your proposal!

However, I am closing this for two reasons:
- I do believe this belongs in extension space; at least at this time, where implementation and feature set are pretty much unclear. Experimenting with an extension could then pave the way for including it into core.
- This is too far away from the areas we are focusing on for core right now, so I would like to avoid having yet another issue open that we don't have concrete plans for.

I would definitely like to see more discussion on this topic on https://discuss.flarum.org, though! :+1:
