### ISSUE TITLE
Notifications don't follow the rules

### ISSUE THREAD

**Issue by JCKodel** [flarum/core#1914]
## Bug Report

**Current Behavior**
I'm using the bio plugin to show real user names on my forum. If bio is empty, the username is used (in my case, the username is the e-mail, with all invalid chars changed to `-`, so jonh@gmail.com become jonh-gmail-com).

In my plugin, I protect the username showing only the first part of the address (so jonh-gmail.com become jonh).

This is the plugin:
```php
namespace codeart\bioext;

use Flarum\Extend;
use Flarum\User\Event\GetDisplayName;
use Illuminate\Contracts\Events\Dispatcher;
use Illuminate\Contracts\View\Factory;

return [
    function(Dispatcher $events, Factory $views) {
        $events->listen(GetDisplayName::class, function($user) {
            $name = $user->user->bio;

            if(empty($name) or is_null($name)) return explode("-", $user->user->username)[0];

            return $name;
        });
    }
];
```

This works fine on every page:

![image](https://user-images.githubusercontent.com/379339/67343925-093ec780-f50d-11e9-93c4-8893b26c8fc6.png)

The first one is a edited bio.
The following two are automatic bio (I'm using SSO).
The last one has no bio, thus, returns the username (until the first "-").

Everything works fine and the world is beautiful.

BUT, notice the notification popup:

![image](https://user-images.githubusercontent.com/379339/67344036-5d49ac00-f50d-11e9-9936-f4265c883567.png)

Somehow, the unfiltered username is being displayed on some users.

Clicking on that post, everything works:
![image](https://user-images.githubusercontent.com/379339/67344071-80745b80-f50d-11e9-9b42-c00ef6ac7e2b.png)
![image](https://user-images.githubusercontent.com/379339/67344080-84a07900-f50d-11e9-84bd-aea148e42232.png)
![image](https://user-images.githubusercontent.com/379339/67344086-89652d00-f50d-11e9-97f5-6085530df751.png)

There is some inconsistences whether the UI uses the `GetDisplayName::class` or not =\

**Steps to Reproduce**
1) Use the PHP script above in conjunction with the FoF User Bio extension
2) Set an real user name in the bio
3) Set some test user to "some-username-with-dashes"

**Expected Behavior**
I would expect that **every** single use of username would call my plugin.

**Environment**
- Flarum version: 0.1.0-beta.10
- Website URL: https://mcc-forum.code.art.br
- Webserver: nginx
- Hosting environment: Azure Ubuntu 16 Virtual Machine
- PHP version: 7.1
- Browser: Chrome 77

```
jckodel@mail:/data/www/mcc-forum.code.art.br$ php flarum info
PHP Notice:  Undefined offset: 1 in /data/www/mcc-forum.code.art.br/vendor/flarum/core/src/Extension/Extension.php on line 109
Flarum core 0.1.0-beta.10
PHP version: 7.1.32-1+ubuntu16.04.1+deb.sury.org+1
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, exif, mcrypt, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache
+----------------------------------+-----------------+--------+
| Flarum Extensions                |                 |        |
+----------------------------------+-----------------+--------+
| ID                               | Version         | Commit |
+----------------------------------+-----------------+--------+
| flarum-approval                  | v0.1.0-beta.8   |        |
| flarum-bbcode                    | v0.1.0-beta.8   |        |
| flarum-emoji                     | v0.1.0-beta.10  |        |
| flarum-lang-english              | v0.1.0-beta.10  |        |
| flarum-flags                     | v0.1.0-beta.9   |        |
| flarum-likes                     | v0.1.0-beta.9   |        |
| flarum-lock                      | v0.1.0-beta.9   |        |
| flarum-markdown                  | v0.1.0-beta.10  |        |
| flarum-mentions                  | v0.1.0-beta.10  |        |
| flarum-statistics                | v0.1.0-beta.9   |        |
| flarum-sticky                    | v0.1.0-beta.9   |        |
| flarum-subscriptions             | v0.1.0-beta.9   |        |
| flarum-suspend                   | v0.1.0-beta.9   |        |
| flarum-tags                      | v0.1.0-beta.10  |        |
| fof-gamification                 | 0.1.4           |        |
| flagrow-linguist                 | 0.3.1           |        |
| fof-polls                        | 0.1.1           |        |
| fof-default-user-preferences     | 0.2.0           |        |
| fof-follow-tags                  | 0.2.1           |        |
| wiwatsrt-best-answer             | v0.2.4          |        |
| fof-reactions                    | 0.1.0           |        |
| matteocontrini-imgur-upload      | v3.3.0          |        |
| flagrow-analytics                | 0.8.0           |        |
| tiu-ram0n-brazilian-portuguese   | 1.1.10          |        |
| fof-transliterator               | 0.2.0           |        |
| michaelbelgium-discussion-views  | v0.1.0-beta.8.2 |        |
| flagrow-sitemap                  | 0.2.0           |        |
| clarkwinkelmann-circle-groups    | 0.2.1           |        |
| isaced-email-verification-switch | 0.1.3           |        |
| fof-user-bio                     | 0.1.3           |        |
| nikovonlas-web-push              | v0.1.0-beta.8   |        |
| fof-formatting                   | 0.1.2           |        |
| fof-user-directory               | 0.3.3           |        |
| bioext-                          | dev-master      |        |
+----------------------------------+-----------------+--------+
Base URL: https://mcc-forum.code.art.br
Installation path: /data/www/mcc-forum.code.art.br
Debug mode: ON
Don't forget to turn off debug mode! It should never be turned on in a production system.
```

**Comment by datitisev** [comment]
After looking through the code a bit, I don't see a reason why it should return a string other than the display name.

Here are the relevant pieces of code:

> https://github.com/flarum/mentions/blob/4b12b6b8d87d24dc35215525b7dfb39207d04e88/js/src/forum/components/PostMentionedNotification.js#L21
> https://github.com/flarum/core/blob/aa31b8307d2ffb0792b10b8c06a382887172ead2/js/src/common/Translator.js#L59-L63
> https://github.com/flarum/core/blob/aa31b8307d2ffb0792b10b8c06a382887172ead2/js/src/common/helpers/username.js#L9
> https://github.com/flarum/lang-english/blob/8a76061201c5a9b02d2614675f5f7e773b2fdf6a/locale/flarum-mentions.yml#L18

The only thing I can think of is that maybe the event isn't being fired on `/api/notifications`? Can you look at that endpoint and see what the included users' display names are?

**Comment by JCKodel** [comment]
My mistake.
Notice that only the "votes" notifications are bugged, so it is not a Flarum problem.
Trying to pinpoint the bug on my votes extension to report it there.

**Comment by JCKodel** [comment]
This is the offending script: https://github.com/FriendsOfFlarum/gamification/blob/62f38f3b6bbd7eb237c7afbedda9b7ae8a464553/js/src/forum/components/VoteNotification.js

My workaround was to change the translation to remove the username altogether.
