### ISSUE TITLE
No activation emails

### ISSUE THREAD

**Issue by lopar** [flarum/core#192]
I registered at betaforum and received no mail at all. Even on spam filters. I tried to login, and system said, that there isn't such member at all. It feels like my account not just unconfirmed, it never was created. Like: «soo, you fill that registration forms? okay, we'll clear 'em all and make you wait for nothing for ages, ha-ha!».

**Comment by tobscure** [comment]
My bad, thanks for reporting it. Try again now?

**Comment by lopar** [comment]
That's strange. Now I fill in my data, pushed the button and nothing happened. Even the popup window didn't disappear. But I've got two emails after that: 
«Someone (hopefully you!) has changed their email address on Flarum Development Forum to this one.» 
«Someone (hopefully you!) has submitted a forgotten password request for your account on the Flarum Development Forum.»

Okay, I logged in using link in first email, but something is wrong with the whole process...

**Comment by tobscure** [comment]
Glad it's working. Will look into the signup stuff as part of #193
