### ISSUE TITLE
[Tags] Adjust navItems priorities

### ISSUE THREAD

**Issue by matteocontrini** [flarum/core#1923]
The navigation items added to the sidebar by the flarum/tags extension currently all have the same priority (value -10).

![immagine](https://user-images.githubusercontent.com/2164763/67756534-776a1980-fa3a-11e9-9396-a6049386d9fe.png)

This is unideal because extensions may want for example to add a new link button after the "Tags" link.

My suggestion is to adjust priorities to at least separate the "Tags" button and the tags list, so that:

![immagine](https://user-images.githubusercontent.com/2164763/67756665-ada79900-fa3a-11e9-881b-afa31d38399d.png)

This would allow extensions to add a new link to the sidebar, below the "Tags" one.

If this is ok for you I can send a PR.

Thanks

**Comment by tankerkiller125** [comment]
The [User Directory](https://discuss.flarum.org/d/5682-user-directory-by-friendsofflarum) extension already has it's added link below the Tags link and above the topics. And I've seen many other extension do it too. Notably [this code](https://github.com/FriendsOfFlarum/user-directory/blob/master/js/src/forum/index.js#L30) seems to be the part that's doing it.

So I'm slightly confused as to what exactly this issue is trying to address

**Comment by matteocontrini** [comment]
This issue addresses the fact that passing a value of -9 has the effect of adding the link above the Tags button:

![immagine](https://user-images.githubusercontent.com/2164763/67977835-25331f00-fc19-11e9-8bea-df79a5984a5a.png)

While using -10 has the effect of adding it below the buttons, since that's the value used in the tags extension:

https://github.com/flarum/tags/blob/ba4c4929a8297c097c43357e6b1fd660b781c3d5/js/src/forum/addTagList.js

![immagine](https://user-images.githubusercontent.com/2164763/67977932-4eec4600-fc19-11e9-8aa4-0ef9d51dadb5.png)

The link you posted passes 85 as a value, which has the effect of putting the link at the top of the list.

**Comment by matteocontrini** [comment]
Still an issue

**Comment by askvortsov1** [comment]
This was closed by https://github.com/flarum/tags/commit/ea142b8468e20b7d5caff8d92eedb82d08a7908c, and can be added to the beta 13 milestone.
