### ISSUE TITLE
OAuth Login System

### ISSUE THREAD

**Issue by MrGameMemo** [flarum/core#1926]
## Bug Report

**Current Behavior**
I cannot manage to connect / create an account on my forum (hosted on FreeFlarum). I have activated the Google & Discord Login extensions but my credentials (which are correct) do not work. Discord or Google shows an error on the login page.

**Steps to Reproduce**
1. Go to your Flarum admin
2. Click on Extensions
3. Scroll down to Discord login || Google login
4. Install the extensions and finish the setup.
5. Then, disconnect from your admin account and try creating your account from the front-end interface pop up.

**Expected Behavior**
I should be logged in with my email and join the « Members » group.

**Screenshots**
![IMG_0128](https://user-images.githubusercontent.com/34198694/68033534-2bc8a180-fcc0-11e9-9e57-d105f5a38098.jpeg)
![IMG_0129](https://user-images.githubusercontent.com/34198694/68033538-3125ec00-fcc0-11e9-9cca-cf55f5829677.jpeg)
![IMG_0130](https://user-images.githubusercontent.com/34198694/68033546-33884600-fcc0-11e9-8017-1c870f7fd7d2.jpeg)

**Environment**
- Flarum version:
 Flarum
0.1.0-beta.10PHP
7.2.24-0ubuntu0.18.04.1MySQL
10.1.41-MariaDB-0ubuntu0.18.04.1

- Website URL: https://beta.kodin-school.com
- Webserver: apache
- Hosting environment: Shared (FreeFlarum.com)
- PHP version: x.y.z
- Browser: Safari Mobile + Chrome + Firefox

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

**Possible Solution**

Let us configure directly the OAuth Link for Discord Signup & Login

**Additional Context**

**Comment by datitisev** [comment]
I aaaums the issue here is that you don't know what the redirect url should be when configuring oauth on discord/Google
..?

**Comment by tankerkiller125** [comment]
@datitisev That's what the problem appears to be, shouldn't it just be /auth/<provider>?

**Comment by datitisev** [comment]
@tankerkiller125 Yes, so for `flarum/auth-github` it is `/auth/github`, and for `fof/auth-discord` it is `/auth/discord`

@MrGameMemo I'm not sure what your possible solution here is - in any case, this would be an issue with fof/auth-discord and not core. I'm going to close this for now.
