### ISSUE TITLE
Live validation for signup form + password strength meter

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#193]
The sign up experience will be nicer with live, as-you-type validation.

What needs to be done:
- Work out which how to do the validation. I think most of it should be done with client-side logic (e.g. validate the email address, validate the characters in the username, check that another user with the same name doesn't exist).
- However we need to consider that in the future there may be things like reserved usernames defined in config. The best way to handle this would probably be to add those config values to the /forum API endpoint, and then still do client-side validation.
- (Overall, I think it's best to avoid weird API endpoints whose sole purpose is validation.)
- We also need to find the best option for a password strength meter.
- Finally, we need to design how this will look. I envision a green tick or red cross icon on the right side of each input, accompanied by a green or red border, and a tooltip on the right with more info.

**Comment by darkspotinthecorner** [comment]
On password strength: https://xkcd.com/936/ :grinning:

**Comment by luceos** [comment]
Community extension, I'm fine to keep it as is: https://extiverse.com/extension/glowingblue/password-strength
