### ISSUE TITLE
Missing compat exports in core extensions

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#1933]
This is a list of all the components that are currently not exported from the javascript of our core extensions, making them impossible to extend or reuse.

It's not exhaustive. Feel free to complete it.

## Emoji

- [ ] ~~`twemoji` library~~
- [ ] ~~`simple-emoji-map` library~~
- [ ] `components/AutocompleteDropdown`

## Suspend

- [ ] `components/SuspendUserModal.js`
- [ ] `components/UserSuspendedNotification.js`
- [ ] `components/UserUnsuspendedNotification.js`

**Comment by dsevillamartin** [comment]
This will most likely be done with the Mithril v2 rewrite of core extensions (see flarum/framework#1821).

**Comment by clarkwinkelmann** [comment]
Still relevant.

Another extension discussed recently was Mentions. It currently only exports `utils/textFormatter`, but has so many other components and helper functions that could be re-used or extended.

**Comment by clarkwinkelmann** [comment]
`twemoji` and `simple-emoji-map` should be discussed as part of flarum/issue-archive#161

**Comment by davwheat** [comment]
Suspend-related stuff will be fixed with https://github.com/flarum/suspend/pull/34

**Comment by askvortsov1** [comment]
Since we want to move ahead with https://github.com/flarum/core/issues/1933, this is now redundant in favor of https://github.com/flarum/core/issues/1933 and flarum/issue-archive#161
