### ISSUE TITLE
Add in admin panel confirm email switch

### ISSUE THREAD

**Issue by itsnunolemos** [flarum/core#1939]
## Add in admin dashboard confirm email switch

**Is your feature request related to a problem? Please describe.**
When you have one Website and Forum together, the register of the user will be confirmed by website. It's not necessary be confirmed again by the flarum.

**Describe the solution you'd like**
In admin panel have a switch for a user confirm email.

**Comment by franzliedke** [comment]
As suggested [in the PR](https://github.com/flarum/core/pull/1940#issuecomment-559290569), there is a workaround by using the API, so I am closing this for now.
