### ISSUE TITLE
Allow extensions to register their own CSRF ignored paths

### ISSUE THREAD

**Issue by andreasjacobsen93** [flarum/core#1941]
## Feature Request

As discussed in https://github.com/flarum/core/pull/1925 it is sometimes needed to bypass the CSRF check on a specific route, due to some external limitations.

We are using a sign-on service provider with php saml, which returns to our site with a POST request containing metadata used to verify the user. Therefore we need our extension to be able to register a route to be ignored by CSRF check.

Another option we looked at is trying to add a middleware that sets the bypass CSRF value, but it seems middleware cannot be registered in a specific order from an extension and therefore cannot run before the CSRF check.

**Comment by luceos** [comment]
link #1919

**Comment by franzliedke** [comment]
Hi @andreasjacobsen93, would you rather have the more flexible middleware extension mechanism (please check out the proposal in #1957), or the one proposed above?

What would your middleware do? Check path and HTTP method and - for a match - set the `bypassCsrfToken` attribute on the request?

**Comment by franzliedke** [comment]
(I tend to keep this ticket open for the time after 0.1, and implement #1957 quickly so that there is at least a workaround in place.)

**Comment by andreasjacobsen93** [comment]
The PR in https://github.com/flarum/core/pull/1925 seems to be the quickest solution, we already patch our core with it since we rely on the functionality.
The proposal in https://github.com/flarum/core/issues/1957 is a more flexible solution and not only limited to CSRF check. That way we would need to insert a middleware before the CSRF check to set the bypassCsrfToken attribute

**Comment by askvortsov1** [comment]
As this will be flexibly supported in Beta 12 through middleware extenders, should this be closed?

Also, @andreasjacobsen93  if y'all are interested in a SAML solution that doesn't require patching core to work, please check out https://github.com/askvortsov1/flarum-saml. If it's missing any features you need, let me know, and I'd be happy to consider them.

**Comment by franzliedke** [comment]
See [my comment above](https://github.com/flarum/core/issues/1941#issuecomment-570596759). 

If this becomes a common thing, I'd rather have a dedicated mechanism than everyone adding another middleware just to add a request attribute for a single route...
