### ISSUE TITLE
utf8-url encoded username url support (simple solve)

### ISSUE THREAD

**Issue by shangjiaxuan** [flarum/core#1949]
#  Feature Request

**Is your feature request related to a problem? Please describe.**
I am having problem if I manually allow usernames to contain spaces and non-ASCII characters and use a link to go to the user page, it would trigger a 404 error (url encoded strings are not converted).

**Describe the solution you'd like**
A detailed description of your proposed solution. Include:
- How the feature would work/behave
- Any potential drawbacks
- Maybe a screenshot, design, or example code

Modify the following kines in function `protected function data(ServerRequestInterface $request, Document $document)` in `src/Api//Controller/ShowUserController.php` 

    if (! is_numeric($id)) {
        $id = $this->users->getIdForUsername($id);
    }

to

    if (! is_numeric($id)) {
        $id = $this->users->getIdForUsername(urldecode($id));
    }

Tested on my forum at [this site](https://forum.nepfan.club). As shown here in Firefox:
![test1](https://forum.nepfan.club/assets/files/2019-12-03/1575405700-468970-done.png)
![test2](https://forum.nepfan.club/assets/files/2019-12-03/1575405711-318968-done2.png)

**Justify why this feature belongs in Flarum's core, rather than in a third-party extension**
This changes the behavior of core api. Also the overhead involved with a decode on strings that are not percent-encoded may not be too high (not metered). This would allow removing the restriction on username characters (spaces allowed as encoded `%20` in url request) at least on the user display side.

**Describe alternatives you've considered**
Probably implement this somewhere in a extension.

**Comment by shangjiaxuan** [comment]
`grep -r 'numeric'` on `src` directory gives only this and a line in `./Util/Str.php`, and grep -r 'alpha' only gives `./Util/Str.php`. Most likely there won't be security issues involved.

**Comment by shangjiaxuan** [comment]
Note: Using space in username breaks post cross referencing. Allowing space is more tricky here.

**Comment by shangjiaxuan** [comment]
It seems that [this post](https://discuss.flarum.org/d/915-spaces-non-ascii-characters-in-usernames/24) mentions a rather good solution to the username with `@mention` system by recognizing `@"mention user"`. Making this and changing a bit how UserValidater.php works (allow more characters) should allow an complete extension that allow spaces, non-ascii and other characters in the username.

**Comment by luceos** [comment]
related flarum/framework#1356

**Comment by franzliedke** [comment]
More cross-reference: flarum/framework#557 and flarum/issue-archive#254

**Comment by tankerkiller125** [comment]
I'm not a huge fan of allowing space, but I did discover that `/^[a-z0-9\p{L}\p{N}_-]+$/i` as a regex for the validator would allow unicode characters to be used as a username. We would need to figure out proper slugging though.
