### ISSUE TITLE
Ask for confirmation when deleting a post

### ISSUE THREAD

**Issue by matteocontrini** [flarum/core#1966]
## Feature Request

I've found that quite a few users on my forum (soft)delete posts by mistake and sometimes don't even realize they do that.

I think this could be improved by asking for confirmation when deleting/hiding a post. I don't think it would be annoying, since deleting a post is not something you do very often.

It could also be an option, actually, depending on how people feel this issue.

**Comment by timas130** [comment]
Created a PR, hope it will be reviewed soon.

**Comment by franzliedke** [comment]
Fixed in #2135.
