### ISSUE TITLE
Optional route parameters cannot be filled via the url builder

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#1972]
## Bug Report

**Current Behavior**

    app(UrlGenerator::class)->to('forum')->route('discussion', ['id' => 1]);
    // http://flarum.localhost/d/1

    app(UrlGenerator::class)->to('forum')->route('discussion', ['id' => 1, 'near' => 5]);
    // http://flarum.localhost/d/1

**Expected Behavior**

    app(UrlGenerator::class)->to('forum')->route('discussion', ['id' => 1]);
    // http://flarum.localhost/d/1

    app(UrlGenerator::class)->to('forum')->route('discussion', ['id' => 1, 'near' => 5]);
    // http://flarum.localhost/d/1/5

**Possible Solution**

This feature can probably be implemented without too many troubles inside `RouteCollection`.

Currently all variations of the route (first with a single parameter, then with two parameters) are parsed by `fast-route`, and added to both the routing and the `$reverse` array.

The limitation is that we currently always take the first route matching the name from the `$reverse`, whereas the one with the optional parameter is likely in second place.

https://github.com/flarum/core/blob/d492579638fb52dafbfe65f1f36a95eb6047f7f3/src/Http/RouteCollection.php#L91

We should probably try replacing the parameters in each of the `$this->reverse[$name]` matches, then return the one where we were able to replace the most tokens.

Or alternatively, index the reverse array based not only on name, but also on the parameter names or count in order to pick the correct reverse route in a single access.

Once implemented, we should use the route builder in places where it's currently skipped for this very reason https://github.com/flarum/subscriptions/blob/master/views/emails/newPost.blade.php#L6

**Additional Context**

Discussed on the forum here https://discuss.flarum.org/d/22573-how-to-navigate-to-a-particular-post-in-flarum

**Comment by askvortsov1** [comment]
We probably still want this
