### ISSUE TITLE
Open links in a new tab

### ISSUE THREAD

**Issue by therealsujitk** [flarum/core#1973]
### Feature Request

I think it would be more convenient if links on the forum opened in a new tab by default.

**Comment by tankerkiller125** [comment]
This was heavily discussed in another ticket at one point and the decision was not to open new tabs. There is an extension on discuss that allows you to choose how to open links though

**Comment by datitisev** [comment]
Both options were discussed in https://github.com/flarum/core/issues/859, and the change was made to open them in the current tab.

You can install the [`franzl/flarum-open-links-in-new-tab`](https://flagrow.io/extensions/franzl/flarum-open-links-in-new-tab) extension to open links in new tabs.
