### ISSUE TITLE
Upgrade s9e/text-formatter

### ISSUE THREAD

**Issue by tankerkiller125** [flarum/core#1979]
Creating this ticket so we don't lose it in the forums.

## Upgrade Request
s9e/text-formatter is very behind currently (^1.2.0, current version is 2.2.3) an upgrade should be made to bring this up to date and determine what has changed so that the upgrade can be performed. The new version brings in several enchantments (such as customization over code highlighting)

**Comment by luceos** [comment]
I love it when we ship magic. Enchanting forums ought to be our new tagline.

**Comment by tankerkiller125** [comment]
All open source devs ship magic, all software is magic, just like all hardware is magic, you just can't let the magic blue smoke out.

**Comment by franzliedke** [comment]
We could do this in two steps:
- Upgrade to the latest 1.x release first (beware of API changes in [v1.3.0](https://github.com/s9e/TextFormatter/blob/master/CHANGELOG.md#130-2018-09-20))
- Then upgrade to the latest 2.x release - taking care of all breaking changes across core and extensions, if any

**Comment by tankerkiller125** [comment]
@franzliedke Reviewing the formatter code it appears that 1.3.0 may already be used (just not explictly) based on the fact that `$configurator->javascript->exports` is set instead of `$configurator->javascript->exportsMethods` along with the fact that the caret operator is used in `composer.json` I think a migration to the 2.x release is the next step.
