### ISSUE TITLE
Markdown sometimes parsing as emojis

### ISSUE THREAD

**Issue by jberlyn** [flarum/core#198]
When certain markdown syntax is used within a discussion, it will conflict with the emoji implementation. For example, appending bold syntax (**) with a proceeding colon (:) will try to show a kissing emoji.

**Comment by franzliedke** [comment]
@s9e Can we prioritize the order of inline parsing?

**Comment by tobscure** [comment]
Nah we just need to tweak some settings. See https://github.com/s9e/TextFormatter/issues/12

**Comment by s9e** [comment]
@franzliedke Not in this instance. Markup is processed in the same order it appears in the text and in `:**` the emoticon starts before the other markup.

AFAICT the only workarounds are in userland, e.g. by using `__` instead of `**`.

**Comment by tobscure** [comment]
See flarum/emoji#1
