### ISSUE TITLE
Flarum Beta 10, 11 Not Support in PHP 7.4.1

### ISSUE THREAD

**Issue by LianSheng197** [flarum/core#1980]
## Follow Official Installation Tutorial
https://flarum.org/docs/install.html

## Bug Report

**Current Behavior**
Flarum beta 10, 11 (or all...?) not support in PHP 7.4.1

**Steps to Reproduce**

> 1. Using PHP 7.4.1.
> 2. `composer create-project flarum/flarum . --stability=beta` 
>  or 
> `composer create-project flarum/flarum:v0.1.0-beta.10 . --stability=beta`
> 3. Set all about site setting (httpd-vhosts.conf, httpd.conf).
> 4. Open the browser, and get the **ERROR**:
> ```
> Notice: Trying to access array offset on value of type null in C:\xampp\htdocs\ft\vendor\illuminate\support\ServiceProvider.php on line 84
> ...
> ``` 
> Full error like this:
> ![image](https://user-images.githubusercontent.com/18535495/73414878-29bbc080-434b-11ea-9b10-7481a97893d2.png)

**Expected Behavior**
If using PHP 7.3.6, the installer is work.
![image](https://user-images.githubusercontent.com/18535495/73415182-16f5bb80-434c-11ea-8dc1-a559c0226b79.png)

**Environment**
- Flarum version: v0.1.0-beta.10, v0.1.0-beta.11
- Website URL: localhost
- Webserver: Apache
- Hosting environment: localhost
- PHP version: 7.3.6, **7.4.1**
- Browser: Google Chrome 79.0.3945.130

```
Output of "php flarum info", run this in terminal in your Flarum directory.

C:\xampp\htdocs\ft>php --version
PHP 7.4.1 (cli) (built: Dec 17 2019 19:24:02) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

C:\xampp\htdocs\ft>php flarum info
PHP Notice:  Trying to access array offset on value of type null in C:\xampp\htdocs\ft\vendor\illuminate\support\ServiceProvider.php on line 84

Notice: Trying to access array offset on value of type null in C:\xampp\htdocs\ft\vendor\illuminate\support\ServiceProvider.php on line 84


  Command "info" is not defined.  

```

**Comment by franzliedke** [comment]
Nice catch, thanks for the report!!!

Can you try out [this change](https://github.com/flarum/core/commit/2465a39c1c76f15761318c280844d1892a19b782) and see whether that works? (You will find the appropriate files in the `vendor/flarum/core` directory.

**Comment by LianSheng197** [comment]
It works, but... 
Only for the installer page... xDDD

Here is error from Flarum installing:
![image](https://user-images.githubusercontent.com/18535495/73555375-7822a980-4488-11ea-86ac-1b2206661659.png)

Hell of "Trying to access array offset on value of type null"

[It's seems like PHP 7.4 change and deprecation.](https://stitcher.io/blog/new-in-php-74#invalid-array-access-notices-rfc)

***
#### Test Environment

- Flarum version: beta.10
- PHP version: 7.4.1

**Comment by franzliedke** [comment]
Thanks for your help!!!
We will have to switch to another LESS library, it seems, but right now that's [harder than I thought](https://github.com/wikimedia/less.php/pull/17#issuecomment-580886403).

In the meantime - as a hack - can you add this line after the opening PHP tag of `public/index.php`?

~~~php
error_reporting(E_ALL ^ E_NOTICE);
~~~

**Comment by LianSheng197** [comment]
Thank you!
I tried to reinstall beta.10 with PHP 7.4.1 and just change [this ](https://github.com/flarum/core/issues/1980#issuecomment-580765921)and [this](https://github.com/flarum/core/issues/1980#issuecomment-580887951), then the installation worked perfectly, without any extra errors throwing. 

Looking forward to future updates: D

**Comment by franzliedke** [comment]
I've [sent a pull request](https://github.com/wikimedia/less.php/pull/24) to the Wikimedia less.php fork to add back support for PHP 7.1. Let's hope they accept this. :smile:

**Comment by franzliedke** [comment]
Okay, I hope [this PR](https://github.com/flarum/core/pull/1985) fixes all problems. :smiley:
