### ISSUE TITLE
Dead links for "contributing" documentation

### ISSUE THREAD

**Issue by fzyzcjy** [flarum/core#1984]
1. the "Run the test suite with vendor/bin/phpunit in the relevant package folder.
See here for more information about testing in Flarum." link in https://flarum.org/docs/contributing.html#development-workflow

Not only cannot I click that link, but I also cannot find *where does the existing tests locate*... Could you please tell me so I can mimic the existing tests to write mine?

2. the "we recommend that you read the Concepts documentation in the Extension docs to understand a bit more about how Flarum works" in https://flarum.org/docs/contributing.html#what-to-work-on

Looking forward to contributing!

**Comment by tankerkiller125** [comment]
Both of these links are working for me properly on Chrome, what browser are you using?

**Comment by fzyzcjy** [comment]
@tankerkiller125 Yes I mean the link inside the webpage, i.e.

1. https://flarum.org/docs/link-to-core/tests/
2. https://flarum.org/docs/extend/concepts.html

So could you please tell me where the tests locates in the source code, so I can mimic the existing tests to write mine?

**Comment by tankerkiller125** [comment]
All current Flarum test are located [here](https://github.com/flarum/core/tree/master/tests) as far as running test you need to run `composer run test:setup` in the root core directory and then from there you can use `composer run test` to run the test.

**Comment by fzyzcjy** [comment]
OK! Er... there are only a few tests...?

**Comment by tankerkiller125** [comment]
Correct, our test game isn't that great at the moment, it's something we are currently working on.

**Comment by fzyzcjy** [comment]
Get it, thanks
