### ISSUE TITLE
not support Arabic letters

### ISSUE THREAD

**Issue by djoudi** [flarum/core#1990]
## Bug Report
![image](https://user-images.githubusercontent.com/152725/74097624-7e5ef880-4b0e-11ea-8c5d-776f2e1ef639.png)

**Comment by tankerkiller125** [comment]
This is known, currently usernames are validated against the `/^[a-z0-9_-]+$/i` regex which only allows latin characters, dashes, numbers, and underlines. Changing to the `alpha_dash` validator would correct this issue. However the Flarum slugger needs to be adjusted before it makes sense to allow non latin characters in names.
