### ISSUE TITLE
Problems with css calc in custom style

### ISSUE THREAD

**Issue by NSD4rKn3SS** [flarum/core#1996]
## Bug Report

**How to Reproduce**
Adding this line (1.) to your custom style settings will be translated to this (2.) when your style gets loaded on the site.
1.) .item:first-child { width: calc(100% - 800px) }
2.) .item:first-child { width: calc(-700%); }
Viewing the same line in the settings after a save shows the attribute got properly saved.

**Expected Behavior**
Custom CSS should be loaded in as is.

**Screenshots**

**Environment**
- Flarum version: 0.1.0-beta.11.1
- Webserver: Ubuntu | Apache 2.4.18
- PHP version: 7.3.14-6

**Comment by tankerkiller125** [comment]
This is the expected behavior from the style options as it uses LESS compiling. Please reference https://coderwall.com/p/yyou-q/css3-calc-in-less-css for data escaping in LESS.
