### ISSUE TITLE
Test Mail Button

### ISSUE THREAD

**Issue by askvortsov1** [flarum/core#2004]
## Feature Request

**Is your feature request related to a problem? Please describe.**
One very useful feature that I've seen on other platforms (such a discourse) is the ability to test email configuration from the admin panel. I think this should be included to allow admins to easily test their email configuration when setting up the forum.

**Describe the solution you'd like**
Add:
- A test form on the mail configuration admin pane. This would include the test email recipient and their email address, and would ping the endpoing.
- An API endpoint (or alternate mechanism) that sends an email with the experimental test configuration, and returns a success message or an error message

**Justify why this feature belongs in Flarum's core, rather than in a third-party extension**
This could be a very useful tool for ensuring that email configuration works properly, and bugfixing it when it doesn't. It would only really be used once, and would be useful to pretty much every starting forum, and has relatively small overhead, so I think core would be (eventually) a good place.

**Comment by datitisev** [comment]
Is this a duplicate of #1655 ?

**Comment by askvortsov1** [comment]
Oh my I'm on a roll with these duplicate posts, this is like my 3rd this week!
