### ISSUE TITLE
Cannot reorder secondary tag(s)

### ISSUE THREAD

**Issue by PeopleInside** [flarum/core#2007]
## Bug Report

**Current Behavior**

Cannot reorder secondary tags.

**Steps to Reproduce**
1. Create three secondary tag
2. Try to change the order of the list, you cannot: elements can be dragged but the position is not saved

**Expected Behavior**
Be able to decide the secondary tag(s) order

**Screenshots**

![SharedScreenshot](https://user-images.githubusercontent.com/5006150/74601965-21ca8300-50a4-11ea-8550-6b8c5710c6bf.jpg)

**Environment**
- Flarum version: 0.1.0-beta.11.1
- Webserver: [Apache]
- Hosting environment: [vps]
- PHP version: 7.3.11
- Browser: [Firefox 73.0 Windows 10]

```
Output of "php flarum info", run this in terminal in your Flarum directory.

Flarum core 0.1.0-beta.11.1
PHP version: 7.3.11
Loaded extensions: Core, date, libxml, pcre, dom, fileinfo, filter, hash, json, SPL, bz2, posix, Reflection, session, SimpleXML, standard, xml, xmlreader, xmlwriter, bcmath, openssl, calendar, ctype, curl, dba, mbstring, ftp, gd, gettext, gmp, iconv, imap, intl, ldap, exif, memcached, zlib, pcntl, PDO, pdo_sqlite, shmop, soap, sockets, sqlite3, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlrpc, xsl, zip, Phar, mysqlnd, mysqli, pdo_mysql, ionCube Loader, Zend OPcache
+----------------------+----------------+--------+
| Flarum Extensions    |                |        |
+----------------------+----------------+--------+
| ID                   | Version        | Commit |
+----------------------+----------------+--------+
| flarum-approval      | v0.1.0-beta.8  |        |
| flarum-bbcode        | v0.1.0-beta.8  |        |
| flarum-emoji         | v0.1.0-beta.10 |        |
| flarum-lang-english  | v0.1.0-beta.11 |        |
| flarum-flags         | v0.1.0-beta.10 |        |
| flarum-likes         | v0.1.0-beta.9  |        |
| flarum-lock          | v0.1.0-beta.9  |        |
| flarum-markdown      | v0.1.0-beta.10 |        |
| flarum-mentions      | v0.1.0-beta.10 |        |
| flarum-statistics    | v0.1.0-beta.9  |        |
| flarum-sticky        | v0.1.0-beta.9  |        |
| flarum-subscriptions | v0.1.0-beta.9  |        |
| flarum-suspend       | v0.1.0-beta.10 |        |
| flarum-tags          | v0.1.0-beta.11 |        |
| flarum-pusher        | v0.1.0-beta.9  |        |
+----------------------+----------------+--------+
```

**Possible Solution**

**Additional Context**

**Comment by datitisev** [comment]
Duplicate of #1549 and #1292, I think.

Those issues were closed because this is "intended behavior", but we may want to change that tbh.

**Comment by PeopleInside** [comment]
Is so hard make possible reorder also secondary tag?
Why not? :S :( I cannot reopen this issue.

**Comment by datitisev** [comment]
It is possible. The question is if we want this - probably yes, to be honest.

**Comment by PeopleInside** [comment]
If you will not I suppose users will start to ask for support. I imagine a community with many secondary tag and the impossibility to reorder. Seems a great issue.
