### ISSUE TITLE
Installation if already installed

### ISSUE THREAD

**Issue by askvortsov1** [flarum/core#2019]
## Feature Request

**Is your feature request related to a problem? Please describe.**
If config.php is deleted, flarum will put itself in installation mode. However, when you try and enter credentials for the database, it will try to create new tables (which it can't because tables are already there) and error. There should be a way to escape this without having to manually create and fill a config.php file.

**Describe the solution you'd like**
If, while connecting to the database Flarum finds all the tables already there, it can just create a config.php and assimilate into the existing database.

**Justify why this feature belongs in Flarum's core, rather than in a third-party extension**
It's to do with installation, which is core.

**Comment by tankerkiller125** [comment]
How often does this actually happen though? I feel like adding a bunch more logic to the setup command just to handle an issue that will rarely happen seems like overkill, especially since the config file is only a couple of lines and the issue is super easily resolved.

**Comment by askvortsov1** [comment]
I feel like this is a minor thing, but could be useful for upgrading issue. Ie if your entire skeleton gets wiped, it's easier to recover.

I'm not sure that we need a full feature tbh, I agree that could be overkill. However, while for technical users "table flarum_migrations already exists" is very clear, non technical users might not exactly understand what that means and how they should deal with it. And after all, the target audience of the visual installer is just as much non-technical users

**Comment by bmalex88** [comment]
I doubt non technical users will dare install flarum or even use command line based tools. They can go to WP or other software that install itself when you blink twice

**Comment by askvortsov1** [comment]
One thing to note here is that WordPress also has a config.php file.

As to the actual installation process, there's a lot of ongoing discussion about making flarum easier to install (possibly as a one click install on shared hosting), but I believe that the consensus is waiting until after stable to start partnering with shared hosts

**Comment by bmalex88** [comment]
I remember having started some discussions about installation on shared hosting a few years ago (because I had to install it on a Vagrant machine then migrate everything to the shared server) but now I believe that before a solution is found every shared hosting plan will provide a SSH terminal already.
A web installer as a separate tool is probably what will work best

**Comment by askvortsov1** [comment]
So I was able to build something that actually works (I'm proposing that something like that be officially adopted, but that conversation is on hold): https://github.com/askvortsov1/flarum-ez-install. It installs, updates, etc flarum in one line of code.

**Comment by franzliedke** [comment]
> There should be a way to escape this without having to manually create and fill a config.php file.

To be honest, I don't understand where this entire request comes from. Why did you even land in this situation? Is this relevant for your dev setup?

Detecting whether "all tables are already there" is far from trivial, at least with our current migration-based approach for the installer, and more so when you take bundled extensions into account.

I am very open for adding better error messages for some of these situations (e.g. the database already contains tables - when no prefix was configured), but I find it hard to understand the use-case for the scenario brought up here.

**Comment by datitisev** [comment]
I think this situation comes up when restoring from a backup, for example. Or migrating the database from another installation, and all you need is for Flarum to detect the current installation - instead, you have to install Flarum and then replace the DB.

**Comment by askvortsov1** [comment]
Tbh, I'm not 100% sure what I was trying to fix when I opened this, but honestly it's about as low priority as it gets when it comes to issues we need to look at.

**Comment by franzliedke** [comment]
Okay then. If we ever come back to this, I'd say it wouldn't belong to the `install` command then. Setting up the database is pretty much its biggest task, so a special mode where that essential part is gone doesn't seem right to me. :stuck_out_tongue_winking_eye: 

Let's bow to the stale bot.
