### ISSUE TITLE
Tags list page might show a "last discussion" that doesn't have the tag

### ISSUE THREAD

**Issue by matteocontrini** [flarum/core#2022]
## Bug Report

**Current Behavior**

In the tags page, it can happen that under a primary tag the "last discussion" is a discussion that actually doesn't have the primary tag.

**Steps to Reproduce**
1. Create a discussion with tag A
2. Remove tag A from the discussion
3. Browse to yourforum.com/tags and see that the last discussion is shown at the bottom of tag A's box

**Expected Behavior**

A discussion that doesn't have the tag shouldn't be shown as the last discussion that has the tag, even if it had in the past.

**Screenshots**

![immagine](https://user-images.githubusercontent.com/2164763/75186785-f18c7f80-5748-11ea-8de3-51f60a06d337.png)

![immagine](https://user-images.githubusercontent.com/2164763/75186800-f9e4ba80-5748-11ea-86a6-90e6f9f61bfc.png)

**Environment**
- Flarum version: 0.1.0-beta.11.1
- Website URL: local
- PHP version: 7.2.12
- Browser: Firefox 73

```
Flarum core 0.1.0-beta.11.1
PHP version: 7.2.12
Loaded extensions: Core, bcmath, calendar, ctype, date, filter, hash, iconv, json, SPL, pcre, readline, Reflection, session, standard, mysqlnd, tokenizer, zip, zlib, libxml, dom, PDO, bz2, SimpleXML, xml, wddx, xmlreader, xmlwriter, openssl, curl, fileinfo, gd, gettext, gmp, intl, imap, ldap, mbstring, exif, mysqli, Phar, pdo_mysql, pdo_sqlite, soap, sockets, xmlrpc, xsl
+----------------------+----------------+--------+
| Flarum Extensions    |                |        |
+----------------------+----------------+--------+
| ID                   | Version        | Commit |
+----------------------+----------------+--------+
| flarum-approval      | v0.1.0-beta.8  |        |
| flarum-bbcode        | v0.1.0-beta.8  |        |
| flarum-emoji         | v0.1.0-beta.10 |        |
| flarum-lang-english  | v0.1.0-beta.11 |        |
| flarum-flags         | v0.1.0-beta.10 |        |
| flarum-likes         | v0.1.0-beta.9  |        |
| flarum-lock          | v0.1.0-beta.9  |        |
| flarum-markdown      | v0.1.0-beta.10 |        |
| flarum-mentions      | v0.1.0-beta.10 |        |
| flarum-statistics    | v0.1.0-beta.9  |        |
| flarum-sticky        | v0.1.0-beta.9  |        |
| flarum-subscriptions | v0.1.0-beta.9  |        |
| flarum-suspend       | v0.1.0-beta.10 |        |
| flarum-tags          | v0.1.0-beta.11 |        |
| fof-nightmode        | 0.4.0          |        |
| fof-byobu            | 0.4.1          |        |
+----------------------+----------------+--------+
Base URL: http://flarum11.localhost
Installation path: C:\wamp64\www\flarum11
Debug mode: off
```

This might be the intended behaviour, but it's unideal because if a discussion doesn't have a primary tag anymore it means it shouldn't have had it in the first place, and thus shouldn't be shown in the Tags page.

**Comment by davwheat** [comment]
Can reproduce!

**Comment by askvortsov1** [comment]
Will be fixed in

https://github.com/flarum/tags/pull/78

**Comment by matteocontrini** [comment]
Thanks Alexander!
