### ISSUE TITLE
Registration and login placeholders are not visible in some mobile browsers

### ISSUE THREAD

**Issue by studosi-fer** [flarum/core#2028]
## Bug Report

**Current Behavior**
When using Google Chrome and MIUI 11 browsers on various Androids, the registration and login input boxes aren't displaying placeholders (which makes it hard to know which field is for what). So far, this has been confirmed not to happen on Firefox Android, and it doesn't happen on Chrome for desktop no matter the zoom or window size (not CSS related, therefore).

**Steps to Reproduce**
Go to a Flarum forum and try to register or login through Chrome for Android or MIUI 11 browser.
Input fields will be blank, without placeholders.

**Expected Behavior**
Placeholders in input fields for registration and login are shown.

**Screenshots**
Chrome

![image](https://user-images.githubusercontent.com/60950091/75485933-ea18e080-59ab-11ea-8db9-c9183a2546a7.png)

MIUI 11

![image](https://user-images.githubusercontent.com/60950091/75485960-f1d88500-59ab-11ea-8e25-a28073aa0dcf.png)

Firefox

![image](https://user-images.githubusercontent.com/60950091/75485975-fac95680-59ab-11ea-9507-a17248b4052c.png)

**Environment**
- Flarum version: 0.1.0-beta.10
- Website URL: http://ka.mpus.eu
- Webserver: Apache
- Hosting environment: VPS
- PHP version: 7.1.33-1+ubuntu
- Browser: Chrome Android 80.0.3987.119, MIUI Browser V11.4.3-g

```
Output of "php flarum info", run this in terminal in your Flarum directory.

Flarum core 0.1.0-beta.10
PHP version: 7.1.33-1+ubuntu19.10.1+deb.sury.org+6
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache
+------------------------------+----------------+--------+
| Flarum Extensions            |                |        |
+------------------------------+----------------+--------+
| ID                           | Version        | Commit |
+------------------------------+----------------+--------+
| flarum-bbcode                | v0.1.0-beta.8  |        |
| flarum-emoji                 | v0.1.0-beta.10 |        |
| flarum-lang-english          | v0.1.0-beta.10 |        |
| flarum-flags                 | v0.1.0-beta.9  |        |
| flarum-lock                  | v0.1.0-beta.9  |        |
| flarum-markdown              | v0.1.0-beta.10 |        |
| flarum-mentions              | v0.1.0-beta.10 |        |
| flarum-statistics            | v0.1.0-beta.9  |        |
| flarum-sticky                | v0.1.0-beta.9  |        |
| flarum-subscriptions         | v0.1.0-beta.9  |        |
| flarum-suspend               | v0.1.0-beta.9  |        |
| kilowhat-mailing             | 0.2.0          |        |
| noriods-auto-more            | 0.3.0          |        |
| clarkwinkelmann-emojionearea | 0.2.0          |        |
| antoinefr-money              | v0.7.0         |        |
| dem13n-nickname-changer      | 0.1.6          |        |
| antoinefr-online             | 0.4.0          |        |
| fof-byobu                    | 0.3.4          |        |
| fof-formatting               | 0.1.2          |        |
| fof-ignore-users             | 0.1.4          |        |
| fof-masquerade               | 0.3.3          |        |
| fof-nightmode                | 0.3.0          |        |
| fof-polls                    | 0.1.1          |        |
| fof-profile-image-crop       | 0.1.1          |        |
| fof-reactions                | 0.1.0          |        |
| fof-terms                    | 0.4.0          |        |
| reflar-latex                 | 0.2.0          |        |
| reflar-level-ranks           | 1.2.1          |        |
| flarum-tags                  | v0.1.0-beta.10 |        |
| flagrow-upload               | 0.7.1          |        |
| avatar4eg-transliterator     | 0.4.0          |        |
| zerosonesfun-bbbbcode        | 2.9.3          |        |
| fof-linguist                 | 0.4.1          |        |
| fof-gamification             | 0.1.6          |        |
+------------------------------+----------------+--------+
Base URL: https://ka.mpus.eu
Installation path: /var/www/kampus_test
Debug mode: off
```

**Possible Solution**
Might have to do with mobile Chromium?

**Additional Context**
I have done some custom CSS on the site but it seems unlikely that is the problem since different platforms and different browsers on the same platform work as intended.

**Comment by datitisev** [comment]
That feels like a bug with the browser or your custom styles. The placeholder attribute on the inputs should be set.

Works fine for me on Android Chrome at https://nightly.flarum.site.

**Comment by tankerkiller125** [comment]
This also works for me on nightly, beta and my own sites. I feel like it's either the customizations or an extension doing this. Not core.

**Comment by studosi-fer** [comment]
Found out the custom CSS that's messing it up:

```
::-webkit-input-placeholder
{ color: #fff !important; }
```

The question is, though - why does it work on some browsers, and not on others?

**Comment by tankerkiller125** [comment]
Correct, firefox does not use webkit, it's prefix for css is moz

**Comment by studosi-fer** [comment]
> Correct, firefox does not use webkit, it's prefix for css is moz

Then that probably settles it, I'll close it since this is just a CSS blunder of mine.
