### ISSUE TITLE
Extensions page on Firefox is bugged out

### ISSUE THREAD

**Issue by datitisev** [flarum/core#2029]
**Browser: Firefox 73**
![image](https://user-images.githubusercontent.com/6401250/75493147-4584a780-5987-11ea-9c06-1c15c3dd598d.png)

**Browser: Chromium (Vivaldi)**
![image](https://user-images.githubusercontent.com/6401250/75493261-795fcd00-5987-11ea-9b40-0c9c2b887901.png)

**Comment by clarkwinkelmann** [comment]
Oddly this was fine on my beta 11 until now. I just checked, and it's broken on my beta 11 install. I am on Firefox 73. Not sure if it was just updated or if I already had that version in the past.

It's very inconsistent. It's broken when I load the page, but if I resize the window, then resize it again to the original 1920px width, sometimes it fixes itself. Sometimes it doesn't.

When I load the page in adaptive view, even with the same width, it seems like the problems appears less frequently.

This sounds like something broke in a Firefox update, nothing to do with a change in Flarum.

**Comment by tankerkiller125** [comment]
The bug is even weirder in Firefox 74 Beta 9, it loads incorrectly originally but if you just wait about 10 seconds it goes back to the way it should be. I've been unable to figure out why this is though.

**Comment by clarkwinkelmann** [comment]
I also noticed the jump after a few seconds, or when I start scrolling. I suspect the jump might have something to do with the left navigation becoming affix or something.
