### ISSUE TITLE
Selected tags are hidden in the tags modal on mobile

### ISSUE THREAD

**Issue by matteocontrini** [flarum/core#2030]
## Bug Report

**Current Behavior**

The list of selected tags in the "edit tags" modal is hidden (shifted outside of the box) when browsing from mobile. This appears to happen indipendently from the number of tags that have been chosen. Reproducible on beta.flarum.site.

**Steps to Reproduce**

Using a mobile browser (tested on Chrome for Android):

1. Tap the "create discussion" button
2. In the post composer, tap "Choose Tags"
3. Select a tag
4. Notice that the tag name is cut

**Expected Behavior**

Tags should be visible.

**Screenshots**

![immagine](https://user-images.githubusercontent.com/2164763/75565527-6532d300-5a4e-11ea-9a69-8831037e2308.png)

**Environment**
- Flarum version: 0.1.0-beta.11.1
- Website URL: https://beta.flarum.site
- Browser: Chrome 80 Android

**Comment by askvortsov1** [comment]
Fixed in https://github.com/flarum/tags/pull/83, not stale.
