### ISSUE TITLE
Integration Testcase: adding extenders after app has been initialized doesn't work.

### ISSUE THREAD

**Issue by askvortsov1** [flarum/core#2035]
## Bug Report

**Current Behavior**
Extenders are only applied when the app is being initialized for the first time in the testcase. This means that if extenders are added after any database calls have been made, everything breaks

**Comment by franzliedke** [comment]
Ignoring this for now, as a workaround exists. See https://github.com/flarum/core/pull/2036#issuecomment-595734221.
