### ISSUE TITLE
Make API access tokens properly expire

### ISSUE THREAD

**Issue by tobscure** [flarum/core#204]
There is an expired_at column in the table, but I don't think we actually check it currently.

Also we need to delete old records every so often – cron is obviously best for this, but won't be available on all shared hosts. Could we emulate it by running an AJAX request every few hours on some lucky person's client?

**Comment by franzliedke** [comment]
I don't think we can emulate that with an AJAX call.

Laravel does something similar with a "lottery" setting for cleaning up old sessions: it configures the chances of running the garbage collection. That should do the trick, no?

Other options: creating a secret URL that could be used with "poor man's cron" tools or RSS feed readers ;)

**Comment by tobscure** [comment]
The lottery thing sounds good.

**Comment by tobscure** [comment]
I've implemented code to validate the expiry date on access (and email/password) tokens. Made #217 for the lottery.
