### ISSUE TITLE
Automatically hide post if has n flags

### ISSUE THREAD

**Issue by askvortsov1** [flarum/core#2050]
## Feature Request

**Is your feature request related to a problem? Please describe.**
If a post has an abnormally high number of flags, it should probably not be on the forums. 

**Describe the solution you'd like**
When a post receives n flags, with n configurable in extension settings, automatically hide the post until a moderator can review.

**Justify why this feature belongs in Flarum's core, rather than in a third-party extension**
It's a change to the flags extension.

**Describe alternatives you've considered**
- If a post has an outlier number of flags (statistics, yay!), automatically hide it until a moderator can review. This would avoid a setting, but would require a lot of calculations that wouldn't scale well.

**Comment by imorland** [comment]
I like this idea, very much. One question, would there also be an option to disable the auto-hide of the post, is the site admin required?

**Comment by askvortsov1** [comment]
@imorland if we're adding admin settings to manage the threshold, we could also add in a toggle.
