### ISSUE TITLE
Page title not changing correctly

### ISSUE THREAD

**Issue by despecial** [flarum/core#2060]
## Bug Report

**Current Behavior**
Switching from discussion list view or a single post to profile/private discussions won't change the page title. It stays the same.

**Steps to Reproduce**
1. Go to a single post or discussion overview
2. Click on your profile name (or private discussions)
3. Check the page title

**Expected Behavior**
Page title should change to the current page view title

**Screenshots**

**Comment by timas130** [comment]
#### Screenshots

![bug5](https://user-images.githubusercontent.com/20511387/77628663-637b0300-6f59-11ea-9a95-6994d2cd2749.gif)

**Comment by Yalfoosh** [comment]
Reproduced both on a vanilla local and live beta12 Flarum.

**Comment by askvortsov1** [comment]
We still want this

**Comment by askvortsov1** [comment]
Fixed as a side effect of #2255
