### ISSUE TITLE
User's discussion page post excerpts added by flarum/sticky

### ISSUE THREAD

**Issue by datitisev** [flarum/core#2066]
When viewing a user's discussions (`/u/<id>/discussions`) the excerpts only appear when flarum/sticky is enabled - even though the code to show them is in core.

The following lines make this occur: https://github.com/flarum/sticky/blob/0a25c0cab7075ea708c244ad838e60782259dbda/js/src/forum/addStickyExcerpt.js#L7-L9

This should probably be in core as
1) it doesn't just affect the main discussion page, to which flarum/sticky shows excerpts for sticky discussions, and
2) it is not obvious to anybody that this extension is the one that adds it (myself included)

Thoughts? I spent a long time being confused, thinking my rewrite had broken something because the code for the excerpts was in but not showing anything. I only found it after debugging the HTTP requests and comparing them to those @ Flarum Discuss.

With Sticky:
![img](https://cdn.discordapp.com/attachments/360670804914208771/688402326901227556/unknown.png)

Without Sticky:
![img](https://cdn.discordapp.com/attachments/360670804914208771/688402273122123938/unknown.png)

**Comment by datitisev** [comment]
Still relevant. Not a priority, however.

**Comment by askvortsov1** [comment]
This should be pretty easy to fix by checking that `app.current.matches(IndexPage) || app.current.matches(DiscussionPage)` as part of the conditional for adding the excerpt

**Comment by askvortsov1** [comment]
Fixed in https://github.com/flarum/sticky/pull/25
