### ISSUE TITLE
Mobile view cut off on @ mentions

### ISSUE THREAD

**Issue by katosdev** [flarum/core#2070]
## Bug Report

**Current Behavior**
When mentioning a user using @katosdev the modal box is cut off on mobile view. Confirmed across Safari (iPhone 8 and iPhone7) and Android device (community member)

**Steps to Reproduce**
1. Go to any discussion on a mobile device
2. Reply to a post and @ mention a user
3. The modal box that appears is cut off on the left hand side.

**Comment by timas130** [comment]
![screenshot](https://user-images.githubusercontent.com/20511387/77625968-9cb17400-6f55-11ea-8bc9-684b1740f266.png)

**Comment by askvortsov1** [comment]
Closed in https://github.com/flarum/mentions/pull/46.
