### ISSUE TITLE
Garbage Collector isn't deleting expired access tokens

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#2075]
## Bug Report

**Current Behavior**
When the garbage collector kicks in (2% of requests), it is supposed to delete access tokens where the last activity + lifetime < now. However no tokens are actually deleted.

**Steps to Reproduce**
1. Login into Flarum to create access tokens. Do not check "remember" otherwise the lifetime will be very long
2. Wait for the tokens to expire or manually modify their dates (default is 3600 seconds = 1h)
3. Refresh the page many times to trigger the garbage collector
4. The tokens are never removed from the database and continue to work

**Expected Behavior**
The expired tokens should be deleted once they expire.

**Environment**
- Flarum version: master, likely broken since beta 8

**Cause**

There is some code to delete the access tokens, but it has no effect.

The issue seems to have been introduced in https://github.com/flarum/core/commit/fe73cf32374f2385d08b3af434da4aced45ca1ed by changing `last_activity_at` from `TIMESTAMP` to `DATETIME`.

The SQL query currently used to delete access tokens compares the date value with a timestamp, which never yields any result.

**Possible Solution**

A simple solution is proposed in #2074 . The solution must still be checked for any timezone-related issues. I'm also not sure if calling `UNIX_TIMESTAMP()` on all values will have any performance impact on a large number of tokens.

Other solutions could include reverting back to `TIMESTAMP` for the `last_activity_at` column.

Another option that would also help get rid of database-calculated dates and use Carbon only would be to have an additional column in which we store the expiry date, computed from the last activity and lifetime when we update the last activity. Then we can just check this value against the current time like we do for other kinds of tokens.

One last suggestion that I actually quite like would be to get rid of the lifetime property, and replace it with a `permanent` property. Then we no longer have custom lifetimes, instead we have one lifetime for normal login tokens which we can use like for other tokens (we can keep it 1h, or use 24h like most other tokens), and we can make remember and user-created tokens never expire, which was kind of the goal of the 5 years lifetime anyway.

**Security implications**

I believe the older and larger forums are the most impacted. Potentially all tokens created since the migration to beta 8 are still in their database and can be used to perform actions as the user.

This gives a higher chance of success for an attacker brute-forcing tokens of old user accounts.

However this is also linked to another known issue outlined in the security roadmap: remember me tokens are never deleted either. So even if we released an emergency fix for this, the other issue would still remain and is just as dangerous if a large number of users used the "remember" feature or social login.

My suggestion is to fix this alongside the remember me issues and the tokens management screen in #2074 and release it with beta ~~13~~ next one

In the meantime a mitigation would be for owners of old forums to manually perform a cleanup of expired tokens from the database via an SQL command. A single cleanup will delete the multiple years of expired tokens and significantly reduce risks. Even if they stay there until we fix I would still expect a very low chance of them being brute-forced successfully.

**Comment by tankerkiller125** [comment]
> One last suggestion that I actually quite like would be to get rid of the lifetime property, and replace it with a permanent property. Then we no longer have custom lifetimes, instead we have one lifetime for normal login tokens which we can use like for other tokens (we can keep it 1h, or use 24h like most other tokens), and we can make remember and user-created tokens never expire, which was kind of the goal of the 5 years lifetime anyway.

I would actually prefer this method overall. I do think we should make those global expire times configurable by administrators or something though.
