### ISSUE TITLE
Load more button - replicating posts

### ISSUE THREAD

**Issue by Eldenroot** [flarum/core#2081]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Steps to Reproduce**
1. Go to '...' FLARUM official site
2. Click on '....' "Load more"
3. Scroll down to '....' the new loaded content
- the last thread is replicated, see the image below (2x times clocked on load more button)

**Expected Behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/778890/77309506-13076980-6cfd-11ea-8159-b5533f9408fa.png)

**Environment**
- Flarum version: Flarum official site
- Website URL: http://example.com
- Webserver: [e.g. apache, nginx]
- Hosting environment: [e.g. shared, vps]
- PHP version: x.y.z
- Browser: [e.g. chrome 67, safari 11]

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

**Possible Solution**

**Additional Context**

**Comment by matteocontrini** [comment]
flarum/issue-archive#230

**Comment by dsevillamartin** [comment]
Yep, duplicate of flarum/issue-archive#230.
