### ISSUE TITLE
Middleware insertBefore and insertAfter appear reversed?

### ISSUE THREAD

**Issue by AlexanderOMara** [flarum/core#2083]
This is in relation to one of the changes made in https://github.com/flarum/core/pull/2063 (earlier versions did not work correctly at all).

## Bug Report

**Current Behavior**

`Flarum\Extend\Middleware::insertBefore` places a Middleware class after another in the array, and `Flarum\Extend\Middleware::insertAfter` places it before.

**Steps to Reproduce**

Here's some example code:
```
(new Extend\Middleware('forum'))
    ->insertAfter(
        HttpMiddleware\AuthenticateWithSession::class,
        Middleware\Authenticate::class
    )
```

Unexpectedly this would make the array:

```
[
        HttpMiddleware\ParseJsonBody::class,
        HttpMiddleware\CollectGarbage::class,
        HttpMiddleware\StartSession::class,
        HttpMiddleware\RememberFromCookie::class,
        Middleware\Authenticate::class,
        HttpMiddleware\AuthenticateWithSession::class,
        HttpMiddleware\CheckCsrfToken::class,
        HttpMiddleware\SetLocale::class,
        HttpMiddleware\ShareErrorsFromSession::class
]
```

This seem unintuitive, especially since `Flarum\Extend\Middleware::add` would add it to the end.

**Expected Behavior**
I would expect the opposite behavior.

**Environment**
- Flarum version: Commit `0bc06e1bb1bf3f0b0f241827ef6bd7704650b9fc`
- Website URL: localhost
- Webserver: apache
- Hosting environment: local
- PHP version: Unrelated
- Browser: All browsers

**Possible Solution**
Revert a portion of commit `0bc06e1bb1bf3f0b0f241827ef6bd7704650b9fc`

**Comment by tankerkiller125** [comment]
What's interesting is that our test our passing correctly with the current behavior, but not the previous behavior. Part of this may be related to the fact that middleware are part of a pipeline and are not necessarily executed in the order that they are placed. I'll do some more looking into this to figure out what's going on.

**Comment by AlexanderOMara** [comment]
> Part of this may be related to the fact that middleware are part of a pipeline and are not necessarily executed in the order that they are placed.

Yes, I believe you are correct about that, because the `process` can run code both before and after it calls the rest of the pipeline.

**Comment by tankerkiller125** [comment]
I found the issue, I put the middleware in the test in backwards (original vs added) 🤦‍♂ causing the original way to fail. You are correct that they are backwords. I am updating both the test and the extender to correct it. I'll make a PR in a couple of minutes.
