### ISSUE TITLE
Bring back common, forum, and admin namespaces in JS

### ISSUE THREAD

**Issue by datitisev** [flarum/core#2085]
Related to #1821. 

I think it'd be in our best interest to bring back the `common`, `forum` and `admin` namespaces that were removed at some point (I think beta 8).

Pros:
- we don't have to worry about naming files the same in `common` and `forum`/`admin` causing issues (because of `flarum.core.compat`)
	- also prevents issues when we generate typings - using `flarum/forum/Forum` instead of `flarum/Forum`
	  ![img](https://cdn.discordapp.com/attachments/600769671922319360/691003021060210758/unknown.png)
- makes knowing where files are located in core easy when looking at extensions (no need to guess namespace)
- if looking at core, can easily see what the import should be (no need to remove part of it)
- easier to understand from the perspective of a newly starting extension developer (luceos, https://github.com/flarum/core/issues/2085#issuecomment-604285670)

Cons:
- definitely means ALL JS exts will stop working
- @clarkwinkelmann thinks it'd be more readable, likes bundling <stack> & common

What we could do is allow both ways- keep the current structure without the stack in flarum.core.compat BUT also allow including the stack when typing code (stripped on build). This could cause confusion, however.

If I missed any pro/con, please comment so.

**Comment by luceos** [comment]
It's also easier to understand from the perspective of a newly starting extension developer.

**Comment by tankerkiller125** [comment]
I feel like the majority of JS extensions will probably break in the rewrite anyways. I think the benefits far outweigh the cons here. Just making it easier to understand for new extension developers I think alone outweighs the cons.

**Comment by clarkwinkelmann** [comment]
We currently accept using the `/admin` and `/forum` imports when using `@` imports https://github.com/flarum/flarum-webpack-config/blob/master/index.js#L55

We can add that as well as `/common` support to the "old-style" section so that developers can prepare their extensions for the upcoming change.

**Comment by datitisev** [comment]
@clarkwinkelmann I don't think there's a single extension that uses `@flarum/core` imports - mainly because core exports barely anything and it's not documented in the slightest.

I didn't even know we had JS extenders 🤷‍♂

**Comment by askvortsov1** [comment]
I'm generally in the 'explicit is better than implicit' camp, and I think this makes things clearer. I'm in favor.

**Comment by luceos** [comment]
@franzliedke could you share your thoughts on this one too 🙏

**Comment by datitisev** [comment]
Still relevant. We're probably doing this.

**Comment by clarkwinkelmann** [comment]
Discussed in today's meeting: if we want to refactor `compat` to include the namespace (and allow identical names in common and forum/admin), we should do both that and this issue subject at the same time so extensions won't need to re-compile.

Doing so requires completely removing the ability to include without namespace I think.

**Comment by askvortsov1** [comment]
So that would leave us without a BC layer?

**Comment by datitisev** [comment]
@clarkwinkelmann I think I maybe didn't explain things correctly during the meeting.

If we want to include the namespaces without immediately requiring extensions to update their code, we need a BC layer.

If we don't want to include the namespaces just yet but allow extension developers to use them in imports, we need the webpack PR.

You can't really have both this issue & the webpack PR because the webpack PR gets rid of the namespaces and this issue would add them to compat.js - making any import not work. 

If the namespace is added to the compat imports without a BC layer the extensions *will* need to update their code.

**Comment by askvortsov1** [comment]
Which webpack PR in particular are we talking about?

And for BC layer, do you mean duplicating the content of the `compat` files so that every item has 2 keys? Would that increase bundle size?

**Comment by datitisev** [comment]
I'm talking about https://github.com/flarum/flarum-webpack-config/pull/7.

A BC layer here, with the current system, would mean duplicating all the keys in the object, yes. That would increase bundle size, but not by a noticeable amount, I would think.

**Comment by askvortsov1** [comment]
So in your opinion, we should go for this issue with a BC layer and not the webpack PR?

**Comment by datitisev** [comment]
Yes, because both instances require extension developers to update their imports at some point. The webpack PR would be a temporary solution that is mainly to allow typings (once I get around to creating those) to work anyway. Once the namespaces are added to compat.js the extension developer would have to update & rebuild their dist again.

**Comment by askvortsov1** [comment]
Lets do that then.

**Comment by luceos** [comment]
Remove proxy/bc layer before stable.

**Comment by askvortsov1** [comment]
I would propose that we deprecate it before stable, and only remove for v2. It's a big breaking change, and unlike the Mithril or events BC layers there isn't that strong a reason to force one convention over another so immediately. We should add a console warning though.

**Comment by datitisev** [comment]
The current step is to deprecate the other imports, correct? How do we want to do this?

I tried adding a console.log() to the Proxy for when a namespace isn't included. I don't know if this is what we wanted, but
1) I can't make it appear only in debug mode (at least not safely, `app.forum` isn't set yet as imports are resolved before the app boots so we'd have to use `app.data` which is 😬)
2) The trace isn't able to point back to what extension used the import, so it's hard to debug.

**Comment by askvortsov1** [comment]
I don't know that we need a formal message, but we should:

- mark it as deprecated in the code
- change references in the documentation
- announce the change in the release announcement

**Comment by datitisev** [comment]
> How difficult would it be to generate a typing library based on the new, full imports? That could be a useful tool for devs

Not difficult. I was playing around with automatically generating typings, and as the imports for types are determined by the path (at least how we're using TS, w/o modules) then it's very easy. But that should be discussed in another issue, and I should probably try to make a repo that would host typings for Flarum & automatically generate them (again, not very hard).

**Comment by askvortsov1** [comment]
Another thing we could do is release a CLI utility that checks for old style imports
