### ISSUE TITLE
Link to post scrolls to the previous post

### ISSUE THREAD

**Issue by gyaaniguy** [flarum/core#2086]
**Current Behavior**
Opening a Link to direct post, say 5th post, scrolls to the 4th post.

**Steps to Reproduce**
1. Go to https://discuss.flarum.org/d/23184-flarum-categories/5
2. Address bar will show /4 not /5.  4th post would also be scrolled .

**Possible Solution**
Creating a pull request :) . Should it be in beta branch ? docs say latest stable branch. Apologies, this is my first attempt at collaborating with git.

**Comment by tankerkiller125** [comment]
Which version of flarum are you seeing this on? Your PR appears to be based on beta 7.2 which is very old at this point.

**Comment by datitisev** [comment]
Still relevant.

**Comment by askvortsov1** [comment]
Will be fixed in #2160
