### ISSUE TITLE
Pinned posts preview lines

### ISSUE THREAD

**Issue by Fastidious** [flarum/core#209]
Pinned posts preview lines (the two or three lines pinned posts show on the post list), almost touch the labels. Recommending  some padding or other approach, so the text doesn't get that close to the labels.

**Comment by tobscure** [comment]
screenshot?

**Comment by Fastidious** [comment]
See below.

![screen shot 2015-08-02 at 10 07 32](https://cloud.githubusercontent.com/assets/8352292/9026469/547848b8-38fe-11e5-8fbd-f1a061d57946.png)

**Comment by tobscure** [comment]
I don't think this is an issue, looks fine to me

**Comment by franzliedke** [comment]
Agreed. They're not on the same line.
Am 03.08.2015 01:28 schrieb "Toby Zerner" <notifications@github.com>:
