### ISSUE TITLE
Current TextFormatter v2 version breaks IE 11 support

### ISSUE THREAD

**Issue by datitisev** [flarum/core#2106]
![image](https://user-images.githubusercontent.com/6401250/77926980-c67bdb00-7274-11ea-92f0-0ce1a3c0c7b1.png)

Line 390, col 311: 
![image](https://user-images.githubusercontent.com/6401250/77927023-d72c5100-7274-11ea-9c15-3c36cc6dbaa8.png)

![image](https://user-images.githubusercontent.com/6401250/77927060-e01d2280-7274-11ea-8d7b-45d91a155035.png)

Looks like IE 11 doesn't support `for...of` loops.

**Comment by tankerkiller125** [comment]
I think this brings us back to the Polyfill issue. https://github.com/flarum/core/issues/1960 further IE11 is no longer the default browser and Windows 7 is officially dead. I know that IE11 is being supported for security reasons in Windows 10 but it will never receive new features which begs the question of how long we should support outdated browsers?

**Comment by datitisev** [comment]
We've fixed a bunch of IE 11 issues after IE 11 stopped being the default browser.

I don't want to bother with it either.

**Comment by askvortsov1** [comment]
This particular issue is to do with a dependency, there's not much we can do on our end other than filing an issue with text formatter (which we should probably do) and downgrading to a different version of the dependency (not sure if that's worth it, we'd have to push out a whole new release)

**Comment by Eldenroot** [comment]
IE11 will be replaced by Edge sooner or later... I think we should not take care about this old browser. New Edge works in Win 7 and it is only a matter of time when it will be replaced by the latest Edge.

**Comment by Zeokat** [comment]
I agree, Forget IE 11. Put time in something dead and unsupportted is not wise from my point of view.

**Comment by tankerkiller125** [comment]
I'm going to close this as it's a dependency issue and I the consensus seems to be to drop IE support. Edge Chromium is now available for Win7+ (although Win7 is EOL so if your using it I would recommend upgrading to Win10)
