### ISSUE TITLE
old username under "posted by"

### ISSUE THREAD

**Issue by poush** [flarum/core#211]
Basically the issue is 
You go to a thread > Post something > Press back button top > And then the same thread has written old username under "posted by" 

<img width="402" alt="screen shot 2015-08-02 at 8 17 35 pm" src="https://cloud.githubusercontent.com/assets/1812082/9026638/f5414b50-3953-11e5-90e0-5c4acee12641.png">

on refreshing page it is fine there
<img width="302" alt="screen shot 2015-08-02 at 8 17 44 pm" src="https://cloud.githubusercontent.com/assets/1812082/9026639/f5acbce6-3953-11e5-83f3-54bad8f44554.png">

**Comment by Fastidious** [comment]
The title of this issue is wrong. It should be "Discussion doesn't refresh on reply," or similar. I think I read somewhere the auto "refresh" was disabled while in beta, but it might be something worth checking.

**Comment by tobscure** [comment]
Fixed. Will push to dev forum soon.
