### ISSUE TITLE
Colour names and RGB passes validation

### ISSUE THREAD

**Issue by markiemm** [flarum/core#2121]
On the tags extension, entering the colour name will change the preview at the top to the colour of your choice but does not pass validation. Only HEX codes work. This used to work back in BETA 6 but was broken in future BETA versions and to this day still is broken in BETA 12

**Comment by askvortsov1** [comment]
Personally I'd like to see the options expanded to color names and RGB, although we could always just make those not work on the preview.

**Comment by the-turk** [comment]
I think the best solution will be allowing HEX only because I couldn't think any elegant solution to check invalid color names.

**Comment by askvortsov1** [comment]
In that case, perhaps the fix should be not showing a preview for non-hex values?

**Comment by datitisev** [comment]
> In that case, perhaps the fix should be not showing a preview for non-hex values?

I think there really shouldn't be any validation here. If the color is invalid, you'll see that in the preview 🤷

**Comment by askvortsov1** [comment]
> > In that case, perhaps the fix should be not showing a preview for non-hex values?
> 
> I think there really shouldn't be any validation here. If the color is invalid, you'll see that in the preview

Yeah that makes sense too
