### ISSUE TITLE
'login_providers' table error found by deleting account

### ISSUE THREAD

**Issue by Littlegolden** [flarum/core#2124]
## Bug Report
After deleted an account registered with a third-party login, the corresponding data in the `login_providers` table will not be automatically deleted, so it will be impossible to register again with the same third-party account.

**Steps to Reproduce**
1. Sign Up with GitHub Account or any other third-part login.
2. Delete this account.
3. Enable debug mode.
3. Re-SignUp with the same GitHub Account.
https://i.loli.net/2020/04/15/bURAazgYSvc26Ns.png

**Environment**
- Flarum version: beta12
- Webserver: nginx.1.16
- PHP version: 7.3

**Comment by datitisev** [comment]
That's odd, we have a line that should delete the login_providers row when the foreign user is deleted. Do you have that foreign relation in your table?

https://github.com/flarum/core/blob/1d953b3514eea807c59a2d70451eb6d483811741/migrations/2018_09_22_004200_create_login_providers_table.php#L24

**Comment by askvortsov1** [comment]
@Littlegolden It seems that with the proper DB configuration, this should not happen. If you have this relation in your DB but the issue persists, could you reopen this issue? Thanks!
