### ISSUE TITLE
Discussion canonical URL sometimes contains empty "near" parameter

### ISSUE THREAD

**Issue by matteocontrini** [flarum/core#2130]
Example:

```
https://discuss.flarum.org/d/21542-removing-the-image-button/
```

has canonical URL (as shown in the HTML meta tag):

```
https://discuss.flarum.org/d/21542-removing-the-image-button?near=
```

While this one (no slash at the end):

```
https://discuss.flarum.org/d/21542-removing-the-image-button
```

Has this canonical URL:

```
https://discuss.flarum.org/d/21542-removing-the-image-button
```

I think the `near` querystring parameter shouldn't be there in the first case.

**Comment by datitisev** [comment]
Still relevant.

**Comment by matteocontrini** [comment]
Still an issue.

**Comment by askvortsov1** [comment]
Since #2246 is fixed, we can now use the regular url generator for the whole link in `Forum\Content\Discussion.php`
