### ISSUE TITLE
Api /tags postCount parameter type is not clear

### ISSUE THREAD

**Issue by xkeyC** [flarum/core#2137]
## Bug Report

**Current Behavior**

open siteurl/api/tags

data > tag > attributes > postCount

0 is int, otherwise it is String. I am developing a client using a strongly typed language, and encounter this type error when decoding json.

I can temporarily type judge to solve this problem，But I hope the type of this parameter can be clear

**Comment by tankerkiller125** [comment]
postCount is not a valid attribute in the Flarum Core, do you mean discussionCount? In which case it always shows as a valid int in my testing.

We also need more information, what version of flarum are you running, what is the output of `php flarum info`, php version, etc. without this information we can not properly diagnose this issue.

**Comment by xkeyC** [comment]
It is indeed postCount, it may be provided by some extension, I will check it, thanks for your reply.

**Comment by xkeyC** [comment]
> postCount is not a valid attribute in the Flarum Core, do you mean discussionCount? In which case it always shows as a valid int in my testing.
> 
> We also need more information, what version of flarum are you running, what is the output of `php flarum info`, php version, etc. without this information we can not properly diagnose this issue.

found it! It's a question of flarum-categories expansion!
