### ISSUE TITLE
Extended permissions for Tags extension

### ISSUE THREAD

**Issue by Genetik57** [flarum/core#2138]
Hi team,

I open this request related to the subject at this address -> https://discuss.flarum.org/d/23428-have-extended-permissions-with-the-tags-extension

Original message:

> Is it possible to have an update of the extension Tags (https://github.com/flarum/tags) which allows to attribute to a few group of people a non respect of the restrictions of tags?
> 
> For example I defined a primary and secondary tags limit but it applies to administrators and members... I would only like this limit to be for members and not for administrators
> 
> I can't find this option even in permissions menu
> 
> What do you think about this feature???

For me I think it would be a very good idea if administrators as well as other ranks could get over these restrictions

Thanks for all Team

**Comment by askvortsov1** [comment]
Are you proposing this restriction exception just for the tag count limits, or for some other aspect of tags as well?

**Comment by Genetik57** [comment]
@askvortsov1 for the tag count limits

**Comment by askvortsov1** [comment]
Here's how I'm envisioning this happening:

- A permission is setup to bypass tag requirements
- If $actor->can() that permission, `validateTagCount` is skipped in https://github.com/flarum/tags/blob/fa83f496b0004e31ef2f4fc854bfcdf6a4cfa3c3/src/Listener/SaveTagsToDatabase.php#L85. The discussion instance is passed to the permission check.
- Furthermore, extensions like Byobu can add in a policy to conditionally skip validation, such as if that discussion is private. The only question then is that if discussions are switched from private to public, tags would need to be added, but that's a Byobu issue not a tags issue.

**Comment by askvortsov1** [comment]
We want this.

**Comment by Genetik57** [comment]
Me too

**Comment by Genetik57** [comment]
Hi,

Any news?

**Comment by askvortsov1** [comment]
I laid out what needs to happen in https://github.com/flarum/tags/pull/107#discussion_r551639080, just a question of it getting done.
