### ISSUE TITLE
Starting a reply with a # 

### ISSUE THREAD

**Issue by Fastidious** [flarum/core#215]
Starting a reply with  a # makes Safari *and* Chrome (OS X Yosemite) crazy. I am getting the beach ball, and can't type any further unless page is reloaded. Starting with # again repeats same behavior.

**Comment by tobscure** [comment]
Closing until we can reproduce - http://discuss.flarum.org/d/458/another-test/1

**Comment by Fastidious** [comment]
As I wrote on the forum, start with #, a space, then text. I could also replicate this on iOS Safari.

**Comment by tobscure** [comment]
Ah, I see.

**Comment by tobscure** [comment]
TextFormatter issue: https://github.com/s9e/TextFormatter/issues/14
