### ISSUE TITLE
My Suggestions

### ISSUE THREAD

**Issue by CSS-Lletya** [flarum/core#2158]
So pardon my lack of knowledge how to submit proper and secure feature requests on github. I usually don't do this. Anyways here's my list, etc..  If any of these pre-exist i'm sorry as I just came up with these ideas while looking at my forum and feeling what could be best to have added (for everyone). I feel like most of these should be in Core, however they can be Extension based regardless. 

**Installation progress visual**

- Visual progress bar showing progress of installation.
- Can be designed in any way, as long as us the consumer can understand easily

**Ability to upload a custom background**

- Allows optimal (optional) design for consumers forum uses.

**Ability to add a profile banner (Similar to IPB)**

- Add an option upload for profile banner (there's no real drawbacks on this. this'll make flarum so much better)

![Image of IPB](https://i.imgur.com/nuhc1wg.png)

**Auto purge cache/Fix bug where cache isn't updating automatically**

- Installing addons shows css naming instead of actual naming we'd typically read
- Forum users also experience this as well until admin manually purges cache. 

**Image popup system**

- So regardless of size it'd be nice to have a popup window displaying the image (as seen below, not to look like it but the concept behind it you understand at least (mechanics, etc..))

![Image of popup](https://www.jqueryscript.net/images/Gallery-Popup-With-jQuery-LC-Lightbox.jpg)

**Ability to use a background image for forum Welcome Banner**

- Would be another great stylizing feature to have. I'd say add mp4 support but that'd be a bit too much for rendering, so image would suffice

**More Emoji's**

- Can look into free emoji's to use. Discord has quite a lot, however not sure if available to utilize their emoji set/speciifcs)

- Animated emoji's are cool too! ;)

**User group styling**

- Add a option to enter html/css to stylize the format of the display of user groups (example, add a css effect to make a username/group glow, etc...)

**Users online block**

- Would be a great feature to let everyone know who's online, most online, past 24 hours online, etc..

**Comment by tankerkiller125** [comment]
As noted in the comments of the Feature Request template:
> **IMPORTANT**: Feature requests on this GitHub issue tracker are only accepted in case they have been approved by a core developer or contain extensive argumentation and directions for implementation. For all other feature requests, ideas and feedback please post in the Flarum Community: https://discuss.flarum.org/t/feedback.

For this reason I will be closing this issue, please consider posting this feedback on our forums for discussion with the devs and the community.
