### ISSUE TITLE
Problems with Markdown

### ISSUE THREAD

**Issue by Fastidious** [flarum/core#216]
If the following is entered, it will show all as a numbered list:

    1. One.
    2. Two.
    
    * One.
    * Two.

Entering it this way renders the same results:

    1. One.
    2. Two.    
    * One.
    * Two.

Both examples above will render as:

1. One.
2. Two.
3. One.
4. Two.

**Comment by franzliedke** [comment]
Yes, that's a bug. Please take it up with [TextFormatter](https://github.com/s9e/TextFormatter), though.

**Comment by Fastidious** [comment]
Maybe [Parsedown](http://parsedown.org/)?

**Comment by franzliedke** [comment]
I think we're pretty sold on TextFormatter ;)
