### ISSUE TITLE
Pusher - dynamice content isn't loading on non public discussions

### ISSUE THREAD

**Issue by Wadera** [flarum/core#2165]
## Bug Report

**Current Behavior**
https://discuss.flarum.org/d/23805-pusher-dont-working-on-non-public-discussions

Looks like Pusher don't work on Private / Non public discussions.
Currently my forum can establish connections and some notifications are pushed, example:

* New posts appear dynamically in public accessible discussions
* Notification about all new fallowing / lurking / flagged posts appear on flag / bell icon

![pusher](https://user-images.githubusercontent.com/407236/81978872-0a0f8600-9624-11ea-9df8-915b2b8c30de.PNG)

But on non public / private discussion new posts don't appear dynamically.

More details already provided by: `@Staszek#82852`
under: https://discuss.flarum.org/d/2558-need-help-in-using-pusher-with-flarum/75

> `@Staszek#82852` I investigated a little, and have some conclusions.
> It seems, that notification works only, when forum is visible to public view.
> Pusher plugin listens for two events: PostWasPosted, and NotificationWillBeSent. First one is raised when there is new post, and notification is sent, if Guest user can see it:
>     public function pushNewPost(PostWasPosted $event)
>     {
>         if ($event->post->isVisibleTo(new Guest)) {
>             $pusher = $this->getPusher();
> 
>         $pusher->trigger('public', 'newPost', [
>             'postId' => $event->post->id,
>             'discussionId' => $event->post->discussion->id,
>             'tagIds' => $event->post->discussion->tags()->lists('id')
>         ]);
>     }
> }
> 
> second type of notification, NotificationWillBeSent, should send notification, if user can see a post:
>     public function pushNotification(NotificationWillBeSent $event)
>     {
>         $pusher = $this->getPusher();
>         $blueprint = $event->blueprint;
> 
>     foreach ($event->users as $user) {
>         if ($user->shouldAlert($blueprint::getType())) {
>             $pusher->trigger('private-user'.$user->id, 'notification', null);
>         }
>     }
> }
> 
> But after search in my whole Flarum instance, I haven't found a single line of code, that rises it. So no chances for push notification...
> Am I missing something? Maybe there is some extension, that rises this event? Or is it a bug, and I should write about it on Github?

**Steps to Reproduce**
1. Go to any non-public or private discussion
2. Duplicate browser tab
3. Post new message
4. New message won't be loaded in background for other users / on second tab.

**Expected Behavior**
It should works on the same way as any other discussion on flarum, example:
1. Go to public available discussion
2. Duplicate browser tab
3. Post new message
4. New message will be loaded in background for other users / on second browser tab for this topic.

**Screenshots**

![pusher-test](https://user-images.githubusercontent.com/407236/81981112-bb63eb00-9627-11ea-9337-538956265c2b.gif)

**Environment**
- Flarum version: 0.1.0-beta.13
- Webserver: [apache + nginx proxy + cloudflare on frontend]
- Hosting environment: Dedicated Server - CentOS
- PHP version: 7.3.17
- Browser: Firefox 76.0.1 / Chrome Version 81.0.4044.138

```
$ php flarum info
Flarum core 0.1.0-beta.13
PHP version: 7.3.17
Loaded extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, calendar, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, gettext, SPL, iconv, intl, json, mbstring, session, standard, mysqlnd, PDO, pdo_mysql, pdo_sqlite, Phar, posix, Reflection, mysqli, SimpleXML, soap, sockets, sodium, exif, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, imagick, ionCube Loader
+---------------------------------+----------------+--------+
| Flarum Extensions               |                |        |
+---------------------------------+----------------+--------+
| ID                              | Version        | Commit |
+---------------------------------+----------------+--------+
| flarum-approval                 | v0.1.0-beta.13 |        |
| flarum-bbcode                   | v0.1.0-beta.12 |        |
| flarum-emoji                    | v0.1.0-beta.13 |        |
| flarum-lang-english             | v0.1.0-beta.13 |        |
| flarum-flags                    | v0.1.0-beta.13 |        |
| flarum-likes                    | v0.1.0-beta.13 |        |
| flarum-lock                     | v0.1.0-beta.13 |        |
| flarum-markdown                 | v0.1.0-beta.13 |        |
| flarum-mentions                 | v0.1.0-beta.13 |        |
| flarum-statistics               | v0.1.0-beta.13 |        |
| flarum-sticky                   | v0.1.0-beta.13 |        |
| flarum-subscriptions            | v0.1.0-beta.13 |        |
| flarum-suspend                  | v0.1.0-beta.13 |        |
| flarum-tags                     | v0.1.0-beta.13 |        |
| fof-user-bio                    | 0.1.3          |        |
| fof-links                       | 0.3.0          |        |
| fof-polls                       | 0.1.2          |        |
| fof-spamblock                   | 0.2.2          |        |
| extiverse-bazaar                | 0.4.1          |        |
| fof-split                       | 0.4.3          |        |
| fof-follow-tags                 | 0.3.4          |        |
| fof-byobu                       | 0.5.0          |        |
| fof-recaptcha                   | 0.1.2          |        |
| michaelbelgium-profile-views    | v2.1.6         |        |
| fof-profile-image-crop          | 0.1.1          |        |
| fof-user-directory              | 0.3.4          |        |
| michaelbelgium-discussion-views | v3.2.0         |        |
| fof-best-answer                 | 0.1.7          |        |
| fof-upload                      | 0.9.1          |        |
| fof-merge-discussions           | 0.3.3          |        |
| flarum-pusher                   | v0.1.0-beta.13 |        |
| fof-nightmode                   | 0.4.0          |        |
+---------------------------------+----------------+--------+
Base URL: https://my.domain
Installation path: /home/doesnt-matter/domains/my.domain/flarum
Debug mode: off
```

**Comment by KyrneDev** [comment]
Related https://github.com/flarum/pusher/pull/17

**Comment by askvortsov1** [comment]
Shoo stalebot!

**Comment by luceos** [comment]
Looks like related PR was merged @Wadera can you confirm?
