### ISSUE TITLE
Negation in tags filter does not work

### ISSUE THREAD

**Issue by rob006** [flarum/core#2168]
**Steps to Reproduce**
Go to https://discuss.flarum.org/ and type `-tag:extensions` in search field: https://discuss.flarum.org/?q=-tag%3Aextensions

**Expected Behavior**
List of all discussion **without** `extensions` tag.

**Current Behavior**
List of all discussion **with** `extensions` tag (same as for query without negation: `tag:extensions`).

**Comment by datitisev** [comment]
Looks like it works if you do `!tag:extensions`.

**Comment by rob006** [comment]
> Looks like it works if you do `!tag:extensions`.

Hmm, that is weird. First, `-` seems to be used for negation:

https://github.com/flarum/core/blob/d492579638fb52dafbfe65f1f36a95eb6047f7f3/src/Search/AbstractRegexGambit.php#L43

Second, `!` does not work for `!tag:solved`: https://discuss.flarum.org/?q=!tag%3Asolved

**Comment by clarkwinkelmann** [comment]
This was broken in flarum/tags#75 when replacing `orWhereExists` with `orWhereIn` because `orWhereIn` doesn't have a `$not` parameter:

    orWhereExists(Closure $callback, $not = false)
    orWhereIn($column, $values)

The method is currently called with 3 parameters instead of the expected 2 and the third does absolutely nothing.

I have prepared a PR.
