### ISSUE TITLE
Updated threads not being displayed as unread

### ISSUE THREAD

**Issue by DCSJAPAN** [flarum/core#219]
Since the latest update, it's impossible to tell which threads are unread. The titles are not bold.

For example, here's what I see before I click the "Show x updated discussion(s)" link:

![before](https://cloud.githubusercontent.com/assets/13129997/9126267/6003874c-3ce6-11e5-9b4d-6eaadfecc116.png)

And here's what I see after I click it:

![after](https://cloud.githubusercontent.com/assets/13129997/9126274/6c2727e0-3ce6-11e5-8859-72f134e96e4d.png)

It seems pretty clear that the "Previous forum software?" thread has been updated, but there's nothing (other than the fact that the post has been moved to the top) to indicate that there's an unread post there.

Using Safari 7.1.7 on Mavericks, as always. :)

**Comment by DCSJAPAN** [comment]
... Never mind ... was logged out and didn't notice.

Maximum self-facepalm.

**Comment by tobscure** [comment]
Haha! Come to think of it, we should actually have some kind of mechanism to detect if you've been logged out, and then prompt you to re-enter your password.

**Comment by DCSJAPAN** [comment]
That would be helpful, if possible.
