### ISSUE TITLE
Duplicate notifications

### ISSUE THREAD

**Issue by PeopleInside** [flarum/core#2191]
## Bug Report

**Current Behavior**

As told [here](https://discuss.flarum.org/d/23912-avoid-two-email-for-notificate-a-reply) I think a solution should be found to avoid double ring bells and email notifications on new post / reply.

Actually often happen than someone mention in a post and two different email notification and ring bells are sent.

One that inform about a new post, the second one that inform you has been mentioned.

The two component mention and subscriptions should work together or be just one.

**Possible Solution**

The system should send just one notification or email so need a check if one of the two notification is present than do not send the other. Sorry I cannot help with the code... I'm just reporting the issue experienced in https://discuss.flarum.org

Hope this can be fixed, improved.

**Comment by dsevillamartin** [comment]
Duplicate of flarum/issue-archive#318 I think. FYI, this is a hard issue to resolve because these are different extensions and different settings dictate whether you get notifications for each event.
