### ISSUE TITLE
Confirmation email code duplication

### ISSUE THREAD

**Issue by matteocontrini** [flarum/core#2193]
Hello,

I've noticed that the [SendConfirmationEmailController](https://github.com/flarum/core/blob/4da2994d1fab1a167406680876101d19603cc27a/src/Api/Controller/SendConfirmationEmailController.php) and [AccountActivationMailer](https://github.com/flarum/core/blob/4da2994d1fab1a167406680876101d19603cc27a/src/User/AccountActivationMailer.php) classes do almost exactly the same thing, with the only difference that they are triggered in different situations.

I think that there's space for improvement and that the code duplication could be avoided.

**Comment by clarkwinkelmann** [comment]
I'm not sure that's worth it seeing how little code there's in the Confirmation controller.

Though we could probably move some of the methods of the ActivationMailer to a trait and re-use them in both places.

**Comment by askvortsov1** [comment]
Tbh, this seems like a litle over-optimization. If we need to use that code again in a third place, then let's abstract it away. But for now, I think that might bring more confusion than justified

**Comment by matteocontrini** [comment]
Honestly I don't agree. The code in the two files literally does the same exact thing, it's just arranged slightly differently. I think this brings more confusion because there are multiples places where the confirmation email can be sent out, with the same exact configuration.

A change in the confirmation email would require modifying the same (copy-pasted) code in two places, and I don't see how this could be considered good or make sense.
