### ISSUE TITLE
Flarum gets stuck when an edit is submitted after a subsequent reply is added

### ISSUE THREAD

**Issue by DCSJAPAN** [flarum/core#220]
Here's something I've noticed a couple times since you disabled the editing of posts once a subsequent reply has been added to the discussion:
 
If you start to edit your post, but don't manage to submit it before someone else adds a reply to the same discussion, Flarum ends up getting stuck when you eventually try to submit the changes. It just sits there spinning, and it seems like the only way to get it unstuck is to leave the page. (I think it may time out after a while, but I haven't waited long enough to be sure.)

It seems like Flarum has noticed it's trying to update a post that can't be updated, but doesn't know what to do about it. It needs a way to check for this situation and exit it gracefully.

(At present, even when you leave the page to get it unstuck, you're left with a tab at the bottom of the window containing the unposted alterations. If possible, it might be a good idea to leave that in place, as in some cases the user may want/need to edit and submit the alterations as a new post.)

**Comment by Fastidious** [comment]
I had reported this on the old sandbox, never came around to create a ticket for it. The same behavior occurs if you start editing a topic/reply, and while doing it, the editing time expires. All you get is a the spinning wheel, nothing else.

**Comment by DCSJAPAN** [comment]
I didn't notice that, since I've never waited quite that long to submit an edited post.

When the wheel is spinning because a subsequent reply was posted before submission, this is the error info I get (not sure if the top one is relevant):

[Error] TypeError: undefined is not an object (evaluating '$(e).offset().top')
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (4068, line 0)

**Comment by tobscure** [comment]
Related to #118

**Comment by tobscure** [comment]
Merging into #118.
