### ISSUE TITLE
Automatically load updated post

### ISSUE THREAD

**Issue by DCSJAPAN** [flarum/core#221]
Regarding the new yellow "Show x updated discussion(s)" message...

I like seeing this message when I've left the page sitting idle for a while, but it bugs me a bit when it shows up after I've just reloaded the page (by clicking on the logo or whatever). And it is particularly bothersome when it was **me** who updated the discussion that it's prompting me to show!

Would it be possible to have the thread list reload automatically whenever the user returns to it?

Apologies if this is already under consideration...

**Comment by Fastidious** [comment]
> particularly bothersome when it was me who updated the discussion that it's prompting me to show.

That one irks me quite a bit as well. :-)

**Comment by franzliedke** [comment]
Thanks, will be fixed after beta ;)

**Comment by tobscure** [comment]
The "updated discussions" message appearing when it was you who made a post should be fixed.

This extension needs to be completely rewritten at some stage after beta, so we'll keep all of this in mind :)

**Comment by DCSJAPAN** [comment]
Yes, it's a much smoother experience now. Thanks!

**Comment by DCSJAPAN** [comment]
Hmmm ... the auto updating when I reload the page works fine, but now the pusher isn't showing me the "updated discussions" message at all, even after the page has been idle for a few hours.

**Comment by tobscure** [comment]
Check the browser console for messages. We're on the free Pusher plan atm, so most likely the connection quota has been reached

**Comment by DCSJAPAN** [comment]
Hmm ... I tried closing the window, clearing the cache, and reloading ... and now it seems to be working. Could it simply have been a caching issue? (But if that were the case, would I have noticed the change in the reloading behavior? Puzzling.)

I'll keep an eye on it, and check the console if it happens again. Thanks!

**Comment by tobscure** [comment]
We're currently using the [Sandbox Pusher plan](https://pusher.com/pricing), which limits us at 20 simultaneous connections. So if there are 20 people already browsing the forum and you hop on, push won't work for you.
