### ISSUE TITLE
"Like" and "Reply" blocked

### ISSUE THREAD

**Issue by Fastidious** [flarum/core#222]
Go to any topic, any, that has replies. Once "inside the topic", hover over the name of the poster for one of the replies, to get the pop up to show. Move mouse out, then try to click the reply or like links, on the comment you used the mouse hover on.

**Comment by tobscure** [comment]
What browser are you using?

**Comment by Fastidious** [comment]
@tobscure Safari, OS X Yosemite.

**Comment by DCSJAPAN** [comment]
... Seeing the same thing with Safari 7.1.7 with Mavericks (not that this will come as a surprise).
