### ISSUE TITLE
[Frontend] UI does't get refreshed if a discussion is deleted from the Discussions tab of the user profile

### ISSUE THREAD

**Issue by iPurpl3x** [flarum/core#2233]
## Bug Report

**Current Behavior**
If a user that has the rights to permanently delete discussions and does this from the Discussions tab of a user profile, the UI doesn't get refreshed and the Discussion stays on screen.

**Steps to Reproduce**
1. Login in as admin
2. Create a new discussion
3. Got to own profile, then on the Discussions tab
4. Use the dropdown menu to delete the discussion created in step 2
5. Use the dropdown menu to "Delete Forever"
6. The discussions stays on screen until the page ins reloaded.

**Expected Behavior**
In step 6, the discussion should not be visible on the screen anymore.

**Environment**
- Flarum version: 0.1.0-beta.13
- PHP version: 7.2.24
- Browser: Chrome 83.0.4103.116

**Comment by tankerkiller125** [comment]
Could you also please include the `php flarum info` results. Further are you able to replicate the issue on https://beta.flarum.site

**Comment by iPurpl3x** [comment]
@tankerkiller125 I don't have access to the server so I can't do `php flarum info`. But I was able to replicate the problem on https://beta.flarum.site

**Comment by iPurpl3x** [comment]
@askvortsov1 this seems to still be an issue, will it just be ignored, or should this issue be reopened ?
