### ISSUE TITLE
Pinned?

### ISSUE THREAD

**Issue by sysdl132** [flarum/core#2234]
## Bug Report

**Current Behavior**

Pin=not pin

**Steps to Reproduce**
1. Go to topics
2. Click on pin
3. Send a new reply in another topic

**Expected Behavior**

The pinned topic fell down to other not pinned topics
**Screenshots**

![Screenshot_20200715_145833](https://user-images.githubusercontent.com/54708046/87513694-b402a180-c6ab-11ea-82bd-a247b003dab4.jpg)

**Environment**
- Flarum version: 0.1.0-beta.13
- Website URL: https://sl132.flarum.cloud
- Webserver: [nginx]
- Hosting environment: vps ubuntu https://freeflarum.com 
- PHP version: 7.2.24
- Browser: opera mobile and chrome 80 in the windows
**Additional text:**
if you find something,reply directly or post a topic in my forum

**Comment by datitisev** [comment]
Pinned discussions only appear at the top when they are unread. They will still be at the top in their tags, but otherwise they'll fall down and act like regular discussions.
