### ISSUE TITLE
Localised date formatting

### ISSUE THREAD

**Issue by davwheat** [flarum/core#2241]
https://github.com/flarum/core/blob/bd40353bcc7d35fd401789b3a75debbc2e834a7e/js/src/common/utils/humanTime.ts#L22-L28

At the moment, humantime conversion strings are hard coded, resulting in a UK forum displaying "Jan 1, 2019" as opposed to the "UK" format of "1 Jan 2019".

Could these formatting strings be moved to locales so that forum admins can override them as needed to match their own forum requirements?

**Comment by datitisev** [comment]
I think this is where a UK (or non-american :P) language pack would come in?

The `ll` format would be the one displaying `Jan 1, 2019`, not the hardcoded `D MMM`. This can be overriden with `config.js` pretty sure?

![image](https://user-images.githubusercontent.com/6401250/88329876-990dde00-ccf8-11ea-91cf-506c107ce55e.png)

**Comment by tankerkiller125** [comment]
@datitisev you are correct, https://github.com/Nearata/lang-italian/blob/master/locale/config.js can be used as an example of this.

**Comment by davwheat** [comment]
Oh that's really useful, actually! I didn't realise that existed. Thanks for the help!

**Comment by franzliedke** [comment]
Not sure if this is possible, but maybe the locale config in the English language pack could be adopted to change this based on the *region* provided by the browser?

Localization is hard. :v:

**Comment by datitisev** [comment]
The English language pack doesn't have momentjs config - it comes from moment itself.

I guess we could add our own and check `navigator.language || navigator.userLanguage` and see if it's `en-US` or anything else 🤔

**Comment by franzliedke** [comment]
Let's say we might consider a PR. :wink:
