### ISSUE TITLE
Url Generator doesn't resolve optional parameters

### ISSUE THREAD

**Issue by askvortsov1** [flarum/core#2245]
The FastRoute route parser returns an array, where the first element is the route with NO optional parameters, and further arguments are every combination of optional parameters. In https://github.com/flarum/core/blob/ad42058a8aecec03410f0dd6712dab4d7c3cdabb/src/Http/RouteCollection.php#L91, we always take the first option, ie the one without optional parameters. It would be really nice to be able to resolve optional parameters, but the exact way of doing so is tricky, as that array of parsed route options looks something like:
[["\/d\/",["id","\\d+(?:-[^\/]*)?"]],["\/d\/",["id","\\d+(?:-[^\/]*)?"],"\/",["near","[^\/]*"]]]

Preferably, instead of always taking the first one, we would iterate over every option and get the one with the most matching optional parameters (complete from left to right)

**Comment by SychO9** [comment]
Duplicate of #1972 ?

**Comment by askvortsov1** [comment]
Yep, thanks for finding that! Github search has failed me once again :thinking: :cry:
