### ISSUE TITLE
"alt" attributes for avatars

### ISSUE THREAD

**Issue by hackgence** [flarum/core#2256]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Not having "alt" attributes in avatar images causes SEO issues

Checked using Google's Lighthouse - https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk

![](https://i.imgur.com/i6Zuwzg.png)

**Describe the solution you'd like**
Maybe [alt] attributes should be named as the username of the user

**Justify why this feature belongs in Flarum's core, rather than in a third-party extension**
Flarum core has alt attributes for images in the post section, it should also have for images of avatars, it is good habit.

**Describe alternatives you've considered**
None

**Comment by matteocontrini** [comment]
I don't think that using the username as the `alt` text is a solution. The alternative text should be a description of the image, and the username doesn't describe much. I think it would only be confusing for people that use screen readers.

It's not always possible to provide a meaningful `alt` text, unfortunately, but that doesn't mean that using whatever text is available is acceptable. I don't think that adding the `alt` just to get a good score on Google Lighthouse is a good idea...

**Comment by askvortsov1** [comment]
Well, the image is the avatar for the user, so I wouldn't say that using the username as the alt tag is incorrect. Although perhaps "username's avatar" might be better...

**Comment by matteocontrini** [comment]
> Well, the image is the avatar for the user, so I wouldn't say that using the username as the alt tag is incorrect

Yes, but imagine a screen reader reading "Image: askvortsov", would that be useful or help the user understand what the image is about? I don't think so...

**Comment by askvortsov1** [comment]
In that case, @smartclash would you be able to update your PR to use an empty string instead of the username? Sorry for the confusion on this one :hear_no_evil:

**Comment by smartclash** [comment]
Sure thing, will be doing that @askvortsov1 :)

**Comment by franzliedke** [comment]
You handled this perfectly, thanks. :+1: Totally agree with @rob006 .
