### ISSUE TITLE
Click on Quote redirects back to home in Guest Mode

### ISSUE THREAD

**Issue by poush** [flarum/core#226]
Okay

So i open up a topic

>> I am on some post with someone quote like "<= Toby" 
>> I click on quote link
>> Instead of getting redirected to that quoted message on that topic i am redirected back to home

^^ This happens in guest mode.

**Comment by Fastidious** [comment]
This is [explained here](http://discuss.flarum.org/d/462/linking-to-another-comment-works-but-doesn-t/1). Not a bug.
