### ISSUE TITLE
[Frontend Rewrite] Change Sort adds tag as query parameter

### ISSUE THREAD

**Issue by w-4** [flarum/core#2267]
Introduced in https://github.com/flarum/core/pull/2151 

**Steps to Reproduce**
1. Go to https://nightly.flarum.site/t/general
2. Select a sort 
3. Url changes to https://nightly.flarum.site/?tags=general

**Possible Solution**
Inside GlobalSearchState changeSort: 
Change the line `m.route(app.route(this.searchRoute, params))` to `m.route(app.route(app.current.get('routeName'), params))`
(see https://github.com/flarum/core/issues/2266)

**Comment by askvortsov1** [comment]
Good catch! With this solution, we should make sure that, for tags and following, the logic to filter by tag or by following is implemented based on the route, not on query params. Or perhaps on either?

**Comment by askvortsov1** [comment]
Implemented, thank you very much!
