### ISSUE TITLE
[Frontend Rewrite] DiscussionList double results bug

### ISSUE THREAD

**Issue by w-4** [flarum/core#2268]
## Bug Report

Introduced in https://github.com/flarum/core/pull/2150

**Current Behavior**
When a user navigates away (to a different tag for example) while the results are loading, it will lead to both the previous and new results being added to app.discussions. 

```js
  refresh({ clear = true } = {}) {
    this.loading = true;

    if (clear) {
      this.clear();
    }

    return this.loadResults().then(
      (results) => {
        this.parseResults(results);
      },
      () => {
        this.loading = false;
        m.redraw();
      }
    );
  }

```

**Possible Solution**

Add an additional `this.discussions = []` before calling parseResults. Not perfect, since results are parsed twice still, but in most cases it wouldn't be visually noticeable.

**Comment by askvortsov1** [comment]
Fixed in https://github.com/flarum/core/pull/2322
