### ISSUE TITLE
Password Reset 500 Internal Server Error

### ISSUE THREAD

**Issue by Blaxus** [flarum/core#229]
This is what I get when I try to submit the reset form.
![Error](http://puu.sh/jxj4A/9c65b5efb8.png)

Also, perhaps I should remind you guys about this issue as well: https://github.com/flarum/core/issues/148

**Comment by McFarts** [comment]
DO fault probably

**Comment by tobscure** [comment]
Is this still happening?

**Comment by Blaxus** [comment]
Yes, I just checked. I'd post on the forum, but yeah can't login so...

**Comment by tobscure** [comment]
I suspect this is a problem because your account was imported from our original esoTalk install. I've deleted it – would you mind signing up from scratch again and then testing the forgot password process once more?

**Comment by Blaxus** [comment]
Okay, signup worked great, activation works. Reset page is still empty, this time not an internal server error, just an empty page.

**Comment by tobscure** [comment]
Ah, sorry about that! Fixed.

**Comment by Blaxus** [comment]
Lol nope, the form shows now, but when I try to reset my password it gives a 500 internal server error.

**Comment by tobscure** [comment]
Strange, I can't reproduce that! Perhaps your reset token expired when you submitted the form? (I think they're supposed to last an hour though...)

**Comment by Blaxus** [comment]
Hmm let me retry.

**Comment by tobscure** [comment]
@Blaxus Sorry - for the sake of testing, I changed your password! I think it's working now though, for real. Could you go through the process once more and confirm?

**Comment by Blaxus** [comment]
It's fixed now

**Comment by tobscure** [comment]
:tada:

**Comment by z1haze** [comment]
Any word on this being fixed?
