### ISSUE TITLE
Hidden posts still shown on homepage

### ISSUE THREAD

**Issue by HVEVB** [flarum/core#2293]
## Bug Report

**Current Behavior**
When a post is hidden/deleted, it still shows up for non admins on the homepage when tags is chosen as the start page. Clicking it shows an alert with The requested resource was not found

**Steps to Reproduce**
1. In admin panel, set **Basic** > **Home Page** to **Tags**
2. Create a post
3. Delete it, but not permanently
4. Go to the homepage, and it's still shown as the latest

**Expected Behavior**
Should not be shown on the home page

**Screenshots**
![image](https://user-images.githubusercontent.com/36706634/93002753-65517680-f539-11ea-90aa-ac4a0de56676.png)
![image](https://user-images.githubusercontent.com/36706634/93002767-7b5f3700-f539-11ea-8af8-c99a2fe1366c.png)

**Environment**
- Flarum version: 0.1.0-beta.13
- Website URL: https://forum.manhunt.gg
- Webserver: apache
- Hosting environment: vps
- PHP version: 7.3.12

**Comment by askvortsov1** [comment]
Thanks for reporting! This was actually fixed in https://github.com/flarum/tags/pull/78, and will be available with beta 14
