### ISSUE TITLE
Update Readme.md to match services we use

### ISSUE THREAD

**Issue by luceos** [flarum/core#2296]
I noticed the badges inside our readme (flarum/core and flarum/flarum) have outdated information:

- logo in both repos is 404, hotlink from either the github org avatar or from flarum.org directly
- remove travis
- add github action badge (if possible)
- add styleci badge (core is repo 28257573, flarum does not exist in styleci)

**Comment by Heniisbaba** [comment]
Hi, @luceos, 
I'd like to do this. I'm new to contributing and I have read the contributing guidelines.
I don't know how to remove travis though, and what github action badge to add but I've added the success badge and StyleCi badge

Here is a screenshot of edit of the forked Readme.md
![Screen Shot 2020-09-25 at 10 11 07](https://user-images.githubusercontent.com/25427586/94249225-7fb32900-ff17-11ea-8875-1ee7715bbebd.png)

**Comment by franzliedke** [comment]
@Heniisbaba That would be awesome! Please feel free to send a PR. :hugs: 

"Remove travis" means removing the first badge (we're now using GitHub Actions in favor of Travis CI, so that badge is based on outdated builds). Other details can be discussed in the PR, I would say.

**Comment by Heniisbaba** [comment]
Alright @franzliedke, I'll send in a PR now
