### ISSUE TITLE
Investigate Modal State Inconsistencies when closing via `this.hide`

### ISSUE THREAD

**Issue by askvortsov1** [flarum/core#2303]
See https://github.com/flarum/tags/pull/93#discussion_r491291402

**Comment by franzliedke** [comment]
Really, the best way you can clean this up for real is by stopping to use Bootstrap's modal JS (the CSS is nice for styling). Mixing DOM-based state and VDOM stuff is bound to be endlessly confusing.

**Comment by franzliedke** [comment]
To be clear: if the proposed fixes fix the end-user behavior, then that's fine for now. But IMO, cleaning this up will greatly help with maintenance in the future.

**Comment by askvortsov1** [comment]
We're planning to eliminate bootstrap in later releases, we'll either adopt a smaller custom library, or code in custom modal logic (which might make sense given how (relatively) small it is

**Comment by franzliedke** [comment]
The biggest problem in this particular area is the huge and very confusing mismatch between DOM-based and VDOM-based approaches to JS. This is independent from using or not using Bootstrap for styling certain things.
