### ISSUE TITLE
When clicking on add reply or new topic it's glitchy

### ISSUE THREAD

**Issue by McFarts** [flarum/core#233]
The css animation that slides from the bottom is not smooth and glitchy. I think it should be more smoothed out.

It makes it seem very unmodern and buggy.

Definitely some css love needs to happen to that before production

Edit: It actually animates fine after you first open and close it already

But, once you refresh cache, and open it for the first time, it slides from the bottom really glitchy like, hard to explain.

**Comment by Fastidious** [comment]
@McFarts "slides from the bottom," of what? Could you screenshot it? Or LiceCap it?

**Comment by McFarts** [comment]
Hmm. for example, take a look:

It's hard to see, but you can experience it better when you look at it frame by frame

![](https://i.gyazo.com/a385975100ec87541e33b239052e4232.gif)

First 2-3 frames it kinda of does a glitchy slide up animation, it's hard to explain

**Comment by Fastidious** [comment]
What browser are you using, under what OS? I am using Safari, under OS X Yosemite, and the animation doesn't behave like in your capture.

**Comment by McFarts** [comment]
Hmm really? I'm just on the recent version on chrome... hmm

**Comment by Fastidious** [comment]
@McFarts just check on Chrome 46, OS X, still not behaving like that (the reply box comes out smoother in both, Safari and Chrome for OS X). It might be a Windows thing. Sadly, only Windows 10 to test, and even if the UI under Edge has many little bugs, the one you show is not one of them.

Could you disable *all* extensions (for this test) and clear your browser cache, then try again?

**Comment by McFarts** [comment]
Hmmm @Fastidious no problem.

![](https://i.gyazo.com/224c547ce1486e0e3ae1094c3eaa7420.png)

Disabled everything and cleared browser cache and forced reload to dl all new assets.

New GIF:

![](https://i.gyazo.com/d4ecc098226a9895116c1a782e1c9f6f.gif)

Seems a little smoother? Or is it placebo effect?

**Comment by McFarts** [comment]
Also, can u do a gif for me I want to see what it looks like on your screen please

**Comment by Fastidious** [comment]
This is what I see, in which I see no problems:

![reply_smoootness](https://cloud.githubusercontent.com/assets/8352292/9252796/4b4dea88-41a8-11e5-81f0-65929b82525f.gif)

**Comment by McFarts** [comment]
Hmm.. odd. Yeah it looks way smoother when the slide initiates from the bottom.
