### ISSUE TITLE
Post content needs to be truncated

### ISSUE THREAD

**Issue by Allineer** [flarum/core#235]
```
Warning: DOMDocument::loadXML(): AttValue: ' expected in Entity, line: 1 in /home/forge/discuss.flarum.org/system/core/vendor/s9e/text-formatter/src/Renderer.php on line 20

Warning: DOMDocument::loadXML(): Premature end of data in tag p line 1 in Entity, line: 1 in /home/forge/discuss.flarum.org/system/core/vendor/s9e/text-formatter/src/Renderer.php on line 20

Warning: DOMDocument::loadXML(): Premature end of data in tag r line 1 in Entity, line: 1 in /home/forge/discuss.flarum.org/system/core/vendor/s9e/text-formatter/src/Renderer.php on line 20
```

![9c746789823d857e1cd912f8745ecf6c](https://cloud.githubusercontent.com/assets/1168049/9279434/38bcc484-42c0-11e5-9acb-4c9e27e6ffd9.png)

**Comment by Felli** [comment]
I'll confirm this is also happening to me.

**Comment by s9e** [comment]
@tobscure Can you send me the XML please? If that's not an issue with the DB I'm very interested in how that could happen.

**Comment by tobscure** [comment]
@s9e Ah you're right, it's probably a truncation error. I deleted the data but when I looked there were no </ending> tags.
