### ISSUE TITLE
Discussion list sidebar disappears after reloading the discussion page

### ISSUE THREAD

**Issue by CWKevo** [flarum/core#2356]
## Bug Report

**Current Behavior**
Discussion list side panel is not accessible after discussion page reloads.

**Steps to Reproduce**
1. From the main page of your forum, go to any discussion.
2. Hover to the middle-left of the screen - a sidebar with discussion list should appear:

![image](https://user-images.githubusercontent.com/39010496/95012581-17acc300-063a-11eb-95c6-fee9f6567f4b.png)

3. Reload the current page/discussion using F5.
4. The sidebar is not accessible, or no longer exists, not even after it was pinned

**Expected Behavior**
The sidebar appears.

**Screenshots**
--- || ---

**Environment**
- Flarum version: beta.13
- Website URL: https://discuss.flarum.org (replicable on Discuss)
- Webserver: N/A
- Hosting environment: N/A
- PHP version: Probably 7.2
- Browser: Chrome 85.0.4183.121, 64-bit; also replicable on Microsoft Edge 85.0.564.68, 64-bit (because it is a Chrome ripoff bruh but let's stick to the topic)

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

N/A

**Possible Solution**
In order to fix this bug, you must first fix this bug in order for it to be fixed.

**Additional Context**
The sidebar reappears when you get outside of the discussion (eg. by using the back button to get to the main forum page) and then re-visiting the discussion page.

**Comment by matteocontrini** [comment]
Duplicate of flarum/issue-archive#396.

**Comment by SKevo18** [comment]
Now I see, also flarum/framework#1993. Didn't knew it was already opened before.
