### ISSUE TITLE
[Frontend Rewrite] History oninit bugs

### ISSUE THREAD

**Issue by w-4** [flarum/core#2368]
## Bug Report

**Current Behavior**
`app.history.push` is currently called from `oninit`. This won't update between changes to the same route. It leads to an issue where the back button on the discussion page brings you back to the wrong index page. 

**Steps to Reproduce**
As an example: 
1. Go to https://nightly.flarum.site
2. Search for something and search for all discussions.
3. Click on a search result in the discussion list
4. Click Back - the back button just redirects to the first loaded site https://nightly.flarum.site without the search query
5. Discussion list is not filtered anymore. 

**Possible Solution**
Moving `app.history.push` calls into `onNewRoute`.
Prerequisite: https://github.com/flarum/core/pull/2359

**Comment by askvortsov1** [comment]
Unfortunately it looks like the frontend rewrite has amplified some of the issues with the internal history system and back button. flarum/issue-archive#357 also comes to mind. I think that in future betas we might want to replace our internal history system with just calling the browser's history API. To be completely honest, that seems to be working better anyways (the browser's back button often makes more sense than Flarum's.
