### ISSUE TITLE
Email validation error does not appear if the domain extension is intentionally left out

### ISSUE THREAD

**Issue by Ralkage** [flarum/core#2370]
## Bug Report

**Current Behavior**
For the email input field, email validation error does not appear if the domain extension is intentionally left out.

**Steps to Reproduce**
1. Log out of your current session.
2. Click on "Sign Up".
3. Fil out the username and password fields with dummy credentials.
4. Fill out the email field and omit the domain extension at the end (i.e. ralkage@flarum).
5. Click on "Sign Up".

**Expected Behavior**
A "The email must be a valid email address" validation error should appear when the domain extension is left out of the email address field.

**Screenshots**
<details>
<summary>Beta 13</summary>

![image](https://user-images.githubusercontent.com/2059356/95355217-4a052d00-0893-11eb-8104-c6b64f7b4665.png)
![image222](https://user-images.githubusercontent.com/2059356/95355398-859ff700-0893-11eb-9794-bf48bb9eadba.png)
![image](https://user-images.githubusercontent.com/2059356/95368487-344c3380-08a4-11eb-9af4-8c457f7fae75.png)
</details>

<details>
<summary>Beta 14</summary>

![image](https://user-images.githubusercontent.com/2059356/95355803-f6dfaa00-0893-11eb-8abb-70bc3a5acce7.png)
![image](https://user-images.githubusercontent.com/2059356/95355824-fd6e2180-0893-11eb-9071-cb4095c431e0.png)
![image](https://user-images.githubusercontent.com/2059356/95355846-019a3f00-0894-11eb-99a6-cbcef2d078d1.png)
![image](https://user-images.githubusercontent.com/2059356/95368542-43cb7c80-08a4-11eb-93dd-ebbb6dfefb22.png)
</details>

**Environment**
- Flarum version: v0.1.0-beta.14
- Website URL: https://qa.flarum.site
- Webserver: Nginx
- Hosting environment: Unknown
- PHP version: 7.3.11
- Browser: Microsoft Edge Version 85.0.564.70 (Official build) (64-bit)

**Possible Solution**

N/A

**Additional Context**
This occurs on any modal that allows the ability to add, remove, or edit a user's email address such as the Sign Up, Edit User, and Edit Email modals (see screenshots).

**Comment by askvortsov1** [comment]
This seems to be a (somewhat controversial) change in Laravel's validator logic:

- https://github.com/laravel/framework/issues/28316
- https://github.com/octobercms/october/issues/5070
- https://github.com/laravel/framework/issues/27875

**Comment by askvortsov1** [comment]
Closed in https://github.com/flarum/core/commit/962b49567c8eb13bf6323efadc135244ae12982d
