### ISSUE TITLE
Unable to search for users with specific permissions setup

### ISSUE THREAD

**Issue by Ralkage** [flarum/core#2372]
## Bug Report

**Current Behavior**
In beta 14,  when "View discussions" permission is set to groups other than "Everyone" and "View user list" permission is set to "Everyone", users aren't able to search for other users.

**Steps to Reproduce**
1. Go to the Admin area.
2. Click on "Permissions"
3. Set "View discussions" to "Members" 
4. Set "View user list" to "Everyone".
5. Open a private/incognito browser session.
6. Visit the forum as a guest.
7. Search for an existing user using the forum search feature.

**Expected Behavior**
You should be able to search for users even when View discussions" permission is set to groups other than "Everyone" and "View user list" permission is set to "Everyone"  and "View user list" permission is set to "Everyone".

**Screenshots**
<details>
<summary>Beta 13</summary>

![image](https://user-images.githubusercontent.com/2059356/95362059-89d01280-089b-11eb-8488-24f648961874.png)
![image](https://user-images.githubusercontent.com/2059356/95361952-63aa7280-089b-11eb-9459-1e540bbc090b.png)
</details>

<details>
<summary>Beta 14</summary>

![image](https://user-images.githubusercontent.com/2059356/95362380-019e3d00-089c-11eb-8c1a-12bdae605945.png)
![image](https://user-images.githubusercontent.com/2059356/95362400-07941e00-089c-11eb-90eb-0eb64208e972.png)
![image](https://user-images.githubusercontent.com/2059356/95362465-1f6ba200-089c-11eb-84cb-5f3fd0852288.png)

</details>

**Environment**
- Flarum version: v0.1.0-beta.14
- Website URL: https://qa.flarum.site
- Webserver: Nginx
- Hosting environment: Unknown
- PHP version: 7.3.11
- Browser: Microsoft Edge Version 85.0.564.70 (Official build) (64-bit)

**Possible Solution**

N/A

**Additional Context**
~~Still have to test this issue when "View discussions" permission is set to other groups such as Admins, Mods, etc.~~ Confirmed.

**Comment by askvortsov1** [comment]
We have 2 options for fixing this:

1. In https://github.com/flarum/core/blob/master/src/User/UserPolicy.php#L37-L46, replace `$actor->cannot('viewDiscussions')` with `$actor->cannot('viewDiscussions') && $actor->cannot('viewUserList')`. That way, people could search for users, but their profiles would all be empty

2. Make `viewDiscussions` a prerequisite permission for `viewUserList`. As discussed in #1680, the `viewDiscussions` permission would be more accurately named `viewForum`.

**Comment by clarkwinkelmann** [comment]
I have a hard time wrapping my head around this.

This seems to be **intended** behavior following the changes we made in #2305 . It's just the "pre-requisite" part that's not made obvious via the admin UI.

But I prefer solution number one. It preserves most of the old behavior, while allowing access to profiles even if user listing is disabled. But I say we also add a comment above the test saying something like "viewDiscussions is used here to control whether direct access to any profile is allowed"

Maybe even better, refactor the code to use positives instead of negatives, something like

```php
        // This check is already made in ListUsersController but we repeat it so it applies to direct user profile as well
        if ($actor->can('viewUserList')) {
            return; // Allow seeing everything without restriction
        }

        // Even if user listing is disabled, we still want to allow direct access to user profiles when access to the forum is granted
        if ($actor->can('viewDiscussions')) {
            return; // Allow seeing everything without restriction
        }

        // If neither user listing or forum access is granted, we hide all profiles from guests
        if ($actor->isGuest()) {
            $query->whereRaw('FALSE');
            return;
        }

        // We always allow logged in users to see themselves
        $query->where('id', $actor->id);
```

**Comment by askvortsov1** [comment]
The only concern I have about solution 1 is that profiles would be largely empty (and would have misleading post/discussion counts, as those aren't generated per-visitor). That being said, configuring settings like this is a deliberate choice that a forum admin would make, so I'm assuming they would be aware of the implications.

I also like the more exlicit rewrite of the code, makes things clearer to readers
