### ISSUE TITLE
Adding a Custom Header in Admin area under Appearance does not place contents above Flarum's header

### ISSUE THREAD

**Issue by Ralkage** [flarum/core#2373]
## Bug Report

**Current Behavior**
In beta 14,  when you add content to the Custom Header in the Admin area under Appearance, the contents are not placed above Flarum's own header as indicated in the helper text.

**Steps to Reproduce**
1. Go to the Admin area.
2. Click on "Appearance".
3. Click on "Custom Header".
4. Enter some random HTML such as `<h1>Custom Header Test</1>`.
5. Click on "Save Changes".
6. Exit the Admin area and go back to the forum view.
7. Locate the Custom Header you just added.

**Expected Behavior**
The Custom Header you set should appear above Flarum's  own header and not within the PrimaryHeader.

**Screenshots**
<details>
<summary>Beta 13</summary>

![image](https://user-images.githubusercontent.com/2059356/95367168-6b214a00-08a2-11eb-8523-c4772d6aa50b.png)
![image](https://user-images.githubusercontent.com/2059356/95367118-5775e380-08a2-11eb-8775-e1627d957907.png)
</details>

<details>
<summary>Beta 14</summary>

![image](https://user-images.githubusercontent.com/2059356/95367237-80967400-08a2-11eb-9b69-12f04a9ef225.png)
![image](https://user-images.githubusercontent.com/2059356/95367012-38775180-08a2-11eb-9b14-6f5d5b61288d.png)</details>

</details>

**Environment**
- Flarum version: v0.1.0-beta.14
- Website URL: https://qa.flarum.site
- Webserver: Nginx
- Hosting environment: Unknown
- PHP version: 7.3.11
- Browser: Microsoft Edge Version 85.0.564.70 (Official build) (64-bit)

**Possible Solution**

N/A

**Additional Context**
N/A

**Comment by SychO9** [comment]
I believe this was fixed by #2371
