### ISSUE TITLE
Preview button seems to be broken

### ISSUE THREAD

**Issue by DCSJAPAN** [flarum/core#238]
In [the spam thread](http://discuss.flarum.org/d/529/comfortable-to-get-color-treated-tresses/3) the preview button acting like a link to the top post.

In [this thread](http://discuss.flarum.org/d/355/state-of-the-beta/76) it jumps up a ways, then back down again ... but doesn't actually show the reply.

**Comment by s9e** [comment]
It works for me. Check out your browser's console, see if there's an error there.

**Comment by DCSJAPAN** [comment]
No, no errors in there.

I've just upgraded to Safari 7.1.8 ... perhaps that has something to do with it?

**Comment by tobscure** [comment]
Confirmed

**Comment by s9e** [comment]
Oh ok, I misread it as "the Reply button." The preview button doesn't work for me either, I was thinking of the Reply button. Sorry for the confusion.

**Comment by Mecvak** [comment]
Those links are broken
Rather then -> http://discuss.flarum.org/d/355/state-of-the-beta/76
It should be -> http://discuss.flarum.org/d/355-state-of-the-beta/76

**Comment by franzliedke** [comment]
Yeah, we recently changed the URL scheme, most likely all old links will be dead now :-/
