### ISSUE TITLE
[Mobile] Mark Read Slidable Gesture not working

### ISSUE THREAD

**Issue by SychO9** [flarum/core#2380]
## Bug Report

**Current Behavior**
When sliding a discussion to the right on a touchscreen, the markread method is not executed, therefore not marking the discussion read.

**Steps to Reproduce**
1. Go to the discussion list.
2. Slide an unread discussion to the right.
3. The discussion is still marked unread.

**Expected Behavior**
It should be marked read

**Screenshots**

**Environment**
- Flarum version: https://github.com/flarum/core/commit/656409794c38d2d0545e44d54c4aa817242fecf3

**Possible Solution**
Changing the anchor to a span (for example) seems to fix the issue
https://github.com/flarum/core/blob/656409794c38d2d0545e44d54c4aa817242fecf3/js/src/forum/components/DiscussionListItem.js#L94-L99

Or changing 
https://github.com/flarum/core/blob/656409794c38d2d0545e44d54c4aa817242fecf3/js/src/forum/utils/slidable.js#L129
To
```js
$underneath[0].click();
```

**Additional Context**
I think a change from the Mithril 2 update might have affected it, because it was working a little while back.

**Comment by askvortsov1** [comment]
Changing it to a span makes sense to me
