### ISSUE TITLE
Extensions settings not accessible

### ISSUE THREAD

**Issue by maicol07** [flarum/core#2386]
## Bug Report

**Current Behavior**
The more menu of an extension is empty (screenshot 1).
If you zoom in or out the page the settings entry become visible and clickable (screenshot 2)

**Steps to Reproduce**
1. Go to Extensions
2. Enable an extension like tags
3. Open the more menu
4. See empty menu

**Expected Behavior**
Settings menu entry shows (screenshot 2)

**Screenshots**
1.
![immagine](https://user-images.githubusercontent.com/9463142/95777561-b71b2700-0cc6-11eb-8753-8f1c8e5df7c8.png)

2.
![immagine](https://user-images.githubusercontent.com/9463142/95777707-006b7680-0cc7-11eb-8f71-75161ca30a20.png)

**Environment**
- Flarum version: 0.1.0-beta13
- Website URL: localhost
- Webserver: Apache
- Hosting environment: XAMPP
- PHP version: 7.4.5
- Browser: Mozilla Firefox 81.0.1

```
Flarum core 0.1.0-beta.13
PHP version: 7.4.5
Loaded extensions: Core, bcmath, calendar, ctype, date, filter, hash, iconv, json, SPL, pcre, readline, Reflection, session, standard, mysqlnd, tokenizer, zip, zlib, libxml, dom, PDO, bz2, SimpleXML, xml, xmlreader, xmlwriter, openssl, curl, FFI, ftp, fileinfo, gd, gettext, gmp, intl, imap, ldap, mbstring, exif, mysqli, odbc, Phar, pdo_mysql, pdo_sqlite, shmop, soap, sockets, sodium, tidy, xmlrpc, xsl, xdebug
+-------------------------+------------------+--------+
| Flarum Extensions       |                  |        |
+-------------------------+------------------+--------+
| ID                      | Version          | Commit |
+-------------------------+------------------+--------+
| flarum-approval         | v0.1.0-beta.13   |        |
| flarum-bbcode           | v0.1.0-beta.12   |        |
| flarum-emoji            | v0.1.0-beta.13   |        |
| flarum-lang-english     | v0.1.0-beta.13   |        |
| flarum-flags            | v0.1.0-beta.13   |        |
| flarum-likes            | v0.1.0-beta.13   |        |
| flarum-lock             | v0.1.0-beta.13   |        |
| flarum-markdown         | v0.1.0-beta.13   |        |
| flarum-mentions         | v0.1.0-beta.13   |        |
| flarum-statistics       | v0.1.0-beta.13   |        |
| flarum-sticky           | v0.1.0-beta.13   |        |
| flarum-subscriptions    | v0.1.0-beta.13   |        |
| flarum-suspend          | v0.1.0-beta.13   |        |
| flarum-tags             | v0.1.0-beta.13.2 |        |
| maicol07-sso            | dev-master       |        |
| dem13n-nickname-changer | 0.2              |        |
+-------------------------+------------------+--------+
Base URL: https://flarum.local.dev
Installation path: D:\xampp\htdocs\flarum
Debug mode: ON
Don't forget to turn off debug mode! It should never be turned on in a production system.
```

**Comment by tankerkiller125** [comment]
What screen size does this happen on? Given that it can be fixed with zoom settings it may be a responsive screen issue and I want to make sure we can replicate this in some way.

**Comment by maicol07** [comment]
1920 x 1080

I can confirm that sizes lower than 1600 (width) works well.

The only issue with lowest sizes (like smartphones) is that they can't press the more button

**Comment by askvortsov1** [comment]
No longer applicable as of #2409
