### ISSUE TITLE
Sub-tags bug in chrome

### ISSUE THREAD

**Issue by tarunmarkose** [flarum/core#239]
The "Installation" subtag of "Support" on the demo site opens wrongly under "Dev". This happens for me while using Chrome. Firefox and Safari, are fine.

![screenshot 2015-08-20 13 04 05](https://cloud.githubusercontent.com/assets/7383852/9378054/0e9d89e2-473c-11e5-8956-7b64c028680c.png)

**Comment by tarunmarkose** [comment]
Hey, @tobscure if you are not fixing this before the beta release, I and my colleague @ishanAhuja could try and take care of it. Let me know.

**Comment by tobscure** [comment]
Go for it! Relevant file is js/lib/utils/sortTags in the flarum/tags repo.

**Comment by tobscure** [comment]
This issue was moved to flarum/tags#17
