### ISSUE TITLE
[Mentions] [Intervention] Ignored attempt to cancel a touchstart event with cancelable=false

### ISSUE THREAD

**Issue by SychO9** [flarum/core#2392]
## Bug Report
Not exactly a bug but an error in the console when clicking on a post mention on a touchscreen device.

```
[Intervention] Ignored attempt to cancel a touchstart event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
```

**Steps to Reproduce**
1. Go to a discussion on a touchscreen device
2. Click on a post mention
3. See error in console

**Environment**
- Flarum version: beta-14 https://github.com/flarum/core/commit/a3bd431503a6abfbd9e6639336ff437d4819a704
- Browser: Chrome 84.0.4147.105
- OS: Ubuntu 18.04.4 LTS

**Possible Solution**
Need to check that the event is cancelable before calling `preventDefault()`

https://github.com/flarum/mentions/blob/f76ef5dc88dad489bf8fa0deae0d7114d39309e2/js/src/forum/addPostMentionPreviews.js#L106

**Comment by Ralkage** [comment]
Hi, can you tell us which mobile browser and OS can we reproduce this on?

Additionally, can you tell us which Flarum version(s) you got this error in?

**Comment by SychO9** [comment]
my bad, I forgot to past the exact flarum version. I also added the browser version, however it's the desktop browser, I noticed the error while emulating a touchscreen device with the dev tools.
