### ISSUE TITLE
[Suspend] Error thrown when clicking on Suspension notification

### ISSUE THREAD

**Issue by Ralkage** [flarum/core#2393]
## Bug Report

**Current Behavior**
In beta 14, when a suspended user clicks on the notification letting them know that they are suspended or unsuspended, an error is thrown in the console.

**Steps to Reproduce**
1. Log into an account that is able to suspend users.
2. Pick a dummy user to suspend and suspend indefinitely.
3. Log out or open a private/incognito browser session.
4. Log in with the dummy suspended user's account.
5. Open up your browser dev tools/console tab.
6. Click on the new suspend notification.
7. Error is thrown but the user is still able to visit their profile from clicking on the notification. 

**Expected Behavior**
Not sure how this is supposed to behave other than it not throwing an error message when the notification is clicked on and set to a read state.

**Screenshots**
![image](https://user-images.githubusercontent.com/2059356/96156657-51ee4e00-0edf-11eb-9df1-540c7e5b0af6.png)

**Environment**
- Flarum version: v0.1.0-beta.14
- Website URL: https://qa.flarum.site
- Webserver: Nginx
- Hosting environment: Unknown
- PHP version: 7.3.11
- Browser: Firefox Developer Edition v82.0b9 (64-bit)

**Comment by askvortsov1** [comment]
Seems to be something wonky with firefox, I'm not seeing this on chrome.
