### ISSUE TITLE
Improve discussion page near canonical url

### ISSUE THREAD

**Issue by w-4** [flarum/core#2397]
## Bug Report

**Current Behavior**
In beta.13 and beta.14, there is a canonical url included in the hmtl document. 
For example for  https://discuss.flarum.org/d/187-word-association-game/1000 
the canonical url is https://discuss.flarum.org/d/187-word-association-game?near=1000

As per https://github.com/flarum/core/issues/189#issuecomment-709429091 this causes search engines to crawl that URL.

Edit: the redirect works, my link was just broken.

**Comment by w-4** [comment]
We could do it the way the Discourse does. They also use a postnumber for the URL, but use a `page` parameter in the canonical url. 
As an example:
For the first 20 posts the canonical would be  https://discuss.flarum.org/d/187-word-association-game
for the next 20, it would be https://discuss.flarum.org/d/187-word-association-game?page=2

That is probably better for SEO, because of less links and no overlap.

**Comment by davwheat** [comment]
I'm really confused by this. What's the issue here?

Using the `/d/1233456/100` syntax could make search engines think it's a totally separate page from `/d/123456` causing page duplication.

We should keep that canonical to prevent that, but we should also add `rel=next` to link to the page before that.

It might be work replacing this canonical with a `?page=x`-based one, though, as the `?near=1000` seems to take me to post 950...

**Comment by enricoeur** [comment]
This is big mistake. Really i dont understand why was not fixed...

**Comment by askvortsov1** [comment]
> I'm really confused by this. What's the issue here?
> 
> Using the `/d/1233456/100` syntax could make search engines think it's a totally separate page from `/d/123456` causing page duplication.
> 
> We should keep that canonical to prevent that, but we should also add `rel=next` to link to the page before that.
> 
> It might be work replacing this canonical with a `?page=x`-based one, though, as the `?near=1000` seems to take me to post 950...

I like using `page=x` as the canonical URL. Post numbers can be messy.

I'll also note that the current no-js approach is missing next page / prev page buttons. THAT is quite problematic, and something that definitely needs to be fixed before stable.

**Comment by askvortsov1** [comment]
When redesigning, we should also make sure to fix https://github.com/flarum/core/issues/2130

**Comment by askvortsov1** [comment]
https://github.com/flarum/core/blob/f2168f939db15f58c1511b56b4d95c737b62ce1a/views/frontend/content/discussion.blade.php#L18-L24 is incorrect, because there won't be prev/next links on the API document for a single item. That's what's causing the missing pagination links.
