### ISSUE TITLE
Sign in issues on Edge

### ISSUE THREAD

**Issue by mbp41** [flarum/core#240]
When signing into Flarum on MS Edge, it will always say wrong password, even if it is correct, I think this has something to do with it appearing like the username disappears when one clicks log in. For some strange reason, if the password is saved in Edge, sign in will work.
Also, once one is logged in, they do not stay logged in.

**Comment by Felli** [comment]
Tried myself and logged in, tho I did see that there were problems trying to login, took a few times (2 attempts max.) but I did in fact login on MS Edge, you most likely do like most people do and miss clicked something or something along the lines of this, other than that I can use MS Edge fine.

**Comment by Felli** [comment]
Might wanna add that tags are off even in MS Edge. lol
![image](https://cloud.githubusercontent.com/assets/2011633/9409576/58383144-47d0-11e5-8b32-47690040d942.png)

**Comment by brainscript** [comment]
@Felli Use [Firefox](http://firefox.com)! :smile_cat::neckbeard:

**Comment by Felli** [comment]
@brainscript that's not the issue at hand. Also Firefox has it's own problems with Flarum, like sometimes blocking JavaScript. lol

**Comment by tobscure** [comment]
I believe this was fixed as part of #464
