### ISSUE TITLE
Toggling notifications results in duplicate icons

### ISSUE THREAD

**Issue by sburkett** [flarum/core#2400]
## Bug Report

**Current Behavior**
Clicking to enable or disable a certain type of notification in your user settings results in multiple X and checkmark icons being displayed. If you continue to click the notification toggle, the color will alternate between red and green, but you end up with duplicate icons.

**Steps to Reproduce**
1. Login
2. Click your avatar, then settings
3. Scroll down to "Notifications"
4. Click to enable or disable any of them (web or email)

**Expected Behavior**
The single icon should change along with the color

**Screenshots**
![image](https://user-images.githubusercontent.com/2219483/96651266-7349a280-1302-11eb-97a8-6cc40eeb4e80.png)

**Environment**
- Flarum version: Flarum core 0.1.0-beta.13
- Website URL: Local for now, not yet live
- Webserver: Apache
- Hosting environment: Linode dedicated
- PHP version: 7.2.34
- Browser: Version 86.0.4240.75 (Official Build) (64-bit) (also happens on other browsers I've tested as well)

```
Flarum core 0.1.0-beta.13
PHP version: 7.2.34
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, libsodium, apcu, bcmath, bz2, calendar, ctype, curl, dba, dom, enchant, mbstring, fileinfo, ftp, gd, geoip, gettext, gmp, iconv, igbinary, imagick, json, exif, mysqlnd, mysqli, odbc, PDO, pdo_dblib, pdo_mysql, PDO_ODBC, pdo_sqlite, Phar, posix, pspell, recode, redis, shmop, SimpleXML, snmp, soap, sockets, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, wddx, xmlreader, xmlwriter, xsl, memcached, zip, Zend OPcache, xdebug
+-----------------------------------+------------------+--------+
| Flarum Extensions                 |                  |        |
+-----------------------------------+------------------+--------+
| ID                                | Version          | Commit |
+-----------------------------------+------------------+--------+
| flarum-approval                   | v0.1.0-beta.13   |        |
| flarum-bbcode                     | v0.1.0-beta.12   |        |
| flarum-emoji                      | v0.1.0-beta.13   |        |
| flarum-lang-english               | v0.1.0-beta.13   |        |
| flarum-flags                      | v0.1.0-beta.13   |        |
| flarum-likes                      | v0.1.0-beta.13   |        |
| flarum-lock                       | v0.1.0-beta.13   |        |
| flarum-markdown                   | v0.1.0-beta.13   |        |
| flarum-mentions                   | v0.1.0-beta.13   |        |
| flarum-statistics                 | v0.1.0-beta.13   |        |
| flarum-sticky                     | v0.1.0-beta.13   |        |
| flarum-subscriptions              | v0.1.0-beta.13   |        |
| flarum-suspend                    | v0.1.0-beta.13   |        |
| flarum-tags                       | v0.1.0-beta.13.2 |        |
| fof-user-directory                | 0.3.4            |        |
| clarkwinkelmann-create-user-modal | 1.0.1            |        |
| reflar-doorman                    | 0.1.6            |        |
| fof-user-bio                      | 0.2.0            |        |
| fof-links                         | 0.3.0            |        |
| fof-polls                         | 0.1.2            |        |
| fof-pages                         | 0.4.0            |        |
| fof-formatting                    | 0.1.5            |        |
| fof-drafts                        | 0.1.13           |        |
| fof-terms                         | 0.4.3            |        |
| fof-upload                        | 0.10.0           |        |
| fof-reactions                     | 0.3.4            |        |
| fof-masquerade                    | 0.3.4            |        |
| fof-profile-image-crop            | 0.1.2            |        |
| fof-merge-discussions             | 0.3.3            |        |
| fof-split                         | 0.4.4            |        |
| fof-byobu                         | 0.5.6            |        |
+-----------------------------------+------------------+--------+
Base URL: http://localhost
Installation path: /var/www/tmv
Debug mode: ON
```

**Possible Solution**

**Additional Context**

**Comment by askvortsov1** [comment]
Huh, this is an interesting one. I feel like this shouldn't be possible in the new beta 14, because there can at most be 1 checkbox per-setting (since components aren't stored anymore since #2183). Could you try to replicate on https://nightly.flarum.site?

**Comment by sburkett** [comment]
Just tested there and it worked fine. Actually, I think I know what it might be. Let me look at something.

Yep, I was right. Did a little debugging. I had added a JS script include for FontAwesome 5 in my custom footer (I'm a pro customer, and needz my iconz).

As you probably know they changed quite a bit about how the icons are handled in FA 5. I removed it as a test, and it works fine. So it was a conflict there.

I really want to find a seamless way to incorporate FA Pro, but I really dislike the idea of slapping around with stuff in `vendor` for the obvious reasons.

I suppose one approach would be to just add a toggle in the Appearance admin page which would allow you to conditionally compile in the free FA as a default action. Toggling it off would require you to handle it yourself in the custom header/footer or something.

I'm open to any ideas or suggestions. I'm a dev by trade, and do a lot of design work as well, but `less` stuff, mixins, etc. is not something I've really had a chance to fully explore.

**Comment by askvortsov1** [comment]
I'm going to close this as icon duplication isn't really a core issue, but feel free to open a new issue about FA Pro icons: I agree that it would be nice to support those (feel free to just copy-paste your last comment for that issue).
