### ISSUE TITLE
[Akismet] Call API manually, take advantage of features not supported by the current library

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#2405]
We are currently using https://github.com/tijsverkoyen/Akismet , which has not seen any update in the last 8 years. There isn't much activity in the GitHub, and the documentation is down.

We only use [one single API endpoint](https://akismet.com/development/api/#comment-check), which we could easily call with Guzzle.

One downside of using tijsverkoyen's library is that server headers are directly fetched from `$_SERVER`, which completely skips our middleware stack. So for example extensions altering the user IP aren't taken into account (for example, a theoretical Cloudflare IP restore extension).

By calling the API directly, we could take advantage of features not implemented in tijsverkoyen's library, like `X-akismet-pro-tip` that allows discarding "obvious spam" https://blog.akismet.com/2014/04/23/theres-a-ninja-in-your-akismet/ This could be a new setting that directly soft-deletes the posts / suspends the user instead of marking them for approval.

Other interesting API parameters are `blog_lang` which could be set to the forum language, and `is_test` which could be set when debug mode is on.

`user_role` could be used to always approve administrators, though I think our strategy here is to make the check on the Flarum side and not send any API query at all if the user can skip the check.

**Comment by iPurpl3x** [comment]
Is this still going to make it for 1.2 @luceos ?

**Comment by askvortsov1** [comment]
> Is this still going to make it for 1.2 @luceos ?

Almost certainly not for 1.2 at this point.

**Comment by rafaucau** [comment]
@askvortsov1 If we help update this extension, it will be for 1.2?

**Comment by askvortsov1** [comment]
We're currently in feature freeze for v1.2, but tbh since it's not core, we could publish a release of just akismet separately.

**Comment by davwheat** [comment]
If agree with @askvortsov1. Separate release of Akismet is very much possible.
