### ISSUE TITLE
Symfony Package Version Self/Laravel Inconsistency Causing Composer Conflicts

### ISSUE THREAD

**Issue by KyrneDev** [flarum/core#2406]
## Bug Report

**Current Behavior**
Symfony dependencies cause version conflicts with the rest of the Laravel 6 suite.

**Steps to Reproduce**
1. Require a package like `illuminate/routing` (^6.0)
2. This package requires `symfony/config` (^4.3.4) which can't be installed because Flarum sets it to only 3.0 versions

Ext 2. 
1. Require `illuminate/http` (^6.0)
2. This package requires 2 Symfony packages both ^4.3.4 which again conflicts with any 3.0 Symfony package Flarum requires

**Expected Behavior**
The Symfony packages should all be the same major version to prevent conflicts and for full Laravel 6 support.

**Environment**
- Flarum version: beta 14

**Additional Context**
Trying to use non-bundled Laravel packages and cannot because of the various Symfony conflicts.

**Comment by luceos** [comment]
Laravel framework 6.x: https://github.com/laravel/framework/blob/6.x/composer.json#L34-L42
