### ISSUE TITLE
CommentPost content script tags not executed during oncreate

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#2412]
## Bug Report

**Current Behavior**
When a post is loaded and its template contains javascript, the javascript doesn't run until the post experiences an onupdate cycle.

This can be experienced with syntax-highlighted code blocks, but probably also other extensions.

**Steps to Reproduce**
1. Create post with code block
2. Refresh page
3. See post is not highlighted

This can probably be reproduced with other community extensions. I think the code block is the only one from core with javascript in the template itself.

**Expected Behavior**
Javascript should run during the first render

**Screenshots**
![image](https://user-images.githubusercontent.com/5264300/97117463-403d4f80-1704-11eb-8098-bd79fbbcadf5.png)

**Environment**
- Flarum version: beta 14
- Website URL: tested locally

**Possible Solution**
We need to call the code from `onupdate` in `oncreate`. Previously that code ran in `config` without any regard to `isInitialized`.

Beta 13 code

https://github.com/flarum/core/blob/fd371c1203439810af8f6814cdff402faebf4126/js/src/forum/components/CommentPost.js#L57-L72

Current code

https://github.com/flarum/core/blob/c9a04fe009abf474b39f562e9d4bf13c5ecf25c8/js/src/forum/components/CommentPost.js#L59-L74

While we're at it, I think we should also call `super.onupdate` with a `vnode` parameter. If an extension was to extend `Post.prototype.onupdate`, they wouldn't be able to access `vnode` because `CommentPost` forgets to pass it up.

**Additional Context**
Reported by RebelCoderRU here https://discuss.flarum.org/d/25227-code-highlighting-not-working-properly-on-beta-14

**Comment by askvortsov1** [comment]
Unfortunately this doesn't fix the issue. From local testing, code blocks are highlighted during editing and not on a regular page because its shown in the `ComposerPostPreview` component. This chunk of code does nothing in beta 14 (which is probably the issue)
