### ISSUE TITLE
Day.js plugins and Typescript

### ISSUE THREAD

**Issue by lhsazevedo** [flarum/core#2417]
_Originally posted at #2391_

Even not using directly, we need to import relativeTime dayjs plugin at `js/src/common/utils/humanTime.ts`. Without this import, typescript can't pick up tipes for the [fromNow()](https://github.com/flarum/core/blob/2ff46f5a2ebe2532f780f6e60a921beb41876d69/js/src/common/utils/humanTime.ts#L32) method and complains.
The code still works though, because relativeTime plugin is installed at `js/src/common/index.js`:

https://github.com/flarum/core/blob/2ff46f5a2ebe2532f780f6e60a921beb41876d69/js/src/common/index.js#L12-L16

We can avoid this import if we move this plugin installation process to a separated dayjs library module, something like:
```typescript
// js/src/common/lib/dayjs.ts

import dayjs from 'dayjs'
import relativeTime from 'dayjs/plugin/relativeTime';

dayjs.extend(relativeTime)

export default dayjs


// js/src/common/utils/humanTime.ts

// no need import relativeTime from 'dayjs/plugin/relativeTime';
import dayjs from '../../common/lib/dayjs'
```

**Comment by davwheat** [comment]
A better option is to include this plugin in the TS global typings file we have jQuery and such in at the moment.

**Comment by lhsazevedo** [comment]
I would like to try this! Would you mind if I do?

**Comment by davwheat** [comment]
Go for it!
