### ISSUE TITLE
I am so excited about this FLARUM

### ISSUE THREAD

**Issue by rajjanorkar** [flarum/core#242]
Hi Team,

Great work when it is getting release.
at least can i use similar to http://discuss.flarum.org/  if you have code ready to install.

Thank you guys

keep up the great work.

**Comment by rajjanorkar** [comment]
Simply closed... :-1:

**Comment by solhuebner** [comment]
@rajjanorkar this is not an actual issue and he had to clean up a bit. Stay tuned :)
