### ISSUE TITLE
Custom homepage that is not a URL breaks the demo site.

### ISSUE THREAD

**Issue by tarunmarkose** [flarum/core#243]
If Custom Home Page is a non URL, it breaks the site at http://berlo.id.au/flarum. 

See screenshot below:

![screenshot 2015-08-24 18 20 16](https://cloud.githubusercontent.com/assets/7383852/9440469/f296c89a-4a8c-11e5-9f83-d6ab4f12a248.png)

**Comment by tobscure** [comment]
I don't think this is really an issue, it's just the way the setting works. If the admin screws it up, they'll quickly realise and can fix it in the admin CP.
