### ISSUE TITLE
[Pusher] Clicking refresh button results in an error.

### ISSUE THREAD

**Issue by SychO9** [flarum/core#2433]
## Bug Report

**Current Behavior**
With pusher, when a discussion is updated, a button appears to update the discussion list. That button currently does not work.

```
Uncaught TypeError: t.refresh is not a function
    at HTMLButtonElement.onclick (index.js:76)
    at _.handleEvent (render.js:888)
```

**Steps to Reproduce**
1. Enable and configure pusher.
2. Go to the discussion list.
3. Using a different account on another browser, simulate a notification.

**Environment**
- Flarum version: https://github.com/flarum/core/commit/5842dd120081eb93c2ecfbebcc4f92a2280e6a69
- Webserver: apache
- Hosting environment: localhost
- PHP version: 7.4.9
- Browser: Chrome 84

**Comment by askvortsov1** [comment]
Great catch, thanks!
