### ISSUE TITLE
Search terms starting with an asterisk `*` cause a js error

### ISSUE THREAD

**Issue by luceos** [flarum/core#2436]
## Bug Report

**Current Behavior**

When you search for any term starting with a `*` the component crashes.

**Steps to Reproduce**
1. Go to https://nightly.flarum.site
2. Open your browser console log
3. Click on the search bar, enter `*nominus`
4. Error occurs

**Expected Behavior**

No idea.

**Screenshots**

<img width="744" alt="image" src="https://user-images.githubusercontent.com/504687/97971042-be63bb00-1dc2-11eb-9cb2-4577a1703dd1.png">

Reported by @iPurpl3x

**Environment**
- Flarum version: x.y.z
- Website URL: http://nightly.flarum.site

**Comment by askvortsov1** [comment]
I am no longer able to replicate this on current nightly.
