### ISSUE TITLE
Consider switching cookie library

### ISSUE THREAD

**Issue by tankerkiller125** [flarum/core#2439]
Our current cookie library is fairly unmaintained and likely won't get PHP8.0 support listed in the composer.json file. This leaves us basically two options to fix the issue:

Option 1: Change the library, https://github.com/delight-im/PHP-Cookie looks pretty good just at a quick glance, this will require swapping out all internals and either making a BC layer or just out right breaking any extensions that set their own cookies.

Options 2: Fork the existing library, this has the benefit of no BC layer or breaking extension, but would require us to maintain the fork.

**Comment by askvortsov1** [comment]
I don't think a BC layer is needed here, but we also shouldn't maintain an extra library if that's not necessary. I would be good with switching to a more well-maintained library.

**Comment by tankerkiller125** [comment]
Looking deeper into the library I originally suggested it won't work because it lacks proper PSR7 support. I am continue my hunt for a good library.

**Comment by franzliedke** [comment]
PHP 8 support for the current cookies library is being worked on, see https://github.com/dflydev/dflydev-fig-cookies/issues/38 and the related PR.

**Comment by askvortsov1** [comment]
Looking at @luceos 's PHP 8 PR, the new proposed library seems simpler if anything, plus it's better maintained which is a huge plus in my books. I don't see why not to make the change.

**Comment by askvortsov1** [comment]
Since PHP 8 is now supported with our current library, this is a lot less urgent. The change might still be worth considering for reasons of maintainability, but that should be discussed (and PRed if we decide to do so) separately.
