### ISSUE TITLE
Sharing on Chrome Android takes the wrong URL

### ISSUE THREAD

**Issue by matteocontrini** [flarum/core#2440]
## Bug Report

**Current Behavior**

It seems that when using the share feature of Chrome mobile (on Android at least) the URL that is shared is the original one when the page was first loaded, and not the current one, that might have changed after navigating through the Flarum SPA.

This might well be a Chrome bug but maybe there's something that should be done on the Flarum side.

**Steps to Reproduce**
1. Go to https://nightly.flarum.site/ with Chrome on Android
2. Click on any discussion
3. Open the Chrome menu from the top right corner
4. Tap share and select a destination
5. Notice that the URL that is shared refers to the homepage and not to the discussion

**Expected Behavior**

The actual current URL should be shared.

**Environment**
- Flarum version: probably any version? Tested on nightly and beta13
- Browser: Chrome Android 86.0.4240.185

**Comment by askvortsov1** [comment]
We use Mithril for routing, core's only direct interaction with the browser's history API is updating the page title/url while scrolling in a discussion. This is most likely a Chrome issue, but if not, it's a mithril issue.

**Comment by datitisev** [comment]
Could it be caused by the canonical link that is added on page load for SEO?
