### ISSUE TITLE
Not having lifecycle method stubs on parent component create extensibility issues

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#2446]
Considering the example

```js
import {extend} from 'flarum/extend';
import Component from 'flarum/Component';
import HeaderPrimary from 'flarum/components/HeaderPrimary';

class ComponentA extends Component {
  view() {
    return m('div', 'A ' + this.attrs.content);
  }
}

class ComponentB extends ComponentA {
  onupdate() {
    console.log('ComponentB.onupdate ' + this.attrs.content);
  }
  view() {
    return m('div', 'B ' + this.attrs.content);
  }
}

app.initializers.add('extend-parent', () => {
  extend(HeaderPrimary.prototype, 'items', items => {
    items.add('a', m(ComponentA, {content: 'A'}));
    items.add('b', m(ComponentB, {content: 'B'}));
  });

  extend(ComponentA.prototype, 'onupdate', function() {
    console.log('ComponentA.onupdate extended ' + this.attrs.content);
  });
});
```

`ComponentB` never calls `ComponentA` `super.onupdate()` because `ComponentA` doesn't have such a method.

Now comes an extension that wants to run code on `onupdate` for both `ComponentA` and `ComponentB`. We expect `extend(ComponentA.prototype, 'onupdate', function () {})` to work.

However in practice, the `extend` will only execute for `ComponentA`, and never for `ComponentB`, where only the original `onupdate` executes.

In Flarum, this situation could happen when extensions extend core Flarum components, and another extension wants to extend the missing method on a core component.

One example is using `extend(Page.prototype, 'onupdate', function () {})`. It works fine with stock Flarum. But if an extension added a new page extending `Page` and adding `onupdate`, then the `extend` will never be called on that page.

To prevent this situation from happening, all components extending Flarum's `Component` should call `parent` methods. This means we need to add no-op methods for each Mithril lifecycle method on the base `Component` and ask extensions to always call `parent` even if the default is a no-op.

---

PS: I have also tested the opposite: extending a missing method on a child does work as expected already, because the parent prototype is copied down and calling `extend()` on a "non-existing" child method properly extends the one copied from the parent prototype.

**Comment by clarkwinkelmann** [comment]
I still think this is relevant

**Comment by askvortsov1** [comment]
I believe we should be able to add these stubs and super calls without much issue, since if something extending Component doesn't call super, it just won't do anything (nothing breaks)

**Comment by clarkwinkelmann** [comment]
Agreed. If do add them, we should still make sure to mention it in the release notes for developers.

Unfortunately I see no easy way of "deprecating" not calling the parent to warn developers of a missing call. And even if there was a way, not calling the parent is a legitimate use case as well. But you should call parent by default instead of the opposite to ensure extensibility.

We'll just need to specify it in the upgrade guide, and I'll be sure to open GitHub issues on any extension that doesn't follow it afterwards :rofl:

**Comment by askvortsov1** [comment]
But if the new parent methods are just empty stubs, I don't see why we'd even need to deprecate not calling it. It's not a functional change and doesn't break anything so BC doesn't really apply.

**Comment by clarkwinkelmann** [comment]
True, there's no backward compatibility concern here.

I'll need to check how many extensions are affected.

What I mean is, just adding the method won't solve the extensibility issue described above if there's a bunch of extensions around not calling the parent when they should. So we should make clear we expect extensions to call the parent in future Flarum versions, otherwise extension developers won't be able to reliably extend those lifecycle methods.
