### ISSUE TITLE
buggy mount-redraw.js preventing successful upgrade to beta 14

### ISSUE THREAD

**Issue by HLFH** [flarum/core#2447]
## Bug Report

**Current Behavior**
The forum homepage is not loading correctly after the upgrade to beta 14. 

**Steps to Reproduce**
1. Update your composer.json
2. Follow upgrade procedure to beta 14
3. Load the forum and connect if not connected yet to see private posts within the homepage
4. See error with posts not entirely loading with warning message

**Expected Behavior**
The forum homepage should load correctly after the upgrade to beta 14. 

**Environment**
- Flarum version: beta 14
- Website URL: https://forum.acsemb.org (mostly a private forum)
- Webserver: nginx
- Hosting environment: Dedicated server on Scaleway Dedibox, Archlinux
- PHP version: PHP 7.4.12 
- Browser: Chrome version 86.0.4240.111 (Official Build) (x86_64)

```
➜  forum sudo -u http php flarum info
Flarum core 0.1.0-beta.14.1
PHP version: 7.4.12
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, pcntl, SPL, PDO, bz2, posix, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, bcmath, Phar, curl, exif, ftp, gd, gettext, gmp, iconv, imap, intl, mysqli, pdo_mysql, pdo_sqlite, pspell, sockets, sqlite3, tidy, xmlrpc, zip, geoip, igbinary, imagick, mailparse, redis, Zend OPcache
+------------------------------+------------------+--------+
| Flarum Extensions            |                  |        |
+------------------------------+------------------+--------+
| ID                           | Version          | Commit |
+------------------------------+------------------+--------+
| flarum-approval              | v0.1.0-beta.14   |        |
| flarum-bbcode                | v0.1.0-beta.12   |        |
| flarum-flags                 | v0.1.0-beta.14.1 |        |
| flarum-likes                 | v0.1.0-beta.14   |        |
| flarum-lock                  | v0.1.0-beta.14   |        |
| flarum-mentions              | v0.1.0-beta.14   |        |
| flarum-sticky                | v0.1.0-beta.14   |        |
| flarum-suspend               | v0.1.0-beta.14   |        |
| flarum-tags                  | v0.1.0-beta.14   |        |
| flarum-subscriptions         | v0.1.0-beta.14   |        |
| cbmainz-de                   | 0.12.1           |        |
| flarum-markdown              | v0.1.0-beta.14   |        |
| flarum-statistics            | v0.1.0-beta.14   |        |
| flarum-emoji                 | v0.1.0-beta.14   |        |
| flarum-lang-english          | v0.1.0-beta.14.1 |        |
| fof-links                    | 0.4.0            |        |
| fof-transliterator           | 0.2.0            |        |
| fof-user-directory           | 0.3.4            |        |
| fof-byobu                    | 0.5.6            |        |
| fof-split                    | 0.5.0            |        |
| fof-upload                   | 0.11             |        |
| qiaeru-lang-french           | v1.8.1           |        |
| rooaaar-lang-french-extended | v1.16.0          |        |
| fof-user-bio                 | 0.3.1            |        |
+------------------------------+------------------+--------+
Base URL: https://forum.acsemb.org
Installation path: /srv/http/acsemb/forum
Debug mode: ON
```

**Possible Solution**
I don't know which extension is problematic/related to the bug yet.
I don't know if it is even a core issue.

**Additional Context**
This is what is saying Chrome web console:
```chrome
Uncaught Error: [e] The "children" attribute of attrs should never be used. Either pass children in as the vnode children or rename the attribute
at e.u.setAttrs (Component.ts:114)
at e.u.oninit (Component.ts:57)
at Function.a (render.js:30)
at M (render.js:917)
at render.js:153
at render.js:160
at l (render.js:66)
at u (render.js:50)
at render.js:134
at l (render.js:63)

mount-redraw.js:15 TypeError: Cannot read property 'onbeforeupdate' of undefined
at render.js:929
at f (render.js:407)
at h (render.js:302)
at render.js:477
at f (render.js:416)
at h (render.js:315)
at render.js:477
at f (render.js:416)
at h (render.js:302)
at render.js:477
a @ mount-redraw.js:15
```

**Comment by askvortsov1** [comment]
This is an issue with an extension that is using the unsupported "children" attr, not with core. You might want to go through your list of extensions and ensure that all have been updated for beta 14.

**Comment by HLFH** [comment]
All have been updated for beta 14, but I still have the bug and I am not the only one.

**Comment by askvortsov1** [comment]
Are you able to replicate this issue with on `https://beta.flarum.site/`? Or with all community extensions disabled? (Note that byobu is not beta 14 compatible). The reason why I am hesitant to reopen the issue is that we've been unable to replicate it with only core and bundled extensions in our dev and QA testing.

**Comment by HLFH** [comment]
I am not able to replicate the issue on `https://beta.flarum.site/`. 
*fof/byobu* seems be the culprit, so I disabled it, and the forum homepage loads correctly.

And eventually the fact not every string seems to be translated from English to German and French locales. I'll look into that. Thanks for the reply.

**Comment by datitisev** [comment]
The stack trace says mount-redraw because that's Mithril code, and the error occurs after internal Mithril redraws. 99% of the time the problem will not be with that file or any Mithril file.

The error that is thrown was added by us so that it makes more sense than the one Mithril will throw if a children attr is passed. It is usually caused by code that hasn't been updated for beta 14.

**Comment by tankerkiller125** [comment]
`fof/byobu` appears to be your issue, from what I know it's not updated (and it shows not updated in that list)

**Comment by HLFH** [comment]
@tankerkiller125 Everything now works with *fof-byobu* disabled and *[lang-french](https://github.com/qiaeru/lang-french/issues/24#issuecomment-730501609)* updated.
