### ISSUE TITLE
Recaptcha v2

### ISSUE THREAD

**Issue by idk-pixel** [flarum/core#2448]
## Google Reacaptcha v2
Maybe you should add a feature with google recaptcha, placing all sites and keys in the admin panel for the google recaptcha site key, secret key , etc.

this allows bots not to create multiple account on the forums.

thanks.

**Comment by askvortsov1** [comment]
Thank you for the suggestion! This is a feature that better belongs in the extension ecosystem, in fact, there is already an extension for it: https://discuss.flarum.org/d/18399-friendsofflarum-recaptcha
