### ISSUE TITLE
IP Email

### ISSUE THREAD

**Issue by idk-pixel** [flarum/core#2450]
# Security Request 

### If You sign Up with a IP, and someone tries to login without the same ip, send an email to the person and tell them to reset the password or authorize the IP.

# Thanks

**Comment by askvortsov1** [comment]
This is also something that makes more sense as an extension than as a core feature. Although It'd be nice to ensure in core that the IP (and maybe the whole request) is provided to the LoggedIn event

**Comment by askvortsov1** [comment]
This will be taken care of automatically when the last used IP address gets added to the access token in https://github.com/flarum/core/pull/2074.
