### ISSUE TITLE
Automatic Right-to-Left (RTL) for bidirectional posts

### ISSUE THREAD

**Issue by ramisedhom** [flarum/core#2455]
## Bug Report

**Current Behavior**
Currently posts that have mixed directional language (ex. paragraphs with both Arabic and English), it's always have LTR direction, aligned to left with wrong reading direction which make reading such paragraphs unclear. The same is happening while writing a post in post composer.

**Steps to Reproduce**
1. Start a discussion
2. Start writing in [any of RTL languages](https://en.wikipedia.org/wiki/Right-to-left)
3. Add some words in the middle with any LTR language
4. Post discussion

**Expected Behavior**
Paragraphs starting with words from RTL languages, should be aligned to be right with correct reading directions.

**Environment**
- Flarum version: 0.1.0-beta.14.1
- PHP version: 7.4.12
- Browser: chrome 86.0.4240.183 (Official Build) (32-bit)

```
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, curl, hash, filter, ftp, gettext, gmp, SPL, iconv, pcntl, readline, Reflection, session, standard, shmop, SimpleXML, mbstring, tokenizer, xml, bcmath, dom, fileinfo, gd, imap, intl, json, exif, mysqlnd, mysqli, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, soap, sockets, sqlite3, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip
+----------------------+------------------+--------+
| Flarum Extensions    |                  |        |
+----------------------+------------------+--------+
| ID                   | Version          | Commit |
+----------------------+------------------+--------+
| flarum-approval      | v0.1.0-beta.14   |        |
| flarum-emoji         | v0.1.0-beta.14   |        |
| flarum-lang-english  | v0.1.0-beta.14.1 |        |
| flarum-flags         | v0.1.0-beta.14.1 |        |
| flarum-likes         | v0.1.0-beta.14   |        |
| flarum-lock          | v0.1.0-beta.14   |        |
| flarum-markdown      | v0.1.0-beta.14   |        |
| flarum-mentions      | v0.1.0-beta.14   |        |
| flarum-statistics    | v0.1.0-beta.14   |        |
| flarum-sticky        | v0.1.0-beta.14   |        |
| flarum-subscriptions | v0.1.0-beta.14   |        |
| flarum-suspend       | v0.1.0-beta.14   |        |
| flarum-tags          | v0.1.0-beta.14   |        |
| fof-user-directory   | 0.4.0            |        |
| fof-follow-tags      | 0.5.1            |        |
| flarum-pusher        | v0.1.0-beta.14.1 |        |
| flarum-bbcode        | v0.1.0-beta.12   |        |
+----------------------+------------------+--------+
```

**Possible Solution**
-Simply:
  - Add `unicode-bidi: plaintext;` to `p` selector in `./vendor/flarum/core/less/common/scaffolding.less` to fix posted paragraphs,
  - Add `unicode-bidi: plaintext;` to `.TextEditor textarea` selector in `./vendor/flarum/core/less/forum/Composer.less` to fix post composer.

I had tried this solution and posted about on [Flarum dev forum](https://discuss.flarum.org/d/25377-right-to-left-rtl-for-bidirectional-posts)

**Additional Context**
- Proposed solution has not impact on:
  - Posts or paragraphs starting with words from LTR languages.
  - The forum theming

**Comment by askvortsov1** [comment]
This makes sense, but my biggest concern here is https://developer.mozilla.org/en-US/docs/Web/CSS/unicode-bidi: apparently this isn't intended for regular web dev use?
