### ISSUE TITLE
If the interface throws exception, the subsequent process of middleware will not go

### ISSUE THREAD

**Issue by yulei745** [flarum/core#2459]
## Bug Report

**Current Behavior**

If the interface throws exception, the subsequent process of middleware will not go.

**Steps to Reproduce**

If the role of a middleware is to set the relevant value after the response, it will not take effect and lose the role of middleware.

```
$response = $handle->handle($request);

$response->withHeader('Access-Control-Allow-Origin', '*');

return $response
```

**Environment**

- Flarum version: Beta.14
- 
- Webserver: Apache
- 
- Hosting environment: local
- 
- PHP version: 7.4.9
- 
- Browser: Chrome 84

**Comment by askvortsov1** [comment]
Any middleware before `HandleErrors` should still run though. Closing since this is already supported.
