### ISSUE TITLE
Tag modal fails to open when no tags are available

### ISSUE THREAD

**Issue by matteocontrini** [flarum/core#2473]
## Bug Report

**Current Behavior**

When there are no tags the user can choose from, the modal for choosing tags in the new discussion composer fails to open, and this exception is shown in the console:

```
TypeError: this.tags[0] is undefined
    oninit TagDiscussionModal.js:30
```

I stumbled upon this while trying to reproduce #2464.

**Steps to Reproduce**
1. Go to https://nightly.flarum.site/
2. Login as an admin and go to the admin section
3. Delete all the tags
4. Go back to frontend, click "Start a Discussion", click "Choose Tags" and observe that nothing happens

**Expected Behavior**

Not sure, the modal should open but maybe it would be best to hide the "Choose Tags" button altogether.

**Environment**
- Flarum nightly (66482c2)

**Comment by askvortsov1** [comment]
I don't know that we should consider this an actionable bug, because this particular state should never happen: if there are no tags, the "Create a Discussion" button should be disabled. With https://github.com/flarum/tags/pull/105, that logic should become even cleaner.

**Comment by luceos** [comment]
This issue is still not solved. It isn't high priority, but it's a bug nevertheless.
