### ISSUE TITLE
[Nicknames] Can't set a nickname

### ISSUE THREAD

**Issue by SychO9** [flarum/core#2484]
## Bug Report

**Current Behavior**
Getting a validation error.
```
The nickname may not be greater than characters.
```

Also, if there's a space, it says saved, but isn't.

**Comment by askvortsov1** [comment]
I'm having trouble replicating this. Have you configured min / max / regex validation in admin?

**Comment by askvortsov1** [comment]
Ah nvm, I got it. If you save anything at all in the settings dashboard, it sets the max length to null which crashes everything. I'll add the default permissions and settings as a migration

**Comment by SychO9** [comment]
alright, also If it's not supposed to work with min / max / regex settings set, then I think users shouldn't be given the option to edit nickname in the first place

**Comment by askvortsov1** [comment]
Well that's not _quite_ the case: it should work without those set (since those should have reasonable defaults which they don't until now), it's just that if you set max length to 0 (which is absurd), it won't work.

**Comment by askvortsov1** [comment]
> Also, if there's a space, it says saved, but isn't.

Just pushed the default settings / permissions fix. To apply it, you'll need to disable, uninstall (via admin dash), and reinstall the extension. Is this still replicable?

**Comment by SychO9** [comment]
> I think it's reasonable that requiring a unique nickname wouldn't allow you to use someone else's username as a nickname?

Absolutely

> Is this still replicable?

I don't get the validation error anymore, but it still doesn't set the nickname despite the modal closing as if it saved fine :shrug:

```
+-------------------------+-------+
| key                     | value |
+-------------------------+-------+
| flarum-nicknames.max    | 150   |
| flarum-nicknames.min    | 1     |
| flarum-nicknames.regex  |       |
| flarum-nicknames.unique | 1     |
+-------------------------+-------+
```

Is the regex field required ?

**Comment by askvortsov1** [comment]
Nope, regex is optional.

**Comment by SychO9** [comment]
The nickname actually saves just fine, it's just that when you have `username` set as the display name driver, the frontend fills the nickname input with the username, making it look like it doesn't work.

Does make me wonder, if the admin sets the display name driver to username, should we still show the nickname input to the end user ? it's not used if it's not the driver so I'd think it best to not show it.

**Comment by askvortsov1** [comment]
Hmm, the way I see it, setting `nickname` as the display name driver would be part of the installation / configuration steps for this extension. Otherwise we need to serialize which display name driver is being used to the frontend, which is doable of course, but feels like excess logic.

**Comment by SychO9** [comment]
Well, I really think we should do *something*, you're right that logically the admin should set it as the driver, but it's not intuitive to do so. I forgot to do so myself, especially since the option to change the driver is in another settings page (Basics).

If we leave it the way it is, I feel like it'll be one of those things that'll end up in many support topics and whatnot.

>  Otherwise we need to serialize which display name driver is being used to the frontend, which is doable of course, but feels like excess logic.

I don't see it as excess logic, we have a valid reason here for the frontend to be aware of the current display name driver, also it's just adding the `display_name_driver` setting as an attribute in the forum serializer and adding a conditional in the frontend.

**Comment by askvortsov1** [comment]
I suspect that if we hide nickname inputs when the driver isn't enabled, that might just confuse people even more since the extension is enabled but not doing anything. A few ideas:

1. Add a migration that automatically enables the driver when enabled. Although that's probably a bad idea, because it doesn't persist.
2. Duplicate the "choose a default driver" setting on the nicknames page. I don't like this either because duplicating settings unnecessarily is unnecessary
3. Add a big warning alert on the nickname extension's settings page if nicknames isn't selected. We'd need a custom settings page (although we could still use the setting object => component util), but that would let admins know they need to adjust stuff
4. Hide user-side inputs if the nickname driver isn't selected (what you proposed).

I don't think (4) alone would be sufficient as I mentioned at the start, but maybe if we do both (3) and (4) that would be intuitive?

**Comment by SychO9** [comment]
> I suspect that if we hide nickname inputs when the driver isn't enabled, that might just confuse people even more since the extension is enabled but not doing anything.

Right, but that only confuses the admin, and not all the members who would be seeing this *what seems to be not working* input. And this can easily be fixed by adding a note in the extension's settings page. (The extension will only work if it is selected as the display name driver in the *\*link to basics page\**)

So yes (4) and (3) would be the best way to go imho.

> 3. Add a big warning alert on the nickname extension's settings page if nicknames isn't selected. We'd need a custom settings page (although we could still use the setting object => component util), but that would let admins know they need to adjust stuff

Hmm, I see, it'd definitely be great if we can still use `registerSetting` instead of having to create a whole new custom page component.

**Comment by askvortsov1** [comment]
Perhaps if registerSetting receives vnodes, it should return them directly? I think that would be nice for inserting components in between settings

**Comment by SychO9** [comment]
That would even allow extension devs to insert custom components for settings! I've had to create/use custom components for some settings before (like a custom tagselection component), so I see this as a good and valid use case.

**Comment by askvortsov1** [comment]
Hmm we'd need something a bit more complex for that than just vnodes since you'd need access to the page component as `this`. Maybe we could allow passing in a closure that takes `this` as an argument instead?

**Comment by SychO9** [comment]
Oh my bad, you did say directly passing vnodes, but I thought of a function that returns the vnode.

> Maybe we could allow passing in a closure that takes this as an argument instead?

Yea I think that'd be more sensible.

**Comment by askvortsov1** [comment]
(4) done. I'll wait on #2468 before adding (3).

**Comment by SychO9** [comment]
> I suspect that if we hide nickname inputs when the driver isn't enabled, that might just confuse people even more since the extension is enabled but not doing anything.

We could have also not hidden the input and just serialized nickname and used that in the modal :p 
```js
this.nickname = Stream(app.session.user.displayName());
this.nickname = Stream(app.session.user.nickname());
```

**Comment by askvortsov1** [comment]
Why allow people to change stuff if it has no effect? I see enabling the nickname driver as a necessary part of the installation.

> this.nickname = Stream(app.session.user.displayName());
> this.nickname = Stream(app.session.user.nickname());

I thought about doing it like this, but providing the display name as the initial input lets the user edit what actually is shown, not the nickname itself.

**Comment by SychO9** [comment]
Hmm, I can't set the nickname back to the username.

Seems like we can use the rule class to ignore the actual user's ID: laravel.com/docs/6.x/validation#rule-unique

```php
Rule::unique('users', 'username')->ignore($user->id);
```

**Comment by SychO9** [comment]
Can't change the nickname back to the username value, haven't looked at the code to see why that is.

**Comment by askvortsov1** [comment]
> Can't change the nickname back to the username value, haven't looked at the code to see why that is.

Hmm, are you on the latest version? If the nickname sent is the same as the user's current username, it should be set to null so that the actual username is displayed

**Comment by SychO9** [comment]
Yea, it works fine with the NicknameModal, it's only a problem with the EditUserModal, so it's a frontend issue, something minor in the code most likely.

**Comment by askvortsov1** [comment]
Should be fixed now.

**Comment by SychO9** [comment]
> Should be fixed now.

Fixed indeed.

Another concern is new users can choose a username which is the same as someone else's nickname, not sure if we also want to prevent that.

Other forum software that I'm familiar with do that.

**Comment by askvortsov1** [comment]
Good point! So other than this, the only thing we're waiting on for nicknames v1 to be complete is:

- Adding a warning to admin dashboard if nickname driver is not enabled once #2468 is merged
- Adding nicknames to flarum/flarum, making it enabled by default in core
