### ISSUE TITLE
AvatarEditor should show an upload icon instead of a user's default avatar

### ISSUE THREAD

**Issue by tobscure** [flarum/core#249]
The AvatarEditor component (shown on a user's profile if the avatar is editable) should display a big "upload" icon in place of the avatar if the user hasn't uploaded one. This will make discovery of the upload function more obvious.

What needs to be done:

* Add a check in AvatarEditor to see if the user's `avatarUrl` is empty – if it is, show an upload icon instead of their avatar.

**Comment by franzliedke** [comment]
Related to #107.
