### ISSUE TITLE
Notifications panel infinite scrolling doesn't work anymore

### ISSUE THREAD

**Issue by matteocontrini** [flarum/core#2508]
## Bug Report

**Current Behavior**

Infinite scrolling in the notifications panel was introduced in 77c25ab7252b82012c77117ccfdd899bd823d65e but it appears it's not working currently.

**Steps to Reproduce**
1. Go to any forum on beta.13, beta.14 or beta.15 (maybe earlier, not sure) where you know you have a lot of notifications
2. Login
3. Click the bell icon and notice that you cannot scroll past the first 10 notifications

**Expected Behavior**

New notifications should be loaded as you scroll. This was the actual behaviour in the past at some point.

**Screenshots**

https://user-images.githubusercontent.com/2164763/102908618-06749500-4478-11eb-9273-182ee144dfe0.mp4

I also noticed that if I open the dev tools, infinite scrolling starts working again, probably because the height of the notifications panel changes.

https://user-images.githubusercontent.com/2164763/102908690-18eece80-4478-11eb-8ee1-6fbf6f84f6fe.mp4

**Environment**
- Flarum version: beta.13, beta.14, beta.15, probably other versions as well
- Website URL: reproduced on discuss.flarum.org, other than on my forum
- Browser: Firefox 84

**Comment by datitisev** [comment]
Probably a height issue, as you said - it works fine for me without opened dev tools on discuss.

**Comment by matteocontrini** [comment]
It might be related to Firefox because I'm unable to reproduce the issue on Edge (Chromium). I assumed it was a widespread issue since multiple users of my forum told me they've never seen infinite scrolling working 🤔 

Feel free to change the title to something that suits better 😊

**Comment by imorland** [comment]
+1 from me, using both FF mobile and desktop, it has been quite some time since the infinite scrolling has worked for me on any Flarum site

**Comment by datitisev** [comment]
> It might be related to Firefox because I'm unable to reproduce the issue

I am using Firefox and it works fine on discuss 🤷

**Comment by matteocontrini** [comment]
Hello, I cherry-picked the fix commit and deployed on my forum and the issue is still present.

**Comment by iPurpl3x** [comment]
This seems to be broken again in 1.2 and 1.3. Is anyone aware of that already ?

**Comment by matteocontrini** [comment]
Works for me™ on 1.2 and nobody reported this issue to me after the fix.

**Comment by iPurpl3x** [comment]
Ok @matteocontrini, I now realized that sometimes it works and sometimes not. I will have to investigate a bit to find out a way to reproduce the issue.
