### ISSUE TITLE
Preloaded tags relationship in DiscussionWasTagged event has old tag values

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#2514]
## Bug Report

**Current Behavior**
When `DiscussionWasTagged` is dispatched, the `Discussion` object passed in the event has the tags relationship loaded, but it contains the old tags. This behavior changed from unfixed beta 14 to security fix 14.1/beta 15 and I think the new behavior is undesirable.

**Steps to Reproduce**

Add to local `extend.php`:

```php
<?php

use Flarum\Extend;

return [
    (new Extend\Event)->listen(\Flarum\Tags\Event\DiscussionWasTagged::class, function ($event) {
        var_dump(\Illuminate\Support\Arr::pluck($event->oldTags, 'slug'), $event->discussion->tags->pluck('slug'));die();
    }),
];
```

On beta 14, two different arrays are dumped. In beta 15, the two arrays are identical and contain the slugs of the old tags.

**Expected Behavior**
We should be able to call `$event->discussion->tags` and expect an up to date payload.

**Environment**
- Flarum version: beta 14 with tags 14.1, beta 15, dev-master

**Possible Solution**
One solution would be to leave as-it, and recommend users to always query a fresh copy of the tags using `->tags()->get()` instead of the possibly cached `->tags`. But I don't think it's a good solution. It will cause unneeded database queries if multiple extensions want the updated tags, which is often what you want if you're listening for the event.

Another solution is to unload the relationship before triggering the event. I confirmed the following change fixes it:

Existing code:

https://github.com/flarum/tags/blob/9f3a12376998b3d43bb996dd5ab1b4d822e677c2/src/Listener/SaveTagsToDatabase.php#L111-L113

Fixed code:

```php
            $discussion->afterSave(function ($discussion) use ($newTagIds) {
                $discussion->tags()->sync($newTagIds);
                $discussion->unsetRelation('tags');
            });
```

**Additional Context**
The change has been introduced with https://github.com/flarum/tags/pull/95 . The tags relationship is pre-loaded in the policy and remains loaded during the whole lifecycle.

I have discovered the issue while working on Audit Log https://github.com/kilowhat/flarum-ext-audit-free/blob/8b9c92425a68dfbef5f009f8bc0fd5ca547e0f2e/src/Extenders/FlarumTagsEvents.php#L24

Other extensions that use the event include:

Action Log (queries a fresh copy, so not impacted) https://github.com/SychO9/flarum-action-log/blob/b2e8dc8228ea2f54947e039b9d8f18bd967629a8/src/Listener/LogDiscussionTagged.php#L44

Follow Tags (not impacted because the discussion instance is passed to a job with `SerializesModels`) https://github.com/FriendsOfFlarum/follow-tags/blob/93012fc748309cce992efdc1026f18600937e65b/src/Jobs/SendNotificationWhenDiscussionIsReTagged.php#L54

**Comment by SychO9** [comment]
huh, I had noticed this when I was updating action log to beta15, didn't understand why and how it had changed, so I just decided to query a fresh copy.

This makes a lot of sense 👍🏼

**Comment by askvortsov1** [comment]
I'm fine with the proposed solution of unsetting the relationship :+1:

**Comment by clarkwinkelmann** [comment]
It seems like in beta 16 the same effect applies to `Flarum\User\Event\GroupsChanged`. `$event->user->groups` returns the old groups. They are probably preloaded by some permissions. Not sure if it's worth a separate issue. It should receive the same fix.
