### ISSUE TITLE
Activation email doesn't have forum title prefix when re-sent

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#2515]
## Bug Report

**Current Behavior**
The activation email has the [Forum Name] prefix in the subject. But clicking "send activation email again" sends an identical email, without the prefix.

**Steps to Reproduce**
1. Create new account
2. Ask for new activation email
3. Compare the two emails received

**Expected Behavior**
The two emails should have identical titles. The missing prefix seems to be an oversight.

**Screenshots**
![image](https://user-images.githubusercontent.com/5264300/103249794-2ffa5880-4971-11eb-930b-0b2dc68e71bf.png)

**Environment**
- Flarum version: beta 15

**Possible Solution**
Add subject prefix by copy-pasting code

Without prefix

https://github.com/flarum/core/blob/f8edc2d827fee47dc78fbb75ee1d3b28580ed11d/src/Api/Controller/SendConfirmationEmailController.php#L85

With prefix

https://github.com/flarum/core/blob/0a6c5217c11e625aab5deec05bf6a6caf31bfa0d/src/User/AccountActivationMailer.php#L66

**Comment by matteocontrini** [comment]
I think this is better solved through #2193 (PR => #2493).

**Comment by askvortsov1** [comment]
This was a purposeful change made in https://github.com/flarum/core/pull/1613, so I don't think we should be so quick to reverse it.
