### ISSUE TITLE
Discussion list isn't refreshed when navigating to/from following through an intermediate page

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#2516]
## Bug Report

**Current Behavior**
There are situations in which arriving on the discussion list will continue to show the state of a previous discussion list, even though the filters are supposed to be different

**Steps to Reproduce**
1. Mark at least one discussion as Followed (initial state, only needs to be done once)
2. Open forum on homepage
3. Visit non-discussion-list page, like the Tags page
4. Visit Following page
5. Observe Following page shows the state of All Discussions

Opposite also works:

1. Open forum on Following
2. Visit non-discussion-list page, like the Tags page
3. Visit All Discussions
4. Observe All Discussions shows the state of Following

**Expected Behavior**
The list should be refreshed.

**Screenshots**
![image](https://user-images.githubusercontent.com/5264300/103253916-75278600-4983-11eb-94de-007d55b2e268.png)

**Environment**
- Flarum version: beta 14, beta 15

**Possible Solution**
The problem is that the Subscription extension only mutates `DiscussionListState.requestParams`, but that value is not part of the system that compares a state with the previous state.

The refresh check happens in `DiscussionListState.refreshParams`:

https://github.com/flarum/core/blob/f8edc2d827fee47dc78fbb75ee1d3b28580ed11d/js/src/forum/states/DiscussionListState.js#L71-L77

Which itself takes the params from `GlobalSearchState.params` in `IndexPage.oninit`:

https://github.com/flarum/core/blob/f8edc2d827fee47dc78fbb75ee1d3b28580ed11d/js/src/forum/components/IndexPage.js#L40

https://github.com/flarum/core/blob/f8edc2d827fee47dc78fbb75ee1d3b28580ed11d/js/src/forum/states/GlobalSearchState.js#L47-L53

Instead of accessing `app.current.get('routeName')` in `DiscussionListState.requestParams`, it should be accessed in `GlobalSearchState.params` and an intermediate state should be stored in `params`.

This is the code I'm using to fix the same issue that's affecting the Bookmarks extension, I'm going to test it some more in Bookmarks, but I think it can be used very similarly in Subscription (Bookmarks is essentially a reskin of Subscription).

```js
    extend(GlobalSearchState.prototype, 'params', function (params) {
        params.bookmarked = app.current.get('routeName') === 'bookmarks';
    })

    extend(DiscussionListState.prototype, 'requestParams', function (params) {
        if (this.params.bookmarked) {
            params.filter.q = (params.filter.q || '') + ' is:bookmarked';
        }
    });
```

**Additional Context**
Found when testing the beta 15 update of Bookmarks. Also happens when navigating through any other pages, like All Discussions > FoF User Directory > Following.

The bug doesn't happen when no discussions are followed when going in the direction Following > All discussions, because an empty state automatically triggers a refresh. It also doesn't happen when navigating directly from one page to the other, since coming from an `IndexPage` component also always triggers a refresh.

**Comment by SychO9** [comment]
related: #2502

**Comment by clarkwinkelmann** [comment]
Woops, didn't notice that other issue. Same thing.

**Comment by askvortsov1** [comment]
From local testing, this seems to be fixable by setting `params.q` on `GlobalSearchState's `params` directly, changing both doesn't seem to be necessary. I'll open a PR.
