### ISSUE TITLE
Design and implement reset password and error page UIs

### ISSUE THREAD

**Issue by tobscure** [flarum/core#252]
Currently the reset password and error page UIs are pretty much non-existent.

Error 404 pages should have a login form.

What needs to be done:
- Design a lightweight template for interfaces powered by the backend. I envision a simple centered light-blue box. All CSS should be embedded directly in the `<head>`, like in the installer. Very important that it's simple.
- I don't have clear-cut instructions for implementation at the moment.

**Comment by Luceos** [comment]
Does this include implementing the issue with reset password? When entering a email address, the api url is 404. Tested on discuss.flarum.org. See also: https://github.com/flarum/core/issues/589

**Comment by tobscure** [comment]
@Luceos Nope that's fixed in the latest master. I'll deploy to discuss.flarum soon.

**Comment by Albert221** [comment]
Which browsers should be supported? I can design and code some basic error message layout.

**Comment by franzliedke** [comment]
@tobscure Did you already have some plans for these? Or even mockups?

**Comment by jordanjay29** [comment]
Is this still on the to-do for B7? Would be nice to have it working on discuss.flarum.

**Comment by franzliedke** [comment]
Yeah, I agree, should be simple enough as well.

@tobscure Can we squeeze this in?

**Comment by edd--** [comment]
removed from the milestone, does this mean that we won't be getting this feature ?

**Comment by franzliedke** [comment]
No, it has just been demoted so that we could release beta7. It will be included in the final release, if I am not mistaken. :wink:

**Comment by josemi-ca** [comment]
This has been closed but it seems the option to login from 404 page has not been implemented flarum/issue-archive#377

**Comment by luceos** [comment]
Re-opened flarum/issue-archive#377 for further discussion and ways to implement.
