### ISSUE TITLE
[Accessibility] Enabled/Disabled extension dot indicators not accessibility-friendly

### ISSUE THREAD

**Issue by SychO9** [flarum/core#2520]
Apart from the color difference (red/green) the shapes/forms of the dots indicating if an extension is enabled or disabled should also be different enough to be able to tell without the colors. And they should also have tooltips.

**References:**
https://discuss.flarum.org/d/7585-free-flarum-hosting-on-an-expert-platform-by-freeflarum-com/1878
https://discuss.flarum.org/d/25844-old-style-admin-panel/21

Some propositions:
. | .
-- | --
![flarum lan_admin (17)](https://user-images.githubusercontent.com/20267363/103570687-d42c5400-4ec9-11eb-98eb-3813ddc65ab5.png) | ![flarum lan_admin (15)](https://user-images.githubusercontent.com/20267363/103570539-94fe0300-4ec9-11eb-8a1f-25535fa91de2.png)

**Comment by tankerkiller125** [comment]
I think that a simple outline/filled in indicator should work well, except probably the reverse of the one shown (green is solid, red is outlined).

**Comment by SychO9** [comment]
> I think that a simple outline/filled in indicator should work well, except probably the reverse of the one shown (green is solid, red is outlined).

🙈 oh yeah you're right, they should be reversed
