### ISSUE TITLE
What should happen if mention user in restrict tag?

### ISSUE THREAD

**Issue by PeopleInside** [flarum/core#2523]
What should happen in the following scenario:

    Member A has access to a restrict tag, for example private.
    Member B doesn't have access to the restrict tag, for example private.

Member A mention Member B in a discussion in private tag.

On Beta 15 the result seems to be:

    Member A are able to mention Member B
    Member B are not notified about mention of Member A

Can be maybe this scenario be improved in some way to avoid Member A think sent a notification to Member B and waiting a reply from Member B that will not arrive?

Should Member A be able to mention a Member B that has not access to the restrict tag without this send in any case a notification to Member B?

**Is correct no notification is sent because can expose sensible data as Member B has no access to this tag so should not receive any content by email but... Member A can not know Member B has no access and will be not notified.**

Some idea:
If the user Member B has no access to the restricted tag should be not mentioned by anyone or can be but a warning should alert who is doing the tag no email and no alert and no access will be possible for that mentioned user.

Currently if you have large community with users and permissions... it's look quite a bug you can tag someone that never will alerted as usual. This create confusion.

Maybe connected also to
https://github.com/flarum/core/issues/1965

**Comment by PeopleInside** [comment]
Sleep bot ^_^

**Comment by luceos** [comment]
I now only fully understand your request. In the past mentions actually did - incorrectly - send notifications to mentioned users that had no access to the tag the discussion was in. We actually noted this on discuss and contents from the post were shared with that user. 

My personal belief is that mentions is not just a ping to get someone's attention, but also an ability to link to specific posts or profiles of users. Unintentionally pinging someone (regardless of post information shared) is not something we should introduce.

For this reason I am closing this issue.

**Comment by PeopleInside** [comment]
Hi @luceos , can you please reopen this?
What I'm reporting here is not about send a topic notification to someone has no permission but find a way to alert who is ping someone that will be not ping.

Maybe mention should not allow to mention a user that has no access, actually mention allow this but never send email. I'm imaging if an user has no access using @ should not show the not allowed member so who is ping with tag will understand..  that cannot ping that user on that tag.

Maybe a check like a tag list who check if user are in the tag or not when a tag is restricted.
