### ISSUE TITLE
Policies: treat `true` as `allow`, and `false` as `deny`

### ISSUE THREAD

**Issue by askvortsov1** [flarum/core#2525]
## Feature Request

I think the new tiered levels of response in the policies system is well worth it, but is also somewhat inconvenient: I have already forgotten to return one of those 2 variables multiple times. Returning a boolean expression is much more than returning `boolean expression ? $this->allow() : $this->deny()`. Perhaps `AbstractPolicy` should treat `false` as `$this->deny()` and `true` as `$this->allow()`?

**Comment by SychO9** [comment]
I would be in favor, mainly because it would allow us to directly return expressions like before, which is more straightforward and simple, and it just seems to be the way any developer would expect it to be. Also, since we now have the `ALLOW` and `DENY` constants, the change would be very simple.

```php
// Before
return $expression;

// Currently
return $expression ? $this->allow() : $this->deny();
```

**Comment by luceos** [comment]
if `$expression` is `"foo"`, the string, your conditional would be treated as true too.. 

It would make more sense to do an `is_boolean($expression)` conditional and then return it:

```php
if(is_bool($expression)) {
    return $expression ? $this->allow() : $this->deny();
}

return <the rest>;
```

**Comment by SychO9** [comment]
I was referring to a boolean expression :P 
 something like:

```
return $actor->has('perm') && $actor->id === $model->id;
```
