### ISSUE TITLE
Add user online indicators

### ISSUE THREAD

**Issue by tobscure** [flarum/core#254]
* Similar to esoTalk, if a user is online (seen in the last 5 mins), we want to show a little green circle just to the left of the username.
* This should be added to the PostHeaderUser component.
* Probably use an fa-circle icon, with a style to make it a bit smaller just like in the UserCard component.

**Comment by dcsjapan** [comment]
In connection with this, consider matching the color and style of the online indicator on the user page and profile popup to the above, as per this suggestion:

http://discuss.flarum.org/d/902-green-circle-to-display-user-is-online

**Comment by Luceos** [comment]
See PR: https://github.com/flarum/core/pull/676
