### ISSUE TITLE
Deprecate and remove `evented` util

### ISSUE THREAD

**Issue by askvortsov1** [flarum/core#2547]
This util was previously used to allow the PostStream and DiscussionPage to communicate, but is now unnecessary with PostStreamState. It doesn't seem to be used in any extensions: https://query.flarum.dev/q/788d223f-4492-4ef0-ba5d-32023fa40a99

**Comment by prabhatjoshi321** [comment]
May i take on this Issue.

**Comment by tankerkiller125** [comment]
@prabhatjoshi321 Go for it! If you have any questions or need help we're always around someplace.

**Comment by prabhatjoshi321** [comment]
@ tankerkiller125  Thank you, I'll start right away

**Comment by askvortsov1** [comment]
Deprecated stuff will be removed with the 2.0 release, we can consider this closed.
