### ISSUE TITLE
[Flags] Create an event for flag creation

### ISSUE THREAD

**Issue by matteocontrini** [flarum/core#2551]
Currently, the `flarum/flags` extension only has an event for when a flag is being deleted ([`FlagsWillBeDeleted`](https://github.com/flarum/flags/blob/master/src/Event/FlagsWillBeDeleted.php)).

It would be useful to have an event for when a flag is created as well (more precisely, when a user flags a post).

A possible use-case would be, for example, an extension that generates an "external" notification for admins/moderators when a flag is created. (With external I mean an email or a message in a Telegram group, for example.)

Relevant discussion on discuss: https://discuss.flarum.org/d/25981-listening-to-flag-creation

**Comment by askvortsov1** [comment]
For that matter, it would be nice to update the naming scheme for flags event to fit better with what we're using in core and modern extensions.

**Comment by imorland** [comment]
I'll happily take this on and submit a PR - this would be very useful for me too..

@askvortsov1 When I rename the `FlagsWillBeDeleted`, would it be better to deprecate for a release cycle and dispatch the old and new, or just swap out?

**Comment by askvortsov1** [comment]
Thank you! And yeah we'd want to deprecate it first.

**Comment by askvortsov1** [comment]
Fixed in https://github.com/flarum/flags/pull/35
