### ISSUE TITLE
[Sticky] excerpts don't show for logged in users when new content is present

### ISSUE THREAD

**Issue by imorland** [flarum/core#2556]
## Bug Report

**Current Behavior**
Stickied discussions only display the excerpt content to guests. Logged in users do not see the excerpt when new content is present in the discussion.

**Steps to Reproduce**
1. Pin a discussion
2. Create some new content (ie new reply)
3. Log out
4. Note the excerpt is displayed
5. Login as another user
6. Note there is unread content
7. Note the excerpt is not displayed

**Expected Behavior**
Logged in users should see the excerpt too, if there are new posts in the discussion (based on beta 13 behaviour).

**Screenshots**
![image](https://user-images.githubusercontent.com/16573496/105105360-de467900-5aab-11eb-8571-0c8878d8a8e5.png)

**Environment**
- Flarum version: 0.1.0-beta.15 & dev-master
- Website URL: https://discuss.flarum.org
- Webserver: 
- Hosting environment:
- PHP version: 7.4.14
- Browser: FF, probably others

**Additional Context**

**Comment by imorland** [comment]
Actually, this may actually be a non-issue.

It may not actually make sense to re-display the first post content, after the user has already seen it.

**Comment by askvortsov1** [comment]
I think it would be nice to remind users why the post is sticky by showing the excerpt, but I get what you mean. No strong opinions either way.

**Comment by luceos** [comment]
Re-open if we do have a strong opinion :)
