### ISSUE TITLE
Add UI to configure SMTP settings

### ISSUE THREAD

**Issue by tobscure** [flarum/core#258]
What needs to be done:

* Create an AdvancedPage in the admin CP and add a link for it in the AdminNav. (Related: #167)
* Add fields to allow SMTP config to be saved. Use BasicsPage as an example.

**Comment by ethnp** [comment]
How do I setup the email configuration settings? The fields are blobs...

**Comment by Zoink5** [comment]
The fields are blobs as mentioned by @ethnp - I tried editing them directly but this broke my setup.

**Comment by pescu25** [comment]
yes,how?

**Comment by wa-Nadoo** [comment]
@pescu25, http://flarum.org/docs/installation/ -> Configuring SMTP

**Comment by riznmage** [comment]
@wa-Nadoo The fields are blob, and can not be edited?

Fresh install from composer today.

**Comment by wa-Nadoo** [comment]
@riznmage, use SQL script https://discuss.flarum.org/d/620-smtp-setup/10

**Comment by riznmage** [comment]
@wa-Nadoo Well, I'm getting this error: #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO `config`(`key`, `value`)...

**Comment by kerlw** [comment]
@riznmage table 'config' has been renamed to 'settings'(Of course, you need to add your prefix.)

**Comment by Luceos** [comment]
Please use this issue to discuss the implementation of the UI for configuring the SMTP settings. For questions how to do it without this implementation, use the forums! Or use an SMTP extension [from the list](https://discuss.flarum.org/d/1534-extension-list).

**Comment by datitisev** [comment]
Ok, so I'm trying to make this :wink:
Should it be found (the SMTP settings) in the _Basics_ page?
Thanks!

**Comment by datitisev** [comment]
How does [datitisev/core#258-smpt-settings-ui](https://github.com/datitisev/core/tree/258-smpt-settings-ui) look?
The only thing missing would be the locale in flarum/flarum-ext-english
I've tested it, and it works fine; aka it puts the data in the database correctly.
Here is a screenshot:
_PS: I am on the **Basics** page,  not in Appearance_

![Flarum Admin: Basic @ SMPT Settings](https://i.imgsafe.org/cb8e723.png)

**Comment by vivex** [comment]
do  it supports php mail ?

**Comment by franzliedke** [comment]
Hi @vivex, yes, it is possible to configure Flarum to use mail instead of SMTP, however at the moment this is not possible through the user interface. You would have to create a custom extension.

**Comment by vivex** [comment]
@franzliedke  thanks for quick reply,  So if i change `mail_drive` in DB to `mail` , will it work ?

**Comment by franzliedke** [comment]
You could try that, yes - but I'm not sure what that will do to the admin interface, to be honest. ;)

**Comment by Luceos** [comment]
Yes you can set mail.driver in the database to mail, you can fill in bogus information in the other fields, it will be ignored (if I'm not mistaken).

**Comment by tisuchi** [comment]
I am using mailgun, but have issue. None of the email is triggering. My configuration is like follows- 

```
mail_driver : mailgun
mail_from : donotreplay-------------.com
mail_host: smtp.mailgun.org
mail_port : 587
mail_username : postmaster@----------.com
mail_password : *************
mail_encryption: null
```

Can anybody help me?

**Comment by datitisev** [comment]
@tisuchi This isn't the proper place to discuss this. All the SMTP UI does is set the values into the database. Either your configuration is wrong, or you haven't triggered any events that would send an email.
Please create a discussion at https://discuss.flarum.org with the Support tag

**Comment by Luceos** [comment]
@tisuchi you're missing encryption, for 587 it should be `tls`.

**Comment by tisuchi** [comment]
@Luceos 

Thanks for you replay. But its not working with encryption too.

**Comment by Luceos** [comment]
@tisuchi please open a thread on the forums under support so we can track this down more easily.
