### ISSUE TITLE
Pinned pullout keeps scrolling back to the beginning

### ISSUE THREAD

**Issue by harry-wg** [flarum/core#2582]
## Bug Report

**Current Behavior**
Whenever I select a message from the pinned pullout, the correct message is displayed alongside the pullout. But the pullout immediately scrolls back to the top message instead of maintaining the pullout's correct vertical scroll position 

**Steps to Reproduce**
1. Go to https://discuss.flarum.org/
2. Click on the first visible post
3. If the pinned pullout is not visible, open it and pin it
4. Still in the pinned pullout, scroll it down by a couple of screens
5. Click on a thread title in the pullout
6. Observe that the associated message is correctly displayed alongside the pullout
7. Error: observe that the thread title you clicked on is no longer visible -- the pullout has scrolled back to the top

**Expected Behaviour**
The behaviour in previous versions is correct -- ie, the pinned pullout does not scroll back to the top when selecting a thread from the pullout

**Screenshots**
You can optionally see the above steps in a video at [https://vimeo.com/505898276](https://vimeo.com/505898276

**Environment**
- Flarum version: As far as I can see, you don't mention this at https://discuss.flarum.org/ -- maybe you should?
- Website URL: as above
- Webserver: as above
- Hosting environment: as above
- PHP version: as above
- Browser: Firefox 85.0 64 bit in windows 10

**Comment by askvortsov1** [comment]
Fixed in https://github.com/flarum/core/pull/2402. Now we have an issue for it, thanks!
