### ISSUE TITLE
[Tags] tag.isChild() is undefined on the admin page for label

### ISSUE THREAD

**Issue by KyrneDev** [flarum/core#2592]
## Bug Report

**Current Behavior**
You cannot edit a tag from the admin page once it has been created, `tag.isChild` is undefined.

Related https://github.com/flarum/tags/pull/114

**Steps to Reproduce**
1. Go to tags admin page
2. Click on the pencil to edit a tag
3. See error in the browser console.

**Expected Behavior**
You can edit tags

**Environment**
- Flarum version: dev-master
- Website URL: https://nightly.flarum.site
- Browser: Firefox Dev Edition and Safari

**Comment by datitisev** [comment]
That's... odd... What does `tag` equal at that point? It is defined, as line 12 checks for that, and `isChild` is a valid attribute method in the model 🤔

**Comment by KyrneDev** [comment]
> That's... odd... What does `tag` equal at that point? It is defined, as line 12 checks for that, and `isChild` is a valid attribute method in the model 🤔

If you look here: https://github.com/flarum/tags/blob/master/js/src/admin/components/EditTagModal.js#L33-L40

The tags model only provides the tag label a subset of the info so that it can dynamically update based on values in the field. A reasonable fix is either to check whether that function is defined in the tag label or provide whether it is a child via a stream from the tags model.

**Comment by datitisev** [comment]
I feel like we can easily solve this by making a fake model instance with just that data 🤔 that way it'd prevent this happening in the future as well.

**Comment by askvortsov1** [comment]
I haven't been able to replicate this, creating a new tag and then editing it seems to work for me.
