### ISSUE TITLE
[Tags] Pressing enter on choose tags modal when posting refreshes page

### ISSUE THREAD

**Issue by datitisev** [flarum/core#2595]
## Bug Report

**Current Behavior**
When you don't select enough tags to post (e.g. no tags selected when required), and you try to post discussion, the choose tags modal pops up. If you select the tag with enter and then press enter to trigger the same behavior as "Ok", instead of doing that the page will try to refresh.

**Steps to Reproduce**
1. Open discussion composer
2. Fill title & body
3. Press "Post Discussion"
4. Select tags (keyboard or mouse)
5. Use keyboard while focused in textbox, press enter
6. After alert from browser, page refreshes and goes to `*current url*/?`

**Expected Behavior**
Page doesn't reload, it instead acts as if "Ok" button was pressed

**Screenshots**
![image](https://user-images.githubusercontent.com/6401250/107132324-eb38da00-68ab-11eb-9e08-2373d0d34f5b.png)

**Environment**
- Flarum version: 0.1.0-beta.15
- Website URL: https://nightly.flarum.site, https://discuss.flarum.org

**Comment by askvortsov1** [comment]
EXTREMELY annoying, I've bumped up into this several times but keep forgetting to file an issue.
