### ISSUE TITLE
Should user bios be an extension?

### ISSUE THREAD

**Issue by tobscure** [flarum/core#261]
I'm not sure if it makes sense to include user bios in core, because I can see them being replaced by something more powerful. Ideally we don't want extensions to have to _disable_ core features.

Extracting them as a default extension would be easy – do we want to do this?

**Comment by franzliedke** [comment]
Yeah, don't need this in core, I'd say.

**Comment by viruxe** [comment]
I agree. Rarely anyone want's a bio in a forum. But if they somehow do need it, there should be an extension for it.

**Comment by Luceos** [comment]
I absolutely agree, just take a look at the social profile by @dav-is. Also the current bio has too little value being used on the one page. I would even opt to remove that feature al together from stable and up.

**Comment by franzliedke** [comment]
Ah, true. What are the chances of that feature being added to your extension, @dav-is? That would mean we could close this issue for good. :)

**Comment by dav-is** [comment]
Ill add the feature if this goes though. Although, I'd have to rename the extension ;)

**Comment by jordanjay29** [comment]
I like the extension idea, then if someone wants to add more fields, they have an easy example to work off.

**Comment by Luceos** [comment]
@jordanjay29 with @dav-is experience I wouldn't be too surprised if his extension would allow for dynamic fields. One thing he'll probably have to do is stay away from saving all that data as json in one field and instead migrate into seperate Models.

**Comment by jordanjay29** [comment]
Solved with Flagrow/Masquerade?

**Comment by tobscure** [comment]
This was removed from core in #1214.

Quoting myself:

> I want similar functionality as an official bundled extension in the future, but we have not yet discussed/decided what form this will take and when we will implement it. [...] Bundled extension will come before stable release.

The reason being I think being able to input a little description of yourself (ala. twitter bios) is pretty integral functionality for a forum, and we want to provide a first-party solution for all integral functionality.

I would suggest starting off with just re-implementing the old functionality as an extension. Heck, I'm having second thoughts about having removed it from core. I can imagine people wanting to expand upon user profile by adding custom fields and whatnot, but I just can't imagine someone ever wanting to disable the bio and replace it with something else?

**Comment by Zeokat** [comment]
From my point of view, user bios has low value for the daily forum visitor, but they are needed for administrators.

Situations when i use user bios:
+ Find user's posts fast and review them faster.
+ Check user's activity.
+ To moderate users, posts, etc...

I agree that this functionality has low value at this development stage, but if it can be improved will be nice. Anyway, remove it from the core and offer it as an extension isn't a drama, **it is the best choice**, because **in this way will be the administrator who decide if use this feature or not**.

**Comment by tobscure** [comment]
Just to clarify, we're not talking about user profile pages (they're not going anywhere), but we're talking about the little text field that users can write a few words about themselves in - for example on discuss.flarum.org mine would be "Flarum founder and core developer"

**Comment by luceos** [comment]
I think we should keep it outside of core. Although Masquerade is able to remove the bio, it would probably be better to have a more extensive core extension that would include a signature in addition to the bio. Keeping core clean, flexible and thin is more valuable than (configurable, toggleable) features imo.

**Comment by TurboProgramming** [comment]
We should have a core extension for this just like the flags, suspension, and the sticky extension. The core should have it, but it should be disabled by default and users should enable it only if it's necessary on their forums.

Extension developers may want to extend this feature by creating other extensions aside this core extension, with other fields and features maybe?

**Comment by ardacebi** [comment]
This should probably be closed as https://github.com/flarum/core/commit/914b94b62d7316498b45d3a684a04ad502e2d053 removed this feature from the core and I started creating an extension for this: https://github.com/Extum/flarum-ext-user-bio

**Comment by PeopleInside** [comment]
I am little bit deluded to discover user bio will be removed on beta 8. This is my things, i love so much bio when i discover it. I was surprise when i discover on Flarum this is no more present.
Usually less extension you can have on the original software better is. This is my thing. Maybe just not tried in the last beta, admin or moderator should moderate also this area. Maybe this bio can simply be turned off in the admin backend. Flarum will loose something by removing this, i think also if can be added with an extension. This is just my idea.

**Comment by jordanjay29** [comment]
Third party extension available from FoF: https://github.com/FriendsOfFlarum/user-bio

**Comment by luceos** [comment]
I'm closing this issue for now. Under fof the guarantee of surviving future releases is pretty substantial. I'd also like to point out we can reconsider this decision after stable if we feel like it, but right now any extension the core team doesn't have a responsibility over is a blessing.
