### ISSUE TITLE
[Suspend] Suspension notification shouldn't reveal the actor

### ISSUE THREAD

**Issue by matteocontrini** [flarum/core#2614]
## Feature Request

**Is your feature request related to a problem? Please describe.**

As discussed* [on Discuss](https://discuss.flarum.org/d/26161-anonymous-suspension), the notification of suspension of a user reveals who was the moderator/admin that took the action, although it is unnecessary and could unfortunately be risky for the actor user.

*It wasn't actually discussed but I'll take the likes as an approval to open this issue.

**Describe the solution you'd like**

The suspension notification shouldn't include the name of the user that took the action, which is easy to change:

https://github.com/flarum/suspend/blob/b98e31963f6e82803599b56c157b9de8b266c959/locale/en.yml#L17-L19

But it should also not have a profile picture shown. I'm not sure if this is technically possible with how notifications currently work in Flarum, because after taking a quick look it appears that the actor is required in the notification blueprint.

**Comment by askvortsov1** [comment]
I think an "anonymous suspension" could be good, either site-wide, or per suspension

**Comment by matteocontrini** [comment]
Still relevant IMO.

**Comment by matteocontrini** [comment]
Thank you! Should this have a milestone?

**Comment by SychO9** [comment]
Yup, added for 1.1
