### ISSUE TITLE
Composer stuck when creating new post on mobile

### ISSUE THREAD

**Issue by zerosonesfun** [flarum/core#2617]
## Bug Report

**Current Behavior**
With a iPhone and Safari, go to bottom of a long thread. Try to reply. Sometimes the composer box is stuck. You can’t create a post without scrolling up a little and trying again. 

**Steps to Reproduce**
1. See above

**Expected Behavior**
Composer opens and you create a post. 

**Screenshots**

![E78698DA-A251-4AE6-ABA9-310F693AC2FF](https://user-images.githubusercontent.com/41351317/108569525-022ef180-72da-11eb-943c-b156c3ba1819.jpeg)

**Environment**
- This happens at discuss.flarum...
- Browser: iPhone XR latest Safari version. 

No possible solution at this time. I didn’t notice this behavior in earlier versions of Flarum. Might be a mithril 2.0 issue? Or something that changed during the big mithril 2.0 changes.

**Comment by SychO9** [comment]
could you please test in nightly ?

**Comment by zerosonesfun** [comment]
Never mind. I can’t reproduce in nightly. Must be something that will be fixed with next release.

**Comment by SychO9** [comment]
Thought so, #2279 must have fixed it as well. Thanks for testing.
