### ISSUE TITLE
API versioning

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#263]
We need to work out a mechanism to do this to ensure we can change the API in the future. The best-practice way to do it seems to be sticking a version number prefix in the URL.

What needs to be done:
- Discuss the strategy we will use.
- Work out how we will implement the strategy, particularly with regard to routes, actions, and serializers.

**Comment by luceos** [comment]
I don't know we need this. Even if we add versioning, how are we going to support previous versions? Wouldn't it just bloat the core api, routes and all? And what is the impact to extensions?

I think we can close this, unless we discover serious complications further into v1.x
