### ISSUE TITLE
[Emoji] dropdown disappears in long edit post 

### ISSUE THREAD

**Issue by Ornanovitch** [flarum/core#2635]
## Bug Report

[Related discuss thread](https://discuss.flarum.org/d/24154-dropdown-emoji-doesnt-work-well)

**Current Behavior**
It's a known bug but I found nothing about it on github:
Whenever you edit a long post which makes you scroll down in the placeholder, the emoji dropdown list tends to disappear progressively, until being totally buried in the abyss :skull: 

**Steps to Reproduce**
1. edit a post with a default placeholder height
2. write enough lines so that you can scroll down about 20 lines
3. tap `:` to call the emoji dropdown
4. it doesn't appears, or more precisely, it appears but much too low

**Expected Behavior**
Emoji dropdown should stay calm, next to the colon
I guess the solution will be [in there](https://github.com/flarum/emoji/blob/0155803b0503727c9962d3994f59e7f3d34dd629/js/src/forum/addComposerAutocomplete.js#L141-L158)

**Environment**
- Flarum version: all I have tested (b11-->b15)

**Comment by askvortsov1** [comment]
Figured this out, implemented the fix as part of the companion PRs to https://github.com/flarum/core/pull/2594.

**Comment by Ornanovitch** [comment]
I guess you just rock ! This is a major UX issue for all emojis lovers (I have plenty of them in my community), thank you !
