### ISSUE TITLE
N+1 Queries

### ISSUE THREAD

**Issue by SychO9** [flarum/core#2637]
Somewhat related to #2177 

We currently have a problem with N+1 queries, some endpoints have certain relationships eager loaded, but not others, because they are either not needed by the frontend yet still called in certain serializers, or needed but just not eager loaded.

I have found these endpoints so far with this issue.

* [x] /api - Tags (flarum/tags#120)
* [x] /api/discussions?filter[q]=lorem
  + [x] `mostRelevantPost` (#2639)
  + [x] `tags` (https://github.com/flarum/tags/pull/125)
* [ ] /api/notifications
* [x] /api/posts?include=user
  + [x] `discussion` (https://github.com/flarum/core/pull/2717)
  + [x] `discussion.tags` (https://github.com/flarum/tags/pull/125)
  + [x] `user.groups` (https://github.com/flarum/core/pull/2717)
  + [x] `mentionedBy` (https://github.com/flarum/mentions/pull/64)

* [x] /api/flags
  + [x] `post.discussion.tags` (https://github.com/flarum/tags/pull/125)
  + [x] `post.user.groups` (https://github.com/flarum/flags/pull/38)

**Tags - ShowForumController (flarum/tags#120)**
Relations: `lastPostedDiscussion` (`lastPostedDiscussion.state`, `lastPostedDiscussion.tags`)

In https://github.com/flarum/tags/pull/120 I decided to eager load the two relations used to fix the problem, but looking at it again, we really shouldn't have to do that, the TagsPage component only needs [three things](https://github.com/flarum/tags/blob/046913b5841dd14d1f3eb9651fabc7ea7429365a/js/src/forum/components/TagsPage.js#L57-L68) from the lastPostedDiscussion: title, lastPostNumber, lastPostedAt. All of which are basic information.

Could we either add that data to BasicDiscussionSerializer and use that instead of DiscussionSerializer, or create a custom DiscussionSerializer in the tags extension, exposing only the information we need, that would be cleaner than eager loading relations just because the default serializer assumes they're available.

**Search - ListDiscussionsController (#2639)**
Relations: `mostRelevantPost` (`mostRelevantPost.discussion`, `mostRelevantPost.discussion.tags`, `mostRelevantPost.user.groups`)

This one should be rather simple, this is what we currently do for the `firstPost` and `lastPost` relations, we can just apply the same logic to the `mostRelevantPost` relation.
https://github.com/flarum/core/blob/023871ef86d436cc14631ee63cbbfd3ef9fd4bf1/src/Api/Controller/ListDiscussionsController.php#L115-L123

**Posts - ListPostsController**
Relations: `user.groups`, `discussion` & `discussion.tags` (only when flags is enabled), `mentionedBy` (only when mentions is enabled)

This is a case scenario where some kind of `loadRelations` extender on `ApiController` would solve the problem (read https://github.com/flarum/core/issues/2637#issuecomment-786823441)

**Notifications - ListNotificationsController**
Relations: `subject.discussion` (`subject.discussion.tags`) and `subject.???` (`subject.???.???`)

This one may or may not be more complicated. When subjects are related to discussions, those discussions need tags loaded for ability checks: are they even necessary here ? no. But we do need sticky, locked, and follow data which are only exposed in the DiscussionSerializer.

Another thing is, depending on what the type is, there might be N+1 queries. I've found that `postMentioned` types need `mentionsUsers` relation loaded because it evaluates the content of the post, but I am not sure yet about other types.

**Flags - ListFlagsController**
Relations: `post.user.groups` `post.discussion.tags`

First one is simple, for the second one I'm not sure in which extension we want to eager load the relation.

**Comment by askvortsov1** [comment]
> In flarum/tags#120 I decided to eager load the two relations used to fix the problem, but looking at it again, we really shouldn't have to do that, the TagsPage component only needs three things from the lastPostedDiscussion: title, lastPostNumber, lastPostedAt. All of which are basic information.

I'm not sure of the use case for passing in `lastPostedDiscussion.tags` since the discussions are displayed per-tag and not vice versa, but `lastPostedDiscussion.state` would be quite useful for displaying read/unread status of "last posted discussions" on a tags/categories page. Although I think a better long term solution is rewriting TagsPage to load in tags via the API (with lastPostedDiscussion) as proposed in flarum/framework#2177, which allows us to omit the lastPostedDiscussion relation completely in the few tags (if any) we choose to send in the initial payload.

The `ListDiscussionsController` proposal makes sense to me :+1: 

I find the notifications one to be a little bit less of a priority (which is great since it's the hardest one :laughing:), I'll need to look into the code a bit more before opining on it.

**Comment by SychO9** [comment]
> I'm not sure of the use case for passing in lastPostedDiscussion.tags since the discussions are displayed per-tag and not vice versa

The DiscussionSerializer checks for abilities, which are routed to the tags extension's DicussionPolicy, which uses tag scopes, thus requiring the tags relationship. We could right now avoid a query for the `lastPostedDiscussion.tags` and instead loop through the queried tags and manually set the relationship, since we're currently loading all tags, but it doesn't matter that much since we will be changing the way tags are loaded in the next release anyway.

> Although I think a better long term solution is rewriting TagsPage to load in tags via the API (with lastPostedDiscussion) as proposed in flarum/framework#2177, which allows us to omit the lastPostedDiscussion relation completely in the few tags (if any) we choose to send in the initial payload.

Certainly.

**Comment by SychO9** [comment]
Some more on this:

### ListDiscussionsController
Other than the mentioned relation above that needs some of its relations eager loaded, there is also the `tags` relation, for the same reason, the DiscussionSerializer calls the discussion policies which triggers the DiscussionPolicy registered by the tags extension, which uses/calls the individual discussions's tags.

Whether the tags relation is included in the request or not, we have to always load it. For that we need to edit the tags extension and add a callback before data serialization to load the relation there.

### ListPostsController
Same thing with the `discussion.tags` relation for the same reasons mentioned above, except we can't just load the relation using a callback before data serialization, for two reasons:
* We would only want to load the relation if the `discussion` relation is included in the request, the callback before data serialization has no way of accessing the array of includes.
* Even if we had access to the included relations, loading the relation doesn't make a difference, that's because the relation can be accessed earlier, in my local tests, the flags extension's before data serialization callback executed first, and it called the relation before the tags extension could eager load it. This type of issue is most likely reproducible in other controllers with other extensions.

**Potential solution:**
What if we added a new method to our `ApiController` extender ? something like `loadRelations` that would load the required relations before the `prepareDataForSerialization` callbacks are executed. Its behaviour would be to load any given `relation` and only load `relation.secondRelation` if `relation` belongs to the includes.

**Comment by SychO9** [comment]
I'm closing this, if the future we'll have separate issues for these problems.

Notifications endpoint N+1 Queries issue has been split off to: flarum/issue-archive#113
