### ISSUE TITLE
Consolidate list keyboard navigation code from search, mentions, and tags

### ISSUE THREAD

**Issue by tobscure** [flarum/core#264]
The search results dropdown, mentions autocomplete dropdown, and the tag selection modal all present lists of items that are navigable using the up/down arrow keys. Currently the code to implement this functionality is duplicated in each instance. We should extract it into a reusable core util.

What needs to be done:

* Using the Search component as a base, work out a way to extract the following parts into a reusable core util:
    * The input's keydown event
    * The `getCurrentNumericIndex`, `getItem` and `setIndex` methods
* Allow the Tab key to select an item, in the same way that the Enter key does.

**Comment by franzliedke** [comment]
I consider this done.

I did not find a straight-forward solution how `getCurrentNumericIndex`, `getItem` and `setIndex` would fit in, but I hope that's fine.

@tobscure Any comments?

**Comment by tobscure** [comment]
Looks good 👍
