### ISSUE TITLE
Mentions/Emoji dropdown not scrollable

### ISSUE THREAD

**Issue by askvortsov1** [flarum/core#2640]
See https://github.com/flarum/core/issues/2628#issuecomment-786771268

**Comment by askvortsov1** [comment]
I took another look at this on nightly. When the mentions/emoji dropdown has too many elements, scroll seems to work fine even with the new changes to the composer. The issue seems to be that the mentions dropdown was being rendered outside the page, but in its entirety, so scroll just wasn't applicable (I assume thats the same issue as #2621). Forcing the mentions dropdown not to be rendered outside the screen seems to fix this (as was done alongside the editor drivers refactor). From my testing on nightly, this seems to not be applicable. @matteocontrini I would highly appreciate it if you could test it out and confirm.

**Comment by matteocontrini** [comment]
> From my testing on nightly, this seems to no longer be an issue. @matteocontrini I would highly appreciate it if you could test it out and confirm.

Still an issue, I'm told.


https://user-images.githubusercontent.com/2164763/109432112-ff36ae00-7a09-11eb-9229-2acbc1d89bdf.mp4

**Comment by askvortsov1** [comment]
On the downside, I have now been able to replicate this, and it is indeed around, On the bright side, I've been able to replicate this!

The following changes need to be made:

- Dropdowns extending outside the screen need to be scrollable. @SychO9 you're much better versed in CSS than I am; is this possible?
- The positioning logic for emoji and mentions dropdowns needs to be adjusted so that stuff ACTUALLY isn't displayed outside the screen. Since I can now replicate this, I'll work on it.

**Comment by SychO9** [comment]
It's an interesting case scenario, the dropdown is fine when creating a new discussion, but not when replying to an existing discussion. Because the dropdown has a `max-height` of 150px which is the perfect amount for the new discussion composer, but that limit needs to be `50px` for replying to discussions. I don't think there is a CSS class to tell the two composers apart, but it should be easy to add.

![flarum lan_d_158-double-the-cost10](https://user-images.githubusercontent.com/20267363/109433672-e29e7400-7a11-11eb-8a06-d67c4ed81a7c.png) ![flarum lan_d_158-double-the-cost10 (1)](https://user-images.githubusercontent.com/20267363/109433677-e6ca9180-7a11-11eb-8669-5399ff3a6a90.png)

**Comment by askvortsov1** [comment]
I don't think that solution is as comprehensive as would be preferred. I was thinking something along the lines of the following:

In the dropdown component, when it's opened, we can check its top and bottom coordinates, and ensure that both are inside the viewport. If one is outside the viewport, we adjust height to the difference between the y-coord of the one that IS in the viewport - the viewport height (or 0 if the top is outside the viewport).

**Comment by SychO9** [comment]
Actually what I said would only apply to the first line, so it's not a solution.

> In the dropdown component, when it's opened, we can check its top and bottom coordinates, and ensure that both are inside the viewport. If one is outside the viewport, we adjust height to the difference between the y-coord of the one that IS in the viewport - the viewport height (or 0 if the top is outside the viewport).

we have to fix it by adjusting the Javascript calculations then, CSS is powerless here.

**Comment by askvortsov1** [comment]
> Actually what I said would only apply to the first line, so it's not a solution.
> 
> > In the dropdown component, when it's opened, we can check its top and bottom coordinates, and ensure that both are inside the viewport. If one is outside the viewport, we adjust height to the difference between the y-coord of the one that IS in the viewport - the viewport height (or 0 if the top is outside the viewport).
> 
> we have to fix it by adjusting the Javascript calculations then, CSS is powerless here.

Yep. But that would fix it for any and all dropdowns, by ensuring that any content outside of the viewport is truncated, also solving #2621, which I think is quite worth it

**Comment by askvortsov1** [comment]
Fixed in https://github.com/flarum/emoji/commit/259b934af706e1d8763b8efc8d0e67bbf92cf45f, https://github.com/flarum/mentions/commit/e39c798298ba2b3130ed97945aefeff6af14a5d4

My global solution wouldn't work here because AutocompleteDropdown doesn't actually use the Dropdown component. I'll revisit that in application to the search dropdown though.

**Comment by matteocontrini** [comment]
@askvortsov1 thanks! Not sure why this was removed from the beta.16 milestone though?

**Comment by SychO9** [comment]
@matteocontrini we try to keep issues that we've introduced in the same release off of the milestone
