### ISSUE TITLE
Improve translation key consistency

### ISSUE THREAD

**Issue by tobscure** [flarum/core#265]
We need to solidify our strategy for naming translation keys, and apply it globally for consistency. Initial discussion took place here: http://discuss.flarum.org/d/336-potential-l10n-stumbling-blocks/10

The basic idea is to have **context-related suffixes** for similar translations (see stumbling block 4) and **prefixes** to group related translations (stumbling block 5). However, this strategy needs further refinement, and then needs to be applied.

What needs to be done:

* Go through all components in js/forum/src/components, looking for instances of `app.trans`, cross-matching the keys with their translations in locale/en.yml. Rename keys where necessary so that they are consistent and descriptive.
* Through this process, come up with a brief list of rules/guidelines to follow when naming translation keys.
* Apply the strategy to default extension translations too.

**Comment by tobscure** [comment]
@DCSJAPAN you might be interested in tackling this :)

**Comment by DCSJAPAN** [comment]
I'd be happy to ... give me a while to wrap up the aftermath of my translation job and I'll get right on it.

**Comment by DCSJAPAN** [comment]
Okay, I plan to get started on this soonish.

Do you need me to keep a log of key name changes? Any preferences regarding format of the log?

**Comment by tobscure** [comment]
Yes a log would probably be helpful :) Thanks!

**Comment by dcsjapan** [comment]
Just adding a mention here for completeness' sake:

https://github.com/flarum/core/pull/536

This more or less takes care of the first bullet point in the OP.

Prerequisites for using the changes are noted in the PR description!

**Comment by tobscure** [comment]
Closing as this is done. Thanks again @dcsjapan!

**Comment by dcsjapan** [comment]
I thought this had already been closed! ... You're very welcome!
