### ISSUE TITLE
Composer goes off screen on iOS when starting to type

### ISSUE THREAD

**Issue by matteocontrini** [flarum/core#2652]
## Bug Report

**Current Behavior**

After #2279 and #2631 were applied, when replying to a discussion on iOS by tapping the "reply" area at the bottom of a discussion, it happens that when the user starts typing the composer goes off the screen, even if its position is fixed, and the user needs to scroll up.

**Steps to Reproduce**
1. Go to a forum on nightly with Safari on iOS
2. Open a discussion
3. Tap the "reply" area at the bottom
4. Tap the composer textbox and start writing
5. Sometimes: the page will scroll to the bottom and the composer will go off screen, forcing you to scroll up manually

**Expected Behavior**

The composer should be fixed at the top.

**Screenshots**

![ezgif-com-video-to-gif](https://user-images.githubusercontent.com/2164763/109664516-7cc6ff00-7b6d-11eb-94ae-42ea26b9010b.gif)

**Environment**
- Flarum version: beta.15 with changes from #2279 and #2631 applied
- Website URL: https://forum.fibra.click
- Browser: Safari on iOS. I don't have the versions.

I'll ask the iOS user reporting this to test on nightly.flarum.site to see if it might be an extension or something else on my forum causing this.

**Comment by matteocontrini** [comment]
Confirmed on nightly. It doesn't happen always but most of the times, also on iPad although it just bumps a bit.


https://user-images.githubusercontent.com/2164763/109668029-088e5a80-7b71-11eb-9fe1-a5dab250183a.MP4

**Comment by SychO9** [comment]
Thank you!

Did some research, I now understand why the composer was initially using `position: absolute`, fixed position with the virtual keyboard just doesn't work on iOS.

https://medium.com/@im_rahul/safari-and-position-fixed-978122be5f29
https://gist.github.com/avesus/957889b4941239490c6c441adbe32398#:~:text=Mobile%20Safari%20does%20not%20support,%2C%20focus%20%2C%20and%20blur%20events.

I don't think we should revert back to absolute positioning either as that fixed a couple of annoying issues. What we should do is only apply the old absolute positioning for iOS users.
