### ISSUE TITLE
Close button in minimized composer doesn't work on Safari iOS

### ISSUE THREAD

**Issue by matteocontrini** [flarum/core#2653]
## Bug Report

**Current Behavior**

On Safari on iOS, the button to close the minimized composer (sometimes?) doesn't do anything when tapped.

**Steps to Reproduce**
1. Open the composer
2. Minimize it
3. Tap the X button and observe that it doesn't do anything

**Expected Behavior**

The X button should dismiss the composer.

**Screenshots**

https://user-images.githubusercontent.com/2164763/109706300-11932200-7b99-11eb-95b3-48b8bdbbe44d.mp4

**Environment**
- Flarum version: beta.15
- Browser: Safari on iOS

**Comment by askvortsov1** [comment]
I'm having trouble reliably replicating this on a safari device. Sometimes when I try to click the close button it triggers the Safari bottom nav menu, but other than that, that particular piece works decently well for me.
