### ISSUE TITLE
Find and fix hardcoded translations

### ISSUE THREAD

**Issue by tobscure** [flarum/core#266]
Although most of the client is translatable, there are still a few instances of hardcoded text which need to be fixed.

What needs to be done:

* Make `utils/punctuate` and `utils/abbreviateNumber` translatable. See http://discuss.flarum.org/d/336-potential-l10n-stumbling-blocks/5
* Find any other hardcoded translations by temporarily emptying en.yml and searching far and wide for text that is still in English.
* Do the same for all default extensions.
* Make the whole administration section translatable (it is all hardcoded at the moment).

**Comment by franzliedke** [comment]
@dcsjapan Can we close this?

**Comment by dcsjapan** [comment]
I think it's safe to close it now.

As you say, we've caught enough of them that instead of actively looking for them, we can simply wait for localizers to mention any they find. Hopefully there won't be any! :smile:
