### ISSUE TITLE
[flarum/suspend] permissions on viewing suspended users

### ISSUE THREAD

**Issue by ajaypayne** [flarum/core#2662]
## Bug Report

**Current Behavior**
As a non-admin who has permission to suspend, I am unable to see suspended users using the Search/SuspendedGambit.
As an admin it works as expected and as a user without permission it works as expected.

**Steps to Reproduce**
1. Go to '/api/users?include&filter%5Bq%5D=is%3Asuspended' as a non-admin who has suspend permissions
2. Results will be empty even if you have suspended users

**Expected Behavior**
A user with suspended permissions should see results
**Screenshots**
n/a - can't prove the behaviour from a screenshot

**Environment**
- Flarum version: 0.1.0-beta.15
- Website URL: n/a
- Webserver: apache
- Hosting environment: local
- PHP version: 7.4.15
- Browser: n/a

```
n/a
```

**Possible Solution**
Update permission check from can('suspend') to hasPermission('user.suspend') in gambit

**Additional Context**
n/a

**Comment by askvortsov1** [comment]
> Update permission check from can('suspend') to hasPermission('user.suspend') in gambit

Interesting... `->can('suspend')` should be running into https://github.com/flarum/core/blob/84ded0ce50093287cd0a9680f248b4e34ef9c2d8/src/User/Access/UserPolicy.php#L21-L21, but isn't because no target is provided. Perhaps the permission check might be updated to use an instance of `Guest`?

**Comment by imorland** [comment]
Yep, `->can('suspend', new Guest())` works a treat. PR incoming!
