### ISSUE TITLE
Regression: ListPostsController not correctly filtering by user ID

### ISSUE THREAD

**Issue by davwheat** [flarum/core#2671]
## Bug Report

**Current Behavior**
#2479 introduced a regression where passing `?filter[user]=<id>` would not filter for posts by the user specified.

**Steps to Reproduce**
1. Go to https://nightly.flarum.site/
2. Go to any user profile
3. See there are posts from other users visible on their user profile page

**Expected Behavior**
Only posts by that user should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/7406822/110246511-c6de2500-7f5f-11eb-9ddc-7197dfc42f2d.png)

**Environment**
- Flarum version: dev-master (458a5cc to 4b0ad69 (current))

**Comment by askvortsov1** [comment]
It would be preferable to use the new `author` key (even though it was introduced accidentially) for consistency with the discussion filters/gambits. For this reason, the solution discussed internally was:

- Duplicating AuthorFilter to a deprecated UserFilter, which would use the user key (or even better, extending and overriding the getFilterKey method)
- Changing the frontend code to query by `author`, not by `user`.
