### ISSUE TITLE
Incorrect canonical url on /tags and /all in when using kubernetes (depending on which route is not default)

### ISSUE THREAD

**Issue by imorland** [flarum/core#2673]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Steps to Reproduce**
1. Go to https://community.giffgaff.com
2. View source
3. Notice the canonical url is set correctly
4. Go to https://community.giffgaff.com/all
5. View source
6. Notice the canonical url has picked up the internal kubernetes hostname

**Expected Behavior**
The correct url is present in the canonical parameter

**Environment**
- Flarum version: 0.1.0-beta.13 and 0.1.0-beta.15 and `dev-master`
- Website URL: https://community.giffgaff.com https://preview.community.giffgaff.com
- Webserver: apache
- Hosting environment: kubernetes
- PHP version: 7.4.16
- Browser: erm, any

**Possible Solution**
The issue lies in two files:
https://github.com/flarum/core/blob/ba9665e9db0723af79aa5f381ecabb85b2b1ebcd/src/Forum/Content/Index.php#L88
https://github.com/flarum/tags/blob/f85cc591021f32627be32f0be9f49c3a0b0eb71f/src/Content/Tags.php#L97

Instead of retrieving the hostname from the request `$request->getUri()->withQuery('')`, something like `$this->url->to('forum')->base() . $request->getUri()->getPath()`

PR incoming shortly!

**Comment by askvortsov1** [comment]
I've taken a quick look at other parts of the code; there's one other instance in core where `$request->getUri()` is used without getting path, at https://github.com/flarum/core/blob/ba9665e9db0723af79aa5f381ecabb85b2b1ebcd/src/Install/Controller/InstallController.php#L65-L65. I don't think we can do much about though, as the "base url" needs to come from somewhere. Also, I'm assuming a complex kubernetes-based setup like GiffGaff's probably has a slightly more robust install process than just running the default GUI and hoping it works.

**Comment by imorland** [comment]
Yeah, I'm not sure if/how anything can be done on that one. Like you say, the install used at giffgaff does not run the default GUI setup, so, for giffgaff at least, all good there

**Comment by imorland** [comment]
Note: https://preview.community.giffgaff.com (beta15) has now been updated including this fix. Please only refer to https://community.giffgaff.com (beta13) to see the live example
