### ISSUE TITLE
[emoji] Emoji fails to render

### ISSUE THREAD

**Issue by imorland** [flarum/core#2677]
## Bug Report

See https://github.com/flarum/QualityAssurance/issues/16

- Create a new post
- enter `:` to bring up the emoji selector
- pick an emoji, notice it renders in the preview
- post
- notice only `:` is displayed

![image](https://user-images.githubusercontent.com/16573496/110375137-7511c980-8049-11eb-86c7-d75df4e07859.png)

![image](https://user-images.githubusercontent.com/16573496/110375094-662b1700-8049-11eb-9f8f-7d7b48c65145.png)

**Environment**
- Flarum version: `dev-master`
- Website URL: local and nightly
- Webserver: apache
- Hosting environment: docker
- PHP version: 8.0.3
- Browser: FF 68

**Comment by askvortsov1** [comment]
Fixed in https://github.com/flarum/markdown/commit/01bb723c303ea331118f326f88f9eb7e9d725c42.
