### ISSUE TITLE
Improve admin CP appearance page, allow logo upload

### ISSUE THREAD

**Issue by tobscure** [flarum/core#268]
We want to allow uploading a custom favicon and header image. Additionally it'd be cool to show a live preview (using an SVG) of what the color scheme will look like. Something like this:

![screen shot 2015-08-28 at 1 26 03 pm](https://cloud.githubusercontent.com/assets/128862/9538854/60f6fee2-4d88-11e5-9d42-7457c93209e0.png)

What needs to be done:
* Add API endpoints for uploading a favicon and a header image.
* Redesign/add fields to the AppearancePage component.
* Design a simple SVG showing Flarum's basic layout, and give the appropriate elements class names so they can have their colors changed via JavaScript.
* Hook up the color buttons in the AppearancePage to update the preview SVG.

**Comment by franzliedke** [comment]
@tobscure Do you have some kind of backlog to store ideas like the SVG preview that may be worth revisiting after the first final?
