### ISSUE TITLE
Suggestion: DB table name prefix

### ISSUE THREAD

**Issue by neo22s** [flarum/core#269]
DB Usage of prefix on table names will make it lot easier to check which tables belong to flarum in case the client installs in an existing DB.

something like: flarum_config

What do you think?

ps: I wanted to post in the forum but for some reason I can not.

**Comment by franzliedke** [comment]
There's actually a setting for the prefix already. Thing is, it breaks the forum after installation ;)

I'll make this a priority for the next beta release.

**Comment by neo22s** [comment]
I can also give some tips to improve performance on the DB structure level if you want ;) for example theres need to use a glob on the table settings? or more usage of myisam on many tables etc ;)

Great work guys. Regards!

**Comment by franzliedke** [comment]
Considering this to be fixed - I optimized a whole bunch of raw query expressions to avoid them ignoring the database prefix. I'll keep testing with database prefix on my local install, so I'll hopefully come across any further errors.

**Comment by tobscure** [comment]
:D

**Comment by tobscure** [comment]
@franzliedke Do we want to have a field for it in the installer though?

**Comment by franzliedke** [comment]
The web installer? Yeah, good point, I'll make a note to add it - it's already in the console version...

**Comment by neo22s** [comment]
In the web installer is good to have an optional input table prefix ;)

Also to review all permissions hosting compatibility etc... you can take a look at https://github.com/open-classifieds/openclassifieds2/tree/master/install

We also have a 1 file installer:
https://github.com/open-classifieds/openclassifieds2/blob/master/install-openclassifieds.php

hope this helps we worked hard during years to improve this and cover many many scenarios

**Comment by franzliedke** [comment]
Okay, I added the field to the web installer.

@neo22s Thanks for the links; I'll take a look at those when working on validation etc. :)
