### ISSUE TITLE
[Webpack config] Add support for Mithril fragments within JSX

### ISSUE THREAD

**Issue by davwheat** [flarum/core#2711]
## Bug Report

**Current Behavior**
In JSX, use of `<></>` is synonymous of [Fragment vnodes](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html). It'd be great to have support for this within Flarum extensions.

Currently we can create fragments using `[]`, but having different syntaxes can lead to being confusing. In my opinion, we should follow the general consensus throughout JSX-using libraries.

**Solution**

At a glace, we should be able to add this by modifying the webpack config to include `pragmaFrag: 'm.fragment'` alongside the existing `pragma: 'm'`. This is explained one scroll-click up from this heading: https://babeljs.io/docs/en/babel-plugin-transform-react-jsx/#installation

**Steps to Reproduce**
1. Attempt to render a component wrapped in `<>{...}</>`
2. See error in console that "React is not defined"

**Comment by askvortsov1** [comment]
Huh, I did not know this existed... Cool!
