### ISSUE TITLE
[Testing] No way to run an extension's migration during setup

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#2718]
## Bug Report

When using `flarum/testing` in a community extension, there's no way of running the migrations during setup, so it's not possible to run integration tests that use new database tables/columns.

**Environment**
- Flarum version: beta 16

**Possible Solution**

We need a way to pass an array of community extensions to run migrations for to `Flarum\Testing\integration\Setup\SetupScript` in our `setup.php` file. One might not be enough, if our extension depends on other community extensions we will also want to run those other migrations.

Ideally we should also be able to pass other `Step` classes to add to the `$pipeline` to further customize the setup without having to copy the full setup class.

This is the very crude implementation I made for my extension. But ideally I think we should merge this with the step that enables the core extensions.

```php
<?php

namespace Kilowhat\Formulaire\Tests\integration;

use Flarum\Database\DatabaseMigrationRepository;
use Flarum\Database\Migrator;
use Flarum\Extension\Extension;
use Flarum\Install\DatabaseConfig;
use Flarum\Install\Step;
use Flarum\Install\Steps\ConnectToDatabase;
use Illuminate\Filesystem\Filesystem;

class EnableFormulaireInstallStep implements Step
{
    protected $dbConfig;
    protected $db;

    public function __construct(DatabaseConfig $dbConfig)
    {
        $this->dbConfig = $dbConfig;
    }

    public function getMessage()
    {
        return 'Enabling Formulaire extension';
    }

    public function run()
    {
        $connect = new ConnectToDatabase($this->dbConfig, function ($db) {
            $this->db = $db;
        });

        $connect->run();

        $migrator = new Migrator(
            new DatabaseMigrationRepository($this->db, 'migrations'),
            $this->db,
            new Filesystem
        );

        $extension = new Extension(__DIR__ . '/../..', [
            'name' => 'kilowhat/flarum-ext-formulaire',
        ]);

        $extension->migrate($migrator);
    }
}
```

In `setup.php`, inside `SetupScript::run`:

```php
    $pipeline->pipe(function () use ($dbConfig) {
            return new EnableFormulaireInstallStep($dbConfig);
        });
```

**Additional Context**
This affects my Formulaire extension which was previously using a modified copy of core's integration tests. The code above is what I already used for Flarum beta 15.

**Comment by clarkwinkelmann** [comment]
Following @askvortsov1 explanations on Discord I now understand the migrations for community extensions are actually meant to run when the extension is enabled with `TestCase::extension()` in a test. Right now I unfortunately cannot verify this fixes the issue in my extension because of the other issue affecting `->extension()` :sweat_smile:  #2719

I don't particularly like the idea of running complementary migrations in `setUp`. I understand the benefit of sharing the test database between extensions, but I'd rather run all migrations in `setup`, and run `setup` again each time I switch extension.

**Comment by askvortsov1** [comment]
> but I'd rather run all migrations in setup, and run setup again each time I switch extension.

You need to delete and un-delete the database though... Actually, could we start the setup script process by dropping all tables in the test database? That would make re-running the `setup` command much easier/simpler (no need to recreate the DB every time), and would lead to a bit more reliably consistent state.

> but I'd rather run all migrations in setup

This part I'm not 100% sure about. You'd be stuck with the database migration effects of the extension on every test case run, even if you want to test against the default state, when the extension isn't installed or enabled. Maybe this could be an option?

I'll note that this is currently an issue with the current setup too: migrations run implicitly on enable, but we don't run them down on test case teardown. That's a different issue though.

**Comment by clarkwinkelmann** [comment]
> Actually, could we start the setup script process by dropping all tables

While it's a bit of a different issue, I'd love a flag to do this, even if it's not the default behavior. Just like the `migrate:fresh` option of Laravel (or is it `reset`? I never remember).

> even if you want to test against the default state, when the extension isn't installed or enabled

I believe right now it can't be done, since you can't be sure the database is clean at the start. Also can't tests run async? Or would you be sure those tests run before the others that will run the migrations?

---

I think whatever we choose, it should be consistent between core and community extensions. Right now the core extensions get migrated and enabled during setup, but not community extensions. Either we run all, or we run none. If we run none, it actually kind of solves the issue of not putting any list of enabled extensions in the database during setup.

**Comment by askvortsov1** [comment]
>  Right now the core extensions get migrated and enabled during setup

Enabled yes, but only migrated if they're in the `require-dev` of the extension being tested.

> If we run none, it actually kind of solves the issue of not putting any list of enabled extensions in the database during setup.

I'm strongly in favor of enabling none. Testing setup should start with just the default core state; extension stuff should be added later IMO.
