### ISSUE TITLE
Clearing cache might break forum with exception related to text formatter

### ISSUE THREAD

**Issue by matteocontrini** [flarum/core#2723]
## Bug Report

**Current Behavior**

As discussed [here](https://discuss.flarum.org/d/26529-argument-1-passed-to-must-be-an-instance-of-s9etextformatterrenderer) in some setups (?) clearing cache with `php flarum cache:clear` breaks the forum.

The boot exception is:

>Argument 1 passed to Flarum\Mentions\Formatter\FormatPostMentions::__invoke() must be an instance of s9e\TextFormatter\Renderer, instance of __PHP_Incomplete_Class given, called in /usr/local/openresty/nginx/html/flarum16/vendor/flarum/core/src/Foundation/ContainerUtil.php on line 30

Removing everything in `storage/cache` fixes the issue, until next time.

**Environment**
- Flarum version: beta16
- Webserver: nginx
- Hosting environment: local installation
- PHP version: 7.3

```
Flarum core 0.1.0-beta.16
PHP version: 7.3.23-3+ubuntu20.04.1+deb.sury.org+1
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, sodium, standard, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, Zend OPcache
+----------------------+----------------+--------+
| Flarum Extensions    |                |        |
+----------------------+----------------+--------+
| ID                   | Version        | Commit |
+----------------------+----------------+--------+
| flarum-flags         | v0.1.0-beta.16 |        |
| flarum-markdown      | v0.1.0-beta.16 |        |
| flarum-approval      | v0.1.0-beta.16 |        |
| flarum-bbcode        | v0.1.0-beta.16 |        |
| flarum-emoji         | v0.1.0-beta.16 |        |
| flarum-lang-english  | v0.1.0-beta.16 |        |
| flarum-lock          | v0.1.0-beta.16 |        |
| flarum-mentions      | v0.1.0-beta.16 |        |
| flarum-statistics    | v0.1.0-beta.16 |        |
| flarum-sticky        | v0.1.0-beta.16 |        |
| flarum-subscriptions | v0.1.0-beta.16 |        |
| flarum-suspend       | v0.1.0-beta.16 |        |
| flarum-tags          | v0.1.0-beta.16 |        |
| flarum-likes         | v0.1.0-beta.16 |        |
+----------------------+----------------+--------+
Base URL: http://flarum16.localhost
Installation path: /usr/local/openresty/nginx/html/flarum16
Debug mode: ON
```

**Comment by JoshyPHP** [comment]
`__PHP_Incomplete_Class` would indicate an autoloading issue, I assume with the class generated for [the renderer](https://s9etextformatter.readthedocs.io/Internals/PHP_renderer/). So either the SPL autoloader wasn't set or the file was missing when the object was unserialized.
