### ISSUE TITLE
Admin setting help text disappears after redraw

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#2728]
## Bug Report

**Current Behavior**
The help text defined Using `ExtensionData.registerSetting()` disappears after the first Mithril redraw of the settings page. 

**Steps to Reproduce**

Use following javascript code:

```js
app.initializers.add('my-extension', () => {
    app.extensionData.for('my-extension')
        .registerSetting({
            type: 'switch',
            setting: 'my-setting',
            label: 'A label',
            help: 'A help text',
        });
});
```
![image](https://user-images.githubusercontent.com/5264300/112039374-4533ed00-8b44-11eb-8400-aac1d9c81df9.png)

Click switch:

![image](https://user-images.githubusercontent.com/5264300/112039428-50871880-8b44-11eb-9012-6ccd79cd025e.png)

*Poof* help text is gone and won't come back until next time the page is opened.

**Expected Behavior**
Help text shouldn't disappear.

**Environment**
- Flarum version: beta 16, likely earlier

**Possible Solution**

The problem is here https://github.com/flarum/core/blob/706eaeda4153de130b8530713f00772df7146458/js/src/admin/components/AdminPage.js#L103

The `help` attribute is `delete`ed from the object, but since the object is modified by reference, it's gone forever.

The object needs to be cloned before the `help` attribute is removed.

That `delete` statement seems very out of place. Why do we remove `help` and not `label` ?

Also there's likely a similar issue with `className` lower in the file where an additional `FormControl` class will be added on each redraw https://github.com/flarum/core/blob/706eaeda4153de130b8530713f00772df7146458/js/src/admin/components/AdminPage.js#L124

**Comment by askvortsov1** [comment]
Something along the lines of:

````
const { setting, help, ...componentAttrs } = entry;
```

seems more natural, with `componentAttrs` being passed to the actual input elements instead of the full `entry` object.

**Comment by clarkwinkelmann** [comment]
As a note, I used the following workaround in https://github.com/clarkwinkelmann/flarum-ext-emojionearea which is impacted by this issue.

```js
    // Workaround for https://github.com/flarum/core/issues/2728
    override(AdminPage.prototype, 'buildSettingComponent', function (original, entry) {
        return original({...entry});
    });
```
