### ISSUE TITLE
Crash when opening admin page

### ISSUE THREAD

**Issue by fcpwiz** [flarum/core#273]
Just installed Flarum, and when I go to the Admimistration page I get a crash:

PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20121212/php_filepro.dll' - /usr/local/lib/php/extensions/no-debug-non-zts-20121212/php_filepro.dll: cannot open shared object file: No such file or directory

**Comment by pcrumm** [comment]
`filePro` isn't a dependency for flarum--instead, this looks like a PHP configuration issue. The good news is that it's pretty easy to fix :)

Head to your `php.ini` file (probably in `C:\windows`), search for `filepro.dll` in that file, and add a semicolon (`;`) to the beginning of any line that mentions it. That line should look something like this:

```
extension=php_filepro.dll
```

**Comment by fcpwiz** [comment]
@pcrumm Thanks for the reply! I haven't messed with the php.ini file for a bit. How would I find it via FileZilla?

**Comment by pcrumm** [comment]
@fcpwiz what host are you on?

**Comment by fcpwiz** [comment]
Godaddy VPS.

**Comment by pcrumm** [comment]
@fcpwiz It looks like you can just [drop a php.ini file in the root directory from FileZilla](https://www.godaddy.com/help/phpiniuserini-not-taking-effect-5647), but I haven't been able to find a sensible default for what you can use as a basis there.

Safest next step is to contact GoDaddy support (with the error message you initially supported here) and ask them to point you in the right direction.

**Comment by tobscure** [comment]
Closing this, assuming it's not a Flarum issue.

**Comment by fcpwiz** [comment]
@pcrumm I added the semicolon at the end of it, and I'm still getting the error.

**Comment by pcrumm** [comment]
Start, not end :)
On August 27, 2015 at 11:36:23 AM, fcpwiz (notifications@github.com) wrote:

@pcrumm I added the semicolon at the end of it, and I'm still getting the error.

**Comment by fcpwiz** [comment]
Oh haha

**Comment by fcpwiz** [comment]
@pcrumm Ok, I moved the semicolon to the start of that line, restarted Apache, and the error still persists.

**Comment by fcpwiz** [comment]
Here, you try loading the page up: http://forums.fcpwiz.com/admin

**Comment by fcpwiz** [comment]
Now that I look further into this, it looks like I get this error whenever I visit a page that changes the domain. (Ex. forums.fcpwiz.com -> forums.fcpwiz.com/whatever/)

**Comment by fcpwiz** [comment]
@pcrumm How do I download the php.ini via SSH? I'm already in the server folder containing the php.ini file.

**Comment by fcpwiz** [comment]
@pcrumm You there? This issue is still present.

**Comment by fcpwiz** [comment]
@pcrumm It's been a month and I still have this issue. Please reply.

**Comment by franzliedke** [comment]
He did. You're supposed to add the semicolon at the beginning, not the end.

**Comment by fcpwiz** [comment]
@franzliedke I did do that but I'm still getting the issue.

**Comment by franzliedke** [comment]
You're getting the same error message about the filepro extension? That means it's still being loaded (albeit unsuccessfully). Please contact your host then.

**Comment by fcpwiz** [comment]
Yeah the error is a bit different from before:

`PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20131226/php_fileinfo.dll' - /usr/local/lib/php/extensions/no-debug-non-zts-20131226/php_fileinfo.dll: cannot open shared object file: No such file or directory`

**Comment by fcpwiz** [comment]
Ah! I was in the wrong php.ini file. I fixed that error but now I have a new one:

Flarum\Http\RouteNotFoundException thrown with message ""

Stacktrace:
#14 Flarum\Http\RouteNotFoundException in /home/forums/public_html/flarum/vendor/flarum/core/src/Http/RouterMiddleware.php:60
#13 Flarum\Http\RouterMiddleware:__invoke in <#unknown>:0
#12 call_user_func in /home/forums/public_html/flarum/vendor/zendframework/zend-stratigility/src/Dispatch.php:79
#11 Zend\Stratigility\Dispatch:__invoke in /home/forums/public_html/flarum/vendor/zendframework/zend-stratigility/src/Next.php:113
#10 Zend\Stratigility\Next:__invoke in /home/forums/public_html/flarum/vendor/flarum/core/src/Api/Middleware/ReadJsonParameters.php:32
#9 Flarum\Api\Middleware\ReadJsonParameters:__invoke in <#unknown>:0
#8 call_user_func in /home/forums/public_html/flarum/vendor/zendframework/zend-stratigility/src/Dispatch.php:79
#7 Zend\Stratigility\Dispatch:__invoke in /home/forums/public_html/flarum/vendor/zendframework/zend-stratigility/src/Next.php:113
#6 Zend\Stratigility\Next:__invoke in /home/forums/public_html/flarum/vendor/flarum/core/src/Forum/Middleware/LoginWithCookie.php:47
#5 Flarum\Forum\Middleware\LoginWithCookie:__invoke in <#unknown>:0
#4 call_user_func in /home/forums/public_html/flarum/vendor/zendframework/zend-stratigility/src/Dispatch.php:79
#3 Zend\Stratigility\Dispatch:__invoke in /home/forums/public_html/flarum/vendor/zendframework/zend-stratigility/src/Next.php:113
#2 Zend\Stratigility\Next:__invoke in /home/forums/public_html/flarum/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php:75
#1 Zend\Stratigility\MiddlewarePipe:__invoke in /home/forums/public_html/flarum/vendor/zendframework/zend-diactoros/src/Server.php:166
#0 Zend\Diactoros\Server:listen in /home/forums/public_html/index.php:60

**Comment by franzliedke** [comment]
Which server are you using? Apache?

Also, can you share a screenshot of the full error page? The variables and stuff shown on the right-hand side often help with debugging, too...

**Comment by fcpwiz** [comment]
@franzliedke Sorry, I should've said that I got this fixed. My .htaccess file was outdated.

**Comment by franzliedke** [comment]
Awesome. :+1:
