### ISSUE TITLE
Extensions with no title or description breaks the search input in admin

### ISSUE THREAD

**Issue by Nearata** [flarum/core#2736]
## Bug Report

**Current Behavior**
If an extension with empty title or description is installed, the search input in the admin panel will broke.

**Steps to Reproduce**
1. Install an extension without title or description
2. Go to 'admin panel'
3. Click on 'Search Extensions'
4. Type something
5. See error

**Expected Behavior**
Shouldn't happen.

**Environment**
- Flarum version: 0.1.0-beta.16

**Additional Context**

```js
TypeError: Cannot read property 'toUpperCase' of undefined
    at AdminNav.js:131
    at Array.map (<anonymous>)
    at AdminNav.js:127
    at Array.map (<anonymous>)
    at e.n.extensionItems (AdminNav.js:118)
    at e.n.view (AdminNav.js:19)
    at Function.s (render.js:30)
    at render.js:482
    at h (render.js:419)
    at f (render.js:302)
```

The problem is here:

https://github.com/flarum/core/blob/d642fb531c1335c33ff7515da367f6815ea93b12/js/src/admin/components/AdminNav.js#L131

**Comment by askvortsov1** [comment]
Should be simple enough to fix, just need to add a check that title and discussion exist (or default them to empty strings)
