### ISSUE TITLE
Laravel integration

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#274]

**Comment by bgies** [comment]
Well, this is fairly important to me... the most important being integrating the logins for the website and forum.... either by using my Laravel Auth code for the forum, or the forum login for the website.... I could get by with either, but I think using the Laravel Login for the forum is the way most Laravel developers would go, because most websites have something different about their logins... maybe just using different ACL components...

**Comment by franzliedke** [comment]
I know that a community member is currently experimenting with this. I'll share once I hear back from him. :)

**Comment by anlutro** [comment]
Would it be too far fetched to remove "Laravel" from this issue? Since you're only using packages and not the framework itself, it seems natural to me that you should be able to integrate with any composer-driven PHP application regardless of framework.

**Comment by franzliedke** [comment]
Yes and no. Of course integration should be possible with any Composer project if you invest more or less work. But since we are using many of Laravel's contracts, we intend to make it super easy to integrate with a Laravel project.

**Comment by stellasoft-jim** [comment]
Hi.
Is there any update on this issue at all, whether in a non official fork or perhaps some staging area?
Cheers.

**Comment by MichalKarnicki** [comment]
Hi @tobscure , just wanted to ask what the update of milestones actually means :)? I'm interested in using Flarum and making use of Laravel auth for Flarum, hence I wonder whether I should be looking into a solution myself or there's someone maybe working on it already? Thank you!

PS I'm new to Flarum and super excited about it!

**Comment by tobscure** [comment]
@MichalKarnicki We're currently planning some big changes to the Flarum codebase — I spent a little bit of time thinking about Laravel integration as part of this and I have some ideas. Stay tuned :)

**Comment by MichalKarnicki** [comment]
@tobscure This is exciting 💯 ! From the issues and comments I'm pretty sure that integration will make a LOT of people happy :)! I planned to deploy Flarum shortly, but perhaps it's worth a wait though. Do you think the changes you mentioned can make it in in a month time? (Considering there's some downtime in December, too :) ). (Alternatively, are these changes developed publicly so we can have a peek :D? Thank you for your lovely product!

**Comment by tobscure** [comment]
@MichalKarnicki Sorry I don't think Laravel integration will be ready in a month. The changes will be developed publicly starting soon, they're still in the planning phase at the moment.

**Comment by MichalKarnicki** [comment]
@tobscure Appreciate the quick response! No problem, I'm excited you guys will be working on the changes publicly. Maybe I'll be able to contribute. Once again, thank you for Flarum and good luck with planning! 👍

**Comment by amdad** [comment]
Hey Toby, by saying Laravel you mean also OctoberCMS? Which is top Laravel CMS out there? https://discuss.flarum.org/d/2297-october-cms-laravel-php

**Comment by dav-is** [comment]
@amdad That's a separate issue.

**Comment by mkarnicki** [comment]
For those who desperately need Flarum and Laravel auth integration, have a look at [this blog post](https://wogan.blog/2017/02/12/integrating-laravel-and-flarum/)

PS I was originally @MichalKarnicki, changed my github username to match Twitter.

**Comment by amdad** [comment]
No i rewelka :)

**Comment by tobscure** [comment]
@franzliedke what's the status of this in the context of #1416?

**Comment by franzliedke** [comment]
#1416 will make this easier, I think. I will have to sit down and try out an integration from scratch once we get that in. Will report back then.

**Comment by askvortsov1** [comment]
I'm a bit confused as to what this actually entails. To be honest, I feel like this is better left to the community, via projects and extensions like https://github.com/kalynrobinson/flarum-laravel-integration. I believe that flarum is intended as a standalone app, right?

If something were to be done to improve this, I think the focus should be on making it easier to install flarum on a subdirectory with nginx (since apache plays fairly nicely with this by default).

**Comment by franzliedke** [comment]
We're leaving this to the community for now, but the plan is to provide an official bridge for integrating Flarum into an existing Laravel site. Given that we use Laravel components, it's not too big of a deal. (Apart from their versioning policy, maybe.)
