### ISSUE TITLE
Implement preloading and prefetching

### ISSUE THREAD

**Issue by davwheat** [flarum/core#2741]
## Feature request

Preloading and prefetching could result in ~100ms-200ms off the top of load times on Flarum forums.

We could preload:
- JS
- CSS
- FontAwesome font files

We could preconnect to:
- Twemoji CDN

**Comment by tankerkiller125** [comment]
We could actually do this with middleware if we wanted, and then use an extension API from there if we wanted.

I've actually created a middleware that I use on my sites that does this automatically based on the contents.

https://github.com/flarum-tank/middleware/blob/master/src/AddPreloadHeaders.php
https://github.com/flarum-tank/middleware/blob/master/src/InsertDNSPrefetch.php

**Comment by askvortsov1** [comment]
I would be open to these (or a variant) being included in core. Mixed feelings about parsing the HTML via regex though, but I'm not sure there's a better option (invoking a full HTML parser might be a bit much).

**Comment by tankerkiller125** [comment]
I'm not a huge fan of the regex either, however from what I can tell it doesn't add much if any slowdown to response times. And it's simple without loading a full blown parser. Which is why I did it with regex over anything else.
