### ISSUE TITLE
[Markdown v0.1.0-beta.16.1] mdarea not detecting text modifications

### ISSUE THREAD

**Issue by PeopleInside** [flarum/core#2746]
## Bug Report

**Current Behavior**

https://discuss.flarum.org/d/26673-issue-with-editor-on-beta-16/4

**Steps to Reproduce**
1. Go to https://beta.flarum.site/ should be Beta 16
2. Be sure on Markdown, mdarea is active
3. create a post
4. reply to the post write some casual words than select one of this word and press the B (bold) button in the editor. Without press any space the preview will not show the text in bold, also if you post the post the bold "directive" is lost.

![SharedScreenshot](https://user-images.githubusercontent.com/5006150/113408102-02c5a800-93af-11eb-84ad-e9d268cc8811.jpg)

![](https://i.postimg.cc/Kc7y3KCK/fla16.gif)

**Expected Behavior**

Preview should be updated and the bold text should be not lost if no space bar is pressed

**Comment by ayyilmaz** [comment]
Currently, we have to press another button to activate changing its view.

**Comment by PeopleInside** [comment]
I'm loosing text and code because of this issue.
I past some code than save the post and loose the right code.

Can be this issue be prioritized?

Also if i disable mdarea I get other issues like cannot undone things, etc

**Comment by PeopleInside** [comment]
Thank you for fixing this @askvortsov1 now I have to wait for Flarum update or can I do something for include this fix? I disabled mdata due to issues and wanna resume it.
