### ISSUE TITLE
Changing avatar

### ISSUE THREAD

**Issue by BChuss** [flarum/core#275]
It's impossible to change avatar on the beta version of Flarum. When I do it, it is written  Oops! Something went wrong on the server. Please reload the page and try again.

**Comment by jwdeitch** [comment]
I think I found the issue -> I'll submit a PR if so

**Comment by kavonatsalv** [comment]
I'm getting the same error message. Everything else seems to be a-ok!

**Comment by tobscure** [comment]
Try installing the Imagick PHP extension if possible. Flarum is incorrectly using this by default instead of gd – see d5074c52862972ff0454be88f15f0bf83bdf203f.

Also double-check the permissions on the assets/avatars directory.

**Comment by jwdeitch** [comment]
ImageMagick appears to be the issue - I was going to submit an update the install guide

**Comment by tobscure** [comment]
We'll release beta 2 early next week including this patch and others :)
