### ISSUE TITLE
All posts appear under any tag

### ISSUE THREAD

**Issue by kafuuchino-desu** [flarum/core#2752]
## Bug Report

**Current Behavior**
Once I set the forum homepage to tags, if a user clicks any tag categories and all existing posts will appear under this tag no matter if the post contains that specific tag, and refreshing the page will solve this problem.

**Steps to Reproduce**
1. Set the forum homepage to tags
2. open the forum in a new tab
3. click any tag
4. all existing posts should appear

**Expected Behavior**
only the posts containing this tag should appear

**Screenshots**
![image](https://user-images.githubusercontent.com/33673786/113508596-8c2dd380-9583-11eb-9329-c23c071fc0bd.png)

**Environment**
- Flarum version: 0.1.0-beta.16
- Website URL: https://sakuranomiya.moe/
- Webserver: nginx
- Hosting environment: docker (https://github.com/crazy-max/docker-flarum)
- PHP version: 7.3.27
- Browser: both chrome and edge can reproduce this bug

```
Output of "php flarum info":
Flarum core 0.1.0-beta.16
PHP version: 7.3.27
Loaded extensions: Core, date, libxml, pcre, zlib, filter, hash, readline, Reflection, SPL, session, ctype, curl, dom, fileinfo, gd, gmp, iconv, intl, json, mbstring, openssl, PDO, standard, SimpleXML, sodium, tokenizer, xml, xmlwriter, zip, exif, mysqlnd, Phar, pdo_mysql, uuid, Zend OPcache
+---------------------------------+------------------+--------+
| Flarum Extensions               |                  |        |
+---------------------------------+------------------+--------+
| ID                              | Version          | Commit |
+---------------------------------+------------------+--------+
| flarum-flags                    | v0.1.0-beta.16   |        |
| flarum-approval                 | v0.1.0-beta.16   |        |
| flarum-likes                    | v0.1.0-beta.16   |        |
| flarum-tags                     | v0.1.0-beta.16   |        |
| flarum-lock                     | v0.1.0-beta.16   |        |
| flarum-subscriptions            | v0.1.0-beta.16   |        |
| flarum-emoji                    | v0.1.0-beta.16   |        |
| flarum-sticky                   | v0.1.0-beta.16   |        |
| michaelbelgium-discussion-views | v6.0.0           |        |
| fof-drafts                      | 0.4.0            |        |
| clarkwinkelmann-bookmarks       | 0.1.3            |        |
| fof-socialprofile               | 0.3.0            |        |
| fof-user-directory              | 0.6.0            |        |
| fof-recaptcha                   | 0.3.1            |        |
| glowingblue-composer-preview    | 0.2.0            |        |
| fof-username-request            | 0.5.0            |        |
| flarum-bbcode                   | v0.1.0-beta.16   |        |
| fof-best-answer                 | 0.4.0            |        |
| clarkwinkelmann-circle-groups   | 0.2.4            |        |
| fof-formatting                  | 0.4.0            |        |
| lcinhk-acgembed                 | v0.5.2           |        |
| fof-user-bio                    | 0.5.0            |        |
| fof-spamblock                   | 0.5.0            |        |
| fof-reactions                   | 0.6.0            |        |
| fof-polls                       | 0.3.2            |        |
| fof-merge-discussions           | 0.5.1            |        |
| fof-nightmode                   | 0.8.0            |        |
| flarum-suspend                  | v0.1.0-beta.16   |        |
| flarum-statistics               | v0.1.0-beta.16   |        |
| flarum-mentions                 | v0.1.0-beta.16   |        |
| fof-default-group               | 0.4.0            |        |
| fof-moderator-notes             | 0.5.0            |        |
| fof-ignore-users                | 0.3.1            |        |
| nearata-copy-code-to-clipboard  | v1.3.0           |        |
| fof-profile-image-crop          | 0.3.0            |        |
| fof-subscribed                  | 0.5.0            |        |
| fof-filter                      | 0.3.2            |        |
| clarkwinkelmann-likes-received  | 0.1.2            |        |
| fof-impersonate                 | 0.8.0            |        |
| therealsujitk-show-password     | v2.0.0           |        |
| flarum-markdown                 | v0.1.0-beta.16.1 |        |
| v17development-blog             | v0.3.0           |        |
| fof-follow-tags                 | 0.7.2            |        |
| itnt-uitab                      | v0.3.2           |        |
| fof-links                       | 0.6.0            |        |
| flarum-lang-english             | v0.1.0-beta.16   |        |
| jjandxa-chinese-search          | 0.0.11           |        |
+---------------------------------+------------------+--------+
Base URL: https://sakuranomiya.moe
Installation path: /opt/flarum
Debug mode: off
```

**Additional Context**
I'm also using a CDN for the forum, and idk if this is possibly related to the bug

**Comment by askvortsov1** [comment]
Investigated, this happens because in beta 16, https://github.com/flarum/core/blob/eac7d1b7ade79f0d4ee3b44b210bc09005491316/src/Forum/Content/Index.php#L23-L23 is used even if a different home page is set. So, a preloaded api document is available, which breaks everything.

So https://github.com/flarum/core/blob/eac7d1b7ade79f0d4ee3b44b210bc09005491316/src/Forum/ForumServiceProvider.php#L202-L202 is malfunctioning. The malfunction happens because $routeCollection->getRoutes() are now indexed by route name, whereas previously they were indexed by path.

I propose 2 adjustments:

- The `setDefaultRoute` in `ForumServiceProvider` needs to be fixed. IMO, we should just create a dispatcher and resolve via FastRoute, as done in https://github.com/flarum/core/blob/eac7d1b7ade79f0d4ee3b44b210bc09005491316/src/Http/Middleware/ResolveRoute.php#L54-L54. This would even increase flexibility, allowing to preload an API document for 
- After the first route switch, we should clear the preloaded API document. We could do this by getting the intial path during boot, and if it's changed since then, returning null.

**Comment by kafuuchino-desu** [comment]
I have patched my forum using the commits above, it's working perfectly and I haven't noticed any obivious bugs yet, thx <3

**Comment by looxii** [comment]
> I have patched my forum using the commits above, it's working perfectly and I haven't noticed any obivious bugs yet, thx <3

how to patch ?

**Comment by looxii** [comment]
> > > I have patched my forum using the commits above, it's working perfectly and I haven't noticed any obivious bugs yet, thx <3
> > 
> > 
> > how to patch ?
> 
> We strongly recommend not doing this unless you know what you're doing. But the gist would be creating a fork, making a branch from the beta 16 tag with the commits you want, and installing that branch instead of the packagist published beta 16.

thx

**Comment by luceos** [comment]
@flarum/qa please add this to the qa checklist for confirmation on new releases.
