### ISSUE TITLE
Ctrl/Cmd + Enter to send comment

### ISSUE THREAD

**Issue by lkhrs** [flarum/core#276]
Can we have Ctrl/Cmd + Enter bound to send a comment? I love doing that to send an email in Gmail, and I think it would be really cool on Flarum.

**Comment by jwdeitch** [comment]
I am able to submit comments using the cmd + enter keys on a mac

**Comment by tobscure** [comment]
Should be an easy fix in js/forum/components/TextEditor's configTextarea method (we're using jQuery hotkeys)

**Comment by franzliedke** [comment]
This seems to be already implemented. I can make replies with (on Windows) Win+Enter. Should this be another combination? Ctrl+Enter seems to be the one used in Gmail.

**Comment by tobscure** [comment]
I think both Cmd/Win and Ctrl should work, yes?

**Comment by zaboca** [comment]
I think traditionally Ctrl+Enter on Windows is the preferred route. So yes, Ctrl+Enter should be added.

**Comment by franzliedke** [comment]
Implemented both now. :)

**Comment by lkhrs** [comment]
@franzliedke  Awesome!
