### ISSUE TITLE
Incorrect username in email subject for mentions

### ISSUE THREAD

**Issue by lhunath** [flarum/core#2767]
## Bug Report

**Current Behavior**
When a user replies to a post by mentioning the original user/post, an email is sent out to the original post user. This email contains the wrong user name in the subject line.

**Steps to Reproduce**
1. Turn on `Mentions`
2. User X replies to user Y's post
3. User Y receives email
4. Subject says `Y replied to your post in ...`, although X was the one who replied and Y is the recipient.

**Expected Behavior**
`X replied to your post in ...`

**Screenshots**
<img width="882" alt="image" src="https://user-images.githubusercontent.com/36948/113716857-ff853180-96b8-11eb-99e1-bb7339bc51ec.png">

**Environment**
- Flarum version: 0.1.0-beta.15
- Website URL: https://chat.spectre.app
- Hosting environment: Free Flarum
- Browser: Firefox 87

**Possible Solution**
Not sure – the code seems to say:
```
subject: "{replier_display_name} replied to your post in {title}"
```
Which appears to be correct.

**Additional Context**
Interestingly, the body text of the mail correctly says: `X replied to your post in ...`
Although the body references the same variable:
```
      body: |
        Hey {recipient_display_name}!
        {replier_display_name} replied to your post (#{post_number}) in {title}.
        {url}
        ---
        {content}
```
Maybe I'm looking at the wrong code.

**Comment by askvortsov1** [comment]
Thank you for the report! This is a known bug, and was fixed for beta 16.
