### ISSUE TITLE
Custom Group Name is Wrong: core.group_xxx

### ISSUE THREAD

**Issue by thecodingwizard** [flarum/core#277]
If I create a new group and assign it to someone, when I hover over the tag it will say core.group_xxx instead of XXX.

**Comment by Felli** [comment]
This is might be because of the group not being apart of the core itself.

**Comment by tobscure** [comment]
Seems to be bug in js/lib/Translator's trans method incorrectly not using the fallback? Either that or the fallback in not passed correctly when the badges are constructed in js/models/User.

The Translator would be a great example of something that we should definitely be unit testing :D
