### ISSUE TITLE
[Dev CLI] Always installs npm dependencies even when choosing no

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#2779]
## Bug Report

**Current Behavior**
When using the Flarum Dev CLI, choosing

Run `composer install`? (recommended): yes
Run `npm install`? (recommended): no

Still runs `npm install`

**Steps to Reproduce**

Tested by running `npx flarum-cli init` and filling options as described.

**Expected Behavior**
npm install should not be executed.

**Environment**
- Flarum version: beta 16

**Possible Solution**
Problem is here. Wrong variable is checked.

https://github.com/flarum/flarum-cli/blob/8d98cc91895f0e900cb4ae932683c33e96bc2249/src/commands/init.ts#L207-L211

**Comment by askvortsov1** [comment]
Fixed in https://github.com/flarum/flarum-cli/commit/638cd2ac205290c8865f684a4e6d9df73d7c6b4c
