### ISSUE TITLE
Session bound to User object creates Queueing issues

### ISSUE THREAD

**Issue by luceos** [flarum/core#2784]
## Bug Report

**Current Behavior**

We are setting the session of the user on the User object. When serializing happens - for instance the Notification dispatches - the User object is serialized. Now whenever you are using a Session driver that is not serializable (like Redis) queue handling will fail.

**Possible Solution**

- Bind the solution to ioc (isn't that the case) and remove from the User object.
- Override the `__serialize` method on the User class to drop the session property.

**Comment by askvortsov1** [comment]
Do we need the session to be serialized with the user? Any use cases for accessing it from within the queue?

> Bind the solution to ioc (isn't that the case)

No per-request state in IoC!!! :angry:
