### ISSUE TITLE
How to reload Views (LESS, HTML,...)

### ISSUE THREAD

**Issue by huytd** [flarum/core#279]
Hi all!

Anybody know how to reload the Views when we already deployed Flarum?
For example, I want to do some modification in the LESS/CSS, without do it in `Administrator`.

I know our Views are stored in `storage` folder. Should we delete all the files in `storage`'s sub-folders to make it rebuild?

Thanks

**Comment by tobscure** [comment]
Deleting the CSS files in the assets directory will force a rebuild.

For future reference, questions like this are probably better suited to the Dev tag on our [support forum](http://discuss.flarum.org) :)

**Comment by huytd** [comment]
:+1:
