### ISSUE TITLE
Logging in without activating account shows "login details are incorrect" error

### ISSUE THREAD

**Issue by ralphskie** [flarum/core#280]
1. [SIGN UP] There is no prompt or message for the user that the email is existing on the DB.

![2015-08-28 11_17_30-developer tools - http___localhost_flarum-0 1 0-beta_](https://cloud.githubusercontent.com/assets/5318148/9538413/b873e3ea-4d76-11e5-8df4-b53dfdffcac9.jpg)

2. [LOGIN] - when logging in without first activating your account. The system shows this error  "Youre login details are incorrect", must be "Please activate you account first"?or something else

**Comment by tobscure** [comment]
See #267, #193, and #118 re: the signup issue.

Will look into the login one.

**Comment by tobscure** [comment]
Pretty sure this is fixed in dev-master. Unactivated users are allowed to log in, but they still only have the permissions of a guest. I've yet to add an info message like "you need to confirm your email" with a "resend" button... #709
