### ISSUE TITLE
[Theme extender] Ability to override core `LESS` files

### ISSUE THREAD

**Issue by SychO9** [flarum/core#2817]
When designing a flarum theme, any Less/CSS code you write needs to override any default styles present in core, that means you constantly have to over-specify elements, using `!important` also becomes necessary at times. An optimal solution would be to be able to tell the software: here is a (for example) DiscussionListItem.less file that overrides the default, the software would then not load the default and instead load the custom one.

There might be something that allows us to hook into the import process of Less files, [an `import_callback` option](https://github.com/wikimedia/less.php/blob/ae9a875fb549a35780d10edcf3936163342d59d2/lib/Less/Tree/Import.php#L151-L153), we'd have to pass that to the `Less_Parser` object instantiation [here](https://github.com/flarum/core/blob/9e3699ea4725abca32012a336b633de7771a310f/src/Frontend/Compiler/LessCompiler.php#L70-L74).

This should be a method within a `Theme` extender.

**Comment by iamdarkle** [comment]
@SychO9 I know it's a bit off topic, but until this is implemented is there a way to overwrite without constantly abusing `!important`?

**Comment by SychO9** [comment]
Well, you either overspecify, or use the important rule, or both, that's really all you can do.
