### ISSUE TITLE
`Less` Configuration Variables

### ISSUE THREAD

**Issue by SychO9** [flarum/core#2819]
There are times where I wanted to add a setting which I needed to use in `Less` code similarly to how the primary color is used. It would be great to have:

1. The ability to add a `Less` configuration variable through an extender (Theme extender makes sense).
2. The ability to make it so that a setting that is changed clears the cache, at least the CSS cached assets, and this is for 1 where a configuration value is likely to be a setting the admin can edit, in which case a new set of CSS files need to be compiled with the new value. Right now configuration values such as primary color trigger a cache clear because the setting name starts with `theme_` which I used as a around before for my own settings, but I think it'd be best to improve this and make it a system. (Theme extender also makes sense atm).

**Comment by davwheat** [comment]
> 1. The ability to add a `Less` configuration variable through an extender (Theme extender makes sense).

Can this not be done by just adding a Less variable to the root of a file which is then loaded in the `extend.php` file?

**Comment by SychO9** [comment]
> Can this not be done by just adding a Less variable to the root of a file which is then loaded in the `extend.php` file?

How so exactly ? I'm referring to configuration variables, similar to the primary color which is editable through the admin panel.

**Comment by davwheat** [comment]
Oh! I misunderstood. Ignore me :P

**Comment by justoverclockl** [comment]
I think that will improve extension development for user bad like me 😅

**Comment by askvortsov1** [comment]
Looks like Dem13n has come up with an extender for this on their own! https://github.com/Dem13n/discussion-cards/blob/master/src/Extenders/RegisterLessVariables.php

In the long term, it would probably be a bit more stable for the official extender to use https://github.com/flarum/core/blob/a78cbf644c85cc73852555ed97271328d9a6a2e8/src/Frontend/FrontendServiceProvider.php#L83-L83 directly, to avoid code duplication
