### ISSUE TITLE
User list

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#283]
We want to offer an extensible user list which displays users sorted by metrics (no. of posts/discussions in core, and could be extended to show no. of likes received, etc.)

What needs to be done:
- Decide if this should be part of core, or should be a default extension. (i.e. should we allow it to be disabled?)
- Design it.
- Implementation needs to be nutted out

**Comment by huytd** [comment]
This is for the Administation Dashboard or for the Front-End where all members could see the User list?
In my opinion, we also need the User management for Administration Dashboard, so it should be in the `core`
And a new extension for displaying User list on front-end since not everyone required this feature.

**Comment by moutonnoireu** [comment]
It should be part of flarum, core or default extension is a false debate, it just have to exist, one way or another.

**Comment by cbmainz** [comment]
+1
Yes, it would be very helpful to have a user management for Administration Dashboard.

**Comment by axadr** [comment]
Aministrator needs to know who are signed up into a forum. Simple list of users should be part of core.

**Comment by warpdesign** [comment]
+1
Should be there in admin.

I think there should be a way to manually confirm people's email too.

**Comment by dcsjapan** [comment]
Why not make it available in the user interface, but with added functionality for admins?

- Whether non-admin, non-mod users can see this page would be handled by permissions.
- Admin controls would be displayed in a manner similar to the controls displayed on profiles.
- I agree, one of those controls could be manual confirmation of email.

**Comment by jordanjay29** [comment]
I definitely think it's as useful on the user side as the admin side. The userlist could benefit from various filters, and Awaiting Email Confirmation could be one of them for those with admin permissions.

**Comment by cherryade** [comment]
+1 This should be a core feature.

**Comment by HLFH** [comment]
It seems it's available as a plugin: https://discuss.flarum.org/d/1540-hyn-guardian-user-security-listing-in-the-admin

**Comment by Mecvak** [comment]
-1
This should be a extension.
Core should permit a api to easily access the user list and interact with it (suspend, delete, etc) but the interface to interact with it should be a extension.
This is less about whether you'd ever want to disable it rather then would you ever want to have the option to use a alternate extension to do the same thing.

**Comment by tobscure** [comment]
Relevant discussion here: https://discuss.flarum.org/d/1540-flagrow-guardian-an-additional-security-layer/41

**Comment by wion** [comment]
How does an admin make a user a moderator, for example? I don't see this ability anywhere, or am I missing it? It doesn't make any sense to suggest a "moderator" group in Permissions but not be able to create any moderators. This is a basic and essential feature for any forum. So, definitely some basic roles management in the administration area is critical. And it would logically be tied with groups too, since you're already allowing creation of groups.

**Comment by franzliedke** [comment]
@wion That's already possible. Just go to a user's profile, click on "Controls" and then "Edit": there you can assign them to existing groups.

**Comment by wion** [comment]
Hmm... I don't see where to find the user's profile. At the moment it's just me as admin, and me as another account. Neither account has posted any threads yet. When logged in as admin, I don't see any way to access the profile of my other account. But maybe that's because the account hasn't made a post yet? Is that how you would normally find a profile? I would expect there to be a members list or something. No?

**Comment by franzliedke** [comment]
Yeah, that's all coming. You're right, you can access a user's profile via posts (or via the URL directly).

**Comment by wion** [comment]
Okay, I see. Thanks for the info.

**Comment by tobscure** [comment]
or via the search box, if you type the first few characters of their name

**Comment by vijeetgv** [comment]
@tobscure that from searchbox isn't case sensitive yet, I guess you'd want to add that. :)

**Comment by tobscure** [comment]
@vijeetgv Isn't it? Case-insensitivity seems to be working for me... can you provide steps to reproduce?

**Comment by vijeetgv** [comment]
@tobscure if a username is in total lowercase for example: http://prntscr.com/b5csdu it doesn't find.

And if I make it all-lower case, it works: http://prntscr.com/b5csk6

**Comment by vijeetgv** [comment]
@tobscure Also do you have a feature request for showing full names or screen names (which maybe different from username & may have spaces & dot(.) in them)?

**Comment by tobscure** [comment]
@vijeetgv ah, I see. Thanks, will get that fixed. #961

**Comment by vijeetgv** [comment]
@tobscure  no probs.

**Comment by dcsjapan** [comment]
@vijeetgv See this issue for screen names: https://github.com/flarum/core/issues/557

**Comment by RockFridrich** [comment]
+1

**Comment by rwalkos** [comment]
It is imperative for admin area to have users and e-mail with ability to sort by join date and possibly confirmed or not. I would think it should be a part of core.

As for the front end I think it needs to be very customizable. Such as visibility for different groups like guest, member, mod, admin etc. Would also be nice to be able to show post counts likes etc. but also have that customizable. So for the front end, possibly an extension that can be changed or added to easily. With it being an extension it could always be added later.

**Comment by Pilvinen** [comment]
Definitely should part of the core. I'm surprised that it isn't there already.

**Comment by buiductuan182** [comment]
Aministrator needs to know who are signed up into a forum. Simple list of users should be a part of core. Core has to be enough functional without extensions.
ex: https://www.quangminhhanoi.com/dieu-hoa-lg

**Comment by edgimar** [comment]
when a user's group membership is changed, maybe there should be a "notify user of changes" checkbox next to "save" -- or this functionality can be enabled/customized elsewhere, but it seems like an important feature for the use-case of having a "new user" group where users wait in after signing up until they are validated as regular users.

**Comment by franzliedke** [comment]
@edgimar I love that idea.

To be honest, it is probably too far off inclusion in core at this time, thus it would be a perfect use-case for an extension IMO.

**Comment by alarobric** [comment]
I've implemented a site where new users need to be "confirmed" to view more than a basic welcome post, i.e. added to a user group. The management of users and adding them to groups leaves a lot to be desired right now, even the various user list extensions don't make this any easier.
+1 for this.

**Comment by despecial** [comment]
any news on the current plans for a user management in the admin interface?

**Comment by rob006** [comment]
Bump.
