### ISSUE TITLE
[Mentions] nightly.flarum.site : the mentions menu (in Profile) is full of non mention-related posts 

### ISSUE THREAD

**Issue by Ornanovitch** [flarum/core#2833]
## Bug Report

**Steps to Reproduce**
1. Go to https://nightly.flarum.site and sign in (my test is with an admin account)
2. Go to your Profile's mentions index (`https://nightly.flarum.site/u/{ user }/mentions`)
4. See all the posts as if it was the full discussion list page

**Expected Behavior**
Should only display the posts where I am mentioned (in my case, none)

**Environment**
- Flarum version: nightly

**Comment by davwheat** [comment]
Can reproduce locally.

**Comment by askvortsov1** [comment]
Looks like we forgot to update the ConfigurePostQuery event to a listener. Should be an easy fix, I'll open a PR.
