### ISSUE TITLE
Falsey params passed to `Translator.trans` are ignored in the output

### ISSUE THREAD

**Issue by davwheat** [flarum/core#2839]
## Bug Report

**Current Behavior**
Passing a falsey value to `app.translator.trans`, such as `0` or `"0"` causes it to be ignored in the translator output.

See https://github.com/SychO9/flarum-github-milestone/issues/6 for an example

**Expected Behavior**
It should be output as part of the string.

**Screenshots**
![image](https://user-images.githubusercontent.com/7406822/117217947-2f2f7280-adfa-11eb-9784-b7acbc79ff99.png)

**Environment**
- Flarum version: 0.1.0-beta.16
- Website URL: https://discuss.flarum.com

**Comment by davwheat** [comment]
Fixed between beta 16 and 1.0, likely when we switched to @askvortsov1's formatter. 🎉

**Comment by askvortsov1** [comment]
Credit goes to @ultraq for creating a formatter that doesn't take up 100kb! :partying_face:
