### ISSUE TITLE
Not working with Webpack v5.24

### ISSUE THREAD

**Issue by rafaucau** [flarum/core#2855]
I have been using Webpack `5.21` so far, but after updating the dependencies using `npm update` my extensions stopped working. There are no build errors.
When the webpack version is `5.24.2`, then this error occurs in the browser console after build:
![image](https://user-images.githubusercontent.com/25438601/109205919-89cba300-77a7-11eb-962c-dc21bca7d9a2.png)
![image](https://user-images.githubusercontent.com/25438601/109205958-93550b00-77a7-11eb-82fe-5c8d6aebb324.png)
The error points to a random extension.

I have `npm v7.5.6` and `node.js v14.16.0`

Rollback to Webpack v5.21 helps.

**Comment by davwheat** [comment]
This should be fixed by #2845
