### ISSUE TITLE
Keyboard typing in Mobile UI on Android broken

### ISSUE THREAD

**Issue by tobiaslangner** [flarum/core#2868]
## Bug Report

**Current Behavior**
The Android Keyboard does not work as usual when typing in the "new post" dialog in flarum. Autocorrect does not work and on top of that, key presses are frequently lost. It seems that some process is regularly refreshing the text box (input validation?) which messes with the input.

**Steps to Reproduce**
Attempt to write a new post or reply to an existing one in Chrome on Android. See the attached video. I tried with Chrome, Brave, both also with incognito tab.

**Expected Behavior**
The keyboard works like in other apps and I can just normally enter text using autocorrect.

**Screenshots**
https://user-images.githubusercontent.com/6542746/118352700-0da15a00-b563-11eb-963a-afc2477c70f7.mp4

**Environment**
- Flarum version: 0.1.0-beta.16
- Website URL: https://guggach.bitvalve.org
- Webserver: nginx
- Hosting environment: docker (image: mondiefr/flarum)
- PHP version: 8.0.2
- Browser: Brave 1.24.84, Chrome 90.0.4430.210

```
# php flarum info
Flarum core 0.1.0-beta.16
PHP version: 8.0.2
Loaded extensions: Core, date, libxml, pcre, zlib, filter, hash, json, readline, Reflection, SPL, session, ctype, curl, dom, fileinfo, gd, gmp, iconv, intl, mbstring, openssl, PDO, standard, tokenizer, xmlwriter, zip, exif, mysqlnd, Phar, pdo_mysql, apcu, Zend OPcache
+----------------------+----------------+--------+
| Flarum Extensions    |                |        |
+----------------------+----------------+--------+
| ID                   | Version        | Commit |
+----------------------+----------------+--------+
| flarum-flags         | v0.1.0-beta.16 |        |
| nearata-lang-italian | v0.1.0-beta.16 |        |
| qiaeru-lang-french   | v1.10.0        |        |
| fof-upload           | 0.14.0         |        |
| flarum-approval      | v0.1.0-beta.16 |        |
| flarum-bbcode        | v0.1.0-beta.16 |        |
| flarum-emoji         | v0.1.0-beta.16 |        |
| flarum-lang-english  | v0.1.0-beta.16 |        |
| flarum-likes         | v0.1.0-beta.16 |        |
| flarum-lock          | v0.1.0-beta.16 |        |
| flarum-markdown      | v0.1.0-beta.16 |        |
| flarum-mentions      | v0.1.0-beta.16 |        |
| flarum-statistics    | v0.1.0-beta.16 |        |
| flarum-sticky        | v0.1.0-beta.16 |        |
| flarum-subscriptions | v0.1.0-beta.16 |        |
| flarum-suspend       | v0.1.0-beta.16 |        |
| flarum-tags          | v0.1.0-beta.16 |        |
| fof-byobu            | 0.6.1          |        |
| fof-user-directory   | 0.6.1          |        |
| kakifrucht-de        | 0.14.3         |        |
+----------------------+----------------+--------+
Base URL: https://guggach.bitvalve.org
Installation path: /flarum/app
Debug mode: off
```

**Comment by matteocontrini** [comment]
This should be fixed in the upcoming 1.0 version, you can temporarily work around the issue by disabling `mdarea` in the Markdown extension settings.

**Comment by tobiaslangner** [comment]
Thanks for the response. Indeed I am using Gboard...

Would you mind letting me know where I can disable mdarea? The settings section for the Markdown plugin in the Administration section of Flarum tells me that the extension has no settings.

**Comment by davwheat** [comment]
You might need to update the markdown extension to version 0.1.0-beta.16.1 to see the option.

**Comment by tobiaslangner** [comment]
Thanks, this worked.
