### ISSUE TITLE
[Flags] Clicking "Delete", then "Cancel" dismisses flag.

### ISSUE THREAD

**Issue by davwheat** [flarum/core#2872]
## Bug Report

https://user-images.githubusercontent.com/7406822/118419089-efe30a80-b6b2-11eb-8016-216cdab5582b.mp4

**Comment by askvortsov1** [comment]
Duplicate of https://github.com/flarum/core/issues/2765

**Comment by davwheat** [comment]
Oops! Looks like this happens without approvals, so I'll add that to the bug report there.
