### ISSUE TITLE
[Mentions] Mention autocomplete doesn't remove initial search

### ISSUE THREAD

**Issue by davwheat** [flarum/core#2878]
When using Firefox, using the mention autocomplete, the original 'search' isn't removed when inserting the autocompleted mention.

1. Use firefox
2. Start typing a mention `e.g. "@use"
3. Press TAB to accept the suggestion
4. End up with `@use@"user"#123` (or similar)

**Comment by Ornanovitch** [comment]
I had the same behavior yesterday on nightly but I can't reproduce it anymore since the today's update

**Comment by SychO9** [comment]
Several people have tested and confirmed this no longer occurs, we're not sure of the reason though.

**Comment by askvortsov1** [comment]
Might be https://github.com/flarum/core/commit/9ee3cd6a187c036490717ce227a4ca0bb162ccbe?

**Comment by SychO9** [comment]
Could be, though I did reproduce it in nightly a few days after that commit, unless nightly isn't actually updating nightly.

**Comment by askvortsov1** [comment]
> Could be, though I did reproduce it in nightly a few days after that commit, unless nightly isn't actually updating nightly.

It wasn't because fake data wasn't updated yet.
