### ISSUE TITLE
Reserved Column Names in Tables

### ISSUE THREAD

**Issue by geoclicks** [flarum/core#288]
Hi there,

Noticed that the config table has two columns, 'key' and 'value'. Can these be changed in the released software? They're reserved keywords.

The following statement fails from the mysql cli.

update config set value='/tags' where key='default_route';

Needs to be changed to 

update config set config.value='/tags' where config.key='default_route';

Have not looked at the other tables, there may be more. 

Reserved words can be found here: https://dev.mysql.com/doc/refman/5.0/en/keywords.html

**Comment by tobscure** [comment]
Just wrap the column names with backticks (`). e.g.

```
update config set `value`='/tags' where `key`='default_route';
``` 

@franzliedke do you think this is worth changing? I don't think I have a problem with using reserved keywords for column names.

**Comment by franzliedke** [comment]
Given that we sometimes use raw database expressions (where Laravel's automatic backtick escaping cannot help us), I'd be in favor of another name, but only if we find a good alternative. In FluxBB, we had "conf_key" and "conf_value" but that's unnecessarily awkward (though probably done so for the same reason).

I don't think it's important enough, to be honest, if we don't find an equally to-the-point alternative.

**Comment by tobscure** [comment]
It's not hard to manually use backticks in raw queries though. And I can't see us using raw expressions to interact with the config table, anyway?

But yeah, I'm not gonna spend any time brainstorming, but happy to consider any suggestions from others :)

**Comment by franzliedke** [comment]
Agreed, it should be fine. :)
