### ISSUE TITLE
Request support for CJK user names! 

### ISSUE THREAD

**Issue by StarsRivers** [flarum/core#2881]
At_/src/User/UserValidator.php_
Change the contents of line 47 to `'regex:/^[-_a-zA-Z0-9\x7f-\xff]*[-_a-zA-Z\x7f-\xff][-_a-zA-Z0-9\x7f-\xff]*$/i',
`
Then 
At_/src/Forum/Auth/Registration.php_
Comment out 101 lines like this`// $username = preg_replace('/[^a-z0-9-_]/i', '', $username);`
At_/src/Api/Controller/ShowUserController.php_
Changing `$id` to`urldecode($id)`
(Is there any other way not to use urlcode? )
Known Issue: Cannot  @ sb.
Opinion :Change /vendor/flarum/mentions/src/ConfigureMentions.php

**Comment by luceos** [comment]
v1.0 offers fully flexible mentions using the Display Name; although there's no UTF8 based display name driver it can be developed now.

**Comment by SychO9** [comment]
`flarum/nicknames` is UTF8 friendly for display names.
