### ISSUE TITLE
Avatar upload fails with large file sizes

### ISSUE THREAD

**Issue by datitisev** [flarum/core#2888]
## Bug Report

**Current Behavior**
When uploading a large file, the form data isn't sent (at least not properly? different browsers show different things) and the server returns with 
> POST https://flarum-new.localhost/api/users/1/avatar 422
> The :attribute field is required.

**Steps to Reproduce**
1. Go to user profile
2. Upload a large image (I used https://images.pexels.com/photos/842711/pexels-photo-842711.jpeg?cs=srgb&dl=pexels-christian-heitz-842711.jpg&fm=jpg)

**Expected Behavior**
No error.

**Screenshots**
<details>
<summary>Large Image</summary>

![image](https://user-images.githubusercontent.com/6401250/119582240-3e1e9a80-bd92-11eb-97b5-4bd824fb0c49.png)

Chromium browsers do seem to show the request data, but the error still occurs.
![image](https://user-images.githubusercontent.com/6401250/119582300-57274b80-bd92-11eb-85e0-0f173708b23b.png)

</details>

<details>
<summary>Small Image</summary>

![image](https://user-images.githubusercontent.com/6401250/119582448-88a01700-bd92-11eb-82a6-149c2d8962de.png)

Chromium shows the same thing.
![image](https://user-images.githubusercontent.com/6401250/119582490-9b1a5080-bd92-11eb-916e-54109c661ccf.png)

</details>

**Additional Context**
I found this while trying to debug why `fof/profile-image-crop` failed with large images. I don't know if this is a limitation of FormData or an issue with Mithril request or our code...

> I found the issue with profile-image-crop and large images.
It's not a problem with the ext but with core. The actual error escapes me.
Looking at the request, the FormData isn't passed for large file sizes (both with ext enabled & disabled) - and I cannot figure out why.
i tested this by adding my own data to FormData in core for image upload, and using an image that fails with both ext enabled & disabled
the reason it sometimes fails with it enabled but not disabled is because the resize/crop sometimes makes the image bigger

**Comment by matteocontrini** [comment]
@datitisev indeed there's no error handling when retrieving the uploaded image:

https://github.com/flarum/core/blob/a976a2118a98dffa174e97f35ce239e03bea180f/src/Api/Controller/UploadImageController.php#L67

What I'm doing in an extension of mine is:

```php
if ($file->getError() != UPLOAD_ERR_OK) {
     // Handle error
}
```

Possible errors are documented [here](https://www.php.net/manual/en/features.file-upload.errors.php), among which there's `UPLOAD_ERR_INI_SIZE`.

**Comment by tankerkiller125** [comment]
While that might fix the PHP Max image size there is no way to catch when Nginx or Apache errors out on max upload sizes. So I think some proper front-end error catching language might also help here for when that happens.
