### ISSUE TITLE
[Tags] on event posts, tags editions aren't rendering correctly

### ISSUE THREAD

**Issue by Ornanovitch** [flarum/core#2889]
## Bug Report

**Current Behavior**
When you edit tags of a discussion, the generated `EventPost` renders a wrong message about what tag has been removed and what tag has been added. It renders `added the 1 tag and removed the 1 tag` whatever you do.

**Steps to Reproduce**
1. Edit a discussion's tags 
1. Read the `EventPost`

**Expected Behavior**
The `EventPost` should say something like `added the [tag name] tag and/or removed the [tag name] tag`

**Screenshots**
![Screenshot_2021-05-27 haha - Flarum nightly](https://user-images.githubusercontent.com/34077099/119738614-41448400-be81-11eb-9847-3c5f3a941723.png)

**Environment**
- Nightly

**Possible Solution**
Maybe related to https://github.com/flarum/tags/commit/3694f2cdb8823bac01bbd0c70199fe4d81e4bd7f ?

**Comment by luceos** [comment]
Thanks for the report, I've added a check to our QA checklist and fixed it ahead of the release 😓

**Comment by Ornanovitch** [comment]
Wow, bullet speed resolving :1st_place_medal:
