### ISSUE TITLE
[Tags] Error on saving new tag

### ISSUE THREAD

**Issue by bgies** [flarum/core#289]
When saving you get this error :
SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'is_hidden' at row 1 (SQL: insert into tags (name, slug, description, color, is_hidden) values (Website, website, Feature requests, bug reports, , )) 

Checking and unchecking the "Hide from all discussions" fixes it, so I would assume that it just needs a default set in Mithril when the form opens

**Comment by johannsa** [comment]
Same here
