### ISSUE TITLE
Admin permissions grid on load only shows 4 tags

### ISSUE THREAD

**Issue by likuilin** [flarum/core#2891]
## Bug Report

**Current Behavior**
The Permissions grid in admin only shows 4 tags, unless the Tags page is loaded first. 

**Steps to Reproduce**
1. Install Flarum 1.0.0
2. Create more than 4 secondary tags
3. Go to /admin#/permissions
4. Reload the page
5. See that only 4 tags are in the grid header

**Expected Behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/16179637/120088207-05ddcb80-c0b4-11eb-9851-8362030ca3bd.png)

Note that only 4 tags appear, and the "+ Restrict by tag" does not appear. After navigating to the Tabs page and back: 

![image](https://user-images.githubusercontent.com/16179637/120088224-23129a00-c0b4-11eb-8a85-e336520c0539.png)

**Environment**
- Flarum version: 1.0.0
- Website URL: Private
- Webserver: nginx
- Hosting environment: Docker
- PHP version: 8.0.6
- Browser: Chrome 90

```
Output of "php flarum info", run this in terminal in your Flarum directory.
Flarum core 1.0.0
PHP version: 8.0.6
Loaded extensions: Core, date, libxml, pcre, zlib, filter, hash, json, readline, Reflection, SPL, session, ctype, curl, dom, fileinfo, gd, gmp, iconv, intl, mbstring, openssl, PDO, standard, tokenizer, xmlwriter, zip, exif, mysqlnd, Phar, pdo_mysql, apcu, Zend OPcache
+----------------------+---------+--------+
| Flarum Extensions    |         |        |
+----------------------+---------+--------+
| ID                   | Version | Commit |
+----------------------+---------+--------+
| flarum-approval      | v1.0.0  |        |
| flarum-bbcode        | v1.0.0  |        |
| flarum-emoji         | v1.0.0  |        |
| flarum-lang-english  | v1.0.0  |        |
| flarum-flags         | v1.0.0  |        |
| flarum-likes         | v1.0.0  |        |
| flarum-lock          | v1.0.0  |        |
| flarum-markdown      | v1.0.0  |        |
| flarum-mentions      | v1.0.0  |        |
| flarum-statistics    | v1.0.0  |        |
| flarum-sticky        | v1.0.0  |        |
| flarum-subscriptions | v1.0.0  |        |
| flarum-suspend       | v1.0.0  |        |
| flarum-tags          | v1.0.0  |        |
+----------------------+---------+--------+
Base URL: (redacted)
Installation path: /flarum/app
Debug mode: off
```

**Possible Solution**
The payload that the admin page initially loads (in the HTML inside the `flarum.core.app.load`) seems to only include at most four tags. Using the mariadb general log, I determined that it is likely this is because [LoadForumTagsRelationship](https://github.com/flarum/tags/blob/2874bb9fc301197e1ea6a7924336ac554bb6bfe1/src/LoadForumTagsRelationship.php#L42) is now used to populate the tags in it, but that limits it to 4 tags for display purposes, whereas the admin page, unlike the sidebar, expects to receive all the tags. I'm not sure what change between beta 16 and 1.0.0 that causes LoadForumTagsRelationship to be used improperly to load the admin page payload. 

**Additional Context**
This does not appear in beta 16, only after upgrading to 1.0.0.

**Comment by datitisev** [comment]
I can reproduce this locally 👍 

When testing & trying to fix, remember this:
> Note that only 4 tags appear, and the "+ Restrict by tag" does not appear. After navigating to the Tabs page and back, [it is fixed]
