### ISSUE TITLE
Tooltip bug with italian language

### ISSUE THREAD

**Issue by justoverclockl** [flarum/core#2894]
Version: 1.0

Tooltip bug with italian language

![Immagine](https://user-images.githubusercontent.com/79002016/120227088-d57b6600-c248-11eb-90e1-6171765e7246.png)

**Comment by PeopleInside** [comment]
https://github.com/flarum/core/issues/2636

Thank you for reporting this

**Comment by SychO9** [comment]
Duplicate of flarum/issue-archive#144

**Comment by justoverclockl** [comment]
but is also closed with no resolution, just to know u about that ;)

**Comment by PeopleInside** [comment]
> 
> 
> but is also closed with no resolution, just to know u about that ;)

Issue https://github.com/flarum/core/issues/2636 is not closed, is opened without yet a solution merged.

**Comment by davwheat** [comment]
A solution was possible with CSS tooltips, but we've decided to hold off on that for a while. I plan to replace Bootstrap tooltips with another library in the future, and that should fix this issue.
