### ISSUE TITLE
[tags] Subtags are opened on each primary

### ISSUE THREAD

**Issue by Geraldlzc** [flarum/core#2895]
## Bug Report

Click secondary tags,Discover Primary Tags open,

1. Primary tags disorder,
2. The label on the title is out of order

**Screenshots**
![](https://files.catbox.moe/9nutht.gif)

**Environment**
- Flarum version: 1.0.1
- Website URL: 127.0.0.1
- Webserver: apache
- Hosting environment: 127.0.0.1
- PHP version: 7.3.25
- Browser:google chrome

**Comment by Ornanovitch** [comment]
Seems confirmed: I just reproduced this issue on nightly :ballot_box_with_check:

**Comment by rigomatuja** [comment]
I reproduced this issue switching from seeing discussions to tags, or categories (happens with, and without the extension). Once switched to Tags, and you enter to any of the tags or discussions, the tag tree on the sidebar is missordered without respecting the proper nesting.
### Discussions as homepage (works properly, cleared cache after changes applied)
![image](https://user-images.githubusercontent.com/3653610/120764565-8f5c2600-c518-11eb-909a-0dbfad930f86.png)
![image](https://user-images.githubusercontent.com/3653610/120764685-b4509900-c518-11eb-8fa0-7191bd7ecafa.png)
![image](https://user-images.githubusercontent.com/3653610/120764720-bc103d80-c518-11eb-87ff-814f1f9971a7.png)
![image](https://user-images.githubusercontent.com/3653610/120764743-c29eb500-c518-11eb-9788-e2ba28796cb3.png)

### Tags as homepage (does not work properly, cleared cache after changes applied)
![image](https://user-images.githubusercontent.com/3653610/120764870-e6fa9180-c518-11eb-988b-322f0820b4d8.png)
![image](https://user-images.githubusercontent.com/3653610/120765289-58d2db00-c519-11eb-9184-c8927796939d.png)
![image](https://user-images.githubusercontent.com/3653610/120765137-304ae100-c519-11eb-8e4f-49a4cc7e60b4.png)

**Comment by luceos** [comment]
Not entirely fixed: https://github.com/flarum/tags/pull/134#issuecomment-861665957

**Comment by SychO9** [comment]
I'm pretty sure what @the-turk refers to will be fixed by https://github.com/flarum/tags/pull/137
