### ISSUE TITLE
Missing 'edite user' translation

### ISSUE THREAD

**Issue by Hari-Bonda** [flarum/core#2899]
![](https://i.imgur.com/o8LvwmE.png)

https://discuss.flarum.org/d/26455-wysiwyg-rich-text-editor/116

**Comment by wotta** [comment]
I would like to do this issue.

I do have a question about this, should the translation be added for `core.lib.edit_user.nothing_available` or are there more translations that need to be added at this point?

**Comment by askvortsov1** [comment]
> I would like to do this issue.
> 
> I do have a question about this, should the translation be added for `core.lib.edit_user.nothing_available` or are there more translations that need to be added at this point?
> 

Excellent, thank you! I believe it's just that one, but haven't checked myself. You might want to test after adding it to make sure it works, and there isn't any part missed.
