### ISSUE TITLE
Old browser support

### ISSUE THREAD

**Issue by thangngoc89** [flarum/core#29]
As Ember doesn't support old browser but many users still use them. I think instead show a notification about user update. We should show the information inside 'noscript' tag to user.
More information https://meta.discourse.org/t/make-old-browsers-e-g-opera-mobile-classic-use-the-noscript-version-of-discourse/20716

Refer: https://github.com/flarum/core/issues/19

**Comment by Allineer** [comment]
I think, we should help users to update browser and we can use some like this: 
https://github.com/burocratik/outdated-browser

**Comment by tobscure** [comment]
The noscript version will be completely shitty (i.e. read-only and unstyled) because it will be designed for search engines, but I guess it can't hurt if it's not too hard to show it in older browsers. Flarum is forum software for the future so I think this is extremely low priority anyway.

**Comment by thangngoc89** [comment]
Yeah. It's not hard to show it anyway. This is just what my user (with Discourse forum) are complaining about they can't use Opera Mini. I hope Flarum will be the best integrate ever with my current Laravel website.
