### ISSUE TITLE
[Mentions] Unable to use Formatter with mentions on items other than Posts

### ISSUE THREAD

**Issue by datitisev** [flarum/core#2902]
The new mentions system contains code specific to posts and thus causes errors when no context is passed (or context that is not a Post is passed). Passing a `new Post()` will make all mentions `@[deleted]`

> Warning: Attempt to read property "mentionsUsers" on null

This is caused by https://github.com/flarum/mentions/blob/5a4be87f3ef9e37b14b7b0c150cfd4f159be53f0/src/Formatter/UnparseUserMentions.php#L50-L55, for example, and also the `Format`... class. This affects both user & post mentions.

I think the solution to this should be to check whether the context is a Post/CommentPost instance, and then use `User::find` or `Post::find` if it is not. For example: 

```php
$user = ($post instanceof Post)
    ? $post->mentionsUsers->find($attributes['id'])
    : User::find($attributes['id']);
```

---

Found by investigating https://discuss.flarum.org/d/18301-friendsofflarum-pages/386.

**Comment by dsevillamartin** [comment]
Relevant: flarum/issue-archive#297.

My thoughts on why I'd rather not have flarum/mentions locked down to posts:
> it's not so much as [needing mentions] in pages
> its more about being able to use them anywhere other than posts
> e.g. page with forum rules, lists mods but you aren't able to mention them so users can quickly go to their profile page
> also any other resource - the notification isn't necessary but having the ability of being able to click and go to the mentioned user/post is very helpful
> that's why i don't specially like the idea of only making mentions work on posts... cause then this functionality is gone

A comment by Franz that could be helpful & applied:
> I'd rather have such a feature enabled explicitly if that's what an extension wants. Especially in these scenarios, where we have somewhat unexpected interactions between two extensions.

I would be fine with this solution - having mentions support non-Post resources (similar to the code I have in the issue description) but only if the parsing/unparsing/rendering explicitly requires the feature somehow. Not 100% sure how that'd be implemented though.

**Comment by SychO9** [comment]
We need to look into if flarum/issue-archive#297 can be done in a non breaking way, if it's the case do that directly, if not then temporarily fix this issue in a non breaking way for 1.x

**Comment by askvortsov1** [comment]
> We need to look into if flarum/issue-archive#297 can be done in a non breaking way, if it's the case do that directly, if not then temporarily fix this issue in a non breaking way for 1.x

That should be possible, if we make `AbstractFormatter` the default argument for the formatter extender, and (possibly) deprecate that default

**Comment by askvortsov1** [comment]
> > We need to look into if flarum/issue-archive#297 can be done in a non breaking way, if it's the case do that directly, if not then temporarily fix this issue in a non breaking way for 1.x
> 
> That should be possible, if we make `AbstractFormatter` the default argument for the formatter extender, and (possibly) deprecate that default for v2 to require explicit registration

**Comment by imorland** [comment]
I just tried the proposed solution in the OP of this issue. Same code is required in `FormatUserMentions` as well. This does work, with only a minor change required in the affected extenstions.

This issue is currently impacting 3 extensions: `fof/pages`, `fof/moderator-notes` and `askvortsov/flarum-moderator-warnings`, possibily more.

Whilst I like @askvortsov1 's idea of creating an `AbstractFormatter`, I wonder if a PR implementing @datitisev 's original suggestion might be considered for an interim solution, to restore functionality lost by the mentions changes?

**Comment by SychO9** [comment]
As long as it's not a breaking change, I don't think anyone would mind an interim solution until we refactor the formatter API.
