### ISSUE TITLE
Several console error after upgrade to 1.0.2

### ISSUE THREAD

**Issue by justoverclockl** [flarum/core#2903]
After the upgrade i have several console error that changes every time i refresh the forum, u can see these directly on https://flarum.it

today is changed to:

![err](https://user-images.githubusercontent.com/79002016/120925449-03452c80-c6d9-11eb-9e7b-7b2b0bd21e5e.png)

**Comment by SychO9** [comment]
Looking at where the error points in the compiled code, this is most likely an issue with `fof/polls` and not `flarum/core`.

```js
Object(h.extend)(ce.a.prototype,"oncreate",(function(e,t){a.a.pusher&&a.a.pusher.then((function(e){e.main.bind("updatedPollOption",(function(e){var t=a.a.store.
```
