### ISSUE TITLE
Loading discussion from a direct URL promotes secondary tag

### ISSUE THREAD

**Issue by jordanjay29** [flarum/core#2907]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Steps to Reproduce**
1. Go to any discussion using a secondary tag (nested under a Primary)
2. Copy the URL
3. Load URL directly in a new window: [Like this](https://discuss.flarum.org/d/27394-flarum-100-released)
4. Secondary tag has been promoted to the front and its color used for the discussion header

**Expected Behavior**
Primary tag should remain in the correct order and apply its color to the discussion, even when the discussion is loaded from a URL. 

**Screenshots**
![image](https://user-images.githubusercontent.com/7871706/121032843-4652de80-c771-11eb-92db-e883630f8dd0.png)

**Environment**
- discuss.flarum.org running 1.0.2, confirmed on demo.flarum.site 20210607

**Comment by datitisev** [comment]
If you then go to the discussion list, the secondary tag appears like a primary 

![image](https://user-images.githubusercontent.com/6401250/121070370-a0b56480-c79c-11eb-8a98-d6b627845ccf.png)

**Comment by jordanjay29** [comment]
It seems like navigating from the Primary tag itself is the only way that the correct behavior presents. 

Navigating from All Discussions or from the Secondary Tag displays the affected behavior.
