### ISSUE TITLE
Avatar cannot load if deploy Flarum in sub folder

### ISSUE THREAD

**Issue by huytd** [flarum/core#291]
I see the resource loading code in `User.php` tell that we load from public path of `assets/avatars`

It work great if we deploy Flarum in the root folder of the website. 
But if we deploy it to the sub-folder, for example: `http://abc.com/forum`
The avatar will unable to load, because the image path will be `http://abc.com/assets/avatars/blah.jpg`, the expected path should be `http://abc.com/forum/assets/avatar/blah.jpg`

**Comment by franzliedke** [comment]
Thanks for reporting this, I'll fix subfolder installation for the next beta (planned for early next week).

**Comment by franzliedke** [comment]
Done. Will be released with beta.2 (next week).

**Comment by tobscure** [comment]
:D

**Comment by huytd** [comment]
great :+1:

**Comment by DearTanker** [comment]
weekend or middle week T.T
