### ISSUE TITLE
Bug Can not access API or Admin page

### ISSUE THREAD

**Issue by robrotheram** [flarum/core#292]
Hello Guys got a clean install of flarum but can not access the admin page or api pages causing most features to fail adding post etc. 

The Apache error I am getting is 

    [Fri Aug 28 08:35:46.846842 2015] [negotiation:error] [pid 13] [client 172.17.0.8:52863] AH00687: Negotiation: discovered file(s) matching request: /var/www/site/api (None could be negotiated)., referer: http://forum.robrotheram.com/

My usecase is a little odd but sould not be causing any issues since I have other webapps running without any problem. My use case is running the webapp in a docker container that has apache installed and mod rewrite enabled. The container then sits behind a nginx container used as a load balancer. but even if I connect to the container directly I still get the same error so its not the ngix load balance causing the issue. 

    [Fri Aug 28 08:36:35.836774 2015] [negotiation:error] [pid 12] [client 172.17.0.8:52991] AH00687: Negotiation: discovered file(s) matching request: /var/www/site/admin (None could be negotiated)., referer: http://robrotheram.com:8087/ 

I made sure that the folders are writable since I set them to 777 (I know its bad but I was testing what was causing the problem)

**Comment by franzliedke** [comment]
Sounds like rewriting problems, to be honest. (I'm assuming the front page itself works.) What happens if you access yourhost/api.php/discussions?

P.S.: I've successfully tested Flarum on Apache in a Docker container before (not without hassle), so that itself probably isn't the reason.

**Comment by franzliedke** [comment]
Make sure `AllowOverride` is enabled for the server's public directory, so that our .htaccess file is actually executed. (That was one of the problems I initially encountered.)

**Comment by tobscure** [comment]
This discussion is probably better had on the support forum? Assuming it's a rewrite issue, I'm going to close this.
