### ISSUE TITLE
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by UARRR** [flarum/core#294]
Hello, 

I'm not at all a developer but here you go: As soon as I want to change anything, I'll get one of those "Oops! Something went wrong on the server. Please reload the page and try again." errors. After a little digging I discovered, that behind the scenes this happens: 
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

I attached two images, that might help? I have no idea. 

![screen shot 2015-08-28 at 12 10 12 pm](https://cloud.githubusercontent.com/assets/1484806/9544128/5e4cb02e-4d7e-11e5-9564-66fb9a543f2a.png)

![screen shot 2015-08-28 at 12 10 18 pm](https://cloud.githubusercontent.com/assets/1484806/9544129/61d0087c-4d7e-11e5-98e3-d7be6cda05f5.png)

**Comment by franzliedke** [comment]
Are you using Nginx?

**Comment by UARRR** [comment]
franzliedke: I'm not sure, but I doubt it.

**Comment by franzliedke** [comment]
Hmm, seems to be something else. Can you provide some more details. What exactly did you attempt to do that triggered this error?

**Comment by UARRR** [comment]
I can view everything, open every page, see every little detail without problems, but as soon as I want to save something, e.g. the description, a theme color, no matter what, it gives me above mentioned errors. If I can provide more information somehow, I'm willing to do so, but I'm not sure what you'd need. :)

**Comment by UARRR** [comment]
Maybe this helps? http://hiaooc.com/phpinfo.php

**Comment by kantholy** [comment]
phpinfo response header:
Server:Apache

however, php is running in fastcgi mode instead of apache module...

what action did you perform?

**Comment by UARRR** [comment]
I switched the PHP version the server runs on via .htaccess like they told me to do. I really... didn't do anything else.

**Comment by WG-C** [comment]
+1 Same question:
Server : nginx
```
    server {
        listen       80;
        server_name  mydomain;

        #charset koi8-r;

        #access_log  /var/log/nginx/host.access.log  main;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;


        location / {
            root   /var/www/html/topic;
            index  index.php index.html index.htm;
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            root   /var/www/html/topic;
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            fastcgi_param SCRIPT_FILENAME    $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }

        # redirect server error pages to the static page /40x.html
        #
        error_page  404              /404.html;
        location = /40x.html {
        }

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
        }
    }

```

**Comment by tobscure** [comment]
See http://flarum.org/docs/installation for nginx config.

The Apache issue seems to be a URL rewriting issue, probably not an issue with Flarum itself. Closing this, but we can still continue support discussion here :)

**Comment by UARRR** [comment]
Would still love a bit of help with the Apache issue. Any idea how I could fix the rewriting issue? (Sorry for being a noob.)

**Comment by tobscure** [comment]
Is there a .htaccess file present?

**Comment by UARRR** [comment]
There is, it looks like this: 

```
<IfModule mod_rewrite.c>
  RewriteEngine on

  RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

  RewriteRule ^api(.*)$ api.php [QSA,L]
  RewriteRule ^admin(.*)$ admin.php [QSA,L]

  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule ^(.*)$ index.php [QSA,L]
  
  AddHandler php55-cgi .php
</IfModule>
```

**Comment by franzliedke** [comment]
Are you sure your .htaccess is actually being evaluated? Sometimes they're disabled for certain directories in Apache. Please [try it out](http://stackoverflow.com/questions/9234289/verify-if-htaccess-file-is-running) and report back with the results. :)

**Comment by franzliedke** [comment]
[This comment](https://github.com/flarum/core/issues/298#issuecomment-136053147) may help you fixing if what I mentioned above is really your problem. :)

Good night. :zzz:
