### ISSUE TITLE
Replying / Linking Event Post leads to JS Error

### ISSUE THREAD

**Issue by GreXXL** [flarum/core#2942]
## Bug Report

**Current Behavior**
When mentioning an event post on preview there is a JS-Error in console

**Steps to Reproduce**
1. Go to https://discuss.flarum.org/d/27858-affiliate-marketing-flarum-extension or https://discuss.flarum.org/d/27878-test
2. Hover over the post mention
3. See error

**Expected Behavior**
No JS Error

**Screenshots**
https://user-images.githubusercontent.com/1630413/123234820-9359e300-d4db-11eb-9123-683229a5abe0.mov

**Environment**
- Flarum version: 1.0.3
- Website URL: https://discuss.flarum.org

**Additional Context**
```
Uncaught (in promise) TypeError: Cannot read property 'substring' of undefined
    at i (forum.js?v=c14f5145:1)
    at r (forum.js?v=c14f5145:1)
    at e.view (forum.js?v=c14f5145:45)
    at Function.a (forum.js?v=c14f5145:22)
    at forum.js?v=c14f5145:22
    at forum.js?v=c14f5145:22
    at l (forum.js?v=c14f5145:22)
    at u (forum.js?v=c14f5145:22)
    at forum.js?v=c14f5145:22
    at l (forum.js?v=c14f5145:22)
```

**Comment by SychO9** [comment]
Here's the error when in dev mode:
```
string.ts:5 Uncaught (in promise) TypeError: Cannot read property 'substring' of undefined
    at i (string.ts:5)
    at r (highlight.tsx:27)
    at e.view (PostPreview.js:19)
    at Function.a (render.js:30)
    at render.js:155
    at render.js:160
    at l (render.js:66)
    at u (render.js:50)
    at render.js:134
    at l (render.js:63)
```

Besides fixing the JS error, it would be a good idea to improve the preview for an event post mention, even though people aren't supposed to reply to event posts, they still can by manually writing the post mention, as long as they have the post's ID.
