### ISSUE TITLE
Option to remove site name from meta titles in search results

### ISSUE THREAD

**Issue by heyitsritesh** [flarum/core#2944]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Currently, Flarum adds the site's name at the end of all the meta titles on the entire site. Titles look broken in Google search results because of that.

**Describe the solution you'd like**
A simple option to disable the inclusion of the site's name in meta titles.

**Justify why this feature belongs in Flarum's core, rather than in a third-party extension**
It defines how the site and all of its pages look in the search results. Flarum's core should have this feature.

**Comment by luceos** [comment]
https://extiverse.com/extension/ianm/no-meta-title
