### ISSUE TITLE
Sinhala Unicode not support in Version 1.0.4 but works fine in  0.1.0-beta.9 version 

### ISSUE THREAD

**Issue by thimiraonline** [flarum/core#2956]
Recently I observed that in Flarum version 1.0.4 search does not support Sinhala Unicode. But in version 0.1.0-beta.9. How to fix this? Is it possible to push a minor update with fix, because it is very useful for our Sinhala community.

**Comment by tankerkiller125** [comment]
This issue report does not meet our template requirements, please consider creating a new issue with the correct template information if your issue hasn't already been reported by others.
