### ISSUE TITLE
[Markdown] Inserting an emoji as alt text for markdown image syntax breaks the alt text for an image after posting

### ISSUE THREAD

**Issue by Ralkage** [flarum/core#2958]
## Bug Report

**Current Behavior**
When inserting an emoji as the alt text using markdown syntax, the alt text breaks and adds it's own image element instead.

Adding this to a post:
`![🔥](https://media1.tenor.com/images/93c7568d079ee7f55dbd7ee2472d0993/tenor.gif?itemid=4633722)`

Will produce the following when inspecting the DOM for the post body.

```html
<p><img src="https://media1.tenor.com/images/93c7568d079ee7f55dbd7ee2472d0993/tenor.gif?itemid=4633722" title="" alt="<img class=" emoji"="" draggable="false" loading="lazy">"&gt;</p>
```

**Steps to Reproduce**
1. Create a new discussion or post.
2. Paste the following in the composer body:
    - `![🔥](https://media1.tenor.com/images/93c7568d079ee7f55dbd7ee2472d0993/tenor.gif?itemid=4633722)`
3. Submit and view post. 

**Expected Behavior**
Adding an emoji to the alt text for markdown image syntax should not break the image alt and should allow for an emoji to be used as alt text.

**Screenshots**
![image](https://user-images.githubusercontent.com/2059356/125173536-de3b5200-e18d-11eb-9d73-cf7bd068a121.png)

**Environment**
- Flarum version: 1.0.4
- Website URL: https://demo.flarum.site
- Webserver: Nginx
- Hosting environment: VPS
- PHP version: 8.0.2
- Browser: Firefox 89.0.2 (64-bit)

**Comment by Ralkage** [comment]
I've also tested it with BBCode and it produces the same issue; use this for the BBCode example:

`[IMG alt=🔥 src=https://media1.tenor.com/images/93c7568d079ee7f55dbd7ee2472d0993/tenor.gif?itemid=4633722]`

**Comment by davwheat** [comment]
This seems like it might be to do with the fact that we are passing a string to `Twemoji.parse()`. This isn't the recommended method, with that instead being DOM parsing. See more: https://github.com/twitter/twemoji#dom-parsing
