### ISSUE TITLE
Upload Avatar fails when imagemagick extension is not enabled

### ISSUE THREAD

**Issue by kantholy** [flarum/core#297]
when trying to upload an avatar, the action fails:

XHR fails with error 500 at: `intervention/image/src/Intervention/Image/Imagick/Driver.php18`:
ImageMagick module not available with this PHP installation.

In general it's not a good idea to rely on Imagick, maybe use GD as the Driver in: `Flarum/Core/Users/Commands/UploadAvatarHandler.php:68`

otherwise, add it to the list of required extensions :smile:

**Comment by franzliedke** [comment]
Yep, this was an oversight and is [already fixed](https://github.com/flarum/core/commit/d5074c52862972ff0454be88f15f0bf83bdf203f).

Will be released in the next beta (hopefully early next week).
