### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by pavs** [flarum/core#298]
First I downloaded the beta zip file and unzipped on my localhost /var/www/html, open it up on browser and nothing happens.

So I try again delete everything and do git clone and try to install by running build.sh, still nothing. I saw an error about nothing having bower so I installed bower (sudo npm install -g bower) and tried again and still nothing. I feel like I am missing something obvious, so not sure what to do. Also there is no installation document ( or at least I couldn't find one).

Looks cool, really wanted to try it out but luck.

**Comment by pavs** [comment]
Found some instructions over here: http://flarum.org/docs/installation/

followed this process:  php flarum/flarum install
created a database before doing it.

The process ended without any error, still index.php doesnt load on the root folder.

**Comment by pavs** [comment]
Saw somewhere else that installation on subfolder isnt supported so moved to server www folder without any luck. Still trying

**Comment by d1a8lo24** [comment]
Really simple checks before installing only on Apache.
Make sure you have php is version 5.5 or greater.
Make sure that MySQL is version 5.5 or greater.
Make sure you have Imagemagick install on the server and Imagick install for php this is only for image manipulation but it shouldn't really prevent you from installing it.

If you're not sure of what you have create a php file call it systeminfo.php and add the following code.

    <?php
    phpinfo();
    ?>
go to the URL: htto://yoursite.com/systeminfo.php
and see what kind of a setup you have.

You can also try the following: 
look for the following file:
flarum/bootstrap.php
Now edit it and add the following code right after <?php

    <?php
    ini_set('display_errors', 'On');

Now this variable sometimes works this all depends on the security of your server and your host. also if you have access to the php.ini file you can enable that setting there, just remember to turn it off once you have finish debugging the problem.

**Comment by tobscure** [comment]
Closing this, good instructions above. Let us know if you're still having trouble!

**Comment by pavs** [comment]
Thanks @d1a8lo24 

There were multiple issues (expected as it beta). 

Firs issue was I didnt have mod_rewrite (I assumed I did). so enabled it by sudo a2enmod rewrite

Second problem was for some reason it was not accepting a database I created earlier by the same name, but I dropped it and recreated it by the same name, so after trying several time I gave up and created a new database by a different name not used before and it worked for the first time.

Third problem was I didnt make flarum/storage/framework/views writable, so I had to do that.

The forum installed properly but I couldnt change my   user logog or start a discussion or basically do anything that required me to change or write anything. 


After little investigation, I learned I had to add:

<Directory "/var/www/html">
    AllowOverride All
</Directory>

right under: 
 DocumentRoot /var/www/html

on default apache2 configur file on ubuntu 14 its /etc/apache2/sites-available/000-default.conf

Restart apache2 and everything  works as it should work.

I should mention I installed it on my localhost.

Cheers!

**Comment by tobscure** [comment]
Thanks @pavs – I've update the [installation documentation](http://flarum.org/docs/installation) to include some more detailed information. Also created #357.

**Comment by d1a8lo24** [comment]
This is something I recommend, the install application should be separated like most popular applications do, this will give you more control over what you can test before actually requiring it. for example testing if certain php extensions are available, which directories should have certain write permissions etc...

One of the best installers I have seen and one of the coolest applications out there is via the application koken which is a CMS.and free. Check it out and get some ideas from there you can do a quick install by just downloading one file, this file will test your server for what koken needs and it will create all the necessary set up and configuration before it starts downloading the application.

This will make it easier for many people to install the application with very minimum error.

**Comment by pavs** [comment]
@tobscure From the installation guide, the way I understand that you will have to add

'''
<Directory "/path/to/your/forum">
    AllowOverride All
</Directory>
'''
even if you have mod_rewrite enabled, I could be wrong, but that's how it worked for me.
