### ISSUE TITLE
not loaded flarum

### ISSUE THREAD

**Issue by mimsadAlef** [flarum/core#2999]
please visit link
https://mimsadalef.freeflarum.com

**Comment by matteocontrini** [comment]
It appears to be something related to the Night Mode extension. @davwheat

**Comment by mimsadAlef** [comment]
Apparently it was right, after configuring it, I came to post a post, but I got an error
I disabled some plugins and did not get any results
I wiped all the data with a reset
And broke down

**Comment by mimsadAlef** [comment]
and panel not working
![image](https://user-images.githubusercontent.com/70805659/127919108-fa894c9a-bb71-4f19-bb2e-776d10aef15e.png)

**Comment by datitisev** [comment]
This seems to be an issue with community extensions and/or FreeFlarum. We do not provide support for either of these unless the issue is caused by a Flarum core extension (`flarum/`).

You can try to clear the cache in the Dashboard admin page, if you can access it.

**Comment by mimsadAlef** [comment]
I use freeflarum
My only access is to reset all settings which has no effect

**Comment by luceos** [comment]
Get help from their dedicated discussion or their email address, see https://discuss.flarum.org/d/7585-free-flarum-hosting-on-an-expert-platform-by-freeflarum-com
