### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by Matthew2D** [flarum/core#30]
When I enter this in the terminal `git clone git@github.com:flarum/flarum`, I get this:

    Cloning into 'flarum'...
    Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
    Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights and the repository exists.

**Comment by randsonjs** [comment]
Try this: `git clone https://github.com/flarum/core.git`

**Comment by Matthew2D** [comment]
Worked thanks!
