### ISSUE TITLE
It would be nice to have an option to use a prefix for database tables

### ISSUE THREAD

**Issue by d1a8lo24** [flarum/core#300]
Many people will use a database that is already in use to install Flarum and many times this databsse will have other tables that may have similar tables to the ones Flarum uses so it would be nice to add a prefix option to the installation to create the tables to run Flarum.

This will keep the tables nice and organize to easily manage the database plus it will help prevent overwriting other tables or have problems when installing,

**Comment by tobscure** [comment]
Yep, we agree. Please search existing issues before posting a new one: https://github.com/flarum/core/issues/269
