### ISSUE TITLE
Make extension uninstallation delete extension files

### ISSUE THREAD

**Issue by Felli** [flarum/core#301]
I just now noticed that extensions have the ability to be uninstalled, but when trying it won't actually remove the extension.
Example: Uninstalling the Pusher extension gives a "Please Wait..." popup then refreshes but the extension is still there (Refreshing again doesn't help it is still there.)

**Comment by tobscure** [comment]
It does rollback the extension's migrations, so all of its modifications to the database will be uninstalled. But you're right, it should delete the extension files as well. There should also be a confirmation.

**Comment by Felli** [comment]
As of right now the only way of truly uninstalling is manually deleting from the extensions directory, also to note I haven't gotten any confirmation messages either just the "Please wait..." one.

**Comment by franzliedke** [comment]
I'd say we should rethink this process. We currently have four states for extensions, which makes this slightly complicated:
- **installed** - *alive and kicking*
- **disabled** - *migrations are installed, code is not run*
- **uninstalled** - *files exist, but extension has never been installed*
- **removed** - *files don't exist*

I'd argue we should somehow be able to get from **disabled** or **installed** to **uninstalled**, without having to remove the files altogether. Or does **disabled** fulfill that purpose altogether? (I'm wondering whether there could be any problem with not running extensions, but still having their migrations applied - they should not delete core columns, right?)

I'll delay this until we know how we should proceed.

**Comment by tobscure** [comment]
> Or does **disabled** fulfill that purpose altogether?

I'd like to think it does. Extensions definitely should not fiddle with core columns; their migrations should only be additive. And the end-user shouldn't be concerned with migrations at all anyway. I don't think there's a user-case for going from disabled/installed to uninstalled without removing the files.

**Comment by Luceos** [comment]
This requires integrated composer support to modify the composer.json of the installation. I'm not sure this should be part of the beta-5 milestone for that reason.

**Comment by tobscure** [comment]
@Luceos good point. Maybe we'll tackle admin composer stuff in beta 6.

**Comment by Luceos** [comment]
@tobscure this will be a addition in terms of code for core. It must be well thought out. This issue should probably land on a new one that combines all composer (installer) related issues in one feature spec.

**Comment by Luceos** [comment]
Closing this in favor of a wider implementation that holds this as requirement.
