### ISSUE TITLE
Tag nojs page doesn't use discussion slugger

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#3013]
## Bug Report

**Current Behavior**
The nojs PHP view for tags doesn't use the discussion slugger introduced in #2456 

With the default driver selected, this causes the ID to be repeated twice and therefore the wrong canonical URL to be used. With a custom slug driver, URLs would be broken.

**Steps to Reproduce**
1. Enable tag extension
2. Create discussion in tag
3. View source code of `<flarum url>/t/<tag slug>`
4. Observe wrong links being rendered in the `<noscript>` section

**Expected Behavior**
The links should be rendered identically to Flarum core's `index` nojs content.

Core nojs which has been updated to work with the slugger:
https://github.com/flarum/core/blob/f1ba5e7b7081767a6bfcef4a2736728cf35b9b0e/views/frontend/content/index.blade.php#L9-L13

Tag nojs which hasn't been updated:
https://github.com/flarum/tags/blob/7c9a3ca8d7de5c9d4b6aa7f0275f4b6f2ec20667/views/frontend/content/tag.blade.php#L10-L14

**Screenshots**
Screenshot of https://discuss.flarum.org/t/extensions source HTML
![image](https://user-images.githubusercontent.com/5264300/129096781-baab3863-100f-4d60-910a-3c2221ccacac.png)

**Environment**
- Flarum version: 1.0.4

**Possible Solution**
https://github.com/flarum/tags/blob/master/views/frontend/content/tag.blade.php needs to be updated to work like https://github.com/flarum/core/blob/master/views/frontend/content/index.blade.php

**Additional Context**
Reported here https://discuss.flarum.org/d/28599-tag-pages-seo-issues

**Comment by ayyilmaz** [comment]
https://discuss.flarum.org/d/27915-goog-search-console-excluded-pages

The excluded links have a URL structure that I don't understand on Google Search Console. What could be the reason for this? Currently discussion id is repeated. 

![](https://i.ibb.co/SmfdSFK/image.png)


![image](https://user-images.githubusercontent.com/24845098/123848126-04f0c180-d920-11eb-9d51-c1d7b1073726.png)

**Comment by askvortsov1** [comment]
This is tangential, but I don't like that we duplicate "discussion list" code between core and tags. Could we use an "included" template for both? IIRC this is possible with blade. We might also want to look into overridability of cores blade templates.
