### ISSUE TITLE
Users can't post links that end in ".php"

### ISSUE THREAD

**Issue by trever-s** [flarum/core#3023]
## Bug Report

**Current Behavior**
Users of camas.club receive an error message ("You do not have permission to do that.") when trying to include a link in their post that ends in .php.

**Steps to Reproduce**
1. Go to 'camas.club'
2. Click on 'sign up'
3. Scroll down to select a tag, create a new post, and insert link that ends in .php (e.g., https://www.pnwherbaria.org/index.php)

**Expected Behavior**
I expect when I click "Post to Discussion" it will work. 

**Screenshots**

**Environment**
- Flarum version: 1.0
- Website URL: http://camas.club
- Webserver: Apache 2.4.46
- Hosting environment: Shared (Namecheap Stellar Plus)
- PHP version: 5.6.40
- Browser: Chrome 92.0.4515.131

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

**Possible Solution**

**Additional Context**

**Comment by matteocontrini** [comment]
I've just tried both with a discussion and a post and it works correctly on your forum. This might be a WAF of your hosting provider but without seeing the HTTP response content it's hard to tell.

**Comment by luceos** [comment]
Just tested on discuss: https://discuss.flarum.org/d/28635-link-to-php

As such this is not an issue with Flarum but caused by something else.
