### ISSUE TITLE
Post metadata becomes transparent and is unreadable when a post is pending approval

### ISSUE THREAD

**Issue by matteocontrini** [flarum/core#3031]
## Bug Report

**Current Behavior**

When a post is in the status of requiring approval, the post metadata modal becomes transparent and is unreadable.

**Steps to Reproduce**
1. Configure approval so that new posts require approval
2. Create a new post (with a "normal" user), so that it's not approved by default
3. Click on "x minutes ago" on the post and notice that the modal is unreadable

**Expected Behavior**

The modal's opacity should not be changed when the post is pending approval.

**Screenshots**

![image](https://user-images.githubusercontent.com/2164763/129846561-0139f86f-ced5-4c63-8c49-f71c59e0f915.png)

**Environment**
- Flarum version: 1.0.4
- Browser: Firefox 91

**Comment by SychO9** [comment]
same as flarum/issue-archive#328
