### ISSUE TITLE
[Subscriptions] Email notifications quoting wrong reply

### ISSUE THREAD

**Issue by DCSJAPAN** [flarum/core#304]
Sorry if this is already known about...

I just received an email notification that Kulga had replied to a thread I'm watching. However, the email quoted my preceding reply, rather than Kulga's. I've noticed the same thing in other mail notifications.

I suspect this may be a simple post# versus reply# bug...

It's great to be receiving mail notifications, though! :)

**Comment by tobscure** [comment]
Confirmed.
