### ISSUE TITLE
[Markdown/Emoji] Markdown sometimes parsing as emojis

### ISSUE THREAD

**Issue by tobscure** [flarum/core#305]
_From @tobscure on August 27, 2015 13:53_

What needs to be done:

* Experiment with configuring the s9e\TextFormatter Emoticons plugin as per http://s9etextformatter.readthedocs.org/Plugins/Emoticons/Change_regexp/. Rather than requiring whitespace, we might like to use a negative lookahead for certain characters (e.g. `:`).
* It may also be worth removing the `:*` emoticon, because I can't think of any way to prevent it ruining situations where you want to do some formatting like `**Last updated:** whatever`.

_Copied from original issue: flarum/emoji#1_

**Comment by dbohn** [comment]
Another issue I have noticed while testing which seems to be quite similar but the other way round: At least for me and my friends the emoticon "^^" is quite common. But the used configuration of the TextFormatter deletes these two chars as it is interpreting those as nested sup tags. I think this is neither a syntactically nor semantically correct behavior.

**Comment by tobscure** [comment]
@JoshyPHP thoughts?

**Comment by JoshyPHP** [comment]
I don't think there's a One True Way™ to solve interactions between markup and emotes. If `^^` is systematically replaced with an emote then Reddit memesters will complain that `Your head^^^^^^the_joke` does not work anymore.

If users want to post `^^` as plain text, they can escape it as `\^^` or `\^\^` depending on the context.

**Comment by sijad** [comment]
can't use this instead:
```
        $event->configurator->Emoji->addAlias(':)', '🙂');
        $event->configurator->Emoji->addAlias(':D', '😃');
        $event->configurator->Emoji->addAlias(':P', '😛');
        $event->configurator->Emoji->addAlias(':(', '🙁');
        $event->configurator->Emoji->addAlias(':|', '😐');
        $event->configurator->Emoji->addAlias(';)', '😉');
        $event->configurator->Emoji->addAlias(':\'(', '😢');
        $event->configurator->Emoji->addAlias(':O', '😮');
        $event->configurator->Emoji->addAlias('B)', '😎');
        $event->configurator->Emoji->addAlias('>:(', '😡');

**Comment by tobscure** [comment]
Since the `:*` has been removed, I don't think that this is a real problem anymore. At least, no unwanted emoticons have come up in my everyday use. We can reopen if anyone can provide specific examples where an emoticon is appearing when it is unwanted.
