### ISSUE TITLE
Javascript errors when using mentions without search user permission

### ISSUE THREAD

**Issue by stimw** [flarum/core#3070]
## Bug Report

**Current Behavior**
after I set the permission 'Search users' to only admin and mods

then other users get an error when they reply and mention someone:

![Xnip2021-09-12_10-52-54](https://user-images.githubusercontent.com/30977647/132980394-03ead2cc-cf72-43c6-8d46-d79d0d7dd0fb.jpg)

**same problem happens on my dev environment, which has no third-party extension enabled. So I guess that's a core problem?**

**Steps to Reproduce**
1. Go to 'Permission' in administration
2. Change the 'Search users' settings to 'admin and mods'
3. reply and mention someone as a member

**Expected Behavior**
no error

**Environment**
- Webserver: nginx
- Hosting environment: vps
- Browser: chrome 93.0

```
Flarum core 1.0.4
PHP version: 7.4.20
Loaded extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, ctype, curl, dom, filter, ftp, gd, gettext, hash, iconv, intl, json, mbstring, SPL, session, pcntl, standard, PDO, mysqlnd, pdo_sqlite, Phar, posix, Reflection, pdo_mysql, shmop, SimpleXML, soap, sockets, sodium, mysqli, sysvsem, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, zip, fileinfo, exif, Zend OPcache
+----------------------------------+-------------+--------+
| Flarum Extensions                |             |        |
+----------------------------------+-------------+--------+
| ID                               | Version     | Commit |
+----------------------------------+-------------+--------+
| flarum-flags                     | v1.0.0      |        |
| flarum-approval                  | v1.0.0      |        |
| flarum-tags                      | v1.0.3      |        |
| flarum-suspend                   | v1.0.0      |        |
| afrux-forum-widgets-core         | v0.1.5      |        |
| flarum-sticky                    | v1.0.0      |        |
| fof-oauth                        | 1.0.2       |        |
| fof-byobu                        | 1.0.0       |        |
| fof-linguist                     | 1.0.0       |        |
| justoverclock-hot-discussions    | 0.1.0       |        |
| fof-formatting                   | 1.0.1       |        |
| ffans-clipboardjs                | v1.0.0      |        |
| justoverclock-events-countdown   | 0.1.8       |        |
| justoverclock-custom-html-widget | 0.1.3       |        |
| fof-spamblock                    | 1.0.0       |        |
| acpl-mobile-tab                  | 1.0.5       |        |
| the-turk-stickiest               | 2.0.3       |        |
| flarum-lang-chinese-simplified   | v1.0.4.0810 |        |
| fof-upload                       | 1.0.2       |        |
| extiverse-mercury                | 0.1.3       |        |
| fof-links                        | 1.0.0       |        |
| fof-split                        | 1.0.0       |        |
| flarum-likes                     | v1.0.0      |        |
| fof-ignore-users                 | 1.0.0       |        |
| fof-polls                        | 1.0.3       |        |
| fof-drafts                       | 1.0.3       |        |
| fof-sitemap                      | 1.0.1       |        |
| flarum-bbcode                    | v1.0.0      |        |
| flarum-emoji                     | v1.0.0      |        |
| flarum-lang-english              | v1.0.0      |        |
| flarum-lock                      | v1.0.0      |        |
| flarum-markdown                  | v1.0.1      |        |
| flarum-mentions                  | v1.0.0      |        |
| flarum-statistics                | v1.0.0      |        |
| flarum-subscriptions             | v1.0.0      |        |
| fof-profile-image-crop           | 1.0.0       |        |
| v17development-seo               | v1.8.0      |        |
| fof-recaptcha                    | 1.0.0       |        |
| fof-merge-discussions            | 1.0.0       |        |
| fof-user-directory               | 1.0.2       |        |
| fof-nightmode                    | 1.0.0       |        |
| phenomlab-fancybox-wrapper       | 0.8         |        |
| the-turk-flamoji                 | 1.0.2       |        |
| justoverclock-welcomebox         | 1.2.9       |        |
| afrux-forum-stats-widget         | v0.1.0      |        |
| ganuonglachanh-sonic             | 0.1.5       |        |
| fof-discussion-language          | 1.1.3       |        |
| fof-best-answer                  | 1.1.5       |        |
+----------------------------------+-------------+--------+
```

**Comment by clarkwinkelmann** [comment]
This is expected behavior. At the moment mentions can only be previewed if the user has the search users permission, because the mentioned username needs to be retrieved from the REST API.

I'm not sure if we have any existing issue or discussion about this, but I remember this being discussed internally in the past.

We should either force this permission to always match with the permission to mention users, or disable `@` user autocomplete when the user doesn't have search user permission.

If we do the latter we might need to make some changes to the "reply" part as well so it only uses preloaded data and doesn't try to use the REST API to fetch the user. The problem is that there might be situations where you reply/mention to a post that's not currently visible on the screen and might not actually be preloaded or not have the author preloaded.

**Comment by clarkwinkelmann** [comment]
I think we should keep this issue open, it's a valid use case and it shouldn't be too complicated to disable auto-complete when the user cannot search.

**Comment by ghost** [comment]
It's still not working properly. Even though the user doesn't have permission to search for users, sometimes after typing 2 characters, the list of users (all users from the forum) appears, while other times it doesn't. This also applies to creating new posts or replies.

**Comment by SychO9** [comment]
@rapty88 it's because the list will still show them users that they have seen, like authors of other replies. The searching itself from the API does not happen.
