### ISSUE TITLE
Some plugins are deactivated by themselves.

### ISSUE THREAD

**Issue by makifakkaya** [flarum/core#3075]
## Bug Report

After updating Flarum from beta to stable version, I started having problems activating plugins.

Let me briefly explain the problem. The plugins that I used in the beta version and that I continue to use in the stable version work without any problems. However, the plugins that I started using for the first time after updating to the stable version are disabled by themselves shortly after they are activated. I think the error is caused by the database, but I don't know how to solve it. How can I solve the problem?

**Video**
https://vimeo.com/580057280

**Environment**
- Flarum version: 1.0.4
- Website URL: https://kodmuhendisleri.com
- Webserver: nginx
- Hosting environment: DigitalOcean | lemp-s-1vcpu-2gb-fra1-01
- PHP version: 7.4.18
- Browser: Opera

**Comment by askvortsov1** [comment]
Did you find the reason why this was happening?

**Comment by makifakkaya** [comment]
> Did you find the reason why this was happening?

I created a new droplet and did clean install. The problem disappeared.
