### ISSUE TITLE
Invalid `composer.json` data in enabled or disabled extensions brick admin dashboard

### ISSUE THREAD

**Issue by davwheat** [flarum/core#3078]
## Bug Report

**Current Behavior**
With some extensions, the admin frontend is inaccessible.

One example seems to be `fof/spamblock`. This extension has no effect on v1.0.4, but renders the admin frontend inaccessible on v1.1.

This appears to relate to #3059.

![image](https://user-images.githubusercontent.com/7406822/134510966-5baf111a-50fd-4209-8f4a-7225cf200db2.png)

**Steps to Reproduce**
1. Install `fof/spamblock`
2. Access the admin frontend

**Expected Behavior**

**Environment**
- Flarum version: dev-master
- Webserver: Apache
- Hosting environment: Docker
- PHP version: 8.0.0

**Comment by SychO9** [comment]
looking at the extension's `composer.json` it mistakenly has `optional-dependencies` inside the `icon` object, guess we need to filter the `icon` element to only have string values in our code.

https://github.com/FriendsOfFlarum/spamblock/blob/master/composer.json#L44

**Comment by davwheat** [comment]
It might also be worth considering not breaking if an issue like this happens. Maybe, if we detect something wrong, we could return a placeholder icon?
