### ISSUE TITLE
[Subscriptions] User setting to automatically follow discussions you start/reply to

### ISSUE THREAD

**Issue by tobscure** [flarum/core#310]
_From @tobscure on July 28, 2015 6:46_

What needs to be done:

* Register a new bool preference (`followAfterReply`) using the RegisterUserPreferences event.
* Extend the core SettingsPage component's `settingsItems` method to add a new child to the `notifications` fieldset. That child should be a Switch which saves the followAfterReply preference.
* Listen for the PostWasPosted event and check the preference. If it's true, follow the discussion.

_Copied from original issue: flarum/subscriptions#1_

**Comment by petermein** [comment]
I started working on this issue. Its almost done but i have question about the implementation. 

Referencing: https://github.com/flarum/subscriptions/pull/6

Lets see subscriptions are managed in the subscriptions extension. I added 2 listeners here to add the setting and to listen to a new post. This works fine. 
But now i want to add a setting to the settings page, this is also not that hard but the settings page is part of the core. So i would like to add some sort of addition to the settings page from an extension. Is there i method for this. 

Example on how i implemented the settings now:

Add a new section to the settings list
```javascript
    items.add('forum',
      FieldSet.component({
        label: app.translator.trans('core.forum.settings.forum'),
        className: 'Settings-forum',
        children: this.forumItems().toArray()
      })
    );
```

Implement the items under the heading
```javascript
  forumItems() {
    const items = new ItemList();

    items.add('followAfterReply',
      Switch.component({
        children: app.translator.trans('core.forum.settings.follow_after_reply'),
        state: this.user.preferences().followAfterReply,
        onchange: (value, component) => {
          this.preferenceSaver('followAfterReply')(value, component);
        }
      })
    );

    return items;
  }
```

**Comment by tobscure** [comment]
@petermein Looking great so far! Thanks for taking this on.

I just [committed](9cb45c9) a small change to core which will allow you to slow this switch into the "notifications" settings fieldset, right beneath the grid. I think this is the best place for it.

You'll want to create a new file in js/forum/src (something like `addSubscriptionSettings.js`) with something like:

```js
import { extend } from 'flarum/extend';
import SettingsPage from `flarum/components/SettingsPage`;

extend(SettingsPage.prototype, 'notificationsItems', function(items) {
  items.add('followAfterReply', ...);
});
```

And don't forget to import it into main.js :)

**Comment by petermein** [comment]
Update the subscriptions PR, but i don't like the ordering of the settings items.
There is something with priority but im not sure yet.
