### ISSUE TITLE
Typecheck TypeScript via GH Action (+ possibly before build)

### ISSUE THREAD

**Issue by askvortsov1** [flarum/core#3106]
We currently support TypeScript typings, but don't actually run them to check that they are correct. This means editor support is there, but we lack confirmation that our code is actually correctly typesafe. We should definitely add a GitHub action to check typing, and possibly run that before building JS.

We should check typescript coverage via https://github.com/plantain-00/type-coverage (or the report library)

**Comment by davwheat** [comment]
There's no chance this can be done for 1.2. Core is packed with over 1000 typing errors at the moment.
