### ISSUE TITLE
[Subscriptions] Daily/weekly email digests

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#311]
_From @tobscure on August 27, 2015 13:53_

What needs to be done:
- Spec out exactly how this feature should work.

_Copied from original issue: flarum/subscriptions#2_

**Comment by tarunmarkose** [comment]
@tobscure Since this is going to have a huge role in bringing people back to the forum, I feel we should start brainstorming and implementation of this feature soon.

**Comment by JoshyPHP** [comment]
My personal experience with email digests is that enabling them *by default* is the fastest way to get me to block a sender/report as spam and never read their emails again. Same with the *"We haven't seen you in a long time"* reminders.

**Comment by tarunmarkose** [comment]
True.. it should be completely opt-in. Perhaps this can be done by allowing users to subscribe to Tags.. Flarum could then generate and email a user their daily/weekly digest based on their tag-subscriptions?
