### ISSUE TITLE
The plugin (Subscriptions) that comes with the v1.1 version has a bug. When there is no login user, the page is blank.

### ISSUE THREAD

**Issue by huasio** [flarum/core#3110]
The following two pictures show the specific error message. At this time, the data interface has not been requested, and it is obvious that the error occurred on the client side.

You can see the second picture. Except for the navigation bar, other parts of the page are blank. This is because the browser has a rendering problem. The specific error message on the right side shows that the obvious plug-in keyword is Subscriptions plug-in.

![image](https://user-images.githubusercontent.com/23445537/137661081-d0fe4b0a-2b62-440e-aa46-5b18d45702d8.png)

![image](https://user-images.githubusercontent.com/23445537/137661071-ee76c591-2889-4d4b-8d50-f28c046b06cd.png)

**Comment by askvortsov1** [comment]
> Can you check the error log in `storage/logs` please ?

I strongly suspect this is yet another instance of flarum/issue-archive#39: something null is getting pushed into the payload.
