### ISSUE TITLE
[Subscriptions] Subscribe to tags

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#313]
_From @tobscure on August 27, 2015 13:54_

What needs to be done:
- Create a migration to add an "is_following" column to the users_tags table (if it exists).
- OR, it might be better to just have a separate tags_following table? Not sure.
- Add an extensible TagControls mechanism to the tags extension, and make sure other parts of the tags extension are extensible.
- Use the ApiAttributes event to add an "isFollowing" attribute to the TagSerializer.
- Add code to persist the "isFollowing" attribute using the TagWillBeSaved event.
- Extend the tag extension's TagControls util and add a "follow" button that toggles/saves the isFollowing attribute.
- Add code to the NotifyNewPosts listener to send notifications for new discussions to users who are following any of the tags.

_Copied from original issue: flarum/subscriptions#4_

**Comment by jordanjay29** [comment]
Noting the existence of [fof/follow-tags](https://github.com/FriendsOfFlarum/follow-tags) which now achieves this functionality. This may fulfill or inspire this issue.

**Comment by franzliedke** [comment]
Let's close this, no need to pull this into core for now.
