### ISSUE TITLE
Edit post "until reply" policy broken on PHP8.0

### ISSUE THREAD

**Issue by clarkwinkelmann** [flarum/core#3144]
## Bug Report

**Current Behavior**
Setting the "Allow post editing" setting to "Until next reply" doesn't work on PHP 8.0

**Steps to Reproduce**
1. Use PHP 8.0
2. Set "Allow post editing" setting to "Until next reply"
3. Create additional replies
4. Can still edit post

**Expected Behavior**
Behavior should be identical to older PHP versions

**Screenshots**

**Environment**
- Flarum version: 1.1.0
- PHP version: 8.0

**Possible Solution**
The problem is here https://github.com/flarum/core/blob/9e1b05a358055db1dc8093036a7e006c254b921c/src/Post/Access/PostPolicy.php#L59-L61

The third condition always evaluates to `true` on PHP 8.0 when the setting value is a string that doesn't convert to a number.

```
$ php8.0 -r "var_dump(60 < 'reply');"
bool(true)
$ php7.4 -r "var_dump(60 < 'reply');"
bool(false)
```

I think we should add an `is_numeric()` test inside the third condition.

**Additional Context**
Reported here https://discuss.flarum.org/d/29347-post-is-editable-if-it-has-reply

**Comment by askvortsov1** [comment]
> I think we should add an is_numeric() test inside the third condition.

Agreed, that makes sense to me.
