### ISSUE TITLE
Forward-slash in Tag slug breaks routing

### ISSUE THREAD

**Issue by obfuscatedgenerated** [flarum/core#3152]
## Bug Report

**Current Behavior**
A slug can have / in it, which causes the URL path to be incorrect. There is no warning or filter stopping this.

**Steps to Reproduce**
1. Create a new tag
2. Enter a slug with a forward slash
3. Navigate to it in the browser

**Expected Behavior**
It should reject the slug or replace the slash.

**Comment by askvortsov1** [comment]
Let's just validate against front slashes in tags slugs then?

**Comment by davwheat** [comment]
Yep, seems like a good enough solution to me.
