### ISSUE TITLE
[Mentions] Intelligent positioning of reply/post popups

### ISSUE THREAD

**Issue by tobscure** [flarum/core#316]
_From @tobscure on July 28, 2015 6:59_

From http://discuss.flarum.org/d/396-general-ux/1:

> Hovering to see replies can cut into the top/bottom. I always like it when websites allow for these to go either below or above the mouse to prevent this. http://i.imgur.com/Xk7Nc1L.png, http://i.imgur.com/UhAmXxj.png

What needs to be done:

* Fix up dropdown positioning logic in the addComposerAutocomplete intializer so that the dropdown can't go off the edge of the screen.
* Add some dropdown positioning logic to addPostMentionPreviews initializer so that post previews can't go off the edge of the screen.

_Copied from original issue: flarum/mentions#6_

**Comment by franzliedke** [comment]
Do we have a z-index hierarchy defined somewhere in our stylesheets?

**Comment by tobscure** [comment]
@franzliedke yes, in variables.less
