### ISSUE TITLE
Permission dropdown in extension permission grid unusable

### ISSUE THREAD

**Issue by SychO9** [flarum/core#3168]
## Bug Report

**Current Behavior**
The dropdown doesn't properly position itself based on the space it has, this doesn't allow selecting groups, making the area unusable.

![Screenshot from 2021-11-17 10-43-19](https://user-images.githubusercontent.com/20267363/142606503-100e9d90-a6fb-464d-8728-226e6ab17afc.png)

**Expected Behavior**
Should act the same way in 1.1.0

![Screenshot from 2021-11-17 10-33-40](https://user-images.githubusercontent.com/20267363/142606528-44c503eb-f595-494e-9d47-7f5db2595c94.png)

**Environment**
- Flarum version: 1.2.0-dev

**Additional Context**
By checking into commits, it seems like this was introduced somewhere between https://github.com/flarum/core/compare/v1.1.0..4add23a9840166b4e95e3bca630ee29e56578577

Quiet possibly introduced in #2925

**Comment by askvortsov1** [comment]
We should be able to fix this by just not lazy drawing these particular dropdowns, I guess?

**Comment by datitisev** [comment]
Think so @askvortsov1

**Comment by askvortsov1** [comment]
In practice though, wouldn't it be possible to apply positioning logic when the contents are actually drawn, not before? Possible via an `oncreate` attr on the internal contents?

https://github.com/flarum/core/blob/f003faad27ee1151a98e6eb4136349331b3ee5dd/js/src/common/components/Dropdown.js#L78-L89 could be moved there.
