### ISSUE TITLE
[Mentions] Better reply insertion intelligence

### ISSUE THREAD

**Issue by tobscure** [flarum/core#317]
_From @tobscure on June 25, 2015 0:44_

When you click "reply" on a post, it will check if there is already content in the composer; if so, it will add two blank lines before the mention. This is good, but it can be annoying if you've already put two blank lines in preparation. We should detect if there are blank lines already there or not.

What needs to be done:

* Fix logic in the `insertMention` function in the addPostReplyAction initializer.

_Copied from original issue: flarum/mentions#5_

**Comment by franzliedke** [comment]
Fixed in https://github.com/flarum/flarum-ext-mentions/commit/e825d1a41b1728b39a5d73f1e0aa5dee56f90bb4.

I changed it so that at most two newlines are inserted, depending on the number of preceding newlines. If more than two newlines precede the cursor, they are left intact.

**Comment by franzliedke** [comment]
@tobscure Oh, should we take similar caution for any already existing content following the cursor (i.e. inserting newlines after the quote), too?

**Comment by tobscure** [comment]
I suppose so!
