### ISSUE TITLE
[Suggest]Suggestions on setting up user groups in the user information page!

### ISSUE THREAD

**Issue by airy6** [flarum/core#3171]
When I edit the user group of a user, the user group of this user will be reset, which will lead to conflicts with some extensions. For example, when I use the extension of `Auto Moderator`, it will be changed after the preset `criterion` takes effect. Modify the user's user group (add or delete). Then when I set up the user group again, the user group set by the `Auto Moderator` extension will be overwritten.

**My suggestions are as follows:**

> If you modify the user group modification process from `reset` operation to `modification` operation, similar problems can be avoided! With the development of `Flarum`, there may be many expansions that will involve the operation of modifying user groups. This situation should be avoided as soon as possible!

**My English is not very fluent, so please feel free to let me know if you have any difficulty in understanding.**

**Comment by askvortsov1** [comment]
I'm going to close this for now as it's not immediately actionable, and there's a discussion going on our forums. If we decide to take action after that, we can reopen this.
