### ISSUE TITLE
After changing the default discussion route, it leaks data when it is in restricted tags

### ISSUE THREAD

**Issue by rafaucau** [flarum/core#3182]
## Bug Report

**Current Behavior**
I have changed the discussion path in my extension (to make links from the old forum software work). And it works.
But I've recently noticed that discussions in tags that don't have public view permissions don't return error 404 properly. The frontend loads and when loading posts the error pops up. This leaks some data because there is some metadata in the `<head>` (such as the content of the first post) added by the SEO extension.

```php
use Flarum\Extend;

return [
    (new Extend\Frontend('forum'))
        ->removeRoute('discussion')
        ->removeRoute('discussion.near')
        ->route('/topic/{id:\d+(?:-[^/]*)?}[/{near:[^/]*}]', 'discussion')
];

```

```js
  app.routes.discussion.path = '/topic/:id';
  app.routes['discussion.near'].path = '/topic/:id/:near';
```

**Steps to Reproduce**
1. Change the default path to the discussion. [You can use my example extension](https://github.com/rafaucau/flarum-change-discussion-routes-example)
2. Add a restricted tag to the discussion
3. Visit the discussion link as an guest

Example: https://forum.android.com.pl/topic/374667-test

**Expected Behavior**
The 404 error should be returned correctly by the server as it is when the discussion route has not been changed.

**Screenshots**

https://user-images.githubusercontent.com/25438601/144119725-0f3c571a-2705-4ea1-994a-6f411b7d6ce6.mp4

![image](https://user-images.githubusercontent.com/25438601/144119845-5f9f0c33-b69a-44bb-8688-14f40301d7c9.png)

**Environment**
- Flarum version: 1.1.1
- Webserver: Apache, LiteSpeed
- Hosting environment: local, shared
- PHP version: 7.4, 8.0

**Comment by davwheat** [comment]
Have you got Flarum SEO installed? If so, please remove it and try this again. If not, let us know.

**Comment by rafaucau** [comment]
@davwheat On production, yes.
The issue occurs without SEO extension. In the attached video I show this on a fresh installation of Flarum where only my sample extension to change the discussion route is installed.

When the SEO extension is installed it just leaks more data.
BTW. the problem is not only with tags. If someone knows the link to a private discussion (Byobu) then so will be able to see some of the information.

**Comment by askvortsov1** [comment]
This error occurs because the `Routes->route` extender isn being used incorrectly. The `'discussion'` route is initialized with `Flarum\Forum\Content\Discussion`, which adds these checks: https://github.com/flarum/core/blob/b62d9614e40f534cf5c4ec952c2049125ab08912/src/Forum/routes.php#L22-L26. When the new `discussion` route is re-added, the content invokable class should be too. 

See tags for an example: https://github.com/flarum/tags/blob/8dc297ae5ddc01a33a37eb59821671ab293ae691/extend.php#L38-L39

**Comment by rafaucau** [comment]
I didn't find the cause and thought it was a bug in Flarum. I even asked on the Flarum Discord.

Now it works. Thanks!
