### ISSUE TITLE
Can't add a link within the welcome banner

### ISSUE THREAD

**Issue by arthuragone** [flarum/core#3187]
## Bug Report

**Current Behavior**
When I use Markdown syntax to add an internal link within my welcom banner, it didn't show any link but the plain text of the url with no clickable link. 

**Steps to Reproduce**
1. Go to Admin
2. Go to Essential
3. Add a link [link](url) 

**Expected Behavior**
Being able to add a link to a static page as un exemple. 
**Screenshots**

![Captureaaaaaaaaeeee](https://user-images.githubusercontent.com/10601027/144455201-3bf2d6e5-c797-4212-9fce-3cad27f36ae2.JPG)

**Environment**
- Flarum version: ?
- Hosting environment: freeflarum.com

**Comment by davwheat** [comment]
You need to use HTML code for this banner content, not markdown.

**Comment by arthuragone** [comment]
Thank you didn't figure that out before.
