### ISSUE TITLE
[Mentions] Add "Mentions" section to user profiles to show posts in which the user was @mentioned

### ISSUE THREAD

**Issue by tobscure** [flarum/core#319]
_From @tobscure on May 30, 2015 2:25_

_Copied from original issue: flarum/mentions#3_

**Comment by tobscure** [comment]
What needs to be done:

* Extend the core UserPage component's `navItems` method and add a mentions LinkButton. (Will need to add explicit priorities for the core items in order to insert the mentions link in the correct position.)
* Add a user.mentions route and MentionsUserPage, using the user posts page as an example.
* Add an event to core's Api\Actions\Posts\IndexAction to allow alteration of the `$where` criteria. Listen for this event and add a mentions filter.
* Use that endpoint/filter to show posts on the MentionsUserPage.

**Comment by OwlAsh** [comment]
Started with the task.

**Comment by franzliedke** [comment]
@OwlAsh Awesome! :+1: 

Be sure to post here if you encounter any difficulties. :)

**Comment by sijad** [comment]
<img width="612" alt="screen shot 1394-10-21 at 5 24 41 pm" src="https://cloud.githubusercontent.com/assets/7693001/12235324/570d5a1e-b888-11e5-9fe1-cbc3332e58d5.png">
front-end is done
I had to change priority of list items in `core/js/forum/src/components/UserPage.js` though,
but for filtering posts I couldn't find a clean way to join `mentions_posts` table to query, any idea?

**Comment by tobscure** [comment]
@sijad Sorry for taking so long to get back to you. Looking good! I've just committed 2018e424ec92e974c8fa9ee4d997c86e614e7126 which should allow you to hook in and apply a filter to the query properly. Also efff4c180111f19a3a91326917f69e4723fa04d1 to give the sidebar items priorities.

**Comment by sijad** [comment]
@tobscure thanks, flarum/flarum-ext-mentions#15 just pulled, I wasn't sure if number of mentioned should be shown or not, let me know

**Comment by tobscure** [comment]
For now let's not bother showing the number of mentions, as we'd need to cache that in a column on the users table and keep it up to date. Maybe later.

I think "post" mentions should be included too. I will make that amendment right after I merge the PR!

We shouldn't exclude the user mentioning him/her self.

**Comment by tobscure** [comment]
On second thoughts, maybe we shouldn't include "post" mentions as it complicates things a bit (would require another couple of joins) and they're technically not really mentions of the user anyway.
