### ISSUE TITLE
[Mentions] Add a contextual quote button when text is selected

### ISSUE THREAD

**Issue by tobscure** [flarum/core#320]
_From @tobscure on May 22, 2015 3:26_

Originally reported by amdad (http://demo.flarum.org/#/d/168/read-state-eager-load/6)

> Small idea: maybe after select text to quote Reply button can show up to click somewhere on it? If post is long and we select just one of top line we don't need to scroll to bottom to click reply.

_Copied from original issue: flarum/mentions#2_

**Comment by tobscure** [comment]
When post text is selected, we should show a "quote" button just above/below it. When clicked, a quote containing a post mention + the text will be added to the reply composer. (This is the same as what happens when you select text and hit the post's Reply button.)

What needs to be done:

* Research how to detect what text is currently selected, get the post that contains it, and position an element next to it.
* Implement.

**Comment by franzliedke** [comment]
I know we want to be careful with more dependencies, but just in case it proves difficult, or we reimplement similar things in multiple places, there's this: https://popper.js.org/

**Comment by jordanjay29** [comment]
Did anyone test Chrome compatibility? @modedeep on discuss.flarum (I replicated with Chromium on my own computer) can't quote emoticons/emoji with this feature.

**Comment by datitisev** [comment]
@jordanjay29 I can't quote emoticons/emoji on Safari either... At least they are dispensable ;)

**Comment by jordanjay29** [comment]
Sounds like a webkit family bug.
