### ISSUE TITLE
Tag list in admin panel unnecessarily includes lastPostedDiscussion

### ISSUE THREAD

**Issue by rafaucau** [flarum/core#3201]
## Bug Report

**Current Behavior**
I have 2.5k tags and the tag list in the **admin panel** takes a very long time to load. I noticed that there is a `lastPostedDiscussion` included. Unnecessarily, because it is not used here. It just kills performance.
https://github.com/flarum/tags/blob/c81617fa74365cd864dc7334ba254d75a603c135/js/src/admin/components/TagsPage.js#L47
```js
app.store.find('tags', { include: 'parent,lastPostedDiscussion' })
```

**Steps to Reproduce**
- Have a lot of tags
- Go to admin panel and tag page

**Expected Behavior**
Only the tags should be loaded. This should speed up loading dramatically.

**Screenshots**
![image](https://user-images.githubusercontent.com/25438601/146030730-5cd4b1c0-0e22-4d31-b7bf-159559f32d70.png)

**Environment**
- Flarum version: 1.1.1
- PHP version: 8.0

**Possible Solution**

Remove `lastPostedDiscussion` from `/js/src/admin/components/TagsPage.js`.

**Comment by askvortsov1** [comment]
Great catch, thank you! Opened https://github.com/flarum/tags/pull/152
