### ISSUE TITLE
Tag Alignment on Safari is off.

### ISSUE THREAD

**Issue by RelicSystem** [flarum/core#3218]
## Bug Report

**Current Behavior**
Tags on Safari are not aligned as clean as on other browsers.

**Steps to Reproduce**
1. Download / Open Safari
2. Question life choices
3. Head to your local Flarum instance 
4. Switch to tags
5. Ponder why alignment is off.

**Expected Behaviour**
Cleaner alignment 

**Screenshots**
They do
![safari-tag-alignment](https://user-images.githubusercontent.com/700503/146883784-533a1b1b-09c7-400b-9dd6-c0c2ba59faae.jpg)
![chrome-tag-alignment](https://user-images.githubusercontent.com/700503/146884578-a17b2eb3-145b-4a5c-abaf-69395c0ecb54.jpg)
![edge-tag-alignment](https://user-images.githubusercontent.com/700503/146884583-5ffa3dfb-609e-4bc1-893b-eefddb7710d4.jpg)
![firefox-tag-alignment](https://user-images.githubusercontent.com/700503/146884586-7be74b19-9c99-4714-b68d-cfb02c611160.jpg)

**Environment**
- Flarum version: 1.1.1
- Website URL: https://joolo.net
- Webserver: apache, nginx
- Hosting environment: vpa/shared
- PHP version: 7.4
- Browser: safari (see screenshots with specific version notes.

**Comment by SychO9** [comment]
Hello, thanks for the report!

This will be fixed as part of a larger frontend refactor to use flex/grid flarum/issue-archive#355
