### ISSUE TITLE
[Tags] Add a range of color presets when picking tag color

### ISSUE THREAD

**Issue by tobscure** [flarum/core#324]
_From @tobscure on August 28, 2015 5:7_

Looking at a forum like http://nintendoninjanews.com the tag colors are very strong/a bit harsh on the eye. We should present a range of soft color presets when picking the tag color to encourage nicer color choice. Similar to selecting a color when creating a GitHub issue label. We will still allow for a custom color to be entered if desired.

_Copied from original issue: flarum/tags#18_

**Comment by tobscure** [comment]
Actually a full color picker will probably be better – merging into #755.

**Comment by franzliedke** [comment]
So will that color picker have some nice pastel-ish defaults?
