### ISSUE TITLE
[Tags] Incorrect sub-tags ordering in Chrome

### ISSUE THREAD

**Issue by tobscure** [flarum/core#325]
_From @tobscure on August 28, 2015 2:56_

_From @tarunmarkose on August 20, 2015 7:37_

The "Installation" subtag of "Support" on the demo site opens wrongly under "Dev". This happens for me while using Chrome. Firefox and Safari, are fine.

![screenshot 2015-08-20 13 04 05](https://cloud.githubusercontent.com/assets/7383852/9378054/0e9d89e2-473c-11e5-8956-7b64c028680c.png)

_Copied from original issue: flarum/core#239_

_Copied from original issue: flarum/tags#17_

**Comment by tobscure** [comment]
_From @tarunmarkose on August 27, 2015 8:26_

Hey, @tobscure if you are not fixing this before the beta release, I and my colleague @ishanAhuja could try and take care of it. Let me know.

**Comment by tobscure** [comment]
Go for it! Relevant file is js/lib/utils/sortTags in the flarum/tags repo.

**Comment by ishanAhuja** [comment]
I'm unable to reproduce this issue. Has it been fixed?

**Comment by tobscure** [comment]
No, I can still reproduce in Chrome 44.

**Comment by tarunmarkose** [comment]
@tobscure Seems like something fixed the issue.. if you can still reproduce the error, please outline here.. 

![screenshot 2015-08-30 13 43 23](https://cloud.githubusercontent.com/assets/7383852/9566287/535286a8-4f1d-11e5-80df-bf07df2dd334.png)

**Comment by tarunmarkose** [comment]
I am on Chrome 44.0.2403.157.

**Comment by tobscure** [comment]
And seems to be fixed for me now too! That's weird, but sure, I'll take it :)

**Comment by tobscure** [comment]
I think there might be more to the issue – like the number of other tags are present. We need to come up with a solid reproduction method.

**Comment by tarunmarkose** [comment]
True dat, @maxyc's issue seems like the same problem.
Even and odd number of tags is the first thing that comes to mind.
Alright, lets figure this out! I and @ishanAhuja will first work on reproducing the error today.

@maxyc Is there anything you can add to this thread to help us reproduce the error?
Can you take a screenshot of your tags administration page and put it up here so we can recreate it at our end?

**Comment by tarunmarkose** [comment]
@maxyc An export of your tags table, taken when the problem occurs would also be helpful.

**Comment by maxyc** [comment]
ok, ![](http://cs625231.vk.me/v625231404/47b6a/6V7AIhD3NFU.jpg) on mobile error too

**Comment by maxyc** [comment]
error here http://novour.ru/t/Hobby 
![1](https://cloud.githubusercontent.com/assets/795360/9574172/83881cf0-4fc4-11e5-915c-63f7ef4a7f32.png)

**Comment by maxyc** [comment]
http://novour.ru/sxd/backup/maxyc_novour_2015-08-31_10-43-39.sql.gz

**Comment by maxyc** [comment]
http://novour.ru/sxd/backup/maxyc_novour_2015-08-31_10-46-44.sql.gz db table without users table

**Comment by tarunmarkose** [comment]
Thank you! I was able to recreate the issue. Will report back soon.

-Tarun

**Comment by maxyc** [comment]
bug in Firefox 40.0 / Windows 7
http://api.browsershots.org/png/original/53/53432502fe92f0c63372bab91a76ade9.png

safari and opera is ok
http://api.browsershots.org/png/original/49/495195c8ad1887ba048948d0c6542b27.png
http://api.browsershots.org/png/original/1f/1fe9fe988c9e3596b44271fb5dad0b73.png

**Comment by tobscure** [comment]
Since I added a new sub-tag, discuss.flarum.org is reproducing this reliably now. :tada:

**Comment by ishanAhuja** [comment]
It seems that `sortTags(tags)` (js/lib/utils/sortTags) is giving differently ordered arrays in Chrome and Safari. Consequently the tags are ordered differently on Chrome and Safari. Any insights on what may be the cause?

**Comment by tobscure** [comment]
It's due to a flaw in our sorting algorithm, so it ends up relying on the browser's sorting algorithm which [varies between browsers](http://stackoverflow.com/questions/3026281/array-sort-sorting-stability-in-different-browsers). We need to fix our sorting algorithm.

**Comment by ishanAhuja** [comment]
I see. I'll take a stab at redoing the sortTags function.
If you could provide a sample set of tags passed to sortTags and the expected output (including orphan tags), it would be very helpful. Thanks.

**Comment by tobscure** [comment]
The algorithm should basically result in this:

1. Tags where `position !== null`, ordered by `position` ascending.
    - Tags with a `parent` should immediately follow it. Tags with the same `parent` should be ordered by `position` ascending.
2. Tags where `position === null`, ordered by `discussionsCount` descending.

So given the tags:

| id | name | position | parent_id | discussions_count |
| --- | ------ | ---------- | -------------- | --------------- |
| 1 | other | 4 | null | 10
| 2 | ux | 2 | null | 13
| 3 | dev | 3 | null | 14
| 4 | blog | 1 | null | 1
| 5 | i18n | 2 | 3 | 7
| 6 | extensibility | 0 | 3 | 3
| 7 | theming | 1 | 3 | 1
| 8 | likes | null | null | 7
| 9 | tags | null | null | 19
| 10 | sticky | null | null | 2

We should end up with:

1. blog
2. ux
3. dev
4. extensibility
5. theming
6. i18n
7. other
8. tags
9. likes
10. sticky

**Comment by ishanAhuja** [comment]
Thanks Toby, I'll get on it.

**Comment by ishanAhuja** [comment]
I've been pretty caught up at work, with a new release coming up for our product. If anyone else is willing to take a shot at this and contribute a fix, please go right ahead.
