### ISSUE TITLE
HTML Entities in Browser Title

### ISSUE THREAD

**Issue by zerosonesfun** [flarum/core#3280]
## Bug Report

**Current Behavior**
HTML Entities in browser title.

**Steps to Reproduce**
1. Create a post with a title that includes apostrophes
2. Look at tab title

**Screenshots**
![](https://i.ibb.co/JK74kp9/Screen-Shot-2022-02-08-at-3-20-21-AM.png)

**Environment**
- Flarum version: 1.2
- Website URL: https://discuss.flarum.org
- Browser: Safari

**Comment by davwheat** [comment]
Thanks for the report!

This was fixed by a7254773dd1a22f43b1d7ee714fe29737ba9fa9f. :)
