### ISSUE TITLE
[Tags] Add per-tag unread discussion counts + ability to mark a tag as read

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#331]
_From @tobscure on August 27, 2015 13:49_

This is a tricky one. For every user/discussion, there is a record in the database containing the last post number that was read. Flarum says that a discussion is "unread" if the discussion's last post number is greater than the user's last read number for that discussion. Also, the last post time must be later than the user's "mark all as read" time.

So in order to count the number of unread discussions in a certain tag, do we need to compare _all_ of the individual discussion last post numbers to the user's last read numbers? And wouldn't that involve one query per tag? That sounds pretty inefficient to me...

Marking a tag as read is the easy part, because we can just have a "marked as read" timestamp for each user/tag combo, and then require the last post time for each discussion with that tag to be greater.

What needs to be done:
- Figure out a way to implement this efficiently.
- We'll do other planning after we've done that.

_Copied from original issue: flarum/tags#11_

**Comment by Ornanovitch** [comment]
boring bot
