### ISSUE TITLE
[Tags] Truncate long tag labels

### ISSUE THREAD

**Issue by tobscure** [flarum/core#332]
_From @tobscure on August 6, 2015 1:31_

On mobile, having too many tags pushes the "last reply" info off the screen. Even on desktop, too many tags and a long discussion title can overlap. We should limit the discussion list to displaying 3 tags.

What needs to be done:

* Add a new prop (maybe `count`) to the tagLabels util. If the prop is set, splice the tags beyond that number off.
* Make use of that prop in the addTagLabels initializer when extending the DiscussionListItem's infoItems.
* Add some padding to the DiscussionListItem title so it's less likely to overlap tags.

_Copied from original issue: flarum/tags#10_

**Comment by tobyzerner** [comment]
Given the fix in flarum/framework#702, I'm not going to bother with this. Something to think about as part of flarum/issue-archive#393 though.
