### ISSUE TITLE
Add ability to handle requests ending with a slash

### ISSUE THREAD

**Issue by DCSJAPAN** [flarum/core#334]
A user could conceivably (blush) remove the post number and end up with a URL like this:

http://discuss.flarum.org/d/336-potential-l10n-stumbling-blocks/

... Which gives a 404. Flarum ought to be able to remove the final "/" on its own.

**Comment by franzliedke** [comment]
We'll have to handle duplicate content with this, but that will probably be part of adding rel=canonical meta tags everywhere...
