### ISSUE TITLE
Add a vendor:publish command so that extensions can publish assets

### ISSUE THREAD

**Issue by tobscure** [flarum/core#335]
We need a Laravel-esque API that allows service providers/extensions to register assets, and a command that copies them into the `assets` directory. This will be used during Vagrant installation (core contains FontAwesome assets that need to be published). It should also be run whenever an extension is enabled, and reversed whenever an extension is uninstalled.

We don't necessarily have to call it `vendor:publish`, maybe just `publish` will be fine?

**Comment by franzliedke** [comment]
This would be a good time to talk about [Puli](http://docs.puli.io/en/latest/), I think. :)

**Comment by tobscure** [comment]
I just feel like Puli will make things more complex. From a quick scan of the docs I can't see how it would integrate *simply* for us. The way we have things set up is pretty specialised and works well because it does exactly what we need it to do - nothing more, nothing less. Would we not waste time getting Puli to fit in with this paradigm?

That said, I'll keen an open mind :)

**Comment by tobscure** [comment]
This is done in 2ae7392dead9e42ec28e637ff20a3d45c6e512f4
