### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Petrouchka** [flarum/core#336]
The Flarum License (MIT/Expat) is not copylefted. One day, a closed version will appears and the Open Source version will disappear, like with https://www.lundimatin.fr and so many others Open Source softwares. Should change to a copylefted license like GNU GPL 3.

**Comment by tobscure** [comment]
Nope, copylefting is too restrictive.

**Comment by Petrouchka** [comment]
It's a personnel choice or the choice of the community ?
