### ISSUE TITLE
Should add an inline HTML5 editor

### ISSUE THREAD

**Issue by Petrouchka** [flarum/core#337]
Should be great to add an inline HTML5 editor like https://www.raptor-editor.com.

**Comment by tobyzerner** [comment]
We have no plans to include a WYSIWYG editor in core right now, this will be up to a third-party extension :)

However we do plan to add formatting buttons, see flarum/issue-archive#408.

**Comment by Petrouchka** [comment]
razorCMS is using a very ergonomic editor, mainly for adding pictures.
