### ISSUE TITLE
Firefox lack of speed ?

### ISSUE THREAD

**Issue by Technowix** [flarum/core#339]
Hi there !
A video can worth more than word in this case :
https://www.youtube.com/watch?v=GspHoyBuIdk
(We got lot of "rollback" when we try to scroll)

Step de reproduce : 
Android phone + Firefox for android or Firefox for android BETA

The desktop version of FF are also a bit slow on Flarum :)

And, all of this happen on every topic (Much less on the main page) & the "of canvas menu" on mobile are a bit laggy too ^-^'

**Comment by Technowix** [comment]
Have to say, the "big fat" UI of discourse is really, really smooth in firefox compared to Flarum :x

**Comment by franzliedke** [comment]
@Technowix What's the state of this? Are you still experiencing these problems on Firefox? Anybody else?

**Comment by Technowix** [comment]
@franzliedke just tried on my mobile phone, this is running really smoothly (discuss.flarum.org) !

**Comment by franzliedke** [comment]
Time does heal all wounds, hehe. ;)

Thanks for reporting back!
