### ISSUE TITLE
CLA explanation

### ISSUE THREAD

**Issue by PeeHaa** [flarum/core#34]
I suck at legalese, but does this mean you can (at any point in time) put a closed source license on the project (including all 3rd party contributions)?

> By contributing your code to Flarum you grant Toby Zerner a non-exclusive, irrevocable, worldwide, royalty-free, sublicenseable, transferable license under all of Your relevant intellectual property rights (including copyright, patent, and any other rights), to use, copy, prepare derivative works of, distribute and publicly perform and display the Contributions on any licensing terms, including without limitation: (a) open source licenses like the MIT license; and (b) binary, proprietary, or commercial licenses.

**Comment by qrokodial** [comment]
potentially, but this seems to be more of a "if you submit code, you can't later say that you don't want your code that you submitted to be used anymore". this prevents months or even years of progress to be halted due to DMCA requests.

**Comment by tobscure** [comment]
Tbh, I suck at legalese too so I just copied this from [Ghost's CLA](https://github.com/TryGhost/Ghost/blob/master/CONTRIBUTING.md) (scroll to the bottom). (Ghost is released under the MIT, so I guess I should be attributing that somewhere...)

I think that yes, this does mean at any point in time I can put a closed source license on the project (including all 3rd party contributions) — but would I be correct in saying that a copy of the project at the point in time immediately prior to this relicensing would still be available under the MIT license, and could therefore be forked?

Like @qrokodial said, the CLA is more to explicitly gain permission from all contributors that their code can be used in the project. But it's also good to cover ground in the future in case I do end up wanting to do anything different with the project. (As an example, esoTalk was developed under the GPLv2 with no CLA, and recently I looked into relicensing to the MIT to be more permissive, but realised it's not possible without a lot work manually following up all the contributors.)

**Comment by Danack** [comment]
> but would I be correct in saying that a copy of the project at the point in time immediately prior to this relicensing would still be available under the MIT license, and could therefore be forked?

Yes. License changes aren't retroactive. Being able to change the license would mean that you would be able to make any new versions available under a different license. Older copies of the software would still be distributable under the (as of now) current license.

**Comment by Danack** [comment]
Oh - that bit kind of sucks:

> transferable license under all of Your relevant intellectual property rights (including copyright, patent, and any other rights),

Copyright is one thing - but it would almost certainly not be legal for any person with a job to agree to give patent rights away.....and that's not something people should agree to lightly...

**Comment by tobscure** [comment]
Does the word "relevant" in that sentence have any weight? i.e. If someone contributes some code, but it doesn't involve any patented material, then they don't have to give away patent rights because they're not relevant to the contribution. (Disclaimer: I have no idea what I'm talking about)

**Comment by Danack** [comment]
> Does the word "relevant" in that sentence have any weight?

Some, but it's a little vague. The Google [CLA is even more verbose](https://cla.developers.google.com/about/google-individual) but is slightly more tightly worded.

It's also got a section on the fact that you ought to have your employers permission to sign the CLA.

**Comment by tobscure** [comment]
I'm wondering then how Ghost is getting away with having this CLA? I liked it because it was short and sweet (very readable), and its wording seems to bypass the need to cross-check that a PR author has signed a digital form or whatever.

Other option is to switch to a CLA from harmonyagreements.org, and maybe use something like clahub.com to help checking. Thoughts?

**Comment by qrokodial** [comment]
I just generated a sample CLA from Harmony, and it seems like it's fairly decent but my legalese isn't good enough to determine if this fixes the original problem.  however, clahub.com seems awesome.

**Comment by tobscure** [comment]
Closing, I don't think this is an issue. The wording from the Ghost CLA is in many other open-source CLAs too.
