### ISSUE TITLE
No copyleft in license

### ISSUE THREAD

**Issue by Petrouchka** [flarum/core#340]
The Flarum License (MIT/Expat) is not copylefted. One day, a closed version will appears and the Open Source version will disappear, like with https://www.lundimatin.fr and so many others Open Source softwares. Should change to a copylefted license like GNU AGPL 3.

Is MIT license a personnel choice or the choice of the community ?

I'm interested to contribute (french translation, bug report) if it's a copylefted software. I'm not interested to waste my time for a company who one time will only distribute a proprietary version of Flarum.

**Comment by override-chaos** [comment]
Flarum is MIT and as @tobscure has said here #336 copyleft license is too restrictive.

It's simple Flarum is MIT same as Laravel, if you don't like don't contribute.

```
I'm not interested to waste my time for a company who one time will only distribute a proprietary version of Flarum.
````
You making unfounded assumption that Flarum will go private !

**Comment by Petrouchka** [comment]
My assumption is founded, I'm tired of seeing so many good Open Source project becoming closed source. Flarum is a good product, some companies will invest in it and it will become closed source, it's inevitable.

**Comment by franzliedke** [comment]
The license is our choice as the creators of the software. I think that's fine. :)

That said, I don't see an abundance of MIT open-source projects becoming closed source after some time. That is not "inevitable". Flarum is and always will be free and open-source. We've said that before.

Even if somebody were to take the code and create a closed-source version, the open-source code will still be around. :)

**Comment by Petrouchka** [comment]
MIT license makes sense for a library or a framework like Laravel, not for a PHP web application using it.

**Comment by franzliedke** [comment]
Why?

**Comment by Petrouchka** [comment]
A framework or a library can be used with a free software or a proprietary software -> Open Source license without copyleft, like MIT/Expat license.
For a web application that you want to distribute as a free software (and not as an Open Source software), it's better to choose a copylefted licence like GNU GPL and more better, an AGPL license because it's a web application.
https://en.wikipedia.org/wiki/Affero_General_Public_License

**Comment by franzliedke** [comment]
I'm sure there's always a market for a *free*, open-source solution. :)

**Comment by Petrouchka** [comment]
If you have always enough time and money, of course.
