### ISSUE TITLE
[Tags] New tag is always created as secondary tag and can't be moved as a primary tag

### ISSUE THREAD

**Issue by Petrouchka** [flarum/core#341]
1) New tag is always created as secondary tag -> should add the possibility to choose between Primary or Secondary when creating a new tag.

2) A new tag created as a secondary tag can't be moved immediately as a primary tag. I need to reload the page just after having create it and then, I can move the new secondary tag as a primary tag.

**Comment by Felli** [comment]
Just a heads up you don't actually have to reload the page just click the Tags tab in the admin panel, this also makes the drag n' drop feature work.

**Comment by Petrouchka** [comment]
The drag n' drop feature work in my case, before and after reloading the page.

**Comment by tobscure** [comment]
What browser are you using?

**Comment by Petrouchka** [comment]
Firefox 40.0.3 on Linux Mint MATE 17.2.

**Comment by tobscure** [comment]
Working well for me on Firefox 40.0.3, so we'll assume this is fixed and you can re-test after beta 2 is released.

**Comment by malayladu** [comment]
It works for me.

I have tested in Firefox 37.0.2 Mac OSX 10.8.5

**Comment by Petrouchka** [comment]
I will test, I'm happy you fixed it.

**Comment by Petrouchka** [comment]
Tested in beta 2 and it works well now.
