### ISSUE TITLE
Cannot update Discussion Metadata

### ISSUE THREAD

**Issue by modInfo** [flarum/core#343]
[Sat Aug 29 14:02:21.750136 2015] [:error] [pid 24108] [client 198.41.241.25:60625] PHP Notice:  Trying to get property of non-object in /var/www/flarum/flarum/vendor/flarum/core/src/Core/Discussions/Listeners/DiscussionMetadataUpdater.php on line 82

**Comment by tobscure** [comment]
Gonna need more info. From http://flarum.org/docs/contributing:

> If you find a bug, we’d like to know about it! Remember that the goal of a bug report is to make it easy for us to replicate the bug and develop a fix. Therefore, you should include as much relevant information as possible, and communicate it in a clear, factual way. [This article](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) is a great resource on how to report bugs effectively.

**Comment by tobscure** [comment]
Closing, will reopen if more info is given and we can reproduce.

**Comment by tobscure** [comment]
Closing this, let me know if you can provide any more info.
