### ISSUE TITLE
Can't translate any text

### ISSUE THREAD

**Issue by maxyc** [flarum/core#345]
![](http://cs625231.vk.me/v625231404/478f5/QyjbcGkcmf0.jpg)

1. Translation lists
2. Hours. Yes, its config moment.js, but how config it in flarum? =(
3. Link Tags in left menu

p.s. https://github.com/maxyc/flarum-i18n-russian

**Comment by franzliedke** [comment]
1. Not sure about that one. I usually prefer having the language name in the name of the language. So for German it would be "Deutsch". Helps people find their language if the site is in another language (but requires some kind of icon that makes it clear that's where the language can be selected).
2. Just created [an issue](https://github.com/flarum/core/issues/350) for this.
3. Just an oversight, thanks for the heads-up. Fixed this in https://github.com/flarum/tags/commit/e51465fd1f98c23a8310f53d831f593756ad54fb.

**Comment by tobscure** [comment]
1. I was thinking this should be up to the language pack – it can include both language names when it registers itself?

```php
$event->manager->addLocale('de', 'German (Deutsch)'); // or whatever
```

**Comment by maxyc** [comment]
update,  link "choose tag"  dont translate too, when create discussion

p.s. though you will learn English :D
