### ISSUE TITLE
Install : error on MySQL

### ISSUE THREAD

**Issue by Draky50110** [flarum/core#347]
Hello.

Just tried to install the beta but got an error from MySQL ?

Something went wrong: SQLSTATE[42000]: Syntax error or access violation: 1115 Unknown character set: 'utf8mb4'

**Comment by emilsundberg** [comment]
Which version of MySQL are you using? I think MySQL 5.5 is required, see http://discuss.flarum.org/d/569-sqlstate-42000-syntax-error-or-access-violation for more info.

**Comment by franzliedke** [comment]
Yep, please make sure you're using MySQL 5.5+

**Comment by Draky50110** [comment]
Ok, thanks.
It is the problem.

**Comment by tobscure** [comment]
@franzliedke we should check for this in the installer?

**Comment by franzliedke** [comment]
Yep. [Ticket](https://github.com/flarum/core/issues/364) created.

**Comment by Nerdcoat** [comment]
I installed the latest beta but have the same error. MySQL is 5.5+

**Comment by franzliedke** [comment]
@Nerdcoat Which version exactly?
