### ISSUE TITLE
To extend the localization proposals

### ISSUE THREAD

**Issue by mokecc** [flarum/core#348]
``` php
    public function addLocale(RegisterLocales $event)
    {
        $event->addTranslations('en', __DIR__.'/../../locale/en.yml');
        $locale = app('Flarum\Core\Settings\SettingsRepository')->get('default_locale');
        $path = __DIR__.'/../../locale/'.$locale;
        if (file_exists($path.'.yml')) {
            $event->addTranslations($locale, $path.'.yml');
        } else {
            $event->addTranslations($locale, __DIR__.'/../../locale/en.yml');
        }
    }
```
Doing good I, inherited after the core logic of the default language, States website managers do not have to localize added general extension module from the market at a time, and modify the file extensions, simply as a module in the locale folder, add the localization file you need. Truly multilingual, upgrades to worry about.
Hope can be adopted by the development group.
给扩展的本地化建议
我来说下这么做的好处，采用继承核心默认语言的逻辑后，各国的网站管理人员不用为本地化每次新增来自市场的通用扩展模块，而修改扩展模块的文件，只需要为模块在locale文件夹中添加所需要的本地化文件即可。真正做到多语言，实现升级无忧。
希望能被开发组采纳。

Has been merged into my Github project: https://github.com/mokecc/Flarum-zh_CN
Also has been running on my site: http://f.szlt.net
目前已经合并到我的Github项目中：https://github.com/mokecc/Flarum-zh_CN
同时也已在我的网站正常运行：http://f.szlt.net/

**Comment by tobscure** [comment]
We **strongly discourage overwriting Flarum's core files.** It makes it a huge pain in the ass to upgrade, which is exactly what we're trying to avoid with the extensions system.

To make a language pack, you should make an extension which contains and registers your locale files. See the [Packaging](http://flarum.org/docs/extend/packaging) and [Localization](http://flarum.org/docs/extend/localization) docs for more info.

We are aware that this process is currently too difficult for non-developers, and will work to make it simpler and better documented. Please be patient.
