### ISSUE TITLE
"Start a discussion" button is cutted

### ISSUE THREAD

**Issue by Petrouchka** [flarum/core#349]
When you show tags on 3 colomns instead of two (on a large screen), the "Start a discussion" button is cut at its right side.
![capture-forum de discussion logiciels libres - mozilla firefox](https://cloud.githubusercontent.com/assets/3955499/9563770/93e2da80-4e8f-11e5-8609-76ee55decd46.png)

**Comment by Petrouchka** [comment]
The size of the button is correct when I uncheck "width 100%" :
![capture-forum de discussion logiciels libres - mozilla firefox](https://cloud.githubusercontent.com/assets/3955499/9567337/30ee27f2-4f27-11e5-8314-d8c08b85f0e2.png)

**Comment by dcsjapan** [comment]
The "Log In to Reply" button seems to be affected as well:

http://discuss.flarum.org/d/672-polish-language-extension/11

**Comment by maelsoucaze** [comment]
For information, the *"Send Password Reset Email"* button is also affected (especially when it's translated *"Envoyer le courriel de réinitialisation du mot de passe""*, I should reduce it!).
