### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by DavertMik** [flarum/core#35]
Hi, I'm lead developer of Codeception testing framework.

I feel your project is really promising. I'm also fan of EmberJS )
If you have any questions on testing with Codeception (I see you already bootstrapped it) or on testing with Ember (which I do for my project as well), please contact me in twitter @davert or directly in Skype: `davert.ua`.

I hope I can help and long live to flarum!

**Comment by tobscure** [comment]
Thanks @DavertMik! I've just gotten the redesign to a good stage so I think the next thing I'll focus is testing. Will let you know if I have any trouble!
