### ISSUE TITLE
Setting the Moment locale correctly

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#350]
As reported in #345, changing the locale doesn't affect strings translated by Moment.js.

I've had similar problems in another project recently, so I know what needs to be done, but not quite how to do it best:
- When the page is loaded, call `moment.locale()` with the locale currently in use. (That should be enough since we reload the page after selecting another locale if I read the code right.) We should probably set the locale in the HTML tag, too.
- The locale files for Moment.js need to be loaded; a whole lot of them are available in their Bower component, but they need to be loaded / merged into the assets explicitly. I suggest simply loading all Moment.js locale definitions that are installed in Flarum (since they're not that big).

Relevant Moment.js docs: http://momentjs.com/docs/#/i18n/

**Comment by tobscure** [comment]
No, nothing needs to be done here (apart from documentation). Locales can include a complete Moment.js locale definition in their config.js, exactly like the one on the docs you linked.

```
moment.locale('fr', {
    months : "janvier_février_mars_avril_mai_juin_juillet_août_septembre_octobre_novembre_décembre".split("_"),
    monthsShort : "janv._févr._mars_avr._mai_juin_juil._août_sept._oct._nov._déc.".split("_"),
    // etc.
```

**Comment by maxyc** [comment]
where it in flarum?
