### ISSUE TITLE
Can't delete a discussion

### ISSUE THREAD

**Issue by Petrouchka** [flarum/core#352]
I created a new discussion as administrator and I can't delete it :
"Oops! Something went wrong on the server. Please reload the page and try again."

**Comment by franzliedke** [comment]
Please use your browser console to tell us about the full error message (which is returned by the AJAX call when that error appears).

**Comment by Petrouchka** [comment]
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. forum-yp8De41zcAyCxYrv.css:4:716
Unknown pseudo-class or pseudo-element '-webkit-inner-spin-button'.  Ruleset ignored due to bad selector. forum-yp8De41zcAyCxYrv.css:4:23379
Unknown pseudo-class or pseudo-element '-webkit-search-cancel-button'.  Ruleset ignored due to bad selector. forum-yp8De41zcAyCxYrv.css:4:23624
Unknown property 'user-select'.  Declaration dropped. forum-yp8De41zcAyCxYrv.css:4:36329
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector. forum-yp8De41zcAyCxYrv.css:4:45904
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. forum-yp8De41zcAyCxYrv.css:4:45955
Error in parsing value for 'cursor'.  Declaration dropped. forum-yp8De41zcAyCxYrv.css:4:46148
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. forum-yp8De41zcAyCxYrv.css:4:51363
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. forum-yp8De41zcAyCxYrv.css:4:65112
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector. forum-yp8De41zcAyCxYrv.css:4:82492
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. forum-yp8De41zcAyCxYrv.css:4:82578
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector. forum-yp8De41zcAyCxYrv.css:4:85081
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. forum-yp8De41zcAyCxYrv.css:4:85156
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. forum-yp8De41zcAyCxYrv.css:4:88945
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. forum-yp8De41zcAyCxYrv.css:4:95198
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create forum-VlRSR1XbZYXsQ7u6.js:1:319
DELETE 
XHR 
http://www.numopen.fr/discussions/api/discussions/1

**Comment by Petrouchka** [comment]
What is the server pusherapp.com ?

**Comment by franzliedke** [comment]
Please go to the "Network" tab instead of "Console", find the failing request, and paste its response.

**Comment by tobscure** [comment]
@petrouchka Pusher is a third-party service currently required for the Pusher extension to work. Disable that extension to stop those requests.

**Comment by Petrouchka** [comment]
![capture-forum de discussion logiciels libres - mozilla firefox](https://cloud.githubusercontent.com/assets/3955499/9566088/24a5d4a4-4ef5-11e5-9d58-d28bc65ec23d.png)

**Comment by tobscure** [comment]
@Petrouchka can you click on the request and then paste the contents of the "Response" tab?

**Comment by Petrouchka** [comment]
Like this ?

![capture-forum de discussion logiciels libres - mozilla firefox](https://cloud.githubusercontent.com/assets/3955499/9582797/df81dd14-5007-11e5-83df-7478ff50809f.png)

**Comment by franzliedke** [comment]
We're almost there - please click on the "Réponse" tab on the right half of the screen.

**Comment by Petrouchka** [comment]
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /discussions/api/discussions/1
on this server.<br />
</p>
</body></html>

**Comment by franzliedke** [comment]
Your server seems to have a problem with www.numopen.fr vs. numopen.fr. Please do the following:
- configure your server to use only one URL (which also prevents SEO penalties for duplicate content), either with or without www, always redirect from one to the other
- configure Flarum's base URL (in config.php) accordingly

**Comment by Petrouchka** [comment]
Wow, what a bug !

The DNS contains :
www.numopen.fr.	14400	IN	CNAME	numopen.fr

config.php contains :
'url' => 'http://www.numopen.fr/discussions',

I changed it :
'url' => 'http://www.numopen.fr/discussions',
and now, it works, thank you.

Is it possible to prevent this in the future in an automatic installation script or with using server variables ?

**Comment by Petrouchka** [comment]
But now, I've got some strange UTF8 letters :

![capture-forum de discussion logiciels libres - mozilla firefox-1](https://cloud.githubusercontent.com/assets/3955499/9590070/b684e0a2-5032-11e5-9745-241cceb9497a.png)

**Comment by franzliedke** [comment]
Please post about your new problem on the forum, more people can help there.

**Comment by Petrouchka** [comment]
Sorry, it was a mistake. I always have the same error and can't delete a discussion.

**Comment by Petrouchka** [comment]
The discussion I try to delete disappears but appears again if I reload the page.

**Comment by Petrouchka** [comment]
Do you want to access to my site to test ?

**Comment by Petrouchka** [comment]
Mainly all of my suggestions and bug reports have been closed without discussions or solutions. Sometimes, I must post here, another time on forum etc.
I'm tired of posted, I stop it.

**Comment by franzliedke** [comment]
> Mainly all of my suggestions and bug reports have been closed without discussions or solutions. 

You have made many duplicate posts, here and on the forums. Please help us by keeping discussion in one place, and keeping the noise level down. :)
