### ISSUE TITLE
Include URL rewrite setup instructions in installer

### ISSUE THREAD

**Issue by tobscure** [flarum/core#357]
Before we present the installation details form, we should have a screen which guides the user through setting up URL rewriting (after detecting what web server they're using). It should include:

- Apache: make sure .htaccess is present, make sure `AllowOverride` rule is enabled (contact host if problems). Allow this step to be skipped.
- Nginx: add stuff to config and restart the server
- Lighttpd: add stuff to config and restart the server

**Comment by franzliedke** [comment]
Hmm, I think I'd prefer the default to be PATH_INFO-based (once that works), because that works without any extra instructions. And keep the rest in the documentation...

Are you okay with that?

**Comment by tobscure** [comment]
For Apache, I suppose that makes sense. But for Nginx, some config is going to be required because PATH_INFO doesn't work out of the box? Not sure about Lighttpd.

**Comment by franzliedke** [comment]
Ah yes, good point.

**Comment by franzliedke** [comment]
Hmm, isn't that configuration needed to run the web-based installer in the first place?

**Comment by tobscure** [comment]
No, the request to the installer doesn't have a path (it's the root URL) so isn't affected by URL rewriting setup.

**Comment by franzliedke** [comment]
Well, but you still need to set up a virtual host config for Nginx, right?

**Comment by tobscure** [comment]
Yeah that's true. Good point.

**Comment by tobscure** [comment]
Let's scratch this then.
