### ISSUE TITLE
Prevent duplicate content

### ISSUE THREAD

**Issue by AngelGL** [flarum/core#358]
When you go to the profile page and the user name begin with a Uppercase letter, the URL don't redirect to a lowercase url like in single post topic. I guess that is duplicated content because you have to redirect or use canonical tag.

Example of what I'm talking about:

http://discuss.flarum.org/u/Franz
http://discuss.flarum.org/u/franz

Differents urls, but the same content.

**Comment by franzliedke** [comment]
So this comes down to preventing duplicate content. Yes, we'll probably use canonical meta tags...
Thanks for bringing it up! :)

**Comment by aethior** [comment]
Related with urls, usernames and consistency... Why Flarum use all urls (discussions, tags...) in lowercase except the user profile url? To be honest, I prefer all url in lowercase but I understand that it's a personal preference.

**Comment by franzliedke** [comment]
We should probably use rel=prev, next etc. for paginated content...

**Comment by askvortsov1** [comment]
Looks like the canonical meta tag was added in https://github.com/flarum/core/pull/1901. Proper urls for pagination still need to be done, but that's a different issue.
