### ISSUE TITLE
Login window closes

### ISSUE THREAD

**Issue by Petrouchka** [flarum/core#363]
When I want to log in, the window for authentication always closes if I click outside it and I need to write again my password and email.
It would be better if the window stay here until we are logged. Anyway, we can close it with the cross in the upper right corner.
![capture-forum de discussion logiciels libres - mozilla firefox-1](https://cloud.githubusercontent.com/assets/3955499/9566468/bc154d40-4f06-11e5-8458-eb42611df9d5.png)

**Comment by tobscure** [comment]
Just to clarify, your issue is that clicking on the blue background surrounding the dialog closes the dialog?

**Comment by Petrouchka** [comment]
Yes, exactly. It closes the dialog box and I loose what I writed.

**Comment by tobscure** [comment]
This is intentional (as a quick way to close the dialog) but perhaps for dialogs with text inputs we should disable it. @franzliedke what do you think?

**Comment by Petrouchka** [comment]
The dialog automatically closes once logged. No need to close it during authentication.

**Comment by franzliedke** [comment]
I don't quite understand why an action triggered by a click is a problem when typing. Or are you on a laptop and accidentally touching the trackpad?

In any case, I'd only vote for this change if we were to add a keyboard shortcut ("Escape" button) as an easy alternative for closing the modal.

**Comment by Petrouchka** [comment]
Yes, like in WordPress : http://www.goall.fr/wp-login.php

**Comment by tobscure** [comment]
@franzliedke Escape shortcut is already implemented :)

**Comment by tobscure** [comment]
Actually, I think I'm against changing this. Clicking the background is a really *convenient* way to close the modal, form or not. Just don't click it if you don't want it to close.

**Comment by tarunmarkose** [comment]
+1 for keeping it how it is..  its a big improvement to UX. I can click on
a large area anywhere when the intention is to dismiss a modal.
