### ISSUE TITLE
Word "Forum"

### ISSUE THREAD

**Issue by Petrouchka** [flarum/core#365]
Flarum (flat forum?) is a new version of old PHP forums but now, it's more a flat discussions software than a forum. Why use the word "Forum" now (for example "search forum")?
Discourse doesn't use longer the word Forum but the word "Discussions" ("search in discussions"). It is simpler to understand for people who discover software.

**Comment by franzliedke** [comment]
I think we're pretty happy with the term at this time. 

The forums are probably a better place to discuss this, since others can chime in if they share your opinion.
