### ISSUE TITLE
[Mentions] Mention link on preview bug

### ISSUE THREAD

**Issue by aolko** [flarum/core#367]
If you click mention link on the preview of your post 
![](http://i.imgur.com/UCQMxky.png)
you'll get this:
![](http://i.imgur.com/WYyl0Eo.png)

**Comment by s9e** [comment]
@aolko Looking at the code, it's more an unimplemented feature than a bug.

The correct way to fix/implement it would be to have a JavaScript function that returns the discussionid/number values for a given id, but in the meantime the simplest fix is to only specify an `href` if the mention has a value for `discussionid` and `number`.

```xsl
<a class="PostMention" data-id="{@id}"><xsl:if test="@discussionid and @number"><xsl:attribute name="href">/d/<xsl:value-of select="@discussionid"/>/<xsl:value-of select="@number"/></xsl:attribute></xsl:if><xsl:value-of select="@username"/></a>
```

**Comment by aolko** [comment]
@s9e point me to the exact file

**Comment by s9e** [comment]
`flarum/extensions/mentions/src/Listeners/AddPostMentionsFormatter.php`

The PHP method is `addId()` and it would require a similar JavaScript function for it to work in preview.

**Comment by aolko** [comment]
same

**Comment by aolko** [comment]
Needs fix,
a new bug - writing /u/ and d/d w/o arguments produces an error page

**Comment by tobscure** [comment]
@s9e how/where would I implement the JavaScript version of the `addId` function exactly?

**Comment by s9e** [comment]
@aolko That's because you need to clear the PHP cache.

@tobscure You'll need the JavaScript equivalent to `CommentPost::find()` that you'll use in the JavaScript equivalent to `addId()`. Note that this example uses the bracket notation to access userland objects' properties because of Closure Compiler.

```php
$js = "
	function (tag)
	{
		var post = CommentPost['find'](tag.getAttribute('id'));

		if (post) {
			tag.setAttribute('discussionid', post['discussion_id']);
			tag.setAttribute('number', post['number']);

			return true;
		}
	}
";

$tag->filterChain
	->prepend([static::class, 'addId'])
	->setJS($js);
```

**Comment by aolko** [comment]
@JoshyPHP 
yeah sure why not
````
Flarum\Http\RouteNotFoundException thrown with message ""

Stacktrace:
#14 Flarum\Http\RouteNotFoundException in /home/admin/web/temp.legionlabs.cf/public_html/flarum/vendor/flarum/core/src/Http/RouterMiddleware.php:60
#13 Flarum\Http\RouterMiddleware:__invoke in <#unknown>:0
#12 call_user_func in /home/admin/web/temp.legionlabs.cf/public_html/flarum/vendor/zendframework/zend-stratigility/src/Dispatch.php:79
#11 Zend\Stratigility\Dispatch:__invoke in /home/admin/web/temp.legionlabs.cf/public_html/flarum/vendor/zendframework/zend-stratigility/src/Next.php:111
#10 Zend\Stratigility\Next:__invoke in /home/admin/web/temp.legionlabs.cf/public_html/flarum/vendor/flarum/core/src/Api/Middleware/ReadJsonParameters.php:32
#9 Flarum\Api\Middleware\ReadJsonParameters:__invoke in <#unknown>:0
#8 call_user_func in /home/admin/web/temp.legionlabs.cf/public_html/flarum/vendor/zendframework/zend-stratigility/src/Dispatch.php:79
#7 Zend\Stratigility\Dispatch:__invoke in /home/admin/web/temp.legionlabs.cf/public_html/flarum/vendor/zendframework/zend-stratigility/src/Next.php:111
#6 Zend\Stratigility\Next:__invoke in /home/admin/web/temp.legionlabs.cf/public_html/flarum/vendor/flarum/core/src/Forum/Middleware/LoginWithCookie.php:47
#5 Flarum\Forum\Middleware\LoginWithCookie:__invoke in <#unknown>:0
#4 call_user_func in /home/admin/web/temp.legionlabs.cf/public_html/flarum/vendor/zendframework/zend-stratigility/src/Dispatch.php:79
#3 Zend\Stratigility\Dispatch:__invoke in /home/admin/web/temp.legionlabs.cf/public_html/flarum/vendor/zendframework/zend-stratigility/src/Next.php:111
#2 Zend\Stratigility\Next:__invoke in /home/admin/web/temp.legionlabs.cf/public_html/flarum/vendor/zendframework/zend-stratigility/src/MiddlewarePipe.php:76
#1 Zend\Stratigility\MiddlewarePipe:__invoke in /home/admin/web/temp.legionlabs.cf/public_html/flarum/vendor/zendframework/zend-diactoros/src/Server.php:166
#0 Zend\Diactoros\Server:listen in /home/admin/web/temp.legionlabs.cf/public_html/index.php:60
````

**Comment by tobscure** [comment]
@aolko /u/ and /d/ without a username/discussion ID returning a 404 is not a bug, it's the intended behaviour.

**Comment by aolko** [comment]
Then it should return a 404 page, not a stacktrace
1 сент. 2015 г. 1:38 AM пользователь "Toby Zerner" <notifications@github.com>
написал:

**Comment by tobscure** [comment]
It does. Set debug to false in config.php to disable the stacktraces.

**Comment by datitisev** [comment]
This was fixed/implemented at some point - clicking on the mention now does bring the user to the user, though with a page reload (and not jumping to it in standard Flarum fashion).
