### ISSUE TITLE
XSS on banner

### ISSUE THREAD

**Issue by aolko** [flarum/core#373]
![](http://i.imgur.com/NbUTLDg.png)
![](http://i.imgur.com/1skFuCp.png)

## filter all the fields!!!

**Comment by tobscure** [comment]
No need for Welcome Banner input to be filtered because only admins can set it.

**Comment by Fastidious** [comment]
@tobscure the same would apply to "-30 days," yet it should not be. Wouldn't you agree that it is good practice, either way?

**Comment by tobscure** [comment]
-30 days is different.

In the case of a welcome banner, we want to allow for HTML so the admin can put whatever they want in there. We're letting them define a template.
