### ISSUE TITLE
[Idea] Auto-Updater for flarum core and it's extensions

### ISSUE THREAD

**Issue by kantholy** [flarum/core#379]
* allow the Flarum app (core + extension) to register Update URLs to it's backend
* for example: json file with version information including a "downloadUrl" parameter to a zip-file
* check those urls for updates a regular basis (cronjob?)
* if the version string is unequal the current installed version...
* download the zip file and extract it to the relevant directory (php zip extension required)

*auto updater should be optional and only activated if supported on the server*

**Comment by tobscure** [comment]
Yes, this is a long-term goal. I'm going to close this because it's not something that's actionable right now.
