### ISSUE TITLE
Flarun on share hosting

### ISSUE THREAD

**Issue by Collizo4sky** [flarum/core#38]
I know its build on Laravel.. is there a chance/way flarum can be installed on a shared-hosting?

**Comment by pedrommone** [comment]
If you have SSH access you can install.

**Comment by tobscure** [comment]
It'll be a goal in the long-term to allow easy drag/drop installation on shared hosting without the need for ssh. But not right now during early dev.

**Comment by SebSept** [comment]
Hi,

Any laravel app can stand on as shared hosting, just compil before push, push the vendor dir (without the dev dependencies). That's done.
You just can.t run artisan or migration but You can have it running. I did it (not with flarum).
