### ISSUE TITLE
Prefix migration/table names

### ISSUE THREAD

**Issue by FBI23** [flarum/core#380]
Prefixing of migration names could be used to prevent table-name clashes in Laravel projects that share a DB. For example, the users table/migration is common in Laravel projects. Perhaps prefixing flarum migrations/tables as i.e. 'flarum_users' would solve this clash, especially in existing laravel projects?

**Comment by franzliedke** [comment]
Already done. We will release a new beta version this week which contains the changes that actually make the feature work ;)
