### ISSUE TITLE
Edit post on mobile (Chrome) never saves

### ISSUE THREAD

**Issue by henhouse** [flarum/core#382]
I've experienced this issue twice. The first time someone replied to the thread and I assumed it simply had just "locked" me out of being able to edit my post since the option had then disappeared.

However, it happened to me again today. Essentially whenever I edit a post I just made on mobile, it never processes and I am stuck at this screen endlessly: 
![9ifia49](https://cloud.githubusercontent.com/assets/30731/9580706/fdea6e2c-4fc8-11e5-9169-54bd32a4a5c4.png)

**Comment by tobscure** [comment]
Does it happen on Safari? Can you please [remotely debug it](http://moduscreate.com/enable-remote-web-inspector-in-ios-6/)?

**Comment by tobscure** [comment]
@henhouse? :)
