### ISSUE TITLE
Custom Homepage breaks forum

### ISSUE THREAD

**Issue by OneLostHero** [flarum/core#383]
Custom homepage of any kind breaks the forums.

**Comment by franzliedke** [comment]
You need to provide much more detail...

**Comment by tobscure** [comment]
See http://flarum.org/docs/contributing for information on how to report bugs effectively.

I'm assuming this is a duplicate of #243, in which case you'll need to provide some kind of counterargument to my dismissal.

**Comment by OneLostHero** [comment]
i selected custom, and changed my url to www.shadowedrealms.tk and when i went back into the forum i had an error. so i typed to url back to the admin board and tried http://www.shadowedrealms.tk and it still failed. I even tried shadowedrealms.tk and still had nothing. 
I hope i have provided enough information

**Comment by tobscure** [comment]
That box isn't to put a full URL in. It's for a path relative to your base URL. So for example, the default value is `/all` (all discussions). Another value would be `/tags` to show the tags page.

**Comment by OneLostHero** [comment]
So its not to take you back to the homepage you used to arrive at the forum then?

**Comment by tobscure** [comment]
Nope.
