### ISSUE TITLE
Can't Authenticate (Write or Make Changes) with CGI Wrap

### ISSUE THREAD

**Issue by jonhenshaw** [flarum/core#384]
For those who cannot easily upgrade their core PHP version on a shared or managed server, hosting providers like Pair allow running a newer version as a cgi wrapper. If they're doing this, there are problems with Authorization. Specifically, _nothing_ will be able to be written or saved. The following fixed this problem, and assuming it will work with other hosting environments other than Pair Networks, this should be added to the core files, even if they're commented out by default.

1) Added this to **.htaccess**

`RewriteEngine on`
`RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]`

2) Added this to **config.php**

`$_SERVER['HTTP_AUTHORIZATION'] = $_SERVER['REDIRECT_HTTP_AUTHORIZATION'];`

Those two things made everything work with the cgi wrapper.

**Comment by franzliedke** [comment]
Can you explain (as detailed as possible) what exactly this change does?

**Comment by jonhenshaw** [comment]
I didn't come up with the fix or write it. Apparently "Authorization" doesn't work when you run PHP with a CGI wrapper. This enables it to work. The issue is related to [this](http://stackoverflow.com/questions/13387516/authorization-header-missing-in-django-rest-framework-is-apache-to-blame/30310338#30310338).

I ended up having my hosting provider upgrade my version of PHP to 5.6.x and was able to remove the code and have everything work fine. My concern is for those who can't upgrade their server code and can only run newer versions (5.5 and above) of PHP via CGI wrapper.

Perhaps one of the other contributors/authors of Flarum understands more about how **Authorization** works with Flarum and what this fix actually does.

**Comment by tobscure** [comment]
Flarum's API uses the Authorization header (with a token) to authorize requests. From what you're saying, it seems that using a CGI wrapper prevents the Authorization header from being passed to PHP correctly – namely, it's set to `$_SERVER['REDIRECT_HTTP_AUTHORIZATION']` instead of `$_SERVER['HTTP_AUTHORIZATION']`.

We already have that line in the packaged .htaccess file, so we would only need to add the second thing. I think putting it in bootstrap.php would be appropriate.

**Comment by jonhenshaw** [comment]
Sounds good to me. Thanks @tobscure

**Comment by franzliedke** [comment]
Hmm, how about a middleware instead? That way, we don't need the extra line in .htaccess (and configuration files for other server types). Or am I missing something?

**Comment by larsblockken** [comment]
When using mod_fastcgi the  "-pass-header" parameter in the fastcgi configuration would handle this behaviour. Hardcoding an Authorization header doesn't seem like a best practice to me. It also appears to be related to your hosting provider not setting the right parameters and not immediately related to Flarum. These are just my 2 cents.

**Comment by franzliedke** [comment]
While I'm inclined to agree with @larsblockken, I just pushed a possible solution to this issue. Please check out [this commit](https://github.com/flarum/core/commit/685d5f151793544a433d5f027f3dc87e80ec702f).

What do y'all think?

**Comment by Luceos** [comment]
This suits our needs for now. We can always adapt it based on user feedback before the stable release..

**Comment by tobscure** [comment]
Looks good to me!

**Comment by franzliedke** [comment]
Well, the point is that apparently this *can* be solved on the server admin level without having to change the application code, by adding this:

    FastCgiServer filename -pass-header Authorization

See [this documentation link](http://webcache.googleusercontent.com/search?q=cache:vWM2H6rg5REJ:www.fastcgi.com/mod_fastcgi/docs/mod_fastcgi.html+&cd=8&hl=en&ct=clnk&gl=kr) (it's a Google cache link unfortunately, the real website seems to be down).

**Comment by franzliedke** [comment]
Also see the non-accepted answers on [this StackOverflow thread](http://stackoverflow.com/questions/13387516/authorization-header-missing-in-django-rest-framework-is-apache-to-blame/30310338#30310338).

**Comment by franzliedke** [comment]
@jonhenshaw Does the answer from [this StackOverflow question](http://stackoverflow.com/questions/17018586/apache-2-4-php-fpm-and-authorization-headers) do the trick for you?

**Comment by jonhenshaw** [comment]
Beats me. I stopped testing/using Flarum after it was decided to require Composer to install on the server. As soon as there's a simpler way to install (e.g. WordPress), I'll let you know.

**Comment by franzliedke** [comment]
Okay, I've [reverted the commit](https://github.com/flarum/core/commit/4fe7acfddf093f399c7ac2bfc70693e0ea1c9f73). I'll send a pull request to [Zend Diactoros](https://github.com/zendframework/zend-diactoros/issues/164) instead.

**Comment by franzliedke** [comment]
Jay, my [pull request](https://github.com/zendframework/zend-diactoros/pull/165) has been accepted. :)
