### ISSUE TITLE
Mobile registration

### ISSUE THREAD

**Issue by OneLostHero** [flarum/core#385]
From a mobile device there is no way to register for the forum.

Update: By clicking on a post, and clicking reply to post, you can register. But still not easy for non tech savy people.

Update: There is not a notification describing the requirements for a user name, or why the username was rejected

**Comment by OneLostHero** [comment]
Update: By clicking on a post, and clicking reply to post, you can register. But still not easy for non tech savy peple.

**Comment by tobscure** [comment]
From the [docs](http://flarum.org/docs/contributing/):

> If you find a bug, we’d like to know about it! Remember that the goal of a bug report is to make it easy for us to replicate the bug and develop a fix. Therefore, you should include as much relevant information as possible, and communicate it in a clear, factual way. [This article](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) is a great resource on how to report bugs effectively.

Please be more specific.

If you click on the hamburger menu button (top-left), you should be able to touch "Sign Up" in the menu.

The lack of username validation message is a known issue covered by #267.
