### ISSUE TITLE
Safari installation issue

### ISSUE THREAD

**Issue by poush** [flarum/core#386]
Well first the issue is when i completed my installation on my mac with safari. I ended up having url of my installation as : 
  'url' => 'http://flarum.dev/?forumTitle=Something&mysqlHost=localhost&mysqlUsername=root&mysqlPassword=root&mysqlDatabase=flarum&adminUsername=admin&adminEmail=poush12%40gmail.com&adminPassword=password',

<img width="1108" alt="screen shot 2015-08-31 at 11 00 15 pm" src="https://cloud.githubusercontent.com/assets/1812082/9585535/39746300-5035-11e5-81cb-a71e85d8be99.png">

But everything is fine with installation on doing with chrome instead of safari. I did this installation 2-3 times with safari to ensure there wasn't my fault before but every time i ended up with this

**Comment by franzliedke** [comment]
Seems to be a Safari bug.

Please apply commit 5783dbe77b6ae092cec5ac5b1081ff14f50ea73d and tell us whether this fixes the problem for you.

**Comment by tobscure** [comment]
@poush If that fix doesn't work, can you please open Safari's JavaScript console (Preferences > Advanced > Show Develop in menu bar, then Develop > Show Error Console), reload the page, and report any errors that appear when the page loads or when you submit the form?

**Comment by poush** [comment]
Don't know what's the reason but i just tried it again with fresh installation and everything worked ! Installation gone successful ! And yea even without applying that commit. Now my url is fine to "flarum,dev"

**Comment by poush** [comment]
@tobscure there were no errors in console except that of System reference on doing those installation last night
