### ISSUE TITLE
[Tags] Accommodate long tag names

### ISSUE THREAD

**Issue by tobscure** [flarum/core#391]
See https://spytajsie.com/tags

We need to overflow stuff properly.

**Comment by darkspotinthecorner** [comment]
Sugestion:
* Touch device: Fixed height & width containers, expand the list horizontally (with scrolling) including some visual indicator.
* Pointer device: Don't overflow, let the boxes expand.

**Comment by franzliedke** [comment]
Same thing for [tag titles](https://github.com/flarum/core/issues/505).

**Comment by tobscure** [comment]
The sidebar issue is fixed, tag tiles can be handled in #613
