### ISSUE TITLE
[Tags] No validation on tag slugs to make sure they're unique

### ISSUE THREAD

**Issue by tobscure** [flarum/core#393]
You can create two tags with the same slug. The second one is impossible to view.

**Comment by dcsjapan** [comment]
On a related topic:

It's possible to have two tags with the same name but different content by changing the slugs:

1. Create one "i18n" tag and change the slug to dev-i18n, then move under "Dev" ...
2. Create another one and change the slug to support-i18n, then move under "Support" ...

It might be nice if the tags extension could just add the prefix automatically when the tag is moved under the primary. This would be convenient, but could add a bit of complexity. The extension would need to be able to remove and replace prefixes if the tag is moved again.

**Comment by Luceos** [comment]
One problem with this validation rule I've experienced it that (if it is build that way) triggers an error when updating. Because the slug already exists in the table (itself).. This is the reason why (at work) we implemented dynamic rules that inserted the id if the model existed already... @franzliedke ?

**Comment by tobscure** [comment]
@Luceos Check out the Flarum\Core\Support\ValidatesBeforeSave trait's `expandUniqueRules` method - this should already be the case... if it's not working, there must be a bug there!

**Comment by Luceos** [comment]
Nice! Then this pr is safe to merge from my point of view.

**Comment by tobscure** [comment]
Merged, but we should still add a unique index to the slug column.

**Comment by tobscure** [comment]
Oops! Can you please actually test out your changes before PRing in the future? The rule actually caused a fatal error which I've fixed in 37ecc03dc724fa8cf846ae455596140e076468eb...

**Comment by Luceos** [comment]
As to the unique index.. [Documentation](http://laravel.com/docs/5.1/migrations#modifying-columns) explains that a new dependancy is needed to change columns (when running a new migration). Is that the best option, otherwise a simple edit of the original migration might prove sufficient.

**Comment by tobscure** [comment]
We've included that dependency in flarum/core. New migration :)

**Comment by tobscure** [comment]
You can use the `php flarum/flarum generate:migration --extension=tags --table=tags` command
