### ISSUE TITLE
Can't post when mentioning a user

### ISSUE THREAD

**Issue by yannickp4** [flarum/core#4005]
### Current Behavior

I'm unable to post a private conversation or post when I mention a user in it
![Screenshot 2024-07-05 103535](https://github.com/flarum/framework/assets/5711721/68f5955b-a48e-49e7-a23b-b2fd86ad66a5)
![Screenshot 2024-07-05 103419](https://github.com/flarum/framework/assets/5711721/301d7ceb-277f-487b-a908-647c108e59e1)

### Steps to Reproduce

1. Create a new post or private conversation
2. Write any text and mention someone using the "@" function
3. Select the user you want to mention
4. Submit/Post
5. You get a "Oops! Something went wrong. Please reload the page and try again." error

### Expected Behavior

That I can mention the user without errors

### Screenshots

![Screenshot 2024-07-05 103535](https://github.com/flarum/framework/assets/5711721/37bcdf9f-ec24-4265-8398-d6ef1b58074c)
![Screenshot 2024-07-05 103419](https://github.com/flarum/framework/assets/5711721/f755f506-fdad-4383-983f-487b65ad4d55)

### Environment

- Flarum version: 1.8.5
- Website URL: https://forum.synchestra.ai/public/
- Webserver: nginx
- Hosting environment: /
- PHP version: 8.3.9
- Browser: Chrome 126.0.6478.127

### Output of `php flarum info`

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

### Possible Solution

See the logs in the additional context section

### Additional Context

What I see in the logs:
[2024-07-05 07:33:44] flarum.ERROR: ArgumentCountError: Too few arguments to function Flarum\Mentions\ConfigureMentions::addUserId(), 1 passed and exactly 2 expected in forum.synchestra.ai/vendor/flarum/mentions/src/ConfigureMentions.php:96
Stack trace:
#0 [internal function]: Flarum\Mentions\ConfigureMentions::addUserId(Object(s9e\TextFormatter\Parser\Tag))
#1 forum.synchestra.ai/vendor/s9e/text-formatter/src/Parser/FilterProcessing.php(209): call_user_func_array('...', Array)
#2 forum.synchestra.ai/vendor/s9e/text-formatter/src/Parser/FilterProcessing.php(130): s9e\TextFormatter\Parser\FilterProcessing::executeFilter(Array, Array)
#3 forum.synchestra.ai/vendor/s9e/text-formatter/src/Parser.php(1441): s9e\TextFormatter\Parser\FilterProcessing::filterTag(Object(s9e\TextFormatter\Parser\Tag), Object(s9e\TextFormatter\Parser), Array, Array)
#4 forum.synchestra.ai/vendor/s9e/text-formatter/src/Parser.php(1396): s9e\TextFormatter\Parser->processStartTag(Object(s9e\TextFormatter\Parser\Tag))
#5 forum.synchestra.ai/vendor/s9e/text-formatter/src/Parser.php(1297): s9e\TextFormatter\Parser->processCurrentTag()
#6 forum.synchestra.ai/vendor/s9e/text-formatter/src/Parser.php(345): s9e\TextFormatter\Parser->processTags()
#7 forum.synchestra.ai/vendor/flarum/core/src/Formatter/Formatter.php(105): s9e\TextFormatter\Parser->parse('...')
#8 forum.synchestra.ai/vendor/flarum/core/src/Post/CommentPost.php(155): Flarum\Formatter\Formatter->parse('...', Object(Flarum\Post\CommentPost), Object(Flarum\User\User))
#9 forum.synchestra.ai/vendor/flarum/core/src/Post/CommentPost.php(61): Flarum\Post\CommentPost->setContentAttribute('...', Object(Flarum\User\User))
#10 forum.synchestra.ai/vendor/flarum/core/src/Post/Command/PostReplyHandler.php(84): Flarum\Post\CommentPost::reply(237, '...', 13, '...', Object(Flarum\User\User))
#11 forum.synchestra.ai/vendor/illuminate/bus/Dispatcher.php(122): Flarum\Post\Command\PostReplyHandler->handle(Object(Flarum\Post\Command\PostReply))
#12 forum.synchestra.ai/vendor/illuminate/pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Flarum\Post\Command\PostReply))
#13 forum.synchestra.ai/vendor/illuminate/pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Flarum\Post\Command\PostReply))
#14 forum.synchestra.ai/vendor/illuminate/bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 forum.synchestra.ai/vendor/illuminate/bus/Dispatcher.php(78): Illuminate\Bus\Dispatcher->dispatchNow(Object(Flarum\Post\Command\PostReply))
#16 forum.synchestra.ai/vendor/flarum/core/src/Discussion/Command/StartDiscussionHandler.php(81): Illuminate\Bus\Dispatcher->dispatch(Object(Flarum\Post\Command\PostReply))
#17 forum.synchestra.ai/vendor/illuminate/bus/Dispatcher.php(122): Flarum\Discussion\Command\StartDiscussionHandler->handle(Object(Flarum\Discussion\Command\StartDiscussion))
#18 forum.synchestra.ai/vendor/illuminate/pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Flarum\Discussion\Command\StartDiscussion))
#19 forum.synchestra.ai/vendor/illuminate/pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Flarum\Discussion\Command\StartDiscussion))
#20 forum.synchestra.ai/vendor/illuminate/bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 forum.synchestra.ai/vendor/illuminate/bus/Dispatcher.php(78): Illuminate\Bus\Dispatcher->dispatchNow(Object(Flarum\Discussion\Command\StartDiscussion))
#22 forum.synchestra.ai/vendor/flarum/core/src/Api/Controller/CreateDiscussionController.php(61): Illuminate\Bus\Dispatcher->dispatch(Object(Flarum\Discussion\Command\StartDiscussion))
#23 forum.synchestra.ai/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(116): Flarum\Api\Controller\CreateDiscussionController->data(Object(Laminas\Diactoros\ServerRequest), Object(Tobscure\JsonApi\Document))
#24 forum.synchestra.ai/vendor/flarum/core/src/Api/Controller/AbstractCreateController.php(22): Flarum\Api\Controller\AbstractSerializeController->handle(Object(Laminas\Diactoros\ServerRequest))
#25 forum.synchestra.ai/vendor/flarum/core/src/Http/RouteHandlerFactory.php(41): Flarum\Api\Controller\AbstractCreateController->handle(Object(Laminas\Diactoros\ServerRequest))
#26 forum.synchestra.ai/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}(Object(Laminas\Diactoros\ServerRequest), Array)
#27 forum.synchestra.ai/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ExecuteRoute->process(Object(Laminas\Diactoros\ServerRequest), Object(Closure))
#28 forum.synchestra.ai/vendor/flarum/core/src/Api/Middleware/ThrottleApi.php(33): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#29 forum.synchestra.ai/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Api\Middleware\ThrottleApi->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#30 forum.synchestra.ai/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(44): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#31 forum.synchestra.ai/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\CheckCsrfToken->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#32 forum.synchestra.ai/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(69): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#33 forum.synchestra.ai/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ResolveRoute->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#34 forum.synchestra.ai/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#35 forum.synchestra.ai/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\SetLocale->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#36 forum.synchestra.ai/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(58): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#37 forum.synchestra.ai/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\AuthenticateWithHeader->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#38 forum.synchestra.ai/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#39 forum.synchestra.ai/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\AuthenticateWithSession->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#40 forum.synchestra.ai/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#41 forum.synchestra.ai/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\RememberFromCookie->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#42 forum.synchestra.ai/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#43 forum.synchestra.ai/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\StartSession->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#44 forum.synchestra.ai/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#45 forum.synchestra.ai/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Api\Middleware\FakeHttpMethods->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#46 forum.synchestra.ai/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#47 forum.synchestra.ai/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ParseJsonBody->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#48 forum.synchestra.ai/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#49 forum.synchestra.ai/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\HandleErrors->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#50 forum.synchestra.ai/vendor/flarum/core/src/Http/Middleware/InjectActorReference.php(25): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#51 forum.synchestra.ai/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\InjectActorReference->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#52 forum.synchestra.ai/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#53 forum.synchestra.ai/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#54 forum.synchestra.ai/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\RequestHandler->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#55 forum.synchestra.ai/vendor/middlewares/base-path-router/src/BasePathRouter.php(99): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#56 forum.synchestra.ai/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\BasePathRouter->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#57 forum.synchestra.ai/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(36): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#58 forum.synchestra.ai/vendor/laminas/laminas-stratigility/src/Next.php(49): Laminas\Stratigility\Middleware\OriginalMessages->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#59 forum.synchestra.ai/vendor/middlewares/base-path/src/BasePath.php(73): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#60 forum.synchestra.ai/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\BasePath->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#61 forum.synchestra.ai/vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#62 forum.synchestra.ai/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ProcessIp->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#63 forum.synchestra.ai/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#64 forum.synchestra.ai/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(64): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\EmptyPipelineHandler))
#65 forum.synchestra.ai/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(73): Laminas\Stratigility\MiddlewarePipe->handle(Object(Laminas\Diactoros\ServerRequest))
#66 forum.synchestra.ai/vendor/flarum/core/src/Http/Server.php(45): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#67 forum.synchestra.ai/public/index.php(26): Flarum\Http\Server->listen()
#68 {main}

**Comment by luceos** [comment]
This is not a flarum core issue, but an extension. Please open a support discussion at Discuss that includes the output of `php flarum info`:

https://discuss.flarum.org/t/support
