### ISSUE TITLE
Auto login using iframe

### ISSUE THREAD

**Issue by venkatcerulean** [flarum/core#4017]
### Current Behavior

From my website (reactjs), I'm trying to use iframe and trying to login by default getting below error like
You have been inactive for so long
API getting cors and 405 error

### Steps to Reproduce

Direct login using third party(external website)

### Expected Behavior

Need to login default

### Screenshots

![flaurmerr](https://github.com/user-attachments/assets/78c0e852-8a5e-4940-9ba1-0bd7842c5f28)

### Environment

- Flarum version: x.y.z
- Website URL: http://example.com
- Webserver: [e.g. apache, nginx]
- Hosting environment: [e.g. shared, vps]
- PHP version: x.y.z
- Browser: [e.g. chrome 67, safari 11]

### Output of `php flarum info`

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

**Comment by luceos** [comment]
Stick to discuss for these kind of questions

https://discuss.flarum.org/d/35299

**Comment by venkatcerulean** [comment]
> Stick to discuss for these kind of questions

Why you closed the issue if there is no solution provided
