### ISSUE TITLE
Is this is the official wordpress plugin from Flarum?

### ISSUE THREAD

**Issue by mhsabbagh** [flarum/core#404]
Hello.

While I've been exploring the online wordpress plugins store, I've found this: https://wordpress.org/plugins/qdiscuss/ And I saw that it's very similar to Flarum (actually, 100% the same, without some features).

Are they part of this project or something?

**Comment by franzliedke** [comment]
Nope, it's a rip-off, basically.

Please keep discussions like these in the forums. :)
