### ISSUE TITLE
Administration basics section not working

### ISSUE THREAD

**Issue by SvenLie** [flarum/core#4063]
### Current Behavior

Basics section in administration backend is white and produces error in console:

```
Application.tsx:332 TypeError: Cannot read properties of undefined (reading 'view')
    at render.js:141:24
    at render.js:160:3
    at c (render.js:66:8)
    at l (render.js:50:5)
    at render.js:103:4
    at c (render.js:62:15)
    at l (render.js:50:5)
    at render.js:134:5
    at c (render.js:63:14)
    at l (render.js:50:5)
```

### Steps to Reproduce

1. Go to "Administration"
2. Go to "Basics"

### Expected Behavior

There should be the settings

### Environment

- Flarum version: 1.8.6
- Website URL: e.g. https://demo.flarum.site/admin#/basics
- Browser: Google Chrome 129.0.6668.100 macOS

**Comment by YUCLing** [comment]
Can you check if `1.8.7` works correctly?

**Comment by luceos** [comment]
Basics tab on demo works fine.
