### ISSUE TITLE
PDOException

### ISSUE THREAD

**Issue by Code-Name-Debian** [flarum/core#409]
Upon attempting a fresh install

[02-Sep-2015 05:35:33 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mickey_mouse.config' doesn't exist' in /public_html/flarum/vendor/illuminate/database/Connection.php:310
Stack trace:
#0 /public_html/flarum/vendor/illuminate/database/Connection.php(310): PDO->prepare('select `value`,...')
#1 /public_html/flarum/vendor/illuminate/database/Connection.php(629): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select `value`,...', Array)
#2 /public_html/flarum/vendor/illuminate/database/Connection.php(596): Illuminate\Database\Connection->runQueryCallback('select `value`,...', Array, Object(Closure))
#3 /public_html/flarum/vendor/illuminate/database/Connection.php(315): Illuminate\Database\Connection->run('select `value`,...', Array, Object(Closure))
#4 /public_html/flarum/vendor/illu in /public_html/flarum/vendor/illuminate/database/Connection.php on line 636

**Comment by Code-Name-Debian** [comment]
PHP Version 5.6.12

**Comment by franzliedke** [comment]
What did you do when this happened? It shouldn't happen when running the installer...

**Comment by Code-Name-Debian** [comment]
Ran the installer.  :-/

**Comment by franzliedke** [comment]
When exactly did the error occur? Did you still have an old config.php lying around? If so, please remove that...

**Comment by Code-Name-Debian** [comment]
Shouldn't have reference the two.  They were different installs on different php versions. ;-)

**Comment by franzliedke** [comment]
We haven't even established whether this is actually a Flarum bug ;)

**Comment by Code-Name-Debian** [comment]
Provided @tobscure login details via email (as well as some helpful stuff for the future)

**Comment by HLFH** [comment]
Same issue after signing up for the first time. https://github.com/flarum/core/issues/410

**Comment by ivangretsky** [comment]
Get the same error during fresh installation of Flarum on WIndows 10.
```
<br />
<b>Fatal error</b>:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db_pwsu-forum.settings' doesn't exist' in D:\xampp\htdocs\XYZ\vendor\illuminate\database\Connection.php:319
Stack trace:
#0 D:\xampp\htdocs\XYZ\vendor\illuminate\database\Connection.php(319): PDO-&gt;prepare('select `value`,...')
#1 D:\xampp\htdocs\XYZ\vendor\illuminate\database\Connection.php(655): Illuminate\Database\Connection-&gt;Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select `value`,...', Array)
#2 D:\xampp\htdocs\XYZ\vendor\illuminate\database\Connection.php(618): Illuminate\Database\Connection-&gt;runQueryCallback('select `value`,...', Array, Object(Closure))
#3 D:\xampp\htdocs\XYZ\vendor\illuminate\database\Connection.php(324): Illuminate\Database\Connection-&gt;run('select `value`,...', Array, Object(Closure))
#4 D:\xampp\htdocs\XYZ\vendor\illuminate\database\Query\Builder.php(1431): Illuminate\Database\Con in <b>D:\xampp\htdocs\processwire.su\vendor\illuminate\database\Connection.php</b> on line <b>662</b><br />
```

**Comment by luceos** [comment]
@ivangretsky please don't revive closed, ancient issues. Create an issue of you own and add all requested information from the template.
