### ISSUE TITLE
White page with link title

### ISSUE THREAD

**Issue by Code-Name-Debian** [flarum/core#410]
<img width="404" alt="capture" src="https://cloud.githubusercontent.com/assets/7545839/9624189/4b0d5e62-5118-11e5-81ef-c4fc6187cd38.PNG">

This is all that is seen after installing (using PHP Version 5.5.28)

**Comment by tobscure** [comment]
Let's keep all of the discussion for your issue in #409 :)

**Comment by Code-Name-Debian** [comment]
I'm not sure if you should reference the two or not... They were different install on different php versions.
