### ISSUE TITLE
Force rebuild of locale JavaScript when enabling/disabling extensions

### ISSUE THREAD

**Issue by tobscure** [flarum/core#412]
From http://discuss.flarum.org/d/749-more-information-on-setting-up-a-dev-environment/8

Also need to check that the forum's default locale still exists in case a language pack is turned off.

**Comment by Luceos** [comment]
and according to [this](http://flarum.org/docs/extend/localization/) we can do that by deleting the (admin|forum)-<locale>-*.js files in the assets directory
