### ISSUE TITLE
Mail confirm and reset password page button doesn't appear

### ISSUE THREAD

**Issue by salahineo** [flarum/core#4129]
### Current Behavior

The button in reset password page or mail confirmation page doesn't shown properly due to wrong CSS styles, so it will not appear for a normal user 

### Steps to Reproduce

1. Open reset password or confirm mail link
2. You will not be able to see the submit button 

### Expected Behavior

I should have a clear view of the button to click on it

### Screenshots

![image](https://github.com/user-attachments/assets/3fbe179e-a83e-4d47-a16e-ee74536f2e53)

### Environment

- Flarum version: 1.8.9
- Webserver: Nginx
- Hosting environment: VPS
- PHP version: 8.3
- Browser: Chrome LTS 

### Possible Solution

This CSS code can fix the issue:
button {
  color: #000;
  border: 1px solid #ccc;
  background: #f1f1f1;
}

**Comment by salahineo** [comment]
I investigated further and found the file responsible for this layout issue
![image](https://github.com/user-attachments/assets/c2e77e0c-2692-44b7-98b4-2ea48ae21914)

It seems this issue happened when the main color is #fff in the settings 
![image](https://github.com/user-attachments/assets/05844e17-d54a-42e5-a577-bc29903ddc18)

So I suggest setting the color property to be a variable also as the background, so they can sync together according to the user's choice of colors in the settings 

Thanks

**Comment by luceos** [comment]
We will need the output of `php flarum info`, thank you.

**Comment by salahineo** [comment]
@luceos Since this is not an issue anymore I will close it, just keep it in case there is someone has the same issue so he can know the color variables are the main issue here to change them
