### ISSUE TITLE
Translation system using gettext

### ISSUE THREAD

**Issue by neo22s** [flarum/core#415]
Hello,

Maybe I am wrong but I see you do not use gettext for translations?

There's many advantages on using native gettext for translations. We started with arrays and soon realize was an error. Gettext is faster more flexible and files are portable, perfect to redistribute to other translators.

**Comment by tobscure** [comment]
We use a custom infrastructure, simply because we have some pretty specialised requirements (portable between PHP/JS, complex pluralisation rules, genderization, and more). Translations are written in YAML, compiled into PHP and JSON, and then loaded into a custom Translator class.
