### ISSUE TITLE
nojs being set on slow connections

### ISSUE THREAD

**Issue by jenolan** [flarum/core#417]
This code in ```flarum/vendor/flarum/core/views/app.blade.php```
```javascript
        <script>
          try {
            var app = System.get('flarum/app').default;

            babelHelpers._extends(app, {!! json_encode($app) !!});

            @foreach ($bootstrappers as $bootstrapper)
              System.get('{{ $bootstrapper }}');
            @endforeach

            app.boot();
          } catch (e) {
            @if (! $forum->attributes->debug)
                window.location = window.location + '?nojs=1';
            @endif
            throw e;
          }
        </script>
```
Is timing out too quickly in slow links, at the moment from 0800-2300 my internet is restricted to 128kbs the [Flarum discussion area ](http://discuss.flarum.org) keeps saying I have an old browser, if I manage to be on in the non-blocked time it works fine most of the time but sometimes also clags up as I am on satellite and sometimes loading takes a while, think whatever is 'timing out' (I assume that's the trigger) needs to be loosened a bit for slower connections.

**Comment by jenolan** [comment]
After some digging the exception is at ```var app = System.get('flarum/app').default;``` message 'ReferenceError: System is not defined'

**Comment by tobscure** [comment]
That implies that your JavaScript hasn't been compiled correctly... Is this an installation you have compiled yourself (via git clone, gulp, etc.)?

**Comment by jenolan** [comment]
It is your site ie http://discuss.flarum.org/

**Comment by tobscure** [comment]
So there is no explicit timeout in Flarum, if the connection is dodgy then the browser might just be giving up in which case there's nothing we can do from our side.
