### ISSUE TITLE
[Tags] Selective Secondary Tags

### ISSUE THREAD

**Issue by jenolan** [flarum/core#421]
Been playing with tagging ... starting to get my head around using them instead of multiple levels of forum categories et al.

One thing though, in my case I have a main Tag 'Trainz' with subtags like 'Activity', 'Loco's' etc now what an Activity has as 'secondary differentiation is what version of Trainz it is who is the creator etc (see screen shot the three secondary tags shown only apply to the primary tag Trainz>Activity not to the others. So it would be nice to be able to assign secondary tags to primary tags selectively.

Sorry as per my other report can not read/post to the forum.

<img width="391" alt="screen shot 2015-09-04 at 12 15 14 pm" src="https://cloud.githubusercontent.com/assets/1505228/9675333/5ea80448-52ff-11e5-8b45-0b2281bdab6a.png">

**Comment by dcsjapan** [comment]
@jenolan Just to make sure that we're understanding you correctly:

Basically what you'd like to see is another level of nesting in the primaries. Is that correct?

**Comment by bmalex88** [comment]
Flarum uses tags to categorize posts. When I read tags I usually think about relevant keywords, not categories or sections containing posts, and I am sure more people do the same. Maybe tags should be renamed to sections. We can then focus on adding more options so users can customize their forum's structure and organization better. Tags should be just keywords that we can use for SEO or pointing out content type inside a pot (like, for example, a tag for video, image)

**Comment by tobyzerner** [comment]
Closing in favour of flarum/issue-archive#393
