### ISSUE TITLE
Migration class names could conflict

### ISSUE THREAD

**Issue by tobscure** [flarum/core#422]
It's not a problem right now, but it's one waiting to happen... if two extensions use a reasonably generic migration name, like the Tag extension's `SetDefaultSettings` migration, then they could clash when running the upgrade script.

Should we require all extension migration names to be prefixed with the name of the extension (e.g. `Tags_SetDefaultSettings`)?

**Comment by franzliedke** [comment]
Ah, this sucks. Can't we namespace them properly?

**Comment by tobscure** [comment]
Well, the migrator would somehow need to have knowledge of what the namespace is then (usually the class name is just derived from the filename). The only information it has is the extension name - so we could namespace by that, like `Tags\SetDefaultSettings`. That would be inconsistent with the namespaces of the extension's other classes though ... in the end, either way works, it's just semantics?
