### ISSUE TITLE
Featured image // Excerpt

### ISSUE THREAD

**Issue by jenolan** [flarum/core#423]
Obviously I am looking at moving from Wordpress for my stuff... Two of the things I like are;

'featured image' for a post. Ideally optional at admin / post level. Where enabled allow upload like the avatar and it appears on the first post in topic view and in the topic list on the main page.

'Excerpt' either manual [excerpt][/excerpt] or a 'peek' at the first topic to be shown on the main page.

**Comment by tobscure** [comment]
Extension.
