### ISSUE TITLE
Problems with the Admin option/Basics/Default Language

### ISSUE THREAD

**Issue by lcarlos-fokus** [flarum/core#429]
There are the following problems:
..When changed the option does not enable the Save Changes button
..After Refresh the page always comes back to the option English (en) even after being selected another Language

**Comment by Petrouchka** [comment]
+1

**Comment by Luceos** [comment]
Do you have other options in the dropdown? What language did you install additionally? This question is for both of you (@lcarlos-fokus and @petrouchka)

**Comment by franzliedke** [comment]
I cannot reproduce this, either.

Closing this until further information is provided. @lcarlos-fokus @Petrouchka 
(What browser are you using? Any error messages in the browser console?)
