### ISSUE TITLE
select-input styles broken on Firefox

### ISSUE THREAD

**Issue by tobscure** [flarum/core#43]
Styles are in ember/app/styles/flarum/components.less.

![image](https://cloud.githubusercontent.com/assets/128862/5929742/ac090b86-a6d6-11e4-943d-15bed62eb529.png)

**Comment by Robdel12** [comment]
Shameless plug :flushed:

Would you want to use something like Dropkick.js to style the selects?

**Comment by tobscure** [comment]
@Robdel12 Sorry, prefer to keep things simple + less dependencies :)

This seems to have mostly fixed itself in the latest Firefox. Just need to get rid of that ugly arrow: http://stackoverflow.com/questions/9620404/styling-a-select-element-in-firefox
