### ISSUE TITLE
[Lock] UI: Can follow/unfollow/ignore locked topics

### ISSUE THREAD

**Issue by Fastidious** [flarum/core#431]
If a topic is locked, there is no reason for the "No following/Following/Ignoring." Perhaps that option should be disabled as well, if topic is locked?

**Comment by franzliedke** [comment]
Makes sense. :+1:

**Comment by JoshyPHP** [comment]
There's no need to disable it and some people may have a legitimate use for it. For instance, in some forums people create a thread in anticipation of a contest or an event of sorts and keep it locked until the event begins. Readers may want to subscribe to or ignore that thread before it gets unlocked.

**Comment by Fastidious** [comment]
@JoshyPHP that is a very niche use case. Even in that case, I would just simply create the thread when the contest or event begins, why to create it before hand? Or create it an assign view access to the regular user group, so no comments are allowed (only read access), changing permissions at the time it is needed.

Up to @franzliedke and @tobscure, really. I only provide feedback from the user stand view.

**Comment by tobscure** [comment]
I personally use the follow feature to mark topics I need to reply to or otherwise take action on, so I often "follow" locked topics. 

There is nothing to gain from disabling the feature for locked topics, only *increased* complexity.

**Comment by franzliedke** [comment]
Totally agreed. Sometimes, announcement topics are locked (but admins can still reply).
