### ISSUE TITLE
[UI] Avatars getting chopped off

### ISSUE THREAD

**Issue by Fastidious** [flarum/core#432]
The avatars on topics and comments list are getting chopped off on the left side. The sample below is from comments list, but the same happens on topics list:

**Regular size**
![screen shot 2015-09-04 at 17 26 16](https://cloud.githubusercontent.com/assets/8352292/9694841/569370e6-532a-11e5-935b-013c0d8d6b98.png)

**Magnified**
![screen shot 2015-09-04 at 17 27 00](https://cloud.githubusercontent.com/assets/8352292/9694847/5ac46b52-532a-11e5-889a-8a8f52d20ff8.png)

Under Yosemite 10.10.5, Safari 8.0.8.

**Comment by DCSJAPAN** [comment]
Hmm ... I just tried taking a screenshot I'd done earlier, in which the avatars do seem truncated to me (about one pixels' worth) on the left, and magnified it to 1000x. The result is:

![2015-09-05 7 12 34](https://cloud.githubusercontent.com/assets/13129997/9695551/f8ff2500-539d-11e5-9343-61cb08892a02.png)

... Perfectly regular on both sides. I suspect what we're seeing is some sort of glitch in how Safari (or OS X) renders images.

**Comment by Fastidious** [comment]
I see your perfectly regular, and I up you with my irregular! Ha!

![screen shot 2015-09-04 at 18 21 26](https://cloud.githubusercontent.com/assets/8352292/9695633/c991438c-5331-11e5-916a-f6d5978c77ad.png)

**Comment by DCSJAPAN** [comment]
How are you magnifying it?

**Comment by Fastidious** [comment]
It seems it might be a Safari issue. Chrome renders it fine.

**Comment by tobscure** [comment]
Browser issue.
