### ISSUE TITLE
SEO URLs Faulty

### ISSUE THREAD

**Issue by jenolan** [flarum/core#433]
There is a discussion on [Flarum](http://discuss.flarum.org) currently ```http://discuss.flarum.org/d/855-Is%20this%20what%20it's%20like%20to%20develop%20a%20software?``` problem is if the 'nojs' is added you end up with ```http://discuss.flarum.org/d/855-Is%20this%20what%20it's%20like%20to%20develop%20a%20software??nojs=1?nojs=1``` replicating eternally.
The SEO slug should be .. 
  1. A-Za-z0-9 only
  2. Space converted to '-'
  3. All other characters eliminated

**Comment by Fastidious** [comment]
I do not see this, @jenolan. I see the slug as:

`http://discuss.flarum.org/d/855-is-this-what-it-s-like-to-develop-a-software`

and

`http://discuss.flarum.org/d/855-is-this-what-it-s-like-to-develop-a-software?nojs=1`

**Comment by jenolan** [comment]
Do http://discuss.flarum.org/?nojs=1 the link for the topic is then http://discuss.flarum.org/d/855-Is%20this%20what%20it's%20like%20to%20develop%20a%20software?

**Comment by Fastidious** [comment]
@jenolan ah, that way, in that order, yes, I see it.

**Comment by modInfo** [comment]
I have a similar problem

So make it flarum:
https://spytajsie.com/d/34-portal-wygl-da-jak-stare-zapytaj-my-lisz-e-da-si-na-niego-zgromadzi-tyle-os-b-jak-kiedy-by-o-na-zapytaj/

Properly should be:
https://spytajsie.com/d/34-portal-wyglada-jak-stare-zapytaj-myslisz-ze-da-sie-na-niego-zgromadzi-tyle-osob-jak-kiedys-byl-o-na-zapytaj/

**Comment by tobscure** [comment]
This is covered by #189 and #194.
