### ISSUE TITLE
Jumping to a specific post number is unreliable?

### ISSUE THREAD

**Issue by pxwee5** [flarum/core#437]
Visit this link first in the Word Association Game thread.
http://discuss.flarum.org/d/187-word-association-game/1094

@Toby Check out this image, the edit button is missing now. Initially wanted to edit the previous post, but the option wasn't available. I was moving my mouse up and down quickly on both posts (RastaLulz and mine) to get this screenshot. (The 3 dots didn't appear)
Screenshot 1 - http://i.imgur.com/h6JaKz4.png
Play around with the quote I did in the previous post for **thecodingwizard** to reproduce this issue. 

A few things to take note here on my side
1. When I clicked jump to quote by **thecodingwizard** quoted in my previous post, the slider went to post 513 instead of 646. Not sure you can produce it but here's the screenshot
   Screenshot 2 - http://i.imgur.com/9vrRWsk.png
2. Also, this screenshot was taken 1 full minute after I press the jump to quote. And still nothing appears. (refer to screenshot 2)
3. When using the @ function, isn't it more natural for the members to appear at the top first instead of their posts? 
   At the moment the @ function lists out post first then member. I believe member first then post is the better way to go. 
4. Permalink issue. http://i.imgur.com/9UVJBgR.png
   Total post is 1070 posts. However the the url shows 1096. Maybe you have deleted 20+ posts. Url should reflect the total post count. Correct url should be: http://discuss.flarum.org/d/187-word-association-game/1070 for the last post.

**Comment by Fastidious** [comment]
Duplicate of flarum/issue-archive#395?

**Comment by pxwee5** [comment]
Nope. Different issue but similar.

**Comment by tobyzerner** [comment]
1/2 is a legit bug. 3 is a discussion that should be had in a new topic on the forum. 4 is a feature, not a bug – if the URL reflected the current position of a post within the discussion, then whenever a post is deleted, _all_ of the subsequent post permalinks would change (and thus not be permalinks).

**Comment by askvortsov1** [comment]
1/2 were fixed in flarum/framework#2160
