### ISSUE TITLE
Compact posts branch: ellipsis riding high in mobile

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#444]
Compared with the standard desktop layout...

![ellipsis 1](https://cloud.githubusercontent.com/assets/13129997/9725746/f604e00a-5623-11e5-95ac-dae716598dd9.png)

... the ellipsis button gets displaced when I scrunch my browser up to iPhone size ...

![ellipsis 2](https://cloud.githubusercontent.com/assets/13129997/9725757/1308702c-5624-11e5-9c94-b0bab3cf74b1.png)

Just a tiny aesthetic issue I thought I'd bring to your attention.

**Comment by tobscure** [comment]
This should be fixed now. Will deploy to discuss.flarum soon.
