### ISSUE TITLE
Avatar Canvas CORS problem

### ISSUE THREAD

**Issue by xintron** [flarum/core#445]
The [calculateAvatarColor](https://github.com/flarum/core/blob/master/js/lib/models/User.js#L85) adds a nice identity part for users but it leaves a few things to be desired. Right now there is a CORS issue when hot-linking images from external sources. There are two ways of tackling this from what I've found:
1. Don't use HTML Canvas together with external URIs.
2. Allow tainted canvases - not widely adopted by browsers

Since hot-linking isn't a native function in the core I can see why this wouldn't be high priority but the default [User.color](https://github.com/flarum/core/blob/master/js/lib/models/User.js#L34) uses the memoization function `computed` making it a bit ugly to override (and still fall back to calling the original function); and thus I purpose a change in the default method implementation to make monkey patching easier for extensions. It is possible to work around but it breaks the monkey patching solution to some extent.

More info: https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

**Comment by tobscure** [comment]
Good point, I didn't think of that.

> but the default User.color uses the memoization function computed making it a bit ugly to override (and still fall back to calling the original function); and thus I purpose a change in the default method implementation to make monkey patching easier for extensions. It is possible to work around but it breaks the monkey patching solution to some extent.

Can you elaborate on this a bit?

**Comment by xintron** [comment]
> Can you elaborate on this a bit?

The problem I saw when overriding this color function was that I didn't get the memoization function (the original one) sent as an first argument to my overloaded one if I myself create a new `computed` function. Instead I got the arguments like they would normally be sent in. I'm not sure if this is related to it being set using the mixins function or what's going on but it was to some extend breaking the extensability flow.

The solution I had to take to work around this was similar to this instead:
````js
  var origColorFunc = User.prototype.color;
  override(User.prototype, 'color',
           computed('username', 'avatarUrl', 'avatarColor',
                    function(username, avatarUrl, avatarColor) {

    if (avatarColor) {
      return 'rgb(' + avatarColor.join(', ') + ')';
    } else if (avatarUrl && avatarUrl.indexOf('gravatar.com/avatar/') !== -1) {
      return '#' + stringToColor(username);
    } else {
      return origColorFunc.apply(this, [username, avatarUrl, avatarColor]);
    }
  }));
````
