### ISSUE TITLE
[Subscriptions] Add ignore to DiscussionControls

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#447]

**Comment by dcsjapan** [comment]
Not sure if I should make this a separate issue or not, but while you're at it...

A change to the string describing the feature might be a good idea.

Current: "Never be notified. Hide from the discussion list."

Suggested: "Never be notified. Hide from the All Discussions list."

That should clarify what it does, so people don't assume that it hides the thread everywhere (as I did).
