### ISSUE TITLE
[Mentions] Quote correct post in reply notification

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#448]
As per http://discuss.flarum.org/d/838-reply-to-in-notifications/8

**Comment by franzliedke** [comment]
Not sure if this belongs here, but I encountered a similar problem:

I got a notification about [this reply](https://discuss.flarum.org/d/6825-why-so-many-extensions/15), which referenced posts in another thread. The notification brought me to that other thread, but obviously did not surface the actual reply.

**Comment by askvortsov1** [comment]
Closing this in favor of https://github.com/flarum/core/issues/2127, as that has a better description / steps to reproduce
