### ISSUE TITLE
Empty Search Results

### ISSUE THREAD

**Issue by Shadowwolf97** [flarum/core#45]
When searching for posts that returns zero matches, the page is simply left blank rather than an error message. For instance, when searching for "an awesome search query", zero posts are found, and the page remains completely empty (http://puu.sh/gehn2/9dfeebf485.png).

**Comment by tobscure** [comment]
Yep, search is a bit incomplete at the moment. Will be working on that in the coming weeks :)

**Comment by tobscure** [comment]
Closing, will definitely be addressed when I revamp search
