### ISSUE TITLE
Scroll handle can't reach post at the edge of view

### ISSUE THREAD

**Issue by lightonflux** [flarum/core#454]
So at the top there are 3 post, all fit into the viewport. But the fourth is below. But the scroll handle on the right already shows it as my position, so there is no way to scroll to 4. I can only grab it and scroll to 5. The amount of post does not matter.

Technically the handle bar is correct, because i already see a few pixels of 4, but i don't see any content. And when i try to reach it via handle bar i only see 5. 

Quick fix: Link the text "4 of 9" to a scroll action. So when you press it, it scrolls the post up to the top of your view. 

![bildschirmfoto von 2015-09-09 15 40 58](https://cloud.githubusercontent.com/assets/1377943/9763653/0b673334-570b-11e5-9718-880956f2e952.png)

**Comment by tobscure** [comment]
Not quite sure what you're getting at. Can you maybe demonstrate the bug using a [GIF](http://www.cockos.com/licecap/)?

**Comment by lightonflux** [comment]
I just realised that this is not a bug, but a misunderstanding on my part. Sorry for the confusion.
