### ISSUE TITLE
Avatars do not upload.

### ISSUE THREAD

**Issue by lopar** [flarum/core#456]
Error appears «Oops! Something went wrong on the server. Please reload the page and try again.».

**Comment by LukeWilliamsBK** [comment]
I had this problem, when I looked under the hood, the error was "ImageMagick module not available with this PHP installation."
I fixed it by running the following commands: 

sudo apt-get install php5-imagick
sudo php5enmod imagick
sudo service php5-fpm restart

**Comment by tobscure** [comment]
We've added checks for this in beta 2 (coming very soon). If you're still having trouble, search the forum – there's plenty of discussion about it on there.
