### ISSUE TITLE
Can't register to Flarum Community

### ISSUE THREAD

**Issue by Heart1010** [flarum/core#457]
When I try to register on your Flarum community I get this error in chrome console

![2015-09-10 bildschirmdruck 1](https://cloud.githubusercontent.com/assets/1481680/9784600/61ff81d2-57ac-11e5-9e2c-2c75c6add897.png)

**Comment by franzliedke** [comment]
I believe your password is too short. Has to be at least 8 characters.

**Comment by Heart1010** [comment]
Correct! :+1: 

Some hint/error message would really be helpfull :wink:

**Comment by franzliedke** [comment]
Yeah, we'll handle this as part of #118. Thanks for reporting!
