### ISSUE TITLE
[Lock] Permit groups other then admin to lock threads (permissions)

### ISSUE THREAD

**Issue by Mecvak** [flarum/core#458]
It's impossible to grant a group permissions to lock threads.
There should a option to do so on the assumption that the lock extension is enabled.
Something like
**Lock Discussions:**
[Reference](http://discuss.flarum.org/d/941-close-thread)
____
In the image I've granted all possible moderating options to grouper (blue circle) yet the user is unable to lock a thread.

![](http://i.imgur.com/WDfShKH.png)
![](http://i.imgur.com/4KSCKGH.png)

**Comment by tobscure** [comment]
This has been fixed for beta 3.
