### ISSUE TITLE
Starting Post Highlighting Off

### ISSUE THREAD

**Issue by Shadowwolf97** [flarum/core#46]
When the first unread post is highlighted, it is not centered around the post as one would expect. There is more padding at the top of the post than the bottom.
![image](https://cloud.githubusercontent.com/assets/2414590/6420226/50bef140-be92-11e4-84f8-7f2b4ec62d84.png)

**Comment by tobscure** [comment]
This was fixed in 1d6616a41979c3f116b7cfdc266c735af071b3b5
