### ISSUE TITLE
Prefetching meta tags

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#460]
These may help with performance (DNS resolution etc.):
https://css-tricks.com/prefetching-preloading-prebrowsing/

**Comment by tobscure** [comment]
Do we have any specifics on how this can be applied to Flarum?

**Comment by dav-is** [comment]
I think I saw a discussion on the forums and they said it didn't allow caching of preloaded assets I think...

**Comment by franzliedke** [comment]
Yeah, not sure what this was about. Closing. ;)
