### ISSUE TITLE
No error message for non-unique username on signup

### ISSUE THREAD

**Issue by Zecc** [flarum/core#462]
I tried to sign up on http://discuss.flarum.org but I didn't get the confirmation email. Don't worry! I think it was the email provider's fault because it wasn't showing *any* other emails either.

However, when I tried to sign up using another email address there was no feedback whatsoever. Looking at the browser's network activity I see the following:

    HTTP/1.1 422 Unprocessable Entity
    <other response headers>
    
    {"errors":[{"detail":"validation.unique","path":"username"}]}     

I guess it's okay (debatable) that I couldn't sign up for a username that's already been requested even if it's not been confirmed, but there should be an error message to the user.

**Comment by franzliedke** [comment]
Yep, we'll handle this as part of #118.
