### ISSUE TITLE
Sign Up - POST tosses a 422 from Firefox

### ISSUE THREAD

**Issue by et-clow** [flarum/core#463]
![untitled](https://cloud.githubusercontent.com/assets/5647862/9822547/018cca06-588f-11e5-8348-df09290c6c7f.png)

**Comment by tarunmarkose** [comment]
It's probably failing validation - Does your password have a minimum of 8
characters?

On Friday 11 September 2015, et-clow <notifications@github.com> wrote:

> [image: untitled]
> <https://cloud.githubusercontent.com/assets/5647862/9822547/018cca06-588f-11e5-8348-df09290c6c7f.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flarum/core/issues/463>.
>


-- 
-Tarun

**Comment by franzliedke** [comment]
This is a known issue, we'll create the missing error messages as part of #118.
