### ISSUE TITLE
Unable to login using Internet Explorer 11.0.9600.18015

### ISSUE THREAD

**Issue by Mivexil** [flarum/core#464]
As stated, it is impossible to login using Internet Explorer 11 due to an UI glitch which causes the input fields on the login form to clear following ay input. The same issue happens with the Windows 8 Modern version of IE.

Repro steps:
- visit the front page of a Flarum forum (tested for http://discus.flarum.org)
- click the "Log in" button
- start entering text into the Username (or Password) field
- after typing each letter, the field being typed into clears itself

**Comment by sjennison** [comment]
Not reproducable on Edge, FWIW

**Comment by bwmarrin** [comment]
I can confirm this exact problem.

I've tested on Windows 7 and Windows 10 (Tech Preview) so far.  

My experience is 100% identical to what @Mivexil  reported above.

**Comment by tobscure** [comment]
I've only been able to test on Edge (using https://remote.modern.ie) and couldn't reproduce there.

This is pretty critical though, I'll get a VM running and get this fixed.

**Comment by bwmarrin** [comment]
I'd like to test and verify this is resolved :) Also, I'd like to have a copy installed where it works.  But I'm not quite sure how to run from git master.  Is there some instructions for doing that or can you give me a brief summary?  Then, I'll happily help test Windows IE 11 issues for you :)

**Comment by Mecvak** [comment]
@bwmarrin try [here](http://bleedingflarum.xyzz.work/)?
It's using the very latest commits so expect some breakage ;)

**Comment by bwmarrin** [comment]
Ah, well that definitely works on my IE11 browsers :)  Thanks for the fix guys.
