### ISSUE TITLE
AkiSmet From repository throw invalid API Key

### ISSUE THREAD

**Issue by samymassoud** [flarum/core#468]
I have installed the beta 2 forum from it's repository and also i have built AkiSmet Extension with it.
But whenever any user try to add topic or reply he gets an Error Message.

Because of  "Invalid API Key" and no setting for that in control panel

**Comment by franzliedke** [comment]
You should be able to set the API key in the admin panel.
Click on "Extensions" -> hover over the three dots next to the "Akismet" item -> click on "Settings" -> Enter your API key. :)

**Comment by franzliedke** [comment]
Also, please discuss problems like these on the forums next time. This is not a bug with Flarum (although I admit Akismet shouldn't try to work without having a key entered).
