### ISSUE TITLE
Installation - No Error Message

### ISSUE THREAD

**Issue by kayyyy** [flarum/core#469]
In my case my database wasnt created - but i dont got any error message, just a blank red container

![image](https://cloud.githubusercontent.com/assets/8193345/9838288/18d3e092-5a5a-11e5-9e02-10a05244dd43.png)

After the error the site doesnt reload and the button "please wait .." is hanging so you have to manually reload the page.

**Comment by franzliedke** [comment]
You probably entered invalid errors. Can you please follow the [troubleshooting docs](http://flarum.org/docs/troubleshooting/) to find out the full error?

**Comment by franzliedke** [comment]
P.S.: Please note that you may have to drop and re-create the database to try again.

**Comment by kayyyy** [comment]
Yep deleteing the database and re run the installer solved the problem.
Thought i should create an issue because there wasnt an error message so you can solve this in your final release.

keep up the good work :+1:

**Comment by franzliedke** [comment]
Yep, we'll definitely improve the error messages. :)
