### ISSUE TITLE
extension reports and akismet error

### ISSUE THREAD

**Issue by RudolfFussek** [flarum/core#471]
extension/reports
<b>Fatal error</b>:  require(): Failed opening required '/homepages/17/d591024594/htdocs/habbolando.com/httpdocs/extensions/reports/vendor/autoload.php' (include_path='.:/usr/lib/php5.5') in <b>/homepages/17/d591024594/htdocs/habbolando.com/httpdocs/extensions/reports/bootstrap.php</b> on line <b>12</b><br />

extension/akismet
<b>Fatal error</b>:  require(): Failed opening required '/homepages/17/d591024594/htdocs/habbolando.com/httpdocs/extensions/akismet/vendor/autoload.php' (include_path='.:/usr/lib/php5.5') in <b>/homepages/17/d591024594/htdocs/habbolando.com/httpdocs/extensions/akismet/bootstrap.php</b> on line <b>12</b><br />

**Comment by franzliedke** [comment]
Did you download it from GitHub? I believe we need to build a release for that one first.

**Comment by tobscure** [comment]
These extensions aren't ready for use yet, unless you know what you're doing. Please wait for beta 3 :)
