### ISSUE TITLE
Suspend error

### ISSUE THREAD

**Issue by RudolfFussek** [flarum/core#472]
When you will suspend a User you became a error....

When you will suspend a User you became a error....

{
    "errors": [{
        "code": 500,
        "title": "Internal Server Error",
        "detail": "exception \u0027PDOException\u0027 with message \u0027SQLSTATE[42S22]: Column not found: 1054 Unknown column \u0027suspend_until\u0027 in \u0027field list\u0027\u0027 in \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/database\/Connection.php:402\nStack trace:\n#0 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/database\/Connection.php(402): PDO-\u003Eprepare(\u0027update `users` ...\u0027)\n#1 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/database\/Connection.php(629): Illuminate\\Database\\Connection-\u003EIlluminate\\Database\\{closure}(Object(Illuminate\\Database\\MySqlConnection), \u0027update `users` ...\u0027, Array)\n#2 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/database\/Connection.php(596): Illuminate\\Database\\Connection-\u003ErunQueryCallback(\u0027update `users` ...\u0027, Array, Object(Closure))\n#3 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/database\/Connection.php(407): Illuminate\\Database\\Connection-\u003Erun(\u0027update `users` ...\u0027, Array, Object(Closure))\n#4 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/database\/Connection.php(350): Illuminate\\Database\\Connection-\u003EaffectingStatement(\u0027update `users` ...\u0027, Array)\n#5 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/database\/Query\/Builder.php(1750): Illuminate\\Database\\Connection-\u003Eupdate(\u0027update `users` ...\u0027, Array)\n#6 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/database\/Eloquent\/Builder.php(313): Illuminate\\Database\\Query\\Builder-\u003Eupdate(Array)\n#7 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/database\/Eloquent\/Model.php(1530): Illuminate\\Database\\Eloquent\\Builder-\u003Eupdate(Array)\n#8 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/database\/Eloquent\/Model.php(1464): Illuminate\\Database\\Eloquent\\Model-\u003EperformUpdate(Object(Illuminate\\Database\\Eloquent\\Builder), Array)\n#9 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/flarum\/core\/src\/Core\/Users\/Commands\/EditUserHandler.php(112): Illuminate\\Database\\Eloquent\\Model-\u003Esave()\n#10 [internal function]: Flarum\\Core\\Users\\Commands\\EditUserHandler-\u003Ehandle(Object(Flarum\\Core\\Users\\Commands\\EditUser))\n#11 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/bus\/Dispatcher.php(205): call_user_func(Array, Object(Flarum\\Core\\Users\\Commands\\EditUser))\n#12 [internal function]: Illuminate\\Bus\\Dispatcher-\u003EIlluminate\\Bus\\{closure}(Object(Flarum\\Core\\Users\\Commands\\EditUser))\n#13 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/pipeline\/Pipeline.php(139): call_user_func(Object(Closure), Object(Flarum\\Core\\Users\\Commands\\EditUser))\n#14 [internal function]: Illuminate\\Pipeline\\Pipeline-\u003EIlluminate\\Pipeline\\{closure}(Object(Flarum\\Core\\Users\\Commands\\EditUser))\n#15 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/pipeline\/Pipeline.php(103): call_user_func(Object(Closure), Object(Flarum\\Core\\Users\\Commands\\EditUser))\n#16 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/bus\/Dispatcher.php(206): Illuminate\\Pipeline\\Pipeline-\u003Ethen(Object(Closure))\n#17 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/bus\/Dispatcher.php(179): Illuminate\\Bus\\Dispatcher-\u003EdispatchNow(Object(Flarum\\Core\\Users\\Commands\\EditUser), NULL)\n#18 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/flarum\/core\/src\/Api\/Actions\/Users\/UpdateAction.php(83): Illuminate\\Bus\\Dispatcher-\u003Edispatch(Object(Flarum\\Core\\Users\\Commands\\EditUser))\n#19 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/flarum\/core\/src\/Api\/Actions\/SerializeAction.php(85): Flarum\\Api\\Actions\\Users\\UpdateAction-\u003Edata(Object(Flarum\\Api\\JsonApiRequest), Object(Tobscure\\JsonApi\\Document))\n#20 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/flarum\/core\/src\/Api\/ApiServiceProvider.php(356): Flarum\\Api\\Actions\\SerializeAction-\u003Ehandle(Object(Flarum\\Api\\Request))\n#21 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/flarum\/core\/src\/Http\/RouterMiddleware.php(65): Flarum\\Api\\ApiServiceProvider-\u003EFlarum\\Api\\{closure}(Object(Zend\\Stratigility\\Http\\Request), Array)\n#22 [internal function]: Flarum\\Http\\RouterMiddleware-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#23 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(79): call_user_func(Object(Flarum\\Http\\RouterMiddleware), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#24 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Next.php(111): Zend\\Stratigility\\Dispatch-\u003E__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#25 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/flarum\/core\/src\/Api\/Middleware\/LoginWithHeader.php(66): Zend\\Stratigility\\Next-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#26 [internal function]: Flarum\\Api\\Middleware\\LoginWithHeader-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#27 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(79): call_user_func(Object(Flarum\\Api\\Middleware\\LoginWithHeader), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#28 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Next.php(111): Zend\\Stratigility\\Dispatch-\u003E__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#29 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/flarum\/core\/src\/Api\/Middleware\/ReadJsonParameters.php(32): Zend\\Stratigility\\Next-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#30 [internal function]: Flarum\\Api\\Middleware\\ReadJsonParameters-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#31 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(79): call_user_func(Object(Flarum\\Api\\Middleware\\ReadJsonParameters), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#32 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Next.php(111): Zend\\Stratigility\\Dispatch-\u003E__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#33 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/MiddlewarePipe.php(76): Zend\\Stratigility\\Next-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#34 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/zendframework\/zend-diactoros\/src\/Server.php(166): Zend\\Stratigility\\MiddlewarePipe-\u003E__invoke(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Diactoros\\Response), NULL)\n#35 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/api.php(42): Zend\\Diactoros\\Server-\u003Elisten()\n#36 {main}\n\nNext exception \u0027Illuminate\\Database\\QueryException\u0027 with message \u0027SQLSTATE[42S22]: Column not found: 1054 Unknown column \u0027suspend_until\u0027 in \u0027field list\u0027 (SQL: update `users` set `suspend_until` = 2015-09-15 07:26:08 where `id` = 2)\u0027 in \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/database\/Connection.php:636\nStack trace:\n#0 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/database\/Connection.php(596): Illuminate\\Database\\Connection-\u003ErunQueryCallback(\u0027update `users` ...\u0027, Array, Object(Closure))\n#1 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/database\/Connection.php(407): Illuminate\\Database\\Connection-\u003Erun(\u0027update `users` ...\u0027, Array, Object(Closure))\n#2 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/database\/Connection.php(350): Illuminate\\Database\\Connection-\u003EaffectingStatement(\u0027update `users` ...\u0027, Array)\n#3 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/database\/Query\/Builder.php(1750): Illuminate\\Database\\Connection-\u003Eupdate(\u0027update `users` ...\u0027, Array)\n#4 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/database\/Eloquent\/Builder.php(313): Illuminate\\Database\\Query\\Builder-\u003Eupdate(Array)\n#5 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/database\/Eloquent\/Model.php(1530): Illuminate\\Database\\Eloquent\\Builder-\u003Eupdate(Array)\n#6 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/database\/Eloquent\/Model.php(1464): Illuminate\\Database\\Eloquent\\Model-\u003EperformUpdate(Object(Illuminate\\Database\\Eloquent\\Builder), Array)\n#7 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/flarum\/core\/src\/Core\/Users\/Commands\/EditUserHandler.php(112): Illuminate\\Database\\Eloquent\\Model-\u003Esave()\n#8 [internal function]: Flarum\\Core\\Users\\Commands\\EditUserHandler-\u003Ehandle(Object(Flarum\\Core\\Users\\Commands\\EditUser))\n#9 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/bus\/Dispatcher.php(205): call_user_func(Array, Object(Flarum\\Core\\Users\\Commands\\EditUser))\n#10 [internal function]: Illuminate\\Bus\\Dispatcher-\u003EIlluminate\\Bus\\{closure}(Object(Flarum\\Core\\Users\\Commands\\EditUser))\n#11 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/pipeline\/Pipeline.php(139): call_user_func(Object(Closure), Object(Flarum\\Core\\Users\\Commands\\EditUser))\n#12 [internal function]: Illuminate\\Pipeline\\Pipeline-\u003EIlluminate\\Pipeline\\{closure}(Object(Flarum\\Core\\Users\\Commands\\EditUser))\n#13 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/pipeline\/Pipeline.php(103): call_user_func(Object(Closure), Object(Flarum\\Core\\Users\\Commands\\EditUser))\n#14 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/bus\/Dispatcher.php(206): Illuminate\\Pipeline\\Pipeline-\u003Ethen(Object(Closure))\n#15 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/illuminate\/bus\/Dispatcher.php(179): Illuminate\\Bus\\Dispatcher-\u003EdispatchNow(Object(Flarum\\Core\\Users\\Commands\\EditUser), NULL)\n#16 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/flarum\/core\/src\/Api\/Actions\/Users\/UpdateAction.php(83): Illuminate\\Bus\\Dispatcher-\u003Edispatch(Object(Flarum\\Core\\Users\\Commands\\EditUser))\n#17 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/flarum\/core\/src\/Api\/Actions\/SerializeAction.php(85): Flarum\\Api\\Actions\\Users\\UpdateAction-\u003Edata(Object(Flarum\\Api\\JsonApiRequest), Object(Tobscure\\JsonApi\\Document))\n#18 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/flarum\/core\/src\/Api\/ApiServiceProvider.php(356): Flarum\\Api\\Actions\\SerializeAction-\u003Ehandle(Object(Flarum\\Api\\Request))\n#19 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/flarum\/core\/src\/Http\/RouterMiddleware.php(65): Flarum\\Api\\ApiServiceProvider-\u003EFlarum\\Api\\{closure}(Object(Zend\\Stratigility\\Http\\Request), Array)\n#20 [internal function]: Flarum\\Http\\RouterMiddleware-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#21 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(79): call_user_func(Object(Flarum\\Http\\RouterMiddleware), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#22 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Next.php(111): Zend\\Stratigility\\Dispatch-\u003E__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#23 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/flarum\/core\/src\/Api\/Middleware\/LoginWithHeader.php(66): Zend\\Stratigility\\Next-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#24 [internal function]: Flarum\\Api\\Middleware\\LoginWithHeader-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#25 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(79): call_user_func(Object(Flarum\\Api\\Middleware\\LoginWithHeader), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#26 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Next.php(111): Zend\\Stratigility\\Dispatch-\u003E__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#27 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/flarum\/core\/src\/Api\/Middleware\/ReadJsonParameters.php(32): Zend\\Stratigility\\Next-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#28 [internal function]: Flarum\\Api\\Middleware\\ReadJsonParameters-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#29 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Dispatch.php(79): call_user_func(Object(Flarum\\Api\\Middleware\\ReadJsonParameters), Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#30 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/Next.php(111): Zend\\Stratigility\\Dispatch-\u003E__invoke(Object(Zend\\Stratigility\\Route), NULL, Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response), Object(Zend\\Stratigility\\Next))\n#31 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/zendframework\/zend-stratigility\/src\/MiddlewarePipe.php(76): Zend\\Stratigility\\Next-\u003E__invoke(Object(Zend\\Stratigility\\Http\\Request), Object(Zend\\Stratigility\\Http\\Response))\n#32 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/flarum\/vendor\/zendframework\/zend-diactoros\/src\/Server.php(166): Zend\\Stratigility\\MiddlewarePipe-\u003E__invoke(Object(Zend\\Diactoros\\ServerRequest), Object(Zend\\Diactoros\\Response), NULL)\n#33 \/homepages\/17\/d591024594\/htdocs\/httpdocs\/api.php(42): Zend\\Diactoros\\Server-\u003Elisten()\n#34 {main}"
    }
    ]
}

**Comment by franzliedke** [comment]
Please download the newest version [from GitHub](https://github.com/flarum/suspend). @tobscure fixed this error just two hours ago. :)

**Comment by RudolfFussek** [comment]
I have download the newest version?

**Comment by franzliedke** [comment]
But you probably did not run the migrations...

**Comment by RudolfFussek** [comment]
@franzliedke What do you mean? :o... - Your are from Germany or? Do you can speak german or?

**Comment by franzliedke** [comment]
Yes, I am. I'd advise you to wait for the next beta release, the updating process is not yet as simple as it should be.

**Comment by RudolfFussek** [comment]
Okay... Wobei, ich hatte core usw, alles aktualisiert... Will nicht - warten wir halt mal ab :D...

**Comment by RudolfFussek** [comment]
Okay... I have disable suspend and then I will enable... This error come:

<b>Fatal error</b>:  Class 'Doctrine\DBAL\Driver\PDOMySql\Driver' not found in <b>/homepages/17/d591024594/htdocs/habbolando.com/httpdocs/flarum/vendor/illuminate/database/MySqlConnection.php</b> on line <b>64</b><br />
