### ISSUE TITLE
PATCH requests can be mangled on some intermediary network devices (Was: 400 errors on trying to follow a topic)

### ISSUE THREAD

**Issue by pauljherring** [flarum/core#473]
1) Went to: http://discuss.flarum.org/d/977-invalid-repository-file/5
2) Tried to change status from "Not Following" to "Following"
3) Got "Oops! Something went wrong on the server. Please reload the page and try again." error on the GUI, with a 400 error on console. 
4) Clearing the GUI error reverts the GUI back to its previous state.

Digging a bit further I got the following:

*Response Headers*

HTTP/1.0 400 Bad Request
Server: squid/2.6.STABLE21
Date: Mon, 14 Sep 2015 11:19:54 GMT
Content-Type: text/html
Content-Length: 1911
Expires: Mon, 14 Sep 2015 11:19:54 GMT
X-Squid-Error: ERR_INVALID_REQ 0
X-Cache: MISS from admin.office
X-Cache-Lookup: NONE from admin.office:3128
Via: 1.0 admin.office:3128 (squid/2.6.STABLE21)
Proxy-Connection: close

*Request Headers*

PATCH /api/discussions/977 HTTP/1.1
Host: discuss.flarum.org
Connection: keep-alive
Content-Length: 81
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36
Origin: http://discuss.flarum.org
Authorization: Token ZOqOUcZ7Q1p13bjEPB2qGK5yXqneCLC3MZ1mNX77
Content-Type: application/json; charset=UTF-8
Accept: */*
Referer: http://discuss.flarum.org/d/977-invalid-repository-file/5
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Cookie: flarum_remember=ZOqOUcZ7Q1p13bjEPB2qGK5yXqneCLC3MZ1mNX77

*Request Payload*

{"data":{"type":"discussions","id":"977","attributes":{"subscription":"follow"}}}

**Comment by Fastidious** [comment]
It seems it will have something to do with you going through a cache/proxy (squid).

**Comment by pauljherring** [comment]
Indeed:

http://wisdomofganesh.blogspot.co.uk/2012/08/best-practice-for-use-of-patch-in.html

> Not all infrastructure components understand PATCH. Firewalls are suspicious, proxies could mangle or drop messages containing the unfamiliar verb, not all web servers are geared to handle it, and so on. 

I will note that I've had similar symptoms on my mobile phone with certain public WiFi providers...

**Comment by tobscure** [comment]
Should be fixed with #502
