### ISSUE TITLE
The fileinfo extension is required

### ISSUE THREAD

**Issue by Petrouchka** [flarum/core#475]
I installed flarum-0.1.0-beta.1 on http://www.numopen.fr/discussions/ to try it. It works.
I just downloaded and copied flarum-0.1.0-beta.2 on http://www.numopen.fr/blabla/ and I've got this error :

"Hold Up!

These errors must be resolved before you can continue the installation. If you're having trouble, get help on the Flarum website.
The fileinfo extension is required."

What is wrong ?

**Comment by franzliedke** [comment]
You need to install the PHP extension "fileinfo", exactly as the error says. Otherwise Flarum will not function properly.

**Comment by franzliedke** [comment]
I [just made](https://github.com/flarum/core/commit/cd5f5515e268fdd939fdc5581be21becd5f4565b) the error messages a bit clearer.

**Comment by Petrouchka** [comment]
Thank you.
I keep the same database as the first installation but it causes an error :

"Something went wrong: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'migrations' already exists (SQL: create table `migrations` (`migration` varchar(255) not null, `extension` varchar(255) null) default character set utf8mb4 collate utf8mb4_unicode_ci)"

So, I need to create a new database and transfer my data from the old database. It would be better to add a test if the database and tables soon exist and use them if so.

**Comment by franzliedke** [comment]
Just follow the upgrade instructions in [this post](http://discuss.flarum.org/d/987-flarum-v0-1-0-beta-2-released).
