### ISSUE TITLE
Can't delete a discussion

### ISSUE THREAD

**Issue by Petrouchka** [flarum/core#478]
I created a new discussion as administrator and I can't delete it :
"Oops! Something went wrong on the server. Please reload the page and try again."
Same bug in beta 2 than with beta 1 : https://github.com/flarum/core/issues/352

**Comment by Petrouchka** [comment]
And I noticed something strange. The discussion that I created as an admin doesn't appear when I'm connected as a normal user. I can see it only as admin.

If a create a new discussion as a normal user, I can't delete it as user nor as admin.

**Comment by Luceos** [comment]
Please read [this](http://flarum.org/docs/troubleshooting/) and add additional information, without it we cannot help you in any way. The error message is way too vague.

**Comment by Petrouchka** [comment]
I can delete a discussion when I add at the end of the .htacces :
Order allow,deny
Allow from all

And discussions are visibles by everybody now too.
So, it's an access problem. But what I added is perhaps wrong and not secure, I don't know what should be really added.

I think the problem appeared because there is another .htacces at a higher level, at the root of the domain. Its content is :
```
# razorCMS default access file - smiffy6969 - www.razorcms.co.uk - ulsmith.net

IndexIgnore .htaccess */.??* *~ *# */HEADER* */README* */_vti*

Options -Indexes

<Limit GET POST>
order deny,allow
deny from all
allow from all
</Limit>

<Limit PUT DELETE>
order deny,allow
deny from all
</Limit>

<Files ~ ".sqlite$">
Order allow,deny
Deny from all
</Files>

<Files index>
ForceType application/x-httpd-php
</Files>

AddType video/ogv .ogv
AddType video/mp4 .mp4
AddType video/webm .webm
AddType audio/ogg .ogg
AddType audio/mp3 .mp3
AddType audio/m4a .m4a
AddType image/svg+xml svg

DirectoryIndex index.html index.htm index.php index default.html default.htm default.php default

RewriteEngine On
RewriteCond $0####%{REQUEST_URI} ^(.*)####(.*)\1$
RewriteRule ^.*$ - [E=BASE_PATH:%2]
RewriteRule ^sitemap_index.xml %{ENV:BASE_PATH}rars/seo/sitemap [L,QSA]
RewriteRule ^sitemap([0-9]*).xml %{ENV:BASE_PATH}rars/seo/sitemap/$1 [L,QSA]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ %{ENV:BASE_PATH}index.php?path=$1 [L,QSA]
```

**Comment by Luceos** [comment]
fixed in: https://flarum.today/fr/d/3-suppression-d-une-discussion/21

**Comment by Petrouchka** [comment]
Will it be fixed in Flarum .htaccess ?
