### ISSUE TITLE
Wrong redirection

### ISSUE THREAD

**Issue by Petrouchka** [flarum/core#480]
When I want to change the mail address, if I click on the link in the message, I'm redirected to a wrong page.

![capture-reglages - discussions gnu-linux et logiciels libres - mozilla firefox](https://cloud.githubusercontent.com/assets/3955499/9873598/31674a84-5ba1-11e5-9681-558e27a5fd30.png)

![capture-erreur de chargement de la page - mozilla firefox](https://cloud.githubusercontent.com/assets/3955499/9873603/37f11222-5ba1-11e5-87d5-8a2b2ff30636.png)

**Comment by franzliedke** [comment]
One issue about this is enough.

**Comment by Fastidious** [comment]
@franzliedke which other issue is handling this? Do you have the number for it?

**Comment by franzliedke** [comment]
#481

**Comment by Fastidious** [comment]
@franzliedke I might be mistaken, but this issue, #480, is about after registering, a button having a link that is wrong.

On a comment I deleted (because it did not relate to the issue), if I sign up with `user@bananas.com`, it doesn't mean there is a webmail interface (or a mail server at all!) running at `bananas.com`.

**Comment by franzliedke** [comment]
One was about registration, the other about changing the email address. The underlying issue is the same.

**Comment by Fastidious** [comment]
@franzliedke popular email providers will not cut it. It should not link to the domain of the email, it should simply redirect to forum root, after telling the user to check for email. Many users will have their own domain, corporate emails, etc., and it will not be possible to account for all.
