### ISSUE TITLE
Wrong link after creating a new user

### ISSUE THREAD

**Issue by Petrouchka** [flarum/core#481]
When a new user creates an account, the message redirects him to http://www.domain.com/ and not to http://www.domain.com/flarum_directory/ if flarum is not installed at /.
![capture-discussions gnu-linux et logiciels libres - mozilla firefox](https://cloud.githubusercontent.com/assets/3955499/9873638/68969e4c-5ba1-11e5-8795-4fdf2551d582.png)

**Comment by Fastidious** [comment]
It is not taking you to the Flarum root. I think what @tobscure meant was to redirect the user to the webmail interface, so they can check email to activate the account. This doesn't work--unless you are using Gmail, Yahoo (perhaps) or similar).

It might not be a bug per se, just a wrong assumption (from developers). Still something that should be changed.

**Comment by Petrouchka** [comment]
The link is different with the link used here : https://github.com/flarum/core/issues/480
In both case, it doesn't work.

**Comment by Fastidious** [comment]
@Petrouchka I believe both issues are related.

**Comment by Petrouchka** [comment]
Yes, exactly.

**Comment by franzliedke** [comment]
I don't think this is going to happen. See #62 for reference.

**Comment by Fastidious** [comment]
@franzliedke I saw #62, there is no relation at all with this one.

I don't understand why you say it isn't going to happen. Because my email is `peter@bananas.com` it doesn't mean there is a webmail running at `bananas.com` for me to check the email. It just doesn't make sense.

**Comment by franzliedke** [comment]
Not sure where your comment went, @Fastidious. Let me still reply...

The assumption of reaching the mail client at the email domain is a very nice touch *when it's true*. Given that we have no way to determine (other than maybe whitelisting the most popular providers - can you compile a list?) whether we can make that assumption for a given email address, it's either do it and cause a little bit of confusion when the assumption fails, or throw it out and lose the nice touch. Apparently, Toby doesn't want the latter.

**Comment by franzliedke** [comment]
I created [a new ticket](https://github.com/flarum/core/issues/541) for the whitelist idea. Please continue discussion there.
