### ISSUE TITLE
Default language not work in beta 2.

### ISSUE THREAD

**Issue by modInfo** [flarum/core#491]
In MySQL `default_locale` is set to my language, this works great in beta 1, but not more in beta 2

**Comment by Luceos** [comment]
Did you try setting your default language in the admin area under the tab basic? A dropdown is shown if multiple languages are correctly installed.

**Comment by franzliedke** [comment]
I'm closing this, as we don't have enough information about how to reproduce this.
It's possible that your translation is incompatible with beta.2.

Feel free to post more information if you still have this issue.
