### ISSUE TITLE
Ugly white borders of badges

### ISSUE THREAD

**Issue by nxrighthere** [flarum/core#492]
http://postimg.org/image/ct7hf22dt/

That's looks much better.
http://postimg.org/image/f1oxntn5n/

**Comment by tarunmarkose** [comment]
Stas, your solution wouldn't work if the avatar's prominent color was the
same as the badge.. The border creates a separation.

**Comment by franzliedke** [comment]
What @tarunmarkose says. Also, this is highly subjective, and easy to change with a little bit of custom theming.

If you want to rally more support for this, please try the forums first. =)
