### ISSUE TITLE
Do not specify protocol in config.php

### ISSUE THREAD

**Issue by pauljherring** [flarum/core#493]
In config.php, the default installation specifies http (or more likely whatever the first setup page was using) as the config:

```
-bash-4.1$ cat config.php
<?php return array (
[...]
  'url' => 'http://flarum.example.com',
```

requiring a change to config.php if https is required, and preventing both from being used if the site owner wants to allow both.

Removing the protocol from the URL allows both:

```
-bash-4.1$ cat config.php
<?php return array (
[...]
  'url' => '//flarum.example.com',
```

**Comment by Javier-Rotelli** [comment]
little thing to have in mind. 
if you remove the protocol, it breaks at least the link in the welcome email. if this change pass, yo should see that

**Comment by franzliedke** [comment]
I'll keep this in mind when tackling flarum/issue-archive#390, thank you!
