### ISSUE TITLE
Add titles for pages that lack them

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#495]
Some pages show nothing but the forum name in the title bar. The following titles can be added:
- "All Discussions" for the All Discussions page
- "Tags" for the Tags page
- The tag name when a tag-specific discussion list is displayed

In addition, a routine is needed to omit the title of whatever page is set as the site homepage.

**Comment by askvortsov1** [comment]
I've added titles for the tags pages in https://github.com/flarum/tags/pull/72. I'll add the "All Discussions" title, and the logic for clearing the homepage in a new PR.

**Comment by askvortsov1** [comment]
What's better than 1 pull request? 6 Pull Requests! Here we go...

1. Added all discussions title to all discussions page, created mechanism to clear title if on defaultRoute
Core: https://github.com/flarum/core/pull/2047
Lang pack: https://github.com/flarum/lang-english/pull/158

2. Add title to 'all tags' and individual tag pages:
Tags: https://github.com/flarum/tags/pull/72
Lang pack: https://github.com/flarum/lang-english/pull/154

3. Add title to 'following' page:
Subscriptions: https://github.com/flarum/subscriptions/pull/23
Lang Pack: https://github.com/flarum/lang-english/pull/159

Have fun y'all!
