### ISSUE TITLE
issue with extension folder name

### ISSUE THREAD

**Issue by samymassoud** [flarum/core#501]
folder extension must be exact name as  extension name in flarum.json

The problem in this file ExtensionManager.php

    protected function load($extension)
    {
        if (file_exists($file = $this->getExtensionsDir() . '/' . $extension . '/bootstrap.php')) {
            $className = require $file;

            $class = new $className($this->app);
        }

        return $class;
    }

This code didn't load extension and only throw notice that $class not defined, sure if user closed notice notification in PHP he will never know what is wrong !

**Comment by franzliedke** [comment]
Wouldn't that be the fault of the extension, though? Or are you saying you want us to make an additional check here?

**Comment by samymassoud** [comment]
Yes , i mean if extension fail or user copied extension from Github with for example(extension-master) as folder name, it will fail and user will never know that and if he is a developer he might think it's flarum issue.

**Comment by franzliedke** [comment]
I've made it fail a little more gracefully. :)
