### ISSUE TITLE
Allow faking of PATCH/DELETE methods

### ISSUE THREAD

**Issue by tobscure** [flarum/core#502]

**Comment by franzliedke** [comment]
It's a shame REST is bombarded like that from servers. :-(

**Comment by franzliedke** [comment]
Et voila, I implemented the middleware. Works beautifully when testing with PostMan.

@tobscure Can you take care of actually using it in our client app. You need to overwrite all PATCH/PUT/DELETE requests to instead use POST and send the `X-Fake-Http-Method` header with the value set to the HTTP method you want to fake.

**Comment by mrpteo** [comment]
how do i use this fix? Is in a single file or do i need to download it all from Github?

**Comment by franzliedke** [comment]
Wait until Toby closes the issue, then apply all the commits linked in this issue, plus [this one](https://github.com/flarum/flarum/commit/c29323b3f4c048166b2ab2a1432a9c5d76af48ba).
