### ISSUE TITLE
Friendly 404 fails

### ISSUE THREAD

**Issue by Code-Name-Debian** [flarum/core#503]
I'm going to assume bug (correct me if wrong).   

https://sociallyuncensored.com/55555555555555555555555555555555551111

^ If the URL doesn't exist, you get a lot of raw code.  Ideally you should be given a nice friendly invalid url message

**Comment by franzliedke** [comment]
Try again with "debug" set to `false` in config.php.

**Comment by Fastidious** [comment]
@Code-Name-Debian or you could configure your server to give out the 404 instead.

**Comment by Code-Name-Debian** [comment]
Turning config to false worked.

@Fastidious Server already had that enabled ;)

**Comment by franzliedke** [comment]
Is it worth having 404 errors shown as the "pretty" page even in debug mode? I'd say so...

If you don't agree, @tobscure, just close this. :)

**Comment by tobscure** [comment]
I agree!
