### ISSUE TITLE
If the title is too long on mobile, it overlaps & if the tag is too long long on desktop

### ISSUE THREAD

**Issue by SolidOrphan** [flarum/core#505]
When the tag is too long, it overalps on the titles' subjects on the home page

![capturetitletoolong](https://cloud.githubusercontent.com/assets/7015069/9915460/c44e1514-5ce9-11e5-9c26-b35344649a84.PNG)

If the title's forum is too long, it overalps too on mobile : 

On the home page

![screenshot_2015-09-16-21-05-37](https://cloud.githubusercontent.com/assets/7015069/9915459/c44cdf00-5ce9-11e5-8126-1f22592a6201.png)

With the panel side open

![screenshot_2015-09-16-21-05-42](https://cloud.githubusercontent.com/assets/7015069/9915458/c44ae592-5ce9-11e5-879b-923c8e210b6b.png)

**Comment by franzliedke** [comment]
We'll manage this as part of #391, but thanks for reporting!
