### ISSUE TITLE
Discussion/User search drivers + ElasticSearch implementation

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#509]
The search architecture _should_ be pretty good to go in terms of slotting in alternative drivers, but may need some minor work.

**Comment by vinken** [comment]
Hi, I'm glad to hear that you are going to add Sphinx/ElasticSearch driver. 
Will Sphinx driver be published in next beta?

**Comment by tobscure** [comment]
Nope.

**Comment by dav-is** [comment]
May I suggest [Laravel Scout](https://laravel.com/docs/5.3/scout)?

**Comment by matteocontrini** [comment]
Interesting to consider as well: https://github.com/valeriansaliou/sonic

**Comment by amdad** [comment]
I would suggest https://manticoresearch.com/

**Comment by askvortsov1** [comment]
This seems to be a direct subset of https://github.com/flarum/core/issues/1355, so I'm going to close it for now to focus discussion there.
