### ISSUE TITLE
[Pusher] Should not show Update Discussion when ignoring thread

### ISSUE THREAD

**Issue by Mecvak** [flarum/core#512]
The pusher extension shouldn't display a new update bar when you're ignoring the thread itself. 
For example, I am ignoring the word association game, but it will push the update anyways. Then once clicked, it won't show it.. because it's being ignored.

![](http://i.imgur.com/CaMII8K.gif)

**Comment by tobyzerner** [comment]
Consolidating into flarum/framework#512

**Comment by franzliedke** [comment]
Do you mean flarum/issue-archive#404?

**Comment by tobscure** [comment]
Haha yep!
