### ISSUE TITLE
Breaking Tags 101

### ISSUE THREAD

**Issue by Felli** [flarum/core#513]
At the moment you're able to break the tags extension

Example
----
### Multiple Tag creation

This is basically how this happened, I finally got the 2nd beta working to test it out, but ran into a little bug when creating tags, here's how this can be done >Admin Panel>Tags>If your server is lagging a little and you try saving multple times (On a accident) sometimes (Almost always) multiple tags will be created, and if you delete one the others become undeletable till you close the tab and open a new one.
### Screenshots
![](http://i.imgur.com/jhaCef6.png)
![](http://i.imgur.com/IeokmXV.png)
![](http://i.imgur.com/rJ4uaqq.png)

**Comment by Mecvak** [comment]
Confirm bug on [demo site](http://flarum.xyzz.work/)
At the start I click **Save Changes** multiple times very quickly

![](http://i.imgur.com/dFVix9N.gif)

**Comment by franzliedke** [comment]
@tobscure Is this a duplicate?

**Comment by tobscure** [comment]
Nope, I don't think so.

**Comment by Mecvak** [comment]
Similar or a duplicate of [#393](https://github.com/flarum/core/issues/393)?
It'd be impossible to create multiple tags if there was a tag validation for the slug to make sure it was unique..

**Comment by dcsjapan** [comment]
It does seem like #393 has fixed this, so I'll close it.
