### ISSUE TITLE
Reply popover hidden below header

### ISSUE THREAD

**Issue by lightonflux** [flarum/core#517]
When your read a comment on top the viewport, and you hover the reply button, the popover showing the post is below the header of the side. 

Video: https://imgrush.com/kcf2klhauIeu

Solutions:

 * Draw popover under mouse if neccesarry
 * automatically scroll up to show popover and scroll back when the popover disappears

**Comment by tobscure** [comment]
Duplicate of #316 I think (video is no longer accessible)
