### ISSUE TITLE
async requests submitted via javascript result in 401 unauthorized error

### ISSUE THREAD

**Issue by NimbleHost** [flarum/core#519]
In v0.1.0-beta2 any async requests submitted via javascript fail with a 401 unauthorized error.

In the Chrome dev console clicking on the error listing link to the javasacript file in question will place the cursor in the middle of a return statement. That return statement immediately follows a thrown `Error` specifying, `Request data should be either be a string or FormData. Check the 'serialize' option in 'm.request'`. 

See included screenshot for reference.

None of Flarum's user permissions, or file permissions, have been altered. This error occur immediately after a fresh install, after the initial login, whenever creating a new discussion, or trying to edit the user avatar, etc.

![nimblehost forums](https://cloud.githubusercontent.com/assets/233289/9973573/40be5dca-5e43-11e5-874a-2a68eaad82bc.png)

**Comment by tobscure** [comment]
I think the error message you've pointed out in the code has nothing to do with this, it's not actually being thrown :)

401 errors mean that Flarum isn't being passed the auth token properly. This could be because Apache is stripping the Authorization header. If you search around, there are some [discussions](http://discuss.flarum.org/d/586-unable-to-make-any-changes-or-create-posts) about how to fix this.

We will be removing the need for the Authorization is a subsequent beta so this won't be an issue.

**Comment by NimbleHost** [comment]
Appreciate the response and info @tobscure. None of the linked suggestions (neither the SO answers, nor the solution that @henshaw discovered) worked to fix this issue on my particular setup, just FYI.

**Comment by tobscure** [comment]
Hmm, OK, time to debug! Can you add this to the top of your api.php file, after the opening PHP tag:

```
die($_SERVER['HTTP_AUTHORIZATION']);
```

Then open the Network tab in the inspector, do something to trigger an async request, and inspect the contents of the Response for that network request?

**Comment by NimbleHost** [comment]
Appreciate the debugging assistance @tobscure.

After doing as you asked, and triggering an async request by trying to create a new discussion, the Response tab in the Network tab states "This request has no response data available". I've attached a screenshot for reference.

> Also, does the error occur when you're simply browsing around?

No, not to this point.

![nimblehost forums](https://cloud.githubusercontent.com/assets/233289/9974278/75d0ae70-5e55-11e5-82bd-9364b458300d.png)

**Comment by tobscure** [comment]
This result implies that, indeed, the Authorization header is not being passed into PHP correctly, which is a server issue. Can you give some details about your webserver? (Hosting, Apache version, mods enabled, etc.)

**Comment by NimbleHost** [comment]
This particular site is on a WebFaction box with CentOS 6 and Apache 2.2.15. I know `mod_rewrite` is enable but am not sure of what else is. 

Considering this looks like a server issue I don't want to take up your time trying to figure it out. I'll ping their support to see if they can help get me pointed in the right direction.
