### ISSUE TITLE
error message not normal

### ISSUE THREAD

**Issue by train860** [flarum/core#523]
my operation is succeed,but always come out the message at the bottom of window.

"
    Oops! Something went wrong on the server. Please reload the page and try again.
"

and,I was found no errors on the http request !

how can I fix it? thank you!

**Comment by franzliedke** [comment]
No errors on the HTTP request? It should at least have an HTTP status code that tells us more about the type of error.

Also, which "operation" are you talking about? Please help us help you by reading the [troubleshooting guidelines](http://flarum.org/docs/troubleshooting) and providing much more detailed information.

**Comment by franzliedke** [comment]
Please give us more information, otherwise I'll have to close this. :(

**Comment by train860** [comment]
sorry for late!
it seems that all the Post HTTP requests have this problem.

**Comment by franzliedke** [comment]
Please provide us with the content of the failing requests. [Instructions](http://flarum.org/docs/troubleshooting/#oops-something-went-wrong).

**Comment by KrzysiekF** [comment]
Hello,
I have the same error. When I try stick, lock, follow message. In many options in administration panel I'v get this issue. 

This is details od the request:

<pre>
Remote Address:85.128.189.147:80
Request URL:http://forum.okenvato.com/api/discussions/1
Request Method:PATCH
Status Code:403 Forbidden
Response Headers
view source
Accept-Ranges:bytes
Connection:keep-alive
Content-Encoding:gzip
Content-Length:858
Content-Type:text/html
Date:Wed, 07 Oct 2015 06:03:10 GMT
Server:Apache/2
Vary:Accept-Encoding
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4,cs;q=0.2
AlexaToolbar-ALX_NS_PH:AlexaToolbar/alxg-3.3
Authorization:Token DN*******************kn8s
Cache-Control:no-cache
Connection:keep-alive
Content-Length:79
Content-Type:application/json; charset=UTF-8
Cookie:flarum_remember=DN7qZrlaDoVzjLGOMVJ91uh5S1FvK4ngPTqTkn8s; _ga=GA1.2.663989550.1444073422
Host:forum.okenvato.com
Origin:http://forum.okenvato.com
Pragma:no-cache
Referer:http://forum.okenvato.com/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36
Request Payload
view source
{data: {type: "discussions", id: "1", attributes: {subscription: "follow"}}}
</pre>
