### ISSUE TITLE
Mentions: post_mentioned_by_self  

### ISSUE THREAD

**Issue by amdad** [flarum/core#526]
For example we have translations in Likes:
    post_liked_by:
    post_liked_by_self:
 
In Mentions we have:
    post_mentioned_by:
    **post_mentioned_by_self:**     <= missing, please add this 

In English you of course don't need this. But in other languages like mine, it's crucial.

**Comment by franzliedke** [comment]
Do people really mention themselves?

**Comment by tobscure** [comment]
Yeah it's possible, so we need to make a correct translation for it

**Comment by amdad** [comment]
@franzliedke In situation when you reply to your own post. You get:

**You replied to this.** or **You and Toby replied to this.**

I cannot properly translate those lines without own separate string and pluralization.

**Comment by franzliedke** [comment]
Ah, true, I noticed that in the German translation, too (for likes, though).

And I didn't realize that *self* refers to the current user, not necessarily the original poster...

**Comment by amdad** [comment]
Oh, right. Really you not need reply to own post. Just any post.  It just form of direct speaking to user.  Which is great. Toby as rules as always.

**Comment by tobscure** [comment]
Closing in favour of #597
