### ISSUE TITLE
Can't use a index.html or other xxx.html page inside the flarum directory.

### ISSUE THREAD

**Issue by L33tSheep** [flarum/core#529]
That's a problem who's having on the FlarumFR member : he can't put a index.html page (or otherthing.html) in flarum's directory and access it. 

The log when accessing the custom page is : 

![](http://puu.sh/khRt7/7f289bf98e.png)

**Comment by franzliedke** [comment]
Does it not work with any HTML page or just with index.html?
(Where exactly is the HTML file located?)

And what server are you using? Apache, I suppose?

**Comment by tobscure** [comment]
Pretty sure this is a server config issue. I don't know about Apache, but for nginx you'd just need to give index.html precedence over index.php:

```
index index.html index.php;
```

Presumably there's something similar you can do in Apache.
