### ISSUE TITLE
Add validation to limit discussion title length

### ISSUE THREAD

**Issue by tobscure** [flarum/core#53]
There should be a smaller limit on the length of a discussion title (60 characters?)

**Comment by franzliedke** [comment]
80?

**Comment by tobscure** [comment]
Yeah 80 sounds good.

**Comment by LimiQS** [comment]
Why not let site admins modify the max title length instead of write it into the source code? (but 80 is still a good length for title)
please forgive my poor english

**Comment by franzliedke** [comment]
One reason that comes to my mind: the limit is probably enforced by database constraints (i.e. the `title` field in the discussions table).

**Comment by qrokodial** [comment]
what would be the use-case for modifying the title length? adding customization for the sake of having customization adds unnecessary complexity when there is no realistic reasons for modifying it.

**Comment by jgknight** [comment]
> what would be the use-case for modifying the title length?

The use case would be a forum admin wanting to increase or decrease the allowed length of forum titles.. While I agree with not adding complexity, searching around on Google provides a lot of results for people looking to customize the title length of different software (vBulletin, phpBB, etc.)  Perhaps it's not a priority for initial release, but it certainly is not in the realm of 'unrealistic' to provide some method to change it.

**Comment by solhuebner** [comment]
I think this is where the plugin concept can catch up on the end. Like I would like to see it as a bbPress replacement but I think this will not work out of the box. Although it would be awesome ;-)

**Comment by tobscure** [comment]
Also we should truncate the slug at 40 characters or so.

**Comment by tobscure** [comment]
What needs to be done:

* Add a validation rule to the Discussion model to limit the discussion title to 80 characters.

**Comment by franzliedke** [comment]
Fixed in flarum/framework#338, thanks @lbausch.

**Comment by Balancer** [comment]
> One reason that comes to my mind: the limit is probably enforced by database constraints (i.e. the title field in the discussions table).

The field `title` isn't used in foreign keys and therefore has no such restrictions.

80 characters for the title - it's VERY, very little to complete the work: - /

**Comment by franzliedke** [comment]
@Balancer I was referring to the size of the database column, but that is [currently set to 200](https://github.com/flarum/core/blob/30076547e5818bab3281e476333ece4149bb22bb/migrations/2015_02_24_000000_create_discussions_table.php#L19).

**Comment by tobscure** [comment]
It may as well be set to 255, 200 is kind of arbitrary.

The max title length should be configurable (not necessarily via default UI, but definitely via db settings). Do we have an issue for that elsewhere or should we reopen this one?

**Comment by franzliedke** [comment]
I created [an issue](https://github.com/flarum/core/issues/1138), thanks.
