### ISSUE TITLE
Can't upload avatar (Error 500)

### ISSUE THREAD

**Issue by Sakarias-Longhorn** [flarum/core#531]
Hello there, 
I know this issue has been posted many times but it's still not fixed for me in Beta 2,

OS : Windows Server 2012 R2
Xampp Stack (Php 5.6)

When I try to upload an avatar it just says "oops something went wrong..."

I have imagick installed on the server
![](http://sakarias.eu/u/20150921232704.png)

and the php extension enabled
![](http://sakarias.eu/u/20150921232628.png)

Best regards.

**Comment by tobscure** [comment]
Can you please follow the Troubleshooting Guidelines to get more information on the error?

Imagick isn't required as of beta 2, but GD is. Make sure you have that installed, and also that your avatars directory is writable. Otherwise it could be due to #482

**Comment by Sakarias-Longhorn** [comment]
I'm on windows and the avatar directory is writable, also I just checked the GD extension, it's enabled but it's gd2, does it matter ?

**Comment by tobscure** [comment]
gd2 is fine.

**Comment by tobscure** [comment]
Sorry, forgot to link to the [Troubleshooting Guidelines](http://flarum.org/docs/troubleshooting/).

**Comment by Sakarias-Longhorn** [comment]
Well I just formated the server and installed ubuntu, I'll try to see if I can reproduce the error. (But I'm using lamp so I guess it'll not install PHP 5.6

**Comment by Sakarias-Longhorn** [comment]
Well it's working perfectly with no other dependencies on Ubuntu Server 14.04 with the LAMP stack, so.. =)
