### ISSUE TITLE
Request body not being passed to PHP?

### ISSUE THREAD

**Issue by mrpteo** [flarum/core#533]
So, whenever i go to update a post(title or contents) i get an error saying something went wrong. I noticed i get the same error when i favorite a post. After looking at developer tools it had to be something backend.

I checked my error log to see that these actions were producing the following errors:
PHP Warning:  Invalid argument supplied for foreach() in /Forum/flarum/vendor/flarum/core/src/Api/Middleware/ReadJsonParameters.php on line 27 

PHP Catchable fatal error:  Argument 3 passed to Flarum\Core\Discussions\Commands\EditDiscussion::__construct() must be of the type array, null given, called in /Forum/flarum/vendor/flarum/core/src/Api/Actions/Discussions/UpdateAction.php on line 85

PHP Warning:  Invalid argument supplied for foreach() in /Forum/flarum/vendor/flarum/core/src/Api/Middleware/ReadJsonParameters.php on line 27 

PHP Catchable fatal error:  Argument 3 passed to Flarum\Core\Discussions\Commands\EditDiscussion::__construct() must be of the type array, null given, called in Forum/flarum/vendor/flarum/core/src/Api/Actions/Discussions/UpdateAction.php on line 85 

Now dont get me wrong im fairly competent with PHP but with so much code involved i thought it'd save alot of my time and maybe help someone else if you guys have a fix.

**Comment by franzliedke** [comment]
Try applying [this commit](https://github.com/flarum/core/commit/ee9862004d04352e8fddc0f6959ea43285e4e139) to see whether this fixes it.

I *am* a little confused, though, because apparently the request body seems to be empty to the backend... that should not happen on such a request.

**Comment by mrpteo** [comment]
No, same result seems to be occuring

**Comment by tobscure** [comment]
What web server are you running? I suspect that it may be a server issue rather than a Flarum one, with the request body not being properly passed to PHP...

**Comment by mrpteo** [comment]
Its running on iPage shared hosting in this instance. Running: Apache/2

**Comment by franzliedke** [comment]
@mrpteo Are you sure it's the *same* issue. It's clear that there should be a "Something went wrong" error, but the stack trace should be different...

**Comment by mrpteo** [comment]
there are 4 errors above, when i do one action e.g. edit post i get the first 2 and then when i favourite them i get the second two.

**Comment by mrpteo** [comment]
I've looked through the errors when previewing the http response and this is what i get back when i follow the post:

Catchable fatal error: Argument 3 passed to Flarum\Core\Discussions\Commands\EditDiscussion::__construct() must be of the type array, null given, called in /Forum/flarum/vendor/flarum/core/src/Api/Actions/Discussions/UpdateAction.php on line 86 and defined in  Forum/flarum/vendor/flarum/core/src/Core/Discussions/Commands/EditDiscussion.php on line 43

now i can add the little snippet you suggested to the UpdateAction.php file and the PHP error goes away but i still get the CSS popup error message and the action is not actually completed.

**Comment by tobscure** [comment]
So it sounds like what is happening is that for some reason, `php://input` is empty on PATCH requests, due to some quirk in your shared host's platform. It doesn't matter though - we will be moving away from PATCH requests in beta 3. Please track #502 :)
