### ISSUE TITLE
No post options in Firefox (v40.0.3)

### ISSUE THREAD

**Issue by mrpteo** [flarum/core#534]
So far i've only tested in chrome and firefox and something i've noticed. The hover post options(right of post count) dont display in firefox, image below:

http://gexii.com/i/5601589a46168.png

E.g. there are no options like, rename, favourite...

**Comment by Luceos** [comment]
Do you see a console log error in your browser?

**Comment by franzliedke** [comment]
Did it fix itself?

**Comment by mrpteo** [comment]
It seems so, when i reuploaded all the files to try and fix my other issue it went away so im guessing one of my css files hadn't uploaded correctly.
