### ISSUE TITLE
RouteNotFoundException when visiting a page

### ISSUE THREAD

**Issue by fcpwiz** [flarum/core#535]
Whenever I visit a page (ex. forums.com/whatever/), I get this error:

![screen shot 2015-09-22 at 4 32 01 pm](https://cloud.githubusercontent.com/assets/2921172/10030798/7a14222e-6147-11e5-8978-e711ac5b02de.png)

**Comment by tobscure** [comment]
Sounds like a [URL rewriting](http://flarum.org/docs/installation) issue. Please search the issues/[forums](http://discuss.flarum.org/?q=rewriting), you should be able to find a solution.

**Comment by fcpwiz** [comment]
Ah! I was using esoTalk's .htaccess file instead of Flarum's.
