### ISSUE TITLE
Move language selector to bottom of the index sidebar; add option to turn it off

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#539]
**_2 Upvotes**_ A couple of changes to the handling of the language selector:
- It should be moved to the bottom of the index sidebar, where it won't be overly prominent.
- An admin option should be added to to allow disabling of the language selector.
- This option could go near the default language setting on the Basic page.
- When the language selector is disabled, the admin-specified default language is used for all users.

**Comment by tobscure** [comment]
:+1:

**Comment by dcsjapan** [comment]
Some things that occurred to me while editing the language pack installation docs.

The "option to turn it off" part is probably not necessary if English is being extension-ified.

As for moving the language selector, it just occurred to me that this would make it impossible to change the language when the user isn't looking at the index page. Having it in the header would be somewhat more convenient (if a bit cluttered).

An alternative solution would be to give the language selector a smaller footprint. Would it be possible to replace it with [the FontAwesome icon that Maël suggested for use with language packs](http://fortawesome.github.io/Font-Awesome/icon/language/)? You could then format the dropdown similarly to the Reports and Notifications dropdowns, with a "LANGUAGES" title at the top.

**Comment by maelsoucaze** [comment]
Yay to that. In addition to the move, we could also use a simple browser checking. If the browser's language is different than the default language of the forum, a banner saying "This forum is also available in [Language]. Do you want to change the language ? [Yes] [No] ("No" let the forum's default language).

**Comment by Mecvak** [comment]
+1 @maelsoucaze .
As flarum gets more and more features and more support, I think it'd be ideal to keep clutter to a absolute minimum.
Maybe instead of a language selector on the home page, there should be a settings button that can be a catch all for a lot of this (kind of a expanding thing to display all options without leaving the page.. . After the initial choosing of the language, it's really not going to be needed to be immediately accessible.

 Something maybe like googles new tab settings?
![](http://i.imgur.com/3bDszuP.gif)

**Comment by dcsjapan** [comment]
Interesting idea ... the session menu is already pretty close to that.

Come to think of it, it would probably be ideal to make the language setting a user preference on the Settings page. From that perspective, the language selector is really only needed by guests ... and it happens that guests don't need the Notifications dropdown.

Perhaps we could replace the Bell with a Languages icon for guests, and let registered users change it from their user settings page?
