### ISSUE TITLE
Forget Password Popup window

### ISSUE THREAD

**Issue by pavs** [flarum/core#540]
Looks like code comment shows up on the popup window.

![screenshot from 2015-09-24 13 43 25](https://cloud.githubusercontent.com/assets/3807064/10068005/bf229bb2-62c2-11e5-9efb-ba5306081e25.png)

**Comment by franzliedke** [comment]
That has already been fixed with [this commit](https://github.com/flarum/core/commit/fdb598187f621d18d15cf7a800954809ed2121b1).
