### ISSUE TITLE
and 1 others ...

### ISSUE THREAD

**Issue by amdad** [flarum/core#546]
For example: **...and 1 others like this.**

This is nonsense. If it is just one other there should be his nickname. This info have sense only when from 2 and above users.

**..and 2 others like this.**

**Comment by franzliedke** [comment]
Is this relevant for any other extension than "Likes"? Not for "Mentions", apparently...

**Comment by realrandal** [comment]
I didn't check it, but of course it should be working like this in every time, everywhere.
