### ISSUE TITLE
When the user name contains Chinese or other multi byte language, mentions is not working correctly.

### ISSUE THREAD

**Issue by justjavac** [flarum/core#548]
When the user name contains Chinese or other multi byte language, **mentions** is not working correctly.

http://discuss.flarum.org/d/1061-e-mail-smtp-config-ui/3

**Comment by justjavac** [comment]
Did not convert it to link

![Did not convert it to link](https://cloud.githubusercontent.com/assets/359395/10115317/d7313a32-6435-11e5-911d-3d5813aa3a28.png)

**Comment by dcsjapan** [comment]
Related to https://github.com/flarum/core/issues/465.
