### ISSUE TITLE
Simplify Moment.js Locales Integration

### ISSUE THREAD

**Issue by maelsoucaze** [flarum/core#551]
***1 Upvote*** The current system requires that the translator have some JS skills to extract and adapt the Moment.js code to add it in his config.js file. I think we want to avoid that. We should make it possible to just download the wished [locale file](https://github.com/moment/moment/tree/develop/locale), copy it to the language pack's root and rename it to *moment.js* (for example).

**Comment by dcsjapan** [comment]
I've taken the liberty of starting [this thread](http://discuss.flarum.org/d/1163-a-unified-approach-to-simpler-localization) so we can discuss this issue in combination with #550.

**Comment by maelsoucaze** [comment]
:+1:

**Comment by dcsjapan** [comment]
Closing in favor of this approach:

https://github.com/flarum/core/issues/745
