### ISSUE TITLE
Flarum (with Spanish language extension) is not working in UC Browser

### ISSUE THREAD

**Issue by Buhito72** [flarum/core#559]
UC Browser is a very popular browser, especially for mobile. The forum http://foro.flarum.es (Flarum with Spanish language extension) is not working with UC Browser.

**Comment by franzliedke** [comment]
Thanks for reporting this, but this is not a very helpful bug report.

Please review our contribution guidelines and post some more details about what exactly "is not working".

**Comment by Buhito72** [comment]
Ok, sorry. When you enter the forum with UC Browser appears an empty page.

**Comment by franzliedke** [comment]
Is this still a problem?

**Comment by franzliedke** [comment]
I am closing this issue as it seems to have grown stale. If you still encounter this problem with the latest version, please feel free to re-open it.

Please understand that outdated issues are closed regularly to keep the amount of open issues to a manageable minimum. In any case, thanks for taking an interest in this software and opening the issue in the first place!
