### ISSUE TITLE
Only seeing placeholder text on new install from vagrant

### ISSUE THREAD

**Issue by zaksoup** [flarum/core#560]
After successfully running vagrant up all text seems to be missing and instead what I see is `core.placeholder` where placeholder is a relevant sample text (e.g. `signup_email_placeholder`)

**Comment by franzliedke** [comment]
You need to install the flarum/english extension.

**Comment by tobscure** [comment]
@franzliedke should we update the Vagrant setup script to auto-install the flarum/english extension?

**Comment by Mecvak** [comment]
Is there some method of compiling that needs to be done? Simply cloning into extensions seems to work. I essentially just have [mine](https://github.com/Mecvak/flarum/commit/a421273aa4d4fc4a2cfd1d0d6ebe5cf393f6343b#diff-6ac9ee8f1fef1df50ac839d222fb0f3a) clone the repo in source, then rsync it over to the compiled one..
