### ISSUE TITLE
RouteNotFoundException - When forum is private

### ISSUE THREAD

**Issue by neo22s** [flarum/core#561]
I have created a test installation and set the site as private "View discussions->Members". Then I have tried to open one of the links on private mode to see what error I got or redirected etc...

Seems cant find the 404 route ;)

Got this:
![image](https://cloud.githubusercontent.com/assets/241725/10225632/075da574-6864-11e5-8643-d12830a2fcb2.png)

**Comment by Mecvak** [comment]
I presume something better would be a "Permission Denied" kind of page?

**Comment by kirkbushell** [comment]
Depends on the requirements, really. Usually with routes you want hidden, a 404 is a more suitable response.

**Comment by Mecvak** [comment]
In that case this is already resolved probably.
In config.php change debug from true to false
  
'debug' => **false**,

**Comment by franzliedke** [comment]
This will be handled as part of #118
