### ISSUE TITLE
Confirm to Add Tags Button Disabled

### ISSUE THREAD

**Issue by aswinehart** [flarum/core#562]
<img width="619" alt="screen shot 2015-10-01 at 4 37 23 pm" src="https://cloud.githubusercontent.com/assets/10821970/10233153/e37341a4-685a-11e5-8b6e-4763c99eb443.png">

When I inspected the element, it has a disabled class. Are we able to use this soon? Thanks!
<button class="Button Button--primary hasIcon disabled" type="submit" disabled="">

**Comment by tobscure** [comment]
Check the restrictions in Admin > Tags > Settings > Required Number of Primary Tags. Looks like you've set the minimum at 6.
