### ISSUE TITLE
Translate group names on the server end

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#564]
The following strings generated from English group names need to be translated on the server end:

```
  ##
  # GLOBAL STRINGS - Translation of the following keys is handled by the server.
  ##

  # The following keys are generated from group names:
  group_admin: Admin
  group_admins: Admins
  group_guest: Guest
  group_guests: Guests
  group_member: Member
  group_members: Members
  group_mod: Mod
  group_mods: Mods
```

**Comment by franzliedke** [comment]
For installation, you mean?

**Comment by tobscure** [comment]
Nope, we still want the default group names to be translated depending on the user's locale setting, right? So the translation would happen on API serialisation.
