### ISSUE TITLE
Installation: Administrator Name field didn't allow space between words

### ISSUE THREAD

**Issue by imink** [flarum/core#565]
Version: v 0.1.0 beta

When I enter all the fields in the install page ( Notice that the Administrator Name field is John Watson within a space), then after click the button below, it raises a **Something went wrong:** with no other info.

Then I remove the space in the name field, which turn out to be successful and get into the flarum.

Anyone has met this before?

**Comment by Luceos** [comment]
We're currently at version 0.2.0 beta. Supporting an older unstable version does not make sense. Please upgrade and assert the issue is still actual.

**Comment by tobscure** [comment]
0.1.0-beta.2, actually :)

I believe this is indeed an issue.

**Comment by franzliedke** [comment]
@tobscure We're displaying the error messages now in the installer, right? That would mean this can be closed...

**Comment by tobscure** [comment]
Nah
