### ISSUE TITLE
Hardcoded primary keys in installation routine lead to fatal error

### ISSUE THREAD

**Issue by pvanhemmen** [flarum/core#566]
Hey there,

after entering all installation credentials I got the following Fatal Error after submit:

```Fatal error: Call to a member function updateLastSeen() on a non-object in /var/www/path/to/flarum/public/flarum/vendor/flarum/core/src/Forum/Middleware/LoginWithCookie.php on line 44```

A look into the `users_groups` table shows that the relation of `user_id` to `group_id` is wrong. Basically flarum assumes that the admin group will always have a primary key of 1. The server I'm on is part of a distributed server network with a MySQL ring replication. To avoid key collisions new primary keys here always start at 2 and are incremented by 3.

Since all ID's in the installation process seem to be hardcoded in ```flarum/vendor/flarum/core/src/Install/Console/InstallCommand.php``` and elswhere, the installation will never work for databases that have setup different primary key handling.

Apache/2.2.22 (Debian)
Mysql 5.5.44-0+deb7u1-log (Debian)
php 5.5
Firefox 41.0

**Comment by tobscure** [comment]
What about if we explicitly set the IDs when we create the default groups, instead of relying on auto increment? i.e. `insert into groups (id, name) values (1, 'admin'), (2, 'mod')` etc.

**Comment by Luceos** [comment]
Assuming the database settings are configured, why not simply use the Model to store each group and use their respective id's to generate the entry for users_groups?

**Comment by tobscure** [comment]
We also refer need to them by ID elsewhere in the application, via the constants on the Group class.

**Comment by Luceos** [comment]
That would then have to change. It would be fairly easy to cache those keys permanently, what do you say @franzliedke ?

**Comment by franzliedke** [comment]
I'm fine with hardcoding them during installation as Toby suggested. Will that mess with the auto-increment start value, though, when adding more groups via admin panel later?

**Comment by pvanhemmen** [comment]
Thanx for getting back on this topic. Setting the ids explicitly (during installation only, of course) should work in my case as only auto-incremented entries are affected and setting ids manually is not a problem. Its should also be possible to add more groups later on from within the admin panel (even when transferring the installation to another server with different settings ) as auto-increment will just pick up incrementing from the highest id found.

I can see the advantages of concrete model based id handling already during installation, though, as it would also cover any other cases that may arise. Just my 2 cents.

**Comment by franzliedke** [comment]
@pvanhemmen This should be fixed, please try it out with the latest dev version.
