### ISSUE TITLE
TypeError: t is null

### ISSUE THREAD

**Issue by SkyzohKey** [flarum/core#568]
Hey,
I just installed Flarum on a fresh ftp to try it, install was successfull but when i want to interact with the cms (start a post, edit settings, edit profile, change avatar, etc...) the console tells me:
```TypeError: t is null forum-m9tedt3Iehj86FXj.js:6:19556```

How can I fix this ? :x

**Comment by franzliedke** [comment]
Is this still a problem? We're hoping to have this fixed (or at least easier to debug) with the next beta, see #582.
