### ISSUE TITLE
Icon Edges Appear Fuzzy

### ISSUE THREAD

**Issue by MariusMasalar** [flarum/core#569]
They're razor sharp on mobile, but on my desktop (latest Yosemite, 1920x1080 display resolution) they appear fuzzy. I checked in Safari, Firefox, and Chrome.

It's as if the edges are fuzzy, unclear. Doesn't seem to affect the UI icons (reply, edit, etc.) just the Admin, Sticky, etc. ones.

Example screenshot:
![flarumiconfuzz](https://cloud.githubusercontent.com/assets/1610077/10251223/4edf53a4-68fd-11e5-8004-c4d60be4bc84.png)

**Comment by HavocKKS** [comment]
Hey, isn't that already fixed in beta 5? I have no white borders on my installation

**Comment by franzliedke** [comment]
Hmm, they do look okay for me, too. Chrome 50 un Ubuntu. And, more importantly, they don't have a white edge either...

@tobscure Did you remove the border at some point?

**Comment by franzliedke** [comment]
Ah, yes, he did. I found [the commit](https://github.com/flarum/core/commit/dc757fae5f4a43630447b4c6efc5fe4fbec02a53).

**Comment by HavocKKS** [comment]
@franzliedke urgh you're too fast i've just found it :D
Very cool without the white border though.

**Comment by franzliedke** [comment]
@HavocKKS Thanks for looking into it!
