### ISSUE TITLE
Enable YAML parser to detect and handle HTML tag equivalents in strings

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#574]
Tags enclosed in angle brackets will be used in strings to denote text attributes and links. The parser needs to be able to recognize these tags and apply the HTML properties to the enclosed text.

Example of bold text:
```
key: "This is some <strong>bold text</strong>."
```
```
app.trans('key', {strong: <strong/>})
```
Example of a link:
```
key: "This is <a>a link</a> to another place."
```
```
app.trans('key', {a: <a href="http://www.example.com"/>})
```
***Documentation note:***

*The l10n documents should alert translators to the existence of these tags and explain their handling. Translators should be warned that tags, like variables, should not be translated.*

**Comment by tobscure** [comment]
Implemented. The current behaviour for when a tag is present in the translation but not in the input is to ignore the tag and output its contents normally. e.g.

```
key: "This is a <i>test</i>"
app.trans('key', {i: <i/>}); // This is a <i>test</i>
app.trans('key'); // This is a test
```

Alternatively, it would be possible to automatically convert the tag into HTML, meaning that translators could add custom emphasis to their translators using basic HTML tags, without requiring alterations to Flarum's code.

```
app.trans('key'); // This is a <i>test</i>
```

However, I held off from doing this just yet, as I feel it could quickly become a slippery slope. Translators would not be able to apply **attributes** to their custom tags, which could be confusing and put pressure on us to add this functionality down the track, increasing the parser's complexity and decreasing performance. For this reason I think it might be better to strictly limit the use of "HTML" inside translations to tags supplied by the Flarum code, as the current implementation does.

What do you think?

**Comment by dcsjapan** [comment]
I hadn't even stopped to think about the possibility that translators might add tags in places where the English had none.  But I think the current approach is reasonable.

This feature is basically here to help translators reproduce the emphasis that's present in the English. Doing without it would only mean that translators would have to deal with *more* strings, some containing placeholders for other (mostly fragmentary) strings, which would be more confusing.

One question:

What happens when a translator decides to *leave out* tags that are present in the English? Will that cause the app.trans function to complain of a missing parameter?

For example, some writing systems don't have anything that corresponds to italics. The translator would probably just want to drop that tag. Will that be possible?

**Comment by tobscure** [comment]
Yeah, the translator won't complain of missing parameters :)

**Comment by dcsjapan** [comment]
Cool!

**Comment by tobscure** [comment]
Oh, another syntax idea:

```
key: "This is some {strong:bold text}."
key: "This is {link:a link} to another place."
```

So the name of the variable comes before the `:`, and the custom content comes after it. It makes the parsing much simpler, and I think it would be easier to explain as well? Since it's just an extension of the normal variable syntax.

**Comment by dcsjapan** [comment]
Hmm, I like that too.

It will be easier to explain in one sense, but slightly more complicated in another. I was planning on telling translators "Don't translate anything inside curly brackets!" as a simple rule of thumb to keep them from screwing up the placeholders. This would end up as an exception to that rule, so we'll have to be careful about making the difference clear. Would it help if we enclosed the translatable part in quotes?
```
key: "This is some {strong:"bold text"}."
key: "This is {link:"a link"} to another place."
```
Other than that, I don't see any problem with it. I do think that a syntax which avoids the HTML-style tags may be less confusing to some people.

I like the idea of using `{link:xxx}` for links. Could we go with `{bold:xxx}` and `{ital:xxx}` as well? That would make it clear even to translators with no HTML skills.

**Comment by tobscure** [comment]
Unfortunately we can't use quotes because things would mess up with the quotes around the whole translation.

> I like the idea of using {link:xxx} for links. Could we go with {bold:xxx} and {ital:xxx} as well? That would make it clear even to translators with no HTML skills.

I like it. May as well expand it to `{italics:xxx}` though :)

**Comment by dcsjapan** [comment]
Do you want me to adjust the YAML for the ones we've already done?

**Comment by tobscure** [comment]
Hmm, on second thoughts, I think the HTML syntax might actually be more intuitive. Look at this example:

```
edit_group_icon_text: "Enter the name of any {link:FontAwesome} icon class, {italics:without} the {code:fa-} prefix."
edit_group_icon_text: "Enter the name of any <a>FontAwesome</a> icon class, <em>without</em> the <code>fa-</code> prefix."
```

I think it's much easier to see what's going on in the second one. Variables and tags are two different concepts, and trying to force them into one syntax is probably not a good idea.

And I just thought of a way to make the tag parser much simpler too.

**Comment by dcsjapan** [comment]
It *is* a bit easier to see what the translator should and shouldn't touch, I agree.

Okay, we'll go with the existing pattern then!

**Comment by tobscure** [comment]
:+1:
