### ISSUE TITLE
Use span or div element for icons instead of incorrect «i».

### ISSUE THREAD

**Issue by CyberAP** [flarum/core#576]
It's a common mistake to use \<i> element for icons. If you want to promote your forum as SEO-ready then you should use an appropriate tag for icons, some of them include: \<div>, \<span>, \<img>, \<picture> with \<img>.
\<i> is a tag for text information: http://www.w3.org/International/questions/qa-b-and-i-tags

**Comment by Fastidious** [comment]
Fontawesome is implemented with `<i>`. I do not think it affects SEO much, if at all.

**Comment by tobscure** [comment]
Yeah, I don't think this is an issue

**Comment by CyberAP** [comment]
I can understand if it doesn't affect search engine ranging, but every professional would be much disappointed with this element misuse and false feature promotion.
