### ISSUE TITLE
New install in local (MAMP): I always get this message "Oops! Something went wrong on the server."

### ISSUE THREAD

**Issue by Dakoom** [flarum/core#578]
"Oops! Something went wrong on the server. Please reload the page and try again."

Everything that I try to do, every click that I made, I always get this message. Nothing is working. 
Here is a video:

https://vid.me/ECka

**Comment by mrtrez** [comment]
Hi,

Same issue for me.

**Comment by tobscure** [comment]
Please follow the [troubleshooting instructions](http://flarum.org/docs/troubleshooting/) (specifically the "Oops! Something went wrong" section) to provide more info so we can work out what's going on :)

**Comment by Dakoom** [comment]
Here it is the Response:

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /flarum/api/discussions was not found on this server.</p>
</body></html>

**Comment by tobscure** [comment]
More than likely a rewriting issue. Please read the [installation docs](http://flarum.org/docs/installation/) and search/post on the [forum](http://discuss.flarum.org) for help.

**Comment by Dakoom** [comment]
In fact, if was a missing .htaccess file in the installation root. :)
Sorry, my miastake!
