### ISSUE TITLE
API links don't include `/api` path

### ISSUE THREAD

**Issue by makenosound** [flarum/core#579]
When requesting the the `discussions#index` from the API via a URL like `http://flarum.org/api/discussion` the `links` returned are something like:

```
"links": {
    "first": "http://flarum.org/discussions?page%5Boffset%5D=0",
    "next": "http://flarum.org/discussions?page%5Boffset%5D=20"
},
```

... which doesn’t include the `/api` portion of the URL. Is that intentional or just an oversight in the URL generation?

Cheers,
Max

**Comment by tobscure** [comment]
Oversight indeed! I caught this too the other day. It's been fixed in the [dev branch](https://github.com/flarum/core/commits/composer) (i.e. will be fixed for beta 3).

**Comment by makenosound** [comment]
Ah, sweet — way of ahead of me :)
