### ISSUE TITLE
Request - error 403 forbidden

### ISSUE THREAD

**Issue by KrzysiekF** [flarum/core#581]
Hello,
When I try stick, lock, follow message. In many options in administration panel I'v get this issue.

"Oops! Something went wrong on the server. Please reload the page and try again."

This is details od the request:

<pre>
Remote Address:85.128.189.147:80
Request URL:http://forum.okenvato.com/api/discussions/1
Request Method:PATCH
Status Code:403 Forbidden
Response Headers
view source
Accept-Ranges:bytes
Connection:keep-alive
Content-Encoding:gzip
Content-Length:858
Content-Type:text/html
Date:Wed, 07 Oct 2015 06:03:10 GMT
Server:Apache/2
Vary:Accept-Encoding
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:pl-PL,pl;q=0.8,en-US;q=0.6,en;q=0.4,cs;q=0.2
AlexaToolbar-ALX_NS_PH:AlexaToolbar/alxg-3.3
Authorization:Token DN*******************kn8s
Cache-Control:no-cache
Connection:keep-alive
Content-Length:79
Content-Type:application/json; charset=UTF-8
Cookie:flarum_remember=DN7qZrlaDoVzjLGOMVJ91uh5S1FvK4ngPTqTkn8s; _ga=GA1.2.663989550.1444073422
Host:forum.okenvato.com
Origin:http://forum.okenvato.com
Pragma:no-cache
Referer:http://forum.okenvato.com/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36
Request Payload
view source
{data: {type: "discussions", id: "1", attributes: {subscription: "follow"}}}
</pre>

**Comment by tobscure** [comment]
Server specs? Probably related to #502

**Comment by KrzysiekF** [comment]
Server specification: 
<pre>

Core

PHP Version	5.5.23
Directive	Local Value	Master Value
allow_url_fopen	On	On
allow_url_include	Off	Off
always_populate_raw_post_data	Off	Off
arg_separator.input	&	&
arg_separator.output	&	&
asp_tags	Off	Off
auto_append_file	no value	no value
auto_globals_jit	On	On
auto_prepend_file	no value	no value
browscap	no value	no value
default_charset	no value	no value
default_mimetype	text/html	text/html
disable_classes	no value	no value
disable_functions	no value	no value
display_errors	Off	Off
display_startup_errors	Off	Off
doc_root	no value	no value
docref_ext	no value	no value
docref_root	no value	no value
enable_dl	On	On
enable_post_data_reading	On	On
error_append_string	no value	no value
error_log	no value	no value
error_prepend_string	no value	no value
error_reporting	22519	22519
exit_on_timeout	Off	Off
expose_php	Off	Off
extension_dir	/usr/lib/php55/modules	/usr/lib/php55/modules
file_uploads	On	On
html_errors	On	On
ignore_repeated_errors	Off	Off
ignore_repeated_source	Off	Off
ignore_user_abort	Off	Off
implicit_flush	Off	Off
include_path	.:/usr/share/pear/	.:/usr/share/pear/
log_errors	Off	Off
log_errors_max_len	1024	1024
mail.add_x_header	Off	Off
mail.force_extra_parameters	no value	no value
mail.log	no value	no value
max_execution_time	30	30
max_file_uploads	20	20
max_input_nesting_level	64	64
max_input_time	600	600
max_input_vars	1000	1000
memory_limit	64M	64M
open_basedir	no value	no value
output_buffering	no value	no value
output_handler	no value	no value
post_max_size	64M	64M
precision	14	14
realpath_cache_size	256k	256k
realpath_cache_ttl	300	300
register_argc_argv	On	On
report_memleaks	On	On
report_zend_debug	On	On
request_order	no value	no value
sendmail_from	no value	no value
sendmail_path	/usr/sbin/sendmail -t -i 	/usr/sbin/sendmail -t -i 
serialize_precision	100	100
short_open_tag	On	On
SMTP	localhost	localhost
smtp_port	25	25
sql.safe_mode	Off	Off
sys_temp_dir	no value	no value
track_errors	Off	Off
unserialize_callback_func	no value	no value
upload_max_filesize	64M	64M
upload_tmp_dir	no value	no value
user_dir	no value	no value
user_ini.cache_ttl	300	300
user_ini.filename	.user.ini	.user.ini
variables_order	EGPCS	EGPCS
xmlrpc_error_number	0	0
xmlrpc_errors	Off	Off
zend.detect_unicode	On	On
zend.enable_gc	On	On
zend.multibyte	Off	Off
zend.script_encoding	no value	no value

curl
cURL support	enabled
cURL Information	7.15.5
Age	2
Features
AsynchDNS	No
CharConv	No
Debug	No
GSS-Negotiate	Yes
IDN	Yes
IPv6	Yes
krb4	No
Largefile	Yes
libz	Yes
NTLM	Yes
SPNEGO	No
SSL	Yes
SSPI	No
Protocols	tftp, ftp, telnet, dict, ldap, http, file, https, ftps
Host	i386-redhat-linux-gnu
SSL Version	OpenSSL/0.9.8b
ZLib Version	1.2.3

DBA support	enabled
Supported handlers	gdbm cdb cdb_make inifile flatfile

dbase Version	5.1.0
DOM/XML	enabled
json support	enabled
mcrypt support	 enabled

mysql
MySQL Support	enabled
Active Persistent Links	0
Active Links	0
Client API version	5.5.40
MYSQL_MODULE_TYPE	external
MYSQL_SOCKET	/tmp/mysql.sock
MYSQL_INCLUDE	-I/usr/include
MYSQL_LIBS	-L/usr/lib -lmysqlclient

PDO drivers	sqlite, mysql, pgsql


</pre>

**Comment by tobscure** [comment]
Please wait for beta 3 when #502 will be fixed, and if you're still having trouble we'll take a deeper look then.

**Comment by KrzysiekF** [comment]
OK ... no problem, thank you :)
