### ISSUE TITLE
Add a CDN property in src/Api/Serializers/ForumSerializer.php 

### ISSUE THREAD

**Issue by pupboss** [flarum/core#583]
updated 14 Oct

Now I don't need to sync my js with CDN server:

I have deployed my site on CDN, I use a pull zone instead of a push zone ([KeyCDN](https://www.keycdn.com/?a=8362)).

If you use the pull zone site address, the login action may not worked anymore, so you are supposed to follow the rule '**deploy as you go**', I just need the .js files and avatars on CDN, so I change the js path and avatar path to CDN address.

---

```
'baseUrl' => Core::url(),
'cdnUrl' => '//cdn.your.site',
```

The .js file's size was so huge, more than 500kb, a foreign country visitors hardly have time to wait for loading.

~~Developers can write a script to sync their `assets` folder to cloud everyday~~ and set up the `views/app.blade.php` line 26 to `<script src="{{ $forum->attributes->cdnUrl . str_replace(public_path(), '', $file) }}"></script>`

My suggestion is not so good but it did works.

**Comment by huobazi** [comment]
:+1:

**Comment by Luceos** [comment]
I'd say this would be perfect for an extension.

**Comment by justjavac** [comment]
extension :100:

**Comment by Luceos** [comment]
You'd best file this request on the Flarum forum under the [features tag](https://discuss.flarum.org/t/features).
