### ISSUE TITLE
Vaprobash: /tmp/vagrant-shell: line 65: npm: command not found

### ISSUE THREAD

**Issue by zak10** [flarum/core#585]
As noted in https://github.com/flarum/core/issues/547, I am still experiencing the same error. I have the newest version of the repository and every time that I try to do a vagrant up (or vagrant provision on an already running box), I get this error.

Any thoughts on this one?

Just to clarify, line 285 of my Vagrantfile (which is what was changed in the commit that closed issue 547):
config.vm.provision "shell", path: "https://raw.githubusercontent.com/franzliedke/Vaprobash/patch-3/scripts/nodejs.sh", privileged: false, args: nodejs_packages.unshift(nodejs_version, github_url)

**Comment by franzliedke** [comment]
Hmm, I can reproduce this, too. :-/

Too bad, I had thought I had fixed it. Will investigate, thanks for the heads-up-

**Comment by franzliedke** [comment]
Found the culprit, I think. Testing my fix right now...

**Comment by franzliedke** [comment]
Works now. Fixed this [over here](https://github.com/franzliedke/Vaprobash/commit/117230cea1afcba14b934b710463c55d0be0a522).

No need for you to update anything, just run `vagrant destroy` and `vagrant up` and you should be good to go. (Make sure config.php doesn't exist...)

**Comment by zak10** [comment]
Works like a charm. Thanks!
