### ISSUE TITLE
nginx `location /` needs `index index.php`

### ISSUE THREAD

**Issue by lxg** [flarum/core#586]
When opening the Flarum home page on a fresh install without a request path in nginx (i.e. without `index.php`), the server responds with a 403 error.

After adding a `index index.php` directive to the `location /` block it works:

```
location / { try_files $uri $uri/ /index.php?$query_string; index index.php; }
```

Solution found [via UL SE](http://unix.stackexchange.com/a/105139).

Tested with nginx/1.6.2 on Ubuntu 15.04. This bug might not occur on other platforms where some sort of  `index index.php` directive is already contained in the `fastcgi_params` file.

**Comment by approached** [comment]
Do you tried this nginx config... https://github.com/flarum/flarum/blob/master/scripts/environment.sh ?

**Comment by lxg** [comment]
No, I didn’t. And I wouldn’t run a script that messes with my config. However, in my opinion, the “payload” of that script should be added to the [installation documentation](http://flarum.org/docs/installation/).

**Comment by Luceos** [comment]
The index directive should be set in the server block.

**Comment by franzliedke** [comment]
Can we do anything about this, as we do not include the `server` block in our example configuration?

**Comment by franzliedke** [comment]
Closing as stale.
