### ISSUE TITLE
Possible mail server problem at flarum.com

### ISSUE THREAD

**Issue by alexbagirov** [flarum/core#59]
Hello!

I tried to sign up on the forum located at discuss.flarum.org but didn't receive a confirmation email. After I have re-sent it, but still nothing happens. I wrote a letter to team@flarum.com but mail delivery failed. Can you check it please?

**Comment by franzliedke** [comment]
I can probably reset your password for you if you tell me your username. Please send an email to franz at [my domain](http://develophp.org).

**Comment by alexbagirov** [comment]
@franzliedke, I need to activate my account and not to reset the password. But I shoot an email for you so just check your inbox, please.
