### ISSUE TITLE
subscriptions logic error

### ISSUE THREAD

**Issue by mokecc** [flarum/core#590]
It should decrease notification count only if it is unread
![image](https://cloud.githubusercontent.com/assets/7262776/10533948/860d9218-7402-11e5-847b-b2abed04138c.png)

**Comment by franzliedke** [comment]
Please read the contribution guidelines and provide more details. For example, what version are you using? What did you do that lead to the error?

**Comment by mokecc** [comment]
I'm using the master branch on GitHub of https://github.com/flarum/subscriptions/tree/475b51760572332fb3e5c3034918fe71f451b77b extension.
If you click on a read notification, the unread count will still decrease, so we can see "-1" or lesser notifications.

**Comment by franzliedke** [comment]
That's helpful, thanks.
Are you using the master branch of Flarum, too? Or 0.1-beta.2?

**Comment by mokecc** [comment]
https://github.com/flarum/core/tree/4e5b3099f8adbf925a054fda0a8ed9859db81d93
