### ISSUE TITLE
Guest posting

### ISSUE THREAD

**Issue by hcgtv** [flarum/core#591]
Searched all the issues here, look through the forum and found one post.

http://discuss.flarum.org/d/425-guest-posting

Will there be quest posting abilities in future builds?

**Comment by Luceos** [comment]
To my knowledge Flarum at this point would allow this, so the functionality could be added from an extension. I'm not sure whether this should be part of core.. Suggestions?

**Comment by gwillem** [comment]
My guest readers are not very online-savvy and are churning like crazy on the registration step. It would be cool if somehow the entry barrier could be lowered (ie. fewer clicks) while accepting a bit more spam (especially during the startup phase of a new forum). What would it take to allow guest posts? Perhaps more people could chip in and make it a bounty feature? I can't code in PHP unfortunately but would sponsor $250 towards its development.

**Comment by luceos** [comment]
@gwillem allow users to sign up using facebook? No need to register, this extension is already available.

**Comment by gwillem** [comment]
Already have that, but still too much churn. People either don't want to register (I assume) or they try but fail (too many steps, username validation etc). The screengrabs I have recorded with mouseflow.com would be hilarious if they weren't so sad :man_facepalming: Also, my audience are digital immigrants (40y+).
