### ISSUE TITLE
Notifications show future time: "in a few seconds".

### ISSUE THREAD

**Issue by milaszewski** [flarum/core#592]
When someone have just posted the notification says:
"user posted in a few seconds"

a bit later it changes to correct "a few seconds ago"

**Comment by dcsjapan** [comment]
It sounds like something that could happen if the user's PC is running slower than the server.

@milaszewski Is your computer set to sync to a network time server?

**Comment by milaszewski** [comment]
Yes, my computers are synced to Apple Europe (time.euro.apple.com.).

**Comment by dcsjapan** [comment]
Thanks for responding ... I just wanted to rule that out as a possibility.

**Comment by tobscure** [comment]
We'll fix this by showing "just now" for any times that are in the future.
