### ISSUE TITLE
Incoming variable to the error page

### ISSUE THREAD

**Issue by mokecc** [flarum/core#593]
```html
404. That’s an error.
The requested URL /flarumone was not found on this server. 
```
to: https://github.com/flarum/core/tree/master/error

**Comment by franzliedke** [comment]
I don't understand. Can you please explain in more detail?

**Comment by franzliedke** [comment]
Do you want the 404 error page to contain the URL of the incorrect request?

**Comment by mokecc** [comment]
yes

**Comment by tobscure** [comment]
I don't think this is necessary, it's in the URL bar

**Comment by franzliedke** [comment]
Agreed.
