### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by maxyc** [flarum/core#595]
![](http://cs627626.vk.me/v627626404/234f7/79dNgvzl2oQ.jpg)
![](http://cs627626.vk.me/v627626404/23501/y5H9y9wrHH4.jpg)

http://discuss.flarum.org/d/862-international-support/100
here

**Comment by franzliedke** [comment]
Can you please give this issue a descriptive title and a detailed description?
Take a look at our [troubleshooting guidelines](http://flarum.org/docs/troubleshooting/) to learn how to report errors. :)

**Comment by Luceos** [comment]
Can't reproduce this.
