### ISSUE TITLE
Design nicer error/placeholder pages

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#596]
Remaining from #118:
- [x] Error page designs (404.html, 500.html)
- [ ] Design and handle error messages for empty sections
  - [ ] Discussion list (e.g. search, see #773 773)
  - [ ] User profile: Activity
  - [ ] User profile: Mentions (see #1489)
  - [ ] more?
- [ ] Design and handle error page for discussion not found, user not found, route not found, etc.

**Comment by franzliedke** [comment]
404 pages should contain a login form.

**Comment by tobyzerner** [comment]
Kind of also the same as flarum/framework#252 but meh

**Comment by edd--** [comment]
I guess a temporary workaround can be to have a refresh to the login page in the 403 and 404.html pages ... That's how I fixed it for the time being anyway ...

**Comment by franzliedke** [comment]
@edd-- Yep, that's a good idea!

**Comment by TristianK3604** [comment]
i have a simple idea for error pages:
![403 Forbidden Page](https://i.imgur.com/JD5IHAS.png)

**Comment by luceos** [comment]
I'd prefer to use the compiled (if possible) stylesheet and use that styling @TristianK3604 .

**Comment by franzliedke** [comment]
> I'd prefer to use the compiled (if possible) stylesheet

@luceos Why? I think it's good when error pages are self-contained, and so far that's what we have been doing...

**Comment by luceos** [comment]
I wasn't aware about that decision. I nevertheless don't think it's a big deal to include the stylesheet, if it doesn't exist it won't break the page anyway.

**Comment by tobscure** [comment]
The design aspect of this issue is already solved in https://github.com/flarum/core/commit/9392e1bec3fd1fa967e1c59dc23890631aaa997d and https://github.com/flarum/core/commit/b7c1cc5ceffb36bc990919bd749050f49f39554b

**Comment by askvortsov1** [comment]
The user mentions, posts, and discussions pages now all have empty messages.
As to custom messages for discussion not found, route not found, user not found, this should all be handled by flarum/issue-archive#206.

That leaves "too few characters = no discussions" as the only issue; as such, I will reopen https://github.com/flarum/core/issues/773 (if it's not really needed, stable bot will remove it) and close this.
