### ISSUE TITLE
[Likes] & [Mentions] More flexible handling of "you" in the subject

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#597]
In situations where the word "you" may be used in the subject of a sentence, we need to offer separate strings for all cases where "you" is present. This is to needed support languages that inflect the verb differently when it is included in a compound subject (e.g. "You and Bob like this."), which doesn't occur in English.

Currently this issue affects the Likes and Mentions extensions as described [here](http://discuss.flarum.org/d/1246-differences-between-languages-make-some-phrases-difficult-to-translate/7).

In both cases, when the list of names includes the user, the extension needs to format the output using the `_self` variant regardless of whether the array contains one or more than one username. (Currently, the "you" only gets similar treatment if there are no other names in the list.)

For the Likes extension, the plural variant is not needed in English strings involving a "you":
```
post_liked_by: "{users} likes this.|{users} like this."
post_liked_by_self: "{users} like this."            # This can be varied for pluralization.
```
For the Mentions extension, no plural variant is needed in English (due to the past tense):
```
post_mentioned_by: "{users} replied to this."       # This can be varied for pluralization.
post_mentioned_by_self:  "{users} replied to this." # This can be varied for pluralization.
```
When the English string doesn't include any plural variants, comments should be added as shown above to let the translator know where such variants can be added.

There's one caveat to this approach:

Some languages may have more than one way of pluralizing nouns, and yet rely on a "single/plural" distinction when inflecting verbs to agree with the subject. In such cases, the translator will need to use [explicit interval pluralization](http://symfony.com/doc/current/components/translation/usage.html#explicit-interval-pluralization) to avoid being forced to create duplicates of the plural string.

NOTE: This issue supersedes https://github.com/flarum/core/issues/526.

**Comment by dcsjapan** [comment]
Some updates on the status of this issue:

#### Likes:

On closer inspection, it seems this extension wasn't affected after all. The relevant strings were being generated by an `app.translator.transChoice` call, and a {count} value was already being passed back with all versions. So all we needed to do was add a comment to alert translators to the fact that the `liked_by_self` string can be pluralized. This has been done.

#### Mentions:

This one needs a bit more effort. The "mentioned-by list" builder was using an `app.translator.trans` call that needed to be converted to use `transChoice`. This has been done.

##### What remains to be done:

- The  "mentioned-by list" isn't truncated in the same manner as the "likes list" and probably should be.

- While truncating the list, the list length should be limited to prevent an "*... and one others*" situation.

- When the session user is in the list, the "You" should be moved to the front of the array.

 - This will allow the user to quickly identify the post he/she has replied to.
 - It will also prevent an unsightly capitalized "You" from appearing in the middle of the sentence.

These things can probably be accomplished by adapting some of the code from **addLikesList.js** for application to **addMentionedByList.js** so that both lists will be handled similarly.

Note: It will also be necessary to add a modal analogous to **PostLikesModal.js** to display the full list of repliers when the "mentioned-by list" is truncated.

**Comment by tobscure** [comment]
All done :)

**Comment by dcsjapan** [comment]
Wow, fast work!
