### ISSUE TITLE
Rest API does not honor user permissions

### ISSUE THREAD

**Issue by zethon** [flarum/core#599]
To reproduce, go to the Administration settings and for the "Global" group and set the "View discussions" permission to "Members".

Then authenticate a user through the REST API and then try /api/discussions or /api/posts, neither of these and a few other calls do not work even though the user has the appropriate permissions. Some of the calls return 401, others return Json: "{ data: [0] }"

**Comment by zethon** [comment]
Also, even tho the /api/forum call does work with "View discussions" set to "Members", none of the tag information is returned. Setting "View discussions" to "Everyone" will return the tag information in the /api/forum call.

**Comment by tobscure** [comment]
I believe this is fixed in master (beta 3 coming soon).

**Comment by franzliedke** [comment]
Hmm, on my local installation, I can still read discussions, even if "View discussion" is set to "Members" only.

**Comment by tobscure** [comment]
@franzliedke I can't seem to reproduce... what's your exact setup?

**Comment by franzliedke** [comment]
Latest flarum/flarum and flarum/core, as well as the english, likes, and mentions extensions.

**Comment by tobscure** [comment]
I mean, in terms of users and groups and whatnot?

**Comment by franzliedke** [comment]
Whoops. Just the default setup, it's a pretty fresh install. Admins and Mods, I set the "View discussion" permission globally, I don't have any tag-specific ones.

**Comment by tobscure** [comment]
Thanks. Reproduced. Seems to only be a problem when the Tags extension is disabled. I'll take a look.
