### ISSUE TITLE
User bio not updating

### ISSUE THREAD

**Issue by alexbagirov** [flarum/core#60]
Well, I have entered @tobscure's page at [demo.flarum.org] (http://demo.flarum.org/#/u/Toby).
![2015-04-17 22 39 11](https://cloud.githubusercontent.com/assets/6885864/7207395/9c4a5424-e552-11e4-842e-e7aa3cae5d64.png)
After I click on my nickname at the top of the page and select "Profile". It opens my profile and shows all information correctly but the bio is still Toby's.
![2015-04-17 22 40 41](https://cloud.githubusercontent.com/assets/6885864/7207416/cf2315fc-e552-11e4-91e0-4ca88123942e.png)
Of course it shows the right bio after reloading the page.

P.S.:Just have discovered that page title is also named as Toby's page.

**Comment by tobscure** [comment]
Should be fixed in new Mithril app

**Comment by alexbagirov** [comment]
Yes, seems to be fixed now. Thanks!
