### ISSUE TITLE
[Tags] Rest API needs a way to get a list of tags

### ISSUE THREAD

**Issue by zethon** [flarum/core#600]
Currently there is no API call to get a list of tags on the system. A GET /api/tags call would be nice (and make sense). It would also be nice if there was an optional param to filter primary and secondary tags.

**Comment by tarunmarkose** [comment]
I agree, this is an essential feature.


On Thursday 22 October 2015, Adalid Claure <notifications@github.com> wrote:

> Currently there is no API call to get a list of tags on the system. A GET
> /api/tags call would be nice (and make sense). It would also be nice if
> there was an optional param to filter primary and secondary tags.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/flarum/core/issues/600>.
>


-- 
-Tarun

**Comment by tobscure** [comment]
For the record, you can currently get all tags at GET /api/forum. But a separate endpoint would be nice.

**Comment by Luceos** [comment]
I'm not sure this has a high priority. I would rather put up a feature request to set up proper (public) api endpoints, so generate a list first what is needed and then complete that instead of one requested endpoint at a time. What do you think?
