### ISSUE TITLE
Loosen restrictions on MySQL username when installing

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#602]
It seems that applying alpha_dash validation to the MySQL username during installation can prevent the use of usernames required by certain PaaS implementations.

See [this thread](http://discuss.flarum.org/d/1263-an-error-in-use-mysql-paas-s-username-with-a-percent-sign-when-installtion) for an example.

Perhaps it would be best to modify or remove validation on this field?

**Comment by ekee** [comment]
it's a bug,plz help to improve.

**Comment by Luceos** [comment]
MySQL usernames with dots are allowed as well. The only (factual) limitation I could find was a length limit of 32 and "16 characters before MySQL 5.7.8".

**Comment by ekee** [comment]
Really not need for this,Cause flarum only works on Myisam,but most PaaS mysql support by the IDC are all only inodb. So...This is a Tragedy...

**Comment by franzliedke** [comment]
I just fixed this. I realize we don't use the installer right now, however it may very well serve as inspiration for an external installer tool in the future (when Composer is fully integrated), so I just went ahead...

**Comment by tobscure** [comment]
@franzliedke What do you mean we don't use the installer?

**Comment by franzliedke** [comment]
Yeah, not sure what I was thinking. Just ignore me ;)
