### ISSUE TITLE
Add Behat testing

### ISSUE THREAD

**Issue by oldskool** [flarum/core#604]
I think integrating [Behat](http://docs.behat.org/en/v2.5/) to the project to write/test user flows would be a nice addition of test cases.
With Behat you can write test scenarios like this:

    Given the following user exists:
      | id | email       |
      | 1  | foo@bar.com |
    And I am logged in as "foo@bar.com"

    When I go to "/"
    And I press the "Create new discussion" button
    Then I should see the "div#createNewDiscussion" element
   
    When I fill in the following:
      | discussionBody | Hello, this is a test post! |
    And I press the "Post discussion" button

    Then I should be on "/discussion/1"
    And I should see "Hello, this is a test post!"

As you can see, it almost reads like a story. Of course these steps need to be defined (although most of the stuff above is already available as part of the Mink bundle), but it adds very useful test cases to make sure flows like these work as expected.

I could set up a basic test suite to demonstrate this further.

**Comment by luceos** [comment]
Related to flarum/issue-archive#424 ; in dicussion with @franzliedke decided to take a first look at Behat testing as the first backend testing strategy in use.

**Comment by Luceos** [comment]
The problem with Behat for testing actual behavior of Flarum is the inability by default of Behat to test JS apps. More information [here](http://docs.behat.org/en/v2.5/cookbook/behat_and_mink.html#understanding-mink).

**Comment by tobyzerner** [comment]
So what's the path forward here? I kind of think that we should be testing our JSON-API pretty thoroughly (just with PHPUnit or whatever), and then separately testing our JS app (using Mocha or similar – I'm looking into this now).

Maybe we should consolidate this issue into flarum/issue-archive#424.
