### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by oldskool** [flarum/core#605]
I have an issue in my dev environment.

The core repo seems to be a dependency of the "flarum" repo as well. This is causing me to have both:

    /vagrant/flarum/vendor/flarum/core

As well as my own development files (the submodule) in:

    /vagrant/flarum/flarum/core

Composer seems to "prefer" the version in the `/vagrant/flarum/vendor` dir over my own files, hence it's not testable (since it's not using *my* files but the latest repo files instead).

Is there an easy way to tell composer to ignore the "root level" files and use my files instead?

**Comment by kirkbushell** [comment]
When developing, setup your own package and just set the dependency.

**Comment by tobscure** [comment]
`composer remove flarum/core`, and then use franzliedke/studio to load your local copy of flarum/core.

**Comment by Luceos** [comment]
or use repositories - path to overrule that flarum/core is a remote dependancy, it will load a local folder instead, see: https://getcomposer.org/doc/05-repositories.md#path
