### ISSUE TITLE
Oops! Something went wrong on the server. Please reload the page and try again.

### ISSUE THREAD

**Issue by Azuraxe** [flarum/core#607]
Hey All,
I have followed the guide over here about troubleshooting Flarum > http://flarum.org/docs/troubleshooting/

Unfortunately, I still do not understand what these errors mean.
I click Network > then console and see
Failed to load resource: the server responded with a status of 501 (Not Implemented)

Trying everything I receive this error. Whether it be changed a person's group, making a new group, creating tags, it all. I receive the same error.

I know there is a definite way around this but I just am too silly to see it. Any ideas?
http://prntscr.com/8vtymr
Thanks,
Mas

**Comment by franzliedke** [comment]
I'm pretty sure this is a problem with your web server not supporting PATCH requests. This was fixed in #502, which will be in the next beta version (due to be released this week, probably).

**Comment by franzliedke** [comment]
Yep, pretty sure this is it. Closing this.

In the meantime, you will have to either change hosting, or wait for the next release. :)

**Comment by dangerORclose** [comment]
Hey,
I am having this error.
But i can log in on flarum forum, but not on my own forum.
But i can on my phone and tablet. And someone else also can.
(So i can not log in or sign up on my forum without the error.)
I am using Google Chrome browser.

**Comment by Luceos** [comment]
@dangerORclose please open a support question on the official forums, most likely something is wrong with your set up; this ticket is not about specific per-user problems.

https://discuss.flarum.org/t/support
