### ISSUE TITLE
Translations not showing

### ISSUE THREAD

**Issue by oldskool** [flarum/core#608]
I just re-installed my dev environment and a fresh install of the latest repository doesn't show the proper translations, just the labels/placeholders:

![screen shot 2015-10-27 at 23 15 46](https://cloud.githubusercontent.com/assets/567664/10774311/b59bf6ee-7d00-11e5-8d50-d2ffbd34a7d0.png)

**Comment by tobscure** [comment]
Make sure the flarum/english extension is installed and enabled.

**Comment by oldskool** [comment]
@tobscure Ah OK, yeah I would definitely include English by default (or at the very least ask the user which (supported) language they want to use and install the extension for that language).

**Comment by oldskool** [comment]
I added the english extension, but it still does not show anything. I figured I may need to enable/set it in the admin panel, but I get a 404 when I go to flarum.dev/admin. Any ideas on that @tobscure or @franzliedke ?

**Comment by tobscure** [comment]
Make sure URL rewriting is set up correctly (check the installation docs for proper config)
