### ISSUE TITLE
Use quote styles as recommended by Symfony

### ISSUE THREAD

**Issue by maelsoucaze** [flarum/core#610]
In YAML files, quotes are required when the string contains special or reserved characters.

We should base these files on Symfony recommendations:

- Strings containing any of the following characters should be single-quoted:
`:`, `{`, `}`, `[`, `]`, `,`, `&`, `*`, `#`, `?`, `|`, `-`, `<`, `>`, `=`, `!`, `%`, `@`, and `\`

- Strings containing any of the following characters should be double-quoted:
`\0`, `\x01`, `\x02`, `\x03`, `\x04`, `\x05`, `\x06`, `\a`, `\b`, `\t`, `\n`, `\v`, `\f`, `\r`, `\x0e`, `\x0f`, `\x10`, `\x11`, `\x12`, `\x13`, `\x14`, `\x15`, `\x16`, `\x17`, `\x18`, `\x19`, `\x1a`, `\e`, `\x1c`, `\x1d`, `\x1e`, `\x1f`, `\N`, `\_`, `\L`, `\P`

See: http://symfony.com/doc/current/components/yaml/yaml_format.html#strings

I'm working on a PR for this, feel free to discuss to know if we should implement this or not. For information, I'm already using it on my French language pack.

**Comment by dcsjapan** [comment]
> Strings containing any of the following characters must be double-quoted:

As near as I can recall, we don't have any of those yet.

**Comment by maelsoucaze** [comment]
No, you're right, we don't. :)

**Comment by maelsoucaze** [comment]
For information, when using single-quoted strings, any single quote ' inside its contents must be doubled to escape it.

**Comment by dcsjapan** [comment]
So anything with a comma in it has to be in quotes? Sheesh. I never thought a comma was so special.

**Comment by maelsoucaze** [comment]
Yep, any characters listed above, because it's used in sequences or mappings (where a comma is used to separate list).

**Comment by dcsjapan** [comment]
Ahh, I see. Thanks for the explanation.

**Comment by tobscure** [comment]
I think that we should use double quotes instead of single quotes. Because single quotes often appear in language (apostrophes) and it's weird to have to escape them. There's no reason not to use double quotes?

**Comment by maelsoucaze** [comment]
I just follow the Symfony recommendation, and it limits double quotes:

> The double-quoted style provides a way to express arbitrary strings, by using \ to escape characters and sequences. For instance, it is very useful when you need to embed a \n or a Unicode character in a string.
> If the string contains any of the following control characters, it must be escaped with double quotes:
> `\0`, `\x01`, `\x02`, `\x03`, `\x04`, `\x05`, `\x06`, `\a`, `\b`, `\t`, `\n`, `\v`, `\f`, `\r`, `\x0e`, `\x0f`, `\x10`, `\x11`, `\x12`, `\x13`, `\x14`, `\x15`, `\x16`, `\x17`, `\x18`, `\x19`, `\x1a`, `\e`, `\x1c`, `\x1d`, `\x1e`, `\x1f`, `\N`, `\_`, `\L`, `\P`

Concerning the single quotes issue, a similar issue applies with double quotes used in a double-quoted value. For example:
- `      all_discussions_button: "Search all discussions for ''{query}''"`
- `      all_discussions_button: "Search all discussions for \"{query}\""`

Like you see, we also have to escape double quotes with two single quotes or a backdash if we choose the double quotes standard. If we want coding standards, of course.

**Comment by tobscure** [comment]
Yeah I think in our case, use of single quotes inside translations is much more common than double quotes, so I'm inclined to deviate from the Symfony recommendation and go with a sane default of double quoted strings. The double-single-quote escape is not particularly intuitive imo either, whereas most people know a backslash means "escape the next character".

Thanks for bringing it up though!

**Comment by maelsoucaze** [comment]
Or, to prevent that escape, we can use `’` instead of typewriter one `'`.

**Comment by maelsoucaze** [comment]
Okay, I will resubmit a PR to just include double quotes to special or reserved characters. :)
