### ISSUE TITLE
Group icons break responsive design

### ISSUE THREAD

**Issue by ghost** [flarum/core#612]
This was originally reported by Flame on the forum.
http://discuss.flarum.org/d/1273-fyi-graphic-display-errors

It would appear that if you have a community with more than your average groups, the icons do not keep unified neatly

![snap](https://cloud.githubusercontent.com/assets/7545839/10791932/faa2189e-7d60-11e5-9798-72ee19464d77.jpg)
![snap2](https://cloud.githubusercontent.com/assets/7545839/10791950/05fa0300-7d61-11e5-8fe2-1d1f217cbf72.jpg)

**Comment by franzliedke** [comment]
Hmm... I wonder: Is that a real issue? Why would somebody create so many groups for a user?

**Comment by Code-Name-Debian** [comment]
I would be in agreement with you as I personally see this a trivial and outside the usual norm.  Though I do know of a few sites that 'over do it'. 

 It really only becomes a 'problem' in that rare case and only if your desired goal is to compete against other developments where this wouldn't be an issue.

But by no means is this a show stopper.

**Comment by franzliedke** [comment]
Closing as stale.
