### ISSUE TITLE
is it working with php 5.6?

### ISSUE THREAD

**Issue by Alukardd** [flarum/core#617]
Hello I have server with Debian Jessie and php 5.6.

I tried to use 0.1.0-beta.2 release. After Installation wizard I got error:
Fatal error: Call to a member function updateLastSeen() on null in htdocs/flarum/vendor/flarum/core/src/Forum/Middleware/LoginWithCookie.php on line 44

Also I try to use master branch and got next error
Notice: Trying to get property of non-object in htdocs/vendor/flarum/core/src/Http/Middleware/AuthenticateWithCookie.php on line 63

Catchable fatal error: Argument 3 passed to Flarum\Http\Controller\ClientView::__construct() must be an instance of Flarum\Core\User, null given, called in htdocs/vendor/flarum/core/src/Http/Controller/ AbstractClientController.php on line 142 and defined in htdocs/vendor/flarum/core/src/Http/Controller/ClientView.php on line 119

**Comment by Code-Name-Debian** [comment]
This is interesting.  I have 2 sites using php 5.6.  I'm curious why this is affecting you and not me.  Did you download from the main site OR from the latest github build?

**Comment by Alukardd** [comment]
From GitHub a few minutes ago... Then I run ```php composer.phar update``` and then run through installation wizard.

**Comment by Code-Name-Debian** [comment]
This is likely the difference between our setup.  I'm using the current beta 2 and you're using the github.

You did download it from here?
https://github.com/flarum/flarum

The CORE report is not a complete build.

**Comment by Alukardd** [comment]
Yes from this github url.

As I  said, I also try to use relase build from github — [0.1.0-beta.2](https://github.com/flarum/flarum/releases/download/v0.1.0-beta.2/flarum-0.1.0-beta.2.zip)

**Comment by Code-Name-Debian** [comment]
Can you please provide the EXACT (full build) php version?

From the command line:  php -v

Or if you prefer, copy and paste this into a notepad and save it as phpinfo.php (make sure you name it with .php and not .txt).  Upload it to your site root and navigate to it.

<?php
// Show all information, defaults to INFO_ALL
phpinfo();
?>

**Comment by Alukardd** [comment]
[php -i](https://gist.github.com/Alukardd/3d4cdbd324407845e000)

At this moment I', trying to build php-5.5.30 from source. At with it I also got error after installation:
```Catchable fatal error: Argument 3 passed to Flarum\Http\Controller\ClientView::__construct() must be an instance of Flarum\Core\User, null given, called in /var/lib/clodo/forum/cl-web-forum-testtag-20151030-172514/htdocs/vendor/flarum/core/src/Http/Controller/AbstractClientController.php on line 142 and defined in /var/lib/clodo/forum/cl-web-forum-testtag-20151030-172514/htdocs/vendor/flarum/core/src/Http/Controller/ClientView.php on line 119```

What am i doing wrong?

**Comment by Code-Name-Debian** [comment]
As you and I are both now using beta 2 and the same php version and you're still getting this error,  I'm puzzled.

I honestly don't think you, yourself are doing anything wrong.  So please don't think that way.

I'm using both CentOS and Ubuntu.  Ubuntu being Debian base, it shouldn't be any different (especially if you're building from source).  Perhaps you found an edge case in the code.

CC: @franzliedke

**Comment by Alukardd** [comment]
No with php5.5.30 I don't try beta2 bundle.

**Comment by Alukardd** [comment]
With php-5.5.30 and 0.1.0-beta.2 release bundle, I got
```Fatal error: Call to a member function updateLastSeen() on a non-object in /var/lib/clodo/forum/cl-web-forum-testtag-20151030-172514/htdocs/flarum/vendor/flarum/core/src/Forum/Middleware/LoginWithCookie.php on line 44```

**Comment by franzliedke** [comment]
Please clarify: You're getting that error message when viewing the index page right after finishing the installer?

**Comment by Alukardd** [comment]
Yes, in all cases.

**Comment by tobscure** [comment]
Delete browser cookies and try again?

**Comment by Alukardd** [comment]
omg, are you seriously?
What installation I should try again? What version of php and what version of flarum?

**Comment by tobscure** [comment]
```
Fatal error: Call to a member function updateLastSeen() on a non-object in htdocs/flarum/vendor/flarum/core/src/Forum/Middleware/LoginWithCookie.php on line 44
```
```
Catchable fatal error: Argument 3 passed to Flarum\Http\Controller\ClientView::__construct() must be an instance of Flarum\Core\User, null given
```

These errors imply that you're making requests with an auth cookie which references a user that doesn't exist. (Perhaps still logged in from an old installation.) Hence why I suggested clearing cookies.

Failing that, I would wait for beta 3 to be released (soon).

**Comment by Alukardd** [comment]
For new installation I should delete config.php and drop database? Is it enough?

**Comment by tobscure** [comment]
Yes.

**Comment by Alukardd** [comment]
After removing lonely cookie ```flarum_remember``` nothing changed.

**Comment by Alukardd** [comment]
Why I have trouble and @Code-Name-Debian and many other has no problems?
May be I have different modules versions???

**Comment by Code-Name-Debian** [comment]
@Alukardd I can completely understand your frustration.  It is never no fun when something you want to use, fails to work.  But please understand that we are only trying to help.

**Comment by Alukardd** [comment]
I understand that anybody who answer here tries to help me. But I really don't understand what's wrong with my installation and how I can fix it or detect problem.

**Comment by Code-Name-Debian** [comment]
Let us try to dig just a little deeper.   In your config.php please change debug from false to true (if it is not already so).

  'debug' => true,

Next please add this line

ini_set('display_errors', 'On');

It may not display anything new, but there is the possibility that it could and you really have nothing to lose at this point.

**Comment by Alukardd** [comment]
I already have ```display_errors = On```

**Comment by Code-Name-Debian** [comment]
ini_set('display_errors', 'On');

As well?

**Comment by Code-Name-Debian** [comment]
If you already have that enabled in your php.ini file, then in all honesty, I'm stumped.

I can only recommend you wait until beta 3 as @tobscure has suggested.

**Comment by Alukardd** [comment]
After the night I opened the forum and maybe my cookies expired but I hadn't seen fatal error. I see only link to index.php as link I see "forum title" from my installation procedure.
I got error in browser console
```
The stylesheet http://testforum.domain.com/index.php/assets/forum-jnFgsBBIkl81J8Ut.css was not loaded because its MIME type, "text/html", is not "text/css". testforum.domain.com
SyntaxError: expected expression, got '<' forum-yjmYGPyhvQ72Qlh7.js:1:0
SyntaxError: expected expression, got '<' forum-en-VFse93tZavYupGah.js:1:0
ReferenceError: System is not defined testforum.domain.com:73:17
```

**Comment by Alukardd** [comment]
I just create clear installation of Debian 8 for test flarum, and as I can see it's works!
I'll compare this installation with previous. Before I use external MySQL server and nginx before apache...

**Comment by Code-Name-Debian** [comment]
Glad you were able to resolve this.  Perhaps the external MySQL was a factor?

**Comment by Alukardd** [comment]
At this moment I don't know what was the reason, but I'' find it.
Now I only can say that this situation is very strange.

**Comment by Alukardd** [comment]
I found cause.
My nginx redirect ```/``` ⇒ ```/index.php```, after installation flarum wrote to ```config.php``` ```'url' => 'http://testforum.domain.com/index.php'```, after it nothing works fine...
@tobscure  That's a pity.
