### ISSUE TITLE
Status reports new, when nothing is new

### ISSUE THREAD

**Issue by Code-Name-Debian** [flarum/core#618]
This happen on Flarum's own support forums.  I last checked yesterday (October 30) and cleared out all my new notices.  Today (October 31, Halloween), it says I have 6 new notices, but displays nothing.

![capture](https://cloud.githubusercontent.com/assets/7545839/10864366/68766740-7fc2-11e5-9fd5-40fd18f61762.JPG)

**Comment by Code-Name-Debian** [comment]
Pro:  Making everything (clicking the checkmark) dismissed the notice.  

Con: But this of course doesn't help discover that the underlying cause was.

**Comment by franzliedke** [comment]
This was due to the upgrade of the forum to the latest version (and caused by an old bug in maintaining the notification status). You won't see it again if you have marked all notifications as read.
