### ISSUE TITLE
I have problem with langs in BETA3

### ISSUE THREAD

**Issue by KrzysiekF** [flarum/core#622]
I have problem with langs. My admin panel looks like this:

![Image](https://api.monosnap.com/rpc/file/download?id=sq2Mb2Cz6w0ggWwlJfThxOrgLUpFiE)

**Comment by tobscure** [comment]
From the [upgrade guide](http://discuss.flarum.org/d/1331-flarum-0-1-0-beta-3-released):

> 8\. Re-enable extensions. **After enabling the English language pack, you may need to delete assets/*.js if language strings are not showing up.**

:)

**Comment by KrzysiekF** [comment]
afff ... yes, now its work :) Thank you, and Im sorry for my unnecessary question :)
