### ISSUE TITLE
Install URL of Flarum

### ISSUE THREAD

**Issue by OwlAsh** [flarum/core#629]
When u install the flarum in /flarum and open the URL, you'll see the install overview.
But when u open /flarum/u/XY (because you can ;D), you'll see the install overview too.

The problem here is, that the configuration of config.php will be wrong because it take the wrong URL.

**Comment by franzliedke** [comment]
I don't think that's a problem, because there's no way that will happen unless you manually enter the URL (and you should know what you're doing in that case).

**Comment by OwlAsh** [comment]
Maybe a nice to have (set the label) and when we have the time (haha!) then we can look again?

**Comment by Luceos** [comment]
I don't think this is an actual "issue" unless you specifically make it so ;) Therefor I'd like to close to in favor of more pressing issues. Nice of you to report this @OwlAsh, at least we are now all aware of this and can handle incoming issue that might result from it.
