### ISSUE TITLE
[Markdown] Reference-style links not working in posts

### ISSUE THREAD

**Issue by fuzzmz** [flarum/core#630]
Reference-style Markdown links aren't working.

In the following example the first markdown link (`Google`) doesn't get turned into a hyperlink once the post is made, while the second one (`this one`) works as expected:

```markdown
This [Google][1] link doesn't work while [this one](https://google.com "Google") does.
    [1]: https://google.com "Google"
```

**Comment by franzliedke** [comment]
Please take that issue up with the TextFormatter library by @s9e. That's what we're using for Markdown rendering, and it only supports a subset of Markdown (even though that word means a different thing everywhere it's used). 

That said, I'd love to have that syntax, too. :+1:

**Comment by JoshyPHP** [comment]
What's the use case for reference links in a forum? AFAIK the syntax was designed for emails (which are read in plain text and where the inline URL hurts readability) and for big documents that use named references.

Coincidentally, [I removed reference links from my TODO list earlier today](https://github.com/s9e/TextFormatter/commit/6f239df442a22f5078e9cc7eae011dcc483eec5a). Personally, I see them as cruft.

**Comment by franzliedke** [comment]
I guess it's not needed. ;)

If really necessary, somebody could create a plugin for your library, right? ;)

**Comment by fuzzmz** [comment]
Cross-posting from https://github.com/s9e/TextFormatter/issues/21#issuecomment-155704812

I have nothing against not having this feature. I only came across the issue as I've been toying with integrating @flarum as a commenting system for a @pelican powered blog, and was using the article summary as forum post contents, which in my case happened to use reference-style links.

**Comment by franzliedke** [comment]
This has been implemented in TextFormatter. Thanks, Joshy! =)

**Comment by JoshyPHP** [comment]
Yup, it's in the [0.4.4](https://github.com/s9e/TextFormatter/releases/tag/0.4.4) release along with the thing about starting ordered lists at an arbitrary number.

**Comment by franzliedke** [comment]
I [updated our version constraint](https://github.com/flarum/core/commit/61b09ac98203e178529f772bd60954d1e4440637), thanks for your work on this library!
