### ISSUE TITLE
Allow moving index (and other public files) into public/ directory

### ISSUE THREAD

**Issue by eigan** [flarum/core#632]
If someone configure their vhost wrong, could anyone go directly into the source / logs, no?

https://discuss.flarum.org/composer.json
https://discuss.flarum.org/Vagrantfile
https://discuss.flarum.org/storage/
https://discuss.flarum.org/.git/

**Comment by Luceos** [comment]
What is your question exactly? Ofcourse people can misconfigure their webserver, take for example all those laravel sites installed completely in the public directory, making the .env file world readable.

**Comment by franzliedke** [comment]
We cannot move index.php into the public directory - that would make things harder on shared hosts. :(

What we can do is improve the standard hosting configuration (and .htaccess file) that we have in our documentation (or ship with).

**Comment by tobscure** [comment]
We should also make it possible/easy to set up a public directory structure if desired.

**Comment by franzliedke** [comment]
Okay, we just need to make sure that all paths are configurable.

Best way to make sure is probably to build an alternative skeleton.

**Comment by Luceos** [comment]
This is also related to https://github.com/flarum/core/issues/692 in terms of security of downloadable files.

I agree however with @franzliedke, but I wouldn't create a new skeleton, I would simply extend the current one to allow configuration of the public folder. Can't we detect the presence of the bootstrap file by looking in the current or parent directory and go from there during installation?

**Comment by franzliedke** [comment]
I won't make it official, just build one for fun to see whether everything works. :)

**Comment by bmalex88** [comment]
Hi guys. I have just finished working on this and it works. I have a **public** folder with **index.php, api.php, admin.php**, **assets** and **.htaccess**. Everything else is moved behind, in a folder called forum

**Comment by franzliedke** [comment]
@bmalex88 That's great. What did you need to change in core to get it working?

**Comment by bmalex88** [comment]
Very few things. I will push to my fork to show you. Basically, in the index.php you have to specify a second argument for the public path (which can be avoided by using `$_SERVER['DOCUMENT_ROOT'])` in `Application->publicPath()`. I also added a few functions for getting and setting the public path just like the base path

**Comment by franzliedke** [comment]
Well, feel free to send us a pull request, where we can discuss your solution. :)

**Comment by bmalex88** [comment]
Done. I guess we can still keep the structure of flarum/flarum as it is. Just change the arguments in the _index.php, api.php_ and _admin.php _files to reflect the location of the base folder

**Comment by ryanwinchester** [comment]
I am running into this problem with `public_path` being used all over the place, but I want to specify what that is.

**Comment by bmalex88** [comment]
@ryanwinchester, I am working on this. In fact, it is done already but I need to merge it with the actual code. The base and public path are the same by default, so nobody will have to change nothing, except those who want to use a different page

**Comment by franzliedke** [comment]
@bmalex88 Looking forward to that PR. :)

**Comment by bmalex88** [comment]
I have made a PR: https://github.com/flarum/core/pull/938

**Comment by franzliedke** [comment]
Can we consider this to be done?
The only outstanding issue is files like Vagrantfile etc. being downloadable. I'd argue they should not be included in the downloadable package when we go stable (i.e. use the installer). That still leaves us with composer.json...

**Comment by tobscure** [comment]
Yes this issue is done.
