### ISSUE TITLE
Please Help me. Can't send to non-contacts

### ISSUE THREAD

**Issue by Bahal** [flarum/core#633]
Method: messages.sendMessage Result: {"_":"rpc_error","error_code":400,"error_message":"PEER_FLOOD"} Stack: Error '

Please tell me when this is going to end?
No answers by Email
Waited 45 days and still it is what it is
Don't transfer me to another topic cause I couldn't find anything.it was one but it was said ONE day!!. Please give me a short answer I'll be grateful.

**Comment by franzliedke** [comment]
I don't see how this is Flarum related. Please correct me if I'm wrong.
