### ISSUE TITLE
Cannot read property 'type' of undefined 

### ISSUE THREAD

**Issue by pillaros** [flarum/core#635]
this bug  after appears in  I manually recompile front-end code, 
the error information screen capture:
![error1 png](https://cloud.githubusercontent.com/assets/9571292/11169532/770e4540-8bf5-11e5-8627-2da2c292336b.png)

error occurrend in file flarum/core/js/lib/Store.js pushObject function
 
I use a ugly approach in  flarum/core/js/lib/Store.js 
```
 pushPayload(payload) {
    if(payload.data == null){
        payload = eval("("+payload+")")
    }
}
```

**Comment by franzliedke** [comment]
Do you still have this problem?

When did the error occur? Which response was being handled? And what did it contain?

**Comment by LuaxY** [comment]
I have the exact same error, juste after database configuration.
(DB was correctly installed, config.php is ok too)

**Comment by sebble** [comment]
I can confirm the same error on the main page after the configuration page.

The objects I see going through this function are:

```
data = Object {type: "forums", id: 1, attributes: Object, relationships: Object}
data = Object {type: "groups", id: 1, attributes: Object}
data = Object {type: "groups", id: 2, attributes: Object}
data = Object {type: "groups", id: 3, attributes: Object}
data = Object {type: "groups", id: 4, attributes: Object}
data = Object {type: "tags", id: 1, attributes: Object}
data = null
```

I could provide more information if you can tell me where to look.

**Comment by sebble** [comment]
I have downgraded PHP from 7.0.0beta to 5.6.11 and the system appears to work.  I suppose this is a migration bug in the `type: users` back-end.  #685

**Comment by tobscure** [comment]
Closing in favour of #685
