### ISSUE TITLE
Feature Request: Image upload and wysiwyg for markdown

### ISSUE THREAD

**Issue by bahuma20** [flarum/core#636]
Really need an image-upload in posts.
Generally we should add a wysiwyg editor for markdown. Maybe in the style tumblr does.

**Comment by flame05** [comment]
this is no issue!

**Comment by bahuma20** [comment]
@flame05 Don't know how to set a label "feature request"

**Comment by Luceos** [comment]
Please be aware that feature requests are not actual "issues" - problems - for this tracker. Both feature requests are also covered in the Flarum forums.
