### ISSUE TITLE
Initial issues: PHP Modules Check + Locale

### ISSUE THREAD

**Issue by kirilcvetkov** [flarum/core#638]
Hello,
I think this project is amazing and i'd like to be a part of it.
So I installed flarum using composer and had 2 issues:
1. The UI warned me about missing modules in PHP but it didn't warm me about ctype and tokenizer (I had to guess/research it). I think an extension to the modules check would be appropriate.

**Comment by Luceos** [comment]
- [Topic](https://discuss.flarum.org/d/1489-initial-issues-php-modules-check-locale).

This issue needs splitting, I am going to remove the second point because it's less specific.

**Comment by Luceos** [comment]
as long as mysql is required by default, it might be wise to either document the requirement of the mysql php module too

**Comment by franzliedke** [comment]
Hmm, are ctype and tokenizer needed for core or for more specific things of the TextFormatter-related extensions only?

**Comment by Luceos** [comment]
http://laravel.com/docs/5.1/installation#installation

- PHP >= 5.5.9
- OpenSSL PHP Extension
- PDO PHP Extension
- Mbstring PHP Extension
- Tokenizer PHP Extension

**Comment by franzliedke** [comment]
I was referring to our core, not Laravel's. ;)

We [currently](https://github.com/flarum/core/blob/6d895e6d77bcc1f92b0b29c7af50368302c79e74/src/Install/InstallServiceProvider.php#L36-L44) require the following ones:

- dom
- fileinfo
- gd
- json
- mbstring
- openssl
- pdo_mysql

**Comment by Luceos** [comment]
I know but tokenizer is listed in the Laravel requirements, so I assumed it's also required with Flarum.

Grepping one of my vendor directories including laravel/framework, it seems tokenizer is used in phpunit and phpdocumentor.

**Comment by Luceos** [comment]
Grepping the vendor of my flarum-tenancy package tokenizer is required by:

- dflydev/fig-cookies
- s9e/text-formatter
- doctrine/annotations

**Comment by franzliedke** [comment]
@s9e *ctype* and *tokenizer* are not strictly required for your package to work, right?

**Comment by franzliedke** [comment]
Just for me to remember: The [apache_get_modules() function](http://php.net/apache_get_modules) can be used to detect that mod_rewrite is disabled (in case we're running Apache).

**Comment by Luceos** [comment]
You might want to integrate this into the new Installer (see https://github.com/flarum/flarum/pull/31) as the first step in the process.

**Comment by Luceos** [comment]
s9e does not have a dependency on ctype nor tokenizer in the latest release.
Do we want to integrate webserver specific checks in Flarum?

Also I noticed the prerequisites in the installer has already been given a refactor. What else needs work for this issue to close @franzliedke ?

**Comment by franzliedke** [comment]
I wanted to explore whether we can automatically find out some rewriting issues (e.g. rewriting being disabled etc.)

**Comment by Luceos** [comment]
@franzliedke you previously (in another issue) explained that webserver configurations are a responsibility of the user/server admin. I'm not sure whether we should burden Flarum with that intelligence, unless we can do that from within a seperated installer which is deleted after installation - _suggestion_?

**Comment by franzliedke** [comment]
Yes, it is their burden. But for *prerequisites* (especially those that often cause questions) we can try to give them as many hints as possible.

**Comment by Luceos** [comment]
As prerequisites, sure +1

**Comment by franzliedke** [comment]
I'm postponing the installer hints for when we rewrite that.

As for `ctype` and `tokenizer`, both extensions are enabled by default in every PHP install, so we won't add them explicitly...
