### ISSUE TITLE
Click+dragging horizontally on the stream scrubber produces 'NaN of # posts'

### ISSUE THREAD

**Issue by barneycarroll** [flarum/core#64]
Couldn't reproduce consistently, but managed here: http://demo.flarum.org/#/d/107/update-introducing-flarum-s-fast-new-front-end/1

**Comment by tobscure** [comment]
I remember being able to reproduce this when you first reported it, but I can't seem to reproduce it anymore. Maybe it was accidentally fixed...

**Comment by barneycarroll** [comment]
WFM

**Comment by kotcrab** [comment]
This is still happening. To reproduce open any thread without answer. Click on "1 of 1 post" and start dragging horizontally. You will see NaN flashing sometimes. If you manage to release mouse when NaN is shown then post disappears completely:
![2015-09-28_2213](https://cloud.githubusercontent.com/assets/4594081/10147492/8cc02a6c-662e-11e5-8f9b-4c0c7884f567.png)

**Comment by franzliedke** [comment]
We could also hide the scrubber when there's only one post.

What do you think, @tobscure?

**Comment by tobscure** [comment]
Fixed.

@franzliedke I don't think there's a good reason to hide it.
