### ISSUE TITLE
Members cannot start discussion with global permissions restricted

### ISSUE THREAD

**Issue by jordanjay29** [flarum/core#640]
When the Start Discussion permission is restricted by group (not including Members) and the Members group has been granted permission to start discussions on selected tags, the ability for Members to start discussions across the entire board is restricted, both on the main page and inside tag pages. 

To reproduce:  
* Change global Start Discussions permission to something other than Members
* Add a new tag (restrict by tag) or edit existing
* Change tag's Start Discussions permission to Members
* Members will be unable to start discussions anywhere

**Comment by tobscure** [comment]
This is the intended behaviour with the current implementation: adding tag-specific permissions serves to *restrict* them *after* the global permissions are applied, not to grant additional permission that haven't already been granted globally. This is the simplest paradigm in terms of logic/implementation/code complexity, and I don't think we should move away from it.

However I agree that in terms of usability it's not ideal... Perhaps there are improvements we could make to the UI to make it acceptable, like:

* Explain clearly how permissions work
* Make it easier to restrict many tags with permission copy+paste, etc.
* Others...

**Comment by jordanjay29** [comment]
I think clarity is definitely needed if this is WAD. I'm a bit more used to the trinary structure of permissions of SMF (Allow/Disallow/Deny) than the binary (allow/deny) at work here. 

Perhaps disallowing groups to be selected (grey them out) in tag-specific permissions that aren't granted those permissions globally?

**Comment by tobscure** [comment]
Yeah, something like that could work.

Could you elaborate on how the trinary structure works? What's the difference between disallow and deny?

**Comment by jordanjay29** [comment]
Sure. 

SMF allows users to be part of multiple groups, just like Flarum. When a user group allows a permission, the user has access to it, even if other groups disallow it. When a user group **denies** an action, however, the user cannot access it even if another group would allow access. It's a quick and easy way to create a class of users who are restricted (troublemakers, for example) without having to restructure the whole permissions set.

**Comment by tobscure** [comment]
Thanks.

So it turns out I was actually wrong about the current implementation. In fact, tag-specific permissions do override the global permissions completely... The issue is that the "Start Discussion" button is disabled if the user can't start a discussion globally, not taking the tag-specific permissions into account (as per your report).

The good news is that I've managed to fix this! It's in amongst a mess of WIP changes at the moment, but I should push it sometime this week.

**Comment by jordanjay29** [comment]
Huzzah! Great to hear a quick resolution to this one.
