### ISSUE TITLE
User profiles not working

### ISSUE THREAD

**Issue by alexbagirov** [flarum/core#65]
Hi.

After front-end update it is not possible to open user's profile when clicking his login in the thread.

**Comment by tobscure** [comment]
Having trouble reproducing this one, are there any specific circumstances/steps that cause it?

**Comment by alexbagirov** [comment]
No, I just opening random thread and trying to open anyone's profile.

UPDATE: working sometimes, but not always.

**Comment by tobscure** [comment]
I need more info.

Any particular users it's not working for? Which browser? Do you get a white screen or does just nothing happen? Is there a JavaScript error in the console at any stage?

**Comment by franzliedke** [comment]
Cannot reproduce this, either.

**Comment by alexbagirov** [comment]
Well, it works now. I don't know what was it. Sorry.
