### ISSUE TITLE
search remembering value

### ISSUE THREAD

**Issue by Luceos** [flarum/core#650]
From discuss.flarum.org;

- visit a tag
- enter a search request, submit
- browse to another tag
- [ ] the search is remembered, ok I can live with that
- empty the search value, submit
- [ ] nothing happens, probably doesn't submit on empty values?
- way out: edit the url or click the logo to start anew on the forum

**Comment by dcsjapan** [comment]
One thing I noticed while recreating this is, if you do things in the order @Luceos describes ...

> - visit a tag
> - enter a search request, submit

The search pops you out of that tag, showing results for the entire forum. It might be nice if the search actually gave you results for the current tag first. Perhaps it would be nice if it worked this way:

Action: User submits a search from the main index.
Response: Same as current implementation.

Action: User submits a search while viewing a tag.
Response: Search dropdown displays the following information:

- Show all results for {tag}
- Search all discussions for "{query}"
- (A list of top hits from {tag})

**Comment by tobscure** [comment]
That's a nice idea, @dcsjapan.

The search not submitting if you clear the value of the field and press enter is indeed a bug. Another way out is to click the "x" on the right side of the search input.
