### ISSUE TITLE
[Flags] Alerts always indicate time as "a few seconds ago"

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#651]
I just noticed that the time info on a flag alert always reads the same: "A FEW SECONDS AGO". When you hover over the time info, the tooltip says the time is invalid. Here's an example:

![screen shot 2015-11-30 at 16 26 19](https://cloud.githubusercontent.com/assets/13129997/11465782/40e23194-977f-11e5-80aa-62b09626e6fc.png)

This is a post I made 3 minutes before the screenshot was taken, which was flagged by @Luceos about immediately after it was created. The time info in the alert doesn't seem to refer to either of those events.

**Comment by Luceos** [comment]
A Carbon object when instantiated with an argument of value NULL will default to now.
