### ISSUE TITLE
[Mentions] Notification system broke after being mentioned in a tag where i do not have access

### ISSUE THREAD

**Issue by moutonnoireu** [flarum/core#652]
After being mentioned by @Luceos in a "staff" discussion where i do not have any access :
 ![](http://i.imgur.com/6kOV7bU.png) 
![](http://i.imgur.com/WMSr0Gz.png)

The notification system broke : 
![](http://i.imgur.com/53MAbTF.gif)
---
I think that i (or any user who do not have access to a tag) simply shouldn't be notified.

**Comment by dcsjapan** [comment]
Good point! Thanks for bringing this up.
