### ISSUE TITLE
IP listing on post

### ISSUE THREAD

**Issue by Luceos** [flarum/core#657]
***1 Upvote*** Recently IP's have been added in the database for each post. It would be nice to be able to see that IP listed on the post for mods. We might make an additional right in order to access that information.

**Comment by jordanjay29** [comment]
"We might make an additional right in order to access that information." I like this for sure. Maybe part of a bigger permission once user administration comes in some form.

**Comment by dcsjapan** [comment]
:+1: for a "View IP addresses" permission.
