### ISSUE TITLE
UX : When replying to a post with solely an image, the "reply" tag won't align correctly

### ISSUE THREAD

**Issue by moutonnoireu** [flarum/core#658]
The "< luceos" should be at the top of the post.

 ![](http://i.imgur.com/9IcTWcR.png)

**Comment by franzliedke** [comment]
Hmm, well, the image should either be inline with the text like it is, or be on a separate line automatically. I'd argue for the second...

**Comment by tobscure** [comment]
Can't you just manually add a newline before the image? I'd argue the current appearance is technically correct.

**Comment by moutonnoireu** [comment]
Adding a line partially solve this, but it's ugly.

![](http://i.imgur.com/5EDlpak.png)

**Comment by Luceos** [comment]
I'm not sure this is a bug.. I would say an extension could prettify image insertions too like floating somewhere or adding padding etc..

**Comment by tobscure** [comment]
Yeah I don't think this is a bug.

**Comment by tobscure** [comment]
@franzliedke and I agree that this is the expected behaviour. We'll see if it gets annoying and reevaluate later if necessary, but for now adding lines around an image is fine.
