### ISSUE TITLE
"No Notifications" error on mobile safari

### ISSUE THREAD

**Issue by tarunmarkose** [flarum/core#659]
When I opened Notifications on mobile safari, I got an "Oops something went wrong, please reload the page" error. Reloading the page many times did not help. I spaced the reloads apart by a few hours assuming you guys were in the middle of updating the software. I had 7 unread notifications according to the badge on the icon. But the notifications page said "No Notifications". On the notifications screen, I could see the "mark all as read" button - trying to use it had no effect. 

Thereafter, I tried on the desktop.. it opened fine. Even though it too reported 7 unread on the badge, there were only 3 posts that I could see, which were actually unread/grey. Marking everything as read worked fine this time. Checked the mobile again - things were working suddenly. Something I did when marking everything as read fixed the issue.

I'm not sure if this bug report helps - but this is all I've got for now. Not exactly sure if I did something to cause this either. If I notice the issue again, I'll add details here.

My username on discuss.flarum.org is tarun.

https://www.dropbox.com/s/4spnx2e8xqj9fj1/Flarum%20notifications%20error.png?dl=0

**Comment by Luceos** [comment]
I reported the same issue on Gitter yesterday while using chrome. Noone had the same issue until @tobscure showed up and reported the same issue. So.. I'll mark this as bug and hope Toby had a moment to check the server logs for the reason of the 500 error.

**Comment by tobscure** [comment]
@Luceos do you remember if we ever got to the bottom of this?

**Comment by Luceos** [comment]
It never occurred again @tobscure I fear this was a temporary "ghost-in-the-line" thing, let's close it and hope it does not occur again.

@tarunmarkose you agree?

**Comment by tarunmarkose** [comment]
@Luceos @tobscure Yep, never happened again.

**Comment by franzliedke** [comment]
Probably the result of some deployment and session-related change on discuss.flarum.org.
