### ISSUE TITLE
New thread: the page doesn't load nothing until you refresh

### ISSUE THREAD

**Issue by Dakoom** [flarum/core#66]
as per chat:
In the demo of Flarum at demo.flarum.org - I just created a new thread called Test in the category Sandbox. Nothing happens. The browser URL change to this: http://demo.flarum.org/#/d/114/test/1, but I'm still in the discussions list view. Refreshing with that URL and I'm in the discussion now.

**Comment by franzliedke** [comment]
I can reproduce this on Chrome.

From the Console:
> Uncaught TypeError: Cannot read property 'retain' of undefined

**Comment by Dakoom** [comment]
Thank you for the additional info provided, franzliedke!

**Comment by franzliedke** [comment]
You're welcome. I'll try to find out whether I can fix this today.

**Comment by tobscure** [comment]
I've fixed this in my local copy, haven't had a chance to commit + push yet. Will do first thing on Monday.
