### ISSUE TITLE
Uncaught ReferenceError: System is not defined

### ISSUE THREAD

**Issue by HLFH** [flarum/core#662]
Hi,

Because it's closed, it's not a duplicate of that very same issue #410 I got after signing up for the first time.

So, I got also a blank page with only a title.

With kind of:

> GET https://example.com/flarum/index.php/assets/forum-197c85dd.css 
index.php:79 GET https://example.com/flarum/index.php/assets/forum-7b6a5838.js 
index.php:80 GET https://example.com/flarum/index.php/assets/forum-en-df77f08d.js 
index.php:84 Uncaught ReferenceError: System is not defined(anonymous function) @ index.php:84

What should I do?

**Comment by franzliedke** [comment]
Hmm, what is the base URL in your config.php configured to?

The URLs should not have the "index.php" in them - that might be caused by that base URL being misconfigured...

**Comment by HLFH** [comment]
Kind like that: `  'url' => 'https://example.com/flarum/index.php'`

**Comment by HLFH** [comment]
Why in http://flarum.org/docs/installation/#url-rewriting, is there 

>   location /flarum {
        deny all;
        return 404;
    }

So that's why I got 404 errors...

**Comment by HLFH** [comment]
Fixed by PR https://github.com/flarum/flarum.github.io/pull/24

**Comment by HLFH** [comment]
EDIT: I just completely misconfigured my nginx conf. between the main domain and the forum subdomain.
