### ISSUE TITLE
Locking Thread Then Sticky Thread Shows Locked For Both Badges

### ISSUE THREAD

**Issue by pxwee5** [flarum/core#667]
![](http://i.imgur.com/0vfQd3g.png)

To replicate
1. Lock thread
2. Sticky thread
3. Mouseover to confirm. 

```html
<ul class="DiscussionListItem-badges badges">
  <li class="item-sticky"><span class="Badge Badge--sticky " title="Sticky" data-original-title="Locked"><i class="icon fa fa-fw fa-thumb-tack Badge-icon"></i></span>
  </li> 
  <li class="item-locked"><span class="Badge Badge--locked " title="" data-original-title="Locked" aria-describedby="tooltip219726"><i class="icon fa fa-fw fa-lock Badge-icon"></i></span>
  </li> 
</ul>
```
Check out the html code. 

A refresh fixed the issue. Just that its abit annoying to get it in the beginning :P

Discussion Thread:
https://discuss.flarum.org/d/1584-wrong-text-for-sticky-lock-thread-popup/4

**Comment by bogdanteodoru** [comment]
I can do this one as well. Should we keep the sticky or lock icon? Or both?

**Comment by franzliedke** [comment]
The icons should stay the same - this one is just about the "title" attribute, as far as I know.

Thanks!

**Comment by tobscure** [comment]
It's likely related to a quirk of Mithril's redrawing algorithm, in which case this may not be so good for new contributors because a solid understanding of said algorithm may be necessary. I'm happy to take a look if you have no luck.

**Comment by bogdanteodoru** [comment]
I will try to solve it out (might be a good way to learn Mithril's algorithm). If I don't find a solution I will follow up.
