### ISSUE TITLE
Convert `settings` table `value` column to TEXT instead of BLOB

### ISSUE THREAD

**Issue by tobscure** [flarum/core#669]
phpMyAdmin (and possibly other clients) doesn't play nice with manual editing of BLOB fields:

![](http://i.imgur.com/dEqvBmL.png)

Is there anything that should stop us from using a TEXT field instead?

**Comment by moutonnoireu** [comment]
Nothing as BLOB is for data storage rather than simple text. TEXT is fine and readable. My SQL knowledge is little but i think that is all it is to that.

**Comment by Luceos** [comment]
### change to TEXT:

- It seems blob can be [slower](http://stackoverflow.com/a/7072160/717181). 
- If an extension wants something extreme, it can create its own table using a migration.

### keep BLOB:

- The benefit of BLOB in settings is that any extension can store anything you want. That allows for extreme flexibility.
- I was under the impression that the motto of Flarum is to keep the technical stuff out of the way from a webmaster, as such it should never matter what type any field in the database is.

**Comment by franzliedke** [comment]
It's true that BLOB is much more flexible in many ways. On the other hand, I don't think we need that kind of flexibility. TEXT is already flexible enough - it can take a lot of content, as long as that can be serialized as text.

**Comment by Luceos** [comment]
Added:

- BLOB allows storage of several GB's, giving any extension (or core) that much freedom would also mean that unexpected results can happen of disks running full.

**Comment by franzliedke** [comment]
Fixed in #684.
