### ISSUE TITLE
[Site] Add link to API Docs

### ISSUE THREAD

**Issue by jordanjay29** [flarum/core#672]
The [API Docs](http://apidocs.flarum.org/0.1.0/php/) site is extremely useful for seeing the structure of Flarum, perhaps it could be linked in the Documentation sidebar or on the *Using the API* page.

**Comment by Luceos** [comment]
@moutonnoireu for the todo on documentation.

**Comment by moutonnoireu** [comment]
Noted.

**Comment by franzliedke** [comment]
Not really a core issue, so I am closing this. If you still need it, feel free to open again on the site repository.
