### ISSUE TITLE
[Github] authentication fails in multiple ways on discuss.flarum.org

### ISSUE THREAD

**Issue by mlyle** [flarum/core#673]
Initially I got an error-- blank white window with a message  about invalid index after the redirect from github asking me whether to allow the app.  Now after clicking "sign up" and selecting to use github, it fills in my user name and has a blank email.  No matter what I fill in the email field it says "The email field is required."

**Comment by mlyle** [comment]
Initial problem report was on Safari on OSX.  Reproduced the exact same scenario, including github "invalid state" on Chrome just now.

**Comment by tobscure** [comment]
This should all be fixed in dev-master, which discuss.flarum.org is running. Can you confirm? Let me know if it's still not working.

**Comment by mlyle** [comment]
Still not working.

![image](https://cloud.githubusercontent.com/assets/90903/12160878/013eed46-b4a5-11e5-8a50-bb9e76aa81e6.png)

**Comment by mlyle** [comment]
Confirmed still broken on Chrome, Safari on OSX.

**Comment by mlyle** [comment]
I played with this more.

1. I read the code of flarum-ext-auth-github and it seems to correctly request the user:email scope.
2. My Github account definitely has authorized the scope user:email for the discuss.flarum.org 
3. It still didn't work.

Then, I made my email address public briefly.  And then it worked. (!)

I looked at the github API docs about retrieving a user's resource.  No bueno:

https://developer.github.com/v3/users/

> Note: The returned email is the user's publicly visible email address (or null if the user has not specified a public email address in their profile).

This is the correct API access to use instead:

https://developer.github.com/v3/users/emails/

**Comment by franzliedke** [comment]
Ah, nice, thanks for clarifying this!

**Comment by franzliedke** [comment]
@tobscure Shall I take care of this one?

**Comment by tobscure** [comment]
Yes please! I suppose you'll need to make an additional API request in GithubAuthController@getIdentification... the other option would be to add a github_id column to the users table and use that as the identification, then just suggest the email, forcing the user to set it manually if it's null. Similar to what we do for the Twitter auth extension.

**Comment by mlyle** [comment]
Pretty, pretty please.. If you guys fix this one I'm likely to deploy one for d-ronin/dRonin.

**Comment by franzliedke** [comment]
@mlyle I'll take a look tomorrow, or on the weekend. :)

**Comment by mlyle** [comment]
Much appreciated :)

**Comment by sijad** [comment]
sijad/flarum-ext-auth-github@a83041606c67b4720b31d7ce19a365d75a250244
this is only an example but it [almost](https://github.com/sijad/flarum-ext-auth-github/blob/a83041606c67b4720b31d7ce19a365d75a250244/src/GitHubAuthController.php#L77) fix the issue (maybe it's not a bad idea remove `AbstractOAuth2Controller` due `GitHubAuthController` overrides `handle`?)
but as @tobscure recommended, maybe `github_id` is a better idea?

**Comment by tobscure** [comment]
@sijad with regard to AbstractOAuth2Controller, what if we pass `$token` and `$provider` into `getIdentification` so that the /user/emails API request can be made there, without overriding `handle`?

**Comment by sijad** [comment]
@tobscure yes, definitely

**Comment by sijad** [comment]
@tobscure can I do this? how about [this](https://github.com/sijad/flarum-ext-auth-github/blob/a83041606c67b4720b31d7ce19a365d75a250244/src/GitHubAuthController.php#L77)?

**Comment by tobscure** [comment]
@sijad looking good, just want @franzliedke to comment if he has any better ideas than passing all that stuff into `getIdentification` :)

**Comment by franzliedke** [comment]
I'll review it. :)

**Comment by franzliedke** [comment]
Thanks again, @sijad. I simplified your proposal a bit, so that I didn't have to overwrite the `handle` method.

@mlyle A little later than planned, sorry, but you can play with it now. :) Thanks for the thorough investigation, too!

**Comment by sijad** [comment]
there were an open PR https://github.com/flarum/core/pull/849, I forgot mention this issue there, should I close that?

**Comment by franzliedke** [comment]
Hmm, one more thing: Technically, the [recommended way](https://developer.github.com/v3/#hypermedia) to access low-level GitHub API endpoints is to use hypermedia. This would mean going to the [API root](https://api.github.com/) first and then going to the URL provided in the "emails_url" field.

Right now, we construct the URL manually, which is frowned upon in REST land. Downside: one more request (although a cheap one, probably).

**Comment by kloknibor** [comment]
How do I update this fix to my flarum install :$? composer update doesn't work because it only sees the old beta...

**Comment by franzliedke** [comment]
@kloknibor You can apply the commits linked (further above) in this issue by hand, or wait for beta.5, which will come very soon (TM). :)

**Comment by kloknibor** [comment]
@franzliedke Damn that was a quick response! Thanks! And since I haven't found what you meant  and only used "composer require flarum/flarum-ext-auth-github" by ssh, so it might be better for me to wait for the new beta haha! Thanks anyway
