### ISSUE TITLE
Ask for confirmation before "Mark all as Read"

### ISSUE THREAD

**Issue by pwFoo** [flarum/core#679]
I'm logged in an able to click and write replies, but get an password prompt if I click at "Mark All as Read" button. I'm also logged in after page reload
Is it a bug?

**Comment by franzliedke** [comment]
Nope, it's the new "sudo mode". It asks you for your password for certain sensitive actions (e.g. visiting the admin panel), but only if you haven't authenticated in the last 30 minutes.

**Comment by pwFoo** [comment]
Ok, is the sudo mode configurable? Because I would disable it for mark read feature ;)
But it's great to secure the admin center ;)

**Comment by franzliedke** [comment]
Let's wait for @tobscure's opinion...

**Comment by tobscure** [comment]
Sudo mode is currently required to edit any user attributes as there are sensitive things like password, email, and groups. However, it's true that it's not ideal to require it for *everything*, like the mark-as-read time. Perhaps we should make [the check](https://github.com/flarum/core/blob/master/src/Api/Controller/UpdateUserController.php#L55) more specific depending on the contents of the `$data` array.

**Comment by franzliedke** [comment]
Okay, makes sense. It does make sense to have at least an alert popping up to confirm that users really want to mark all posts as read. Happened to me on accident once.

**Comment by tobscure** [comment]
Agreed.

**Comment by dcsjapan** [comment]
I agree that an "Are you sure you want to mark all threads as read?" sort of confirmation dialog would make sense, but asking for password confirmation seems a bit overboard. It interferes with the normal flow of forum use.

**Comment by bogdanteodoru** [comment]
Hello guys. I started implementing this.. Is not a hard thing to do but just want to get your opinion on something. 

First, I've added the text to the English locale file (core.yml), but doesn't seem to get updated in my JS code. Any clue why? Do I need to run another command or something? 

Second, do we want a modal popup like.. for example when changing the password? I have implemented a simple alert popup with Cancel/OK buttons which from my point of view does the job.

**Comment by franzliedke** [comment]
@bogdanteodoru Did you recompile the JS code? You can also try removing the JS files in the assets directory. 

I don't think we need a full modal. Using JavaScript's `confirm()` method should be enough.

**Comment by sijad** [comment]
@bogdanteodoru I think you didn't install latest dev version, please follow [this instruction](https://github.com/flarum/flarum/blob/master/CONTRIBUTING.md#development-setup), *sudo mode* isn't available in beta4, see 9896378b59b3f1d260049c162abe5786c4be8ed0

**Comment by tobscure** [comment]
Reopening, see https://github.com/flarum/core/pull/729#issuecomment-170396780

**Comment by bogdanteodoru** [comment]
We should close this. Fix in https://github.com/flarum/core/pull/735

**Comment by franzliedke** [comment]
Thanks @bogdanteodoru and @sijad!
