### ISSUE TITLE
Cannot reply after logging in

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#68]
I just visited a thread on the demo forum that I wanted to reply to, but wasn't logged in.
After logging in, the reply button still read "Cannot reply"... needs to be updated when permissions change.

**Comment by tobscure** [comment]
Yep, I noticed this too. The discussion needs to be reloaded after logging in so that the `canReply` attribute gets updated. Will do on Monday.

**Comment by franzliedke** [comment]
Seems to be fixed?

**Comment by tobscure** [comment]
It shouldn't be :P

**Comment by franzliedke** [comment]
Hmm, I cannot duplicate this behaviour now on the demo forum...

**Comment by tobscure** [comment]
Ah, I know what it is. The discussion list (in the side pane) is reloaded when you log in. So if you are doing it in one of the discussions on the first page of the discussion list, the new permissions will be loaded into the store. But if you click "load more" and do it on one of the discussions on the second page, that discussion won't be reloaded and its permissions will still be old. A bit complicated, but definitely a bug.
