### ISSUE TITLE
[Permissions|Security] members only discussions posts visible to everyone

### ISSUE THREAD

**Issue by cwildfoerster** [flarum/core#680]
***1 Upvote*** I setup flarum using the composer method to run a simple and small forum for a small group of friends. 

I initially kept the registration open, defined a group and set the permission for everything, especially "View discussions" to that group.

After everyone joined, i disabled the registration and reverted the permissions to Members again.

It works, BUT if anybody knows or guesses a username and navigates to `/u/username` the users discussion **POSTS** are clearly visible, even with mentioned other users posts, for everybody!

I think that should not happen.

**Comment by tobscure** [comment]
Yep good point.

**Comment by Luceos** [comment]
+1 the permissions should have a wider effect..

**Comment by cwildfoerster** [comment]
@Luceos they should not only be wider, but correct. setting discussions to a permission and not checking that permission at some point is just wrong and a bug.

**Comment by Luceos** [comment]
@cwildfoerster i was referring to the fact that there is no access restriction to all api endpoints. There should be a check on user profile as well for instance. That's what I meant with wider, as in more.
