### ISSUE TITLE
[Mention]Username contains non-alphanumeric character will not be parsed when being mentioned.

### ISSUE THREAD

**Issue by LimiQS** [flarum/core#686]
As the title shown, username contains non-alphanumeric character will not be parsed when being mentioned. ONLY pure alphanumeric usernames will work properly with mention plugin, or @ function. If a username contains something non-alphanumeric such as CJK Characters. Mention will not work. Leave a plain text with mention code format. (as what you seen now, just something like @的の의def#5948)

Screenshot:
![image](https://cloud.githubusercontent.com/assets/9378097/11912491/d8141db2-a679-11e5-96a5-ea8cf729dc32.png)

Environment Info: 
Flarum 0.1.0-beta.4 (update directly from beta 2, in strict accordance with documentation,with NO error or warning reported while updating)
PHP 5.6 on Apache 2.4
Flarum Plugins:
![image](https://cloud.githubusercontent.com/assets/9378097/11912505/65414106-a67a-11e5-8985-5a9fe051f360.png)

**Comment by tobscure** [comment]
Flarum doesn't support non-alphanumeric characters in usernames at the moment. See #557
