### ISSUE TITLE
Post not allowed when creating a message from a secondary tag

### ISSUE THREAD

**Issue by Averell7** [flarum/core#688]
Using 0.1.0-Beta 3 :
1) Select a primary tag
2) Start a discussion and write a message.
It works well

1) Select a secondary tag (whatever its position)
2) Start a discussion and write a message. 
3) Submit : We get the message : Discussion must have between 1 and 1 primary tags.
I tried to change the values in Tags / settings, but to no avail. 

To be able to post, the user must :
1) click on the tag
2) Add a primary tag to the discussion. It will be published ONLY if there is a primary tag and a secondary tag associated to it.But 95% of users will be unable to guess. 

Thanks for the job

Dysmas

**Comment by tobscure** [comment]
Thanks for the detailed report! This has already been reported and fixed: #424
