### ISSUE TITLE
Mobile view: No apparent way to close left menu

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#69]
...apart from clicking on the back arrow file on the right part (which then turns into the menu icon) and then clicking on the menu icon again.

In a perfect world, there would probably be two ways to close the menu: a button as well as the possibility to swipe left to hide the menu.

**Comment by tobscure** [comment]
The Ember app had some code which made any tap on the slither of page content on the right close the drawer. I forgot to transfer this over :P
