### ISSUE TITLE
UrlGenerator without prefix

### ISSUE THREAD

**Issue by LzIManD** [flarum/core#696]
> core/src/Api/UrlGenerator.php

    class UrlGenerator extends AbstractUrlGenerator
    {
        protected $prefix = 'api';
    }
> core/src/Api/Controller/ListDiscussionsController.php

    87    $document->addPaginationLinks(
            $this->url->toRoute('discussions.index'),
            $request->getQueryParams(),
            $offset,
            $limit,
            $results->areMoreResults() ? null : 0
    93  );

but,
get http://localhost:88/api/discussions?include=startUser&page%5Boffset%5D=0,
not prefix , just  

    ...
    "links": {
        "first": "https://discuss.flarum.org/discussions?include=startUser",
        "next": "https://discuss.flarum.org/discussions?include=startUser&page%5Boffset%5D=20"
     },
    ...

**Comment by Albert221** [comment]
I have reproduced this issue and it actually occurs.

**Comment by tobscure** [comment]
Merged #706
