### ISSUE TITLE
Search bar overlapping forum title

### ISSUE THREAD

**Issue by Jump3r99** [flarum/core#697]
When I set long forum title, extended search bar overlaps it. Addictionally, when it lose focus, it blinks down and goes back to its position

**Comment by tobscure** [comment]
Screenshots?

**Comment by Jump3r99** [comment]
![1](https://cloud.githubusercontent.com/assets/12465392/12070582/0795b0ec-b07e-11e5-9091-eba2131ad290.PNG)
![2](https://cloud.githubusercontent.com/assets/12465392/12070583/0798766a-b07e-11e5-81d6-f056414bae18.png)
![3](https://cloud.githubusercontent.com/assets/12465392/12070585/07c51bde-b07e-11e5-8295-2cdf7be21328.png)
![4](https://cloud.githubusercontent.com/assets/12465392/12070586/07c7b394-b07e-11e5-8f97-fe51e24a2da6.png)
![5](https://cloud.githubusercontent.com/assets/12465392/12070584/07c16688-b07e-11e5-9190-2d0f901e4ef7.png)

**Comment by tobscure** [comment]
Thanks

**Comment by moutonnoireu** [comment]
I had multiple ideas, for this issue :

1) When the title reach 33 characters (that's when it starts going crazy), put the search field in the mobile state, where there is no text or visible field, just the search icon. And when clicking it, make the search field appear in the .hero space.

2) Restrict the title to 33 characters and do not touch anything else.

3) Reduce the size of the expansion of the search field when clicked or disable his animation.

**Comment by 7h3ev1l** [comment]
I just use: 

`.Search-input input {
    width: 0px;
    padding-left: 33px;
    padding-right: 0px;
}`

![default](https://cloud.githubusercontent.com/assets/11967079/14001552/25aa733a-f14f-11e5-9950-797db7e1f1d7.png)

And when i click:
![default](https://cloud.githubusercontent.com/assets/11967079/14001568/46e185e8-f14f-11e5-8c58-020f7a23ad54.png)

**Comment by tobscure** [comment]
I think this will be a good candidate for flexbox (#848)

**Comment by viruxe** [comment]
This also happens on mobiles.
