### ISSUE TITLE
Change password page need design

### ISSUE THREAD

**Issue by Jump3r99** [flarum/core#699]
![reset](https://cloud.githubusercontent.com/assets/12465392/12070589/4f752c1c-b07e-11e5-8c10-f586a23eadf6.PNG)

I know it's low on TODO list, but please: just center 'em.

**Comment by Jump3r99** [comment]
BTW how to add tags?

**Comment by tobscure** [comment]
Duplicate of #252

**Comment by Luceos** [comment]
@jump3r99 tagging is reserved for core team members.
