### ISSUE TITLE
Error when clicking notification of moved topic

### ISSUE THREAD

**Issue by Holyphoenix** [flarum/core#70]
I get this error when I click the notification saying you had moved my "http://demo.flarum.org/#/d/109/pinned-discussion-should-be-above-me/1" topic to the sandbox.  

NotFoundHttpException inRouteCollection.php line 145:

in RouteCollection.php line 145at RouteCollection->match(object(Request)) inRouter.php line 729at Router->findRoute(object(Request)) in Router.php line 652at Router->dispatchToRoute(object(Request)) inRouter.php line 628at Router->dispatch(object(Request)) in Kernel.php line 214at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))at call_user_func(object(Closure), object(Request)) inPipeline.php line 141at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in ShareErrorsFromSession.php line 55at ShareErrorsFromSession->handle(object(Request),object(Closure)) in Pipeline.php line 125at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in StartSession.php line 61at StartSession->handle(object(Request),object(Closure)) in Pipeline.php line 125at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) inAddQueuedCookiesToResponse.php line 36at AddQueuedCookiesToResponse->handle(object(Request), object(Closure)) in Pipeline.php line 125at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in EncryptCookies.php line 40at EncryptCookies->handle(object(Request),object(Closure)) in Pipeline.php line 125at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in CheckForMaintenanceMode.php line 42at CheckForMaintenanceMode->handle(object(Request),object(Closure)) in Pipeline.php line 125at Pipeline->Illuminate\Pipeline\{closure}(object(Request))at call_user_func(object(Closure), object(Request)) inPipeline.php line 101at Pipeline->then(object(Closure)) in Kernel.php line 115at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 84at Kernel->handle(object(Request)) in index.php line 9

**Comment by tobscure** [comment]
This issue was moved to flarum/categories#2
