### ISSUE TITLE
discuss.flarum.org doesn't work without javascript

### ISSUE THREAD

**Issue by bohwaz** [flarum/core#704]
I can't login or sign up or discuss.flarum.org without Javascript, and forum browsing is somehow limited.

**Comment by dcsjapan** [comment]
Flarum is a forum script that makes particularly heavy use of Javascript. If you want to use Flarum or participate at discuss.flarum.org, you'll need to enable Javascript.

**Comment by tobscure** [comment]
We do intend to improve the noscript version of Flarum somewhat, but only in a read-only/SEO manner. Any interaction will require JavaScript. Track #189 for more information.

Also note that Flarum has a flexible architecture, so it would be possible for someone to build a traditional non-JS frontend if desired.

**Comment by bohwaz** [comment]
This is a disappointing decision frankly.

**Comment by tobscure** [comment]
There's plenty of discussion about it if you're interested:

https://discuss.flarum.org/d/79-fluxbb-joins-forces-with-flarum/8
https://discuss.flarum.org/d/84-stateless-html
