### ISSUE TITLE
Updating tags triggers "show updated discussions"

### ISSUE THREAD

**Issue by Luceos** [flarum/core#707]
The yellow bar is showing changes to threads if you modify the tags of a thread.

I'm not sure this is wanted behavior, because these threads will not be marked (strong) as changed in the list on redrawing.

I remember other related issues that had to do with the rights for the thread? Maybe we can merge this with that issue?

**Comment by tobyzerner** [comment]
Yeah this can be piled with flarum/issue-archive#404. We should just add a check so that push events are only triggered for new posts with type `comment`
