### ISSUE TITLE
FontAwesome icons not rendering correctly on mobile

### ISSUE THREAD

**Issue by Jump3r99** [flarum/core#708]
I have LG Leon with Chrome and when I go to Flarum forum (Polish language) I see Chinese chars everywhere. :P
![quickmemo _2016-01-03-21-42-09](https://cloud.githubusercontent.com/assets/12465392/12122649/a1abd376-b3dc-11e5-80f1-876564a80b24.png)

**Comment by franzliedke** [comment]
Strange. Looks like it cannot load the icon font for some reasons. Can you try with another browser?

**Comment by Jump3r99** [comment]
Tested it on "Internet" and Firefox app, it worked normally.

**Comment by dcsjapan** [comment]
Possibly related:

http://stackoverflow.com/questions/32287712/font-awesome-icons-showing-in-chinese-on-lg-g3

**Comment by Albert221** [comment]
On Samsung Galaxy Ace 3 with Android 5.1.1 on latest stable Chrome everything is fine.
![2016-01-08 21 28 29](https://cloud.githubusercontent.com/assets/4085280/12210007/4db5fe36-b657-11e5-9c71-cc6bacda7252.png)

**Comment by SKukreja** [comment]
I've noticed this issue occurs due to cross domain issues when you don't have www. in your URL, as you can see in the two screenshots. I experience this sometimes, and the inability to click/view discussions when I don't have www. The second is probably related to the api url, and may be workaroundable using htaccess, but I have no idea how.

**Comment by franzliedke** [comment]
@SKukreja Automatically redirecting to the correct base URL (with/without www) is the responsibility of the site owner...

**Comment by Luceos** [comment]
Redirection can be done with htaccess as well, no need to edit any server configuration.

**Comment by Luceos** [comment]
I assume this is a specific hosting environment issue. Please do re-open if you feel this issue remains if it's not a www vs non-www issue.
