### ISSUE TITLE
Install - NFS timeout

### ISSUE THREAD

**Issue by kfrankperson** [flarum/core#71]
When trying to install the vagrant image, everything works great until the point of mounting NFS shared folders, which fails.

![screen shot 2015-05-09 at 15 30 17](https://cloud.githubusercontent.com/assets/9014669/7550632/35f41104-f661-11e4-8292-aad38247701b.png)

**Comment by franzliedke** [comment]
Have you installed NFS? On Ubuntu it's the package "nfs-common"...
Am 09.05.2015 16:37 schrieb "Frank Pearson" <notifications@github.com>:

**Comment by kfrankperson** [comment]
Sorry should probably have said am on Mac OSX Yosemite. 

I was follow this instructions from the readme.

**Comment by franzliedke** [comment]
Please make sure NFS is installed...
Am 09.05.2015 18:13 schrieb "Frank Pearson" <notifications@github.com>:

**Comment by kfrankperson** [comment]
I will just use homestead which works straight out of the box.
