### ISSUE TITLE
Handle unauthenticated access to Settings page more gracefully

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#714]
Presently, when an unauthenticated user enters the URL for the Settings page ...

https://discuss.flarum.org/settings

... the forum redirects to the following page ...

https://discuss.flarum.org/settings?nojs=1

... and returns "Something went wrong while trying to load the full version of this site."

In this situation, Flarum should really display a "You need to be logged in to access the Settings page" error message, preferably accompanied by a login prompt.

**Comment by franzliedke** [comment]
This one should return a 404 to be closed, after that #596 will take over.
