### ISSUE TITLE
Language pack helpers

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#717]
The [current language pack bootstrap](https://github.com/flarum/flarum-ext-english/blob/483a3db56cb9ef49ef0e0abc01bd66db51797689/bootstrap.php) contains a lot of code that language pack authors will need to copy. It's hard to keep these in sync. (Thanks to @maelsoucaze for your help in this.)

I want to abstract some of the logic behind some easy to use method, which will allow us to more easily change the implementations without breaking language packs.

Input on the needed methods is welcome. /cc @maelsoucaze @dcsjapan

**Comment by dcsjapan** [comment]
@franzliedke I'm a little behind @maelsoucaze when it comes to understanding the nuts and bots of language pack creation, since I haven't any actual experience creating a language pack. (That's part of the reason why I haven't gotten around to writing up the l10n docs yet.) I'm not sure what you mean when you say "keep these in sync".

**Comment by maelsoucaze** [comment]
Yep, I agree with @dcsjapan, I don't really understand everything. But I'll be glad to help on it once explained! Concerning the l10n docs, I'll try to make some progress on it. I've been busy but I'm sure I'll find some time to work on it.

**Comment by franzliedke** [comment]
An example...

This kind of code:
~~~php
        if (file_exists($manifest = __DIR__.'/composer.json')) {
            $json = json_decode(file_get_contents($manifest), true);
            if (empty($json)) {
                throw new RuntimeException("Error parsing composer.json in $name: ".json_last_error_msg());
            }
            $locale = array_get($json, 'extra.flarum-locale.code');
            $title = array_get($json, 'extra.flarum-locale.title', $title);
        }
        if (! isset($locale)) {
            throw new RuntimeException("Language pack $name must define \"extra.flarum-locale.code\" in composer.json.");
        }
~~~
Could be simplified to something like this:
~~~php
        $pack = $event->loadLanguagePackFrom(__DIR__);
        $locale = $pack->getLocale();
        $title = $pack->getTitle();
~~~

And so on...

**Comment by tobscure** [comment]
@franzliedke Or we could just extract the whole thing into a single method?

```php
<?php

use Illuminate\Contracts\Events\Dispatcher;
use Flarum\Event\ConfigureLocales;

return function (Dispatcher $events) {
    $events->listen(ConfigureLocales::class, function(ConfigureLocales $event) {
        $event->loadLanguagePackFrom(__DIR__);
    }
};
```

**Comment by franzliedke** [comment]
Done as you suggested.

Ping @maelsoucaze: This will be relevant for language packs for beta.5. The old ones should still be compatible, but the new helper method will help in making them more upgrade-proof for the future.

**Comment by maelsoucaze** [comment]
Great!

By the way, StyleCI recommendations should be used? If so:

```php
use Illuminate\Contracts\Events\Dispatcher;
use Flarum\Event\ConfigureLocales;
```
Should be changed with:
```php
use Flarum\Event\ConfigureLocales;
use Illuminate\Contracts\Events\Dispatcher;
```

And `function(ConfigureLocales $event)` should be changed to `function (ConfigureLocales $event)`

**Comment by franzliedke** [comment]
Thanks, I [cleaned it up](https://github.com/flarum/flarum-ext-english/commit/1ebede5fd24cfea22521ad6632bc47c7de7d3064).
