### ISSUE TITLE
Opening the admin panel while logged out causes a error.

### ISSUE THREAD

**Issue by MrPowerGamerBR** [flarum/core#719]
![http://i.imgur.com/q8d8833.png](http://i.imgur.com/q8d8833.png)

Maybe I'm wrong, but shouldn't trying to open the admin panel while logged out display a error message instead of showing a "PrettyPageHandler"?

If debug is disabled, this message is shown:

![http://i.imgur.com/9An0Oy8.png](http://i.imgur.com/9An0Oy8.png)

Forum thread: https://discuss.flarum.org/d/1784-opening-the-admin-panel-while-logged-out-causes-a-error/6

**Comment by franzliedke** [comment]
Thanks a lot! This one is indeed not intended.

**Comment by franzliedke** [comment]
What needs to be done:

- Adapt the `PermissionDeniedException` to have a default code of `403`. This can be done similar to the current [`RouteNotFoundException` implementation](https://github.com/flarum/core/blob/b83c81c06e78aba5f4f5528e960ddff456826368/src/Http/Exception/RouteNotFoundException.php).
- Add a simple template for this error to the [error directory](https://github.com/flarum/core/tree/b83c81c06e78aba5f4f5528e960ddff456826368/error).
- Update the [`HandleErrors` middleware](https://github.com/flarum/core/blob/417b7f7972352f7bcc1afb75948b8e4877a80d82/src/Http/Middleware/HandleErrors.php#L55): exceptions with status code 403 should always return a pretty page, too.

**Comment by Albert221** [comment]
I'm taking this. What shall happen on debug? Whoops or this HTML page?
