### ISSUE TITLE
can see the UI to upload user image in everyone's profile page.

### ISSUE THREAD

**Issue by wutong** [flarum/core#72]
http://demo.flarum.org/#/u/Toby
I signed as my account,
but I can see the upload UI on orther's profile page

**Comment by franzliedke** [comment]
I'll take care of that. =)

**Comment by RodrigoCR** [comment]
Also I can delete the profile image on anyone's profile page.

**Comment by tobscure** [comment]
Sorry @franzliedke I couldn't resist :P
