### ISSUE TITLE
[flarum-mentions] User & post mentions cannot work with certain usernames.

### ISSUE THREAD

**Issue by imi415** [flarum/core#722]
I guess the user mention and post mention functions only recognize English-only usernames which can be matched in `src/Listener/FormatUserMentions.php` and `src/Listener/FormatPostMentions.php` by the following regex `'/\B@(?<username>[a-z0-9_-]+)#(?<id>\d+)/i'`.
Some usernames (e.g. usernames contain special characters or CJK characters) cannot be correctly identified as replies, displaying only username and a hashtag. At the beginning I thought this could be fixed by simply change the regex string which could match CJK characters, but when I tried several different expressions (e.g. '[\u4E00–\u9FCC]'), flarum threw regular expression exceptions.

**Comment by franzliedke** [comment]
This is part of #557.
