### ISSUE TITLE
Notify the old address when email address is changed

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#723]
As per the Gitter conversation beginning [here](https://gitter.im/flarum/internals?at=568c6cd8e8598dd0601550b7): when Flarum receives a request to change a user's email address, it might be a good idea to send notification to the old email address.

The message content should be something along the following lines:

```
        Hey {username}!

        Someone (hopefully you!) has requested a change of address for your account on {forum}.

        If you didn't intend to change your address, click the following link to contact an admin:
        {url}

        If you requested this change of address, please ignore this email.
```

Adding this notification will require two additions to the code:

1. A function to send the above notification to the old email address.

 - The notification should be sent concurrently with the confirmation email to the new address.

2. A function to handle the URL used for notification of a mistaken address change.

 - What happens when the new email address has been confirmed when the URL is used?
 - In particular, what happens if the new address has been used to change the password?

Considerations: If the user mistakenly changed their address, they can just ignore the confirmation email (or if worse comes to worst, they can log in and change it back). So this notification is needed mainly for situations where a user has lost control of their account.

In such cases, the user may not be able to log in to the forum, so the URL provided must be accessible to unauthenticated users. A simple form (username, old address, new address) might give admins the info they need to investigate the problem, but such a form could also be used maliciously.

Perhaps Flarum needs to send some sort of unique serial number identifying each address change?

**Comment by franzliedke** [comment]
Hmm, what's the behavior we want here? There are alternatives:

1. Send an email to the old address with a link to enter a new address.
2. Change it, send an email to the old one with a link to revert the change.

The way I see it, the first one can cause problems when the user doesn't have access to the old address anymore.
On the other hand, the second one is difficult from a security perspective: When somebody else managed to change the email address, they may have been able to wreak all kinds of havoc in the user's profile (deleting posts, trolling other people, removing the account) before the original owner manages to revert the change...

**Comment by tobscure** [comment]
With security issues, I generally like to copy what other big organisations are doing as they pay very smart people to sort out these issues. Can we investigate the behaviour of changing your email address in Facebook, Twitter, Google+, Microsoft/Skype, Apple ID, etc.?

**Comment by dcsjapan** [comment]
**Facebook: ** You add a new email address to the account and confirm it as your primary address before removing the new one. You have to enter your password to confirm the email. There's no mention of notification to the old address.

https://www.facebook.com/help/207097142662705

**Twitter: ** You change the address and enter your password to confirm the change, then confirm the new address by clicking the link in the confirmation mail. There's no mention of notification to the old address.

https://support.twitter.com/articles/15356?lang=en#update

**Google+: ** Similar to Facebook, except that they DO mention notification to the old address.

https://support.google.com/plus/answer/1045580?hl=en

**Microsoft: ** Similar to Facebook. There's no mention of notification to the old address.

http://windows.microsoft.com/en-us/windows-10/change-the-email-for-your-microsoft-account

**Apple: ** Similar to Twitter. There's no mention of notification to the old address.

https://support.apple.com/en-ap/HT202667

Only Google's help docs specifically mention sending notification to the old address. The others may or may not do this ... I wouldn't be surprised if they don't.

It sounds like Google's notification to the old address consists of a message only. If it does contain a link, I'd guess it would be a generic link to a support resource. Of course, they can get away with that because they've got those resources in place. That's the trouble with comparing what Flarum does to something like Google: their online resources are always going to be more extensive.

So ... I suppose Flarum could just send a message to the old address and leave what happens afterward up to the site admin. Wise admins will have set up a webmaster address for their domain that users can contact in an emergency. But there may be some admins who won't bother, or won't know to bother. How much hand-holding should Flarum provide?

Overall, it looks like notification to the old address is not a huge priority. Should we skip this?

**Comment by tobscure** [comment]
Discussed at decided that it won't be necessary since we're removing sudo mode and requiring the password to be entered every time you change your email (#674)
