### ISSUE TITLE
Add Monkeypatch Support

### ISSUE THREAD

**Issue by sijad** [flarum/core#728]
I used to work on a commercial forum platform for years and there was an ability to extend php classes with plugins hooks that called Monkeypatch, it's allows developers to run codes before or after of most of core classes methods. Monkeypatch can let developers do this without touching the core files and only using extensions.
for example let think a developer wants to run some codes before `Flarum\Core\Foo\FooClass::Foomethod` but it can't done by listening to events, so developer can make a php class lets call it `Acme\Bar\BarClass` which contains this:
```php
<?php
namespace Acme\Bar;
use Flarum\Core\Foo\FooClass;
class BarClass extends FooClass
{
	protected function Foomethod() {
		// do something here
		return parent::Foomethod();
	}
}
```
It can be done by using [spl_autoload_register](http://php.net/manual/en/function.spl-autoload-register.php)
see alos [Monkey patch](https://en.wikipedia.org/wiki/Monkey_patch)

**Comment by Luceos** [comment]
You might want to read up on the [IoC used in Laravel](https://laravel.com/docs/5.1/container).

**Comment by franzliedke** [comment]
Indeed. We try to follow OO principles where possible, and try to make it possible to modify behavior by injecting alternate (or decorated) instances of classes. If you have further questions like these, please post them in the forums. :)

**Comment by sijad** [comment]
I can't understand if you're interested why did you closed this? As i can see there are lots of issues taged feature so i thougth there is the right place to post this

**Comment by franzliedke** [comment]
Well, this is already possible to large extent. Also, we use this place for features that are planned to be implemented, not for dicussion. We use the forum for the latter. I hope you understand. :)
