### ISSUE TITLE
Migrator uses non studly cased namespace for extensions

### ISSUE THREAD

**Issue by Luceos** [flarum/core#732]
The [Migrator](https://github.com/flarum/core/blob/master/src/Database/Migrator.php#L249) class is formatting the namespace of extensions as lowercase:

```
exception 'ReflectionException' with message 'Class flagrow\image\upload\Migration\CreateFlagrowImagesTable does not exist'
```
When the class is:

```php
<?php namespace Flagrow\ImageUpload\Migration;

/*
* This file is part of image-upload.
*
* (c) Flagrow
*
* For the full copyright and license information, please view the license.md
* file that was distributed with this source code.
*/

use Flarum\Database\AbstractMigration;
use Illuminate\Database\Schema\Blueprint;

class CreateFlagrowImagesTable extends AbstractMigration
{
```

**Comment by Luceos** [comment]
@tobscure renamed that package to `flarum-ext-image-upload` just guess the new namespace it required :P

**Comment by tobscure** [comment]
But the prefix is truncated by the composer-installer so the extensions directory is still called flagrow-image-upload, so migrations prefix shouldn't change.

**Comment by Luceos** [comment]
I know, I would expect the namespace wouldn't matter. However the actual namespace requested (at this time is):

```php
namespace flagrow\ext\image\upload\Migration;
```
;) I'll try to patch this asap. It's bothering me.

**Comment by Luceos** [comment]
Ok, the issues encountered:

- [ ] any dash (-) is replaced with a namespace divider, this splits up the package names and vendors that might have a dash in them: `flarum-friends-the-package` originally `flarum-friends/flarum-ext-the-package` will receive namespace `Flarum\Friends\Flarum\Ext\The\Package` (ignore the prefix for now)
- the prefix `ext-` was not removed due to running a stable flarum/flarum and consequentually flarum/composer-installer.

In order to fix the issue (no 1) I suggest we re-load the composer.json name, wouldn't it be wiser anyway to have some Extension object. This can be extended later on for the marketplace functionality. @franzliedke ?

**Comment by tobscure** [comment]
Re: no 2, the latest stable version of flarum/composer-installer does remove the `ext-` prefix. Make sure you've updated and then you might need to run `composer update` once more to rename the extension directory?

**Comment by Luceos** [comment]
@tobscure 2 was not an issue ;) I shouldn't have listed it.

**Comment by franzliedke** [comment]
Fixed in https://github.com/flarum/core/commit/191589e2b1a633d92ccac57e49b8805dd23252cd.

**Comment by Luceos** [comment]
Thanks :+1: @franzliedke
