### ISSUE TITLE
API: Prevent from locking yourself out of admin group

### ISSUE THREAD

**Issue by KennethWussmann** [flarum/core#736]
Hey,

just a little improvment idea for the API.
You cannot remove the Admin-Group from yourself using the website, but you can by using the API. 
So you can lock yourself out of your Flarum-Instance.

**Comment by tobscure** [comment]
Good thinking.

**Comment by jordanjay29** [comment]
If someone has permissions and technical knowledge to fiddle around with the API, shouldn't we let them do stuff like this? Most admins are probably going to have access to set themselves back to the admin group through mysql if they goof. Just a thought.

**Comment by tobscure** [comment]
Having access as an admin to the API doesn't mean you'll have access to the MySQL database. Good example is the Flarum.com hosting service – if someone was to unset themself as admin, the only way to reverse it would be for them to contact support. Not ideal.

**Comment by franzliedke** [comment]
Should this be the case for all admins or only the root admin (a.k.a. the first user to be created)?
If so, there needs to be *some* way to demote admins (for whatever reason - e.g. if they drop out, or have abused their powers).

**Comment by franzliedke** [comment]
So... only disable this for the very last admin?

**Comment by tobscure** [comment]
Admins (root or not) should not be able to demote themselves. Non-root admins should not be able to demote the root admin.

**Comment by jordanjay29** [comment]
Ehh, I'm okay with that design choice for Flarum.com. But not for self-hosted solutions. I had a situation on a site where the root admin and user was someone who set up the site for us, and we took it over after a time. He later became a troublesome user and had to be banned. Without the ability to demote him as the root user, the site would have been destroyed. 

I think I'm going back to my original stance for self-hosted solutions: if the user has access to the API they should be able to make any changes. Flarum.com may need to diverge in this instance for their setup, and that's okay. But when we hand over keys to the software to our users, we can't keep the master for ourselves.

**Comment by tobscure** [comment]
Some good points there. Will keep thinking about this.

**Comment by johnhearfield** [comment]
This is how Slack manages teams:
https://get.slack.help/hc/en-us/articles/201912948-Owners-and-Administrators

In a sense, there are 'Super Admins' which can demote other Admins and Mods, but then who has access to demote Super Admins?
