### ISSUE TITLE
[Tags] Add ability to search for tags

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#742]
Tags should be added as a section of results in the search dropdown so that they can be quickly filtered and found.

Also, as suggested by @dcsjapan in https://github.com/flarum/core/issues/650#issuecomment-160545512:

> Action: User submits a search while viewing a tag.
> Response: Search dropdown displays the following information:
> 
> Show all results for {tag}
> Search all discussions for "{query}"
> (A listing of top hits from {tag})

**Comment by sijad** [comment]
please see https://github.com/flarum/core/issues/257#issuecomment-170273052
