### ISSUE TITLE
Fix `php flarum generate:extension`

### ISSUE THREAD

**Issue by tobscure** [flarum/core#743]

**Comment by cccRaim** [comment]
```
[Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "generate:extension" is not defined.                    
                                                                  
  Did you mean this?                                              
      generate:migration          
```
what can I do?

**Comment by franzliedke** [comment]
@cccRaim This command has been removed a long time ago. Right now, we don't offer a skeleton for extensions. You can use any of the existing extensions to get a head-start.

**Comment by cccRaim** [comment]
@franzliedke thx, I try to submit code to packagist and use dev-master to test my extension code

**Comment by datitisev** [comment]
@cccRaim Read https://discuss.flarum.org/d/1662-extension-developer-first-read

**Comment by cccRaim** [comment]
@datitisev thx, it works!

**Comment by cccRaim** [comment]
@datitisev btw, I can't visit http://apidocs.flarum.org/

**Comment by datitisev** [comment]
@cccRaim Yes, that was removed. A community version run by me can be found at  https://discuss.flarum.org/d/4421-flarum-php-api-docs.
Plese ask in Discord/forums instead of on Github, by the way. To keep everything in the same place :)
