### ISSUE TITLE
Use EmojiOne instead of Twemoji

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#744]
Quoting Toby:

> That reminds me, we should make an issue to switch the Emoji extension to [EmojiOne](http://emojione.com/) instead of Twemoji. They're much more up-to-date.

**Comment by JoshyPHP** [comment]
The new image set in EmojiOne 2.0 is gorgeous, but [their JS file](https://github.com/Ranks/emojione/blob/master/lib/js/emojione.min.js) is huge. Currently 128 KB minified.
