### ISSUE TITLE
Add dummy config.js file to English language pack

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#745]
**_1 Upvote**_ The English language pack lacks a config.js file, which (if present) would contain information from Moment.js that localizers need to deal with. Adding this file to the English language pack would make it easier for localizers to use the English pack as a basis for localization.

**Comment by maelsoucaze** [comment]
:+1:

**Comment by viruxe** [comment]
Maybe you guys just could reference this link someone: https://github.com/moment/moment/tree/develop/locale

It worked for me with just a minor edit and renaming to `config.js`.

**Comment by dcsjapan** [comment]
We could certainly add instructions to the l10n docs. However ...

This issue was created alongside https://github.com/flarum/core/issues/550 as part of [this proposal](https://discuss.flarum.org/d/1163-a-unified-approach-to-simpler-localization), which I made way back before Composer was officially a thing. The idea was to furnish localizers with a complete set of files, so they wouldn't have to do anything but translate the phrases; thus making the localization process accessible to anyone who can translate, regardless of technical background.

Since then https://discuss.flarum.org/d/1163-a-unified-approach-to-simpler-localization has become a non-issue, and Composer has changed how and where configuration information is saved. So it might be a good idea to review my original proposal from the perspective of how things stand at present.

I still believe it would be a good idea to provide a wizard to help localizers get started on a new language pack. Ideally, that should be done as part of a [translation UI](https://discuss.flarum.org/d/843-ideas-for-a-translation-ui) ... something that will require quite a lot of work (as Toby has repeatedly pointed out) and so is not very practical in the short term.

In the meantime, another option may be to provide localizers with a specialized repo that they can fork or download as a basis for their work. Up till now we've been telling folks to use the English language pack for this; but the lack of Moment.js in the English language pack makes this complicated. (Some localizers have ended up using the French language pack instead, because it's closer to the finished form).

So we need an interim solution. Of course we can certainly add detailed instructions in the l10n docs; but providing localizers with all the necessary files in a readily accessible form would be better because:

- It will reduce the amount of work all localizers will have to do by a small amount.
- It will reduce the chance the localizers will make a mistake, and so reduce support requests.
- It will make the l10n docs that much easier to write, and simpler to follow.

So at this point I'd still like to suggest that we add the config.js to the English language pack locale folder.

If there is some technical reason why we can't (or shouldn't) do that, then we could create a separate "langpack skeleton" repo that ...

- includes the English version of Moment.js, and
- adds commenting to other files (e.g. composer.json and the license file) to assist localizers

... and then write the l10n docs around the idea that they'll be using this repo as a basis.
