### ISSUE TITLE
Add URL and PATH to install form

### ISSUE THREAD

**Issue by pwFoo** [flarum/core#749]
I use a Flarum docker container behind a proxy. After install I have to change the url `http://<IP>` to `http://<my.domain.com>`. So I think it would be great to have extended / expert options during installation?

**Comment by franzliedke** [comment]
Why can't you use the domain for the installation?

And even if so, can't you change it in config.php?

**Comment by pwFoo** [comment]
I used [docker-flarum (echo511)](https://hub.docker.com/r/echo511/docker-flarum/) and url was set to `http://<internalIP>`, but official domain is needed. Because of SSL offloading I changed it to `https://flarum.example.com` and it works.

It seems Flarum detects the address? But detection can't convider the setup with reverse proxy.

**Comment by Luceos** [comment]
Maybe you should have hit the flarum installation from the definitive URL immediately? That would have prevent a lot of issues. I'm voting to close, maybe this could be added in a future installer as an advanced configuration setting?

**Comment by franzliedke** [comment]
This can be configured when installing from the console.
