### ISSUE TITLE
Decouple from Laravel

### ISSUE THREAD

**Issue by tobscure** [flarum/core#75]
From tobyzerner.com/mithril:
> Instead of using the whole framework, we will explicitly pull in components and tie everything together with a custom bootstrapping process. This will allow us to optimize performance and provide better integration with existing applications.

I thought I'd create an issue so we can (a) work out exactly what needs to be done and (b) keep track of it.

[fluxbb/fluxbb#2.0](https://github.com/fluxbb/fluxbb/tree/2.0) and [fluxbb/core](https://github.com/fluxbb/core) are obviously good inspiration :)

- [x] Implement a custom [router](https://github.com/nikic/FastRoute)
- [x] Explicitly pull in only the Illuminate components that we need
- [x] Pull in a PSR-7 implementation (probably the one by @phly, which has now moved to Zend)
- [x] Pull in a PSR-7 middleware stack ([zend-stratigility](https://github.com/zendframework/zend-stratigility)) to the skeleton repository. This will replace Laravel's HTTP kernel.
- [x] Convert the different parts (frontend, admin and API) of the app to separate middlewares that can be mounted independently. This should also speed up routing because only the routes for the proper middleware need to be parsed. (Special attention to route generation, because we do need all routes there.)
- [x] Hook this up with a container instance (an application class?) and load our service providers
- [x] Implement a config system: `config.php` for database details, everything else in a ConfigRepository (database)
- [ ] Provide integration with Laravel (possibly via a separate package), basically bridging the Symfony HTTP kernel to PSR-7.
- [x] Review and update the Composer requirements (Laravel 5.1, PHP 5.5, ...)

@franzliedke I'm dying for your input here :D I'm happy to do anything you want to delegate, I really want to get this moving :)

**Comment by Allineer** [comment]
@tobscure, look in this: https://github.com/gatakka/PGF-Router

**Comment by franzliedke** [comment]
We'll likely go with nikic's FastRouter.

**Comment by BenOvermyer** [comment]
If you're decoupling from Laravel, why not decouple from PHP?

**Comment by qrokodial** [comment]
> If you're decoupling from Laravel, why not decouple from PHP?
> - @BenOvermyer 

because Flarum needs to be able to be easily ran almost anywhere, and PHP is universally supported throughout all web hosts.

**Comment by BenOvermyer** [comment]
That's fair reasoning. MySQL datastore, then?

**Comment by franzliedke** [comment]
MySQL is supported, as are several others (the ones that Laravel's database component supports).

**Comment by BenOvermyer** [comment]
What templating engine are you using? I don't see Twig; are you using Blade at the moment?

**Comment by franzliedke** [comment]
Yep.

**Comment by BenOvermyer** [comment]
Decoupling from Laravel would be best served by using an independent templating engine. I recommend Twig, having used it to great success myself.

**Comment by franzliedke** [comment]
It's okay to use some of the Laravel components, we're just trying not to tie ourselves to its default structure too much.

**Comment by BenOvermyer** [comment]
Again, fair. My recommendation stands, though. ;)

**Comment by franzliedke** [comment]
Let's discuss the whole Twig thing on the [development forums](http://discuss.flarum.org). These kind of things are not yet set in stone, so you might convince us by listing its special powers. ;)

**Comment by BenOvermyer** [comment]
Will do! As soon as I can sign up on the forums. Getting a connection timed out error atm.

**Comment by franzliedke** [comment]
The actual decoupling from Laravel's foundation is almost finished, next up: pulling in only the components that are needed and setting them up by hand.

**Comment by franzliedke** [comment]
For anybody watching this: I just merged the `psr-7` branch into master. This will be awesome! =)

**Comment by rodrigoargumedo** [comment]
+1 :smile:

**Comment by BenOvermyer** [comment]
Fantastic. =D

**Comment by tobscure** [comment]
This is basically done - Laravel integration is another issue :)
