### ISSUE TITLE
[helpers] suggestions for new helper sets

### ISSUE THREAD

**Issue by luceos** [flarum/core#755]
This is a generic placeholder issue for documenting valuable new helpers for core. The idea is to create a few new packages that will add new helper sets. Extension developers could then simply add the dependancy for the package and use any helper component available. 

For instance the few I can think of:
- [ ] ~~pagination, select a model/endpoint and generate a paginated list automatically~~
- [x] dropdowns and other menu/navigation related elements
- [ ] color picker
- [ ] posts range selector

Related to @dcsjapan 's [comment](https://discuss.flarum.org/d/1540-flagrow-guardian-an-additional-security-layer/31).

**Comment by tobscure** [comment]
Not sure about pagination as I think we generally want to discourage it in favour of infinite scrolling/ other techniques.

Dropdowns and navigation stuff is already present (in lib/components), unless you can be more specific on exactly the kinds of things you're looking for.

**Comment by Luceos** [comment]
@tobscure really great feedback. So the user list of Guardian would also be implemented best using an infinite scrolling concept?

**Comment by dav-is** [comment]
An idea I had for this was input sliders. I'd say they are important for anything with numbers that have an upper limit.

**Comment by dcsjapan** [comment]
> So the user list of Guardian would also be implemented best using an infinite scrolling concept?

That's how I've been imagining the user list would work. It would also be good to have some filtering controls at the top, so you could type in a letter or two to filter by name, or type in a year and filter by joined date, etc.

> An idea I had for this was input sliders. I'd say they are important for anything with numbers that have an upper limit.

That sounds like it could be useful!

**Comment by Luceos** [comment]
An element what would come in handy for a future version of split would be a multi select for discussion posts. So you can select multiple posts or a range for instance.

**Comment by dav-is** [comment]
I just put in a PR for an icon selector component #855

**Comment by dcsjapan** [comment]
Would a **color picker** of some sort fit in here?

**Comment by Luceos** [comment]
@dcsjapan totally agree.

**Comment by dcsjapan** [comment]
I added a suggestion for a "staff alert email" helper here: https://github.com/flarum/core/issues/957

**Comment by franzliedke** [comment]
I am closing this. As always, we can open concrete sub-tickets when we actually intend to implement any of these, and have a detailed plan for what they would look like.
