### ISSUE TITLE
[UI] Hover a replied to conversation bug

### ISSUE THREAD

**Issue by Fastidious** [flarum/core#757]
The attached illustrates:

![Odd UI bug](https://cloud.githubusercontent.com/assets/8352292/12460846/d625cb72-bf83-11e5-941f-dc031b9eaa1d.gif)

**Comment by tobscure** [comment]
Link to the thread this is occurring in? Can you reproduce with other replies/posts, or just this one?

**Comment by Mecvak** [comment]
https://discuss.flarum.org/d/1727-what-does-pusher-do-exactly/2
Can't replicate in Firefox 43.0

**Comment by tobscure** [comment]
What browser are you able to produce it in?

**Comment by Fastidious** [comment]
I can reproduce it with latest Safari on latest OS X.

**Comment by datitisev** [comment]
Is this still a problem?
I can't reproduce this  in _Safari 9.1_ with _Mac OS X El Capitán (10.11.4)_

**Comment by Fastidious** [comment]
It appears it was fixed. It is OS X, by the way, not Mac OS X. :-)
