### ISSUE TITLE
finally is not a function error after manually compiling js files

### ISSUE THREAD

**Issue by theyaserfox** [flarum/core#759]
I have manually compiled `js` files using these commands:
```sh
$ npm install -g gulp
$ cd vendor/flarum/core
$ ./scripts/compile.sh
```
but on clicking on flag or notification icons or flag a post and click `Flag Post` I get this error:
`Uncaught TypeError: app.store.find(...).then(...).finally is not a function`

**Comment by franzliedke** [comment]
Pretty sure @tobscure [fixed this already](https://github.com/flarum/core/commit/60d78cedef82f68bba8e5a58e32750443c4399a2). Please make sure you're running the latest version.
