### ISSUE TITLE
Session Dropdown bug after clicking on other dropdowns

### ISSUE THREAD

**Issue by theyaserfox** [flarum/core#760]
I have cloned `flarum` skeleton project, downloaded `dev` version and compiled js files, then I found this bug:
When I click on Dropdowns other than `SessionDropdown` (e.g. `NotificationsDropdown`) then click on `SessionDropdown` It appears like this, with spare `Dropdown-separator`s
![screen shot 2016-01-23 at 1 29 25 pm](https://cloud.githubusercontent.com/assets/6294013/12529971/c5440996-c1d5-11e5-9881-242b6224d99d.png)
and each time I click on other `Dropdown-separator` numbers increase

**Comment by franzliedke** [comment]
Ah, thanks for the report. I had encountered it, too, but couldn't quite reproduce it consistently...

**Comment by tobscure** [comment]
Same as #754:

> See 3cec7e8 and db06b8c. Track lhorie/mithril.js#934. Basically, as of the resolution of #727, you no longer need to compile JS yourself... but if you are, you'll need to manually apply this patch to your copy of mithril.js until that issue is fixed.
