### ISSUE TITLE
Tags not hidden when they should 

### ISSUE THREAD

**Issue by Averell7** [flarum/core#761]
When you have tags with sub-tags (second level) and you use the feature "Restrict by tags", the tag doesn't disappear when it should. It is always shown, even if the discussions are not. The reason is simple : When you use "Restrict by tags", the is_restricted field, in the tags table is set to 1 for the first level tag, but NOT for the second level tags depending from the first. Set is_restricted to 1 for all the second level tags, and the behaviour is correct. 

Conclusion : When a tag with second level tags is set to restricted (is_restricted = 1) the second level tags should be set to the same value. 

Flarum 0.1.0-beta4
Php 5.5
Apache 2.4

To reproduce : Just set some secondary tags under a first level tag, and try to have it not visible, using "Restrict by tags". It does not work,

**Comment by Averell7** [comment]
I would add a design question : 
I would have expected secondary tags to inherit there properties from the primary tags, but it does not work. 
Once I have set is_restricted to 1 for the secondary tags (see above), then they appear in the permissions window, with permissions set to administrators only, and I have to set the permissions for each of them. We will end in a totally unusable permissions window. With 12 primary tags and about 3 secondary tags for each, we have 36 columns. 
I think in the Permissions window, only primary tags should appear and secondary tags should inherit everything from the primary tag. Otherwise they are not really secondary.

**Comment by jordanjay29** [comment]
Hmm, maybe nested secondary tags should import the permissions of their parent primary tag when added to the permissions screen, and until that time inherit the permissions of their parent primary tag. I can definitely see use cases for having different permissions for nested secondary tags, however.

**Comment by Averell7** [comment]
The best schema could then be : 

* By default : Nested secondary tags don't appear in the permissions screen and inherit permissions from their parent
* If desired, they can be added to the permissions screen, just like primary tags, and then they would have their own permissions. 

At a technical level : 

[code]
    if parent_id != null  and is_restricted == 0 :
          - inherits permissions from the parent
          - doesn't appear in the permissions screen
    elif parent_id != null and is_restricted == 1 :
         - appears in the permissions screen
         - gets its own persissions scheme

**Comment by tobscure** [comment]
This has been fixed in https://github.com/flarum/flarum-ext-tags/commit/5d1785b38561ba5386f2317427ccc45fc5e423c1
