### ISSUE TITLE
update .gitattributes exluding files for distribution

### ISSUE THREAD

**Issue by Luceos** [flarum/core#762]
This makes the distribution version smaller.

When using `composer install --prefer-dist` the distribution file is used - a zip generated. This archive file will automatically not have the files excluded by using export-ignore in the .gitattributes file.

**Comment by tobscure** [comment]
Which files should be excluded?

**Comment by Luceos** [comment]
Explaining the "feature" every file/directory that is not required for the functionality of the code:

- i'd keep license because it should be redistributed with the code
- all documentation files can go
- all tests and mocks

I hope this clarifies this functionality, if not please comment. I'd have to come up with a better clarification when I have a bit more time ;)
