### ISSUE TITLE
Rewrite extensions page info message

### ISSUE THREAD

**Issue by Luceos** [flarum/core#765]
Admin extensions page mentions:

> In the meantime, if you manage to get your hands on a new extension, simply drop it in your forum's extensions directory.

This leads to a lot of questions of why it's not working.

> You have to use composer in ssh/bash to get an extension working properly. Composer automatically generates a "map" of all code, without using composer the code in the extension will not be available to Flarum.

**Comment by franzliedke** [comment]
This has already been fixed a few days ago when @dcsjapan [extracted these strings](https://github.com/flarum/flarum-ext-english/pull/63) to make them translateable.

**Comment by Luceos** [comment]
Cool, couldn't find that change anywhere.
