### ISSUE TITLE
Accentuated characters break the link to a user

### ISSUE THREAD

**Issue by Averell7** [flarum/core#767]
Although this bug is related to :  Slug transliteration #194, I create a new issue because it is really different, it is a question of transliteration only (I may be wrong on that point)

Suppose the user : Béatrice
In a message, you want to create a link to her message :
@Béatrice#12

In the text, you will see : @Béatrice#12, and the link is not created. 

The reason is transliteration. 
Transliteration is used for user names. Try :
Create a user : Beatrice
Try to change it to : Béatrice. Refused with message : *User name already in use.*
Try in two steps : 
1) Change Beatrice to Béatrice1
2) Change Béatrice1 to Béatrice
It works. 

New test : 
1) User Beatrice (without accent). Create a message with a link to Beatrice. 
2) Change Beatrice to Béatrice : The previously created link continues to work, but you cannot create a new link to Béatrice. The working link is written : 
`<a href="/d/7/43" class="PostMention" data-id="68">Beatrice</a>`
In the texte it appears like : Beatrice (without accent)

If you let the mouse on the link, you will see in the popup : "Béatrice : Blablabla..."  with accent on Béatrice. 

This mixing of two types of representation of the user (with or without accent) is the reason of the bug. 

Solution : when creating a link to user, use the same type or transliteration which is used when creating the references to the posts.

**Comment by tobscure** [comment]
Thanks for the report. As discussed in #832 and #557, we've made a decision to disallow non-ASCII characters in usernames.
