### ISSUE TITLE
[Subscriptions] System setting to receive email notifications for every new discussion

### ISSUE THREAD

**Issue by IvoPereira** [flarum/core#768]
Hello,

I've been trying out Flarum for my development team discussion boards, and so far it looks awesome.

However it would be great if we could be notified of every post made in the forums through email, as we are not constantly checking the forums.

Is it possible or planned at any future release? If not, I would love to get my hands dirty and create an extension for it.

Thanks

**Comment by Luceos** [comment]
Not sure whether this should be part of core instead of an extension, @flarum/core ?

**Comment by tobscure** [comment]
Part of the Subscriptions extension

**Comment by Luceos** [comment]
@tobscure ha, yes that suits subscriptions perfectly!

**Comment by oscarotero** [comment]
:+1:

**Comment by oscarotero** [comment]
I really need this feature. Is planed to add a "Automatically follow all new discussions" to the Suscriptions extension?

**Comment by kulga** [comment]
This can be mitigated somewhat by 
* Automatically follow discussions that I reply to - True
*  Someone posts in a discussion I'm following - True

I don't know about a **Automatically follow all new discussions** though. That would flood the discussions with Following badges ![](http://i.imgur.com/S7RbVGG.png) which doesn't seem like good design..

Perhaps in the notifications a option for "Someone makes a post" 
-- Which would include new discussions and their initial post

**Comment by oscarotero** [comment]
In my use case, I'd like to use the forum as a replacement for google groups, so I think this feature is important because users are lazy to enter in the forum to search new discussions.

**Comment by oscarotero** [comment]
I've created a pull request with this feature. https://github.com/flarum/flarum-ext-subscriptions/pull/9
Any suggestion is welcome.

**Comment by tobscure** [comment]
> @kulga I don't know about a Automatically follow all new discussions though. That would flood the discussions with Following badges  which doesn't seem like good design..

I'm thinking this too... @oscarotero your PR looks great from a technical point of view but I'm not sure if that's what we want to do from a design POV. Keen to hear others' thoughts and will think more deeply about it myself when I have a chance, but I suspect Kulga's suggestion for a notifications option for "Someone makes a post" would be a better approach?

**Comment by franzliedke** [comment]
> I suspect Kulga's suggestion for a notifications option for "Someone makes a post" would be a better approach?

Sounds better, yes. But that's going to cause a lot of load - maybe it should be an extension instead?

**Comment by oscarotero** [comment]
The problem with "Someone makes a post" is that users cannot unfollow a discussion, I other words: stop receiving emails with new posts of a discussión. Am I wrong?

**Comment by oscarotero** [comment]
And from my point of view, as a designer, I think it's unneccesary to be so explicit about which discussions are followed and which not. This is a preference of the user (like, for example, the notifications in github issues). The star icon is used to highlight things, not to follow.

**Comment by youds** [comment]
Is there any status of this availability in Flarum?

**Comment by franzliedke** [comment]
To be honest, I am really unsure about adding this, unless we add support for queue workers / background jobs first.

**Comment by youds** [comment]
Hi

Filters such as "new posts from new users" could make it more popular as well as organising who receives what, like "mods a, b and c receive posts from forum 1 and 2" etc.

This is essential; board management especially with multiple boards can be really frustrating! I've used one of the extension modules for now. Some 3rd party app monitoring service.

**Comment by youds** [comment]
If I can be of any help at all, I will - is there any quick start guides for people wanting to fork the project?

**Comment by datitisev** [comment]
@youds You can find a brief guide on contributing to Flarum at https://flarum.org/docs/contributing.html#development-setup

**Comment by youds** [comment]
Thanks, I will enjoy this project :)

**Comment by franzliedke** [comment]
> Filters such as "new posts from new users" could make it more popular as well as organising who receives what, like "mods a, b and c receive posts from forum 1 and 2" etc.

That's not the topic of this issue, and well suited for extension space. :grinning: 

Looking forward to your contributions!

**Comment by luceos** [comment]
Some thoughts I had about this:

- We shouldn't want cron/queue functionality in core by default (please note flagrow/console for scheduled tasks exists and bokt/flarum-queue for queue functionality).
- Sending large quantities of mail should really be pushed to a queue (not scheduled tasks please).

With both of the above in mind I'd say this should really be a third party extension. Whoever builds that can use said packages for faster prototyping and development.

In addition if you want to be notified of new posts as a team and use something like discord or slack, I can recommend the reflar/webhooks extension.

**Comment by franzliedke** [comment]
> We shouldn't want cron/queue functionality in core by default

Why not? It's absolutely an infrastructure concern and potentially useful for many extensions; and there are still default adapters that work well even on shared hosts.

> Sending large quantities of mail should really be pushed to a queue (not scheduled tasks please).

Absolutely - and we already do so in some of our official extensions.

**Comment by luceos** [comment]
@franzliedke most likely this discussion about cron/queues should be separated into its own issue ;) I'd gladly pull the necessary changes into core if we want it though.

**Comment by tobscure** [comment]
> most likely this discussion about cron/queues should be separated into its own issue

https://github.com/flarum/core/issues/978

> Why not? It's absolutely an infrastructure concern and potentially useful for many extensions; and there are still default adapters that work well even on shared hosts.

Agreed

> I'd gladly pull the necessary changes into core if we want it though.

Yes please!

**Comment by franzliedke** [comment]
After discussion in today's team meeting, I will close this issue and the corresponding pull requests. The feature itself (allowing users to receive emails about *every new discussion*) is probably not feasible for large forums, and - where it's feasible - probably a nice concern, so not suitable for most forums. Therefore, we decided this belongs into third-party extensions concern.

Don't worry, though - there are several good news for you:
- With the imminent beta.11 release, Flarum's core itself will use its new queueing functionality to offload expensive tasks like sending lots of emails to background processes. This is the groundwork for this and similar features.
- The [fof/follow-tags](https://github.com/FriendsOfFlarum/follow-tags) extension implements this feature, limited to particular tags. Probably a good middle ground for most forums - you should really only use this with a proper queue backend, though!
- The [fof/subscribed](https://github.com/FriendsOfFlarum/subscribed) extension implements - among other things - the ability to subscribe to all new discussions.
- There's also [Post Notifications per E-Mail](https://discuss.flarum.org/d/20750-post-notifications-per-e-mail) - which allows sending these notifications to a whitelist of email addresses. Useful when a bunch of admins want to be aware of new activity without having to visit the forum all the time.

---

Beyond all of that, I would be happy to see another extension that lets you use Flarum as / via a mailing list - that would require some more work around email headers (and maybe even email inbox parsing) for proper threading support in mailboxes.
