### ISSUE TITLE
Multiple access token may available together.

### ISSUE THREAD

**Issue by LimiQS** [flarum/core#770]
I. How to generate two available token: Login (Get Token A) -> Clean Cookie -> Login (Get Token B)
II. I edited my 'flarum_remember' cookie, found no matter I set it value to Token A or Token B, I can use my forum and account normally and there is no behavioural difference while using either token.
III. Take a look at DB Table `access_token`, I found `user_id` can duplicate. I think it may be a good choice to let it CANNOT duplicate. (and it's may also helpful to expired token clean up issue #217)

**Comment by Luceos** [comment]
I want to be able to stay logged in on multiple machines. I see no reason to make access_tokens limited per user.

**Comment by tobscure** [comment]
Yeah, this isn't an issue. And #217 is already closed.
