### ISSUE TITLE
Eliminate `extensions` directory from skeleton

### ISSUE THREAD

**Issue by tobscure** [flarum/core#774]
@franzliedke and I discussed the usefulness of the `extensions` directory in the skeleton today. There are a couple of reasons we have this directory in the first place:

* **So we can scan its sub-directories to build a list of available extensions.** However, we realised we can just read the list from `vendor/composer/installed.json`, filtering by package type. We do this anyway to get extension version numbers!

* **To support drag/drop uploading of extensions.** It only works for extensions that don't have any Composer autoloading or dependency requirements though (really only language packs). We decided we want to discourage this because it is very likely to cause confusion by having multiple extension installation methods.

Since both of these reasons are invalid, we think there is no longer any reason to have a separate `extensions` directory. Instead, extensions can just be installed into the `vendor` directory like any other package. It's cleaner and eliminates a potential source of confusion.

**Comment by Luceos** [comment]
This has some issues:

- Composer has to run twice, first to drop the flarum/composer-installer then to move extensions to vendor. It's beta, let's live with that?
- All migrations by extensions had the flarum-(ext-) removed in the namespace. I'm not sure how to handle this. Replacing flarum-ext- in the composer name to resolve to the migration namespace might create issues, because it's still namespace guessing. What's the reason for namespaced migrations that aren't necessarily required to be added to the classmap anyway :stuck_out_tongue:

**Comment by franzliedke** [comment]
Migrations are now not namespaced anymore. *yay*

**Comment by Luceos** [comment]
Jep, that should make this a much easier task.

**Comment by Luceos** [comment]
Any objections to move this to beta 5? I had a wip branch somewhere I need to finish now with the latest changes to the migration namespaces ;)

**Comment by franzliedke** [comment]
Agreed. Since we are already breaking BC with the migrations stuff, we may as well do this change in beta.5 as well and make the upgrade as painful as possible. But only once. ;)

*Wait a sec. @Luceos, you did propose to move this to beta.5, right? I got an email...*

**Comment by Luceos** [comment]
I know I deleted it because I couldn't find my branch. But let's move this to beta 5. The reason is the same as you say, there is already a backward compatibility thing here.

Sorry to confuse you.

**Comment by Luceos** [comment]
So there's this PR, it also adds prefer-stable.

**Comment by Luceos** [comment]
@franzliedke a test run would be great for this one.

**Comment by tobscure** [comment]
In addition to the flarum/flarum PR, we also need a flarum/core PR which updates the extension manager code to read the list of extensions from installed.json, and the extensions service provider which uses the correct path for bootstrap.php files... And the migration runner?

**Comment by Luceos** [comment]
Jep. I'll might as well send those in as well. Sorry to bother ;)

**Comment by Luceos** [comment]
> In addition to the flarum/flarum PR, we also need a flarum/core PR which updates the extension manager code to read the list of extensions from installed.json, and the extensions service provider which uses the correct path for bootstrap.php files... And the migration runner?

- [ ] reading list of extensions from installed.json
- [ ] extension service provider due to bootstrap includes
- [ ] migrator

**Comment by Luceos** [comment]
Both PR's are merged (flarum/flarum and flarum/core), closing.

**Comment by franzliedke** [comment]
:clap:
