### ISSUE TITLE
Page scroll when organizing Tags

### ISSUE THREAD

**Issue by viruxe** [flarum/core#775]
This is just an example so you guys get what I mean. I have lots of tags and I wan't to move one of them to the top or even make it a sub tag of a tag that is up in the list. When I try to drag the said tag to make those actions the page doesn't automaticaly scroll up, so I'm stuck making various step moves until I reach the top or the desired tag.

![tags_reorganize](https://cloud.githubusercontent.com/assets/1616657/12866351/eb3e72ec-ccc2-11e5-8814-65d1d3a7a2f5.gif)

**Comment by Luceos** [comment]
You have to move to the edge of the screen, not the edge of the header menu. That does feel like an issue though. Maybe we should trigger the behavior when it hits the edge of the parent element?
