### ISSUE TITLE
Improve forgot password modal error handling

### ISSUE THREAD

**Issue by tobscure** [flarum/core#776]
Currently, in the forgot password dialog, if you leave the email address field blank, or enter a non-existent email address, the error message shown is:

> The requested resource was not found.

We should make this more descriptive. Also, it should display inside of the modal rather than as an alert.

**Comment by datitisev** [comment]
I'm going to try to do this :)
My first code contribution to Flarum if it works ;)
If gotten so far as to "Email field is required" :)
Happy days!

**Comment by tobscure** [comment]
For the record: mostly fixed in 7120ba2

**Comment by datitisev** [comment]
I did think it was fixed, but because it wasn't closed, and there was never a "Please insert email" error message, I thought I would add it, so it doesn't look in the database for nothing ;)
