### ISSUE TITLE
Scrollbars on "Tags cloud?"

### ISSUE THREAD

**Issue by Fastidious** [flarum/core#780]
See screenshot:

![screen shot 2016-02-09 at 7 59 45 am](https://cloud.githubusercontent.com/assets/8352292/12916818/381580aa-cf03-11e5-9981-8e46c8e8430e.png)

**Comment by franzliedke** [comment]
So? Where's the bug? ;)

**Comment by Fastidious** [comment]
@franzliedke no a bug, but an issue. I find it ugly. If it is intended feel free to close this.

**Comment by franzliedke** [comment]
Well, it's intended as far as I'm concerned. If I remember correctly, we added some code to fix some overflow bugs, and this is the result.

I agree it's not super pretty, but Toby was planning to overhaul these page anyway, so I'm sure this will be fixed as part of that work.

Thanks for bringing it up, anyway. :)
We would appreciate it, though, if the next bug report would be a little more helpful. At the bare minimum, please explain why you think you've found an issue, and especially what kind of behavior you would expect instead. That makes things a lot easier for us...
