### ISSUE TITLE
[Mentions] Reply button adds two newline characters to empty post

### ISSUE THREAD

**Issue by jordanjay29** [flarum/core#781]
I noticed this from the recent dev-master update of discuss.flarum (and @Luceos kindly linked [the commit in question](https://github.com/flarum/flarum-ext-mentions/commit/e825d1a41b1728b39a5d73f1e0aa5dee56f90bb4#diff-0d11d2887abdd78ba33d581f4cdbee6bR28)). When clicking reply for an @mention in a post, it will insert two newline characters preceding. From the comment, it looks like the new feature is supposed to look for included content, but the logic is off (if there's no content, array will always return 3).

**Comment by franzliedke** [comment]
Ah, the edge cases. Thanks for reporting this!
