### ISSUE TITLE
"Mark as Read" pop-up lang bit

### ISSUE THREAD

**Issue by sijad** [flarum/core#782]
click on "Mark as Read" button will ask user to confirm this:
`core.forum.discussion_list.mark_all_as_read_confirmation`

**Comment by franzliedke** [comment]
I'm pretty sure you need to update your English language extension. It's [in there](https://github.com/flarum/flarum-ext-english/blob/f0ef8e1b09de4a0a0d26e22002abdc1c6c533ab1/locale/core.yml#L238).

**Comment by sijad** [comment]
sorry, I see that on http://discuss.flarum.org

**Comment by sijad** [comment]
the one I'm referring is "Mark as Read" not Mark All as Read" button and it should be under [discussion_list](https://github.com/flarum/flarum-ext-english/blob/f0ef8e1b09de4a0a0d26e22002abdc1c6c533ab1/locale/core.yml#L201)

**Comment by franzliedke** [comment]
Hmm, sorry for the premature closing.

**Comment by tobscure** [comment]
There shouldn't be a prompt for marking a single discussion as read - I think that was erroneously merged. It should be removed.
