### ISSUE TITLE
[Mentions] link for users in preview mode incorrect

### ISSUE THREAD

**Issue by Luceos** [flarum/core#788]
On the current live forums I noticed that when editing an existing post, the preview of that post shows links to users with a `/d/` in the url instead of a `/u/`. Couldn't find any matching issue, so I hope this is not duplicate.

**Comment by franzliedke** [comment]
Hmm, I tried to look into this, but didn't quite understand what was going on. Need some help from @tobscure ...

**Comment by tobscure** [comment]
Duplicate of #367
