### ISSUE TITLE
post number changes on page refresh

### ISSUE THREAD

**Issue by sijad** [flarum/core#789]
with each refreshing discuss page, the post number changes to previous post

for example if you're at localhost/flarum/d/{discuss-title}/20
with each refreshing it goes to localhost/flarum/d/{discuss-title}/19, localhost/flarum/d/{discuss-title}/18, and so-on

**Comment by axadr** [comment]
It is because of after scrollToNumber(near) calculatePosition gets `startNumber = near - 1`

I think we should pass **near** to **positionChanged** event.

**Comment by askvortsov1** [comment]
Fixed in #2160

**Comment by askvortsov1** [comment]
Unfortunately not yet fully fixed.
