### ISSUE TITLE
[Emoji] Popup z-index wrong

### ISSUE THREAD

**Issue by Luceos** [flarum/core#791]
![screenshot_20160210-200308](https://cloud.githubusercontent.com/assets/504687/12961362/60aec01a-d040-11e5-8b8f-fd0fbab869c4.png)

**Comment by franzliedke** [comment]
@Luceos Can you still reproduce this? The composer is full height when I simulate a small screen using Chrome's dev tools...

**Comment by Luceos** [comment]
No it's been fixed somewhere ;)
