### ISSUE TITLE
Method [validateText|max] does not exist in /illuminate/validation/Validator.php

### ISSUE THREAD

**Issue by bmalex88** [flarum/core#793]
This is related to the _flarum-tags_ extension. Apparently, `validateText` is not a valid rule. I used `validateString` (without max) and it worked, but I guess that is just a cheap workaround.
It happens when I try to save a new tag

**Comment by tobscure** [comment]
Thanks for the report!

**Comment by Menyengera-M-Kivuyo** [comment]
i got this error when upload file "Method Illuminate\Validation\Validator::validateCsv,txt,xlx,xls,pdf does not exist." any one help me
