### ISSUE TITLE
markdown issue with : in the link, caused by emoji popup

### ISSUE THREAD

**Issue by Luceos** [flarum/core#794]
In the composer window newlines (by pressing enter) cannot be created after the closing `)` when the link contains a `:`.

eg: 

`[somelink](http://google.com)`

**Comment by kulga** [comment]
* If you: enter link or ```[linktext](link)``` - you can't newline
* If you: type : at any point and enter a link and hit newline, it converts the link to default emotion (and all future links newlined at the end of the link)
![](https://i.imgur.com/m6sTliX.gif)

**Comment by tobscure** [comment]
Fixed in flarum/flarum-ext-emoji#4
