### ISSUE TITLE
Emoji popup halts writing if using : textually

### ISSUE THREAD

**Issue by Luceos** [flarum/core#795]
If you simply want to prepare for a list or any other reason to use `:` textually, the emoji popup opens and needs closing before you can continue. This could be improved, for instance by adding a small delay on the popup.

**Comment by tobscure** [comment]
I think this is essentially the same as #794, we can consolidate into one issue.

**Comment by Luceos** [comment]
I'd prefer not to close this one, to function as a requirement for the fix/improvement.

**Comment by dcsjapan** [comment]
I'd like to add that this makes it impossible to end a paragraph with a colon, something I do a lot:

![emoji](https://cloud.githubusercontent.com/assets/13129997/13031323/60b515d0-d30d-11e5-9f6c-9486eff1b90e.png)

The emoji popup here on GitHub seems to activate if the colon is preceded by a space, but not if it's preceded by some other character. That would probably be a good way to handle it.
