### ISSUE TITLE
[DB structure] Fix problem with Timestamp default value.

### ISSUE THREAD

**Issue by LimiQS** [flarum/core#796]
When I modify my DB of flarum. I found all columns with type `Timestamp` in the tables have set a default value `0000-00-00 00:00:00`. But min value of `Timestamp` in mysql is `1970-01-01 00:00:01`. Although no affect has been found while using this DB with flarum. But it's still a good idea to use a valid default value.

PS. When trying to modify the structure of a table with such a mis-configured default value, an error will be alerted. That's the only problem I found till now and I fixed it with `mysqldump` and `vim`. (Since unavoidable errors will be alerted while trying to fix the problem with SQL statement in `access_tokens` table. I manually change the default value in the dump file and then import it to rewrite original DB)

**Comment by franzliedke** [comment]
Hmm, so you're saying changing this in a migration will not work? If so, I think we can just cheat (we're still beta, hey) and fix it in the existing migration.

**Comment by LimiQS** [comment]
Hmm...good idea. As it's not serious (at least at present), a cheat-and-fix may be the best way to solve it.

**Comment by franzliedke** [comment]
As far as I can tell, we have no more `TIMESTAMP` columns, so this should be obsolete, probably since #1236.
