### ISSUE TITLE
You do not have permission to do that - Flarum Forum

### ISSUE THREAD

**Issue by AlexL777** [flarum/core#797]
Hello Developers,

I have had problems with Flarum indeed appears to me in changing the avatar or by calling the forum posts that I have no Permissions.

I have tried everything and the directories in the FTP account have naturally already write access.
My .htaccess looks like and I had to change it so, so that the forum posts are at least displayed. Before that did not go well.

    Header always set Access-Control-Allow-Origin "*"
    Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
    Header always set Access-Control-Max-Age "1000"
    Header always set Access-Control-Allow-Headers "x-requested-with, Content-Type, origin,  authorization, accept, client-security-token"

    # Allow access if Flarum is installed in a subdirectory,
    # but another .htaccess in a higher directory denies access.

    <IfModule mod_authz_core.c>
     Require all granted
    </IfModule>

    <IfModule mod_rewrite.c>
    RewriteEngine on

    RewriteCond %{HTTP_HOST} !^www\.flarumboard\.de$
    RewriteRule ^(.*)$ http://www.flarumboard.de/$1 [L,R=301]

    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    RewriteRule ^vendor/(.*)?$ / [F,L]
    RewriteRule ^storage/(.*)?$ / [F,L]
    RewriteRule ^config.php$ / [F,L]

    RewriteRule ^api(.*)$ api.php [QSA,END]
    #RewriteRule ^admin(.*)$ admin.php [QSA,L]
    RewriteRule ^admin(.*)$ admin.php [QSA,END]

    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule !^assets index.php [QSA,L]

    # MultiViews can mess up our rewriting scheme
    Options -MultiViews

    # Autoindex will list all assets files which is not so good
    Options -Indexes
    </IfModule>

I have in the error_log this:

    [11-Feb-2016 05:04:49 UTC] PHP Fatal error:  Uncaught exception 'UnexpectedValueException'  with message 'Unrecognized protocol version (Subrion CMS Updates HTTP/1.0)' in  /home/alexleu/flarumboard.de/vendor/zendframework/zend-diactoros/src/ServerRequestFactory.php:469
Stack trace:
     #0 /home/alexleu/flarumboard.de/vendor/zendframework/zend- diactoros/src/ServerRequestFactory.php(75):  Zend\Diactoros\ServerRequestFactory::marshalProtocolVersion(Array)
    #1 /home/alexleu/flarumboard.de/vendor/zendframework/zend-diactoros/src/Server.php(118): Zend\Diactoros\ServerRequestFactory::fromGlobals(Array, Array, Array, Array, Array)
    #2 /home/alexleu/flarumboard.de/vendor/flarum/core/src/Http/AbstractServer.php(31): Zend\Diactoros\Server::createServer(Object(Zend\Stratigility\MiddlewarePipe), Array, Array, Array, Array, Array)
    #3 /home/alexleu/flarumboard.de/index.php(16): Flarum\Http\AbstractServer->listen()
    #4 {main}
    thrown in /home/alexleu/flarumboard.de/vendor/zendframework/zend- diactoros/src/ServerRequestFactory.php on line 469

What else can I do?

About a help, I am pleased. Thank you very much.

**Comment by franzliedke** [comment]
We use this place to track real, confirmed issues with the Flarum software. Please answer questions like these on [our forums](https://discuss.flarum.org).
