### ISSUE TITLE
Class flarum\flarum-ext-approval\Migration\AddIsApprovedToDiscussions does not exist

### ISSUE THREAD

**Issue by bmalex88** [flarum/core#798]
This happens when I run `php flarum install`, after I submit all the data. I see that several tables are created. Also, if I use the web installer, I get an incomplete error

> Something went wrong: <br /> <font size='1'><table class='xdebug-error xe-strict-standards' dir='ltr' bord

**Comment by franzliedke** [comment]
We use this place to track real, confirmed issues with the Flarum software. Please answer questions like these on [our forums](https://discuss.flarum.org).

**Comment by bmalex88** [comment]
I suppose this doesn't happen to you, then

**Comment by franzliedke** [comment]
Nope. Installation worked just fine for me yesterday. ;)
