### ISSUE TITLE
PHP Notice in admin cp

### ISSUE THREAD

**Issue by sijad** [flarum/core#799]
[Notice: Only variables should be passed by reference in core/src/Extension/Extension.php on line 89](https://github.com/flarum/core/commit/191589e2b1a633d92ccac57e49b8805dd23252cd#diff-0a48d7ce27bf0c1311dabda7f1754392R89)
it broke admin cp

**Comment by Luceos** [comment]
what version of php are you running? Please give more info.

**Comment by sijad** [comment]
with php 5.6.17 I get this:
```
Strict standards: Only variables should be passed by reference in /usr/local/var/www/flarum/vendor/flarum/core/src/Extension/Extension.php on line 89
```

[php.net end](http://php.net/manual/en/function.end.php)
> This array is passed by **reference** because...

**Comment by franzliedke** [comment]
@Luceos You need to pass a variable to `end()`.

**Comment by Luceos** [comment]
@franzliedke I know, I was aware of the cause ;)
