### ISSUE TITLE
Implement post deletion

### ISSUE THREAD

**Issue by tobscure** [flarum/core#8]
Posts should be able to be soft-deleted (hidden) so that they only appear to people who have permission to restore them (author + whichever groups have permission.)

Additionally, users with the correct permissions should be able to delete a hidden post permanently.

The API for all of this should(?) be working. I can’t quite remember :3

**Comment by thangngoc89** [comment]
We should have a cronjob to clean up hidden post after x days to.

**Comment by tobscure** [comment]
@thangngoc89 Definitely in an extension :)

Half of this is done in c28307903be0f25c95c5ddad9464536a5e3c10d0, still need to implement permanent deletion though.

**Comment by RugWarrior** [comment]
:+1:

**Comment by tobscure** [comment]
Oh yeah the other half of this was done in 36787bcf456843041da33c80c0c5456298e144a8
