### ISSUE TITLE
Why the flarum-ext-instructions Extensions didn't update

### ISSUE THREAD

**Issue by skywalker512** [flarum/core#804]
flarum-ext-instructions only support beta.2.
Why didn't update

**Comment by tobscure** [comment]
Not a priority at this time. It also lacked some functionality and needed a bit of design revision so didn't really have time.

**Comment by Luceos** [comment]
Correct me if I'm wrong, but let's close this for now. If core and primary core extensions are at full speed, we can reconsider this extension. Maybe someone else picked it up before that? Maybe we should advertise that?
