### ISSUE TITLE
Limit Post Length

### ISSUE THREAD

**Issue by LimiQS** [flarum/core#805]
I found there is NO post length limitation for flarum. So if someone's post content is more than 64KB (MySQL limitation of a single value, may be varied for different people), the whole topic will get into error because of data format error. (the ending tags added by flarum and the part of the content >64kb will be dropped by MySQL)

Although it's really HARD to reach 64KB limitation. A too long post will ruin the post as well. So I think it's necessary to set a limitation to post length.

**Comment by kulga** [comment]
I believe this is fixed... Attempting to post a large post gives me this

**The content may not be greater than 65535 characters.**

**Comment by Luceos** [comment]
@kulga in dev-master? Did you try this on the official forums?

**Comment by kulga** [comment]
@Luceos On discuss.flarum.org [sandboxed tag](https://discuss.flarum.org/d/2079-a-really-long-post)
Specifically, I can post 65522 characters but not 65523.
