### ISSUE TITLE
getUserDocument needs refactoring

### ISSUE THREAD

**Issue by Luceos** [flarum/core#806]
Registration of some technical debt. I noticed in ClientView the following todo.

``` php
    /**
     * Get the result of an API request to show the current user.
     *
     * @return object
     */
    protected function getUserDocument()
    {
        // TODO: calling on the API here results in an extra query to get
        // the user + their groups, when we already have this information on
        // $this->actor. Can we simply run the CurrentUserSerializer
        // manually? Or can we somehow inject this data into the ShowDiscussionController?
        $document = json_decode($this->api->send(
            'Flarum\Api\Controller\ShowUserController',
            $this->actor,
            ['id' => $this->actor->id]
        )->getBody());

        return $document;
    }
```

**Comment by renyuneyun** [comment]
Is this already done?

I saw this class/file has been renamed to `Http/WebApp/WebAppView` and there is an argument `Request $request` in this function in 9bfb797fdc94f2bc1be342e15c89765a70d5fe33.

**Comment by datitisev** [comment]
Yeah, it does look like it got done. [This line](https://github.com/flarum/core/commit/9bfb797fdc94f2bc1be342e15c89765a70d5fe33#diff-b3f82c51060bdb1ef707531f9bccbe02R400) specifically is the new `WebAppView#getUserDocument` which, I think, closes this issue.

**Comment by Luceos** [comment]
Will close this as the specified code has been refactored.
