### ISSUE TITLE
Add GitHub integration?

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#809]
This came up recently [in the forums](https://discuss.flarum.org/d/2073-in-dept-github-implementation), and almost immediately I ran across a reference to the same idea [here](https://discuss.bolt.cm/d/2-does-this-thing-have-kittens/17), so I thought I'd make an issue of it...

Basically, how about adding GitHub integration for automatic linkification of issues, PRs, etc.?

It would certainly be handy for discuss.flarum.org (not to mention Flarums for any other GitHub-hosted projects). But I'm not sure whether it would really fit as a bundled extension. It might be better left to a third-party developer. Or maybe it's a good project for Flagrow. Thoughts?

**Comment by franzliedke** [comment]
I don't think this makes sense as a bundled extension (developers are a niche, at least when looking at the whole target group for online forums).

I'd looooove an extension for this, though. :)

**Comment by tobscure** [comment]
^ agreed!

**Comment by Luceos** [comment]
I was looking into this already. Wanted to add hashtag as bbcode to reference a github issue first. Not any progress so far though.

**Comment by sijad** [comment]
I made [one](https://github.com/sijad/flarum-ext-github-autolink) but commits autolinking has conflicts with Mentions plugin, it can be fixed if we use `Username/Repository@SHA` instead for commits
let me know your thoughts

**Comment by Luceos** [comment]
@sijad what if your regular expression match checks for the github domain? That would solve the conflict with mentions.. Right?

**Comment by sijad** [comment]
@luceos I think yea that's a good idea. I'll work on that

**Comment by tobscure** [comment]
Closing this, @sijad's extension is great 👌
