### ISSUE TITLE
Navbar unreasonably expands upon scrolling of one thread

### ISSUE THREAD

**Issue by rodrigoargumedo** [flarum/core#81]
When I go to the [Discuss](http://discuss.flarum.org/140-feature-idea-placeholder-posts-when-scrolling-down) forum, the navbar title expands upon scrolling for most recent conversation, leaving out the search functionality obstructed. Is this a CSS bug? (I used the desktop version of the app)

![bar](https://cloud.githubusercontent.com/assets/7613139/7643618/5ae7514c-fa58-11e4-9f9d-cbd9c866e7bd.JPG)

**Comment by tobscure** [comment]
The dev forum is powered by esoTalk, this is an esoTalk bug :)

**Comment by rodrigoargumedo** [comment]
Oh, thanks. I will forward this to the folks at esoTalk. @tobscure
