### ISSUE TITLE
Unfuzz some fuzzy times (e.g. >30 days, >1 year)

### ISSUE THREAD

**Issue by jordanjay29** [flarum/core#815]
As a result of [this discussion on discuss.flarum](https://discuss.flarum.org/d/1776-display-full-date-in-post-header-of-posts-older-than-30-days). 

Quoting @tobscure:

> <30 days = relative time ago
> <1 year = Day Month, no year
> [_greater than_ symbol here because Markdown is a PITA]1 year = Day Month Year

This prevents ambiguous dates like Oct, '15, which can be misconstrued (especially in North America) as 15 October, instead of October 2015.

**Comment by franzliedke** [comment]
Wouldn't using October 2015 be the easiest solution here?

**Comment by tobscure** [comment]
@franzliedke Are you proposing something different to this?

```
<30 days = relative time ago
<1 year = Day Month, no year
>1 year = Day Month Year
```

**Comment by franzliedke** [comment]
I was proposing to show `Oct 2015` instead of `Oct '15` as a simple way of preventing confusion with `Oct 15`.

**Comment by tobscure** [comment]
OK, as far as I can see that's the same as what I've proposed above, so I think we're on the same page...

**Comment by franzliedke** [comment]
Not quite, your `>1 year` suggestion has the day as well, but I'm not against adding that either. ;)

**Comment by tobscure** [comment]
Ah I see. My argument for adding that is that if you have multiple posts in a row in the same month, it can be useful to be able to see at a glance how many days apart they are :)

**Comment by davwheat** [comment]
> @franzliedke  Not quite, your >1 year suggestion has the day as well, but I'm not against adding that either. ;)

I wish days were shown but if that was going to be done, why not just show dates for anything over 1 month old? Or 1 week? Or 1 day? Or just everything?

**Comment by askvortsov1** [comment]
@jordanjay29 I'd like to propose:

< 30 days: relative time
< 1 year: June 1st (the 'st or 'th should help distinguish between month and year)
>= 1 year: June 1st, 2011

**Comment by davwheat** [comment]
Remember different locales have different preferred date formats.

2011-06-01 would usually be 1 June 2011 in the UK.

**Comment by tankerkiller125** [comment]
Are there any libs that can take the program date/time and automatically set the displayed value according to the users browser locale?

**Comment by askvortsov1** [comment]
Now that I think about it, moment has localization support. https://momentjs.com/. Only issue is, it doesn't have that for just month date. I think 'June 1st' is fair for the under 1 year category, but we can also do '1st June' or 'June 1'

**Comment by jordanjay29** [comment]
`June 1` was my preferred approach, simply because cardinal numbers don't need the 'st/th/rd' translated or dealt with. And it's quite odd to see it in practice sometimes, most casual writing uses only the cardinal numbers (the number alone) and not ordinals (with the 'st/th/rd'). I think most users will be able to distinguish between 1June 1, 20111 and 1June 11 without using ordinals. 

Distinction is important when we're trying to address confusion over a format that allows dates like `June '15` and `15 June` in the same discussion. 

(And on that note, I think the default format for Flarum is DMY and not MDY I've been using as examples in this comment)

**Comment by askvortsov1** [comment]
I've included both US and non-US support, please see the PR above
