### ISSUE TITLE
Fatal Error Application name is already in use

### ISSUE THREAD

**Issue by sijad** [flarum/core#816]
after merge latest change a get this error:
```
Fatal error: Cannot use Illuminate\Contracts\Foundation\Application as Application because the name is already in use in flarum/vendor/flarum/core/src/Foundation/AbstractServiceProvider.php on line 14
```
note [Application Class](https://github.com/flarum/core/blob/master/src/Foundation/Application.php) already exist in [Foundation](https://github.com/flarum/core/tree/master/src/Foundation) folder

Tested with PHP 5.6

**Comment by sijad** [comment]
this is similar to @36ad4a855477bc1b9d5b3806a7b5899632abeac6
but I'm not sure why you need `Illuminate\Contracts\Foundation\Application` here

**Comment by franzliedke** [comment]
I reverted the bad change in #817. Thanks for the report.
