### ISSUE TITLE
prevent vital db information to be shared on exception

### ISSUE THREAD

**Issue by luceos** [flarum/core#818]
We should catch pdo exception when debug is off. This is a common issue with Eloquent, the stacktrace is shown when debug is off including the PDO connection information (or most of it).

See: https://discuss.flarum.org/d/2110-on-db-connection-fail-reveal-db-related-sensitive-data

**Comment by franzliedke** [comment]
Why does it not show our "pretty" HTTP 500 error page, though? Does the error happen too early?

**Comment by Luceos** [comment]
Haven't investigated yet. If I do I'll assign it to myself. I just know this is quite common for L-apps.

**Comment by Slayer95** [comment]
Any news about this?

**Comment by franzliedke** [comment]
@Slayer95 Did you report this in the forums? If so, can you provide me with the full stack trace, so that I can figure out why this did not get caught by our normal error handler (which should have prevented the stack trace from being shown when debug mode is turned off)?

**Comment by Slayer95** [comment]
It wasn't me, but I may still provide you with an stack trace, as soon as I get one again -the error logs are empty @.@, and I had edited some core files, which I have just now resetted.

**Comment by Luceos** [comment]
@franzliedke this most commonly happens if you get a failed connection exception. Just try changing the password or username to something that is invalid.

**Comment by franzliedke** [comment]
That's a good hint, I could reproduce that. :)

**Comment by franzliedke** [comment]
Closing in favor of the more up-to-date #1421.

Thanks for the hint, @sijad :wink:
