### ISSUE TITLE
Time Stamp

### ISSUE THREAD

**Issue by Felli** [flarum/core#82]
So I've only tested this in Torch, Chrome, & Chrome Canary's browser and it would seem that the time stamp isn't working correctly it sets the time stamp hours ahead of when the post was actually posted.
![](http://i.imgur.com/aknsllf.png)

**Comment by tobscure** [comment]
Can't reproduce this... is it showing '3h ago' immediately after you post something?

**Comment by Felli** [comment]
Yes, right after I've posted it shows it as made "3h ago".

**Comment by franzliedke** [comment]
Yuck, timezones... ;)

**Comment by franzliedke** [comment]
@Felli What timezone are you in?

**Comment by tobscure** [comment]
Yeah probably... it shouldn't really be an issue because the dates are parsed on the client-end and then converted into relative time with moment.js. I can look into this more tomorrow

**Comment by tobscure** [comment]
I still can't reproduce this by changing my computer's timezone :(

The API is outputting times in UTC correctly (e.g. `time: "2015-05-19T00:06:18+00:00"`), and then moment.js is responsible for parsing them and outputting them in the local timezone. So again, theoretically there's nothing wrong there.

Can you think of anything I can try? Is anyone else experiencing this problem?

**Comment by franzliedke** [comment]
I'm getting the following console message when viewing a discussion on my dev forum:

> Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.

Could that have to do with it?

**Comment by tobscure** [comment]
Good thought, but unfortunately that was only to do with the discussion scrubber :( 03b47c3591bd49ed236f59d660e28159bc5ba28d

**Comment by tobscure** [comment]
Closing until this can be reproduced

**Comment by Ansego** [comment]
http://momentjs.com/timezone/
