### ISSUE TITLE
More attributes in app.blade.php

### ISSUE THREAD

**Issue by sijad** [flarum/core#820]
`dir` and `lang` attributes needs to be added to `<html>` tag, it should be like this:

`<html dir="{{ $dir }}" lang="{{ $lang }}">`

it'll allow developers to change document direction in browser easily.
also it'll be a good idea if `<body>` tag had a configurable `class` attribute

update: 
related links:
- [Why use the language attribute?](https://www.w3.org/International/questions/qa-lang-why.en)
- [Why you should use "dir" attribute](https://alicoding.com/why-you-should-use-dir-attribute-more-for-right-to-left-localization/)

**Comment by franzliedke** [comment]
@sijad How exactly do you want to make the body's `class` attribute to be configurable? A custom class name is not necessary, you can just use `body` as a selector in your CSS. I suppose you mean something different... Are you talking about having different classes attached to the body depending on which page is open?

**Comment by sijad** [comment]
had something like [modernizr](https://modernizr.com/) in mind
one of the use cases, body classes can help developer do things only using css (like conditions in css) and no javascript

**Comment by franzliedke** [comment]
Yes, but which things? ;)

**Comment by sijad** [comment]
as said it's just an idea, there can be lots of use cases:
* user is logged in
* user group
* user is admin
* ...
just saying it not that bad have this option, adding these classes in **back-end** means they can also be used in case user javascript is disabled

**Comment by franzliedke** [comment]
Hmm, technically this should be possible, because we refresh the page when logging in / out.

**Comment by franzliedke** [comment]
Thanks to David, direction and language will now be exposed.

**Comment by tobscure** [comment]
So now we just need to expose body class? Is there anything else?

**Comment by franzliedke** [comment]
Yes, we probably need to come up with a list of which things we are talking about (and then create a new ticket with some instructions to make it contributor-friendly).

**Comment by luceos** [comment]
@tobscure this relates to the frontend refactor. If we add a body class this can be closed?

**Comment by tobscure** [comment]
We'll do that in a separate PR.

**Comment by franzliedke** [comment]
Let's close this. When the use-cases for concrete classes come up, these can be tracked / added separately.
