### ISSUE TITLE
Deleted threads not loading after user deletion

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#823]
There's an issue causing endless spinning after a user is deleted. See for example the two posts created in the AM of Feb. 22, 2016 by a spammer who has been deleted.

Question for @Luceos:

Did you delete the threads before deleting the user, or just delete the user? I wonder if the order in which things are done makes any difference to whether this issue occurs.

**Comment by Luceos** [comment]
I first deleted the threads, which allowed me to still see the post. After that I deleted the user, because suspending doesn't work for now (pr awaiting merge for that). Seems to me there is an issue with the ajax call, can't see what from tablet.

**Comment by dcsjapan** [comment]
Thanks, just want to make sure the order was clear for whoever looks into this issue.

**Comment by Luceos** [comment]
```
Uncaught TypeError: Cannot read property 'number' of undefined
```
This probably has to do with the count for the discussion. As the initial post is removed there is no total amount of posts. Can't see the exact line due to minification at this time.

**Comment by jordanjay29** [comment]
Can we re-open this to deal with the zombie threads? If a user's profile is deleted, and their posts are deleted with it, it seems that their discussions (which are now otherwise empty) remain intact, and thus become zombies. 

Zombies will eat your brains. Best to take care of them before they do that.
