### ISSUE TITLE
Support setting MySQL port in installation

### ISSUE THREAD

**Issue by tobscure** [flarum/core#825]
https://discuss.flarum.org/d/2115-how-to-configure-different-mysql-port

We should parse the host field for a `:` and explode it if found

**Comment by sijad** [comment]
in installation you can use `host:port` as *host* field and it's working, no need to change anything

**Comment by franzliedke** [comment]
Not sure whether that's intended to work, though - it's better to fix this properly and make sure future changes e.g. in Laravel's database component don't catch us off-guard.

**Comment by tobscure** [comment]
I would argue that the port field should be omitted from the installer to avoid confusing users who will not need to change it from the default (majority of cases)?

**Comment by franzliedke** [comment]
Yep, sounds good. For people who want to do it, they can still add the port at the end of the hostname, so that use case is covered as well.

**Comment by sijad** [comment]
should revert #989?

**Comment by franzliedke** [comment]
@sijad For the parts concerning the visual installer, yes. :)
