### ISSUE TITLE
You do not have permission to do that.

### ISSUE THREAD

**Issue by santiagobiali** [flarum/core#826]
Note: This is happening on discuss.flarum.org

You do not have permission to do that happening when:
- Sign Up ` failed to load resource discuss.flarum.org/register `
- Change some setting in user's profile ` 401 (Unauthorized) ` in ` api/users/nº ` but if accessed directly it returns.

**Comment by Luceos** [comment]
Verified by simply pressing save on the user settings page. No edits needed.

**Comment by dcsjapan** [comment]
I received this message after clicking the "Mark all as read" button and entering my password.

**Comment by tobscure** [comment]
I have a fix for this I will push in a few hours

**Comment by dcsjapan** [comment]
"Mark all as read" works now! :clap: 

... That was a fast few hours! :smile:
