### ISSUE TITLE
Unable to view profiles with cyrillic letters in login name by direct link

### ISSUE THREAD

**Issue by wa-Nadoo** [flarum/core#832]
If you go to the profile through a link in the post all works as expected
![cyrilic-notbug](https://cloud.githubusercontent.com/assets/1248501/13342225/862b729a-dc50-11e5-9dee-d8c8b283f429.png)

After F5 you got error
![cyrilic-bug](https://cloud.githubusercontent.com/assets/1248501/13342080/4c19f38e-dc4f-11e5-9354-37153c9b93bb.png)

**Comment by tobscure** [comment]
Thanks for the report. As per the latest discussion in #557, we intend for only usernames containing ASCII characters to be allowed. It's a bug that you were allowed to sign up with a unicode letter, one which I've just fixed ;)
