### ISSUE TITLE
getPlainContent does not trim spaces from either end

### ISSUE THREAD

**Issue by jordanjay29** [flarum/core#834]
[getPlainContent](https://github.com/flarum/core/blob/232f3b6bc696f8c36b39b1eeaae01c299d4a1622/js/lib/utils/string.js#L36) is leaving in extra spaces when it replaces html elements.

**Comment by tobscure** [comment]
e.g. when you have a couple of empty (containing no text) paragraphs at the start

**Comment by franzliedke** [comment]
@jordanjay29 Can you provide a detailed example? Before / after applying the function...

**Comment by jordanjay29** [comment]
My example is a bit different than Toby's, I see it when <img> tags are replaced in my Summaries extension. [Here's my test site with Summaries enabled](http://testbed.legendofdevira.com/flarum/), the top discussion there is a good example of the problem demonstrated. When replacing the <img> tags in the excerpt, getPlainContent drops in a few spaces as well, leaving the "Now with photo." line indented somewhat arbitrarily. 

I don't use getPlainContent on its own anywhere, so I can't show you a before example like that.

**Comment by tobscure** [comment]
Example input:

```
<p><img src="whatever.jpg"><br><img src="another.jpg"></p><p>Text</p>
```

getPlainContent output:

```
"    Text  "
```

Expected output:

```
"Text"
```

Also, the browser attempts to load the images even though they are never displayed – we should try and fix that too.

**Comment by dav-is** [comment]
Is there a reason we can't use jQuery's [text()](http://api.jquery.com/text/)?
