### ISSUE TITLE
composer post-cmd-script clear cache

### ISSUE THREAD

**Issue by luceos** [flarum/core#838]
The cache files are cleared when en- or disabling extensions. When, however, an extension is updated through composer which offers changes to the application, we don't invalidate cache. The only way to get these new changes is by either deleting files or by re-enabling a random extension.

Let's trigger flushing cache using composer post-cmd-script attribute using the todo artisan command, see #837

**Comment by tobscure** [comment]
:+1:

**Comment by tobscure** [comment]
Closing as per conclusion in https://github.com/flarum/core/issues/1442
