### ISSUE TITLE
TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by pituseligmann** [flarum/core#839]
When trying to update my profile description by pressing the Enter key, I'm getting a

> Uncaught TypeError: Cannot read property 'bind' of undefined
save @ forum-eb0ac94f.js:28591 
save @ forum-eb0ac94f.js:28572 
handleObj.handler @ forum-eb0ac94f.js:11492 
jQuery.event.dispatch @ forum-eb0ac94f.js:6532
elemData.handle @ forum-eb0ac94f.js:6218

I have debug enabled, and it's not popping the usual red notification icon that appears when something went wrong.

Running Flarum Beta 4.

**Comment by Luceos** [comment]
According to @santiagobiali this was fixed in dev-master. Closing, re-open if not correct.

See:
https://discuss.flarum.org/d/2162-profile-description-throwing-error-on-enter-key/3
