### ISSUE TITLE
Spaces in generated class names

### ISSUE THREAD

**Issue by wizgriz** [flarum/core#847]
1. Create or edit a group name to include spaces, e.g. "cool people"
2. Observe the class attribute on the group badge on any user in the group being `Badge--group--cool people`, as in `.Badge--group-cool` and `.people`

I imagine this could end up turning up in places other than groups as well.

**Comment by franzliedke** [comment]
Thanks for the report!

@tobscure Probably a good place to employ the `slug` function again, right?

**Comment by franzliedke** [comment]
Okay, I've fixed this by using the group ID instead - that makes more sense in my eyes. :)

**Comment by franzliedke** [comment]
But it's probably breaking BC, so we'll have to put this in the changelog.
