### ISSUE TITLE
Do we still need .php_cs now that we're using Style CI?

### ISSUE THREAD

**Issue by tobscure** [flarum/core#852]
I can't think of a reason we should keep it, but just wanted to double-check before getting rid of it?

**Comment by franzliedke** [comment]
Kick it!

**Comment by franzliedke** [comment]
Wait, what about the ES linting stuff?

**Comment by tobscure** [comment]
That was very broken and out of date. Got rid of it for now, we can bring it back in the future when I can be bothered to set it up properly.
