### ISSUE TITLE
[Mentions] Mentioning a post from a public discussion inside a restricted discussion makes the restricted post visible to the public

### ISSUE THREAD

**Issue by tobscure** [flarum/core#853]
Say I have Post A which is visible to the public.

Then in a restricted tag/discussion, I create Post B which mentions Post A.

Now Post A will display "[username] replied to this" which will display Post B when hovered over, even to the public.

**Comment by Luceos** [comment]
Seriously?! Nice find.

**Comment by jordanjay29** [comment]
Similar to #652? Seems both would be good for Beta 5.

**Comment by Luceos** [comment]
652 broke the notification dropdown, @jordanjay29 ; this is the when you've quoted a post and the entry "replied to this" is generated on the referenced post. Two different items.

Additionally I wouldn't push any task onto the beta 5 milestone now unless absolutely necessary. It's quite easy to push this task as one of the first after beta 5 and tag a new version for mentions soon after.

**Comment by franzliedke** [comment]
Since it is a somewhat critical bugfix, I'd vote for inclusion. What do you think, Toby?

**Comment by tobscure** [comment]
I don't think it's that critical as it's a bit of an edge case, doesn't happen very often. Will include in b5 if we have time.
