### ISSUE TITLE
[Tags] Unable to Drag N Drop in a mobile device

### ISSUE THREAD

**Issue by datitisev** [flarum/core#854]
This goes along with [Flarum: Issue Moving Tags In Admin Panel On Mobile](https://discuss.flarum.org/d/2225-issue-moving-tags-in-admin-panel-on-mobile)

As of v0.1.0-beta.4, you are unable to drag tags in a mobile device. Tested with a Blackberry ([@ron_jeremy](https://discuss.flarum.org/d/2225-issue-moving-tags-in-admin-panel-on-mobile)) and an iPad myself.
I haven't tested with latest dev, because I don't have time to install it and I didn't find any issues neither open nor closed on flarum/core about this.

Steps to reproduce:
1. Go to Administration > Tags (in mobile)
2. Try to drag :smiley: 

Tested with _v0.1.0-beta.3_ and _v0.1.0-beta.4_.

**Comment by ibrahimk157** [comment]
Any progress on this? It's been a year since this has been reported

**Comment by askvortsov1** [comment]
Fixed in https://github.com/flarum/tags/pull/82
