### ISSUE TITLE
Can't add more than one primary tags for discussion

### ISSUE THREAD

**Issue by selvamvasu** [flarum/core#857]
Hi,
Even though we have configured primary tags settings as "required minimum 1 tags and maximum 10 tags". I can't add more than one primary tags for my discussion. When I select Ist primary tags, The tags list is disappeared, i can't select another one like sub tags.

Refer flarum discussion.
https://discuss.flarum.org/d/2248-can-t-add-more-than-one-primary-tags-for-discussion

**Comment by dcsjapan** [comment]
To help us see the situation, could you provide a screenshot of the Tags page in your admin UI?

**Comment by tobscure** [comment]
I can't seem to reproduce this.

**Comment by selvamvasu** [comment]
Hi,
I am using flarum 0.1.0-beta.3. and find the screen shots below.
 
![my_primarytags_list](https://cloud.githubusercontent.com/assets/10844236/13802678/3558e1cc-eb64-11e5-8f95-4939c6248255.png)
![otheres_tags_disappeared_once_select_onetag](https://cloud.githubusercontent.com/assets/10844236/13802679/355ed4ce-eb64-11e5-97fd-d227d26973fd.png)
![tag_settings](https://cloud.githubusercontent.com/assets/10844236/13802680/3562f93c-eb64-11e5-808a-b842025afd1d.png)

**Comment by dcsjapan** [comment]
Thanks for the screenshots @selvamvasu ...

Toby's confirmed that this feature's working properly on the current version, and I've also been able to select more than one primary tag in the [Flarum demo site](https://discuss.flarum.org/d/697-devflarum-test-out-flarum), which is running Flarum beta 4.

Your best bet is probably to update to beta 4 ... or wait just a little while and try beta 5 when it's out.
