### ISSUE TITLE
Non-responsive UI while a thread is marked as read on mobile.

### ISSUE THREAD

**Issue by tarunmarkose** [flarum/core#860]
Whenever I read a thread and head back to All Discussions, the UI freezes for about 2-3 seconds, after which the thread's title font goes from bold weight to normal, signifying that it has been read.

This happens when I use the browsers back gesture via a left to right swipe from the edge of my screen. 

I'm using iOS 9.2.1, on an iPhone 6.

**Comment by tarunmarkose** [comment]
Going to confirm that it happens when I use Flarum's back button as well. Don't have any unread messages at the moment! 😄

**Comment by franzliedke** [comment]
Going to close this as stale, as there seem to have been no other reports of this. Do let me know if I am wrong, please!
