### ISSUE TITLE
[Tags] Prevent inadvertent creation of duplicate tags

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#863]
When adding tags for a new discussion, it's possible to add the same primary tag more than once.
1. Create a new discussion and open the Add Tags dialog.
   - It doesn't seem to happen in the Edit Tags dialog.
2. Select Feedback as the primary tag, plus at least one subcategory tag.
   - I haven't been able to get it to happen with another tag, but I haven't tried them all.
   - As far as I can tell, it doesn't happen if you don't choose a subcategory.
3. Type in the name of the selected primary tag (i.e. "Feedback").
4. Click the OK button.

The typed-in name is recognized as a primary tag and accepted:

![screenie1](https://cloud.githubusercontent.com/assets/13129997/13816426/b4dc6ff0-ebd1-11e5-8888-bdb2b6b07cc1.png)

The result is a discussion with duplicate primary tags:

![screenie2](https://cloud.githubusercontent.com/assets/13129997/13816447/c80a5344-ebd1-11e5-85c7-dae33e244c6f.png)

Apparently two of the same tag is not considered a violation of the maximum primary tags setting. This does not work if you try to type in the name of any tag other than the one that has been selected.

This seems to be a low-priority display glitch; nothing actually breaks as a result of it.

Bonus fun: Removing one of the duplicates can result in some strange messages in the post stream. :smile: 

![screenie3](https://cloud.githubusercontent.com/assets/13129997/13817254/d7563978-ebd4-11e5-9ffc-3a22d167a956.png)

Credit to @Luceos for spotting this one! :beetle: :flashlight:

**Comment by Kakifrucht** [comment]
I tried reproducing this on my beta.4 forum and I couldn't.

**Comment by dcsjapan** [comment]
Thanks for checking! It may be specific to discuss.flarum.org ... Luceos mentioned that it could have something to do with a fix that Toby put it place to make the Design subcategory fall under a primary again (I'm not sure what the story is there).

Come to think of it, there's one more thing I should check out about this bug.

**Comment by Luceos** [comment]
Design previously was called UX and was a primary itself. A few weeks ago I've re-ordered all tags to match a new structure proposal. Once I moved UX under Feedback it became a subtag of Feedback, but it never knew it was a subtag of anything, only that it had become a secondary. So all threads under Design (formerly UX) had no primary tag anymore. Toby fixed this manually in some way and this might be related.

@tobscure this might be a reason to remove it from beta 5 again.

**Comment by dcsjapan** [comment]
Update based on a Gitter conversation starting [here](https://gitter.im/flarum/staff?at=56ecc077bb4a1731739b2ec3):

- The duplication is probably a result of the tag reorganization carried out at discuss.flarum.org.

- Countermeasures to prevent similar issues due to tag reorganization might be needed.

- That can best be handled during the planned reworking of the Tags extension.

Removing from the b5 milestone.

**Comment by dcsjapan** [comment]
I should probably note that this seems to be related to https://github.com/flarum/core/issues/828.

**Comment by johannsa** [comment]
I cannot reproduce this on Beta 7.1.

**Comment by luceos** [comment]
Indeed, seems to be resolved. Let's close until we see this happen again.
