### ISSUE TITLE
Add more control over the assets

### ISSUE THREAD

**Issue by sijad** [flarum/core#865]
Add some event to control assets:
- Add event to check file before add in [addFile](https://github.com/flarum/core/blob/master/src/Asset/AssetManager.php#L49) function
- Add event for [getCssFile](https://github.com/flarum/core/blob/master/src/Asset/AssetManager.php#L95) and [getJsFile](https://github.com/flarum/core/blob/master/src/Asset/AssetManager.php#L103)
- ability to change/alter `AssetManager` compilers (`JsCompiler` and `LessCompiler`), this option could help for CDN

this changes can help for CDN, Theming, ... (in my situation add RTL support)

P.S. all this changes could be done by using [monkey patching](https://github.com/flarum/core/issues/246#issuecomment-181993118) @franzliedke

**Comment by franzliedke** [comment]
We'll take a look, thanks. Pretty sure that we won't need monkey patching. ;)

**Comment by franzliedke** [comment]
P.S.: What exactly do you want to achieve with these events?

**Comment by sijad** [comment]
I need these for adding RTL support (not all of them, what I have in mind can be done by using first one or the last one)
I'm aware that RTL support can be done by adding some less file to override styles, using an extension (I already made that in local), but as flarum uses `Less` it make it a little hard to cover all styles, also it increase compiled css file size
I'm pretty sure these events can help others too

**Comment by sijad** [comment]
@tobscure what do you think?
can I PR?

**Comment by tobscure** [comment]
Go for it – no guarantees it'll be merged (as I'm still unsure about how the use-case relates to the events exactly) but we'll definitely review it.

**Comment by sijad** [comment]
I see your point, is it wrong to pass variables reference to events?

**Comment by tobscure** [comment]
Not necessarily :)

**Comment by tobscure** [comment]
@sijad I'm working on a refactor of asset management right now – if you can show me the changes you want to make, and the use-case that they solve, I'll take them into account.

**Comment by sijad** [comment]
@tobscure thanks for letting me know

* override (change file name or prevent to be added) `js` and `less` files (before compiling)
  * for example if file `vendor/flarum/core/less/forum/AvatarEditor.less` was going to be added for compiling, an event could change it to `vendor/exampleVendor/core/less/forum/AvatarEditor.less`
  * this can be helpful for theming
* override compiled `js` and `css` file
  * for example load `assets/forum-d23f88bb.rtl.css` instead of `assets/forum-d23f88bb.css`
  * this can help (me) for replace compiled css with `RTL` version (RTL version will produced automatically)
  * another use case can be loading these files from CDN
* change/override `JsCompiler` and `LessCompiler` classes
  * this can help for upload compiled files to CDN for example

**Comment by sijad** [comment]
@tobscure can you let us know about your plans?

**Comment by tobscure** [comment]
@sijad 

> override (change file name or prevent to be added) js and less files (before compiling). for example if file `vendor/flarum/core/less/forum/AvatarEditor.less` was going to be added for compiling, an event could change it to `vendor/exampleVendor/core/less/forum/AvatarEditor.less`

We probably won't support this – not only is it technically difficult (we'd have to dive into the LESS parser), but we want to encourage theming to be done additively so that when we change our CSS, themes won't completely break (there will still be Flarum CSS rules to fall back to).

> override compiled js and css file - for example load `assets/forum-d23f88bb.rtl.css` instead of `assets/forum-d23f88bb.css`

The approach we're taking to locale-specific CSS is to have a global CSS file that's downloaded for all visitors, and then another CSS file for each different locale that language packs can add stuff to. So if doing additive RTL rules is not an option, you'll still be able to achieve what you want, I think, with something like this:

```php
if ($view->getLocales()->getLocale() === 'mylocale') {
    $view->getLocaleCss()->addString(function () use ($view) {
        return convert_to_rtl(file_get_contents($view->getCss()->getFile()));
    });
    $view->getCss()->clear(); // prevents the main CSS from being loaded on this request
}
```

> change/override JsCompiler and LessCompiler classes

Hehe, we won't exactly support this either! However, we will support uploading files to CDNs by a different strategy: We'll make the Compiler classes use a Filesystem interface so that a remote filesystem can be subbed in place of the local filesystem.

**Comment by sijad** [comment]
> but we want to encourage theming to be done in an additive manner so that when we change core HTML/CSS, themes won't completely break (there will still be Flarum CSS rules to fall back to).

doesn't that make produced css bigger and bigger? specially if Flarum going to allow have multiple theme available (if all themes files going to be compiled and merged to a single css file).

> If doing additive RTL rules is not an option, you'll still be able to achieve what you want, I think, with something like this:

it's possible to use something like this too, right?

```
if ($view->getLocales()->getLocale() === 'mylocale') {
    $view->getLocaleCss()->addFile($rtlFile);
    $view->getCss()->clear(); // prevents the main CSS from being loaded on this request
}
```

> We'll make the Compiler classes use a Filesystem interface so that a remote filesystem can be subbed in place of the local filesystem.

that sound good 👍

**Comment by sijad** [comment]
I have another use case. I want to make an extension to make make both dark and light version of css and then let users to choose dark theme in front-end. the easy and clean way is to prevent loading main css file, and load dark css instead. but as it mentioned before there's no way to prevent loading a compiled css file.

**Comment by tobscure** [comment]
Providing every user with the option to choose a dark theme for themselves is something we'll look at for core in 0.3.

Beyond that I don't have much to say about the best way to achieve it right now!

**Comment by luceos** [comment]
@tobscure relates to the frontend refactoring?

RTL support can be ignored, this has been extensively discussed in another issue.

**Comment by tobscure** [comment]
Yes, #1450 adds the ability to replace the assets Filesystem
