### ISSUE TITLE
affixSidebar should check window size on resize event

### ISSUE THREAD

**Issue by sijad** [flarum/core#866]
[see here](https://github.com/flarum/core/blob/master/js/forum/src/utils/affixSidebar.js#L17)
not sure if it's a real problem or not, but on tabltes, window resizes when user rotate device to landscape or portrait after document is loaded and it can make a little problem and user may have to refresh the page or rotate it again

**Comment by sijad** [comment]
another option can be a scrollable sidebar (e.g. [google documents](https://developers.google.com/earth-engine/))

**Comment by franzliedke** [comment]
Hmm... @sijad Did you ever see this being a problem on a real Flarum forum?

Bootstrap's Affix plugin [supposedly](https://github.com/twbs/bootstrap/issues/15845#issuecomment-243214658) handles this already...

**Comment by franzliedke** [comment]
Never mind my question, I figured it all out - [here is the pull request](https://github.com/flarum/core/pull/1131). Good night.
