### ISSUE TITLE
PSR-2 formatting

### ISSUE THREAD

**Issue by franzliedke** [flarum/core#87]
Since all we do with Travis (currently) is checking that the code style adheres to PSR-2, this should be easy to fix with the [CS fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer).

Also, for now we can disable different PHP versions, since we're not actually unit testing anything.

**Comment by franzliedke** [comment]
Fixed in 7885c9a002a2b788aafd02e3f2261ed053c090b9, dd54803aaf2eed1b7454ce1341afaf49242491ce and f7e241e410133a175e0d989922bc66d154db7259.

**Comment by tobscure** [comment]
Awesome work :)

**Comment by franzliedke** [comment]
Really easy to do with PHPCS and the php-cs-fixer. =)
