### ISSUE TITLE
Monorepo?

### ISSUE THREAD

**Issue by tobscure** [flarum/core#874]
https://github.com/babel/babel/blob/master/doc/design/monorepo.md

Here's what it would look like:

![screen shot 2016-03-19 at 9 48 32 pm](https://cloud.githubusercontent.com/assets/128862/13898303/bd4e13d0-ee1c-11e5-9a05-56458cbbac15.png)

We would either need to rename our skeleton to something like `flarum/forum` (`flarum/core` would become `flarum/flarum`), or choose a different name. I don't think it would make sense to keep `flarum/core` as the name, seeing as it would contain packages that aren't "core".

The flarum/flarum composer.json would need to contain autoloading definitions for all of the bundled extensions.

We would also need to adjust the ExtensionManager to scan the packages directory for `flarum-ext-` subdirectories.

I'm not convinced :P I think this kind of thing might work better for JS projects on npm because they have the ability to publish each package/subdirectory individually. Whereas with Composer/Packagist there's no way to do that, you can only publish a whole repo as a package. So doing this feels a bit unnatural.

A PHP project similar to us, [Grav](https://github.com/getgrav), does not use a monorepo. Furthermore, they have issues enabled on all their individual repos... the horror! :scream: 

I think I'm probably in favour of not pursuing the monorepo. Any final thoughts?

**Comment by franzliedke** [comment]
Let it sit a bit...

**Comment by franzliedke** [comment]
One thing we could still do is combining flarum/flarum and flarum/core. When loaded for integration, the skeleton files would simply sit there doing nothing...

**Comment by tobscure** [comment]
Interesting, I'll think about that...

**Comment by tobscure** [comment]
@franzliedke The problem with that is then the update process becomes more difficult. You can't simply call `composer update` anymore – you'd have to manually download the latest version of the source and overwrite your files.

**Comment by sijad** [comment]
@tobscure what was goals of separating `flarum/flarum` and `flarum/core`?

**Comment by sijad** [comment]
@tobscure sorry for my previous comment I didn't read carefully
do you know any PHP extensible project that follows monorepo? what about frameworks?

**Comment by franzliedke** [comment]
Both Symfony and Laravel do this, probably Zend Framework does, too. However, they need to run subsplits regularly to publish the components to their own repositories so that they can be used independently with Composer. That's the biggest downside of this approach in PHP land.

**Comment by sijad** [comment]
Monorepo means users cannot uninstall core extension?

**Comment by tobscure** [comment]
@sijad yes, but you can disable them

**Comment by sijad** [comment]
just for clarification, figuratively if there was an important issue related to an core extension which needs a immediate fix, you need to bump the whole package version?

**Comment by tobscure** [comment]
yep

**Comment by Luceos** [comment]
At this point I really enjoy being able to load any version of Flarum/Core by simply changing the repository in my workbench. This independence from the skeleton is amazing. That also goes for all extensions. I think it would be beneficial in the long run too to allow specific core (or secondary) devs to be responsible for core packages and tag them when needed, instead of having to push a tag for the whole flarum installation every single time..

**Comment by tobscure** [comment]
Closing as at this stage I think the balance is clearly in the favour of keeping it as-is.
