### ISSUE TITLE
Set up ESLint

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#879]
http://eslint.org/

Need to discuss style rules we want to use.

**Comment by tobscure** [comment]
@franzliedke and I discussed and have decided to use the Airbnb preset with as little modification as possible.

**Comment by sijad** [comment]
isn't https://github.com/airbnb/javascript/blob/master/linters/.eslintrc?
if you still have plan to use airbnb. a few dev dependencies should be added to `flarum-gulp` tough.

**Comment by dav-is** [comment]
I found this config works well with Flarum:
```
{
	"extends": "eslint-config-airbnb",
	"rules": {
		"import/no-unresolved": "off",
		"import/no-extraneous-dependencies": "off",
		"react/jsx-filename-extension": ["error", { "extensions": [".js", ".jsx"] }],
		"react/react-in-jsx-scope": "off",
		"react/prop-types": "off",
		"import/extensions": ["error", "never"]
	},
	"env": {
        	"jquery": true
    	},
	"globals": {
        	"app": false,
        	"m": false
    	}
}
```

**Comment by sijad** [comment]
here's mine: https://github.com/sijad/flarum-ext-links/blob/master/.eslintrc

**Comment by sijad** [comment]
[jsx-filename-extension.md](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-filename-extension.md) consider #1030

**Comment by franzliedke** [comment]
We have decided we want to adopt prettier instead of eslint and will do so as part of (?) the frontend rewrite.
