### ISSUE TITLE
Add CAPTCHA to the registration process

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#884]
Mentioned in #641 by @moutonnoireu; also brought up in the forums on occasion.

Would it be a good idea to include alternative solutions, such as admin-configurable questions or text message verification, as part of the same extension? So admins could choose their preferred method, or perhaps a combination of methods ...

Also, are there any places where this would be useful? The subject of allowing posts by unregistered users has been brought up once or twice ...

**Comment by moutonnoireu** [comment]
It could be useful if a new option to authorize non-registered user to speak in a specific tag and thus, a captcha would be useful there.

**Comment by tobscure** [comment]
I think we'll leave CAPTCHA to a third-party, so this can be closed?

**Comment by franzliedke** [comment]
Fine with me. It can be considered again later, but it's not required in core for a first stable release, I'd say.
