### ISSUE TITLE
Flarum in a subdirectory returns 404 for everything

### ISSUE THREAD

**Issue by datitisev** [flarum/core#886]
This starts in https://discuss.flarum.org/d/2300-style-the-login-modal/11

So _gigamick_ made his forum in a subdirectory and everything was working for him.
Now, suddenly, he gets 404 for everything except Flarum assets and forum home page (on /flarum).
The api returns not found all the time.

I was able to reproduce this error, but in a different way.
1. Installed Flarum dev-master locally
2. Set Up Flarum
3. Downgraded Flarum to v0.1.0-beta.4

* When I load the page, discussions appear, guessing from cache
* If i click the button to refresh discussion list, resource is not found, 404.

I have no clue what caused this, but it seems his `.htaccess` and `config.php` are alright.

**Comment by Kakifrucht** [comment]
I have my beta4 in a subdirectory and you can link to threads correctly. However linking to subcategories causes 404's.

**Comment by datitisev** [comment]
Yeah, we don't have much info... which for a bug is not suggestable, but still, it is a bug, and we couldn't figure out what caused it.

**Comment by sijad** [comment]
just asking:
* are you using `Apache`?
* are you sure `mod_rewrite` is activated?

**Comment by datitisev** [comment]
I was using Apache, yes.
I also had `mod_rewrite` activated.
It just happened for me when I downgraded from _dev-master_ to _v0.1.0-beta.4_
For [@gigamick](https://discuss.flarum.org/u/gigamick) it looks like it just suddenly happened @  http://lyrical.me/flarum

**Comment by Kakifrucht** [comment]
I'm using nginx. You can check out the issue here:
Link to thread in subfolder working: https://halfminer.de/forum/d/163
Link to category not working: https://halfminer.de/forum/t/lounge
However you can select categories while on the site properly.

**Comment by datitisev** [comment]
For you if you refresh when you click [tags](https://halfminer.de/forum/tags) it also says not found, it only works because it uses javascript in the beginning…
This is all very weird. :|

**Comment by datitisev** [comment]
For you if you refresh when you click [tags](https://halfminer.de/forum/tags) it also says not found, it only works because it uses javascript in the beginning…
This is all very weird.

**Comment by sijad** [comment]
@datitisev `api.php` can be executed by your apache's User?

**Comment by datitisev** [comment]
@sijad I can't test anything anymore because I solved the issue by reinstalling flarum. Sorry

**Comment by franzliedke** [comment]
Seeing how this did not happen to you when you ran dev-master, @datitisev, I am strongly ssuming this was fixed during the development of beta.5. And I also remember that we fixed some subfolder-related bugs, so this may be done already?

**Comment by datitisev** [comment]
@franzliedke It didn't happen for me on v0.1.0-beta.4 either, but I wasn't using a subdirectory.
I was just using the latest commit of Flarum/core, and then I changed the dependencies to beta.4, and suddenly that error was happening. This wasn't in a subdirectory either.

> And I also remember that we fixed some subfolder-related bugs, so this may be done already?


Hopefully, it seems it is a serious and random problem :|

Thanks for your support, everyones! :smiley:
