### ISSUE TITLE
Security risk using third party server to minify JS 

### ISSUE THREAD

**Issue by sijad** [flarum/core#887]
currently `JsCompiler` class uses an external server to minify JS files (`http://s9e-textformatter.rhcloud.com/flarum-minifier/`)
hypothetically if someone rich to that server, that person can inject any JS code to Flarum
also using `https` is encouraged for this kind of interactions

**Comment by franzliedke** [comment]
That's true, especially the https part.

ping @s9e

**Comment by JoshyPHP** [comment]
If you're concerned about third-party services then you install your own, as described in the [original PR](https://github.com/flarum/core/pull/748).

If you're concerned about MitM attacks then you should definitely use HTTPS.

**Comment by franzliedke** [comment]
Well, does your server support HTTPS?

**Comment by JoshyPHP** [comment]
Yes, OpenShift supports SSL.

**Comment by tobscure** [comment]
Having to run our own server for this is not ideal, I think our best bet is to go back to using Google's - I think people will be pretty happy to rely on that.

**Comment by JoshyPHP** [comment]
What issue does that solve though?

**Comment by tobscure** [comment]
> currently JsCompiler class uses an external server to minify JS files (http://s9e-textformatter.rhcloud.com/flarum-minifier/)
> hypothetically if someone rich to that server, that person can inject any JS code to Flarum

Users might be more inclined to trust the Google Closure Compiler service – which is used by many more people each day, and run by a company with a lot of security experience/resources/etc. – than a more obscure server. At least, that's my gut feeling. What do you think?

**Comment by Luceos** [comment]
Maybe a very stupid question, but why is a remote JS compiler necessary? Aren't there packages which can do this locally or would that increase the Flarum size too much?

**Comment by sijad** [comment]
@luceos [closure compiler](https://developers.google.com/closure/compiler/) do way more that just removing white spaces

**Comment by tobscure** [comment]
Using a PHP JS minifier is possible, but Closure Compiler (which is a Java app) does a lot more to optimize the performance of your code and minify the filesize even more. Obviously we can't depend on a Java app running locally, hence use of the external service (Google vs. s9e vs. whatever)

**Comment by JoshyPHP** [comment]
> What do you think?

In terms of perception I totally agree. In terms of actual risk, I don't know. I'd favor hosting a minifier on a server you control to pool the risk. I think that Appspot (which hosts Google's Closure Compiler Service) is inaccessible from China too. I haven't checked recently though, so it may not be the case anymore.

**Comment by webeindustry** [comment]
You can use a minification module within nginx or apache and cache the files locally. If you're set on using google composure it can be run locally and cached as well.

**Comment by luceos** [comment]
The s9e server is down. Not sure I assumed I reported this elsewhere, but can't find this. We need to prioritise this as errors are thrown in environments that do not suppress warnings.

**Comment by gwillem** [comment]
As [demonstrated here](https://discuss.flarum.org/d/7784-very-slow-load-times-on-cold-cache-profiling), even the Google service shows erratic response times (plus 10 to 30 seconds). I'm not so much worried about a security risk, but I am about increased instability by relying on external services. With every external runtime dependency, the chance of disruption increases exponentially.

**Comment by franzliedke** [comment]
Will be fixed with [the move to Webpack](https://github.com/flarum/core/pull/1367).
