### ISSUE TITLE
Accessibility considerations

### ISSUE THREAD

**Issue by tobyzerner** [flarum/core#892]
Leaving this here for future reference: http://accessibility.parseapp.com/#0

**Comment by franzliedke** [comment]
Thanks so much for posting this! That's a great resource, too.

This is a topic near and dear to my heart, and I would have pushed for this very soon anyway. :)

**Comment by franzliedke** [comment]
Given the link does not work anymore, and there are no concrete tasks, I will close this issue.

**Comment by matteocontrini** [comment]
An archived version of the link is available here anyway:

https://web.archive.org/web/20161229194106/http://accessibility.parseapp.com/

😊
