### ISSUE TITLE
Windows loses image file extensions

### ISSUE THREAD

**Issue by jordanjay29** [flarum/core#893]
[As per this topic at discuss.flarum](https://discuss.flarum.org/d/2359-avatar-upload-still-doesnt-work-in-beta-5)

It seems like Flarum is saving the image file to a .tmp extension, but while Linux can recover the true extension and finish the upload, Windows loses its mind and produces a 500 error instead.

**Comment by dcsjapan** [comment]
Discussion of the cause and workarounds begins at [line 16](https://discuss.flarum.org/d/2359-avatar-upload-still-doesnt-work-in-beta-5/16) of that thread.

**Comment by Averell7** [comment]
The real answer begins at post 24 of the above mentioned thread. 
It is proved that creating a temp file with .jpg extension instead of tmp solves the problem in Windows. No problem if the file is really a gif, png or jpg file, it works for all three types.

**Comment by Averell7** [comment]
Suggested solution :
in project/vendor/flarum/core/src/Core/Command/UploadAvatarHandler.php

```
$tmpFile1 = tempnam($this->app->storagePath().'/tmp', 'avatar');
$tmpFile = str_replace(".tmp", ".jpg", $tmpFile1);         
register_shutdown_function(create_function('', "unlink('{$tmpFile1}');"));        
$command->file->moveTo($tmpFile);
```
