### ISSUE TITLE
Security: flarum doesn't preserve protocol method of uri

### ISSUE THREAD

**Issue by mlyle** [flarum/core#898]
If one loads https://forum.dronin.org, you get a mostly-blank page.

The javascript console fills with:

```
[Warning] [blocked] The page at https://forum.dronin.org/forum/ was not allowed to run insecure content from http://forum.dronin.org/forum/assets/forum-bf694478.css. (forum, line 11)

[Warning] [blocked] The page at https://forum.dronin.org/forum/ was not allowed to run insecure content from http://forum.dronin.org/forum/assets/forum-a1870e9f.js. (forum, line 82)
```

because the forum attempts to retrieve page elements over http;  if it forms fully-qualified urls, it should preserve the http/https portion of the URI.

**Comment by franzliedke** [comment]
Please configure the base URL correctly in config.php.

**Comment by mlyle** [comment]
@franzliedke So I can only support one or the other?  Can't support people deciding to use https for encryption?

**Comment by franzliedke** [comment]
Currently, yes. Just configure your server to redirect HTTP requests to HTTPS. Why do you want to support both?

**Comment by JoshyPHP** [comment]
Isn't it possible to use a protocol-relative URL in config.php?

**Comment by mlyle** [comment]
Yes, it is.  my bad, sorry for the false report.
