### ISSUE TITLE
[Emoji] Suggest only emoji that initially match the string

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#901]
**Problem:**

While the emoji popup seems to provide suggestions based whatever characters are entered after the colon, the algorithm seems to cast its net too wide and doesn't sort the results in any useful order.

![emoji1](https://cloud.githubusercontent.com/assets/13129997/14162325/f91ffe34-f725-11e5-96fa-e0d56dc39cd5.png)

Perhaps I'm too used to how Gitter does things, but when I type in "`:b`" I expect to see a list of emoji whose names start with "b". Instead, I get every emoji whose name *includes* the letter "b" ... and the list is not arranged in any order I can make sense of.

![emoji2](https://cloud.githubusercontent.com/assets/13129997/14162420/b4219256-f726-11e5-9108-2d95a96369ca.png)

Adding a second letter at least brings a few words that start with "b" to the top of the list ... but that's probably just coincidence, since I typed "`:be`" and the suggestions begin with "ba". Now, I would have expected to see "bento" there ...

![emoji3](https://cloud.githubusercontent.com/assets/13129997/14162466/19083184-f727-11e5-87fe-1b56af625468.png)

... but in order to get that as a top suggestion, I need to type "`:bo`". :stuck_out_tongue: 

**Suggestion:**

To be truly useful, the popup needs to behave predictably ... so it should display only suggestions that match the beginning of the emoji's name, sorted in alphabetical order.

---

If that would result too narrow a list of suggestions (or none at all in too many cases), I think it would be okay to include any emoji whose names merely *include* the entered characters ... but these should only appear ***after*** the complete alphabetical list of exact initial matches.

**Comment by jordanjay29** [comment]
I'd agree that Dominion's use case makes sense, and not the way Flarum currently operates.

**Comment by tobscure** [comment]
> include any emoji whose names merely include the entered characters ... but these should only appear after the complete alphabetical list of exact initial matches.

Agreed, let's do this.

/cc @sijad
