### ISSUE TITLE
Admin user can't edit own account

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#903]
Reported by Scarwolf in [this thread](https://discuss.flarum.org/d/2386-can-t-set-a-group-for-a-user):

As of Beta 5, an admin user is unable to edit his/her own account using the Edit User function:

- Can't add himself to a group
- Can't change the email address
- Can't change the password

Confirmed by @tobscure via Gitter. Regarding the last two points, it is probably just as well that direct editing of the email address and password be disallowed.

> @tobscure The bug is that as of b5, to change your own email address via the API, you need to supply your current password. This is obviously impossible in the Edit User dialog. Regardless, it's a security risk to allow changing one's own email or password without any kind of email/password confirmation. Therefore the solution is to not display the "email" and "password" fields in the Edit User dialog if the user is editing themselves.

**Comment by viruxe** [comment]
I don't know if anyone is aware but editing our own username is also impossible.

**Comment by tobscure** [comment]
@viruxe yep it's been fixed in 0f975da
