### ISSUE TITLE
[Signatures] Add per-user setting to disable display of signatures

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#905]
## Issue:

It seems some that users may find signatures *too* distracting, and so may prefer to turn them off. It's a shame that they'll miss out on all the fun and excitement provided by this wonderful new feature, but as Greg Lake used to sing, *C'est la vie !*

## Suggestion:

A simple on-off button in the user profile could be added for this purpose; we could put it right next to the signature field, next to the GIF image playback speed control, so it will be easy to find.

## Other considerations:

We'll have to discuss how disabling the display of signatures will impact the **gamification extension** that we've been planning for our next "New Feature Friday" announcement. Perhaps imposing some sort of deficit point value, which the user could make up in other ways (such as liking their own posts, or quoting two or more posts in the same reply, several times in a row) would be appropriate.

## Expiration:

This issue will not be valid past the following date:

![iu](https://cloud.githubusercontent.com/assets/13129997/14200717/c50e8c8e-f827-11e5-99c9-be3827ff6476.jpeg)

April 1, 2016

**Comment by Cu8eR** [comment]
April joke... but why? This feature makes sense :)

**Comment by Kakifrucht** [comment]
@Cu8eR nah not really

**Comment by dcsjapan** [comment]
@Cu8eR If you haven't read [Toby's description of the Signatures feature](https://discuss.flarum.org/d/2395-announcing-signature-support-in-flarum), I highly recommend it!

**Comment by dcsjapan** [comment]
Closing this issue, as it has served its purpose.
