### ISSUE TITLE
[Tags] Make tag pages indexable w/ custom metadata?

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#906]
Based on feedback from Valoris in [this thread](https://discuss.flarum.org/d/2398-tags-and-seo):
- Make the content of tag pages indexable by search engines.
- Allow customization of the metadata for these pages.

I thought I'd leave this here so @tobscure can think about it while overhauling the Tags extension.

**Comment by tobscure** [comment]
From @aethior in #1144, which goes hand-in-hand with this issue:

> The missing tags show a 200 (Ok) status code. I think these links should use a 404 (Not Found) code.

> ![image](https://cloud.githubusercontent.com/assets/1769227/23631979/7eac6b9a-02c0-11e7-900a-343c68abfedd.png)

**Comment by aethior** [comment]
Missing pages also show a 200 (Ok) status code.

![image](https://cloud.githubusercontent.com/assets/1769227/23841399/4650ceb6-07ad-11e7-854c-a015cc75286a.png)

**Comment by franzliedke** [comment]
This is a bit tricky. What would the correct behavior look like, for empty result sets? As far as I can tell, it's this:

- for the normal index page (page = 1) or with any other search criteria, we should return HTTP 200 and an empty result
- if the user requests any page higher than the total page count for whichever search result we are talking about, the response status should be 404

Is there any more complexity involved?

**Comment by aethior** [comment]
Missing users generates `The requested resource was not found.` message and an infinite loading page.

![tlieheucwvuaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/1769227/24072458/5c7fb0e2-0be7-11e7-8ba9-baeb30b1495f.png)

**Comment by franzliedke** [comment]
404s and no-script content on the tags page have both been done for a while.
