### ISSUE TITLE
Prevent crawling of nojs pages

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#912]
Reported by @dav-is via Gitter chat:

It looks like Google crawled the community site while it was experiencing JS issues and ended up recording some `nojs` URLs.

![nojs](https://cloud.githubusercontent.com/assets/13129997/14237923/403c871e-fa65-11e5-9c68-f5d87c8a1272.png)

Some sort of countermeasures are needed to keep search engines away from these URLs.

It might also be a good idea to use Google web tools to get the site recrawled, so people won't follow the links to these URLs.

**Comment by kulga** [comment]
Seems like a issue with the server configuration (and possibly robots.txt file) then a issue with flarum itself..
In any case, [this post](https://stackoverflow.com/questions/19113788/google-disable-certain-querystring-in-robots-txt/19114489#19114489) looks helpful


robots.txt
```
Disallow: /*?nojs=1
```

**Comment by franzliedke** [comment]
I agree it's not a core issue. But it nicely shows the kind of problems that you get when doing single-page applications... *sigh*

We can leave this one open as a reminder to fix it, though.

**Comment by dcsjapan** [comment]
It's the sort of thing that admins won't know to fix unless we tell them.

If the robots.txt syntax suggested by @kulga will do the trick (I hadn't realized robots.txt could be used that way) then this could be handled by a super-slick installer. It could create a robots.txt file containing this line ... problem solved, yes?

If that sounds good, I'll add a note to the installer discussion issue pointing at this one.

**Comment by dav-is** [comment]
Couldn't the robot.txt just be placed in flarum's root directory?

**Comment by dcsjapan** [comment]
Would that work even if Flarum is installed in a subdirectory? ... I've been under the impression that robots.txt has to be in the web root, or it may be ignored..

Maybe we should just add this to the installation docs, instead? It's a simple enough procedure.

**Comment by tobscure** [comment]
What about using canonical URL meta tags?

**Comment by dav-is** [comment]
@dcsjapan Yeah. Just looked it up. It has to be at the root

**Comment by dav-is** [comment]
Google has settings on crawling with the webmaster tools
![img](http://i.imgur.com/uw3k4VI.png)

**Comment by tobscure** [comment]
@dav-is But google probably isn't the only search engine we need to fix this for :)

**Comment by franzliedke** [comment]
Posting for further reference:
https://developers.google.com/webmasters/control-crawl-index/docs/robots_meta_tag

**Comment by franzliedke** [comment]
As discussed in flarum/flarum#36, we will build a middleware that sends a special header on these pages.

**Comment by franzliedke** [comment]
P.S.: @sijad wants to do this.

**Comment by sijad** [comment]
@franzliedke is it a good idea to add those tags in [app view](https://github.com/flarum/core/blob/fcfc1b2a37e704955093f8d6082d327765dbef9c/views/app.blade.php) header?

**Comment by tobscure** [comment]
Would it be better to be using a canonical URL meta tag rather than a noindex directive?

**Comment by sijad** [comment]
@tobscure yes it seems a better solutions. should I PR a new one?

**Comment by tobscure** [comment]
Or maybe in addition to noindex. Because canonical URL should probably be constructed and set by individual controllers (eg, DiscussionController) rather than just by stripping ?nojs=1 off the end of the current URL...

**Comment by franzliedke** [comment]
Yes, we should *allow* controllers to generate a canonical URL, and if we have one, the view will print the meta tag.

**Comment by dav-is** [comment]
Speaking of canonical urls, should the discussion list have a canonical url that doesn't have the post number in it? For example: forum.example/d/5/77 => forum.example/d/5

**Comment by tobscure** [comment]
not sure I understand @dav-is?

**Comment by dav-is** [comment]
Well the page forum.example/d/5 would have the same content at forum.example/d/5/8 and the same content as forum.example/d/5/9. There's overlap in content so should we just remove the post number from the url using the canonical tag? When google crawls, doesn't it scroll down and load all the posts?

**Comment by tobscure** [comment]
> When google crawls, doesn't it scroll down and load all the posts?

I don't think so? We do know that Google will wait for AJAX content to be loaded... but I can't imagine it would trigger a scroll event. So I think it will only see whatever content is preloaded.

You're right that certain discussion URLs will have similar content though. Maybe we should make the canonical URL use a number rounded down to the nearest multiple of 20 (or however many posts per page there are)?

**Comment by Luceos** [comment]
I was under the impression indexer bots can understand pagination and call on next, prev and other links..

http://stackoverflow.com/questions/35952151/javascript-pagination-and-seo

**Comment by dav-is** [comment]
https://webmasters.googleblog.com/2014/02/infinite-scroll-search-friendly.html?m=1

**Comment by franzliedke** [comment]
Since this topic came up quite often... here's what I understand:

- discussion pages should have rel=canonical meta tags - we [have an issue for this](https://github.com/flarum/core/issues/358), and I've bumped it so that it gets done soon
- this canonical tag should link to the first page
- we should have additional pagination links (for search engines) that lead to search-engine-friendly pages, that - **important!** - can be used to access exactly that range with JS in a browser, too
