### ISSUE TITLE
[Tags] deleted messages show up on tag tiles

### ISSUE THREAD

**Issue by luceos** [flarum/core#913]
Just deleted a test thread on my empty Hyn production forum, but the discussion still shows up on the tag tile footer:

https://discuss.hyn.me/tags

![fireshot capture 10 - hyn - https___discuss hyn me_tags](https://cloud.githubusercontent.com/assets/504687/14239116/e058f46c-fa38-11e5-8838-575f203cee98.png)

**Comment by franzliedke** [comment]
Is it still there after reloading the page?

**Comment by franzliedke** [comment]
Oh, never mind. Yes, it is, I visited the site myself. ;)

**Comment by askvortsov1** [comment]
Will be fixed in https://github.com/flarum/tags/pull/78
