### ISSUE TITLE
Deleting all tags causes a 503

### ISSUE THREAD

**Issue by zethon** [flarum/core#916]
Installed a fresh install and all was working well. Went in the Admin panel and deleted the General tag and every/any request returned 503. I was able to fix this by manually adding a row to the 'tag' table in db.

**Comment by eikcam** [comment]
I am not able to replicate this issue. Did you create a post first or just fresh install and immediately delete the general tag?

**Comment by zethon** [comment]
Hmm.. I just tried recreating with a fresh install, but I'm unable to do so. If I hit this again I'll ad some details.

**Comment by chimericdream** [comment]
I just ran into this with a fresh install last night. I did not create any posts first, and I deleted the General tag. All subsequent requests resulted in an error until I manually added the General tag back in the database. I'll try to reproduce it today and get a step-by-step breakdown for what to do.

**Comment by franzliedke** [comment]
I am closing this issue as it seems to have grown stale. If you still encounter this problem with the latest version, please feel free to re-open it.

Please understand that outdated issues are closed regularly to keep the amount of open issues to a manageable minimum. In any case, thanks for taking an interest in this software and opening the issue in the first place!
