### ISSUE TITLE
Incorporate humanTime output in notification translations?

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#932]
I should have noticed this back when I was doing the extractions, but I was too busy making sure I didn't screw up the code to pay attention to what was happening with the phrases.

![screenshot](https://cloud.githubusercontent.com/assets/13129997/14562285/be1437d2-0356-11e6-8a16-9373aff63596.png)

Although notifications from Likes, Mentions and Subscriptions can be read as a single clause, they are actually composed of two parts: a translatable phrase followed by output from humanTime indicating the time of the event. This is problematic because it involves:

- Hardcoded spaces
- Hardcoded syntax

It would be better if the humanTime output were incorporated into the phrase as a variable (as has been done with `core.forum.discussion_list.replied_text` and `core.forum.discussion_list.started_text`) so that localizers will be able to adjust its position within the clause.

An alternative might be to right-align the humanTime output, so that it doesn't seem to be part of the same clause as the translation:

![mockup](https://cloud.githubusercontent.com/assets/13129997/14562535/2f7dc28e-0358-11e6-9f3f-55574ac6e2ed.png)

This wouldn't be any harder to do, and might even be easier to read. The phrases might need to be adjusted slightly (e.g. add a period at the end of each) but that wouldn't pose any difficulty.

**Comment by tobscure** [comment]
I think something along the lines of your latter suggestion is the way to go. Really the time is meant to be a separate entity. In fact, in the proposed notifications redesign (#868), it's on its own line, so this won't be an issue :)
