### ISSUE TITLE
[Emoji] Insert emoji unicode character instead of :emoji_name:

### ISSUE THREAD

**Issue by tobscure** [flarum/core#941]
I've just noticed on GitHub that they've started inserting the emoji unicode character instead of the `:emoji_name:` code when you select an emoji from the autosuggest menu.

e.g. if I type `:ok` and select the **ok_hand** emoji, I see 👌  in the text field instead of `:ok_hand:`.

Perhaps we should adopt this change too?

**Comment by Reflic** [comment]
I like this change, for not so technical users this helps to understand, that the emoji was inserted correctly  and not that it has gone wrong.

**Comment by JoshyPHP** [comment]
The two benefits of using a third-party emoji library such as Emoji One or Twemoji is that it provides support for emoji on OS that don't and that it normalizes how emoji are displayed. If you use Unicode emoji in the textarea, it will display a replacement character � on OS where they are not supported and where they are supported, the image will be different from the post's.

IMO, it's only good if you can display the correct image in the editor.

**Comment by luceos** [comment]
Obsoleted due to #1460 .

**Comment by tobscure** [comment]
For the record, you would expect any OS that can run a browser that Flarum is compatible with to support emoji these days?

**Comment by datitisev** [comment]
I’d say yes. Flarum works very slowly in older bwrosers and some mobile browsers because of all the JavaScript, however most operative systems these days have Unicode support, they just not be updated to the latest Unicode Andy may be using their own implementation.
