### ISSUE TITLE
PostUser elements get replicated

### ISSUE THREAD

**Issue by Luceos** [flarum/core#942]
![fireshot capture 14 - let s set up bugsn_ - https___discuss flarum org_d_2699-let-s-set-up-bugsnag_2](https://cloud.githubusercontent.com/assets/504687/14882139/64d71bc2-0d37-11e6-9799-9a65aff64881.png)

My avatar gets replicated, inspecting the body:

```html
<article class="Post CommentPost editing"><header class="Post-header"><div class="PostUser"><h3><img class="Avatar PostUser-avatar" src="https://discuss.flarum.org/assets/avatars/5ztmag78s0pdnjbm.jpg"><span class="username">luceos</span></h3></div><img class="Avatar PostUser-avatar" src="https://discuss.flarum.org/assets/avatars/5ztmag78s0pdnjbm.jpg"> Write a Reply...<div class="PostUser"><h3><img class="Avatar PostUser-avatar" src="https://discuss.flarum.org/assets/avatars/5ztmag78s0pdnjbm.jpg"><span class="username">luceos</span></h3></div><img class="Avatar PostUser-avatar" src="https://discuss.flarum.org/assets/avatars/5ztmag78s0pdnjbm.jpg"> Write a Reply...</header><div class="Post-body"></div></article>
```

It seems the postuser is replicated every time when closing the post composer and clicking the "write a reply .." placeholder area.

Chrome version 50.0.2661.86 (64-bit)

**Comment by franzliedke** [comment]
Hmm, cannot reproduce. Same browser on Ubuntu.

**Comment by Luceos** [comment]
First time I can actually use that emote and it's not awkward :+1:

**Comment by poush** [comment]
Cannot reproduce here. 

Chrome Version 50.0.2661.86 (64-bit) (OSX)
Safari Version 9.1 (11601.5.17.1)

**Comment by franzliedke** [comment]
@Luceos Can you reliably reproduce this on your machine? Or did it happen once, probably caused by some other thing you did before?

(It's obviously a bug; I just want to make sure your description describes the actual steps to reproduce...)

**Comment by Luceos** [comment]
Ok so I could reproduce it on ANY discussion. I then closed and opened Chrome and it was gone (also on ubuntu), so some updates must have gotten in the way of the running application.

Thanks for trying to reproduce @poush and @franzliedke
