### ISSUE TITLE
Markdown links strikethrough

### ISSUE THREAD

**Issue by Kakifrucht** [flarum/core#944]
When adding a Markdown strikethrough with ~~ the characters will be added to a link.
For example
```
~~This is a test https://discuss.flarum.org/~~
```
The Link will lead to https://discuss.flarum.org/~~
Tested here: https://discuss.flarum.org/d/2703-links-markdown

**Comment by Kakifrucht** [comment]
I guess I can close this then?

**Comment by JoshyPHP** [comment]
It should be fixed as soon as #947 is merged. I guess you can wait until then.
