### ISSUE TITLE
Clicking and dragging Scrubber beyond final post causes count to exceed max value

### ISSUE THREAD

**Issue by augiwan** [flarum/core#945]
![flarum-post-count](https://cloud.githubusercontent.com/assets/3384391/14896773/d1080710-0d9c-11e6-9889-b62a77b935f2.png)

**Comment by 01010000101001100** [comment]
Noticed this issue on my installation too.

**Comment by Luceos** [comment]
As a reference: https://github.com/flarum/core/issues/785
