### ISSUE TITLE
Huge whitespace when switching reply to edit

### ISSUE THREAD

**Issue by jordanjay29** [flarum/core#948]
I noticed the post box gains a lot of extra whitespace when a user has opened the screen via Reply and then chooses to edit a post instead without closing and reopening the post box.

Replying:
![Replying](https://cloud.githubusercontent.com/assets/7871706/14925874/2a9006b2-0e0f-11e6-8237-79d48640becf.png)
No, I changed my mind, I'm going to edit my last post. Holy Whitespace, Batman!
![Holy Whitespace, Batman!](https://cloud.githubusercontent.com/assets/7871706/14925872/2a896c94-0e0f-11e6-95ca-d03d243d23d9.png)
This is what edit should look like.
![Normal edit view](https://cloud.githubusercontent.com/assets/7871706/14925873/2a8ad156-0e0f-11e6-8702-b83e07eaa9c7.png)

**Comment by poush** [comment]
Yes I can reproduce it.

**Comment by jordanjay29** [comment]
Also seems to happen with Start Discussion for various interruptions (changing tag page, duplicate Start Discussion clicks, etc).

**Comment by tobscure** [comment]
Yep, I've looked into this before and it's a hard one to solve (to the point where you're digging into Mithril's internals)... but will definitely need to find a fix eventually!

**Comment by luceos** [comment]
I also get this on discuss right now. When in a tag view, create a discussion. Then click on the All discussions link. It happens. When you inspect element, it resets.

![image](https://user-images.githubusercontent.com/504687/32485600-4d14ee0e-c3a4-11e7-8865-8fcc07ae5a53.png)
