### ISSUE TITLE
Avatar popup overlaps with awaiting approval post

### ISSUE THREAD

**Issue by ralphskie** [flarum/core#950]
When a post is awaiting for an approval and you mouse over at the avatar, the popup div overlaps with the post.

i think its a z-index problem

please see the photo
![2016-05-03 17_37_00-new community - negros island ph](https://cloud.githubusercontent.com/assets/5318148/14979658/491d5d7e-1156-11e6-9fd1-572bdcc6388e.jpg)

**Comment by tobyzerner** [comment]
Duplicate of flarum/issue-archive#328
