### ISSUE TITLE
We need removeHeadString and removeFootString in ClientView

### ISSUE THREAD

**Issue by bmalex88** [flarum/core#951]
I was trying to create an extension for selecting a custom font for the entire forum from the administrator and replacing the default one, which is hard-coded (???) in the `ClientView`'s constructor.
But I realized that there's no function for replacing or removing a string from the `headStrings` array.

Is there a workaround for this or should I add these functions to the class (`removeHeadString`, `removeFootString`, `replaceHeadString` and `replaceFootString`?

**Comment by franzliedke** [comment]
I believe @tobscure will revamp the `ClientView` class a bit, that should probably be considered...

**Comment by franzliedke** [comment]
@tobscure You asked which of the two APIs I like better:

~~~php
$view->getHead() // returns an Illuminate Collection
    ->push('value')
    ->put('key', 'value')
    ->forget('key');
~~~
or
~~~php
$view->addHeadHtml('key', 'value')
    ->removeHeadHtml('key', 'value');
// how far would we go with these methods? 
// also keep in mind we'd need to add equivalent ones for foot as well
~~~

I'd go with the second. We control the interface (i.e. the method names define the contract of the class), it fits the "Tell, don't ask" principle, and the first one would violate the Law of Demeter.

(Plus, I was surprised that the methods you called on the collection mutate the collection directly - which doesn't fit very well with other methods that are immutable.)

**Comment by tobscure** [comment]
Hmm, so it'd end up looking something like this:

```php
$view->addHeadSnippet('key', 'value');
$view->removeHeadSnippet('key');
$view->getHeadSnippet('key'); // do we
$view->getHeadSnippets(); // need these?

$view->addFootSnippet('key', 'value');
$view->removeFootSnippet('key');
$view->getFootSnippet('key'); // do we
$view->getFootSnippets(); // need these?
```

What about giving items priorities so that they can be ordered?

It just seems to be a lot of functionality for the view class... all implemented twice (for head and foot).

What about an API like the [JS ItemList class](https://github.com/flarum/core/blob/master/js/lib/utils/ItemList.js)? That's kind of the exact functionality we want for this...

```php
$view->getHeadItems()
  ->add('key', 'value', 10) // specify priorities
  ->remove('key');
```

**Comment by franzliedke** [comment]
I'm okay with a custom collection class.

**Comment by sijad** [comment]
if it does not make things conflicted it's possible to store keys in [http://php.net/manual/en/class.splpriorityqueue.php](SplPriorityQueue)

**Comment by sijad** [comment]
currently it's possible to remove/replace google font by `$view->addHeadString('', 'font');`
