### ISSUE TITLE
Add "staff alert email" helper

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#957]
It would be convenient if Flarum had a helper function, available to the core and extensions alike, that could send an alert email to a specified user (or users) in response to a certain event.

For example, it might be nice if the Akismet extension could send an email to all admins and mods when it flags a post as spam. Email notification could be very useful in heading off a large-scale spam attack. 

The helper would provide a dropdown list of destinations that devs can include in their code, allowing the admin to decide who gets notified about what events. The dropdown list should include the following:

- **Admins** - sends an email alert to every user in the **Admins** group.
- **Mods** - sends an email alert to every user in the **Admins** and **Mods** groups.
- **Contact address** - sends an email alert to the address specified in the [**Email** settings page](https://github.com/flarum/core/pull/933#issuecomment-218919097).
- **None** - disables the sending of alert emails for the event in question.

Such a helper could also be useful for backend configuration of a contact page (i.e., a page where users can contact the staff if they can't log into their account or need to handle something "off the board"). Such a page would probably offer a dropdown list of inquiry topics for the user to choose from, e.g.:

- Account approval
- Email misconfiguration
- Account suspension
- Membership issues
- Moderation issues

... and so on. Presumably the list would be customizable, so the admin can add new topics as needed. The "staff alert email" helper would allow the admin to select the proper destination for each inquiry type. (For example, mods wouldn't be able to do anything about email misconfiguration, so this type of inquiry would get sent to admins only. Moderation issues would also need to go to the admins. All other inquiry types would get sent to the mods as well. That sort of thing.)

I should create am issue for this contact page -- I believe I told @jordanjay29 that I'd do so -- but I'm just mentioning it here as a scenario where the helper would come in handy.

**Comment by jordanjay29** [comment]
>  Admins - sends an email alert to every user in the Admins group.
Mods - sends an email alert to every user in the Admins and Mods groups.

I'd probably change this to a generic group selector to account for varying setups. Not everyone will have a Mods group, or some may have several of them. 

Otherwise, I love this!

**Comment by dcsjapan** [comment]
@jordanjay29 I was thinking in terms of default groups that come built into Flarum:

```
  ##
  # GROUP NAMES - These keys are translated at the back end.
  ##

  # Translations in this namespace are used to translate default group names.
  group:
    admin: Admin
    admins: Admins
    guest: Guest
    guests: Guests
    member: Member
    members: Members
    mod: Mod
    mods: Mods
```

But you're right ... making it a default group selector would increase the utility of the helper. Taking the contact page scenario as an example, allowing any group to be chosen would make it possible for that page to handle inquiries to any group, not just the staff. Good call! 👍 

I'll try to get around to writing up that other issue sometime later today. (I was still a bit feverish when we talked about it, so I ended up forgetting about it temporarily.)

**Comment by franzliedke** [comment]
Interesting concept. Not really feasible before the first release, though, I'd say.

**Comment by jordanjay29** [comment]
Related to flarum/issue-archive#346.

**Comment by tobyzerner** [comment]
To expand on @jordanjay29's comment (as per discussion in the staff meeting):

flarum/issue-archive#346 describes plans to rework flags so that they are merely an additional "type" of notification. In the same spirit, we can add a row to the per-user notification settings grid: "Notify me when a post is flagged". This way, moderators can choose for themselves to both turn off flag notification alerts (if it happens to not be their responsibility to attend to flags), and to turn on flag email notifications, like you would any other kind of notification.

Therefore, with regards to the specific issue (a "staff alert email" helper that extensions can make use of), this will simply exist as the current notifications system.

**Comment by dcsjapan** [comment]
> Therefore, with regards to the specific issue (a "staff alert email" helper that extensions can make use of), this will simply exist as the current notifications system.

In other words ... if someone wanted to write an extension that would (for example) accept input from a contact form and notify different people depending on the type of inquiry received, that extension could just add new settings to the permissions page and the per-user notifications grid.

Am I understanding that correctly? It does sound like a helper isn't necessary. 😄

**Comment by tobscure** [comment]
Yep, pretty much!

**Comment by dcsjapan** [comment]
Great! Thanks for taking the idea under consideration, anyway. We can close this, then, I guess?
