### ISSUE TITLE
User search should be case-insensitive

### ISSUE THREAD

**Issue by tobscure** [flarum/core#961]
Reported by @vijeetgv in https://github.com/flarum/core/issues/283#issuecomment-219906851

**Comment by tobscure** [comment]
This is also potentially a problem in discussion/post searching (https://discuss.flarum.org/d/2254-search-is-broken/14). Needs investigation.

**Comment by vijeetgv** [comment]
@tobscure can't complain http://prntscr.com/b5d1va but it doesn't show anything _while I type_ in the suggestions (like the case of users search). When I hit enter, it shows up.

**Comment by dcsjapan** [comment]
> This is also potentially a problem in discussion/post searching

It seems the dropdown won't list any candidates unless the entered term is all lower case. 😦 ❓
