### ISSUE TITLE
Date/time issues for posts always in English

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#970]
Reported by Bek in [this thread](https://discuss.flarum.org/d/3019-date-and-time-translations-doesn-t-working-in-development-version). The following screenshot was taken with a Turkish langpack (I think):

![ss0](https://cloud.githubusercontent.com/assets/13129997/15664601/5828946e-2740-11e6-852c-d240cc5acbcc.png)

Full date and time in the popup are also affected; this one is with the French langpack:

![ss1](https://cloud.githubusercontent.com/assets/13129997/15664703/fe08b242-2740-11e6-8cf5-83759eb723fd.png)

However the discussion index does not seem to be affected:

![ss2](https://cloud.githubusercontent.com/assets/13129997/15664712/04df7f92-2741-11e6-8a5e-735c42dd4dd3.png)

@franzliedke speculated via Gitter:

> Well, the IP address was recently added. Maybe that broke something...

**Comment by bekirkarul** [comment]
@dcsjapan I think it is affected too. It's look like okay because "*Janvier*" means **January** in French. So both language shorten it as "*Jan*". Check it out with Turkish for example. You should see "Oca" or "Ocak" but it is still Jan.

**Comment by dcsjapan** [comment]
@bekirkarul You could be right about that ... I was judging by the fact that the preceding "*a publié ça*" is properly rendered in French.
