### ISSUE TITLE
Emoji omitted from quotes

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#971]
As described in [this thread](https://discuss.flarum.org/d/2932-i-like-this-features-quote/6).

Digital (formerly modedeep) said that emoji are not quoted when using the quote command popup, but I noticed the same thing happening if I select some text with an emoji and quote it with the **Reply** link.

**Comment by jordanjay29** [comment]
Possibly isolated to Webkit derivatives, I've had no problems with this on Firefox. It only occurs on Chrome (and reports of Safari doing the same).
