### ISSUE TITLE
[Tags] Hardcoded error messages

### ISSUE THREAD

**Issue by jordanjay29** [flarum/core#973]
There are some [hardcoded error messages](https://github.com/flarum/flarum-ext-tags/blob/d0b62510d8a1a9d3a38cfdad0ed8447e85c5f7b0/src/Listener/SaveTagsToDatabase.php#L134) in Tags which cannot be translated by normal means. We should probably convert these to yml file entries.

**Comment by dcsjapan** [comment]
There are two messages: line 118 and line 134.

@tobscure Under what circumstances are these messages output? I tried getting them to appear over at DevFlarum, and couldn't find any way to make it happen.

**Comment by tobscure** [comment]
It's a message that is not going to show up in normal use because Flarum's UI protects against submitting a discussion with the wrong number of tags... but it'll show up if you're interacting with the API directly and you use the wrong number of tags.

**Comment by dcsjapan** [comment]
@tobscure Thanks, that explains it.

Do these need to be extracted? I'm not sure how API messages are affected by locale ...

**Comment by tobscure** [comment]
Yep they should be localized. If you would like to make a PR to flarum-ext-english, I can do the rest :)

**Comment by dcsjapan** [comment]
I can do the PHP changes too, if you like ... I've already created a branch for them.

**Comment by tobscure** [comment]
That'd be great, thanks!

**Comment by dcsjapan** [comment]
If we're using`validation.between.numeric` then I'll have to ask you to handle the PHP end after all. The syntax for adding an attribute is a bit beyond my grasp at this point.

**Comment by tobscure** [comment]
No worries! Thanks for the flarum-ext-english PR!

**Comment by dcsjapan** [comment]
Cool! As I expected, it wasn't quite a simple matter of rewriting a line or two. 😜

**Comment by dcsjapan** [comment]
@tobscure I've been thinking about our approach here. Is there any reason we couldn't just add these phrases at the bottom of `validation.yml` instead of adding a new `api` namespace?

**Comment by tobscure** [comment]
Hmm, yeah I think you're right. If you send a PR to ext-english I'll fix up PHP. Thanks!

The `api` namespace may still be needed in the future (by us or others) so don't undo your changes to the docs.

**Comment by dcsjapan** [comment]
Roger on the PR and on not changing the docs.

Would the phrases go in the `attributes:` namespace? Or should the be `custom:` keys?
