### ISSUE TITLE
Fix "Edited" hover-link in post info line

### ISSUE THREAD

**Issue by dcsjapan** [flarum/core#975]
I just noticed something about the "Edited" hover link at the top of the post. Since it appears before the "ago" link, it can be read as a sentence ... though it looks like someone accidentally threw one space too many in there. For example:

![screenshot](https://cloud.githubusercontent.com/assets/13129997/15799757/d3f53926-2aa1-11e6-89c4-db9315b8187b.png)

It seems to be saying the post was "edited a few minutes ago", when it fact is was only edited a few seconds ago. To avoid this, the "edited" info should probably come after the "ago" link. That would be more natural in any case, since the edits generally happen after post creation. 😉 

... Actually, I wouldn't mind bringing back the "edited" pencil icon ...

**Comment by tobscure** [comment]
Strange, it shouldn't be displaying before the "ago" text... and indeed it doesn't for me! Are you able to provide a specific discussion/post/steps to reproduce?

**Comment by dcsjapan** [comment]
[Here's the post](https://discuss.flarum.org/d/3067-preview-of-discussion-first-post) where I got that screenshot. Strangely enough, the "Edited" hover-link is now **after** the "ago" link. 😝 

I think I've actually found a strange bug ... hold on a sec, I have an idea ... success!

![screenshot2](https://cloud.githubusercontent.com/assets/13129997/15799878/5ba94c3c-2aa6-11e6-977b-04c0ec06cde3.png)

Immediately after you edit a post, the "Edited" info gets stuck in before the "ago". Reloading/refreshing the page moves it to the proper position!

**Comment by jordanjay29** [comment]
Can't confirm, Edited shows up after X Xes ago for me on Discuss.

**Comment by datitisev** [comment]
It happens for me on Chrome iOS 9 50.0.XXXXXXX)

**Comment by dcsjapan** [comment]
Maybe it's another of those WebKit-related oddities.

**Comment by franzliedke** [comment]
I'm afraid it has something to do with our `ItemList` JavaScript class. Had a quick look earlier today, but did not find anything...

**Comment by tobscure** [comment]
I had a look and traced it back to a Mithril bug, as far as I can tell. Will do some further testing with other versions of Mithril etc.
