### ISSUE TITLE
Upgrade to jQuery 3.0

### ISSUE THREAD

**Issue by tobscure** [flarum/core#979]
https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/

We can probably use the slim version.

**Comment by sijad** [comment]
should other packages like `spin.js` or `moment`... be updated?

**Comment by franzliedke** [comment]
Leaving this open as MR #1064 introduced a regression.

I assume you, @sijad, will take care of it? :)

**Comment by sijad** [comment]
yes I'll
