### ISSUE TITLE
s9e JavaScript minification is broken

### ISSUE THREAD

**Issue by tobscure** [flarum/core#981]
Not entirely sure what's going on, but as of the last few days I've noticed that Flarum crashes when using JavaScript minified by http://s9e-textformatter.rhcloud.com/flarum-minifier/.

```
forum-05ad5387.js:20 Uncaught TypeError: document.jc is not a function(anonymous function) @ forum-05ad5387.js:20(anonymous function) @ forum-05ad5387.js:22
forum-en-df77f08d.js:1 Uncaught ReferenceError: System is not defined(anonymous function) @ forum-en-df77f08d.js:1
1199-finnish-language-pack:205 Uncaught ReferenceError: System is not defined
```

If I comment out adding the `$remoteCache` and the `$hostedMinifer` in JsCompiler, the minification is done with ClosureCompilerService, which works fine.

@JoshyPHP has anything changed on your end? I suppose this is a good reminder that we should perhaps get our own minification service running...

**Comment by JoshyPHP** [comment]
A new version of Google Closure Compiler (v20160517) was released last month. I don't know what version is currently run by Google's Closure Compiler service, they generally don't announce when they update their local version. The local version of Google Closure Compiler that runs on http://s9e-textformatter.rhcloud.com/flarum-minifier/ was updated on June 6. Most of the time, the service acts as a write-through cache to Google's own service, but if Google's service is too slow or unavailable it will run the application locally. I don't know which of the Google Closure Compiler service or application minified a specific file.

Assuming no other factor, a likely explanation would be that the latest version of Google Closure Compiler produces a different result than the one that preceded it and that Google's service runs an older version than mine. Whichever version of the compiler generated the file, once it's cached it's served to all future compilations. I have cleared the service's cache but we still need to know how to get Closure Compiler to generate the bad file.

@tobscure Can you post the unminified file please? It would be interesting to find how both versions differ.

**Comment by JoshyPHP** [comment]
A new version of Google Closure Compiler (v20160517) was released last month. I don't know what version is currently run by Google's Closure Compiler service, they generally don't announce when they update their local version. The local version of Google Closure Compiler that runs on http://s9e-textformatter.rhcloud.com/flarum-minifier/ was updated on June 6. Most of the time, the service acts as a write-through cache to Google's own service, but if Google's service is too slow or unavailable it will run the application locally. I don't know which of the Google Closure Compiler service or application minified a specific file.

Assuming no other factor, a likely explanation would be that the latest version of Google Closure Compiler produces a different result than the one that preceded it and that Google's service runs an older version than mine. Whichever version of the compiler generated the file, once it's cached it's served to all future compilations. I have cleared the service's cache and rolled back to Google Closure Compiler v20160315 but we still need to know how to get Closure Compiler to generate the bad file. If that's a bug, you'll want it to be fixed before Google update their service.

@tobscure Can you post the unminified file please? It would be interesting to find how both versions differ.

**Comment by tobscure** [comment]
@JoshyPHP Thanks for the info!

https://dl.dropboxusercontent.com/u/15724107/forum-unminified.js
https://dl.dropboxusercontent.com/u/15724107/forum-minified.js

Seems that `document.getElementsByTagName` is being turned into `document.jc`. Also I can't find the declaration of the `System` variable anywhere (looking for `System=`).

Confirmed that mininfied JS produced by http://s9e-textformatter.rhcloud.com/flarum-minifier/ after the downgrade is now working again.

**Comment by JoshyPHP** [comment]
It appears the file was minified in `ADVANCED_OPTIMIZATIONS` mode. I dug deeper and found the cause in the webservice's configuration. So it's not a bug in Closure Compiler (the application or Google's service) it was a bug in the service I run. I fixed it and restarted the service with a clean cache so it shouldn't happen again.

**Comment by tobscure** [comment]
Thanks @JoshyPHP, good to have this solved :)
