### ISSUE TITLE
Use Flysystem as a service

### ISSUE THREAD

**Issue by BartVB** [flarum/core#984]
I was browsing the code and bumped into:
https://github.com/flarum/core/blob/58d7be95c165c9b99cd991a530a28d06f31d8249/src/Api/Controller/DeleteFaviconController.php#L55

I.e.:
`$uploadDir = new Filesystem(new Local($this->app->publicPath().'/assets'));`

In my opinion Flysystem would be used much better if the `Filesystem()` was injected as a service. That way it's trivial to swap out the local adapter with the S3 adapter for example. For avatars that's probably not that big a deal, but it is when handling proper image/photo uploads.

Edit: Hmm, this:
https://github.com/flarum/core/blob/31997b8fdf8cf088406dd09d9138b01bbca646af/src/Core/CoreServiceProvider.php#L45
Already seems to provide an `$avatarsFilesystem`? But as far as I can tell this is never used?

**Comment by franzliedke** [comment]
Good catch, thanks!

As you already noticed, we do use proper injection for uploading avatars. The service provider code that you linked in your edit makes sure that the proper instance for avatars is injected in classes like [this one](https://github.com/flarum/core/blob/08aaba6426b14d57605a33072dd8a70d84fa4443/src/Core/Command/UploadAvatarHandler.php).

A similar thing thus needs to be done for favicons. If you're interested in sending a pull request, we can guide you through the process. :)

**Comment by askvortsov1** [comment]
Closed in https://github.com/flarum/core/commit/1fa37a7a6a755abd4686994ef0bb5f0b432f45ec. It would still be nice to make this filesystem manager system extendable, but that's something we can keep track of in https://github.com/flarum/core/issues/2094
