### ISSUE TITLE
Site name: managing it independently from current H1 (Header-title) 

### ISSUE THREAD

**Issue by wion** [flarum/core#986]
I'm [under the impression](https://discuss.flarum.org/d/2739-davis-custom-header/32) that Davis' _Header_ extension is being added to beta6 (nice!). This issue is in relation to that merger.

With the addition of a new global identity/navigation bar ([for example](https://discussion.community)), and the likely potential that `<h1 class="Header-title">` no longer serves the role it was originally designed to fill (in the CSF site example, you can see the `h1` is now serving under the "Main page" link in the Flarum controls bar), it will be necessary to have custom control over `title` element values.

The current "Site Name" value in Admin > Basic outputs in these locations:
- `<h1 class="Header-title">`
- `<title>`
- Name for the "From" field in email notifications

But when that value no longer functions as the principle site identification, as will be the case with a new global identity/nav bar implementation (again, see the CSF discussions site, where the `h1` value has become "Main page"), it no longer makes sense to auto-fill all those locations with the same value. Notably the `h1` value becomes a problem. And the `title` value is not longer working well in search engines either. So bad for humans and machines.

At the very least, there should be a separate configuration for customizing what goes in the `title` element so that shared links and email notifications can use a custom identity. Or just make it so the Site Name value doesn't also fill the `h1`.

The question then is, how should you change handling the `h1` value?

One radical idea would be to merge @sijad's Links and Pages extensions into core too as a single **Local pages** feature managed in Admin > Dashboard, or wherever. Then a site owner could use that native functionality to manage the `<h1 class="Header-title">` and `<div class="Header-primary">` items together easily, but under a more logical semantic.

For example, changing this:

```
<div class="container">
  <h1 class="Header-title">...</h1>
  <div id="header-primary" class="Header-primary">
    <ul class="Header-controls">
      <li class="item-link1">...</li>
      <li class="item-link2">...</li>
      ...etc
    </ul>
  <div id="header-secondary" class="Header-secondary">
    <ul class="Header-controls">
      <li class="item-search">...</li>
      <li class="item-flags">...</li>
      ...etc
    </ul>
  </div>
  ...
</div>
```

To this:

```
<div class="container">
  <nav id="localNav">
    <ul class="local-nav">
      <li class="nav-item1 home">Main page</li>
      <li class="nav-item2">Rules</li>
      <li class="nav-item3">Groups</li>
      <li class="nav-item4">Help</li>
    </ul>
  </nav>
  <div id="access">
    <ul class="access-controls">
      <li class="item-search">...</li>
      <li class="item-flags">...</li>
      ...etc
    </ul>
  </div>
</div>
```

I changed some selector names as well to demonstrate how the current redundant patterns in selector names could be cleared up a little too. (A problem throughout the markup that makes working with CSS harder than it needs to be).

Hopefully I explained the root of the problem, at least.

**Comment by wion** [comment]
The merging of "Local Pages" functionality as suggested could also handle things like the proposed Contact page too: #959.

**Comment by franzliedke** [comment]
Those "redundant" selector names make it easier to write conflict-free CSS. If you can style the header with `.Header-controls` instead of `.Header .access-controls`, you avoid [CSS specificity wars](https://stuffandnonsense.co.uk/archives/css_specificity_wars.html).

**Comment by wion** [comment]
"Conflict-free" and "specificity" are funny terms considering Flarum's CSS is locked down and my overrides file is a mile long.  In any case, I'm less concerned about changing selector names (which would screw up my overrides anyway) and more concerned about not having "Main page" in my `title` or in the "From" field of email notifications. Any thoughts about how that will be handled, that we might look forward to. ;)

**Comment by franzliedke** [comment]
Yeah, that's a difficult one. Using <h1> makes sense when the forum just sits on its own, but obviously you want another <h1> when you're integrating the board in your site's design. (On the other hand, I've seen arguments for using <h1> for the *page title* as opposed to the *site title*, as that's more relevant for each specific page, and thus should be marked as such for search engines.)

Too bad that the HTML5 document outline algorithm [was never implemented](http://html5doctor.com/computer-says-no-to-html5-document-outline/) - that would have solved our problem...

We'll discuss this in the next developer meeting, thanks for bringing it up.

**Comment by wion** [comment]
Thanks for discussing it.

Seems to me you could handle it easily by treating the three output locations with separate data fields in Admin > Basics. So altogether have:

* **Site title** = `<title>`
* **Homepage name** = `<h1>`
* **Email 'From' name** = `<whatever element is>`

So you're adding two fields and renaming the "Site name" field so it's more clear what it's filling.

**Comment by wion** [comment]
Granular control of content is good. ;)

Though you could get away with two fields and let the "Site title" fill the email "From" field too.

**Comment by wion** [comment]
Or maybe the **Site title** field goes into a "Metadata" extension, and the **Email 'From' name** goes into a "Notifications" extension.

**Comment by wion** [comment]
I was kind of hoping to see this addressed in beta6. I still [get complaints](https://discussion.csf.community/d/25-roll-call/25), understandably, about the lack of proper site identification in email notifications from the system, which is still due to the crude way Davis Header extension and core header markup work together. I know this is impacting impressions of your community, and not in a good way.

**Comment by tobscure** [comment]
Is this still an issue?

Since the use-case for this kind of granular control is probably not all that common, my preferred solution would be to:

* Set the forum title to whatever you want to appear in <title> and emails, and...
* Make a cosmetic change so that the <h1> has different content, either by:
  * Overriding <h1> text in CSS (i.e. http://stackoverflow.com/a/14261898), or...
  * Writing a simple extension with JavaScript that replaces the <h1> text.

**Comment by wion** [comment]
@tobscure,

I guess it's not an issue then.

We actually went back to a single bar to avoid the headache altogether. But we might try what you suggest in the future.

**Comment by tobscure** [comment]
Glad to hear it :)
