### ISSUE TITLE
Optimize JS+CSS filesize

### ISSUE THREAD

**Issue by tobscure** [flarum/core#99]
- [x] Use [external babel helpers](https://babeljs.io/docs/advanced/external-helpers/)
- [ ] ~~Consider subbing jQuery for [Zepto](http://zeptojs.com/) or [Cash](https://github.com/kenwheeler/cash)~~
- [ ] ~~Consider subbing moment.js for [timeago](http://timeago.yarp.com/)~~
- [x] Consider dropping all or parts of Bootstrap #103

**Comment by amdad** [comment]
IMHO, Bootstrap is not needed for anything here. It' just bloat CSS. Maybe some HTML markups can be used to more quickly recognize by devs and reuse the same markup when develop extensions frontend.  (like buttons etc.). 

Zepto or Cash would be great, but if this will not complicate too much develop own extensions. I don't know how much different and slimmed down in compare to jQuery they are.

**Comment by franzliedke** [comment]
I agree. We can do most things that Bootstrap gives us through SASS mixins etc.

**Comment by amdad** [comment]
Please, consider that jQuery can be loaded from Google CDN or jQuery CDN, so this can be faster in some way even then lighter alternative. Because in many cases it will be already loaded from browser cache. Not always packing main framework JS with own scripts is best way because of CDN today. 
Decision is up to you. Both ways has pros and cons.

**Comment by tobscure** [comment]
I think a massive CSS overhaul is on the cards at some point. Created an issue: #103

**Comment by tobscure** [comment]
Update: We really need to stick with moment.js because it solves the hard problem of date localization.

**Comment by amdad** [comment]
Originally I do not mention moment.js as a problem, nut not refreshing in real time (in browser) as a disadvantage. Of course proper multi-lang translation is much more important.

**Comment by tobscure** [comment]
Decided against Zepto, we just lose too much by not including jQuery (e.g. if an extension wants to use a jQuery plugin, there's the risk that it won't work with Zepto).

We're still using some of Bootstrap's JS – we may be able to slim it down in the future, but right now it's not important.

Still, the JS is currently sitting at about 96kB with no extensions – not bad!
