### ISSUE TITLE
Flarum API doesn't log errors

### ISSUE THREAD

**Issue by younes0** [flarum/core#991]
rights are okay though:

``` php
chmod 775 /www/icra/icrafl
chmod -R 775 /www/flarum/assets /www/flarum/storage
chgrp www-data /www/icra/icrafl
chgrp -R www-data /www/flarum/assets /www/flarum/storage
```

I also get 500 internal error pages
debug is set to true

**Comment by franzliedke** [comment]
I [recently implemented](https://github.com/flarum/core/commit/1a2174d61411117ed71736ab78ef10d01819d3f4) error logging - at least for the forum and admin server, not the API.

Are you running the latest dev-master?

**Comment by younes0** [comment]
No I'm using beta5 , but merging this commit made it work, thanks!

**Comment by franzliedke** [comment]
Okay, good. :)

I'll keep this open as a reminder to implement API error logging, though.
