### ISSUE TITLE
Markdown in post created via API not processed correctly

### ISSUE THREAD

**Issue by chimericdream** [flarum/core#993]
I am working on an extension that, ultimately, will allow admins to automatically generate discussion posts in their forum for new blog posts in an Atom RSS feed. However, I have noticed that I cannot include a Markdown (or HTML) link in the post body.

Here is the code making the request to create the discussion (the discussion is created successfully):

```php
$res2 = $client->request('POST', 'http://forumurl/api/discussions', [
    'headers' => [
        'Authorization' => 'Token ' . $auth->token
    ],
    'json' => [
        "data" => [
            "type" => "discussions",
            "attributes" => [
                "title" => "{$p['title']}",
                "content" => 'This discussion is in reference to the blog post: "[' . $p['title'] . '](' . $p['href'] . ')"'
            ],
            "relationships" => [
                "tags" => [
                    "data" => [
                        [
                            "type" => "tags",
                            "id" => "22"
                        ]
                    ]
                ]
            ]
        ]
    ]
]);
```

The resulting discussion's body looks as follows:

```
This discussion is in reference to the blog post: "[Blog post title]()"
```

I suspect that the `[]` and `()` characters are being escaped at some point during the creation of the discussion, likely as part of a sanitization process. I looked through the API, and the best guess I could come up with is that this piece of code in `src\API\Controller\CreateDiscussionController.php` (line 70-72)

```php
        $discussion = $this->bus->dispatch(
            new StartDiscussion($actor, array_get($request->getParsedBody(), 'data', []), $ipAddress)
        );
```

However, I can't find where the `$request` variable is being initialized, and the type hint in the method is only an interface, so I can't determine whether this is the spot where the data gets messed up.

_Note:_ I am using the Guzzle library to make the requests to the API.

**Comment by franzliedke** [comment]
From a quick glance, the code looks okay.

Can you please let us see the complete JSON that your code generates?

**Comment by chimericdream** [comment]
Never mind. It was an ID-10-T error. I wasn't properly setting the URL in the first place, so when it got sent over the wire, it wasn't valid Markdown.

**Comment by chimericdream** [comment]
@franzliedke Thanks for the help. I didn't realize my mistake until I actually looked at the request payload.
