### ISSUE TITLE
Confirming accounts doesn't work

### ISSUE THREAD

**Issue by dav-is** [flarum/core#994]
Steps to reproduce:
1. Create a new account (see the "your account isn't confirmed" message)
2. Refresh (your account is confirmed and the message disappears)

Note: It does send a confirmation email and clicking the confirm link in your email says "invalid confirmation link".

It also creates the email key in the DB, but it immediately disappears.

**Comment by tobscure** [comment]
Can't seem to reproduce. Is this using latest dev-master?

**Comment by dav-is** [comment]
Also cannot reproduce. Must have been fixed somehow.

**Comment by paulodamian** [comment]
I have this problem, or something very similar.

I just registered on https://discuss.flarum.org
Got the email, but when I click the link the page says: Invalid confirmation token
If I click the resend confirmation email link, it says "You do not have permission to do that."

I was just registering to ask a few questions about forum speed before try it by my self

**Comment by tobscure** [comment]
Yeah I can reproduce now. In fact, you need only sign up a new account and then reload the page after a few seconds to see that the account has magically been activated – somehow the activation URL is being visited without ever opening the email!

I did some investigation and I think that SparkPost, the SMTP service we use on discuss.flarum.org, may be the culprit... I've opened a ticket with them so we'll see if they can offer any explanation. I don't think this is a bug with Flarum, but I'll reopen the issue as it's definitely something we need to solve on discuss.flarum.org soon.
