### ISSUE TITLE
Tags / Posting: Unable to post unless the "General Tag" is selected

### ISSUE THREAD

**Issue by MrSleeps** [flarum/core#998]
Hey, I've just installed Flarum, been having a play. Came across an issue, when I try to post a new Discussion I am unable to click OK on the select a tag modal, unless I select "General" (I have other tags set up).

I've got no extensions running other than the default ones that come with it.

**Comment by Kakifrucht** [comment]
Seems like something specific to your setup. Did you try to ask for support on the support forums (discuss.flarum.org)? I'm not sure how Flarum handles this exactly, but I think that this issue tracker is for confirmed bugs and not for support.

**Comment by MrSleeps** [comment]
Hmm, it's a straight out of the box install tho?

**Comment by MrSleeps** [comment]
Weird one, just reinstalled it and it works fine now?
